pkg/storage/stores/shipper/indexshipper/tsdb/builder.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/chunk_test.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/index.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/index_test.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/writer.go
In preparation for creating stateless ingesters, this PR adds support for TSDBs to be created by using memory as the backing temporary store rather than disk. This paves the way towards an easier operating model which doesn't require disks.
Note: this adds _support_ but doesn't use it in any existing code paths. I've essentially refactored the TSDB creator to use an interface which can be satisfied by disk or memory. The old code paths will continue to use disks for now to minimize changes.
```
$ cmp 1730487398326535000-compactor-1000-3000-bd34932f.tsdb 1730487451442167000-compactor-1000-3000-bd34932f.tsdb
```
=> feat(TSDB): allow tsdb index creation in memory only

operator/bundle/openshift/metadata/properties.yaml
Fixes the maximum OpenShift version for the upcoming release.
[LOG-6333](https://issues.redhat.com/browse/LOG-6333)
**Checklist**
=> fix(operator): Fix maximum OpenShift version

pkg/storage/stores/shipper/bloomshipper/fetcher.go, pkg/storage/stores/shipper/bloomshipper/fetcher_test.go
A lot of CPU time is spent in decoding the meta files, which are JSON files.
See this CPU profile from a trace:
[`github.com/json-iterator/go`][1] is a drop-in replacement for the Go stdlib `encoding/json`.
**Benchmark**
```
$ benchstat old.txt new.txt 
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/v3/pkg/storage/stores/shipper/bloomshipper
│   old.txt    │               new.txt                │
│    sec/op    │    sec/op     vs base                │
_Fetcher_processMetasCacheResponse-8   4.318µ ± 12%   2.095µ ± 49%  -51.49% (p=0.000 n=10)
│   old.txt   │              new.txt               │
│    B/op     │    B/op     vs base                │
_Fetcher_processMetasCacheResponse-8   1301.0 …
```
=> perf(blooms): Replace JSON lib for encoding/decoding metas

operator/docs/operator/release.md, operator/release-please-config.json
bootstrap directive was added to because grafana had used a specific commit that makes release-please release with a specify version. Bootstrap was being used to avoid release-please from looking so back in the commit history. Since this was back in March we should now be good
**Checklist**
=> chore(operator): removed bootstrap directive from release-please-config

pkg/bloombuild/planner/planner.go
Tables that have not been fully compacted yet will have multi-tenant TSDBs for which the tenant is "" (coming `tsdbStore.UsersForPeriod` and `indexStorageClient.ListFiles`)
In this PR we update the planner to skip these multi-tenant TSDBs.
I though about fixing this at the `indexStorageClient.ListFiles` level but I think it's relatively risky given it's is used in the compactor.
**Checklist**
=> fix(blooms): Skip multi-tenant TSDBs during bloom planning

pkg/bloomgateway/processor.go, pkg/bloomgateway/stats.go
We already log the number of processed blocks, so we also want to know the number of skipped blocks, because they have not been available. This will give better insights on a per-query basis, additionally to the metric of overall skipped unavailable blocks `loki_bloom_gateway_blocks_not_available_total`.
**Checklist**
=> chore(blooms): Add number of skipped bloom blocks to stats-report log line

docs/sources/alert/_index.md
When scrolling alerting documentation, ruler remote evaluation is not mentioned, and for me, it solved many issues, so it would be great to have it in alerting docs.
Fixes #14441
**Checklist**
=> docs(alert): clarify remote rule evaluation

docs/sources/alert/_index.md
(cherry picked from commit d63fbeddff238bffdf0abd8866a582049ea37058)
Manual backport of #14481 because `lokitool` wasn't released until Loki 3.1, so reference to `cortex-tool` after line 208 should remain.
=> docs(alert): clarify remote rule evaluation (#14481)

operator/internal/manifests/openshift/otlp.go
This PR adds another log attribute to the default set of OTLP attributes for OpenShift. This attribute is used by the current visualization to show the log severity and filter for it. This is a workaround for the current version until the visualization supports the new label (`severity_text`).
Fixes [LOG-6324](https://issues.redhat.com/browse/LOG-6324)
**Checklist**
=> fix(operator): Add log attribute for level to structured metadata

.github/workflows/operator-release-please.yml
Adds missing workflow to publish release images for the Loki Operator on Docker Hub.
**Checklist**
=> fix(operator): Publish images on docker hub upon release

pkg/bloombuild/builder/builder.go
Before this PR, when the planner restarted, all builders errored and restarted as well. This happened becvause even though we had a backoff mechanism, it was not reset when we could connect at least once succesfully. 
This PR fixes this so builders just retry connecting to the planner again. We handle the EOF error we get when the planner disconnects to reset the backoff and start again.
Here's an example:
**While the planner is down, there are no restarts**
**But we do print errors**
We did this test using this backoff config:
```jsonnet
bloom_build+: {
builder+: {
backoff_config+: {
min_period: '1s',
max_period: '1m',
},
},
},
```
**Checklist**
- **Note** that Promtail is considered to be feature complete, and …
=> fix(blooms): Do not restart builders when planner disconnects

docs/sources/shared/configuration.md, pkg/loki/loki.go, pkg/loki/modules.go
This commit removes initialization of RF-1 components from `pkg/loki` so we can start to delete old RF-1 code.
**Checklist**
=> chore: remove initialization of RF-1 components from pkg/loki

docs/sources/shared/configuration.md, pkg/loki/loki.go, pkg/loki/modules.go
=> chore: revert "chore: remove initialization of RF-1 components from pkg/loki"

pkg/logcli/query/query.go
When getting data from object storage, we're first checking for the `exists` return and only then for the error returned. Everytime an error is returned an `exists=false` is also returned, and that is taken more precedence than the error itself.
**Checklist**
=> fix: logcli: Check for errors before checking for `exists` when fetching data

pkg/storage/stores/shipper/indexshipper/storage/client.go
Found an unnecessary `Seeker` constraint and am removing it so I don't have to impl unnecessary methods elsewhere when using this.
=> refactor(indexshipper): removes unnecessary seeker impl from index storage client

docs/sources/shared/configuration.md, pkg/loki/loki.go, pkg/loki/modules.go
This pull request removes the initialization of the Querier RF-1 component as it is no longer used.
**Checklist**
=> chore: remove initialization of Querier RF-1

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/community/manager_auth_proxy_patch.yaml
The registry gcr.io/kubebuilder/kube-rbac-proxy is outdated changed to up to date registry https://github.com/brancz/kube-rbac-proxy/issues/280
Full discussion in https://github.com/kubernetes-sigs/kubebuilder/discussions/3907
**Checklist**
=> fix(operator): update kube-rbac-proxy to upstream registry

docs/sources/shared/configuration.md, pkg/loki/loki.go
This pull request removes initialization of the RF-1 client as it is no longer used.
**Checklist**
=> chore: remove initialization of RF-1 client

docs/sources/shared/configuration.md, pkg/loki/loki.go
This pull request removes initialization of metastore code as it is no longer used.
**Checklist**
=> chore: remove initialization of metastore

pkg/bloombuild/common/tsdb.go
Fixes revive lint errors:
```
> pkg/bloombuild/common/tsdb.go:138:47: unused-parameter: parameter 'chks' seems to be unused, consider removing or renaming it as _ (revive)
>            func(_ labels.Labels, fp model.Fingerprint, chks []index.ChunkMeta) (stop bool) {
>                                                          ^
```
**Checklist**
=> chore(blooms): fix lint

nix/packages/loki.nix
[This](https://github.com/grafana/loki/pull/14820) PR updated some packages for lambda-promtail, resulting in subsequent [errors](https://github.com/grafana/loki/actions/runs/11726566061/job/32665508367?pr=14827) when doing the nix check.
This PR adjusts the checksum to the proper value.
nix results before this PR:
```
% nix build
error: hash mismatch in fixed-output derivation '/nix/store/z9p2ls5wj3ga76315c6zfpqzj39hqkvk-lambda-promtail-275b768b-go-modules.drv':
specified: sha256-GM7tXlN7t7c3EHtF4vMzhINIZm+HQpyMYVAv3Dtiny8=
got:    sha256-fG+AJfniGJy9fpD2Jluh7N2FDYt9LCjXCVoWktuvus0=
error: 1 dependencies of derivation '/nix/store/dlsvh3gi9kjhyrawfycnrj1apcg0vn25-lambda-promtail-275b768b.drv' failed to build
error: 1 dependencies of derivation …
```
=> chore: Update lambda-promtail nix checksum

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/community-openshift/kustomization.yaml, operator/config/overlays/community-openshift/manager_resource_reqs_patch.yaml, operator/config/overlays/community/kustomization.yaml, operator/config/overlays/community/manager_auth_proxy_patch.yaml, operator/config/overlays/community/manager_resource_reqs_patch.yaml, operator/config/rbac/role.yaml, operator/docs/operator/compatibility.md, operator/internal/controller/loki/lokistack_controller.go
Fixes warnings as mentioned in the latest release pipeline reports:
- k8s-operator-hub/communit-operators: [0.7.0](https://github.com/k8s-operatorhub/community-operators/pull/5249#issuecomment-2461701309)
- redhat-openshift-ecosystem/community-operators-prod: [0.7.0](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5460#issuecomment-2462091908)
- Leaving the migration to File-Based-Catalog for a separate PR as per instructions need careful considerations:  https://redhat-openshift-ecosystem.github.io/operator-pipelines/users/fbc_onboarding/
- To run the redhat-openshift-ecosystem static tests please consider following the [official …
=> fix(operator): Fix operator release pipeline warnings

pkg/kafka/partition/reader.go, pkg/kafka/partition/reader_test.go
This fixes an edge case where there are no new records available in Kafka during start up, which would cause a deadlock.
It also ensures we don't process the last comitted offset again at startup because we already processed and committed it.
* I also added a 30 second timeout & log line on each Poll call, which is very useful to debug why Loki isn't starting up sometimes!
**Checklist**
=> fix: Ensure partition-reader starts up correctly

docs/sources/shared/configuration.md, pkg/loki/common/common.go, pkg/loki/config_wrapper.go
I found the path.prefix flag useful for running multiple Loki's locally. It exists as a yaml already, so I just added the flag.
Also configured the kafka ingester KV store for non-memberlist backends, which should be configurable. It is useful for running locally too.
=> fix: Add flags for path & configure kafka for non-memberlist kv store

go.mod, go.sum, pkg/ruler/rulestore/bucketclient/bucket_client.go, pkg/storage/bucket/object_client_adapter.go, pkg/storage/bucket/prefixed_bucket_client.go, pkg/storage/bucket/sse_bucket_client.go, vendor/github.com/thanos-io/objstore/CHANGELOG.md, vendor/github.com/thanos-io/objstore/README.md, vendor/github.com/thanos-io/objstore/inmem.go, vendor/github.com/thanos-io/objstore/objstore.go, vendor/github.com/thanos-io/objstore/prefixed_bucket.go, vendor/github.com/thanos-io/objstore/providers/azure/azure.go, vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go, vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go, vendor/github.com/thanos-io/objstore/providers/s3/s3.go, vendor/github.com/thanos-io/objstore/providers/swift/swift.go, vendor/github.com/thanos-io/objstore/testing.go, vendor/github.com/thanos-io/objstore/tracing/opentracing/opentracing.go, vendor/modules.txt
With https://github.com/thanos-io/objstore/pull/63 we now don't need to make an extra call to get the Attributes
**Checklist**
=> feat(thanos): make use of the new function IterWithAttributes

pkg/querier/http.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/roundtrip_test.go
If a query exceeds it's configured limit it returns an error-message.
This message currently references the (invalid) setting `max_entries_limit`, instead `max_entries_limit_per_query` should be used.
**Checklist**
=> fix(querier): show correct setting in error message

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/config.go, pkg/bloomgateway/processor.go, pkg/bloomgateway/processor_test.go, pkg/bloomgateway/worker.go
In case bloom blocks are small, they could be downloaded synchronously to avoid missing blocks on cold start.
This is an undocumented setting.
**Checklist**
=> chore(blooms): Add setting to fetch bloom blocks async or synchronously

docs/sources/shared/configuration.md, pkg/bloombuild/planner/config.go, pkg/bloombuild/planner/planner.go, pkg/bloombuild/planner/planner_test.go, pkg/bloombuild/planner/queue/config.go, pkg/bloombuild/planner/queue/queue.go, pkg/bloombuild/planner/task.go
We are going to wrap the queue to store tasks in the filesystem. We start by extracting the queue into a new pkg. Note that we the current logic is the same as before. We'll implement the disk storage in a followup PR.
**Checklist**
=> refactor(blooms): Extract planner queue into pkg

pkg/bloombuild/planner/strategies/chunksize.go
We saw the following errors when using the `split_by_series_chunks_size` strategy:
```
ts=2024-11-11T13:49:22.314294574Z caller=spanlogger.go:116 user=fake level=error msg="failed downloading chunks" err="failed to load chunk '29/70e445e35a08d865/19312b76db3:1931326dfdf:141bf2e0': failed to get s3 object: NoSuchKey: ..."
```
Arguments for `ForSeries` callback should be captured as the chunks slice is reused on every call.
https://github.com/grafana/loki/blob/18cef217fc4accce30d18df5fb51e354b961dcf3/pkg/storage/stores/shipper/indexshipper/tsdb/single_file_index.go#L168-L169
**Checklist** …
=> fix(blooms): Copy chunks from ForSeries

pkg/ingester/recovery.go, pkg/ingester/recovery_test.go, pkg/ingester/stream.go, pkg/ingester/wal.go
Fixes an edge case in WAL replay where log lines could be lost on WAL replay.
We previously reset the stream counter to 0 after a successful WAL replay. This is a problem if the ingester restarts again before the WAL content is flushed, as we will discard any new WAL entries - anything received after the previous replay - as a duplicate instead of a new log line.
e.g. in this scenario, each startup will create a new segment file in the WAL. After replay, we'd ingest `1A, 1B, 1C, 2D` but `2A, 2B, 2C` will be classed as duplicates of 1A, 1B, and 1C because they have the same entry count.
**Checklist** …
=> fix: Ensure successive WAL replays don't overwrite each other

docs/sources/setup/install/helm/deployment-guides/aws.md, docs/sources/setup/install/helm/install-microservices/_index.md
Removed manually persistence mapping in AWS deployment as not required. Also at the recommendation of the community made ZoneAwareReplication false to save costs.
**Checklist**
=> docs: Removed manual persistence mapping, turned off ingester zone

.github/workflows/scripts/helm-weekly-release.sh
This is a small fix to the weekly helm release script to correctly tag the canary and provisioner images as well.
Fixes https://github.com/grafana/loki/actions/runs/11714266494/job/32658955775
**Checklist**
=> ci: tag provisioner and canary images in weekly helm release

docs/sources/shared/configuration.md, pkg/bloombuild/planner/config.go, pkg/bloombuild/planner/planner_test.go
The docs for min and max offsets are a bit difficult to reason about. This PR improves them with examples and sets the default min offset to 0 (build from today), and the max to 1 (build till tomorrow).
We also add a test for the tables iterator.
**Checklist**
=> fix: Improve docs for min and max table offsets

pkg/bloombuild/planner/planner.go
Followup for https://github.com/grafana/loki/pull/14770. There were still empty tenants. Due to how we initialise and populate the slice.
**Checklist**
=> fix(blooms): Fix tenants slice on loadTenantTables

pkg/distributor/distributor.go, pkg/kafka/client/writer_client.go
Found some metrics in dev looking like this `_kafka_loki_produce_requests_total`
cc @grobinson-grafana  Not sure if those were used in a dashboard but that will break/fix it :)
**Checklist**
=> chore: Fix kafka producer metrics names

pkg/storage/bucket/azure/bucket_client.go, pkg/storage/bucket/client.go, pkg/storage/bucket/gcs/bucket_client.go, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/sse_bucket_client_test.go, pkg/storage/bucket/swift/bucket_client.go
Thanos objstore [metrics](https://github.com/thanos-io/objstore/blob/main/objstore.go#L483) do not track the status code of operations. `objstore_bucket_operation_failures_total` only reports if an operation failed, but nothing more. 
this pr adds a new metric `loki_objstore_bucket_transport_requests_total` to observe the total requests by status code and the http method. Since we are directly wrapping the transport we cannot partition the metric by the object store operation type (get, list...) instead this metric reports the http method.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection …
=> feat(thanos): add new metric to track status codes

pkg/logqlmodel/stats/context.go, pkg/storage/stores/series/series_index_gateway_store.go, pkg/storage/stores/series/series_index_gateway_store_test.go
The `metrics.go` log line contains the `index_used_bloom_filter` field, which was not set to `true` when the query used bloom filters in the `GetChunkRef()` call on the index gateway.
**Checklist**
=> fix: Correctly propagate index stats to metrics.go log line

.github/renovate.json, .github/renovate.json5
This PR attempts to align the renovate configuration to our end goal, with respect to the `main` branch.
Notably it:
- Separates out Helm updates, so they are not mixed with Dockerfile updates
- Explicitly sets Helm updates to not be automerged, since they require documentation updates
- Separates out lambda-promtail updates so they are not merged with other Go updates, since they require Nix updates
- Explicity sets the lamba-promtail updates to not be automerged
- Disables Renovate updates for the Operator code
- Explicitly sets GitHub actions to not be automerged
- Converts the configuration to JSON5, so that each rule can be annotated and explained …
=> chore: Configure renovate to be more in line to the end state

pkg/lokifrontend/frontend/v1/frontend_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go
#14350 introduced detected field values, and refactored our routing logic. In doing so I left out the `/api` bit in `/api/prom/label/{name}/values` as referenced [here](https://grafana.com/docs/loki/latest/reference/loki-http-api/#deprecated-endpoints). This fixes that mistake.
**Checklist**
- [ x] If the change is deprecating or removing a configuration option, update the `deprecated-config.yaml` and …
=> fix: legacy label endpoint route

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/release-workflows.jsonnet, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/workflows/images.yml, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, Makefile, clients/cmd/docker-driver/Dockerfile, docs/sources/send-data/docker-driver/_index.md, pkg/querier/queryrange/roundtrip_test.go
Add ARM64 build and release of the Docker driver in Drone pipeline
Fixes #5682
I would have loved to have a unified x64 and arm64 build but apparently Docker drivers does not support multi arch images. So instead I went with tweaking the build steps to allow cross building the image for ARM64 and added the instructions to do so in `drone.yml`.
It seems there's a drift in the images published on Docker Hub versus the one documented for use. I updated it here but this might be wrong.
**Checklist**
=> feat: build the Docker Driver for arm64

.github/renovate.json5
The previous [PR](https://github.com/grafana/loki/pull/14943) somehow turned on "digest" updates.  This PR attempts to address this, as well as fencing off the `operator/api/loki/go.mod` file along with the `operator/go.mod` file.
**Checklist**
=> chore: Renovate - Turn off digest updates

.github/renovate.json5
The previous [PR](https://github.com/grafana/loki/pull/14948) successfully turned of digest updates for the majority of the `go.mod` files.  This PR turns them off for lambda-promtail, helm, and GH action updates as well.
**Checklist**
=> chore: Turn off digest updates for lambda-promtail, helm, and GH actions

pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go
Currently [the label set](https://github.com/grafana/loki/blob/main/pkg/loghttp/push/push.go#L290-L293) passed to [usage trackers](https://github.com/grafana/loki/blob/main/pkg/loghttp/push/usage_tracker.go#L13) in `push.ParseLokiRequest` [does not include the `service_name` label](https://github.com/grafana/loki/blob/main/pkg/loghttp/push/push.go#L269).
This label could be useful at query time for usage metrics and shouldn't affect `RetentionPeriodFor` for a tenant so this PR keeps it.
N/A
N/A
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As …
=> fix: Keep the service_name label after discovery in push.ParseLokiRequest before calculating retention and passing to the usage tracker

cmd/logcli/main.go, pkg/logcli/client/client.go
This is enabled with the --envproxy flag. This is opt in because for a very small subset of users, it may cause a breaking change. If a user has a proxy url configured  but also sets a HTTP_PROXY variable, then this will cause an error in the request.
HTTP_PROXY is a standard approach to configuring CLIs.
In my use-case, it allows me to use an internal tool to do proxy oauth so I can use logcli via CLI behind auth.
Fixes #11742
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug …
=> feat: add opt-in support for ProxyFroomEnvironment in logcli (#11742)

.github/workflows/helm-ci.yml
Enable `DEBUG` log level on the super linter to figure out what's wrong with helm linting.
**Checklist**
=> ci: set helm-lint log level to debug

pkg/bloombuild/builder/builder.go, pkg/bloombuild/builder/builder_test.go, pkg/bloombuild/builder/config.go
The per-tenant `bloom_build_builder_response_timeout` limit was only enforced in the planner. We now apply it on the builder side as well.
**Checklist**
=> feat(blooms): Apply task timeout in bloom builder

docs/sources/setup/upgrade/_index.md
=> docs: Add upgrade guide for new bloom blocks

docs/sources/get-started/labels/structured-metadata.md, docs/sources/query/query_accceleration.md
Makes small updates to the Structured Metadata and Query Acceleration topics to support the Loki 3.3 version of Query acceleration with Blooms and the GA of Explore Logs.
=> docs: update topics for Blooms

docs/sources/get-started/labels/structured-metadata.md, docs/sources/operations/bloom-filters.md
manual backport of #15058 to the 3.3 branch.
=> docs: Clarifying info about structured metadata, blooms (#15058)

pkg/blockbuilder/controller.go, pkg/kafka/partition/committer.go, pkg/kafka/partition/committer_test.go, pkg/kafka/partition/reader.go, pkg/kafka/partition/reader_service.go, pkg/kafka/partition/reader_test.go, pkg/loki/modules.go
Ths is a nit, but I think we should avoid using type information in the type definition, this commit renames ReaderIfc to Reader and Reader to StdReader.
**Checklist**
=> chore: Remove ifc from interface names

pkg/pattern/drain/drain.go, pkg/pattern/drain/drain_test.go, pkg/pattern/drain/line_tokenizer.go, pkg/pattern/drain/line_tokenizer_test.go, pkg/pattern/drain/metrics.go, pkg/pattern/metrics.go, pkg/pattern/stream.go
This adds a `lines_skpped` metric to the pattern ingesters, which counts log lines that have been skipped for pattern ingestion. This also adds logic to skip lines with too many (> 50) tokens.
Reasons for skipping:
- too few tokens
- too many tokens
- line too long
Fixes #14882
**Checklist**
=> feat: add lines skipped metric to pattern ingesters

docs/sources/get-started/labels/structured-metadata.md, docs/sources/operations/bloom-filters.md
=> docs: Update Blooms docs

pkg/kafka/partition/reader_service.go
=> chore: separate usage of partition owner gauge

pkg/logql/log/pipeline.go
`offsetsBuf` wasn't actually being used anywhere, looks like this just got missed in a refactor commit as part of https://github.com/grafana/loki/pull/13983
cc @MasslessParticle @ashwanthgoli
=> chore: remove minor dead code that was missed in a PR review

pkg/kafka/partition/reader_service.go
=> chore: Add context to logger once

pkg/kafka/partition/reader_service.go
This commit updates reader_service.go to use a separate variable to track the consume offset instead of mutating the last committed offset. I found this makes the code easier to follow as the last committed offset does not change.
**Checklist**
=> fix: Use separate variable to track the consume offset

cmd/loki/loki-local-config.yaml
Fixes https://github.com/grafana/loki/issues/15039
relates to https://github.com/Homebrew/homebrew-core/pull/198450
**Checklist**
=> fix: remove `enabled` field in loki-local-config.yaml

pkg/kafka/partition/reader_service.go
Use `KafkaEndOffset` instead of `-1`. These have the same value.
**Checklist**
=> fix: use KafkaEndOffset instead of -1

pkg/kafka/partition/reader_service.go
This commit adds a debug level log line that emits the consumption offset of a starting ingester. This should help us solve a bug where sometimes an ingester will be waiting for records in the inactive state, which will never arrive as it is inactive.
**Checklist**
=> chore: add a log line for consume offset

pkg/kafka/partition/reader_service.go
This is a small chore to move the catch up logic to `processConsumerLag`. We can do this as it does not depend on any variables in `starting` other than the context.
**Checklist**
=> chore: move catch up logic to processConsumerLag

docs/sources/get-started/labels/structured-metadata.md, docs/sources/operations/bloom-filters.md, docs/sources/query/query_accceleration.md
Further tweaks to the Loki docs to support Public Preview of Bloom Filters before I mount files into the Cloud Docs.
* Standardized the Warning on the two Blooms topics 
* Updated the prerequisites on the Query topic for Cloud Docs
* While making these updates I realized that we never explicitly documented how to enable structured metadata, so added that too.
=> docs: Updates to support public preview of Blooms in Cloud

go.mod, go.sum, pkg/distributor/http.go, pkg/distributor/http_test.go, pkg/loghttp/push/otlp_test.go, pkg/loghttp/push/push.go, vendor/modules.txt
Backporting https://github.com/grafana/loki/pull/15097 to k229
**Checklist**
=> chore: Backport 15097 to k229

docs/sources/setup/install/helm/deployment-guides/aws.md
(cherry picked from commit 06fff99736ab9aa3ee900edbf8120eacbbb925b3)
Manual backport of #14813 to the 3.2 branch.
=> docs: Added video and fixed config value (#14813)

pkg/pattern/aggregation/metrics.go, pkg/pattern/aggregation/push.go, pkg/pattern/aggregation/push_test.go, pkg/pattern/ingester.go
Fixes duplicate metric registration in metric aggregation in pattern ingesters. I used `promauto.With(reg)` along with `m.reg.MustRegister(...` that resulted in duplicate registration
**Checklist**
=> fix(metric_aggregation): Fix duplicate metrics registration

clients/cmd/promtail/Dockerfile
The package has been added to the Docker image with PR #11711 with the intention to support the Docker healthcheck.
However, to reduce the attack surface of our Docker images, we want to keep them as slim as possible. The current version of Promtail (3.3.0) for example contains a wget version with vulnerability [CVE-2024-38428](https://security-tracker.debian.org/tracker/CVE-2024-38428).
The healthcheck can be achieved by other means, e.g.
1. Extend the `grafana/promtail` base image and add `wget` using `apt install wget`
https://github.com/grafana/loki/issues/11590#issuecomment-2106037181
3. Use low-level `/dev/tcp/127.0.0.1:9080` to establish a connection and check the exit code
https://github.com/grafana/loki/issues/11590#issuecomment-2333481326 …
=> chore!: Remove `wget` from Promtail docker image

pkg/kafka/partition/committer.go
This commit fixes an incorrect error check in `autoCommitLoop`.
**Checklist**
=> fix: incorrect error check in autoCommitLoop

clients/pkg/logentry/metric/metricvec.go, clients/pkg/logentry/stages/decolorize.go, clients/pkg/logentry/stages/drop.go, clients/pkg/logentry/stages/eventlogmessage.go, clients/pkg/logentry/stages/extensions.go, clients/pkg/logentry/stages/geoip.go, clients/pkg/logentry/stages/json.go, clients/pkg/logentry/stages/limit.go, clients/pkg/logentry/stages/match.go, clients/pkg/logentry/stages/metrics.go, clients/pkg/logentry/stages/metrics_test.go, clients/pkg/logentry/stages/multiline.go, clients/pkg/logentry/stages/pack.go, clients/pkg/logentry/stages/pipeline.go, clients/pkg/logentry/stages/sampling.go, clients/pkg/logentry/stages/stage.go, clients/pkg/logentry/stages/structuredmetadata.go, clients/pkg/promtail/targets/file/filetarget.go, clients/pkg/promtail/targets/file/filetarget_test.go, docs/sources/send-data/promtail/configuration.md, docs/sources/send-data/promtail/stages/metrics.md
Currently, Grafana Agent uses [k190](https://github.com/grafana/loki/commits/k190/). I am working on upgrading it to a new Prometheus version, but in order to do that I have to update its Loki dependency too. The minimum Loki version which I can update it to is [k195](https://github.com/grafana/loki/commits/k195/).
Unfortunately, k195 is missing two bugfixes which were cherry-picked onto k190. I am raising this PR so that I can cherry-pick 495d226c09db3fc7a and cef4c2826b4b1d3dd2 onto 195 too. 
I hope I can also upgrade Agent's Loki dependency to a much more recent one in the near future.
=> chore: Patch k195 with bugfixes for a Grafana Agent

pkg/querier/queryrange/limits_test.go
The test case is flaky. Recent failure on release branch: https://github.com/grafana/loki/actions/runs/12049536800/job/33596506996?pr=15148
=> chore: Fix flaky `TestAcquireWithTiming` test

docs/sources/setup/upgrade/_index.md
If the `service_name` label exists, it's not overwritten
**Checklist**
=> docs: update _index.md, If the `service_name` label exists, it's not overwritten

docs/sources/operations/query-acceleration-blooms.md
Manual backport of #14544 due to file name change from #14555.
=> docs: Update query-acceleration-blooms.md (#14544)

Makefile
Use existing variables for image names in the make targets,
e.g. replace `$(IMAGE_PREFIX)/loki:$(IMAGE_TAG)` with `$(LOKI_IMAGE)`
=> chore: Replace image names with variable names in Makefile

docs/sources/shared/configuration.md, pkg/querier/ingester_querier.go, pkg/querier/ingester_querier_test.go
Fixes a race condition between the Query and GetChunkIDs calls when using partition-ingesters.
The bug occurs when first Querying logs from an ingester that just flushed a chunk (returning 0 logs), followed by calling GetChunkIDs on an ingester that has not flushed a chunk (returning 0 chunk refs). The bug manifests by returning 0 results when some log lines do exist in other ingesters.
* This solution is to query all the available ingesters for GetChunkIDs in order to make sure we receive any recent chunks that have just been flushed. 
* There is still a small window where a shutting down ingester would flush all it's chunk and then be unavailable during restart to serve the GetChunkIDs request. This is the same with the classic ingesters and would …
=> fix: Mitigate ingester race between Query & GetChunkIDs

cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile
This PR removes the inclusion of glibc into most of the Docker images created by the Loki build system.
It excludes:
- The loki-canary BoringCrypto image, as it requires `glibc` as part of the `CGO` dependency
- The debug image for Loki, as it installs `dlv`, which in turn requires `glibc`
This removes an unneeded dependency, which adds some low severity CVE items into the Docker images that we generate.
**Checklist** …
=> chore(deps): Move from base-nossl to static

Makefile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross
This PR changes promtails base image from `debian:12.8-slim` to `ubuntu:noble-20241015`, `noble` being ubunutu's most recent lts version. The current debian base image has a lot of security CVEs that won't be updated, while ubuntu updates packages much more regularly.
Just as a quick example, the result of a trivy scan on the promtail image with debian base gives `Total: 79 (UNKNOWN: 0, LOW: 59, MEDIUM: 14, HIGH: 5, CRITICAL: 1)` while the trivy scan for the promtail image with ubunutu base results in `Total: 15 (UNKNOWN: 0, LOW: 7, MEDIUM: 8, HIGH: 0, CRITICAL: 0)`
~~EDIT: Moved to draft until I've confirmed the new image can still grab systemd/journal logs~~
EDIT: Couldn't trace through the makefile/Dockerfile what needs to be set for the image to build with promtail and cgo locally, …
=> chore: switch promtails base image from debian to ubuntu

Makefile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross
Backport 4d9c5bb20aba82087d87836d88d2260f7dd913ac from #15195
---
This PR changes promtails base image from `debian:12.8-slim` to `ubuntu:noble-20241015`, `noble` being ubunutu's most recent lts version. The current debian base image has a lot of security CVEs that won't be updated, while ubuntu updates packages much more regularly.
Just as a quick example, the result of a trivy scan on the promtail image with debian base gives `Total: 79 (UNKNOWN: 0, LOW: 59, MEDIUM: 14, HIGH: 5, CRITICAL: 1)` while the trivy scan for the promtail image with ubunutu base results in `Total: 15 (UNKNOWN: 0, LOW: 7, MEDIUM: 8, HIGH: 0, CRITICAL: 0)`
~~EDIT: Moved to draft until I've confirmed the new image can still grab systemd/journal logs~~
EDIT: Couldn't trace through the makefile/Dockerfile what needs …
=> chore: switch promtails base image from debian to ubuntu (backport release-3.2.x)

clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross
Backport 4d9c5bb20aba82087d87836d88d2260f7dd913ac from #15195
---
This PR changes promtails base image from `debian:12.8-slim` to `ubuntu:noble-20241015`, `noble` being ubunutu's most recent lts version. The current debian base image has a lot of security CVEs that won't be updated, while ubuntu updates packages much more regularly.
Just as a quick example, the result of a trivy scan on the promtail image with debian base gives `Total: 79 (UNKNOWN: 0, LOW: 59, MEDIUM: 14, HIGH: 5, CRITICAL: 1)` while the trivy scan for the promtail image with ubunutu base results in `Total: 15 (UNKNOWN: 0, LOW: 7, MEDIUM: 8, HIGH: 0, CRITICAL: 0)`
~~EDIT: Moved to draft until I've confirmed the new image can still grab systemd/journal logs~~
EDIT: Couldn't trace through the makefile/Dockerfile what needs …
=> chore: switch promtails base image from debian to ubuntu (backport release-2.9.x)

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Adding a per-tenant metric for when a tenant has structured metadata sanitized at ingestion time. This would be less spammy than a log line, and while the `tenant` label could be high cardinality it's unlikely to be as the % of users using SM and sending SM that has invalid characters is likely low.
Some of the discussion around https://github.com/grafana/loki/pull/15113 has been that the query time sanitization of the SM name and value (value would be sanitized in that PR, name sanitization is already in place) is that query time sanitization is expensive, and we'd like to move that functionality to be on a per-tenant basis.
The goal here is to inform us which users have been sending invalid SM so that we modify the query time SM sanitization code blocks so that they're only run on a …
=> feat: Add a metric ingestion time SM sanitization

pkg/blockbuilder/builder/controller.go, pkg/blockbuilder/builder/slimgester.go, pkg/blockbuilder/scheduler/strategy_test.go, pkg/kafka/partition/committer.go, pkg/kafka/partition/committer_test.go, pkg/kafka/partition/offset_manager.go, pkg/kafka/partition/reader.go, pkg/kafka/partition/reader_service.go, pkg/loki/modules.go
Splits the existing kafka Reader interface and implementations into smaller parts:
- Reader that only supports `Poll` and a seek method
- OffsetManager to read partition offsets and manage commits
This is needed for read-only components such as block builders that only poll records from a single or multiple partitions, they do not read offsets or commit messages.
`readerMetrics` is now a global that is registered during init, this is to avoid duplicate registration when multiple clients are created.
**Checklist** …
=> chore: split kafka reader ifc into reader and offset manager

pkg/kafka/partition/reader.go, pkg/kafka/partition/reader_service.go, pkg/loki/modules.go
Partition readers can be instantiated multiple times once per each consumer. But this would cause panics as a result of duplicate reader metric registration. This pr updates the constructor to allow callers to pass down metrics.
**Checklist**
=> chore: pass down reader metrics to avoid duplicate registration

docs/sources/shared/configuration.md, pkg/blockbuilder/scheduler/scheduler.go, pkg/blockbuilder/scheduler/scheduler_test.go, pkg/blockbuilder/scheduler/strategy.go, pkg/blockbuilder/scheduler/strategy_test.go
Followup to https://github.com/grafana/loki/pull/15245.
This simplifies and consolidates planner implementation to just `RecordCountStrategy` while adding more parsing logic and the scaffolding to easily create new strategies in the future.
=> feat(blockbuilder): consolidate on record counting planner

pkg/querier/ingester_querier.go, pkg/querier/ingester_querier_test.go, pkg/querier/querier.go, pkg/querier/querier_mock_test.go
@benclive WDYT ?
**Checklist**
=> feat: Use context propagation to use the same ingester in GetChunksID

pkg/querier/ingester_querier.go, pkg/querier/ingester_querier_test.go, pkg/querier/querier.go, pkg/querier/querier_mock_test.go
Cherry-pick `feat: Use context propagation to call the same ingester in GetChunkID as Query (#15186)` (`70d9587863410b5610606bf20210402a2438ffd3`)
* Cherry-pick query fix into k231 to ensure querys don't fail during rollouts.
=> chore(backport): Add querier fix into k231

docs/sources/configure/bp-configure.md, docs/sources/configure/storage.md, docs/sources/setup/upgrade/_index.md
(cherry picked from commit 1b03a08bad4c1cc5294cd1f667204c2a86fbf95f)
Manual backport of #15212 with appropriate adjustments to the Upgrade file to match the 3.0 branch.
=> docs: fixing some Vale linter errors (#15212)

pkg/loki/modules.go
This PR enables meta cache on backend node, on which index-gateway service is running, when deployed in ssd mode.
**Checklist**
=> fix(blooms): Enable metas cache on backend when running in ssd mode

docs/sources/release-notes/v3-2.md
Updates the release notes for Loki 3.2.2.
The Release PR https://github.com/grafana/loki/pull/15147 did not include all of the backported updates, so searched `is:pr base:release-3.2.x -label:type/docs is:closed ` and used that as a base.
=> docs: Release notes for 3.2.2

docs/sources/release-notes/v3-3.md
Updates the release notes for Loki 3.3.2.
The Release PR https://github.com/grafana/loki/pull/15148 did not include all of the backported updates, so searched `is:pr base:release-3.3.x -label:type/docs is:closed ` and used that as a base.
=> docs: Release notes for 3.3.2

docs/sources/release-notes/v2-9.md
Updates the release notes for Loki 2.9.11.
The Release PR https://github.com/grafana/loki/pull/15267 did not include all of the backported updates, so searched `is:pr base:release-2.9.x -label:type/docs is:closed ` and used that as a base.
=> docs: Release notes for 2.9.11

docs/sources/release-notes/v2-9.md
manual backport of https://github.com/grafana/loki/pull/15280 to 3.2.x branch
=> docs: Release notes for 2.9.11 (#15280)

pkg/util/http.go, pkg/util/http_test.go
The IsError method does not return true even though status is 204. This is causing retries that makes aggregated metrics incorrect.
This PR fixes it and adds some tests.
#incident-2024-12-05-metric-aggregation-is-broken
**Checklist**
=> fix(aggregated_metrics): Fix the IsError method causing retries

pkg/bloomgateway/querier.go, pkg/loki/modules.go
After changing the default of  `-bloom-build.planner.min-table-offset` from `1` (yesterday) to `0` (today), we noticed that the bloom gateways reported a very high percentage of missing series in blocks.
This is because the gateway received filter requests for today's block, but the requested series is too new and has not been added to the bloom block yet.
In the bloom querier on the index gateway there is a condition under which requests to the bloom gateway are skipped, because the blooms are likely not available yet.
This PR changes this condition to correctly take the min-table-offset as well as the planning-interval into account.
**Checklist**
- **Note** that Promtail is considered to be feature complete, …
=> fix(blooms): Fix check for skipping most recent data when filtering blooms

docs/sources/release-notes/v2-9.md
Just correcting dates in release notes
Fixes #
**Checklist**
=> docs: correct dates in 2.9.x release notes

pkg/logql/log/metrics_extraction_test.go, pkg/logql/syntax/lex_test.go, pkg/logql/syntax/query_scanner.go
Allows query comparisons against zero bytes, ie `{foo="bar"} | logfmt | bytes < 0b`.
Fixes #14993
**Checklist**
=> fix: allow comparison against zero bytes

cmd/loki/loki-local-config.yaml
Metric aggregation was move to a per-tenant config. #15059 removed the old global config, but forgot to add the new limit override. This adds the limit override to `loki-local-config.yaml` so that metric aggregation is enabled in that config.
**Checklist**
=> fix: enable metric aggregation in `loki-local-config.yaml`

pkg/querier/queryrange/detected_fields.go, pkg/querier/queryrange/detected_fields_test.go
There are a lot of gotchyas with bytes in Loki. In the log line, bytes can be in many different formats, including spaces before the unit, no space before the unit, commas, decimals, basically anything that can be parsed by `humanize.ParseBytes`. However, for a query, we don't accept commas, and the unit must come directly after the number without a space.
This PR sanitizes bytes values returned by `detected_fields/{field_name}/values` to adhere to our rules for byte values in a query to make it easier for Explore Logs to construct queries from the values returned by this endpoint.
Fixes #15052
**Checklist**
- **Note** that Promtail is considered to be feature complete, and …
=> feat: present DF bytes values in queryable format

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/bloom-gateway/statefulset-bloom-gateway.yaml, production/helm/loki/templates/bloom-planner/statefulset-bloom-planner.yaml, production/helm/loki/templates/compactor/statefulset-compactor.yaml, production/helm/loki/templates/index-gateway/statefulset-index-gateway.yaml, production/helm/loki/templates/ingester/statefulset-ingester-zone-a.yaml, production/helm/loki/templates/ingester/statefulset-ingester-zone-b.yaml, production/helm/loki/templates/ingester/statefulset-ingester-zone-c.yaml, production/helm/loki/templates/ingester/statefulset-ingester.yaml, production/helm/loki/templates/memcached/_memcached-statefulset.tpl, production/helm/loki/templates/pattern-ingester/statefulset-pattern-ingester.yaml, production/helm/loki/templates/ruler/statefulset-ruler.yaml
This PR fixes PersistentVolumeClaim definition in statefulset templates for various apps to avoid diffs in ArgoCD.
**Checklist**
=> fix(helm): Fix statefulset templates to not show diffs in ArgoCD

.github/renovate.json5
We update the loki version in the helm chart both weekly, and in response to tagged releases. Therefore, we don't need renovate also trying to do the same.
**Checklist**
=> ci: skip grafana/loki updates in renovate

.github/renovate.json5
With the rework in [this PR](https://github.com/grafana/loki/pull/15308), lambda-promtail no longer needs a nix checksum updated each time, so the special-case handling can be removed.
**Checklist**
=> chore: Renovate - Remove special case for lambda-promtail

pkg/loki/modules.go
When the ruler evaluates rules locally (default), the deletes client is never stopped, hence preventing the workload from stopping gracefully.
I used [this reproducer](https://github.com/user-attachments/files/18080780/docker.zip) to test this out. When stopping the backend container:
- Before the fix, the container never stopped within the grace period (5m). 
- With this PR changes, it finished seconds after requesting the container shutdown.
Fixes https://github.com/grafana/loki/issues/9523 (people shared Loki 3.x fixed it but I think the problem fixed in this PR falls within the issue description).
**Checklist**
- **Note** that Promtail is considered to be feature complete, …
=> fix: Shut down delete client on local rule-evaluator

pkg/bloombuild/planner/planner_test.go
The tests failed when executed with `-race` with the following data race warning:
```
Write at 0x00c00624a118 by goroutine 94542:
github.com/grafana/loki/v3/pkg/bloombuild/planner.(*fakeBuilder).Send()
pkg/bloombuild/planner/planner_test.go:710 +0x1f5
github.com/grafana/loki/v3/pkg/bloombuild/planner.(*Planner).forwardTaskToBuilder()
pkg/bloombuild/planner/planner.go:842 +0xf9
github.com/grafana/loki/v3/pkg/bloombuild/planner.(*Planner).BuilderLoop()
pkg/bloombuild/planner/planner.go:777 +0xdcc
github.com/grafana/loki/v3/pkg/bloombuild/planner.Test_BuilderLoop.func8.2()
pkg/bloombuild/planner/planner_test.go:199 +0x5a
github.com/grafana/loki/v3/pkg/bloombuild/planner.Test_BuilderLoop.func8.gowrap1() …
```
=> fix: data race in bloombuild tests

docs/sources/setup/install/helm/install-microservices/_index.md, docs/sources/setup/install/helm/install-monolithic/_index.md, docs/sources/setup/install/helm/install-scalable/_index.md
Removed compactor settings from MinIO deployments. It was found that these caused MinIO setups to fail due to a bad configuration. Will work on adding these back in with further testing with MinIO when I get to the local deployment guide but for now it is safe to remove these for a better installation experience. 
**Checklist**
- [] Tests updated
=> docs: removed compactor options from minIO deployment

.github/renovate.json5
Renovate keeps [trying to update the go toolchain past our go version](https://github.com/grafana/loki/pull/15184/files#diff-4af3383fe9a944e7db77181929918678d973c5dcf75903193cc8837771e5eec6R5), which I don't think is a good idea.
**Checklist**
=> ci: disable renovate toolchain updates

tools/lambda-promtail/main.tf, tools/lambda-promtail/variables.tf
**What this PR does / why we need it**: Exposes the filter_prefix in the lambda_function of the aws_s3_bucket_notification resource as a terraform variable.
Fixes #15380
=> feat(lambda-promtail): Add terraform variable for s3 bucket notification filter prefix

pkg/chunkenc/memchunk_test.go
I am trying to fix some things in our tests and noticed that `TestChunkSize` was taking a long while and sometimes timing out the `120s` timeout I had. So I took a look and noticed that it was actually a benchmark masquerading as a test :sweat_smile: It wasn't actually testing anything, just collecting stats, and upon further inspection it wasn't doing a very good job of that either. So I fixed it up a bit and made it into a benchmark, to reduce the test execution time in CI.
Another potential improvement here would be to make the `fillChunk()` somewhat randomized. It can accept a RNG and fill the chunks with pseudo-random log lines, for more accurate tests. But that function is used in a bunch of other tests, so …
=> fix(ci): transform TestChunkSize into a benchmark

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/validation/validate.go
=> fix: Return error 422 (Unprocessable Content) when push request does not contain any streams

production/helm/loki/CHANGELOG.md, production/helm/loki/values.yaml
Adds a conditional statement to include rulerconfig only if `ruler.enabled=true`. Without this conditional, the loki-backend pod fails when no bucket is provided for the ruler, even when `ruler.enabled=false`
Fixes #15357
**Checklist**
=> fix(helm): Add conditional to include ruler config only when enabled

operator/ADOPTERS.md
Replaces "Prometheus Operator" with "Loki Operator". This was clearly a copy-paste error.
Fixes #15339
=> chore: Fix wording in Loki Operator ADOPTERS.md files

pkg/blockbuilder/types/grpc_transport.go, pkg/loki/loki.go
**What this PR does / why we need it**
By default loki applies user header interceptor middleware for all grpc methods on the server side which tries to extract user information from grpc metadata. But block scheduler methods are internal and their functionality is not tied to a single user. Adding the scheduler methods to the ignore list to not fail in the interceptor.
Similarly `grpcclient.Instrument()` tries to extract user information from context to perform per-tenant instrumentation cauing these methods to fail. Updated the Dial opts to only include the required interceptors.
**Checklist** …
=> chore(block-scheduler): add scheduler grpc methods to auth mw ignore list

pkg/blockbuilder/scheduler/scheduler.go, pkg/blockbuilder/scheduler/scheduler_test.go, pkg/blockbuilder/scheduler/strategy.go, pkg/blockbuilder/scheduler/strategy_test.go, pkg/loki/modules.go
Record planner is not initialised correctly causing panics, this change inits it with all the required dependencies.
**Checklist**
=> fix(block-scheduler): init record planner correctly

docs/sources/query/logcli/_index.md, docs/sources/query/logcli/getting-started.md
Updates the content on the `logcli` page to
* better organize content
* provide more context on what the tool is for
* add additional examples
* fix formatting issues/ Vale linter issues
=> docs: Update LogCLI topic

docs/sources/query/logcli/_index.md, docs/sources/query/logcli/getting-started.md
(cherry picked from commit bc3d994ff39a53575d859f2c0c552e8a76c746ba)
Manual backport of #15376 into the 3.3 branch.
=> docs: Update LogCLI topic (#15376)

pkg/pattern/aggregation/push.go, pkg/pattern/aggregation/push_test.go
This fixes a few different issues:
1. Setting `p.quit = nil` like that is actually a data race and the tests failed when executed with the `-race` flag:
```
Read at 0x00c000838508 by goroutine 82:
github.com/grafana/loki/v3/pkg/pattern/aggregation.(*Push).run()
github.com/grafana/loki/v3/pkg/pattern/aggregation/push.go:257 +0x184
github.com/grafana/loki/v3/pkg/pattern/aggregation.Test_Push.func3.gowrap2()
github.com/grafana/loki/v3/pkg/pattern/aggregation/push_test.go:172 +0x38
Previous write at 0x00c000838508 by goroutine 80:
github.com/grafana/loki/v3/pkg/pattern/aggregation.(*Push).Stop()
github.com/grafana/loki/v3/pkg/pattern/aggregation/push.go:165 +0x1884
github.com/grafana/loki/v3/pkg/pattern/aggregation.Test_Push.func3() …
```
=> fix: data race / nil channel read in pattern aggregation push

.github/workflows/helm-ci.yml
This issue resolves failing ci, python 3.7 is depricated and not supported in ubuntu 24.04. See thread [here](https://github.com/actions/setup-python/issues/962)
**Checklist**
- [ x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ x] Documentation added
- [ x] Tests updated
- [x ] Title matches the required conventional commits format, see [here](https://www.conventionalcommits.org/en/v1.0.0/)
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely …
=> fix: update-python-version-for-helm-ci

pkg/distributor/distributor_test.go
Tiny data race in the tests itself, without this fix the tests (when executed with `-race`) fail with:
```
Read at 0x00c00187a6a8 by goroutine 10064:
github.com/grafana/loki/v3/pkg/distributor.TestDistributorPushToKafka.func3.1()
github.com/grafana/loki/v3/pkg/distributor/distributor_test.go:586 +0x48
github.com/stretchr/testify/assert.Eventually.func1()
github.com/stretchr/testify@v1.10.0/assert/assertions.go:1949 +0x33
Previous write at 0x00c00187a6a8 by goroutine 9930:
github.com/grafana/loki/v3/pkg/distributor.(*mockIngester).Push()
github.com/grafana/loki/v3/pkg/distributor/distributor_test.go:1872 +0x3c4
github.com/grafana/loki/v3/pkg/distributor.(*Distributor).sendStreamsErr() …
```
=> fix: data race in distributor tests

pkg/logql/log/fmt.go, pkg/logql/log/fmt_test.go
This allows to bypass template format execution if this is a simple swap of the line with another key. Making that trick faster to use.
```
{bar="foo"} | json | line_format `{{.message}}` | pattern "<_>: <_> <something>" ....
```
**Checklist**
=> feat: line_format bypass template execution if possible

pkg/util/mempool/pool.go
Before this change, when I was running the tests with `-race`, the following error occurred:
```
fatal error: checkptr: unsafe.Slice result straddles multiple allocations
goroutine 60 gp=0xc0001ba8c0 m=5 mp=0xc000100008 [running]:
runtime.throw({0x14afd15?, 0xc0004e3d30?})
runtime/panic.go:1067 +0x48 fp=0xc0004e3c18 sp=0xc0004e3be8 pc=0x4b0148
runtime.unsafeslicecheckptr(0x130a920, 0xc0002fa000, 0x40)
runtime/unsafe.go:88 +0x65 fp=0xc0004e3c40 sp=0xc0004e3c18 pc=0x4a5b85
github.com/grafana/loki/v3/pkg/util/mempool.(*slab).get(0xc0002e5400, 0x10)
github.com/grafana/loki/v3/pkg/util/mempool/pool.go:58 +0x25b fp=0xc0004e3d58 sp=0xc0004e3c40 pc=0x1299e7b
github.com/grafana/loki/v3/pkg/util/mempool.(*MemPool).Get(0xc0001a5f60, 0x10) …
```
=> fix: remove unsafe pkg usage from util.mempool

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/release-workflows.jsonnet, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet, .github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/workflows.jsonnet, .github/workflows/check.yml, .github/workflows/images.yml, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml, Makefile, clients/cmd/docker-driver/Dockerfile
https://github.com/grafana/loki/pull/9247 did not seem to fix the docker driver build. It first [failed](https://github.com/grafana/loki/actions/runs/12260541067/job/34205830742) because of the an incorrect prefix in the job definition, and after that was fixed it [failed again](https://github.com/grafana/loki/actions/runs/12260816211/job/34206788442) because of an undefined env variable.
Depends on https://github.com/grafana/loki-release/pull/165
Fixes #5682, #15318
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be …
=> ci: fix the docker driver build

pkg/ingester/ingester_test.go, pkg/ingester/recalculate_owned_streams_test.go
Without these changes, the tests fail when executed with `-race`:
```
Write at 0x00c0126fd5b0 by goroutine 47612:
github.com/grafana/loki/v3/pkg/ingester.(*readRingMock).GetAllHealthy()
github.com/grafana/loki/v3/pkg/ingester/ingester_test.go:1541 +0x6e
github.com/grafana/loki/v3/pkg/ingester.(*ownedStreamsIngesterStrategy).checkRingForChanges()
github.com/grafana/loki/v3/pkg/ingester/recalculate_owned_streams.go:117 +0x77
github.com/grafana/loki/v3/pkg/ingester.(*recalculateOwnedStreamsSvc).recalculate()
github.com/grafana/loki/v3/pkg/ingester/recalculate_owned_streams.go:54 +0x2af
github.com/grafana/loki/v3/pkg/ingester.(*recalculateOwnedStreamsSvc).iteration()
github.com/grafana/loki/v3/pkg/ingester/recalculate_owned_streams.go: …
```
=> fix: data race in ingester test

docs/sources/community/governance.md
Add exception to the Grafana Vale spelling rule for names in the list of maintainers in the Governance file.
=> docs: add exception to spelling rule

docs/sources/send-data/docker-driver/_index.md
Small updates for Vale linting.
=> docs: fix admonition, line spacing

docs/sources/send-data/docker-driver/_index.md
Manual backport of #15462 to the 3.3 branch.
=> docs: fix admonition, line spacing (#15462)

pkg/storage/chunk/client/hedging/hedging.go, pkg/storage/chunk/client/hedging/hedging_test.go
Before these changes, the tests here failed with a bunch of data races, e.g.:
```
Read at 0x000000eb74e0 by goroutine 17:
github.com/grafana/loki/v3/pkg/storage/chunk/client/hedging.(*winnerTrackingRoundTripper).RoundTrip()
github.com/grafana/loki/v3/pkg/storage/chunk/client/hedging/hedging.go:160 +0xa4
github.com/cristalhq/hedgedhttp.(*hedgedTransport).RoundTrip.func2()
github.com/cristalhq/hedgedhttp@v0.9.1/hedged.go:211 +0xa4
github.com/cristalhq/hedgedhttp.runInPool.func1()
github.com/cristalhq/hedgedhttp@v0.9.1/hedged.go:305 +0x39
Previous write at 0x000000eb74e0 by goroutine 22:
github.com/grafana/loki/v3/pkg/storage/chunk/client/hedging.initMetrics()
github.com/grafana/loki/v3/pkg/storage/chunk/client/hedging/hedging.go:39 …
```
=> fix: data race in chunk client hedging tests

docs/sources/send-data/docker-driver/_index.md
We are now publishing both `arm64` and `amd64` versions of the docker driver image. This PR updates the docs to reflect that.
Re: #15318
**Checklist**
=> docs: update docker-driver image reference

.github/workflows/nix-ci.yaml, flake.lock
The nix tests are very hard to maintain, for 2 reasons, 1) we don't run them on every push, 2) they run in a sandbox, and things like relying on specific network interfaces are often introduced to our tests.
This PR adds a condition on the test step to only run if there have been changes to `flake.nix` or `nix/**`. This means that changes to `go.mod`, like we often see from renovate updates, will only lint and build the nix packages to make sure the changes don't break compilation, but will not run the tests. This should help the large number of renovate PRs that fail the nix test step, since I don't have the bandwidth the dig into every one of those failures.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future …
=> ci: remove test step from nix-ci

.gitignore
Removes the workflow submodule added by the GH action for Helm chart release and add the path to the gitignore file.
=> fix(ci): Remove submodule once and for all

pkg/pattern/aggregation/push_test.go
A recent [PR](https://github.com/grafana/loki/pull/15410) caused multiple occurrences of [timeouts](https://github.com/grafana/loki/actions/runs/12410129954/job/34645141970?pr=15493) in this particular test.  This PR increases the buffer size to work around this.
**Checklist**
=> test: Increase buffer size to prevent timeouts in tests

pkg/bloombuild/builder/builder.go, pkg/bloomgateway/resolver.go, pkg/bloomgateway/resolver_test.go
While running bloom filters in production we noticed some Loki clusters that showed a very high percentage of missing chunks when querying blooms, thus resulting in lower filter rate.
_Screenshot from Bloom Gateway dashboard_
The reason is that old, superseded blocks are still considered up-to-date, because they cover a keyspace that is not covered by newer blocks with smaller keyspaces (due to larger individual series).
```
| series fingerprint keyspace
------------+----------------------------------------------------------------
|    o     o   o  o  o     o    o o    o       o    o   o    o
------------+----------------------------------------------------------------
iteration 1 |    111111111111111111111111111111111111111111111111111111111 …
```
=> fix(blooms): Match series to newest block only

.github/workflows/helm-loki-ci.yml
Reverts grafana/loki#14365
See the incident [#incident-2024-12-20-loki-full-repo-takeover-due-to-gh-actions](https://raintank-corp.slack.com/archives/C085SNJHY06)
=> fix(ci): Revert "fixed `Publish Rendered Helm Chart Diff` workflow"

pkg/logql/log/metrics_extraction.go
Structured metadata was not passed downstream when a delete request pipeline filter was processed for a query (only affected metric queries).
**Checklist**
=> fix: structured metadata not always passed down for processing deletes

pkg/blockbuilder/builder/builder.go
Record decoder reuses the stream and entries slice, this would not be a problem if these entries are consumed synchronously. But the block builder buffers the entries and consumes them in batches through a channel while the decoder reuses the entries slice on each decode call.
Making a copy of the entries to avoid this problem. 
**Checklist**
=> fix(blockbuilder): copy entries returned by record decoder

pkg/blockbuilder/scheduler/priority_queue.go, pkg/blockbuilder/scheduler/queue.go, pkg/blockbuilder/scheduler/scheduler.go, pkg/blockbuilder/scheduler/status.go, pkg/blockbuilder/scheduler/status.gohtml, pkg/blockbuilder/scheduler/status_test.go, pkg/loki/modules.go
Adds a status page for block scheduler which can be accessed at `GET /blockscheduler/status`
It lists the following details:
- pending jobs ordered by priority
- in progress jobs ordered by start time
- partition lag, start and end offsets for pending partitions
Added a test to generate an example status page which is skipped by default. Remove `t.Skip()` to generate and inspect the html file
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the …
=> chore: add status page for block scheduler

docs/sources/shared/configuration.md, pkg/blockbuilder/scheduler/queue.go, pkg/blockbuilder/scheduler/queue_test.go, pkg/blockbuilder/scheduler/scheduler.go, pkg/blockbuilder/scheduler/scheduler_test.go, pkg/loki/modules.go
Introduces a job lease checker to expire jobs that have not received any updates from the builders for `-jobqueue.lease-duration`. Expired jobs are immediately re-enqueued so that this work can be assigned to another available builder.
This is helpful when a builder that picked a job is now unavailable either because it restarted, crashed or has become unresponsive, in such cases it is better to assign this work to another builder so as to not fall behind. 
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs …
=> feat(block-scheduler): introduce job lease and requeue expired jobs

Makefile
Small QoL target for building local images with target architectures.
=> chore(make): loki-local-image make target for building images on local machines

pkg/storage/stores/shipper/indexshipper/tsdb/compactor.go
We might have new chunks created while processing delete requests, especially with line filters. The new chunks are then indexed for discoverability. The thing to note here is that TSDB index is not built incrementally and requires all the data at once to build it. This TSDB limitation caused us to batch the updates, which in this case, resulted in increased memory usage due to erroneously retaining a copy of a chunk instead of just the metadata. This PR fixes the issue by batching chunk metas instead of whole chunks.
=> fix: do not retain copy of chunk while indexing a new chunk in tsdb while processing delete requests

pkg/blockbuilder/scheduler/priority_queue.go, pkg/blockbuilder/scheduler/priority_queue_test.go, pkg/blockbuilder/scheduler/queue.go, pkg/blockbuilder/scheduler/status.go, pkg/blockbuilder/scheduler/status.gohtml, pkg/blockbuilder/scheduler/status_preview_test.go, pkg/blockbuilder/scheduler/status_test.go
The scheduler keeps a circular buffer of the last `n` completed jobs. This PR now includes this information in the status page for easier tracking of system behavior. it also adds a test utility to play around with this locally. Here's an example:
=> feat(block-scheduler): status page shows completed jobs

pkg/querier/queryrange/detected_fields.go, pkg/querier/queryrange/detected_fields_test.go
DF field values are currently turning all numeric fields into bytes, this is a bug. This fixes that bug.
**Checklist**
=> fix: bytes unit detection in detected fields

docs/sources/shared/configuration.md, pkg/blockbuilder/scheduler/scheduler.go
*Local branch copy of* https://github.com/grafana/loki/pull/15578 to debug possible fork permission issues
* Removes `max_jobs_planned_per_interval`. We don't want this yet and it was being used incorrectly as the planners `maxJobsPerPartition` argument.
* Hardcodes one job per partition during planning
* enqueues the next job for some partition when the current one finishes.
Some of it is a bit hacky & will need refactoring, but this should work well enough in the meantime to flesh out issues.
=> fix(block-scheduler): one job per partition (local branch copy)

.gitignore, tools/dev/kafka/README.md, tools/dev/kafka/docker-compose.yaml, tools/dev/kafka/loki-local-config.debug.yaml, tools/dev/kafka/provisioning/datasources/default.yml
This pull request introduces a comprehensive development setup for testing Loki with Kafka integration. The setup includes supporting services like Kafka, Grafana, and a log generator, all managed via docker-compose, while Loki itself is run manually from the source code.
**Checklist**
=> feat: add kafka development environment

docs/sources/shared/configuration.md, pkg/storage/chunk/cache/cache_test.go, pkg/storage/chunk/fetcher/fetcher.go, pkg/storage/chunk/fetcher/fetcher_test.go, pkg/storage/config/store.go, pkg/storage/store.go, pkg/storage/stores/series_store_write_test.go, pkg/storage/util_test.go
This change will prevent any chunks fetched by the querier to not be written back to the chunk cache that are before a given time range. 
95% of the searches that our engineering teams execute are within a 7 day range and we have a cache enabled to support 14 days worth of chunks to aid in query performance. We recently found that we have compliance need to maintain searchable logs for 365 days. While these queries outside of the 7 day window are rare, they tend to be longer duration searches of up to 30 days for compliance, contain a lot of data, and tend to be one-off searches.
Currently these chunks fetched by queriers outside our target window are written back to the chunk cache and causing more recent data to be evicted from the cache and …
=> feat: Skip writeback for chunks fetched by queriers older than a duration

docs/sources/get-started/labels/_index.md, docs/sources/get-started/labels/cardinality.md
Reorganizes and revises the Labels topic to take into account:
* New default service_name label
* Label defaults for OTEL
* Provides additional guidance to help customers avoid known issues with labels
Adds a new topic for cardinality.
=> docs: Update labels, add cardinality topic

pkg/blockbuilder/builder/storage.go
Fixes an issue where we wrote indices one "level" up, e.g. we'd write `bucket/index_1000/$file.tsdb` instead of `bucket/index/index_1000/$file.tsdb`. This must be consistent across components and this snuck through because different code paths are used for index uploads in the blockbuilder vs index shipper. It's not worth the heavy refactoring to align these considering this is a stopgap while we introduce new format(s) in the builder/scheduler architecture.
=> fix(blockbuilder): use index path prefix in objectclient for tsdb creation

docs/sources/get-started/quick-start.md
Adds curl commands to procedure.
Fixes #7478 
@Jayclifford345  I just want to make sure that adding tabbed content will also work in the Killercoda tutorial.
=> docs: add curl commands

docs/sources/shared/configuration.md, pkg/distributor/distributor.go, pkg/distributor/field_detection.go, pkg/distributor/field_detection_test.go, pkg/distributor/limits.go, pkg/distributor/validator.go, pkg/logql/log/parser.go, pkg/validation/limits.go, pkg/validation/limits_test.go
This PR introduces a new feature that allows for extraction of "fields" into structured metadata at ingest time.
Fields can either be regular labels, structured metadata keys, or keys from `logfmt` or `json` formatted log lines. 
The fields are defined in a per-tenant configuration as `map[string][]string`, where the key is the target key of the structured metadata, and the value is the list of source fields in given order and the order given above.
Example configuration:
```yaml
limits_config:
discover_generic_fields:
trace_id:
- "trace_id"
- "TRACE_ID"
- "traceID"
- "TraceID"
org_id:
- "org_id"
- "tenant_id"
- "user_id"
```
**Update**: The fields moved into a "fields" objects:
```yaml
limits_config:
discover_generic_fields:
fields:
trace_id:
- …
```
=> feat: Detect fields  based on per-tenant configuration and put them into structured metadata at ingest time

pkg/ingester/instance.go
When using kafka-based ingestion we are missing currently to notify which streams are not created as per response path is asynchronous. This PR adds some short-term logging to inform investigators when and which streams were not created by the partition-ingesters on stream count limiting.
- The partition ingesters have as of today disabled rate limiting.
**Checklist** …
=> fix(partition-ingester): Add stream creation error logging

docs/sources/send-data/_index.md
Adds a new client to the list of third-party clients for Loki.
=> docs: add another third-party client

docs/sources/setup/install/helm/reference.md, production/helm/loki/values.yaml
=> docs: add note to Helm values file

cmd/logcli/main.go, pkg/logcli/index/volume.go, pkg/logcli/print/print.go, pkg/logcli/query/query.go
Adds a new `--include-common-labels` flag to `logcli query`, which causes the output to include all common labels.
This is mostly useful with `--quiet` and `--output=jsonl` as it allows users to get structured information from Loki that has *all* the information that Loki can provide.
Fixes #5702
- The suggestion on the PR was `--all-labels`. Given there are other label selection options, I thought it was easiest to add something to directly control the behaviour to remove common labels.
- I have not written tests, but I have verified that it works locally
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will …
=> feat(logcli): Include common labels

pkg/dataobj/internal/dataset/column.go, pkg/dataobj/internal/dataset/column_builder.go, pkg/dataobj/internal/dataset/column_iter.go, pkg/dataobj/internal/dataset/column_test.go, pkg/dataobj/internal/dataset/page.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/internal/dataset/page_compress_writer.go, pkg/dataobj/internal/dataset/page_iter.go, pkg/dataobj/internal/dataset/page_test.go, pkg/dataobj/internal/metadata/datasetmd/datasetmd.pb.go, pkg/dataobj/internal/metadata/datasetmd/datasetmd.proto, pkg/dataobj/internal/result/result.go, pkg/dataobj/internal/streamio/varint.go
This commit adds the ability to accumulate sequences of dataset.Value into a column, which is split up across multiple pages.
Each page is broken down into two parts:
* A bitmap-encoded sequence of booleans, where 1 indicates a row has a value and 0 indicates the row is NULL, and
* the encoded sequence of non-NULL values, whose encoding is determined by the column options.
The sequence of non-NULL values is then optionally compressed.
This commit also includes initial support for reading these columns, starting with internal-only helper utilities for unit tests.
=> chore(dataobj): column building

pkg/querier/queryrange/downstreamer.go
every time https://github.com/grafana/loki/blob/main/pkg/querier/queryrange/downstreamer.go#L197 this function return. there is no receiver for this channel.
https://github.com/grafana/loki/blob/main/pkg/querier/queryrange/downstreamer.go#L187. but there still have some error send to this channel. which result in goroutine leakage.
we can get this leakage through pprof/goroutine
=> fix: RangeQuery goroutine leak

pkg/dataobj/internal/dataset/column.go, pkg/dataobj/internal/dataset/dataset.go, pkg/dataobj/internal/dataset/dataset_iter.go, pkg/dataobj/internal/dataset/dataset_sort.go, pkg/dataobj/internal/dataset/dataset_sort_test.go, pkg/dataobj/internal/dataset/page.go, pkg/dataobj/internal/dataset/value.go
This commit adds dataset.Dataset, the representation of a set of columns (each of which is split into a set of pages). A Dataset is represented by an interface to allow for implementations where Datasets, Columns, and Pages are backed by object storage or a cache layer.
Two utilities are introduced on top of a Dataset:
* dataset.Sort returns a new Dataset for which values are sorted in ascending order from a selected set of columns.
* dataset.Iter allows for iterating over rows in a dataset from a selected set of columns.
This initial implementation is insufficient for reading at scale: there is no predicate support for filtering out pages and it lazily loads one page at a time during iteration. Both of these would cause unnecessary roundtrips to object storage.
However, dataset.Iter is …
=> chore(dataobj): add Dataset with iteration and sorting support

Makefile
See individual commit messages.
=> chore: Remove crossbuild dockerfiles and their make targets, and *-image-push make targets

.github/workflows/deploy-pr-preview.yml
The previous guard fails because `github.repository` resolves to the base repository on `pull_request` events.
**Checklist**
=> ci: Fix only run on fork guard

pkg/distributor/distributor.go, pkg/distributor/tee_test.go, pkg/kafka/encoding.go, pkg/kafka/encoding_test.go, pkg/pattern/tee_service.go, pkg/pattern/tee_service_test.go
When counting the amount or rates of a stream the respective ingest limits apply across all shards. In that regard the stream metadata are stored using the original hash rather than the one populated by shard creation. However the present implementation will write more metadata records for a shared stream, i.e. equal to the amount of shards. This is a slight waste of records though.
**Checklist** …
=> feat(distributor): Store no shard stream metadata only

docs/sources/send-data/docker-driver/_index.md
This PR fixes a typo in the architecture name, changing `amr64` to `arm64`. This ensures accuracy and consistency in the documentation.
No major changes.
**Checklist**
=> fix: correct typo in architecture name (amr64 -> arm64)

docs/sources/setup/install/helm/deployment-guides/aws.md, docs/sources/setup/install/helm/deployment-guides/azure.md
This PR fixes the broken links in Loki documentation.
Fixes broken links in Loki documentation.
**Checklist**
=> docs: broken URLs fixed

docs/sources/configure/bp-configure.md
Fixes #https://github.com/grafana/support-escalations/issues/5893
=> docs: add info about compression

pkg/distributor/distributor.go
We use background context to push logs to Ingesters from Distributors to continue to ingest logs when we return early. This is to avoid stopping ingestion to remaining ingesters after hitting quorum. However, we have to explicitly copy the required context keys from the parent to the newly created context.
I am working on some changes that add a new key to the context, and I feel that copying all the required keys is cumbersome and error-prone. What we want here is a clone of context without cancellation propagation from parent to child. This is now achievable using [context.WithoutCancel](https://pkg.go.dev/context#WithoutCancel).
=> chore: clone the context instead of using background context while pushing logs to ingesters from distributor

docs/sources/setup/install/helm/install-monolithic/_index.md
This missing line causes the StatefulSet/loki to be missing. 
If one would copy the "s3"  or "azure" sections of this guide, it is possible to miss the "deploymentMode" config (I did it).
It was awful to figure out the mistake, because first timers will not notice the missing StatefullSet (since there is aready a deamonset).
**Checklist**
=> docs: fix missing deploymentMode: SingleBinary

pkg/dataobj/internal/sections/streams/iter.go, pkg/dataobj/internal/sections/streams/streams.go, pkg/dataobj/internal/sections/streams/streams_test.go
This commit introduces the streams package, which tracks a list of streams in a data object.
Each stream is given an ID unique to the scope of a data object. This allows for streams to eventually be split up across multiple sections if one section becomes too large.
=> chore(dataobj): add streams tracking and encoding

docs/sources/shared/configuration.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/limits.go, pkg/distributor/validator.go, pkg/validation/limits.go, pkg/validation/limits_test.go, pkg/validation/validate.go
Introduce the new experimental `enforced_labels` limit.
By default it is empty but when configured, it configures Loki to only accept push requests which streams have all enforced labels.
**Checklist**
=> feat: Add a new `enforced_labels` limit

pkg/dataobj/internal/sections/logs/iter.go, pkg/dataobj/internal/sections/logs/logs.go, pkg/dataobj/internal/sections/logs/logs_test.go, pkg/dataobj/internal/sections/streams/iter.go, pkg/dataobj/internal/sections/streams/streams.go, pkg/dataobj/internal/sections/streams/streams_test.go
This commit is the equivalent of #15713 for the logs section: log records are accumulated into column builders and then flushed into a section at encoding time.
Some minor API changes have been made to sections/streams to ensure consistency with sections/logs.
=> chore(dataobj): add logs tracking and encoding

pkg/dataobj/internal/dataset/value_encoding_plain.go, pkg/dataobj/internal/dataset/value_encoding_plain_test.go
All decoder implementations used io.ReadFull for reading into a buffer except for the plain string decoder, which used io.Reader.Read directly (and incorrectly checked for partial reads).
Thanks to @benclive for finding this.
=> chore(dataobj): fix bug with partial reads of strings

pkg/pattern/aggregation/push.go
Prevent the pattern ingester from sending empty aggregated metric payloads when there are no aggregated metrics to send.
**Checklist**
=> fix: don't send empty aggregated metric payloads

pkg/dataobj/internal/encoding/encoder_logs.go, pkg/dataobj/internal/encoding/encoder_streams.go, pkg/dataobj/internal/encoding/encoder_test.go
encoding.LogsEncoder and encoding.StreamsEncoder failed to set
enc.close = true
on a call to Close. Because the logs and stream sections call Discard on a defer, this means that the *bytes.Buffers were being placed into the pool twice.
=> chore(dataobj): fix bug where instances of *bytes.Buffer are incorrectly shared

pkg/dataobj/dataobj.go, pkg/dataobj/dataobj_test.go, pkg/dataobj/internal/dataset/column_builder.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/internal/encoding/decoder_bucket.go, pkg/dataobj/internal/encoding/decoder_metadata.go, pkg/dataobj/internal/encoding/pools.go, pkg/dataobj/internal/sections/logs/iter.go, pkg/dataobj/internal/sections/logs/logs.go, pkg/dataobj/internal/sections/streams/streams.go, pkg/dataobj/pools.go, pkg/dataobj/reader.go
This PR adds initial end-to-end support for data objects:
* dataobj.Builder gradually constructs a data object via calls to Append.
* Once the builder returns ErrBufferFull, the data object must be flushed with a call to Flush.
Whether a builder is full is based on basic heuristics: 
* The size of a logs section is determined by cut pages and the uncompressed size of the current head page. 
* The size of a streams section is determined by estimating the cost of delta-encoding and compressing label values. 
* The size of an incoming `logproto.Stream` is determined by its labels, line length, and metadata, with a compression estimate applied where appropriate. 
These estimates are conservative and tend to overestimate; this helps keep objects slightly under the limit when flushing. 
I …
=> chore(dataobj): support for building and flushing data objects

docs/sources/shared/configuration.md, pkg/kafka/config.go, pkg/limits/config.go, pkg/limits/ingest_limits.go, pkg/limits/ingest_limits_test.go, pkg/loki/loki.go, pkg/loki/modules.go, tools/dev/kafka/loki-local-config.debug.yaml
Moves the ingest limits config from the `kafka` pkg to the `limits` pkg.
**Checklist**
=> feat(ingest-limits): Move config struct to new limits pkg

pkg/dataobj/dataobj_test.go, pkg/dataobj/internal/sections/logs/logs.go, pkg/dataobj/internal/sections/logs/logs_test.go
During testing, @cyriltovena and I have discovered that sorting the logs dataset is far too slow due to the number of page loads required to iterate over the single table in sorted order.
To move testing along, sorting is being disabled for now, but it will return once the logs section implementation is refactored to lessen the work on the dataset.Sort implementation.
=> chore(dataobj): temporarily disable sorting

pkg/dataobj/dataobj.go, pkg/dataobj/dataobj_test.go, pkg/dataobj/internal/encoding/encoding_test.go, pkg/dataobj/internal/encoding/metrics.go, pkg/dataobj/internal/sections/logs/logs.go, pkg/dataobj/internal/sections/logs/logs_test.go, pkg/dataobj/internal/sections/logs/metrics.go, pkg/dataobj/internal/sections/streams/metrics.go, pkg/dataobj/internal/sections/streams/streams.go, pkg/dataobj/internal/sections/streams/streams_test.go, pkg/dataobj/metrics.go, pkg/dataobj/reader.go
This commit adds detailed instrumentation for data objects:
* Configuration information for the dataobj.Builder, which can be used to determine page and object efficiency.
* Performance information about dataobj.Builder.
* Current stats about the object being appended to.
* Many histograms recording the distribution of data in sections, columns, and pages. To limit the number of time series per builder, these stats are not available as classic histograms.
As a result, this introduces quite a few time series, around 80 per builder instance.
=> chore(dataobj): instrument data objects

cmd/loki/loki-local-config.yaml
Backport 38fcef3f1a27305ad502927b9f7d4476b118488f from #15103
And 5c8542036609f157fee45da7efafbba72308e829 from https://github.com/grafana/loki/pull/15059
---
Remove submodule file
Fixes #15100 
**Checklist**
=> chore: remove submodule accidentally added to repo (backport release-3.3.x)

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/admin-api/deployment-admin-api.yaml, production/helm/loki/templates/gateway/deployment-gateway-enterprise.yaml, production/helm/loki/values.yaml
GEL failed to deploy when deployed with MinIO via the `minio` sub-chart. 
- Removed the minio-mc init container from admin-api; it was unnecessary and caused the admin-api deployment to fail. The MinIO Helm chart now handles this with a [standalone job](https://github.com/minio/minio/blob/master/helm/minio/templates/post-job.yaml).
- Updated the admin-api and gateway deployment container args to pull the correct values from the template.
- bucket-name
- access-key-id
- secret-access-key
- insecure
Note that `access-key-id` and `secret-access-key` are now pulled from the first entry under `minio.users`. Example:
```yaml
minio:
users:
- accessKey: FIXME_ACCESS_KEY_ID_0
secretKey: FIXME_SECRET_ACCESS_KEY_0
policy: readwrite
- accessKey: …
```
=> fix(helm): Update GEL Helm parameters to work with MinIO

pkg/compactor/deletion/request_handler.go, pkg/compactor/deletion/request_handler_test.go
Currently, we do not align delete requests while splitting them. This PR aligns the splits with the split interval for 2 reasons:
1. With deterministically split delete requests, we can easily dedupe delete requests which significantly overlap an existing request with the same selector.
2. 24h splits would align with 24h index table interval. While there won't be any significant improvement, it is better for the splits to cover a whole single table instead of partially covering multiple tables.
**Checklist**
=> chore: align delete request splits to shard interval

pkg/dataobj/dataobj.go, pkg/dataobj/metrics.go
The config metrics weren't registered, but you also can't register constant metrics so I needed to switch them over to a gauge.
=> chore(dataobj): fix dataobj_config metrics

.github/workflows/check.yml, .github/workflows/images.yml, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, Makefile, loki-build-image/README.md
Moves Loki to Go 1.23.5
**Checklist**
=> chore(deps): Bump to Go 1.23.5

pkg/loki/loki.go
Fixes a missing module for `ingest-limits-frontend` that prevented it from being started with `-target`.
**Checklist**
=> chore: fix missing module for ingest-limits-frontend

pkg/dataobj/internal/sections/streams/streams.go
Streams.EstimatedSize is invoked for every append to a data object builder. This method ended up consuming 44% of total CPU time due to it iterating over every label in every stream every call.
We can precompute the size of all labels when a new stream is added, skipping over the iteration. This will make the method several orders of magnitude cheaper with a large streams section.
=> chore(dataobj): improve performance of Streams.EstimatedSize

pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/loki/modules.go
Fixes linter error which prevents the CI pipeline to succeed.
=> chore: Fix `unused-parameter` linter errors

pkg/dataobj/internal/encoding/encoder.go, pkg/dataobj/internal/encoding/encoder_logs.go, pkg/dataobj/internal/encoding/encoder_streams.go
Previously, 13% of flush time was spent growing *bytes.Buffer. The CPU time was exacerbated by the number of calls to *bytes.Buffer.Write that required growing the slice. Additionally, as *bytes.Buffer.Write grows the slice exponentially, the resulting slice was much bigger than it needed to be.
A quick benchmark showed that we can reduce the CPU time and number of allocations by ~3x each by growing the buffer to exactly the size we need before writing all pages.
=> chore(dataobj): reduce total allocations while encoding

docs/sources/send-data/alloy/_index.md, docs/sources/send-data/otel/_index.md, docs/sources/send-data/promtail/_index.md
Based on a conversation with @cyrille-leclerc , moving Alloy and OTEL higher in the Send Data table of contents since they are the preferred clients.
=> docs: change order of TOC

pkg/ingester/instance.go, pkg/ingester/limiter_test.go, pkg/ingester/metrics.go, pkg/ingester/owned_streams.go, pkg/ingester/recalculate_owned_streams_test.go
* dont block reads & writes to tenants while updating the owned streams trackers
* in `ownedStreamsService`, prefer atomics where possible and fallback to mutices.
* More helpful le buckets in lock metrics.
=> perf(ingester): refactor lock acquisitions related to `not_owned` series limit functionality

pkg/loghttp/push/otlp.go, pkg/loghttp/push/push.go
Currently, we update the usage tracker for bytes received stats for each log line. Since it is on a hot path and the tracker would continue to evolve as we do more complex things, this PR reduces the update frequency to stream level.
=> chore: update usage tracker with received bytes on stream level instead of each log line

docs/sources/shared/configuration.md, pkg/limits/frontend/client.go, pkg/limits/frontend/config.go, pkg/limits/frontend/frontend.go, pkg/limits/frontend/service.go, pkg/loki/modules.go
This pull request creates the gRPC clients for the limits frontend, including client pools, and attempts to read all replicas from the ring.
**Checklist**
=> feat: create client for limits frontend to call limits service

pkg/compactor/deletion/delete_request.go, pkg/compactor/deletion/delete_request_test.go, pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_manager_test.go
While loading delete requests for processing, we will look for duplicate delete requests and mark them as processed when we are done processing the loaded requests. This should avoid wasting resources in processing the same requests sent multiple times by the users.
**Checklist**
=> feat: dedupe duplicate delete requests while loading them for processing in compactor

pkg/ingester/instance.go, pkg/ingester/limiter_test.go, pkg/ingester/metrics.go, pkg/ingester/owned_streams.go, pkg/ingester/recalculate_owned_streams_test.go
Cherry-picks 2a2b52808c508be96ff61bdde2d6740a741fb053 onto `k238`.
N/A
N/A
**Checklist**
=> perf(ingester): refactor lock acquisitions related to `not_owned` series limit functionality (#15839)

.github/renovate.json5
This PR does the following:
- Enables monitoring of the current set of releases under maintenance.  This monitoring is limited to security patching only (a global configuration), and individual items like go/helm/docker monitoring are explicitly disabled for these branches.
- Enables automatic approval and merging of minor and patch fixes for Go updates. We have had success with this over the past few months, and it is time to remove the human element from the workflow.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, …
=> chore(deps): Update renovate configuration for more automation

pkg/dataobj/dataobj.go, pkg/dataobj/internal/encoding/metrics.go, pkg/dataobj/metrics.go
This adds three new histograms:
* A distribution of constructed object sizes,
* a distribution of compression ratio across an entire column, and
* a distribution of compression ratio per compressed page.
The compression ratio histogram is only reported for columns where compression is being used.
=> chore(dataobj): add compression ratio and final object size distributions 

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/release-workflows.jsonnet, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/runner.libsonnet, .github/workflows/images.yml, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, Makefile
Build Docker images "natively" on runner architecture
This PR changes the way how multi-arch images are built. Instead of cross-compiling on emulated architecture using multiple platforms in the docker buildx build command, it uses dedicated arm and amd runners to build images "natively" and later combining the resulting image digests into a multi-arch manifest.
This PR is equal to https://github.com/grafana/loki/pull/15858 but the loki-release lib is vendored from upstream.
Upstream changes: https://github.com/grafana/loki-release/pull/180
=> ci: Update loki-release workflows to build Docker images "natively"

pkg/limits/frontend/client.go, pkg/limits/frontend/config.go, pkg/limits/frontend/frontend.go
The limits package will have two clients: a client for the limits-frontend to connect to limits service backends, and a client for the distributor to connect to the limits-frontend. Naming both of these clients "client" will cause naming collisions and also confusion when reading godoc/source code. To avoid both of these problems, we rename the clients to IngestLimitsBackendClient and IngestLimitsFrontendClient, and do the same for their respective configs etc.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` …
=> chore: Differentiate clients in limits package

Makefile, clients/cmd/promtail/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki/Dockerfile
Then building a binary or image release for an upcoming version from a release branch, we provide the version using `--build-arg IMAGE_TAG=...` in the Docker build step of the CI workflow ([ref](https://github.com/grafana/loki/blob/3df08bd39f45bbf8314f31a59f35b955b9a31a5e/.github/workflows/minor-release-pr.yml#L456)).
However, this argument was ignored in the Dockerfile and not further passed down to the `make ...` command inside build phase of the Dockerfile.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made …
=> fix(ci): Provide correct build info for release builds

operator/api/loki/v1/lokistack_types.go, operator/api/loki/v1beta1/lokistack_types.go, operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml, operator/config/crd/bases/loki.grafana.com_lokistacks.yaml, operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml, operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml, operator/docs/operator/api.md
fix struct field name in comment
**Checklist**
=> chore(operator): fix struct field name in comment

pkg/logql/downstream.go, pkg/logql/downstream_test.go, pkg/logql/first_last_over_time.go, pkg/logql/quantile_over_time_sketch.go, pkg/logql/range_vector_test.go, pkg/logql/shardmapper.go
The query sharding for `last_over_time`, `first_over_time` and `quantile_over_time` would not adjust start and end by the passed `offset` for the underlying range query.
This change introduces tests and fixes the adjustment.
**Checklist**
=> fix: Adjust with offset in last, first and quantile over time queries.

clients/cmd/promtail/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki/Dockerfile, cmd/querytee/Dockerfile
In order to access the variable ${IMAGE_TAG} that is provided as `--build-arg IMAGE_TAG=x.x.x` in the `docker build` command, the `ARG` definition in the Dockerfile needs to be inside the build step block, otherwise it is empty.
Fix for ##15939
=> ci: Move IMAGE_TAG Dockerfile ARG into build phase

pkg/limits/frontend/client/client.go
This pull request adds a client for `limits-frontend` service. It will be used in distributors to make queries to the limits service.
**Checklist**
=> feat: add client for limits-frontend service

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
Updates the `skipRange` metadata used by the OpenShift variant.
**Checklist**
=> fix(operator): Update skipRange in OpenShift variant

pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go
This commit fixes a bug in the query range round tripper. It fixes the detection of the operation when decoding a HTTP request into a queryrange request object by comparing the path suffix rather than the equality of the full path.
Fixes #15585
**Checklist**
=> fix: Fix label values query when server.http_path_prefix is set

pkg/loki/loki.go, pkg/loki/modules.go
The bloom gateway client is used both in the bloom builder and in the index gateways. When running Loki in SSD mode, both services are part of the `backend` target, and therefore the client is initialised twice, leading to duplicate metrics registration and a subsequent panic.
This commit extracts the initialisation of the bloom gateway client into a separate service that is started once and becomes a dependency of both bloom builder and index gateway.
Fixes: #14083
=> fix(blooms): Initialize bloom gateway client only once

pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_table.go
We upload delete requests db every 5 mins, irrespective of whether there are any updates.
This PR changes it to upload the db only when there have been any updates since the last upload. This would reduce unnecessary work and make incrementally updated versions easier to recover from object storage.
=> chore: upload delete requests table only when there are updates since last upload

pkg/dataobj/internal/dataset/column_builder.go, pkg/dataobj/internal/dataset/column_test.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/internal/dataset/value.go, pkg/dataobj/internal/dataset/value_test.go, pkg/dataobj/internal/metadata/datasetmd/datasetmd.pb.go, pkg/dataobj/internal/metadata/datasetmd/datasetmd.proto, pkg/dataobj/internal/sections/logs/table.go, pkg/dataobj/internal/sections/streams/streams.go
This commit adds support for storing the minimum and maximum non-NULL value encountered in a page and a column. The minimum and maximum value of a column is determined by the minimum and maximum value across all pages in that column.
These range statistics are primarily useful at read time; if a value being searched for is outside of the min/max value range of a page, the row range represented by that page can be disqualified from the entire dataset. With most pages typically covering hundreds of thousands of rows (up to millions), this can dramatically reduce the search area when reading. 
Range statistics are opt-in to avoid bloating the statistics size when a min/max value would be less meaningful, such as a "minimum log line" in the message column of a logs section.
dataset.Value now …
=> chore(dataobj): support computation of min/max values in pages and columns

pkg/loki/modules.go
This commit removes the initialization of `ListenPort` for the `IngestLimits` ring lifecycler from `InitIngestLimitsRing`. It is not needed here, as the client does not register itself in the ring. It is just needed in `InitIngestLimits`.
**Checklist**
=> chore: remove ListenPort from initIngestLimitsRing

pkg/distributor/distributor.go
This commit renames the import package to `ingester_client`. This will avoid future confusion with `limits_frontend_client`, which will be imported in a subsequent change.
**Checklist**
=> chore: rename client to ingester_client

pkg/distributor/tenant_topic_tee.go, pkg/distributor/tenant_topic_tee_test.go
Adds a codec struct for encoding and future decoding of tenant topics. This will be helpful for determining the tenant a topic refers to.
=> chore(kafka): tenant prefix codec

production/ksonnet/loki/distributor.libsonnet
Adds the option to remove schedule constraints completely for the distributors.
This is already in place for queriers, and is not required for other components because we don't apply anti-affinity by default.
=> feat(ksonnet): Add no_schedule_constraints option to distributors

pkg/distributor/distributor.go
This pull request renames `pool` to `ingesterClients` as we will have another pool for `limitsFrontendClients`.
**Checklist**
=> chore: rename pool to ingesterClients

docs/sources/send-data/promtail/configuration.md
On Ubuntu 24.04 when installed via apt promtail does not have the permissions to get journal logs. This commit explains how to fix that issue.
Maybe fixes #7836, #9922, #11306
**Checklist**
=> docs(promtail): Add group permission note for journal

pkg/storage/bloom/v1/index.go
This function was getting a decompression reader from the pool but not returning it (as far as I can see) so I added that in.
The decompressor only seems to be used within the scope of this function so returning it in a defer should be safe.
=> chore(blooms): Return decompression reader to pool

docs/sources/shared/configuration.md, pkg/loki/common/common.go, pkg/loki/loki.go, pkg/ruler/rulestore/config.go, pkg/storage/factory.go, tools/doc-generator/parse/parser.go, tools/doc-generator/parse/root_blocks.go, tools/doc-generator/writer.go
Unhides docs for configuring thanos storage clients. This will be made available in the next minor release.
I made a minor change to the docs generator to not expand inline root blocks to avoid repetition. We can make this configurable by a doc tag `doc:"noexpand"` if we want to control this behavior
**Checklist**
=> docs(thanos): unhide configuration docs for thanos storage clients

production/loki-mixin-compiled-ssd/dashboards/loki_thanos_object_storage.json, production/loki-mixin-compiled/dashboards/loki_thanos_object_storage.json, production/loki-mixin/.lint, production/loki-mixin/dashboards.libsonnet, production/loki-mixin/dashboards/loki-object-store.libsonnet
Adds dashboard for monitoring object store operations when using thanos-io/objstore storage clients
**Checklist**
=> chore(mixin): add thanos object store dashboard

pkg/dataobj/explorer/ui/package-lock.json, pkg/dataobj/explorer/ui/package.json
Reverts https://github.com/grafana/loki/pull/15965.
**Checklist**
=> fix: reverts the tailwindcss upgrade that was breaking builds

production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/distributor.libsonnet
We're rolling out these new constraint changes with k239
**Checklist**
=> chore: backport distributor constraint changes to k239

production/ksonnet/loki/multi-zone.libsonnet
This reverts commit b45a31e84f83a9921fb34fc4faf15abb4d144e54.
We are no longer going this direction with the ingesters.
**Checklist**
=> chore: revert "fix: scheduling constraints (#16045)"

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/workflows.jsonnet, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml
Restores the automatic setting of the `latest` tag for both GitHub and DockerHub images.
Relates to https://github.com/grafana/loki-release/pull/206
**Checklist**
=> chore(build): Update workflow to leverage updates to latest GH and Docker tags

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/workflows.jsonnet, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml
Backport of https://github.com/grafana/loki/pull/16013 into k240
To fix build issues seen: https://github.com/grafana/loki/actions/runs/13116046557/job/36594197497
**Checklist**
=> chore(build): update release code k240

pkg/distributor/http.go, pkg/distributor/http_test.go, pkg/loghttp/push/push.go
Adaptive Logs filters logs in Loki's push path. There can be the case where all logs are filtered resulting in an empty push request. [This PR](https://github.com/grafana/loki/issues/13399) made empty push requests a validation error which means that some users are seeing push errors related to Adaptive Logs
The request parser [here](https://github.com/grafana/loki/blob/91ff737136cdaf59c857e76f72736124c24c01c3/pkg/loghttp/push/push.go#L112) is keeping interesting statistics that we'd like to keep so This PR introduces a new error `ErrAllLogsFiltered` that can be returned from the parser. When that error is seen, Loki returns a `204` directly to the user without passing the push request to the distributor.
=> fix: Determine when all logs have been filtered

pkg/util/entry_size.go
This PR exports ExcludedMetadataLabels so it can be extended in GEL for any other labels(eg. Adaptive Logs) that need to be accounted for while computing metadata size.
**Checklist**
=> fix: export ExcludedMetadataLabels so it can be extended in GEL

pkg/dataobj/internal/dataset/page.go
Opening a page for reading should not cause a panic. An unknown compression type may be encountered if an older version of the dataobj reading code is trying to read an object produced by a newer version (where new compression types are available).
Because of this, the read path should never panic when encountering an unexpected value in an object; this was the only panic on the read path and is now removed.
=> chore(dataobj): do not panic on unrecognized compression type

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/workflows.jsonnet, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml
Updates the release vendoring code for `k239`, so that the various `latest` tags are correct.
Process was to update `.github/jsonnetfile.json` with `965213a0fe2632438ab0524d606cb71d414e2388` and run `make release-workflows`.
**Checklist**
=> chore(build): Update loki release code for k239

pkg/logql/syntax/walk_test.go
Fixes failing golangciLint step in CI
ref: https://github.com/grafana/loki/actions/runs/13145215326/job/36681649009
=> ci: Fix `gochecksumtype` linter error

.github/release-workflows.jsonnet, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml
We only publish amd64 and arm64 versions of the docker driver, and only have a build image for those platforms, so this removes `linux/arm` as a target.
**Checklist**
=> ci: fix docker driver platforms (fixes k239 release)

.github/workflows/check.yml, .github/workflows/images.yml, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, Makefile, loki-build-image/README.md, tools/lambda-promtail/Dockerfile
>  go1.23.6 (released 2025-02-04) includes security fixes to the crypto/elliptic package, as well as bug fixes to the compiler and the go command. See the Go 1.23.6 milestone on our issue tracker for details. 
ref: https://go.dev/doc/devel/release#go1.23.0
=> chore: Update Golang in CI and build env to 1.23.6

tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/relabel.go, tools/lambda-promtail/lambda-promtail/relabel_test.go
This is required because original relabeling config only support yaml but the lambda promtail config is in json
This change introduces a more robust way of parsing and handling relabel configurations in the lambda-promtail tool. Key improvements include:
- Added a new `relabel.go` with custom JSON-friendly RelabelConfig
- Implemented conversion to Prometheus relabel configs
- Added comprehensive test suite for relabel config parsing
- Simplified environment variable handling in main.go
=> feat(lambda-promtail): Improve relabel configuration parsing and testing

clients/pkg/promtail/targets/lokipush/pushtarget.go, pkg/distributor/distributor.go, pkg/distributor/http.go, pkg/distributor/http_test.go, pkg/loghttp/push/otlp.go, pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go
Forward the `PoliciesStreamMapping` introduced at https://github.com/grafana/loki/pull/15982 to [push.RequestParser][1].
**Checklist**
[1]: https://github.com/grafana/loki/blob/6133dfaa8b3188fd0a874ad6baced38ab0ea5a22/pkg/loghttp/push/push.go#L99
=> feat(policies): Add PoliciesStreamMapping to loghttp limits interface

pkg/loki/loki.go
Found a panic when the tee would fail and it seems to come from the limits not yet inialized.
=> fix(pattern): Correctly initialize overrides for pattern tee.

pkg/dataobj/metastore/metastore.go, pkg/dataobj/metastore/metastore_test.go
Adds a function to iterate over all the metastores within a specific time period for a tenant
* This makes the files in object storage discoverable when all you have is the Start/End time period.
=> chore(dataobj): Add iterator for metastores

pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_store.go, pkg/compactor/deletion/grpc_request_handler.go, pkg/compactor/deletion/request_handler.go, pkg/compactor/deletion/util.go
Avoid some wasteful work and allocations while listing and merging sharded delete requests. Use sorting to group the shards from the same requests instead of making a copy.
=> chore: avoid doing some unnecessary work while listing or merging sharded delete requests

production/ksonnet/loki/config.libsonnet
`ruler_storage` config section is only required when using thanos storage clients. 
**Checklist**
=> chore(ksonnet): add ruler_storage section only if thanos storage is enabled

pkg/querier/queryrange/limits.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/split_by_interval.go, pkg/querier/queryrange/split_by_interval_test.go, pkg/querier/queryrange/splitters.go
Originally the splitter middleware had to parse the query and thus could return an error. However, parsing is done earlier now so no error is returned.
**Checklist**
=> chore: Remove unnecessary errors from splitter.

.github/workflows/helm-diff-ci.yml, docs/sources/setup/install/helm/reference.md, production/helm/loki/scenarios/simple-thanos-values.yaml, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
We are adding the support to thanos storage config inside our helm chart.
Together with this we are doing some refactor in our helpers to make our chart more reusable in some components and avoid code duplication.
**Checklist**
=> chore: helm thanos support

pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/consumer/service.go, pkg/kafka/partitionring/consumer/client.go
* Switches to the existing CooperativeSticky load balancing strategy for multi-tenant streams. The custom strategy is no longer required because we don't have to account for active/inactive partitions.
* Also used a buffer pool for flushing, which avoids needing to permanently allocate a large buffer that we only use once every few minutes
* The pool is shared between all producers which reduces total memory usage but may still spike if many objects need to be flushed at once. We could probably improve this via some coordination / flush workers but thats for another day.
=> chore(dataobj): Use kgo Balancer for dataobj-consumer

clients/pkg/promtail/targets/windows/win_eventlog/event.go, clients/pkg/promtail/targets/windows/win_eventlog/win_eventlog.go
In Alloy we are still using the win_eventlog pkg from Promtail and a user reported that some windows events would make Alloy crash during ingestion (https://github.com/grafana/alloy/issues/2616).
During the investigation, I found out that this code was taken from Telegraf and that this is a problem that they encountered and solved via https://github.com/influxdata/telegraf/pull/12375.
I ported the fix to my local loki and built a custom Alloy version with it. The user tested and reported that the bug was solved: https://github.com/grafana/alloy/issues/2616#issuecomment-2646161039
**Checklist** …
=> fix(promtail): windows forward event crash

.github/workflows/check.yml, .github/workflows/images.yml
Making our github actions workflows definitions to be more consistent and follow the standard definitions from github.
The workflows will continue exactly the same with this change.
**Checklist**
=> ci: standard format to be consistent

Makefile, clients/cmd/promtail/Dockerfile, cmd/logcli/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki/Dockerfile
Backports https://github.com/grafana/loki/pull/15939 and https://github.com/grafana/loki/pull/16159 into k239
**Checklist**
=> fix(ci): backport build info fixes into k239

pkg/dataobj/builder.go, pkg/dataobj/pools.go
While grafana/loki#16146 moved the final buffers used by dataobj builders to a shared pool, there was one remaining source of persistent memory footprint per builder: encoding.Encoder instances.
As encoding is an infrequent operation, builders do not need to persist implementations of encoding.Encoder, and instances can be shared across builders to reduce overhead.
=> chore(dataobj): pool instances of dataobj encoders

operator/internal/manifests/internal/sizes.go
The 1x.pico configuration, introduced in #14407, was modified as follows:
The replicationFactor of the Ingester was increased from 1 to 2.
The number of Ingester replicas was increased from 2 to 3.
However, the PDBMinAvailable[[1]](https://github.com/grafana/loki/blob/716d54e2a9617a80c2496a46e9c4cbf8ed51a5d9/operator/internal/manifests/internal/sizes.go#L71)  setting is still 1 after these changes. This means that two out of the three Ingester pods can be down at the same time, which affects High Availability. To address this issue, this PR updates the PDBMinAvailable setting to 2.
Fixes [LOG-6679](https://issues.redhat.com/browse/LOG-6679)
**Checklist**
- **Note** that Promtail …
=> fix(operator): adjust PDBMinAvailable for 1x.pico size

.github/release-workflows.jsonnet, .github/workflows/check.yml, .github/workflows/images.yml
Restores the publishing of the `lambda-promtail` images
Images can now be seen in the AWS ECR [repository](https://gallery.ecr.aws/grafana/lambda-promtail)
**Checklist**
=> chore(ci): Republish lambda promtail images

Makefile, clients/cmd/promtail/Dockerfile, cmd/logcli/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki/Dockerfile
Backports both https://github.com/grafana/loki/pull/15939 and https://github.com/grafana/loki/pull/16159 to the 3.3.x releases.
**Checklist**
=> fix(build): update build info 3 3 x

docs/sources/setup/upgrade/_index.md
Loki 3.2.x upgrade notes are incorrectly placed under `Unreleased` section
**Checklist**
=> docs: correctly tag upgrade notes

pkg/loghttp/push/otlp.go, pkg/loghttp/push/otlp_test.go, pkg/loghttp/push/push.go
We recently introduced the concept of policies. However, as of now, there's no way to distinguish which labels were seen by which policies. This PR improves that behavior. 
**Checklist**
=> feat: Account for policy when reporting seen resource and metadata labels

docs/sources/setup/install/helm/reference.md, production/helm/loki/templates/provisioner/job-provisioner.yaml, production/helm/loki/templates/provisioner/role-provisioner.yaml, production/helm/loki/templates/provisioner/rolebinding-provisioner.yaml, production/helm/loki/values.yaml
In the Grafana Federal Cloud we have clusters where we cannot create ClusterRole/ClusterRoleBinding due to an increased security posture.  To ensure we can deploy the provisioner in these clusters, this PR conditionally generates Role instead of ClusterRole if enterprise and enterprise.provisioner are enabled and rbac.namespaced is true.
This PR also updates the provisioner job helm hooks to allow it to be customized to run on other hookTypes. This still defaults to post-install and should have no impact to current usage.  This will allow the Grafana Federal Cloud to use the provisioner after helm post-upgrades to attempt to create tenants as required.
Fixes grafana/deployment_tools#185454. …
=> feat(helm): Allow provisioner to be namespaced

Makefile, clients/cmd/promtail/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki/Dockerfile, cmd/querytee/Dockerfile
Then building a binary or image release for an upcoming version from a release branch, we provide the version using `--build-arg IMAGE_TAG=...` in the Docker build step of the CI workflow ([ref](https://github.com/grafana/loki/blob/3df08bd39f45bbf8314f31a59f35b955b9a31a5e/.github/workflows/minor-release-pr.yml#L456)).
However, this argument was ignored in the Dockerfile and not further passed down to the `make ...` command inside build phase of the Dockerfile.
(cherry picked from commit 625bdabce91f1043065b582052b2c3558c9af0e6)
**Checklist**
- **Note** that Promtail is considered to be feature …
=> fix(ci): Provide correct build info for release builds (#15939)

pkg/dataobj/logs_reader.go, pkg/dataobj/logs_reader_test.go, pkg/dataobj/predicate.go, pkg/dataobj/streams_reader.go, pkg/dataobj/streams_reader_test.go
dataobj.Predicate represents some condition for filtering entries in the streams and logs sections.
The Predicate type is shared for simplicity, though some implementations of Predicate can only be used with certain readers:
* LabelMatcherPredicate and LabelFilterPredicate can only be used with StreamsReader.
* MetadataMatcherPredicate and MetadataFilterPredicate can only be used with LogsReader.
All other implementations of Predicate can be used in both Reader types.
This replaces the older API for filtering, which didn't permit doing logical ORs across labels (or timestamp ranges).
=> chore(dataobj): add predicate type for reading logs and streams

pkg/dataobj/metastore/metastore.go, pkg/dataobj/metastore/metastore_test.go
=> fix(dataobj): Fixes timerange matching for dataobj files

pkg/compactor/compactor.go, pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_manager_test.go, pkg/compactor/deletion/delete_requests_store.go, pkg/compactor/deletion/delete_requests_store_test.go, pkg/compactor/deletion/delete_requests_table.go, pkg/compactor/deletion/noop_delete_requests_store.go, pkg/compactor/deletion/request_handler.go, pkg/compactor/deletion/request_handler_test.go
We currently use botldb to store delete requests. However, because it is a key/value store that requires us to craft the KVs to store all the details, it is difficult to add more details. I am working on replacing boltdb with SQLite to store the delete requests, which would let us add more details to the requests and optimize intensive queries that cause the compactor to use too many resources.
Here is how the delete requests store interface will look:
```
type DeleteRequestsStore interface {
AddDeleteRequest(ctx context.Context, userID, query string, startTime, endTime model.Time, shardByInterval time.Duration) (string, error)
GetAllRequests(ctx context.Context) ([]DeleteRequest, error)
GetAllDeleteRequestsForUser(ctx context.Context, userID …
```
=> chore: refactor delete requests store interface to prepare for replacing boltdb with sqlite for storing delete requests

pkg/compactor/deletion/delete_requests_store.go
Remove an unused variable in the delete requests store code.
=> fix: remove unused variable in delete requests store code

pkg/dataobj/predicate_test.go, pkg/dataobj/streams_reader.go
It was correct for logs, but not for stream range.
Refactored both  and added tests.
I guess I'm not the only one cc @rfratto
=> fix(dataobj): Fixes timerange predicate

production/ksonnet/loki/multi-zone.libsonnet
Reverts grafana/loki#16064
At the time of discussion this PR didn't seem necessary, but we realised it's still the most configurable approach, reverting the revert.
=> chore: Revert the revert "fix: scheduling constraints (#16045)""

Makefile
Cleans up unused vars. Also fixes an issue that is preventing promtail builds from running with CGO_ENABLED
Fixes https://github.com/grafana/loki/issues/16220
**Checklist**
=> fix(ci): do not disable CGO in Makefile

docs/sources/shared/configuration.md, pkg/dataobj/querier/store.go, pkg/loki/modules.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/roundtrip.go, pkg/storage/config/schema_config.go
This is a bit of hack that inject a PeriodConfig in the query frontend middleware to ensure we use constant sharding for the dataobj querier when it's in use.
=> feat(dataobj): Ensure constant sharding for the dataobj querier

pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go
Calling approx_topk on some types of queries was causing a panic in the querier.
* This is because the approx_topk operation is not supported on the querier and can only be executed on the front-end and MUST be rewritten.
* In some operations, the approx_topk was not considered shardable and we did not rewrite this query. Specifically, comparison operators are not considered shardable and so skip the rewriting & cause the queriers to panic.
This PR does 2 things:
~1. Adds comparison operators to "shardableOps" map. This means they will be considered shardable and trigger the sharding logic. This is the same as the existing arithmetic operators - we don't have any special logic for them, though it doesn't really give us any benefit either.~ Removed …
=> fix(approx_topk): Map approx_topk operation in all cases

docs/sources/operations/caching.md, docs/sources/operations/query-fairness/_index.md, docs/sources/setup/install/docker.md, docs/sources/setup/install/install-from-source.md, docs/sources/setup/install/local.md, docs/sources/setup/install/tanka.md
Updates the Loki version number in installation docs, and version numbers of other various components (modeled after #15808 which last updated these files).
=> docs: Update versions in docs

docs/sources/get-started/labels/cardinality.md
Fixes broken link in Cardinality topic and removes a couple of duplicate sentences.
=> docs: fix spacing in Cardinality URL

cmd/loki/Dockerfile
Moves to the latest Alpine and Go releases for Loki 2.9.
**Checklist**
=> fix(deps): Loki 2.9.x Bump Alpine and Go versions

pkg/dataobj/querier/metadata.go, pkg/dataobj/querier/metadata_test.go, pkg/dataobj/querier/store.go, pkg/dataobj/querier/store_test.go, pkg/loki/modules.go
This change introduces logging and metrics tracking for stream processing in the dataobj querier. Key modifications include:
- Adding a logger parameter to Store and related methods
- Implementing debug logging for stream processing duration and counts
- Adding an atomic counter to track processed streams
- Enhancing logging in object selection and sharding processes
=> feat(dataobj/querier): Add logging and improve stream processing metrics

tools/stream-metadata-generator/main.go
This pull request fixes a panic in the stream generator when `err` is non-nil.
**Checklist**
=> chore: fix a panic in stream generator

docs/sources/shared/configuration.md, pkg/dataobj/builder.go, pkg/dataobj/consumer/config.go, pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/consumer/service.go
We need an idle check for our objects to be flushed, since there are cases that objects are in memory until reach the configurable size.
If we stop receiving data the size won't increase and it is not flushed.
Fixes https://github.com/grafana/loki-private/issues/1359
**Checklist**
=> chore: flush idle dataobjects after X seconds

pkg/ui/service.go
ckit  is way too chatty in large clusters.
=> chore(ui): Suppress debug log message from ckit

operator/.golangci.yaml, operator/Makefile
Fix linter config see https://github.com/grafana/loki/actions/runs/13397383118/job/37419714676?pr=16360
Changes:
- removed `maligned` as is deprecated https://golangci-lint.run/usage/configuration/#linters-configuration
- govet correctly enable shadow https://golangci-lint.run/usage/linters/#govet
- removed `exclude-rules`
**Checklist**
=> chore(operator): fix .golangci.yaml config file

production/helm/loki/templates/admin-api/deployment-admin-api.yaml, production/helm/loki/templates/admin-api/service-admin-api.yaml
While investigating the support escalation, the customer wanted to disable the adminAPI and configured enabled false but didn't work.
Looking into the helm chart, we were not checking if the enabled flag was configured and always deploying if the enterprise is enabled.
**Checklist**
=> chore(helm): add missing check for adminAPI on enterprise

pkg/distributor/distributor.go, pkg/limits/frontend/client/client.go
=> chore: Move pool factory for ingest-limits-frontend client into package

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/validation/validate.go
Modify how we handle blocked ingestion errors:
* If it is 200, don't expose any error
* Otherwise, expose the error as the configured statusCode, but only if no other validation error occur. I'm calling this a secondTierErr
Also modifying the enforced labels error message to log present labels.
**Checklist**
=> fix: Fix blocked ingestion returned error when 260

pkg/logql/engine.go, pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/querier/queryrange/roundtrip.go, pkg/util/httpreq/tags.go, pkg/util/httpreq/tags_test.go
X-Query-Tags are used to convey source information about queries, we log these values in several places already like our metrics.go lines, not too long ago we added this info to the `executing query` log line but only in the queriers and not in the frontend, this PR adds this to the frontend.
I also refactored a helper function to a different package to make it reusable in the frontend code.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature …
=> chore: log X-Query-Tags in the frontend executing query log message

go.mod, go.sum, vendor/github.com/minio/crc64nvme/crc64_amd64.s, vendor/github.com/minio/crc64nvme/crc64_arm64.s, vendor/github.com/minio/crc64nvme/crc64_other.go, vendor/modules.txt
The `arm` build has been failing, which I could trace to [PR adding an indirect dependency to github.com/minio/crc64nvme](https://github.com/grafana/loki/pull/16334). However, it did not properly handle non-asm builds. There has been a new release with a fix for this build issue. This PR updates the lib from 1.0.0 to 1.0.1 to get the fix.
=> fix: update crc64nvme to fix build issues with arm images

docs/sources/shared/configuration.md, pkg/storage/chunk/client/gcp/gcs_object_client.go
This allows users to specify a custom endpoint for GCS buckets, which might be necessary for users to comply with data locality regulations by using custom regional endpoints.
This doesn't work if the thanos objstore client is used instead, that will be tackled in a separate PR. It should be safe to add in separate PRs because the GCS configs are different in either case.
**Checklist**
=> feat: add a config option for custom GCS endpoints

pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/consumer/partition_processor_test.go, pkg/dataobj/internal/sections/streams/streams.go
The previous implementation was flushing all data that we have every X seconds, we would like to have the flush every X seconds if the stream is idle for that period.
**Checklist**
=> chore: fix flush process for dataobj

production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/overrides.libsonnet
This reverts commit 073c94c4062c1bdb91d8c87f1e299aca4b1ad801.
I'm reverting this check because the way it evaluates tenants can cause concurrent problems when generating the jsonnet manifests. For now I'm reverting to unblock future weekly releases and I'll look into a better way of implementing this check.
**Checklist**
=> fix: Revert "feat: Assert for bad `max_query_lookback` config (#16362)"

pkg/dataobj/internal/dataset/page_iter.go, pkg/dataobj/internal/dataset/page_test.go, pkg/dataobj/internal/dataset/value_encoding.go, pkg/dataobj/internal/dataset/value_encoding_bitmap.go, pkg/dataobj/internal/dataset/value_encoding_bitmap_test.go, pkg/dataobj/internal/dataset/value_encoding_delta.go, pkg/dataobj/internal/dataset/value_encoding_delta_test.go, pkg/dataobj/internal/dataset/value_encoding_plain.go, pkg/dataobj/internal/dataset/value_encoding_plain_test.go
```console
$ benchstat bench_bitmapdecoder_old.txt bench_bitmapdecoder_new.txt 
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/v3/pkg/dataobj/internal/dataset
│ bench_bitmapdecoder_old.txt │      bench_bitmapdecoder_new.txt      │
│           sec/op            │    sec/op      vs base                │
_bitmapDecoder/width=1/variance=none-8                          1.674n ±  5%    1.557n ±  6%   -6.99% (p=0.001 n=10)
_bitmapDecoder/width=1/variance=alternating-8                   1.528n ±  2%    1.727n ±  6%  +13.02% (p=0.001 n=10)
_bitmapDecoder/width=1/variance=random-8                        1.722n ±  5%    1.560n ± …
```
=> chore(dataobj): Decode values in batches

operator/bundle/openshift/metadata/properties.yaml
Updates the maximum version the OpenShift variant of the operator is compatible with.
[LOG-6467](https://issues.redhat.com/browse/LOG-6764)
**Checklist**
=> fix(operator): Update maximum OpenShift version

pkg/limits/ingest_limits.go
This PR updates the lock ordering across all internal functions to be consistent so that inconsistent views are avoided. In detail all lock ordering follows the `removePartitions` method.
**Checklist**
=> fix(ingest-limits): Consistent lock ordering

pkg/chunkenc/memchunk_test.go
Fixes the flaky test skipped in https://github.com/grafana/loki/pull/16474
**Checklist**
=> test: fix flaky multi extractor

pkg/limits/ingest_limits.go
This pull request reduces `ingest_limits.go` to a single mutex `mtx`. We don't think we need separate mutexes at this time. We can explore this again at a later time if we find this causes contention.
**Checklist**
=> chore: reduce ingest_limits.go to single mutex

pkg/limits/ingest_limits.go
This removes a check around the evicted gauge, as we want to know when there is no data to evict. Without this, it looks like we might be evicting data when in fact we are not.
**Checklist**
=> fix: remove check around evicted gauge

docs/sources/shared/configuration.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/validator.go, pkg/distributor/validator_test.go, pkg/validation/ingestion_policies.go, pkg/validation/limits.go
This PR implements global policies that are applied to all streams (regardless of their stream<>policy mappings).
- For enforced labels: the global policy labels is appended to the named policy label if the stream matches a named policy. Otherwise only the global policy labels will be enforced if any.
- For blocked ingestion: 
- If the mapped policy is empty, the global policy block is applied (if exists).
- If the mapped policy is not empty, the stream will be blocked only if there is a matching named policy block
E.g. If we have
```yaml
block_ingestion_policy_until:
"*": <eod>
policy1: <eod>
```
- stream not matching any policy --> will be blocked due to global policy
- stream matching policy1 --> will be blocked due to policy1 policy
- stream …
=> feat(policies): Support global policy

pkg/limits/ingest_limits.go, pkg/limits/ingest_limits_test.go
Stacked on https://github.com/grafana/loki/pull/16536.
**Checklist**
=> fix: spelling mistake in assignedPartitions in ingest_limits.go

.github/renovate.json5
Turns off automerge/approve for security updates.  This is because a security [update](https://github.com/grafana/loki/pull/16556/) impacted the operator `go.mod` file.  The security updates get a high precedence than individual rulesets in the renovate configuration
**Checklist**
=> chore(ci): Renovate turn off automerge/approve

pkg/dataobj/metastore/object.go
Fixes iteration condition so the stream reader does not exit early
=> chore(metastore): Fix stream read condition

.github/workflows/images.yml, Makefile
Bumps the Go version in Loki 3.4
Fixes various CVEs
**Checklist**
=> fix(deps): Move to Go 1.23.7

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/release-workflows.jsonnet, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/install_workflow_dependencies.sh, .github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet, .github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/validate-gel.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/validate.libsonnet, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml
Pulls in https://github.com/grafana/loki-release/pull/230 which will create the release branch if it doesn't exist for major and minor releases after publishing the release.
**Checklist**
=> ci: bump release lib to create branch on release

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/validator.go
Modify our push logic to not enforce labels if the current stream is the especial aggregated metric stream
**Checklist**
=> feat: Do not enforce labels vs agg metric stream

pkg/dataobj/internal/encoding/dataset_logs.go, pkg/dataobj/internal/encoding/dataset_streams.go, pkg/dataobj/internal/encoding/decoder_range.go, pkg/dataobj/internal/encoding/windowing.go, pkg/dataobj/internal/encoding/windowing_test.go
Previously, each page in a call to `ReadPages` would result in one request to storage. This added a lot of latency when data objects were backed by object storage, with the roundtrip time accumulating. 
This PR enables pages in a call to ReadPages to be batched into 16MB windows (from S3's recommendation of using [8MB or 16MB chunks](https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html); 16MB was chosen to further reduce roundtrips). Windows are currently downloaded sequentially, though this could be updated to use concurrency if desired. 
The effectiveness of this code depends on reading multiple columns and pages at once; this only happens when using dataset.Reader from #16429.
Additionally: 
* Column metadata now also …
=> chore(dataobj): Download pages in 16MB batches

pkg/dataobj/internal/dataset/predicate.go, pkg/dataobj/internal/dataset/reader.go, pkg/dataobj/internal/dataset/reader_basic.go, pkg/dataobj/internal/dataset/reader_test.go, pkg/dataobj/internal/sections/logs/iter.go, pkg/dataobj/internal/sections/streams/iter.go, pkg/dataobj/logs_reader.go, pkg/dataobj/logs_reader_test.go, pkg/dataobj/predicate_test.go, pkg/dataobj/streams_reader.go, pkg/dataobj/streams_reader_test.go
This PR replaces the implementation of dataobj.LogsReader and dataobj.StreamsReader to internally use dataset.Reader, which supports predicate pushdown to avoid unnecessary page downloads. 
This is still a WIP; some tests aren't passing yet.
=> chore(dataobj): Wire dataset.Reader into dataobj.LogsReader and dataobj.StreamsReader

docs/sources/release-notes/v2-9.md
Release Notes for Loki 2.9.12 patch release.
=> docs: Patch release notes 2.9.12

docs/sources/release-notes/v2-9.md
Backport 21cfa331312c2c15d833b7a7098450c329fcb92e from #16709
---
Release Notes for Loki 2.9.13 patch release.
=> docs: Patch release notes 2.9.13 (backport release-2.9.x)

pkg/distributor/distributor.go
This commit refactors how the distributor enforces limits to make it easier to add a dry-run mode in a subsequent PR, and also restore stream labels from stream hashes to improve error messages.
**Checklist**
=> chore: refactor how distributor enforces limits

pkg/distributor/distributor.go
This pull request updates the reasons when a request is rate limited to use the stream labels instead of the stream hash. This is so we can return more meaningful error messages to clients.
**Checklist**
=> feat: use stream labels instead of hash in rate limit reasons

pkg/dataobj/planner/physical/dataobjscan.go, pkg/dataobj/planner/physical/expressions.go, pkg/dataobj/planner/physical/expressions_test.go, pkg/dataobj/planner/physical/filter.go, pkg/dataobj/planner/physical/limit.go, pkg/dataobj/planner/physical/plan.go, pkg/dataobj/planner/physical/plan_test.go, pkg/dataobj/planner/physical/planner.go, pkg/dataobj/planner/physical/projection.go, pkg/dataobj/planner/physical/sortmerge.go, pkg/dataobj/planner/physical/visitor.go, pkg/dataobj/planner/physical/visitor_test.go
This PR adds the basic components of a physical plan. For the first iteration of the new execution engine, we need to support nodes to represent limited and filter queries (with only label/line filters). These nodes are:
* DataObjScan
* SortMerge
* Projection
* Filter
* Limit
The physical plan is implemented as a [directed acyclic graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (DAG). It has convenience functions for adding nodes (vertices) and edges, getting parents and children of a node, as well as for traversing the graph using the [depth-first-search](https://en.wikipedia.org/wiki/Depth-first_search) algorithm.
Additionally to the node types, the PR also contains the basic types of expressions, which can be properties of the nodes.
=> chore: Implement basic skeleton for a physical plan

.golangci.yml, pkg/dataobj/planner/internal/tree/printer.go, pkg/dataobj/planner/internal/tree/printer_test.go, pkg/dataobj/planner/physical/printer.go, pkg/dataobj/planner/physical/printer_test.go
This PR adds a generic tree printer (similar to the Unix utility `tree`).
Additionally it provides an implementation to convert the DAG of the physical plan into the generic tree used by the tree printer.
This allows to print plans like this (note, these examples do not make sense, they are only for demonstrating the visual output of the printer).
Simple DAG with single child node:
```
Limit #limit offset=0 limit=0
└── Filter #filter predicates=()
└── SortMerge #merge column=<nil> order=UNDEFINED
├── DataObjScan #scan1 location= stream_ids=() projections=() predicates=() direction=0 limit=0
└── DataObjScan #scan2 location= stream_ids=() projections=() predicates=() direction=0 limit=0
```
DAG with multple root nodes:
```
Limit #limit1 offset=0 …
```
=> chore: Add tree printer for physical plan

docs/sources/shared/configuration.md, pkg/distributor/distributor.go
This pull request adds a dry-run mode for checking limits in distributors. It allows the distributors to call the ingest limits service and check if the request exceeds limits, without rejecting requests that are exceeding limits.
**Checklist**
=> feat: add dry-run mode for checking limits in distributors

docs/sources/shared/configuration.md, pkg/logcli/client/file.go, pkg/logql/engine.go, pkg/logql/engine_test.go, pkg/logql/limits.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/testutil/limits.go, pkg/validation/limits.go
This allows different tenants to have different settings for multi-variant queries support, rather than a global setting.
- Removed EnableMutiVariantQueries from engine options
- Added EnableMultiVariantQueries to tenant limits config
- Updated logql Limits interface to include the new setting
- Updated query evaluation to use tenant-specific setting
- Added tests for the tenant-specific setting
**Checklist**
=> chore: convert multi-variant queries from global to per-tenant config

pkg/limits/frontend/frontend.go, pkg/limits/frontend/limits.go, pkg/limits/frontend/service.go, pkg/limits/frontend/service_test.go
Move the `Limits` interface and adapter code to it's own file.
**Checklist**
=> chore: move adapter to limits.go

pkg/dataobj/planner/logical/format_tree.go, pkg/dataobj/planner/logical/format_tree_test.go
This PR implements the logical plan specific tree formatter using the generic tree printer introduced with https://github.com/grafana/loki/pull/16716
This solves the problem that expressions, which are properties of nodes, were treated equally as the nodes' child node.
---
**Example**
Old
```
Projection id=VALUE_TYPE_UINT64 name=VALUE_TYPE_STRING
├── Column #id
├── Column #name
└── Filter expr=age_gt_21
├── BinaryOp type=cmp op=(>) name=age_gt_21
│   ├── Column #age
│   └── Literal value=21 type=VALUE_TYPE_INT64
```
New
```
Projection id=VALUE_TYPE_UINT64 name=VALUE_TYPE_STRING
│   ├── Column #id
│   └── Column #name
└── Filter expr=age_gt_21
│   └── BinaryOp type=cmp op=">" name=age_gt_21
│       ├── Column #age
│       └── Literal value=21 …
```
=> chore: Implement the logical plan formatter using the generic tree printer

README.md
This PR updates the "Loki stack" to include Alloy instead of Promtail.
It also adds the convenience `make` command in the "Building from source" section.
=> chore(docs): Update stack and build commands in README

pkg/limits/frontend/config.go, pkg/limits/frontend/frontend.go
=> chore: move config struct to it's own file

pkg/distributor/field_detection.go, pkg/distributor/field_detection_test.go
Log lines such as `[DEBUG] foo bar baz` were not getting detected as debug log lines because the current detection expected a `:`. This seems unnecessarily specific, as putting the level in brackets is a common enough practice for unstructured logs.
**Checklist**
=> fix: remove colons from level detection

docs/sources/community/lids/0005-loki-mixin-configuration-improvements.md, docs/sources/send-data/alloy/_index.md
(cherry picked from commit 93301ee284b610689a208e79f15c4b45bf406271)
manual backport of https://github.com/grafana/loki/pull/16748 to the 3.3 branch to fix broken link.  Also includes backport of https://github.com/grafana/loki/pull/16692 to 3.3 branch.
=> docs: fix broken links (#16748)

pkg/limits/frontend/ring.go
No change to behavior (covered with tests), just some clean up.
**Checklist**
=> chore: clean up perReplicaSetPartitions in ring.go

pkg/limits/frontend/ring.go
This commit fixes a data race I added to `getConsumedPartitions` changing it from a slice to a map. This changes it back, avoiding the need to use a mutex as the size is calculated ahead of time and we don't use append.
**Checklist**
=> fix: fixes a data race I added changing this to a map

pkg/dataobj/explorer/inspect.go, pkg/ui/frontend/src/components/explorer/file-metadata.tsx, pkg/ui/frontend/src/types/explorer.ts
**What this PR does / why we need it**:'
Adds tile to Explorer UI showing stream distribution over time within a dataobj
* Shows number of streams containing logs for each hour of the object's time span.
* Shows the full time range (hovering shows the exact dates)
* I added this due to observing that most objects contain the majority of streams within the most recent 1h, but also contain a few much older streams spanning much larger time windows. This just makes it easier to inspect an object.
Fixes https://github.com/grafana/loki-private/issues/1429
=> feat(dataobj-explorer): Add stream distribution info to dataobj explorer UI

pkg/limits/frontend/http.go, pkg/limits/frontend/http_test.go, pkg/limits/frontend/mock_test.go
This pull request fixes a panic in `ServeHTTP` where nil was appended to a slice by mistake.
**Checklist**
=> fix: fix a panic in ServeHTTP where stream was nil

pkg/limits/frontend/frontend.go, pkg/limits/frontend/frontend_test.go
This pull request fixes a bug where known streams could be rejected whenever stream limit was exceeded. The bug occurred when streams for a tenant were sharded over a number of partitions. The problem was that the frontend did not take the intersection of unknown streams from all responses, so if a stream was unknown on instance1, but known to instance2, it would still be rejected.
**Checklist** …
=> fix: bug where known streams could be rejected

pkg/limits/frontend/http.go, pkg/limits/frontend/http_test.go
=> chore: rename structs to use http prefix to differentiate from logproto

pkg/limits/frontend/frontend.go, pkg/limits/frontend/frontend_test.go
This commit updates the frontend to return all reasons a stream was rejected. For example, in the case where a stream was both rate limited and exceeded the maximum number of active streams, both of these errors will now be returned in the same response.
**Checklist**
=> feat: return all reasons a stream was rejected from the frontend

pkg/limits/http.go, pkg/loki/modules.go
Use `ingest-limits` as the prefix to match other services where the service name is used, and use path variables instead of query strings to get the tenant.
**Checklist**
=> chore: update the HTTP debug routes for ingest-limits

pkg/limits/http.go, pkg/limits/http_test.go
Added unit tests for `ServeHTTP` in limits service.
**Checklist**
=> chore: write unit tests for ServeHTTP in limits service

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl
The following headers are only logged with Grafana Enterprise Logs: 
The following headers are available and what they map to in the log line if present: 
- `X-Grafana-User`
- `X-Dashboard-Uid`
- `X-Dashboard-Title`
- `X-Panel-Id`
- `X-Panel-Title`
- `X-Rule-Uid`
- `X-Rule-Name`
- `X-Rule-Folder`
- `X-Rule-Version`
- `X-Rule-Source`
- `X-Rule-Type`
This changes adds support to log these headers if they are present in the request by adding them to the `X-Query-Tags` header as key/value pairs, which will automatically log them with `metrics.go` log messages, which is very useful for debugging/troubleshooting queries. 
The keys are mapped as follows:
- `X-Grafana-User` -> `user`
- `X-Dashboard-Uid` -> `dashboard_id`
- `X-Dashboard-Title` -> …
=> feat: helm log headers nginx config

docs/sources/shared/configuration.md, pkg/ruler/base/compat.go, pkg/ruler/base/ruler_test.go, pkg/ruler/registry.go, pkg/ruler/registry_test.go, pkg/ruler/storage/instance/instance.go, pkg/ruler/storage/wal/wal.go, pkg/ruler/storage/wal/wal_test.go, pkg/validation/limits.go
This change adds the ability to disable WAL replay for specific tenants through ruler_enable_wal_replay tenant override. Disabling WAL replay helps prevent OOM crashes for tenants with large WALs, as it skips loading all series into memory during startup. We are currently only replaying the WAL so we can reuse the series ID, we are not actually replaying any metrics into the remote write target. Having the WAL is still beneficial to handle periods when the remote write server cannot be reached, but the benefit we're gaining from replaying the WAL is minimal considering it frequently causes the rulers to OOMs.
- Added ruler_enable_wal_replay flag to Limits and Overrides
- Modified WAL storage to accept enableReplay parameter
- Updated ruler registry …
=> feat(ruler): add per-tenant configuration to disable WAL replay

pkg/compactor/compactor.go, pkg/compactor/deletion/delete_request.go, pkg/compactor/deletion/delete_request_test.go, pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_manager_test.go, pkg/compactor/retention/expiration.go, pkg/compactor/retention/expiration_test.go, pkg/compactor/retention/retention.go, pkg/compactor/retention/retention_test.go, pkg/compactor/retention/series.go, pkg/compactor/retention/util_test.go, pkg/compactor/testutil.go, pkg/storage/stores/shipper/indexshipper/boltdb/compactor/compacted_index.go, pkg/storage/stores/shipper/indexshipper/boltdb/compactor/compacted_index_test.go, pkg/storage/stores/shipper/indexshipper/boltdb/compactor/index.go, pkg/storage/stores/shipper/indexshipper/boltdb/compactor/iterator.go, pkg/storage/stores/shipper/indexshipper/boltdb/compactor/iterator_test.go, pkg/storage/stores/shipper/indexshipper/boltdb/compactor/series.go, pkg/storage/stores/shipper/indexshipper/tsdb/compactor.go, pkg/storage/stores/shipper/indexshipper/tsdb/compactor_test.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/chunk.go, pkg/tool/audit/audit.go, pkg/tool/audit/audit_test.go, tools/tsdb/tsdb-map/main.go
An intensive delete request can take too long to process, which can hold the table for too long and lead to compaction being blocked. To avoid that, we have a config limiting how much time retention/deletion can work on a table. When the timeout is hit, we stop processing the delete request to let it attempt again in the next retention run. However, since we did not have any saved progress, it would start processing all the chunks again which were already processed during the previous run. This led to an endless loop, causing delete request processing to get stuck and an unnecessary waste of resources.
This PR supports storing the details of already processed streams in the delete requests manager. Using this progress, we can easily skip the streams …
=> feat: store details of processed streams while processing delete requests

pkg/dataobj/logs_reader.go, pkg/dataobj/predicate.go, pkg/dataobj/querier/store.go, pkg/dataobj/querier/store_test.go, pkg/engine/planner/internal/tree/printer.go, pkg/engine/planner/physical/expressions.go, pkg/limits/ingest_limits_test.go
Currently we configure `TimeRangePredicate` on the logs reader to  only process log lines for the desired time range. 
We can further save compute by configuring line and label filters as predicates to only process the matching log lines. This PR adds support to configure `LogMessageFilterPredicate` based on line filter expressions. It also removes the applied filter from the original query plan to avoid the redundant work. Line filters appearing after `line_format` stage are not configured as predicates as it modifies the resulting log line.
**Checklist** …
=> chore(dataobj): pass down line filters to logs reader

tools/promtail.sh
While it is possible to override the version using the `PROMTAIL_VERSION` environment variable, the default should point to the latest release.
=> chore: Update default `VERSION` in `tools/promtail.sh` to latest

pkg/kafka/partition/reader.go
The `lastCommittedOffset` metric wasn't even registered, should be removed from `readerMetrics`.
**Checklist**
=> chore: remove unused metric

pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go
Streams that include the `__aggregated_metric__` label shouldn't be counted towards UsageTracker bytes ingested for tenants.
N/A
N/A
**Checklist**
=> fix: Exclude aggregated metric streams from usage trackers in loghttp/push

pkg/kafka/partition/reader.go
This renames the variable for two reasons:
1. It matches the metric name
2. I want to add a second metric that tracks consumption lag offset, not just seconds
**Checklist**
=> chore: rename consumption lag variable

pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go
re:
- https://github.com/grafana/loki/pull/16862
This PR cherry-picks 4029561088672ca48b9006db257be20663b7cd2b from `main` onto `k247` to fix a bug with usage trackers.
N/A
N/A
**Checklist**
=> fix: Exclude aggregated metric streams from usage trackers in loghttp/push (#16862)

pkg/kafka/partition/reader.go
This pull request reverts #16864. It has a number of problems such as the gauge still being omitted when the phase changes. I would like to revert it and then explore it further before keeping it as a gauge.
**Checklist**
=> chore: revert changing histogram to gauge

pkg/limits/ingest_limits.go
This pull request fixes a bug where the histogram could not measure more than 10 seconds of lag, as `DefBuckets` stops at `10`. We need to use `ExponentialBuckets` like the other consumption lag metrics.
**Checklist**
=> fix: histogram could measure up to 10 seconds of consumption lag, needs exponential buckets

docs/sources/shared/configuration.md, pkg/dataobj/builder.go, pkg/dataobj/builder_test.go, pkg/dataobj/consumer/partition_processor_test.go, pkg/dataobj/internal/dataset/column_reader.go, pkg/dataobj/internal/dataset/page.go, pkg/dataobj/internal/dataset/page_reader.go, pkg/dataobj/internal/dataset/reader.go, pkg/dataobj/internal/dataset/reader_basic.go, pkg/dataobj/internal/sections/logs/iter.go, pkg/dataobj/internal/sections/logs/logs.go, pkg/dataobj/internal/sections/logs/logs_test.go, pkg/dataobj/internal/sections/logs/table_merge.go, pkg/dataobj/internal/sections/streams/iter.go, pkg/dataobj/logs_reader.go, pkg/dataobj/logs_reader_test.go, pkg/dataobj/metastore/object.go, pkg/dataobj/metastore/object_test.go, pkg/dataobj/metastore/updater.go, pkg/dataobj/querier/metadata.go, pkg/dataobj/querier/store.go, pkg/dataobj/querier/store_test.go, pkg/dataobj/streams_reader.go, pkg/engine/planner/internal/tree/printer.go, pkg/engine/planner/physical/expressions.go, pkg/limits/ingest_limits_test.go, pkg/logql/bench/store_dataobj.go
Merging logs stripes was causing OOMs at scale. We found this to be for two main reasons:
* Zstd decoders were not always being released back into the pool. Creating new decoders is expensive, so releasing them back into the pool will help relieve memory pressure. 
* Merging all stripes at once has a significant overhead. 
This PR helps ensure that all Zstd decoders are released back into the pool and can be reused, and additionally adds a new config option to limit how many stripes are merged at once when forming a section, allowing operators to trade off between total flush time and total memory overhead.
=> chore(dataobj): reduce memory overhead of merging logs stripes

pkg/limits/ingest_limits.go
This pull request backports #16886 and #16897 to `k247` so we can track consumption lag in the ingest limits service.
**Checklist**
=> chore: backport #16886 and #16897 to k247

pkg/limits/evict.go, pkg/limits/evict_test.go
This commit adds an evictor abstraction that will run the eviction of stale streams. The reason for abstracing it is two reasons:
1. It is easier to test
2. It will allow us to parallelize eviction over shards of metadata (for example, one per partition) to increase parallelism and reduce lock contention.
**Checklist**
=> feat: add evictor

.github/workflows/helm-weekly-release-pr.yaml
No one is using the weekly version of the helm chart. If people want the weekly, they can just override the image value in the standard release anyway.
**Checklist**
=> ci: remove weekly k-version of helm release

docs/sources/shared/configuration.md, pkg/storage/bucket/client.go
Allow dashes in storage_prefix config of thanos object storage config so we have parity with previous `object_prefix` config.
Fixes #16931
**Checklist**
=> fix: Allow dashes in storage_prefix config

pkg/pattern/aggregation/push.go, pkg/pattern/aggregation/push_test.go, pkg/pattern/ingester_test.go, pkg/pattern/instance.go
Before this change, the pattern ingester pushed aggregated metrics as an indexed label. This is unnecessary as drilldown assumes all detected levels will be in structured metadata (which the indexed label will be stored as during level detection in the distributor). This is also problematic, as levels used for aggregated metrics will show up in the `/label/level/values` endpoint. For users who enforce policies around level, like all caps, then the values added by aggregated metric will be confusing. Finally, indexing the level also increases the cardinality of these streams unecessarily.
This PR changes the pattern ingester to send the detected level as structured metadata, which fixes all the problems listed above.
**Checklist**
- **Note** that …
=> fix: pattern ingester pushes detected level as structured metadata

docs/sources/query/logcli/getting-started.md
Fix logcli docs linking to localhost
**Which issue(s) this PR fixes**
-
-
**Checklist**
=> docs: fix localhost link in logcli getting-started 

clients/pkg/promtail/scrapeconfig/scrapeconfig.go, clients/pkg/promtail/targets/lokipush/pushtarget.go, docs/sources/setup/upgrade/_index.md, docs/sources/shared/configuration.md, pkg/distributor/distributor.go, pkg/distributor/http.go, pkg/distributor/http_test.go, pkg/ingester/kafka_consumer.go, pkg/loghttp/push/otlp.go, pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go, pkg/util/http.go, pkg/validation/validate.go
This PR introduces a config option to control the max received message size for uncompressed data. The default is set to `100 MB`. Previously the code base allowed up to `2 GB` which per push request which is obviously a long-time hanging hindsight. 
**Checklist**
=> feat(distributor): Add MaxRecvMsgSize config for uncompressed message size limits

pkg/engine/internal/types/column.go, pkg/engine/internal/types/operators.go, pkg/engine/planner/logical/builder.go, pkg/engine/planner/logical/logical.go, pkg/engine/planner/logical/node_limit.go, pkg/engine/planner/logical/planner.go, pkg/engine/planner/logical/planner_test.go, pkg/engine/planner/physical/limit.go
Minimal implementation of the logical planner that converts a parsed LogQL statement in AST form into a logical plan in SSA form.
The branch of this PR is based off `chaudum/physical-planner-v2` (#16891).
**Example**
The LogQL query
```
{cluster="prod", namespace=~"loki-.*"} | foo="bar" or bar="baz" |= "metric.go" |= "foo" or "bar" !~ "(a|b|c)"
```
gets converted into the logical plan
```
%1 = EQ label.cluster, "prod"
%2 = MATCH_RE label.namespace, "loki-.*"
%3 = AND %1, %2
%4 = MAKE_TABLE [selector=%3]
%5 = SORT %4 [column=builtin.timestamp, asc=true, nulls_first=false]
%6 = GTE builtin.timestamp, 1000
%7 = SELECT %5 [predicate=%6]
%8 = LT builtin.timestamp, 2000
%9 = SELECT %7 [predicate=%8]
%10 = MATCH_STR …
```
=> chore(planner): Convert AST into logical plan

pkg/engine/internal/types/column.go, pkg/engine/internal/types/literal.go, pkg/engine/internal/types/literal_test.go, pkg/engine/internal/types/value.go, pkg/engine/planner/logical/column_ref.go, pkg/engine/planner/logical/format_tree_test.go, pkg/engine/planner/logical/logical_test.go, pkg/engine/planner/logical/node_literal.go, pkg/engine/planner/logical/planner.go, pkg/engine/planner/physical/expressions.go, pkg/engine/planner/physical/expressions_test.go, pkg/engine/planner/physical/planner.go, pkg/engine/planner/physical/planner_test.go
Literals and column refs are used by both the logical and physical plan. However, the interfaces they need to implement are partly private (`isValue()` and `isExpression()`).
Therefore they are wrapped in their own struct that implement these interfaces.
PR is based off `chaudum/convert-ast-to-logical-plan` (https://github.com/grafana/loki/pull/16916).
=> chore(engine): Unify `Literal` and `ColumnRef` across logical and physical plan

pkg/engine/planner/physical/expressions.go, pkg/engine/planner/physical/limit.go, pkg/engine/planner/physical/optimizer.go, pkg/engine/planner/physical/optimizer_test.go, pkg/engine/planner/physical/plan.go, pkg/engine/planner/physical/planner.go, pkg/engine/planner/physical/planner_test.go, pkg/engine/planner/physical/printer.go
This PR adds a plan optimizer that pushes down limit and filter predicates to the scan node.
Plan:
```
Limit #0xc0000110f8 offset=0 limit=1000
└── Filter #0xc00039dd10
│   └── Predicate expr=LT(timestamp.builtin, 1742826126000000000)
└── Filter #0xc00039ddd0
│   └── Predicate expr=GT(age.metadata, 21)
└── SortMerge #0xc00039de60 column=timestamp.builtin order=ASC
├── DataObjScan #0xc00011b420 location=obj1 stream_ids=(1, 2) projections=() direction=0 limit=0
└── DataObjScan #0xc00011b490 location=obj2 stream_ids=(3, 4) projections=() direction=0 limit=0
```
Optimized plan:
```
Limit #0xc0000110f8 offset=0 limit=1000
└── SortMerge #0xc00039de60 column=timestamp.builtin order=ASC
├── DataObjScan #0xc00011b420 location=obj1 stream_ids=(1, 2) projections=() direction=0 limit=1000
│       ├── …
```
=> chore(engine): Add simple plan optimizer

pkg/distributor/field_detection.go, pkg/distributor/field_detection_test.go
Reverts grafana/loki#16764
This does detect all loglines containing `referrer` as `error` log lines.
=> fix: revert remove colons from level detection

pkg/logql/bench/bench_test.go
benchstat supports changing the "row" and "column" based on a key=value pair naming convention, where key-value pairs are separated by slashes.
Changing the test names to match these conventions such that
BenchmarkLogQL/QUERY/STORE
becomes
BenchmarkLogQL/query=QUERY/store=STORE
allows for cross-store analysis of benchmark results:
benchstat -row /query -col '/store@(chunk dataobj)' FILE
=> chore(logql/bench): use benchstat naming conventions for benchmarks

pkg/engine/planner/internal/tree/mermaid.go, pkg/engine/planner/internal/tree/mermaid_test.go, pkg/engine/planner/internal/tree/printer.go, pkg/engine/planner/internal/tree/printer_test.go, pkg/engine/planner/internal/tree/tree.go, pkg/engine/planner/logical/format_tree.go, pkg/engine/planner/logical/format_tree_test.go, pkg/engine/planner/logical/logical_test.go, pkg/engine/planner/logical/node_binop.go, pkg/engine/planner/logical/node_limit.go, pkg/engine/planner/logical/node_maketable.go, pkg/engine/planner/logical/node_return.go, pkg/engine/planner/logical/node_select.go, pkg/engine/planner/logical/node_sort.go, pkg/engine/planner/logical/node_unaryop.go, pkg/engine/planner/logical/planner_test.go, pkg/engine/planner/logical/printer.go, pkg/engine/planner/physical/printer.go
This allows to return a [Mermaid](https://mermaid.js.org) diagram of the logical and physical plan via an API endpoint.
Example output visualised by a JS engine:
=> chore(engine): Add printer for Mermaid diagram format

pkg/loghttp/push/push.go
To assist with tracking push agent latency, we have a mostRecentLagMs logged message in distributors which includes the difference of timestamps (in millis) between when a push request is received and the most recent timestamp of the log content being pushed.
The logged message, however, doesn't include the IP address of the agent. As a result, it's difficult to correlate increased latency for a given agent.
This commit extracts IP addresses from the `X-Forwarded-For` HTTP header in the distributor.ParseRequest function.  The value is appended to the push request log line, along with the first agent IP address parsed from the header.
Provides better identification of agents w/their lag times in the distributor …
=> feat: Add agent IPs to distributor log

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v5/README.md, vendor/github.com/golang-jwt/jwt/v5/SECURITY.md, vendor/github.com/golang-jwt/jwt/v5/parser.go, vendor/github.com/golang-jwt/jwt/v5/token.go, vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go, vendor/golang.org/x/oauth2/oauth2.go, vendor/modules.txt
Updating dependencies for 3.3.x release that will cover CVE.
Fixes https://github.com/grafana/loki-private/issues/1517
**Checklist**
=> chore: update dependencies on 3.3.x

pkg/analytics/seed_test.go
This test has flaked on me not [1](https://github.com/grafana/loki/actions/runs/14222770309/job/39854780985?pr=17003), not [2](https://github.com/grafana/loki/actions/runs/14202511042/job/39792537244), but [3](https://github.com/grafana/loki/actions/runs/14225082296/job/39862597619) times just today.
=> ci: skip flaky analytics test

pkg/distributor/field_detection.go, pkg/distributor/field_detection_test.go
https://github.com/grafana/loki/pull/16924 changed how the pattern ingester sends the detected level back into the distributors for aggregated metrics. However, the distributors weren't actually checking if `detected_level` was already set in structured metadata, and therefore was still trying to do it's own level detection. This worked against my test data locally, as the original services had indexed level fields that showed up in the aggregated metric log line, but this very much didn't work in many other places :(
For example, I broke our ops environment real good. See all the unknown levels, and when I started running the custom image on distrubtors to test my change.
**Checklist**
- **Note** that Promtail is considered to be feature complete, …
=> fix: short circuit level detection when already detected

pkg/dataobj/metastore/metastore.go, pkg/dataobj/metastore/object.go, pkg/dataobj/metastore/object_test.go, pkg/engine/internal/types/literal.go, pkg/engine/planner/logical/column_ref.go, pkg/engine/planner/logical/format_tree.go, pkg/engine/planner/logical/node_literal.go, pkg/engine/planner/physical/context.go, pkg/engine/planner/physical/context_test.go, pkg/engine/planner/physical/expressions.go, pkg/engine/planner/physical/expressions_test.go, pkg/engine/planner/physical/optimizer.go, pkg/engine/planner/physical/planner.go, pkg/engine/planner/physical/planner_test.go
This PR integrates the data object lookup using the metastore into the query planning.
To achieve that, I extended the `Metastore` interface with an additional function that not only returns the data object paths, but also the stream IDs of streams that match the given label matchers.
```go
type Metastore interface {
...
// StreamsIDs returns object store paths and stream IDs for all matching objects for the given matchers between [start,end]
StreamIDs(ctx context.Context, start, end time.Time, matchers ...*labels.Matcher) ([]string, [][]int64, error)
...
}
```
=> chore(engine): Integrate metastore into physical query planning

operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml
This PR adds configuration to update the ingester memberlist immediately when an ingester becomes unhealthy. It also adds configuration, so that the ingester will rejoin the memberlist using discovery when the network connection becomes available again.
- Fixes #15702, [LOG-6987](https://issues.redhat.com/browse/LOG-6987)
- Workaround for [LOG-6968](https://issues.redhat.com/browse/LOG-6968)
**Checklist**
=> fix(operator): Update memberlist when ingester becomes unhealthy

production/helm/loki/scenarios/ingress-values.yaml, production/helm/loki/scenarios/legacy-monitoring-values.yaml, production/helm/loki/templates/gateway/deployment-gateway-nginx.yaml
The gateway nginx deployment was applying the loki annotation values and the gateway values.
This can cause a configuration error since the gateway container is not a loki container with the same ports.
Inside Enterprise gateway we already use only the gateway annotations.
Fixes #16918 
**Checklist**
=> chore: remove loki annotations from gateway nginx deployment

pkg/logql/bench/bench_test.go, pkg/logql/bench/cmd/bench/views/run.go, pkg/logql/bench/generator_query.go, pkg/logql/bench/store_chunk.go
This PR fixes a bug found in generating test data for chunks: `MemChunks` weren't being closed properly before flushing, which caused the last block of every chunk to be omitted from the flush. As a result, benchmark tests against chunks were inaccurate, causing many metric queries to appear 5-10x faster with chunks than they actually are. 
Additionally, this PR expands on #17006 with another naming convention change: the type of query is now included in the benchmark name to allow developers to only run benchmarks of a specific query type (metric, log). 
PR #17006 neglected to reflect the naming convention change in the benchmark TUI, which stopped it from working. This is now fixed to match the latest naming convention introduced in this PR, and the TUI will now work again.
=> chore(logql/bench): Fix bug in bench data generation and update naming conventions

pkg/distributor/http.go, pkg/distributor/http_test.go
re:
- https://github.com/grafana/loki/commit/1d99f4d86d25a361fc85162fadb21a78308d65d4
We encountered an edge case where Distributors panic when trying to increment their DiscardedBytes metrics for large request bodies:
`panic: counter cannot decrease in value`
N/A
N/A
**Checklist**
=> fix: prevent panic when ContentLength is negative in Distributor RequestBodyTooLarge metrics

pkg/dataobj/metastore/metastore_test.go, pkg/dataobj/metastore/object.go, pkg/dataobj/metastore/updater.go
This PR contains improvements for:
1. Make label names contants
2. Use `strconv.FormatInt` for encoding timestamp into label value (equivalent to `strconv.ParseInt` when decoding)
3. Use `labels.New` to construct labels, rather then string formatting
=> chore(metastore): Use constants for label names

pkg/distributor/http.go, pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go
Prevents panics in `push` Prometheus counters when negative values are passed to Add(). Added guard clauses to both LogLinesBytes and StructuredMetadataBytes processing in ParseRequest, plus a test case that verifies the fix.
The issue can arise when processing X-Forwarded-For header, which might cause negative size calculations in certain cases.
N/A
N/A
**Checklist**
=> fix(push): Add guard clauses to prevent negative counter values

pkg/loghttp/entry.go, pkg/loghttp/entry_test.go, pkg/loghttp/query.go
Fixes an issue which caused improper escaping while ingesting using the JSON API + structured metadata
closes https://github.com/grafana/loki/issues/13918
new example:
```
curl -H 'Content-Type: application/json' -d '{"streams": [{"stream": {"service_name":"test"},"values":[["1744138406570175000", "{}", {"message": "a\nb\nc"}]]}]}' -v 'http://127.0.0.1:3100/loki/api/v1/push'
< HTTP/1.1 204 No Content
curl -v 'http://127.0.0.1:3100/loki/api/v1/query_range?query=%7Bservice_name%3D%22test%22%7D&start=1744138406570175000' | jq .data.result
[
{
"stream": {
"detected_level": "unknown",
"message": "a\nb\nc",
"service_name": "test"
},
"values": [
[
"1744138406570175000",
"{}"
]
]
}
]
```
=> fix(json, structured metadata): correctly handle escaping in json parsing API

pkg/loghttp/push/push_test.go, pkg/loghttp/query.go
In the case of strings, `ObjectEach` strips the quotes but does not unescape them.
Fixes #13918
Fixes #13918
**Checklist**
=> fix: Unescape JSON strucutred metadata string values

pkg/distributor/http.go, pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go
Backport 9000de1aa7a6508234ee58adb346549ac3df2648 from #17056
---
Prevents panics in `push` Prometheus counters when negative values are passed to Add(). Added guard clauses to both LogLinesBytes and StructuredMetadataBytes processing in ParseRequest, plus a test case that verifies the fix.
The issue can arise when processing X-Forwarded-For header, which might cause negative size calculations in certain cases.
N/A
N/A
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the …
=> fix(push): Add guard clauses to prevent negative counter values (backport k249)

pkg/ingester/flush_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
Credits to @Di-Is who opened #9734. This PR fixes #9729 with Di-Is suggestion with the latest changes from Loki.
Unlike other functions (Query, Label...), ingester's series function does not have a function to retrieve data from storage.
Because of this, the series included in the response of the series API is missing, so implement the function described above.
Fixes #9729 
@chaudum superseed #9734 which is now rebased on main branch 
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can …
=> fix: add a process to ingester's series function to get series from storage

pkg/storage/stores/shipper/indexshipper/tsdb/head_read.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/index.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/index_test.go, pkg/storage/stores/shipper/indexshipper/tsdb/querier.go, pkg/storage/stores/shipper/indexshipper/tsdb/single_file_index.go
We are seeing OOMKills on index gateways due to a huge amount of allocations from [LabelValues](https://github.com/grafana/loki/blob/5625464332fc0b3371b744d60d36acaf2600665a/pkg/storage/stores/shipper/indexshipper/tsdb/index/index.go#L1631) method of tsdb index reader. It happens due to copying all the label values read from the tsdb. [This problem arises when the label matchers have any negative matchers](https://github.com/grafana/loki/blob/5625464332fc0b3371b744d60d36acaf2600665a/pkg/storage/stores/shipper/indexshipper/tsdb/querier.go#L175-L191).
I have changed the code to avoid making a copy of the label values unless we want to send it back as a response. I have checked all the usages of that method, and the only place we need to copy the …
=> fix: avoid copying label values from tsdb unless required

pkg/limits/ingest_limits.go
This PR introduces the `CooperativeStickyBalancer` strategy for ingest-limits in parallel to the existing `StickyBalancer`. The purpose is to leverage partition consumption while rebalancing in progress. This is step one of the two migration steps.
**Checklist**
=> chore(ingest-limits): Rollout using both balancers

pkg/querier/multi_tenant_querier_test.go, pkg/querier/queryrange/codec_test.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/queryrangebase/promql_test.go, pkg/querier/queryrange/queryrangebase/test_utils.go, pkg/querier/queryrange/queryrangebase/test_utils_test.go, pkg/querier/queryrange/queryrangebase/value_test.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/views_test.go
This is the first step of support Prometheus `stringlabels` implementation in Loki. 
**Checklist**
=> refactor(stringlabels): Support stringlabels in querier tests

pkg/compactor/compactor.go, pkg/compactor/retention/expiration.go, pkg/compactor/retention/retention.go, pkg/compactor/retention/retention_test.go
We introduced tracking of delete request stream processing in PR https://github.com/grafana/loki/pull/16825.
However, I likely made a mistake in rearranging commits and lost some code for wiring things up 🤦 
I have fixed the code so that the stream tracker is updated.
=> fix: wire up deletion series progress tracking

docs/sources/shared/configuration.md, pkg/blockbuilder/builder/builder.go, pkg/dataobj/consumer/service.go, pkg/kafka/client/reader_client.go, pkg/kafka/client/writer_client.go, pkg/kafka/config.go, pkg/kafka/partition/offset_manager.go, pkg/kafka/partition/reader.go, pkg/kafka/partition/reader_service.go, pkg/limits/ingest_limits.go
Introduces a new config option for kafka clients to enable (or disable) read/write wait and timing histograms.  These are not enabled by default, so this change introduces a new CLI flag and YAML opt which configures the collected metrics to include/exclude historgams.
This PR includes updating the dataobj, blockbuilder (deprecated), and ingest limits so they can take advantage of these collected metrics and monitor latency when reading from and writing to kafka.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a …
=> feat: Optionally enable kafka histograms for read/write latency

pkg/loghttp/entry_test.go, pkg/loghttp/query_test.go, pkg/pattern/aggregation/push_test.go, pkg/ruler/base/notifier_test.go, pkg/ruler/base/ruler_test.go, pkg/ruler/memstore_test.go, pkg/ruler/storage/instance/instance_test.go, pkg/ruler/storage/wal/wal_test.go, pkg/util/conv.go, pkg/util/metrics_helper.go
This is a next step of support Prometheus `stringlabels` implementation in Loki. It adds support in tests of `loghttp`, `pattern` and `ruler`.
**Checklist**
=> refactor(stringlabels): Support stringlabels in loghttp, pattern and ruler tests.

pkg/distributor/distributor.go, pkg/distributor/ingest_limits.go, pkg/distributor/ingest_limits_test.go
Fix package private interface `ingestLimitsFrontendClient` and struct `ingestLimits` having exported methods.
**Checklist**
=> chore: fix private interface had exported methods

pkg/distributor/ingest_limits.go, pkg/distributor/ingest_limits_test.go
This pull request adds a new method to ingest_limits.go to enforce limits against a slice of streams. It returns the streams within the limits, and in the case where one or more streams exceed per-tenant limits, the reasons those streams were not included in the result.
This pull request is stacked on top of https://github.com/grafana/loki/pull/17112.
**Checklist** …
=> feat: add enforceLimits to ingest_limits.go

pkg/dataobj/querier/iter.go, pkg/logql/bench/bench_test.go
Connects dataobj querier to the existing stats object for a very limited set of metrics.
* I didn't modify the object at all, so ChunksDownloaded refers to Dataobj Sections accessed.
* This is quick and dirty to get an idea of whats going on - I will look to embed this into more closely into dataobjs in more iterations.
* I connected them to the benchmark as custom metrics which gives nice output for comparing between chunks & dataobjs:
```
goos: darwin
goarch: arm64
cpu: Apple M3 Max
BenchmarkLogQL
BenchmarkLogQL/query={region="ap-southeast-1"}_[FORWARD]/kind=log/store=dataobj
BenchmarkLogQL/query={region="ap-southeast-1"}_[FORWARD]/kind=log/store=dataobj-14         	       1	20510124250 ns/op …
```
=> chore: Collect basic stats from dataobj queries

pkg/ingester/checkpoint_test.go, pkg/ingester/flush_test.go, pkg/ingester/instance_test.go, pkg/ingester/kafka_consumer_test.go, pkg/ingester/mapper_test.go, pkg/ingester/recalculate_owned_streams_test.go, pkg/ingester/recovery_test.go, pkg/ingester/stream_test.go, pkg/ingester/streams_map_test.go, pkg/ingester/tailer_test.go
This is a next step of support Prometheus `stringlabels` implementation in Loki. It adds support in `ingester` tests.
**Checklist**
=> refactor(stringlabels): Support stringlabels ingester tests

pkg/logql/log/labels.go, pkg/logql/log/parser.go, pkg/logql/log/parser_hints.go, pkg/logql/log/parser_test.go
PR #8724 originally changed the behaviour of LogQL so that the first extracted field takes precedence over any later extracted field with the same name.
However, this PR had two subtle issues due to the caching that parse stages perform for key lookups:
* The precedence logic did not always apply to duplicate fields within the same parse stage (notably for logfmt).
* The caching behaviour could incorrectly cause stages to permanently ignore fields for future log lines where that stage should otherwise perform extraction.
Additionally, once structured metadata was introduced, it was incorrectly being flagged as an "extracted field." Combined with the caching behaviour described above, this means that parsed fields only take precedence over structured metadata if the first log line …
=> fix(logql): Fix inconsistency with parsed field short circuiting

pkg/dataobj/internal/sections/logs/iter.go, pkg/dataobj/internal/sections/logs/iter_test.go, pkg/dataobj/internal/sections/logs/logs_test.go, pkg/dataobj/internal/sections/streams/iter.go, pkg/dataobj/internal/sections/streams/streams_test.go, pkg/dataobj/querier/iter.go, pkg/dataobj/streams_reader_test.go, pkg/logql/bench/bench_test.go
There were some small inconsistencies between chunks and dataobjs when evaluating the benchmark queries, making it hard to evaluate whether the becnhmark truly reflected performance differences between the two storage formats.
This commit adds a test to check the output of each query for each store, and compare it against the expected baseline (chunks).
Because this test is slow and requires generating the data, a new -slow-tests flag has been added to the pkg/logql/bench package. This test will be ignored if that flag isn't present.
This also means that CI will not run these tests by default, and we would need to set up a new pipeline if we wanted them to be ran (which would include generating the test data).
=> chore: align benchmark results between chunks and dataobjs

pkg/logql/bench/store_chunk.go
The timestamp bounds of a chunk are used to update the query range bounds; the previous code always truncated the bounds down, which caused backwards queries to ignore the latest log line in a chunk if that log line was less than a millisecond beyond the truncated timestamp.
I missed this in #17104, because I previously had this fix, generated the dataset with it, and then removed the fix was removed after I thought it wasn't important.
Turns out it was important :)
=> chore(logql/bench): store proper timestamps in generated chunks

pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_manager_test.go
It includes two fixes in tracking stream progress for deletion:
1. Do not clear stream progress when we hit a timeout so that we skip the already processed streams in the next attempt.
2. Store start/end time of the requests in the progress tracker since shared requests have same request ID.
**Checklist**
=> fix: fix timeout and series progress marker for same requests with different shards

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ingest_limits.go, pkg/distributor/ingest_limits_test.go
This pull request adds missing tests for `distributor.Push` to make sure requests are rejected as expected when limits are exceeded.
**Checklist**
=> feat: add tests for enforcing limits in distributors

pkg/loki/modules.go
The recent wiring of the v2 query engine in the querier (https://github.com/grafana/loki/pull/17032) caused a regression in the initialisation of the querier when the Thanos object client was not configured, because the v2 engine uses DataObject and DataObjects rely on Thanos object client.
This commit fixes the problem by creating the Thanos object client only when v2 engine is enabled.
=> fix(engine): Fix querier intitalisation

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/unordered.go, pkg/chunkenc/variants.go, pkg/compactor/deletion/delete_request.go, pkg/dataobj/querier/iter.go, pkg/ingester/instance_test.go, pkg/ingester/tailer.go, pkg/logcli/client/file.go, pkg/logql/log/labels.go, pkg/logql/log/labels_test.go, pkg/logql/log/metrics_extraction.go, pkg/logql/log/metrics_extraction_test.go, pkg/logql/log/parser_hints_test.go, pkg/logql/log/pipeline.go, pkg/logql/log/pipeline_test.go, pkg/logql/syntax/ast_test.go, pkg/logql/syntax/parser_test.go, pkg/logql/test_utils.go, pkg/logqlanalyzer/analyzer.go, pkg/querier/queryrange/detected_fields_test.go, pkg/storage/store_test.go
This is a next step of support Prometheus `stringlabels` implementation in Loki. It adds support in `log.StreamPipeline`.
**Checklist**
=> refactor(stringlabels): Support stringlabels in log.StreamPipeline

pkg/limits/frontend/frontend_test.go
fix bug where `expectedStreamUsageRequest` was not used in the tests for the limits-frontend.
**Checklist**
=> fix: fix bug where expectedStreamUsageRequest was not used

pkg/limits/frontend/frontend.go, pkg/limits/frontend/frontend_test.go
This pull request fixes a bug where limits were incorrect after the change in grafana/loki#16937. This bug occurred because we stopped asking each limit instance if it knew about all stream hashes, and instead starting asking each limit instance if it knew about the stream hashes for its assigned partitions. This broke the logic in the frontend that was taking the intersection of all responses to calculate if a stream was unknown. It should now take the union instead.
This pull request is stacked on top of https://github.com/grafana/loki/pull/17223.
**Checklist** …
=> fix: fix a bug where limits were incorrect after grafana/loki#16937

tools/stream-generator/Dockerfile, tools/stream-generator/README.md, tools/stream-generator/distributor/client/client.go, tools/stream-generator/docker-compose.yaml, tools/stream-generator/entrypoint.sh, tools/stream-generator/generator/config.go, tools/stream-generator/generator/distributor.go, tools/stream-generator/generator/kafka.go, tools/stream-generator/generator/metrics.go, tools/stream-generator/generator/service.go, tools/stream-generator/loki-local-config.debug.yaml, tools/stream-generator/main.go
This PR revives the useful testing tool `stream-metadata-generator` initially developed in the `feat/usage-tracker` branch to test exclusively the new ingest-limits service. In addition the generator is revamped as a stream generator allowing to generate and push entire streams with desired parameters (number or tenants, desired rate, etc.) through the distributor.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix …
=> feat(tools): Add stream generator

pkg/limits/ingest_limits.go
This PR removes the original `StickyBalancer` from list of ingest-limits balancers.
* This PR is a follow-up of: #17085 
* We will merge this once the previous PR is cut in the next k-branch.
**Checklist**
=> chore(ingest-limits): Remove sticky-balancer

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ingest_limits.go, pkg/distributor/ingest_limits_test.go, pkg/limits/frontend/frontend.go, pkg/limits/frontend/frontend_test.go
This pull request backports a number of PRs to k250:
```
2cde9b12e fix: skip streams over limits in dry-run mode (#17114)
805125c70 fix: fix a bug where limits were incorrect after grafana/loki#16937 (#17224)
d106042f0 fix: fix bug where expectedStreamUsageRequest was not used (#17223)
69aeda1bb feat: add tests for enforcing limits in distributors (#17124)
```
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a bug fix to …
=> chore: backport ingest-limits fixes to k250

pkg/querier/querier.go, pkg/querier/queryrange/detected_fields.go, pkg/querier/queryrange/downstreamer.go, pkg/querier/queryrange/parquet.go, pkg/querier/queryrange/queryrangebase/value.go, pkg/querier/queryrange/volume.go
This is a next step of support Prometheus `stringlabels` implementation in Loki. It adds support in the `querier` package.
**Checklist**
=> refactor(stringlabels): Support stringlabels in querier

docs/sources/release-notes/v3-3.md
Update the Release Notes for 3.3.4 release.
=> docs: Update RN for 3.3.4 release

docs/sources/release-notes/v2-9.md
Manual backport of https://github.com/grafana/loki/pull/17242 to 3.3 branch.
=> docs: Update Release Notes for 2.9.14 release (#17242)

pkg/ingester/client/compat.go, pkg/ingester/flush.go, pkg/ingester/index/bitprefix_test.go, pkg/ingester/index/index.go, pkg/ingester/index/index_test.go, pkg/ingester/index/multi.go, pkg/ingester/instance.go, pkg/ingester/mapper.go
This is a next step of support Prometheus `stringlabels` implementation in Loki. It adds support in the `ingester` package.
**Checklist**
=> refactor(stringlabels): Support stringlabels in ingester

pkg/loki/config_handler.go, pkg/loki/loki.go
This PR adds a new API endpoint `GET  /config/tenant/{tenant}/limits` that returns the configured limits (merged with the defaults) of a tenant.
Note, this may be useful to implement the tenants limits page in the new operator UI
https://github.com/grafana/loki/blob/dbf2befc1d888905bb7a69a96c8ba660153808eb/pkg/ui/frontend/src/config/routes.tsx#L94-L98
=> feat: Add endpoint returning tenant configured limits

pkg/engine/executor/executor.go, pkg/engine/executor/executor_test.go, pkg/engine/executor/pipeline.go, pkg/engine/planner/physical/plan.go
This PR implements a framework for basic local query execution using pull-based iterators. These iterators are defined by the `Pipeline` interface.
```go
// Pipeline represents a data processing pipeline that can read Arrow records.
// It provides methods to read data, access the current record, and close resources.
type Pipeline interface {
// Read reads the next value into its state.
// It returns an error if reading fails or when the pipeline is exhausted. In this case, the function returns EOF.
// The implementation must retain the returned error in its state and return it with subsequent Value() calls.
Read() error
// Value returns the current value in state.
Value() (arrow.Record, error)
// Close closes the resources of the pipeline.
// The implementation must close all the of the …
```
=> chore(engine): Add framework for query executor

pkg/dataobj/internal/dataset/dataset.go, pkg/dataobj/internal/dataset/reader.go, pkg/dataobj/internal/dataset/reader_test.go
Calling `Size()` on a row calculates the total size of all values in it. But we cannot call this to calculate the size of reads for primary columns since the rest of the column values are not guaranteed to be nil as we reuse the `Values` slice in a row across reads. This pr updates the stats calculation to only read the size of primary columns. Also adds a test to check the stats and updated some names for clarity.
I could spot a difference in bytes processed when running benchmarks, but it does not show up in the unit test since the buffer gets reset on each run
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future …
=> chore(dataobj): correct stats calculation for prepredicate bytes read

docs/sources/operations/loki-ui/_index.md
The Loki deployment UI is _**very**_ experimental.  Hiding the docs until more work can be done to complete this feature.
I did a little bit of content reorganization (moved "Considerations" from the end of the file to the beginning), just in case someone comes across this in the code base and wants to play with the feature.
=> docs: hide docs for experimental feature

pkg/engine/executor/executor.go, pkg/engine/executor/executor_test.go, pkg/engine/executor/limit.go, pkg/engine/executor/limit_test.go, pkg/engine/executor/util_test.go
This PR contains the implementation of the limit operator, as part of implementing the framework defined in https://github.com/grafana/loki/pull/17260
=> chore(engine): Implement execution pipeline for the limit operator

production/loki-mixin-compiled-ssd/dashboards/loki-logs.json, production/loki-mixin-compiled/dashboards/loki-logs.json, production/loki-mixin/config.libsonnet, production/loki-mixin/dashboards/dashboard-utils.libsonnet, production/loki-mixin/dashboards/loki-bloom-build.libsonnet, production/loki-mixin/dashboards/loki-canary-dashboard.libsonnet, production/loki-mixin/dashboards/loki-deletion.libsonnet, production/loki-mixin/dashboards/loki-logs.libsonnet, production/loki-mixin/dashboards/loki-operational.libsonnet, production/loki-mixin/dashboards/loki-reads-resources.libsonnet, production/loki-mixin/dashboards/loki-resources-overview.libsonnet, production/loki-mixin/dashboards/loki-retention.libsonnet, production/loki-mixin/dashboards/loki-writes-resources.libsonnet, production/loki-mixin/dashboards/recording-rules.libsonnet
Mixin not using per_namespace_label in generation of Dashboards.
Mixin is not changing when per_namespace_label is set.
**Checklist**
=> chore(Mixin): Fix per_namespace_label  not used and add per_instance_label support

pkg/limits/frontend/ring_test.go
=> chore: remove no-op code from ring tests

pkg/engine/executor/executor.go, pkg/engine/executor/executor_test.go, pkg/engine/executor/limit.go, pkg/engine/executor/limit_test.go, pkg/engine/executor/pipeline_test.go, pkg/engine/executor/pipeline_utils_test.go
This PR includes several improvements to the executor package, focusing on code organization, memory management, and testability.
Note: It came from an earlier PR where i accidentally reimplemented the Limit node that @chaudum already had a PR up for. This PR contains the deltas I'd like to keep.
- Extracted the limit pipeline implementation from `executor.go` to a dedicated `limit.go` file
- Created a reusable `NewLimitPipeline` function that can be used independently of the executor context
- Fixed an issue in `CSVToArrowWithAllocator` by removing a premature `defer reader.Release()` that was causing a use-after-free bug
- Introduced new test utility `AssertPipelinesEqual` that makes it much easier to compare Arrow pipelines by:
- Comparing records row-by-row regardless of batch sizes
- …
=> chore(dataobj,testing,executor):  pipeline equality testing

pkg/engine/executor/executor.go, pkg/engine/executor/executor_test.go, pkg/engine/executor/pipeline_test.go, pkg/engine/executor/project.go, pkg/engine/executor/project_test.go
Dependent on / followup to https://github.com/grafana/loki/pull/17311
This PR adds projection support to the Loki query engine executor, allowing queries to select specific columns from record batches. Key changes include:
- Add `NewProjectPipeline` function for creating projection pipelines
- Implement the previously unimplemented `executeProjection` method
- Add `evaluator` field to the `Context` struct for expression evaluation
- Improve CSV to Arrow conversion by trimming whitespace
- Add comprehensive test cases for projections
The implementation includes thorough tests that verify:
- Single column projection
- Multiple column projection
- Column reordering
- Processing multiple input batches
=> feat(dataobj executor): project node

pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go
This commit separates out the tests for GetPartitionConsumers from GetStreamUsage, and adds separate tests to assert the expected behavior of GetPartitionConsumers and the expected behavior of the cache.
**Checklist**
=> chore: separate out tests for GetPartitionConsumers

pkg/limits/frontend/cache.go, pkg/limits/frontend/frontend.go, pkg/limits/frontend/http_test.go, pkg/limits/frontend/mock_test.go, pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go
This pull request fixes a bug where a single error calling `GetAssignedPartitions` for one instance will prevent the frontend from getting the assigned partitions from all other instances. It also makes the code easier to read, removing the loader closure and instead opting for a more simple version of the same code.
This pull request is stacked on top of https://github.com/grafana/loki/pull/17288.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the …
=> fix: fix single error prevents getting assigned partitions

pkg/chunkenc/symbols.go, pkg/chunkenc/symbols_test.go, pkg/logql/log/pipeline.go, pkg/logql/log/pipeline_test.go
Currently we normalize all the structured metadata label names to make them prometheus safe during pipeline execution, this results in us running the normalization code again and again for the same labels.
This PR moves this normalization to when we deserialize the interned string data so it is only done one time.
**Checklist**
=> fix: improve structured metadata label normalization performance

pkg/limits/frontend/frontend_test.go, pkg/limits/frontend/mock_test.go, pkg/limits/frontend/ring_test.go
This pull request improves the unit tests in `ring_test.go` to check the expected number of requests against the actual number of requests.
**Checklist**
=> chore: improve ring_test.go

pkg/storage/chunk/client/noop/noop_object_client.go, pkg/storage/factory.go, pkg/storage/types/types.go
Not a very useful object client, but can be nice for some less common use cases/testing of Loki.
**Checklist**
=> chore: adds a simple noop object client

pkg/ingester/kafka_consumer.go, production/terraform/modules/s3/versions.tf
Adds a new histogram to the `ingester/kafka_consumer.go` consumer metrics to capture the amount of time taken to push a record once it has been consumed from Kafka.
**Checklist**
=> feat: adds partition-ingester push latency histogram

pkg/limits/ingest_limits.go
This pull request adds the kafka client option to disable auto commits for the ingest-limits consumer group. This enables in turn to replay always the last hour of all assigned partitions.
**Checklist**
=> fix(ingest-limits): Disable auto commiting records

tools/lambda-promtail/Dockerfile
Bump Dockerfile go version from 1.23 to 1.24
**Checklist**
=> chore: bump lambda-promtail Dockerfile go version

pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go
This commit adds a method to get zone-aware partition consumers.
**Checklist**
=> feat: add method to get zone-aware partition consumers

pkg/querier/queryrange/limits.go, pkg/querier/queryrange/limits_test.go
Discovered that the code we use to calculate the max parallelism can overrun the int type leading to a max parallelism chosen of 1 instead of the correct value. 
Only affects a query somewhere longer than 40 days. (40 days doesn't have this problem, 60 days does).
Interestingly I'm not sure I can exactly explain the overflow behavior here, the `int` type is supposed to be signed 32 bit, and a time.Duration is a nanosecond value, so seems like this should have overflowed way sooner?
At any rate the behavior was easy to see in a debugger and using 64bit types fixes the problem, added a test to confirm.
**Checklist**
- **Note** that Promtail is considered to be …
=> fix: fix integer overrun when calculating parallelism for very long time range queries

pkg/querier/queryrange/limits.go, pkg/querier/queryrange/limits_test.go
#17428 didn't actually fix the issue, I had modified the test parallelism to 2048 when debugging but reverted it to the previous value in the test when cleaning up my PR.
Thanks to @rfratto for being curious here and digging a bit deeper.
The overflow was actually happening in the multiplication of the nanosecond duration of the query length and the query parallelism value.
This PR hopefully really fixes the issue by reducing the precision we use in this calculation, we don't need nanosecond precision for determining an approx weighed parallelism 👍 
**Checklist** …
=> fix: better fix integer overrun when calculating parallelism for very long time range queries

pkg/engine/executor/executor.go, pkg/engine/executor/executor_test.go, pkg/engine/executor/filter.go, pkg/engine/executor/filter_test.go
This PR implements a filter pipeline for Loki's engine executor component. The filter operator enables row-level filtering of Arrow record batches based on boolean expressions. This is a fundamental component for query execution.
- Implement `NewFilterPipeline` for evaluating filter predicates on record batches
- Add `filterBatch` utility to efficiently filter Arrow records
- Update `executeFilter` in the executor to use the new implementation
- Add comprehensive test suite for the filter pipeline:
- Basic literal predicates (true/false)
- Column reference predicates
- Empty batch handling
- Multiple batch processing
The filter implementation follows the same pattern as the project pipeline, evaluating predicates against each record and creating a new filtered record based on the results. …
=> feat(dataobj, executor): filter node execution

pkg/engine/executor/executor.go, pkg/engine/executor/executor_test.go, pkg/engine/executor/expressions.go, pkg/engine/executor/expressions_test.go, pkg/engine/executor/sortmerge.go, pkg/engine/executor/sortmerge_test.go, pkg/engine/executor/util_test.go
Different implementation of the k-way merge operation without using a heap, like @rfratto described [here](https://github.com/grafana/loki/pull/17280).
>  I think you could implement SortMerge only using slices:
>  * Maintain the following invariant:
>   * For each input pipeline, we store the next record to process. (this already exists as `HeapSortMerge.batches`) 
>   * Additionally for each record, track the starting slice offset (which resets to zero whenever a new record is loaded in).
>   * Iteration stops when all input pipelines have been exhausted (no change from how this is now).
> * To get the next record:
>   * Iterate through each record, looking at the value from their starting slice offset. 
>   * Track the top _two_ winners (e.g., …
=> chore(engine): Implement execution pipeline for SortMerge operator

pkg/loghttp/push/push.go
**What this PR does / why we need it**: 
loki write logs are littered with this error now because we are not sending any structured metadata through.
This was introduced through this change: [https://github.com/grafana/loki/pull/17056/](https://github.com/grafana/loki/pull/17056/files)
Fixes #17371
**Checklist**
=> fix(push): fix guard clauses to prevent error spam in logs

pkg/distributor/distributor.go
Updates the distributor.go module so the call to waitSimulatedLatency is done in the `PushWithResolver` method, rather than `Push` (which calls this other method).
**Checklist**
=> chore: moves call to simulated latency to distributor.PushWithResolver

pkg/distributor/validator.go, pkg/loghttp/push/push.go, pkg/pattern/aggregation/push.go, pkg/pattern/ingester_test.go, pkg/pattern/instance.go, pkg/pattern/tee_service.go, pkg/querier/http.go, pkg/querier/http_test.go, pkg/querier/limits/definitions.go, pkg/querier/limits/validation.go, pkg/querier/querier.go, pkg/querier/testutil/limits.go, pkg/util/constants/aggregated_metrics.go
This PR removes `{__aggregated_metric=~".+"}` streams from the `/series` endpoint, unless an `__aggregated_metric__` matcher is explicitly requested. It does the same for `/labels`, so `__aggregated_metric__` will not appear in a `/labels` response, but you can still request `/labels/__aggregated_metric__/values`.
This will alleviate confusion for people using a tool like `logcli series --analyze-labels` for cardinatlity analysis.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being …
=> feat: hide __aggregated_metric__ in /series and /labels

pkg/engine/executor/expressions.go, pkg/engine/executor/expressions_test.go, pkg/engine/executor/filter_test.go, pkg/engine/executor/functions.go, pkg/engine/internal/types/operators.go
On startup, functions (evaluators of ColumnVectors) for binary expressions can be registered using their signature consisting of the operation, left, and right hand side data type.
The left and right hand side of the binary expressions are evaluated recursively and then the results of the left and right side are compared/resolved with the function that matches the signature.
=> chore(engine): Add framework for function evaluation

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
This pull requests disables writes to the metadata topic when the configuration options `IngestLimitsEnabled` is false.
**Checklist**
=> fix(distributor): Disable metadata topic writes

pkg/distributor/distributor.go
I suggest we use two if statements instead of chaining the enablement flag onto the end of the existing one. It's much easier when reading the code to ignore the entire block when `d.cfg.IngestLimitsEnabled` is false. 
**Checklist**
=> chore: use nested if, it's much easier to reason about

docs/sources/send-data/lambda-promtail/_index.md
Corrects spelling of lambda-promtail in the doc.
None
**Checklist**
=> docs: correct spelling of lambda-promtail

pkg/compactor/deletion/delete_requests_manager.go
I have reused an existing mutex, `deleteRequestsToProcessMtx,` to fix the concurrent access of processedSeries. I will open a follow-up PR to refactor the code. I believe we do not need a mutex to access `deleteRequestsToProcess`.
=> fix: concurrent map access for processedSeries in delete requests manager

.github/workflows/operator-bundle.yaml, .github/workflows/operator-check-prepare-release-commit.yml, .github/workflows/operator-images.yaml, .github/workflows/operator-release-please.yml, .github/workflows/operator-reusable-hub-release.yml, .github/workflows/operator-scorecard.yaml, .github/workflows/operator.yaml
Fixes #grafana/loki-private/issues/1618
**Checklist**
=> chore(ci): Disable persist-credentials for operator workflows

.github/workflows/operator-images.yaml
Fixes #grafana/loki-private/issues/1618
**Checklist**
=> chore(ci): Disable persist-credentials for operator-images workflows

.github/workflows/operator-check-prepare-release-commit.yml, .github/workflows/operator-release-please.yml, .github/workflows/operator-reusable-hub-release.yml
Updates the .github/workflows/operator-*.yml files, extracting variables used in the Github `run` blocks into environment variables.
**Checklist**
=> chore: update github workflow run blocks to use env variables

.github/release-workflows.jsonnet, .github/workflows/images.yml
Updates the release-workflows.jsonnet file so we extract variables used in `run` blocks into environment variables.  This commit also pins the dockerub-login and get-vault-secrets to an sha1 hash.
**Checklist**
=> ci: update release-workflows.jsonnet to extract env vars

pkg/dataobj/internal/dataset/column_builder.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/internal/dataset/value_encoding_bitmap.go, pkg/dataobj/internal/dataset/value_encoding_bitmap_test.go
We currently backfill old rows with nulls if they have no value for a given column. We do this by calling `Encode(value)` N times, but for sparse columns we have to iterate over very large numbers to perform the backfill. This PR adds `EncodeN(value, n)` method to bitmapEncoder to allow appending a value N times - this runs in constant time unlike the existing approach which takes O(n)
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/loki/v3/pkg/dataobj/internal/dataset
cpu: Apple M1 Pro
Benchmark_bitmap_EncodeN/Encode_1000_times-8              227778              5262 ns/op
Benchmark_bitmap_EncodeN/EncodeN_1000_times-8           83439080                14.29 ns/op
Benchmark_bitmap_EncodeN/Encode_10000_times-8              22904 …
```
=> chore(dataobj): backfill sparse rows using EncodeN

pkg/engine/engine.go, pkg/engine/metrics.go, pkg/loki/modules.go, pkg/querier/http.go, pkg/querier/http_test.go
This PR adds basic metrics for observe the duration of the different phases of the new execution engine.
Note, these metrics are subject to change.
=> chore(engine): Add basic metrics for next generation execution engine

.github/release-workflows.jsonnet, .github/workflows/images.yml
failing run: https://github.com/grafana/loki/actions/runs/14754548797/workflow
**Checklist**
=> chore(ci): Add more oidc perms for image publishing jobs

.github/release-workflows.jsonnet, .github/workflows/images.yml
Fixes lamba promtail publishing issue as seen here: https://github.com/grafana/loki/actions/runs/14755330208/job/41423661597
**Checklist**
=> chore(ci): add oidc perms for lambda-promtail publishing

.github/workflows/images.yml
Updates the images.yml workflow file with the following fixes:
* remove a rogue '$' character
* update the references to image digest steps
**Checklist**
=> chore: fix manifest and env var issue in images.yml github workflow

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/admin-api/deployment-admin-api.yaml, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/bloom-planner/statefulset-bloom-planner.yaml, production/helm/loki/templates/read/deployment-read.yaml, production/helm/loki/values.yaml
The `global.extraEnv` and `global.extraEnvFrom` values introduced in chart 6.27.0 where not included for all declared resources and in some cases weren't applied correctly.
Similar PRs:
- https://github.com/grafana/loki/pull/16526
- https://github.com/grafana/loki/pull/16708
- https://github.com/grafana/loki/pull/17472
- https://github.com/grafana/loki/pull/17020
Fixes https://github.com/grafana/loki/issues/16380
Fixes https://github.com/grafana/loki/issues/16565
Fixes https://github.com/grafana/loki/issues/16683
Fixes https://github.com/grafana/loki/issues/16713
Fixes https://github.com/grafana/loki/issues/16713
Fixes https://github.com/grafana/loki/issues/17284
**Checklist**
- …
=> fix(helm): ensure global.extraEnv and global.extraEnvFrom applied to all resources consistently

docs/sources/shared/configuration.md, pkg/distributor/tenant_topic_tee.go
Makes target throughput per partition for tenant topics configurable.
=> chore(tenant-topics): configurable throughput per partition

pkg/limits/frontend/frontend.go, pkg/limits/ingest_limits.go
Fix readiness check passing for a limits-frontend and limits service that is shutting down. It also fixes the error messages to prevent the same message being logged twice in readyHandler in pkg/loki/loki.go.
What happens is we get the following error in `/ready`:
```
Ingest Limits Frontend not ready: ingest limits frontend not ready: starting
```
when instead we want:
```
Ingest Limits Frontend not ready: service is not running: starting
```
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to …
=> fix: fix readiness check

pkg/limits/frontend/frontend.go, pkg/limits/frontend/frontend_test.go, pkg/limits/frontend/gather.go, pkg/limits/frontend/http.go, pkg/limits/frontend/http_test.go, pkg/limits/frontend/mock_test.go, pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go, pkg/loki/modules.go
This pull request makes the limits-frontend no-op while we implement https://github.com/grafana/loki-private/issues/1632.
**Checklist**
=> chore: make the limits-frontend no-op while we refactor it

pkg/dataobj/querier/iter.go, pkg/dataobj/querier/iter_test.go, pkg/engine/engine.go, pkg/engine/executor/dataobjscan.go, pkg/engine/executor/dataobjscan_predicate.go, pkg/engine/executor/dataobjscan_test.go, pkg/engine/executor/executor.go, pkg/engine/executor/executor_test.go, pkg/engine/executor/pipeline_utils_test.go, pkg/util/topk/topk.go, pkg/util/topk/topk_test.go
This commit provides an initial, basic implementation of DataObjScan. Two desired behaviours are omitted for now, as implementing them would likely require enough effort that they warrant their own PRs:
1. Values for any stream label column are encoded using primitive layouts, such that a common label value is written to a buffer each time it is seen.
This is likely to be inefficient while passing memory around, and in the long term, a dictionary encoded layout would be preferable. This is a simple change on our side, but breaks our test framework, as Arrow's `csv` package lacks support for dictionary-encoded columns.
2. DataObjScan fails if given a predicate, due to complications around mapping expressions from the engine into a dataobj.LogsPredicate.
See the very detailed comment in …
=> chore(engine): provide basic implementation of DataObjScan

pkg/engine/executor/dataobjscan.go, pkg/engine/executor/dataobjscan_test.go
`types.ColumnTypeMetadataKey` was renamed to `types.MetadataKeyColumnType` in https://github.com/grafana/loki/pull/17456 
However, https://github.com/grafana/loki/pull/17568 was merged before that, which still used the old name.
=> chore(engine): Fix regression introduced with merging PR #17456

docs/sources/setup/install/helm/configure-storage/_index.md
Manual backport of #17548  to the 3.5 branch because PR merged before the CI updates were all complete, so automated backporting failed.
=> docs: manual backport 17548

pkg/limits/frontend/frontend.go, pkg/limits/frontend/mock_test.go, pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go
This pull request re-implements `ExceedsLimits` in the `ingest-limits-frontend` to use the new `ExceedsLimits` RPC call instead of `GetStreamUsage`.
**Checklist**
=> feat: Re-implement ExceedsLimits in ingest-limits-frontend

pkg/limits/ingest_limits.go
This commit restructures some of our limits metrics. It removes tenant from _ingest_limits_partitions as this was redundant information. The same pod cannot consume different partitions for different tenants. It also counts the number of active and expired streams per tenant, and removes the recorded metric which was not being used.
**Checklist**
=> chore: restructure some of our limits metrics

pkg/limits/ingest_limits.go
This pull request should fix a lint error in `main`:
> Warning: unused-parameter: parameter 'partitionID' seems to be unused, consider removing or renaming it as _ (revive)
**Checklist**
=> fix: lint error in main branch

.github/workflows/backport.yml, .github/workflows/labeler.yml
This makes the `triage` workflow only run when the PR is not coming from a forked repository.
PTAL @periklis 
**Checklist**
=> chore(ci): Do not run triage workflow when PR comes from a fork

pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/engine/executor/dataobjscan.go, pkg/engine/executor/expressions_test.go, pkg/engine/internal/datatype/util.go, pkg/engine/internal/types/column.go, pkg/engine/planner/logical/planner.go, pkg/engine/planner/logical/planner_test.go
* `Entry.Line` maps to `builtin.message` of type `arrow.BinaryTypes.String`
* `Entry.Timestamp` maps to `builin.timestamp` of type `arrow.FixedWidthTypes.Timestamp_ns`
Names and types used when creating and collecting records need to match.
=> chore(engine): Unify name and type of builtin columns

pkg/limits/ingest_limits.go, tools/dev/kafka/loki-local-config.debug.yaml
This pull request provides a small fix in the ingest limits Kafka-WAL constructor to use the correct topic.
**Checklist**
=> fix(ingest-limits): Fix wal appender constructor

pkg/loki/loki.go
This pull requests appends the missing `Overrides` module to the `IngestLimits` module dependencies.
**Checklist**
=> fix(ingest-limits): Add missing Overrides module dependency

pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/retention/retention.go
Deletion supports saving the progress of a series to be able to skip series which are already been processed. However, it requires all the chunks for a series to be sent at once to make it easier to save the progress.
Since both retention and deletion implement the same interfaces, the table iterator asks them to decide whether a series should be skipped. So, if retention is enabled and it says no to skipping the series while deletion has already processed it, we have to iterate through the chunks in that series again. While deletion still efficiently handles it, at the end, we again try to mark the series as processed, which then triggers the check for duplicate series and fails the operation.
This PR fixes the issue by moving the code to see a …
=> fix: move the check for duplicate series up the call stack to fix an issue when retention is enabled

pkg/limits/store.go
The number of stripes should be independent of the number of partitions, as stripes work on tenants rather than partitions.
**Checklist**
=> chore: the number of stripes should be independent of the number of partitions

pkg/compactor/retention/retention.go, pkg/compactor/retention/retention_test.go, pkg/compactor/retention/series.go
Follow up PR for #17663 
We already had a map of series we found while iterating a table, which was used to clean up the series when all its chunks were deleted. I have reused the same map to avoid additional allocations. 
I have also added relevant tests to detect any breaking changes.
=> chore: improve duplicate series detection while iterating table for retention/deletion

pkg/limits/ingest_limits.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
This commit removes the redundant method Store from the `UsageStore`, folding both `Store` and `StoreCond` into a single method called `Update`.
**Checklist**
=> chore: remove redundant method from UsageStore

pkg/dataobj/explorer/inspect.go, pkg/dataobj/internal/encoding/dataset_logs.go, pkg/dataobj/internal/encoding/dataset_streams.go, pkg/dataobj/internal/encoding/decoder.go, pkg/dataobj/internal/encoding/decoder_metadata.go, pkg/dataobj/internal/encoding/decoder_range.go, pkg/dataobj/internal/encoding/encoder.go, pkg/dataobj/internal/encoding/encoder_logs.go, pkg/dataobj/internal/encoding/encoder_streams.go, pkg/dataobj/internal/encoding/encoding_test.go, pkg/dataobj/internal/encoding/metrics.go, pkg/dataobj/internal/metadata/datasetmd/datasetmd.pb.go, pkg/dataobj/internal/metadata/datasetmd/datasetmd.proto, pkg/dataobj/internal/metadata/filemd/filemd.pb.go, pkg/dataobj/internal/metadata/filemd/filemd.proto, pkg/dataobj/internal/sections/logs/iter.go, pkg/dataobj/internal/sections/streams/iter.go, pkg/dataobj/logs_reader.go, pkg/dataobj/querier/store_test.go, pkg/dataobj/streams_reader.go, pkg/dataobj/tools/inspect.go
> **NOTE TO REVIEWER**: I've split this up across several commits to make it easier to review commit-by-commit instead of looking at the overall diff. 
Each section in a data object is split across two "regions" of the file: the section's data, and the section's metadata. A section's metadata is usually used to inform reading a section in smaller units, such as storing the offset of where a data page can be read.
However, only the metadata region was represented in the file-level metadata; the "data" region existed only in the abstract. As a result of this, sections stored absolute file offsets to read units such as page locations. 
Using absolute file offsets in sections led to a few small design quirks: 
* A section cannot be encoded until all sections before it are encoded, otherwise …
=> chore(dataobj): migrate to section-relative offsets

pkg/limits/service.go, pkg/limits/service_test.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
The `WindowSize` is a limits wide configuration (see `config.go`). The configuration should be stored in `UsageStore` instead of being passed to each method. This commit updates the `Evict` method to read from the configuration instead.
**Checklist**
=> chore: remove cutoff from evict

pkg/limits/service.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
This commit removes cutoff and other arguments from `[UsageStore.Update]` as these are limits wide configurations (see `config.go`). This is needed for the `PlaybackManager` so it can call Update without having to pass all these extra parameters.
**Checklist**
=> chore: remove cutoff etc from [UsageStore.Update]

pkg/querier/http.go
```
/src/enterprise-logs/vendor/github.com/grafana/loki/v3/pkg/querier/handler.go:58 +0xb55 |  
github.com/grafana/loki/v3/pkg/querier.(*Handler).Do(0xc0028986d8, {0x555c0a8, 0xc000aa7a40}, {0x558c8e0, 0xc0008018f0}) |  
/src/enterprise-logs/vendor/github.com/grafana/loki/v3/pkg/querier/http.go:203 +0x569 |  
github.com/grafana/loki/v3/pkg/querier.(*QuerierAPI).SeriesHandler(_, {_, _}, _) |  
/src/enterprise-logs/vendor/github.com/grafana/loki/v3/pkg/querier/http.go:341 +0x2c |  
github.com/grafana/loki/v3/pkg/querier.(*QuerierAPI).filterAggregatedMetricsFromSeriesResp(0xc0028be370?, 0x0) |  
/usr/local/go/src/runtime/panic.go:792 +0x132
```
**Checklist**
- …
=> fix(querier): fixes panic when filtering agg metrics from nil resp

pkg/limits/partition_lifecycler.go, pkg/limits/partition_manager.go, pkg/limits/partition_manager_test.go, pkg/limits/service.go, pkg/limits/service_test.go
Adds a new `PartitionLifecycler` to manage assignment and revocation of partitions. This will be used in future to also check offsets.
**Checklist**
=> chore: add PartitionLifecycler to manage assignment and revocation

clients/cmd/docker-driver/Dockerfile
Brings the build image used for the docker-driver up to the same version as what is used in Loki.
**Checklist**
=> chore(build): Bump loki-build-image for docker-driver

go.mod, vendor/modules.txt
It looks to me like the `github.com/hashicorp/consul` module is not actually used by Loki but it is still present in the `go.mod` as a replace and so is still added to the vendor directory (just `modules.txt` though).
This PR removes the `replaces` from the `go.mod` file. I've also regenerated vendor using `go mod vendor`.
The module actually used seems to be `github.com/hashicorp/consul/api` which is not affected by this change.
n/a
**Checklist**
=> chore(deps): Remove unused consul dependency

docs/sources/shared/configuration.md, pkg/limits/config.go, pkg/limits/http.go, pkg/limits/http_test.go, pkg/limits/partition_lifecycler.go, pkg/limits/playback_manager_test.go, pkg/limits/service.go, pkg/limits/service_test.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
This commit renames `WindowSize` to `ActiveWindow`. It does so for the following reasons:
1. We have two windows: `WindowSize` and `RateWindow`. The first window is the time window for active streams, the second window is the time window for calculating rates. As both are windows, I think they should be named consistently to `ActiveWindow` and `RateWindow`.
2. When taking about `WindowSize`, which window are we sizing? The active stream window or the rate calculation window. It is unclear, so this change attempts to avoid such confusion.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection …
=> chore: rename WindowSize to ActiveWindow

pkg/limits/playback_manager_test.go, pkg/limits/service.go, pkg/limits/service_test.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
This commit moves the Config struct out of the UsageStore. As the config becomes more complicated over time, it becomes harder to track which fields are used in the UsageStore and which are not. As discussed with @rfratto, this fixes that problem.
**Checklist**
=> chore: move Config struct out of UsageStore

pkg/limits/partition_lifecycler.go, pkg/limits/service.go
As per https://github.com/grafana/loki/pull/17760.
**Checklist**
=> chore: move Config struct out of PlaybackManager

pkg/loghttp/push/push.go
When capturing statistics regarding the most recent push request, extract the `User-Agent` header value from the request headers.  If this value is included, strip off the trailing '/.*' content and include the agent value in the log line.
Adds User-Agent to the distributor logging so we can track agent types along with lag metrics.
**Checklist**
=> feat: adds User-Agent to distributor push logging

pkg/limits/consumer.go, pkg/limits/consumer_test.go, pkg/limits/producer.go, pkg/limits/producer_test.go, pkg/limits/service.go, pkg/limits/service_test.go
Stop using indirect names that people have to figure out, use more descriptive names of what it does.
**Checklist**
=> chore: Rename Sender and PlaybackManager to Producer and Consumer

pkg/limits/http.go
`ServeHTTP` should use `ForTenant` to iterate just the streams for the tenant, instead of all tenants.
**Checklist**
=> chore: ServeHTTP should use ForTenant instead of All

pkg/limits/limit.go
Removes the unused `RateLimitAdapter` in `limit.go`.
**Checklist**
=> chore: remove unused rate limit adapter

pkg/limits/http.go, pkg/limits/http_test.go, pkg/limits/service.go, pkg/limits/service_test.go, pkg/loki/loki.go, pkg/loki/modules.go
Renames `IngestLimits` back to `Service` so we have the following exported types/functions:
```
type Service struct{ ... }
func New(cfg Config, lims Limits, logger log.Logger, reg prometheus.Registerer) (*Service, error)
```
**Checklist**
=> chore: rename struct back to Service

pkg/limits/consumer.go, pkg/limits/consumer_test.go, pkg/limits/evict.go, pkg/limits/evict_test.go, pkg/limits/frontend/cache.go, pkg/limits/frontend/cache_test.go, pkg/limits/frontend/frontend.go, pkg/limits/frontend/gather.go, pkg/limits/frontend/mock_test.go, pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go, pkg/limits/http.go, pkg/limits/http_test.go, pkg/limits/partition_lifecycler.go, pkg/limits/partition_manager.go, pkg/limits/partition_manager_test.go, pkg/limits/producer.go, pkg/limits/producer_test.go, pkg/limits/service.go, pkg/limits/service_test.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
I have been exporting all types in `pkg/limits` as package public, which means other packages, or anyone using Loki as a Go module, can use these types. That isn't what we want. This fixes all of that, and makes the absolute bare minimum public instead.
For example, before:
```
package limits // import "github.com/grafana/loki/v3/pkg/limits"
const DefaultActiveWindow = 1 * time.Hour ...
const RingKey = "ingest-limits" ...
func MetadataTopic(topic string) string
type CondFunc func(acc float64, stream *proto.StreamMetadata) bool
type Config struct{ ... }
type Consumer struct{ ... }
func NewConsumer(client KafkaConsumer, partitionManager *PartitionManager, usage *UsageStore, ...) *Consumer
type Evictable interface{ ... }
type Evictor struct{ ... }
func …
```
=> chore: cleanup exported types in `pkg/limits`

.github/workflows/relyance.yml, relyance.yaml
Adding the Relyance scanner support to Loki.  This was already done for GEL, and is copying that workflow, along with the Relyance configuration file that we've already been using internally for scans.
**Checklist**
=> chore(ci): Add relyance scanner

pkg/limits/config.go
This commit adds back the window_size and bucket_duration fields as no-ops. This is to avoid a possible problem we might have next week with the releases where the ConfigMap is updated, and some pods on the previous release start crash looping before they can be rolled out to the new image.
**Checklist**
=> chore: add back deprecated config to avoid possible rollout issue

tools/dev/kafka/loki-local-config.debug.yaml, tools/stream-generator/loki-local-config.debug.yaml
Updates a number of committed configurations to use the renamed configuration option.
**Checklist**
=> chore: update tools configurations to change window_size to active_window

pkg/dataobj/consumer/logsobj/builder.go, pkg/dataobj/querier/iter.go, pkg/dataobj/sections/logs/builder.go, pkg/dataobj/sections/logs/builder_test.go, pkg/dataobj/sections/logs/iter.go, pkg/dataobj/sections/logs/iter_test.go, pkg/dataobj/sections/logs/row_reader.go, pkg/dataobj/sections/logs/table_build.go, pkg/dataobj/sections/streams/builder.go, pkg/dataobj/sections/streams/builder_test.go, pkg/dataobj/sections/streams/iter.go, pkg/dataobj/sections/streams/row_reader.go, pkg/dataobj/sections/streams/row_reader_test.go, pkg/engine/executor/dataobjscan.go
PR #17762 temporarily introduced an allocation regression in `logs.RowReader` by adding extra conversions from byte slices to strings and back.
This PR undoes that regression by pushing down usage of the string symbolizer. This allows us to use strings for metadata values all the way down the path before the `dataset.Reader` boundary. 
To be consistent with `logs.RowReader`, `streams.RowReader` now also does the same pattern. As a bonus, this removes the need for `streams.Stream` to track capacities used by the pointers backing strings.
=> chore(dataobj): fix regression in allocations of row readers

go.mod, go.sum, pkg/ui/service.go, vendor/github.com/grafana/ckit/internal/gossiphttp/transport.go, vendor/github.com/grafana/ckit/internal/messages/broadcast.go, vendor/github.com/grafana/ckit/internal/messages/messages.go, vendor/github.com/grafana/ckit/internal/messages/state.go, vendor/github.com/grafana/ckit/node.go, vendor/modules.txt
This pulls in grafana/ckit#84 to reduce the CPU overhead when a lot of nodes are actively joining or leaving the cluster. 
Additionally, we update the service to only set our state after the cluster has been joined. ckit [recommends](https://pkg.go.dev/github.com/grafana/ckit#Node.ChangeState) doing this so that lamport clock synchronization has already happened when the state change messaged is broadcasted. 
If a node restarts and it changes state before joining the cluster, it typically will see a state change from the previous instance of that node, and "correct" it by rebroadcasting the current state. Changing state after joining ensures that the new state change takes precedence over state changes from previous instances of that node.
=> chore(ui): update ckit dependency

.github/workflows/images.yml, Makefile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug
Update the underlying Go version for Loki and Promtail.
**Checklist**
=> fix(deps): Move to Go 1.24.2

.github/workflows/images.yml, Makefile
Moves to the latest Go version for CVE updates.
**Checklist**
=> fix(deps): Move to Go 1.23.8

tools/stream-generator/generator/config.go, tools/stream-generator/generator/service.go
This pull request adds support for a configurable batching interval for push requests. Previously it was calculated based on the request QPS per tenant.
**Checklist**
=> chore(stream-generator): Support batch interval config

pkg/compactor/deletion/delete_requests_manager.go
When we fail to load delete requests, we set DeleteRequestsManager.currentBatch to `nil`, which would lead to panics when we try to do any operation on the batch.
I have changed the code to set it to an empty batch when we fail to load the delete requests.
=> fix: set delete request batch to empty when we load to fail requests

go.mod, go.sum, vendor/github.com/ebitengine/purego/dlfcn.go, vendor/github.com/ebitengine/purego/dlfcn_darwin.go, vendor/github.com/ebitengine/purego/internal/fakecgo/go_libinit.go, vendor/github.com/ebitengine/purego/internal/fakecgo/symbols.go, vendor/modules.txt
`purego` should be update to resolve a build issue on intel macos,
```
link: duplicated definition of symbol dlopen, from github.com/ebitengine/purego and github.com/ebitengine/purego
```
There is no issue number on this repo but others
- https://github.com/ebitengine/purego/issues/313
This is not a problem of `loki` but just affected by packages
**Checklist**
=> feat: purgo package update

docs/sources/shared/configuration.md, pkg/limits/config.go, pkg/limits/service.go, pkg/limits/store_test.go
This pull request adapts the default active window for the ingest-limits service from `1h` to `2h`. With the redesign to synchronous ingest-limits writes the new default represents the same length of active streams in classic ingesters. In addition the evict internal is exposed as a custom config decoupled from the choice of the active window.
**Checklist**
=> fix(limits): Adapt defaults and expose evict interval

pkg/dataobj/consumer/metrics.go
Fix the metric name for last record processed bytes.
**Checklist**
=> chore: rename dataobj consumer metrics

pkg/logql/count_min_sketch.go, pkg/logql/downstream.go, pkg/logql/evaluator.go, pkg/logql/optimize.go, pkg/logql/optimize_test.go
Implements the approx_topk function on the querier directly, so it no longer requires the query-frontend to re-write it via the ShardMapper.
* It is implemented using __count_min_sketch__ as a sharded query is, but I added a step evaluator to process the samples instead of using the Downstreamer & Accumulator.
* This fixes a panic when an `approx_topk` query is not sharded (e.g. it's within the minShardingLookback, or when there aren't any shards within the data) and the raw query is simply forwarded to the querier.
Tested locally to double check it works as expected.
=> fix: Implement approx-topk function on querier

tools/dev/loki-tsdb-storage-s3/dev.dockerfile
I tried running local dev env and it failed with:
```
API server listening at: [::]:18004
2025-05-28T15:59:03Z warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
Version of Delve is too old for Go version go1.24.3 (maximum supported version 1.23, suppress this error with --check-go-version=false)
```
I figured out that's because we're building the image with a newer Go version than dev container is built with.
Fixes dev env
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are …
=> chore: update go & delve in dev.dockerfile to 1.24

tools/dev/loki-tsdb-storage-s3/docker-compose.yml
Just copying same thing we did in Mimir: 1.63 removed the agent from the image, so tracing in the docker compose dev env stopped working.
To workaround, we just pin it to 1.62.
Fixes dev env.
**Checklist**
=> chore: fix dev env tracing by pinning jaeger

pkg/limits/consumer.go, pkg/limits/consumer_test.go, pkg/limits/frontend/cache.go, pkg/limits/frontend/cache_test.go, pkg/limits/frontend/frontend.go, pkg/limits/frontend/gather.go, pkg/limits/frontend/mock_test.go, pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go, pkg/limits/http.go, pkg/limits/partition_lifecycler.go, pkg/limits/partition_manager.go, pkg/limits/partition_manager_test.go, pkg/limits/producer.go, pkg/limits/producer_test.go, pkg/limits/service.go, pkg/limits/service_test.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
As discussed with @rfratto.
**Checklist**
=> chore: use exported methods to differentiate internal methods

docs/sources/setup/install/helm/reference.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/provisioner/job-provisioner.yaml, production/helm/loki/templates/provisioner/role-provisioner.yaml, production/helm/loki/templates/provisioner/rolebinding-provisioner.yaml, production/helm/loki/templates/provisioner/serviceaccount-provisioner.yaml, production/helm/loki/values.yaml
As previously discussed in `#databases`, Loki, Mimir, and Tempo maintained separate, nearly identical provisioner tools. To streamline maintenance and support Grafana's Federal Cloud (where the admin API cannot be exposed externally), these were consolidated into a new, unified `enterprise-provisioner` tool in a dedicated repository. This new tool has been refactored, tested (dev, staging, prod on Federal Cloud), and already integrated into Mimir and Tempo.
This PR completes the migration initiative by transitioning the `enterprise-logs-provisioner` to utilize the new, centralized `enterprise-provisioner`.
Key Changes:
- Updates `values.yaml` to incorporate new configuration values required by the `enterprise-provisioner`.
- Modifies the template …
=> feat(helm): Integrate the enterprise-provisioner into Loki helm chart

pkg/limits/consumer_test.go, pkg/limits/partition_manager.go, pkg/limits/partition_manager_test.go, pkg/limits/service.go, pkg/limits/service_test.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
This pull request moves the metrics out of `service.go` and into the files where the data is owned.
**Checklist**
=> chore: move metrics into partition_manager.go and store.go

pkg/limits/consumer.go, pkg/limits/consumer_test.go, pkg/limits/service.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
This pull request adds a fast path for consuming records from Kafka. We had this before but I removed it thinking we could use the same method, but I think on reflection that was a mistake.
**Checklist**
=> feat: add a fast path for consuming records from Kafka

pkg/limits/consumer_test.go, pkg/limits/partition_lifecycler.go, pkg/limits/partition_manager.go, pkg/limits/partition_manager_test.go, pkg/limits/service_test.go
Remove unused context from `partition_manager.go`.
**Checklist**
=> chore: remove unused context from partition_manager.go

pkg/limits/config.go, pkg/limits/consumer_test.go, pkg/limits/service_test.go, pkg/limits/store.go, pkg/limits/store_test.go
This pull request optimizes rate buckets to avoid re-allocating the slice on each update. Instead, all rate buckets are allocated when the stream is created, and behave as a circular buffer.
This pull request is stacked on top of:
- https://github.com/grafana/loki/pull/17858
- https://github.com/grafana/loki/pull/17899
**Checklist**
=> feat: optimize rate buckets to avoid re-allocating slice

tools/stream-generator/generator/config.go, tools/stream-generator/generator/distributor.go, tools/stream-generator/generator/kafka.go, tools/stream-generator/generator/metrics.go, tools/stream-generator/generator/service.go
This pull request separates created/keep-alive routines in the stream generator. This enabled adding new streams at a different rate than keeping them alive.
**Checklist**
=> fix(stream-generator): Split create/keep-alive streams routines

pkg/limits/config.go
This pull request removes the deprecated configurations `WindowSize` and `BucketDuration`.
**Checklist**
=> chore: remove deprecated config

pkg/limits/service.go
This commit removes `MetadataTopic` as it is no longer used.
**Checklist**
=> chore: remove MetadataTopic as it is unused

pkg/limits/store_test.go
This pull request adds a missing test case for metadata whose timestamp is somewhere in the middle of a bucket to make sure it is assigned the correct rate bucket. Previously, all metadata in this test had timestamps perfectly aligned to the start of each bucket which is neither realistic nor comprehensive. 
**Checklist**
=> chore: add a missing test case where timestamp is not at bucket start

Makefile
We don't use OpenTracing anymore, we want to prevent anyone from accidentally creating traces with that library, the best way to do it is to have a faillint rule.
Ref: https://github.com/grafana/loki/issues/6812
**Checklist**
=> chore: faillint usage of opentracing in make lint

pkg/chunkenc/symbols.go, pkg/chunkenc/symbols_test.go, pkg/chunkenc/unordered.go, pkg/chunkenc/unordered_test.go
When loading a symbolizer from a flushed chunk, we unnecessarily allocate a map that holds entries only to dedupe the data while writing to a chunk. This PR fixes the issue by removing those unwanted allocations and rejecting any writes when the symbolizer is loaded from a flushed chunk. 
**Checklist**
=> fix: avoid memory allocations when loading symbolizer from a flushed chunk

pkg/limits/frontend/frontend.go, pkg/limits/frontend/ring.go, pkg/limits/frontend/ring_test.go
Adds two new counters `loki_ingest_limits_frontend_streams_total` and `loki_ingest_limits_frontend_streams_failed_total` that tracks the total number of received streams and failed streams.
**Checklist**
=> feat: add metric that tracks unanswered streams

pkg/dataobj/internal/dataset/page.go, pkg/dataobj/internal/dataset/page_reader.go
This follows up on the work started in #17841, where pages are immediately decompressed on opening a reader, rather than streaming decompression as values are read.
Allocating a new buffer for every page dramatically increased the number of allocations needed for a query by 273%.
While upfront decompression will always require more allocations, pooling buffers reduces the allocation overhead from 273% down to 13%.
goos: darwin
goarch: arm64
cpu: Apple M1 Max
│  streaming   │                upfront                │            upfront-pooled             │
│    sec/op    │    sec/op      vs base                │    sec/op      vs base                │
sum_by_(cluster,_namespace)_(rate({region="ap-southeast-1",_env="dev"}_|_detected_level=~"error …
=> chore(dataobj): Use pooled buffers when decoding pages

pkg/limits/frontend/ring.go
I like to put the noun at the start of the metric so all `stream` and `partition` related metrics can be found with prefix search (i.e. `loki_ingest_limits_stream`). This fixes that.
**Checklist**
=> chore: put noun at start of metric

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet, .github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml
bump release pipeline to get GCS creds from vault
**Checklist**
=> ci: bump release pipeline to get GCS creds from vault

docs/sources/send-data/promtail/stages/logfmt.md
Fix syntax of example log line in document
None
None
**Checklist**
=> docs: Remove unmatched quote in logfmt.md

docs/sources/send-data/promtail/stages/logfmt.md
Backport https://github.com/grafana/loki/pull/18007 to 3.4 branch.
=> docs: manual backport 17007

docs/sources/query/log_queries/_index.md, docs/sources/query/metric_queries.md
Manual backport of #18025 to the 3.5 branch
Adds shortcodes to content used in learning journeys.
=> docs: backport shortcode addition to 3.5 branch

docs/sources/shared/configuration.md, pkg/kafka/client/reader_client.go, pkg/kafka/client/reader_client_test.go, pkg/kafka/client/writer_client.go, pkg/kafka/client/writer_client_test.go, pkg/kafka/config.go, pkg/kafka/config_test.go, pkg/kafka/partitionring/consumer/client_test.go, pkg/kafka/testkafka/cluster.go
This pull request removes the deprecated `kafka.address` and `kafka.client-id` fields. These fields have been replaced by `kafka.{reader,writer}` config blocks.
Fixes #grafana/loki-private/issues/1663
**Checklist**
=> chore(kafka): Cleanup deprecated fields address and client-id

pkg/limits/limit.go, pkg/limits/store.go, pkg/limits/store_bench_test.go, pkg/limits/store_test.go
We decided that producing a record on each update was too much, and created a lot of records to replay on start up on partition rebalance. Instead, what if we produce a record for a stream if it has been 1 minute or longer since it was last produced. This commit makes the absolute minimum changes required to validate this. It accepts that rate buckets will be incorrect as not all sizes are produced, which will be solved in the next phase of the limits service.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs …
=> feat: quick fix to produce a stream once per minute

docs/sources/release-notes/v3-4.md
(cherry picked from commit 7c622ea42fa5df45a231e1f30042595ccc1b951c)
Manual backport of #18042 to 3.5 branch
=> docs: Update Release Notes 3.4.4 (#18042)

docs/sources/release-notes/v2-9.md
Manual backport of https://github.com/grafana/loki/pull/18041 to 2.9 release branch.
=> docs: Manual backport RN

docs/sources/release-notes/v2-9.md
Manual backport of https://github.com/grafana/loki/pull/18041 to 3.4 release branch.
=> docs: Manual backport patch RN

docs/sources/release-notes/v2-9.md
Manual backport of #18041 to 3.5 release branch.
=> docs: manual backport RN 3.5 branch

docs/sources/shared/configuration.md, pkg/limits/frontend/config.go
This pull request removes a flag that is no longer used.
**Checklist**
=> chore: remove unused recheck period

pkg/compactor/deletion/job_builder.go, pkg/compactor/deletion/job_builder_test.go, pkg/compactor/deletion/job_runner.go, pkg/compactor/deletion/job_runner_test.go
As a follow-up to work on making Compactor horizontally scalable for processing delete requests, this PR adds a job runner that executes the deletion jobs. The Deletion Job runner would download the chunks from the object storage, apply the filters from the given delete requests, upload any newly built chunks with deleted lines filtered out and build a job response which includes:
1. List of chunk IDs to delete from storage and the index.
2. List of chunk IDs to de-index from the index.
3. List of new chunks to be added to the index.
**Checklist**
=> feat(compactor HS): add a job runner for processing of deletion jobs

pkg/storage/stores/composite_store_entry.go
If `err` is nil then calling the method `Error()` on it causes a nil pointer dereference.
=> fix: Fix nil pointer dereference in Volume method of the composite store

docs/sources/get-started/hash-rings.md
updates the name of the ring configuration block
Fixes #18034
=> docs: update config option name

pkg/logql/accumulator.go, pkg/querier/queryrange/downstreamer.go, pkg/querier/queryrange/downstreamer_test.go, pkg/querier/queryrange/roundtrip_test.go
In the frontend we process queries via the Downstreamer which handles sharding of a query, this creates the situation where a query could be heavily sharded and each shard result is appened to a result set before being returned to the engine via the StepEvaluator, after this point the engine would check to see if there were too many series in the result and if there are, fail the query.
The problem though is all the memory was already allocated to handle the responses from all the subqueries, this PR introduces a check to incrementally count the series from each downstreamed shard and will fail the query as soon as we exceed the max_query_series limit …
=> chore: enforce max-query-series when returning shard results

docs/sources/query/_index.md
**What this PR does / why we need it**: I just published a video on LogQL basics. In this PR, I embed it into the main Query page of the docs.
=> docs: Embed LogQL video in docs

pkg/engine/executor/dataobjscan_predicate.go, pkg/engine/executor/dataobjscan_predicate_test.go, pkg/engine/internal/types/operators.go
This PR converts line filter expressions into message predicates for the data object scan, instead of returning an error.
The logic is basically the same as for the metadata predicates, except for the supported operator types.
=> chore(engine): Map line filter expressions to data object predicates

pkg/compactor/deletion/job_runner_test.go, pkg/engine/executor/dataobjscan.go, pkg/engine/executor/dataobjscan_test.go, pkg/engine/executor/expressions.go, pkg/engine/executor/expressions_test.go, pkg/engine/executor/filter.go, pkg/engine/executor/sortmerge_test.go, pkg/engine/planner/logical/planner.go, pkg/engine/planner/logical/planner_test.go
The new engine fails to execute a query when an `arrow.Record` (batch) does not contain the column on which a label filter is used, e.g. `| foo="bar"` where `foo` is neither a label nor a structured metadata.
This change also fixed an incorrect conversion of the label filter operator `=`, which was converted to `MATCH_STR`, but requires to be `EQ`.
=> chore(engine): Filter by unknown column

cmd/loki/loki-local-config.yaml
This PR fixes the default local config loki uses. This PR https://github.com/grafana/loki/pull/16718 moved `enable_multi_variant_queries` from a global querier config to the limits_config section but the default local config is still using the old structure. 
This is my first PR 🎉 
**Checklist**
=> chore: move enable_multi_variant_queries to the correct config section

docs/sources/setup/install/helm/_index.md
GCP is missing from the instructions, which already include AWS and Azure.
=> docs: Add GKE Instructions Link to Installation Readme

pkg/limits/partition_manager.go, pkg/limits/partition_manager_test.go, pkg/limits/service.go
This pull request makes the ingest-limits readiness handler to consider partition state before signaling ready. I.e. the service is considered to be ready and consume traffic when the following conditions apply:
- The partition manager assigned partitions (max retries 10)
- The partition lifecycler moved all partitions from pending/replaying to ready state.
Fixes #grafana/loki-private/issues/1722
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the feature actually being a …
=> fix(limits): Set ready when all partitions ready

docs/sources/get-started/_index.md
Adding an alias to the Get Started topic to generate a redirect for Grafana topics that point to Getting Started.  Should fix at least five broken links in the Grafana docs, according to the broken links dashboard.
=> docs: add redirect to fix broken links

pkg/logqlmodel/error.go, pkg/querier/queryrange/limits.go
This PR improves error message for `maximum of series (%d) reached` error. It provides guidance on how to fix it. This is a common error that users encounter with. 
Fixes https://github.com/grafana/grafana/issues/80210
=> chore: Improve error message for `maximum of series (%d) reached`

pkg/pattern/ingester.go, pkg/pattern/ingester_test.go, pkg/pattern/instance.go
PR https://github.com/grafana/loki/pull/17737 introduced a feature to persist detected patterns on the pattern ingesters. And while there is a dedicated global config `PatternPersistence` and a per-tenant config `PatternPersistenceEnabled`, none of these were honoured, because for writing the patterns to the distributor, the same writer (and its config) as for persisting aggregated metrics is used. So, when aggregated metrics is enabled, also patterns were automatically written/persisted as well.
=> fix(pattern): Fix feature flag for enabling pattern persistence

docs/sources/configure/storage.md
Manual backport of #18203 to 3.5 branch.
=> docs: backport storage fix 3.5

pkg/compactor/deletion/deletion_manifest_builder.go, pkg/compactor/deletion/deletion_manifest_builder_test.go, pkg/compactor/deletion/job_builder.go, pkg/compactor/deletion/job_builder_test.go, pkg/compactor/jobqueue/queue.go, pkg/compactor/jobqueue/queue_test.go
With this PR, we are adding support to persist index updates we need to make to the index files once we are done processing all the segments in the deletion manifest. Index updates are stored per segment since the manifest processing is resumable on the segment level.
**Checklist**
=> feat(compactor HS): store index updates per processed segment in the manifest to the object storage

pkg/storage/stores/shipper/bloomshipper/fetcher.go
The download queue has a fixed size of 100k elements and is implemented using a channel. Since the channel has a fixed size, this will allocate `capacity * object size`, where the object is `downloadRequest[BlockRef, BlockDirectory]`.
This PR changes the channel from a channel of objects (`chan downloadRequest[T, R]`) to a channel of pointers (`chan *downloadRequest[T, R]`) which should significantly reduce the permanently allocated memory for the queue.
The screenshots shows a 3h memory profile (inuse space) of a set of index gateways, where the `bloomshipper.newDownloadQueue` occupies almost a quarter of the inuse memory.
=> chore(blooms): Reduce memory footprint of download queue

docs/sources/shared/configuration.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/limits.go, pkg/distributor/validator.go, pkg/validation/limits.go
While truncated JSON log lines are usually easy to identify (because the JSON becomes invalid), it is not always the case with other plain text log lines.
This PR adds the possibility to add an identifier as suffix for truncated log lines, such as `[...]` so that truncated log lines are easier to spot and identify when querying them.
---
A truncation identifier has almost been implemented with the initial truncation PR (https://github.com/grafana/loki/pull/4051). This implementation is essentially the same.
=> feat: Mark truncated log lines with identifier

pkg/querier/tail/querier_test.go, pkg/querier/tail/tail_mock_test.go
Mock `TailDisconnectedIngesters` calls to return empty clients map. This func gets called periodically from the tailer's loop, not implementing it could result in a panic
```
TestQuerier_concurrentTailLimits/ring_containing_one_active_ingester_and_0_active_tailers (0.00s)
panic:
assert: mock: I don't know what to return because the method call was unexpected.
Either do Mock.On("TailDisconnectedIngesters").Return(...) first, or remove the TailDisconnectedIngesters() call.
This method was unexpected:
TailDisconnectedIngesters(*context.valueCtx,*logproto.TailRequest,[]string)
0: &context.valueCtx{Context:context.backgroundCtx{emptyCtx:context.emptyCtx{}}, key:0, val:"test"}
1: &logproto.TailRequest{Query: "{type=\"test\"}",
DelayFor: 0x0,
Limit: 0xa, …
```
=> chore(tailer): fix a flaky tests in tail/querier_test.go

pkg/loghttp/push/otlp.go, pkg/loghttp/push/otlp_test.go
Fixes the issue where "negative structured metadata bytes received" errors were being logged in Loki when processing OTLP logs.
The OTLP processing code was calculating entry-specific metadata size by subtracting resource and scope attribute sizes from the total metadata size after they were already combined. This calculation could result in negative values, which were caught by guard clauses and logged as errors.
This PR changes the approach to calculate the entry's metadata size *before* adding resource and scope attributes. This preserves the original intent (tracking entry-specific metadata separately) while ensuring the values are always positive.
The change maintains the same accounting logic but eliminates the possibility of negative values …
=> fix(otlp): calculate entry metadata size before adding resource/scope attributes

pkg/dataobj/internal/dataset/reader.go
This fixes an issue where a predicate column was being read more than once. We have a check to avoid this, but the look-up was being done using wrong column instance
```
goos: darwin
goarch: arm64
cpu: Apple M1 Pro
│ stats.txt  │           stats_new.txt            │
│   sec/op   │   sec/op    vs base                │
LogQL/query=sum_by_(detected_level)_(count_over_time({region="ap-southeast-1"}[24h0m0s]))/kind=metric/store=dataobj-engine-8   7.340 ± 4%   4.737 ± 5%  -35.46% (p=0.000 n=20)
│     stats.txt      │               stats_new.txt               │
│ kilobytesProcessed │ kilobytesProcessed  vs base               │
LogQL/query=sum_by_(detected_level)_(count_over_time({region="ap-southeast-1"}[24h0m …
```
=> chore(dataobj): avoid reading a predicate column more than once

pkg/util/arrowtest/arrowtest.go, pkg/util/arrowtest/arrowtest_test.go
This adds two utilities:
* `arrowtest.Rows.Schema`, which infers the Arrow Schema from a set of rows.
* `arrowtest.Rows.Record`, which converts the set of Go rows into an Arrow Record.
These two utilities mean that arrowtest can be used in both directions of testing code that uses Arrow: creating a record to use in testing, and asserting the content of a record.
=> chore(arrowtest): add utilities to construct arrow.Record from test rows

pkg/engine/executor/arrow_scalar_compare.go, pkg/engine/executor/topk_batch.go, pkg/engine/executor/topk_batch_test.go, pkg/engine/internal/arrowagg/arrays.go, pkg/engine/internal/arrowagg/arrowagg.go, pkg/engine/internal/arrowagg/hash.go, pkg/engine/internal/arrowagg/mapper.go, pkg/engine/internal/arrowagg/records.go, pkg/util/topk/topk.go, pkg/util/topk/topk_test.go
This commit adds a `engine.topkBatch` type, which can be used by the implementation of execution nodes to perform compute the set of topk rows from a stream of records. This is needed as part of #17976, and more generally for efficiently sorting rows when a limit is also used. 
Implementing this required quite a few helper utilities in the new `arrowagg` package. The `arrowagg` package provides utilities for aggregating various Arrow types:
* `arrowagg.Arrays` to concatenate a stream of `arrow.Array`s 
* `arrayagg.Records` to concatenate a stream of `arrow.Record`s, creating a merged schema.
* `arrowagg.Mapper` for quickly finding fields in incoming schemas, since arrow-go can return false when comparing two identical schemas/fields.
The end result should be capable of performing topk …
=> chore(engine): add implementation for performing topk across streams of Arrow records

.github/workflows/operator-release-please.yml
It looks like the format for the `timeout-minutes` is given in the wrong format, because runs keep erroring on that line. I have not dug much deeper just compared with the other configuration files and adjusted the configuration accordingly.
**Checklist**
=> fix(ci): Fix workflow timeout added in wrong format

docs/sources/setup/install/helm/reference.md, production/helm/loki/README.md, production/helm/loki/values.yaml
Adds [`block_builder`](https://grafana.com/docs/loki/latest/configure/#supported-contents-and-default-values-of-lokiyaml) option to the default config in the loki helm chart
What is the relation with the same configuration options in the `ingester` config?
Should they be related?
> i.e. If I set `chunk_encoding` should they be equal? Will it break something if they differ?
How do I increment the helm version?
Is that something I need to worry about.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless a case can be made for the …
=> feat(helm): Add `block_builder` config to helm chart

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/chunks-cache/poddisruptionbudget-chunks-cache.yaml, production/helm/loki/templates/memcached/_memcached-statefulset.tpl, production/helm/loki/templates/memcached/_memcached-svc.tpl, production/helm/loki/templates/results-cache/poddisruptionbudget-results-cache.yaml, production/helm/loki/values.yaml
allow external memcached setup, with overriding addresses.
Fixes #12559
the old config loki.memcached does't work anymore.
New way of setting up external memcache is with:
```
memcached:
enabled: false # <- setting false here
resultsCache:
addresses: 'my-resultsCache-memcached-address' # <- setting custom address here
chunksCache:
addresses: 'my-chunksCache-memcached-address' # <- setting custom address here
```
**Checklist**
=> feat(helm): allow external memcached setup

pkg/dataobj/internal/dataset/column_stats.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/internal/dataset/reader.go, pkg/dataobj/internal/dataset/value.go, pkg/dataobj/internal/dataset/value_encoding_plain.go, pkg/dataobj/internal/dataset/value_test.go, pkg/dataobj/sections/logs/row_predicate_order.go
This PR makes several small changes to improve the performance of the dataset.Value API:
1. Reduce the complexity of methods so that methods can be inlined. The previous complexity of Value.Type bubbled down to all the methods, making them hard to inline.
Using error types for panics also reduces the complexity cost of the panic lines while retaining the same error messages; the cost of both string concatenation and fmt.Sprintf bubbled up the cost, further making it difficult to inline functions.
2. Use pointer receivers wherever possible for Value methods. As each Value is 28 bytes (previously 24, but still large), copying the Value on the stack to call a non-inlined method was expensive. This was seen most prominently in CompareValues, which still can't be inlined. Using pointers for …
=> chore(dataobj): Improve performance of dataset.Value API

docs/sources/setup/install/helm/reference.md, production/helm/loki/ci/non-default-values.yaml, production/helm/loki/templates/loki-canary/daemonset.yaml, production/helm/loki/values.yaml
Currently lokiCananry uses the DaemonSet that end up creating 7000 pods in our cluster, since there is no possible way to limit number of containers deployed with Daemonset, I added an optional config to be able to switch to Deployment type
**Checklist**
=> feat(helm): add option to use deployment type instead of daemonset in canary

.github/workflows/add-to-docs-project.yml, .github/workflows/publish-technical-documentation-release.yml
adding comment to allow zizmor checks to pass the docs workflows on the 3.4 branch (these are copied from `main` and `3.5.x` which are passing these checks)
=> ci: update docs workflows for zizmor

docs/sources/query/metric_queries.md
Manual backport of https://github.com/grafana/loki/pull/18396 to the 3.4 branch.
=> docs: backport 18396 to 3.4 branch

docs/sources/query/metric_queries.md
Manual backport of #18396 to the 3.5 branch.
=> docs: backport 18396 to 3.5 branch

docs/sources/operations/multi-tenancy.md
Manually backports https://github.com/grafana/loki/pull/18387 to the 3.4 branch.
=> docs: backport 18387 to 3.4 branch

.github/workflows/images.yml, Makefile
Moves to the latest version of Go.
**Checklist**
=> fix(deps): Move to Go 1.24.5

pkg/dataobj/querier/store_test.go, pkg/dataobj/sections/logs/builder_test.go, pkg/dataobj/sections/logs/reader_test.go, pkg/dataobj/sections/logs/table_build.go, pkg/dataobj/sections/logs/table_merge.go, pkg/dataobj/sections/logs/table_test.go, pkg/engine/engine.go, pkg/engine/executor/dataobjscan.go, pkg/engine/executor/dataobjscan_test.go, pkg/engine/executor/executor.go, pkg/engine/executor/sortmerge.go, pkg/engine/planner/logical/planner.go, pkg/engine/planner/logical/planner_test.go, pkg/engine/planner/physical/planner.go, pkg/engine/planner/physical/planner_test.go, pkg/logql/bench/bench_test.go, pkg/logql/bench/store_dataobj_v2_engine.go, pkg/querier/http_test.go, pkg/querier/querier_test.go
Sorting sections by `timestamp DESC` first and `streamID ASC` second allows for more efficient reading (by section) for BACKWARD log queries.
- Supersedes work in progress PR https://github.com/grafana/loki/pull/18337
- This change breaks FORWARD log queries. Which is ok for the time being. We will add support later again when columnar reading of the dataobj is introduced.
- This change renders existing dataobj in storage incompatible.
<details>
```console
$ benchstat logql_bench_main.txt logql_bench_sortbytimestamp.txt
goos: linux
goarch: amd64
│ logql_bench_main.txt │   logql_bench_sortbytimestamp.txt    │
│        sec/op        │    sec/op     vs base                │ …
```
=> chore(engine): Sort  entries in dataobj sections by timestamp descending

pkg/compactor/deletion/job_runner_test.go, pkg/engine/executor/pipeline.go, pkg/engine/executor/pipeline_test.go, pkg/engine/executor/sortmerge.go
This PR changes how inputs of the `SortMerge` operator are consumed. The inputs are wrapped into the `prefetchWrapper` which consumses the next batch (arrow.Record) in the background while the current batch is processed by the parent node.
```
$ gotest -v ./pkg/logql/bench/... -count=10 -test.bench='^BenchmarkLogQL/query=.+\[BACKWARD\]/kind=log/store=dataobj-engine' -test.run=^$ -timeout=30m -benchmem
```
```console
$ benchstat bench_sortbytimestamp_without_prefetch.txt bench_sortbytimestamp_with_prefetch.txt
goos: linux
goarch: amd64
│ bench_sortbytimestamp_without_prefetch.txt │ bench_sortbytimestamp_with_prefetch.txt │
│                   sec/op                   │     sec/op       vs …
```
=> chore(engine): Prefetch inputs of SortMerge operator

docs/sources/shared/configuration.md, pkg/compactor/client/grpc.go, pkg/compactor/compactor.go, pkg/compactor/config.go, pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/deletion_manifest_builder.go, pkg/compactor/deletion/deletion_manifest_builder_test.go, pkg/compactor/deletion/job_builder.go, pkg/compactor/deletion/job_builder_test.go, pkg/compactor/deletion/job_runner.go, pkg/compactor/deletion/job_runner_test.go, pkg/compactor/deletion/metrics.go, pkg/compactor/jobqueue/metrics.go, pkg/compactor/jobqueue/queue.go, pkg/compactor/jobqueue/queue_test.go, pkg/compactor/jobqueue/worker.go, pkg/compactor/jobqueue/worker_test.go, pkg/compactor/worker.go, pkg/loki/loki.go, pkg/loki/modules.go
It includes the following changes:
1. Add relevant configs
2. Wire things up end-to-end
3. Avoid building a new manifest when one already exists. The reason is that we mark delete requests as processed after processing a manifest, so trying to build a new manifest would require us to check if the requests are already included in one of the existing manifests. It is not worth the complexity since we process a single manifest at a time.
4. Clean up any invalid manifests during startup. 
5. Add some logs and metrics for visibility.
**Checklist**
=> feat(compactor HS): Wire things up and add some metrics

pkg/logql/syntax/parser.go, pkg/logql/syntax/parser_test.go
There was a panic due to an invalid query, which looked something like this:
`sum(label_replace(count_over_time({container="query-frontend"} |= "metrics.go" | logfmt[1m]) or 0, "tenant", "$1", "org_id", "(.*)")) by (tenant)`
Notice the `or 0` in the binary operation, which is [invalid and results in setting an error in the initialised BinOpExpr](https://github.com/grafana/loki/blob/3d2286a84067cfe616c82876e8ed514629440df7/pkg/logql/syntax/ast.go#L1877).
Now, we validate the parsed logQL query to detect any such errors and return them to the user.
[Some expressions have specific validation logic](https://github.com/grafana/loki/blob/e90db7c627352472fd387a73aa7baa33ab5fa5e6/pkg/logql/syntax/parser.go#L195), while for the remaining, we default to …
=> fix: while validating logql expression, detect and validate expression in label_replace

docs/sources/alert/_index.md
Adding where to download `lokitool` after someone asked in the Community [Slack](https://grafana.slack.com/archives/CEPJRLQNL/p1752502295570979) where they could download.
PR also includes:
* some updated headings
* some updated links
=> docs: add lokitool download link

docs/sources/visualize/grafana.md
When I was reading the Visualize topic today, I spotted that the navigation had not been changed from Explore to Drilldown when the app name changed.
Also added a tip based on a Slack conversation.
=> docs: Fix navigation for drilldown

pkg/dataobj/index/builder.go, pkg/dataobj/index/calculate.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/metastore/object.go, pkg/dataobj/sections/pointers/builder.go, pkg/dataobj/sections/pointers/iter.go, pkg/dataobj/sections/pointers/row_reader.go, pkg/engine/engine.go, pkg/logql/bench/bench_test.go, pkg/logql/bench/store_dataobj.go, pkg/logql/bench/store_dataobj_v2_engine.go
Builds & utilitises indexes in the LogQL benchmark suite.
* Fixes a correctness bug which stopped them passing (reset the Pointer object on reads, espcially for `0` int64s.)
* I decided to add the indexed store as a separate store so we can compare with the engine without indexes (and potentially rule out any issues earlier). I happy to just have one store if we want.
* Note: all of calculate.go is extracted from builder.go, and hasn't changed otherwise.
Interesting observation: The benchmark suite doesn't have enough data to make the indexes worthwhile. We correctly resolve less sections but the additional lines & data read from the index tends to make it do more work than without. I don't think this is a problem as it'll make a bigger difference …
=> chore: Add indexes to LogQL benchmarks

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/chunks-cache/poddisruptionbudget-chunks-cache.yaml, production/helm/loki/templates/results-cache/poddisruptionbudget-results-cache.yaml, production/helm/loki/values.yaml
Fix PDB settings for chunksCache and resultsCache
The maxUnavailable variable was not used before. This adds the mechanism that the PDB is only deployed when the replicas are >1 and it also fixes the maxUnavailable variable
**Checklist**
=> fix(helm): Fix PDB settings for chunksCache and resultsCache

pkg/dataobj/index/calculate.go
There was a merge conflict because this PR was merged directly after the one which removed support for slicelabels.
This PR fixes the issue by using the Range API.
=> chore: Fix slicelabels merge conflict

pkg/engine/executor/functions.go, pkg/engine/executor/functions_test.go
Filters predicates on ambiguous columns (basically any label filter expression) cannot be pushed down to the DataObjScan and need to be evaluated in the Filter node.
This PR adds the evaluation functions for `MATCH_RE(string,string)` and `MATCH_SUBSTR(string, string)` and their negating equivalent.
Under the hood, the PR also replaces the type specific comparison function implementations with a generic one, which now also handle arrow.Timestamp arrays correctly.
These two changes can be reviewed in the individual commits.
=> chore(engine): Add support for regex and substr filters

pkg/compactor/compactor.go, pkg/compactor/deletion/delete_request.go, pkg/compactor/deletion/delete_request_batch.go, pkg/compactor/deletion/delete_request_test.go, pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_manager_test.go, pkg/compactor/deletion/deletion_manifest_builder.go, pkg/compactor/deletion/deletion_manifest_builder_test.go, pkg/compactor/deletion/job_builder.go, pkg/compactor/deletion/job_builder_test.go, pkg/compactor/deletion/job_runner.go, pkg/compactor/deletion/job_runner_test.go, pkg/compactor/deletion/metrics.go, pkg/compactor/jobqueue/metrics.go, pkg/compactor/jobqueue/queue.go, pkg/compactor/jobqueue/queue_test.go
It includes a bunch of changes I made while testing it end-to-end:
1. Adds some new metrics.
2. Fixes a deadlock in re-queueing of failed/timed-out jobs in job queue.
3. Adds a workaround for object exists check due to a bug in Thanos' GCS object client implementation.
4. Skip series not selected by delete requests while looking for chunks to process.
5. A bunch of other minor improvements/fixes.
**Checklist**
=> feat(compactor HS): Fixes and changes for getting horizontally scalable compactor to work well

pkg/dataobj/sections/indexpointers/row_predicate_test.go, pkg/dataobj/sections/indexpointers/row_reader.go
Updates the timestamp predicate so the target is overlapping instead of completely inside the range.
We want to return any values that are overlapping with the min/max timestamps of the indexpointers:
e.g. 
An indexpointer with range 01:00 to 02:00 should overlap with query range of 0000-0130 and 0145-0200
=> chore: Use correct TimeRange predicate for indexpointers

pkg/engine/metrics.go
This PR extends the default buckets (that only range to 10s) to 60s.
It also inlines the fully qualified name of the metric, rather than using Namespace/Subsystem/Name. This is for easier searchability of the metric name
=> chore(engine): Extend histogram buckets for metrics for the new query engine

pkg/logql/bench/bench_test.go, pkg/logql/bench/cmd/bench/main.go, pkg/logql/bench/generator_query.go, pkg/logql/bench/generator_test.go
Adds instant metric queries to bench test which can be invoked by setting `--range-type=instant`
**Checklist**
=> chore(bench): add instant metric queries

clients/pkg/logentry/stages/labels.go, clients/pkg/logentry/stages/structuredmetadata.go, clients/pkg/logentry/stages/structuredmetadata_test.go
When Structured Metadata extraction was introduced to promtail, it only picked KV pairs from the extracted map.
With PR grafana/loki#10752, promtail also started picking structured metadata from stream labels to help control the cardinality since it would also remove those labels from streams. However, [before running the pipeline stages, we add all the stream labels to the extracted map](https://github.com/grafana/loki/blob/39a7181a600e9dc848dd3c0b0163c07242a46278/clients/pkg/logentry/stages/pipeline.go#L123-L127), due to this, we are adding duplicate Structured Metadata entries.
In this PR, I fix the issue by deduping the entries before adding them to Structured Metadata.
I have ensured that it is not a breaking change by keeping the order of …
=> fix: ensure we do not add duplicate structured metadata from stream labels and extracted map

docs/sources/shared/configuration.md, pkg/dataobj/internal/arrowconv/arrowconv.go, pkg/dataobj/internal/dataset/predicate.go, pkg/dataobj/internal/dataset/reader.go, pkg/dataobj/sections/logs/predicate.go, pkg/dataobj/sections/logs/reader.go, pkg/dataobj/sections/logs/reader_test.go, pkg/dataobj/sections/streams/predicate.go, pkg/dataobj/sections/streams/reader.go, pkg/dataobj/sections/streams/reader_test.go, pkg/engine/engine.go, pkg/engine/executor/dataobjscan.go, pkg/engine/executor/dataobjscan_predicate.go, pkg/engine/executor/dataobjscan_predicate_test.go, pkg/engine/executor/dataobjscan_test.go, pkg/engine/executor/executor.go, pkg/engine/executor/schema.go, pkg/engine/executor/schema_test.go, pkg/engine/executor/stream_injector.go, pkg/engine/executor/stream_injector_test.go, pkg/engine/executor/streams_view.go, pkg/engine/executor/streams_view_test.go, pkg/engine/executor/topk.go, pkg/engine/executor/topk_test.go, pkg/engine/executor/util_test.go, pkg/logql/engine.go, pkg/util/arrowtest/arrowtest.go, pkg/util/arrowtest/arrowtest_test.go
This PR follows up on the work started in #17976, where DataObjScan will now use the columnar reading APIs instead of the row-based APIs. 
As a result, a few things have changed:
* Projected columns are now respected by the reader; DataObjScan will only read columns from the projected list (or all columns if the projected list is empty).
* For implementation simplicity, the sort order of columns is now consistent, regardless of projection order. 
There was quite a bit of setup work I had to do to be able to make this change; I've split the full implementation across 12 commits for easier reviews.
Additionally, DataObjScan will now force a topk sort if the scanned section is not sorted by timestamp, or not sorted by the requested sort order. When this is done, DataObjScan no longer streams …
=> chore(engine): use columnar logs.Reader for DataObjScan

pkg/engine/planner/physical/optimizer.go, pkg/engine/planner/physical/optimizer_test.go, pkg/engine/planner/physical/planner.go
Column expressions from predicates are not being pushed down during query plan optimisation resulting in incorrect results for metric queries with filter expressions.
This PR updates the `projectionPushdown` optimiser to pushdown predicate columns from `Filter` node for metric queries
**Checklist**
=> chore(engine): add predicate columns to projection list for metric queries

pkg/kafka/client/writer_client.go
Removes the `loki_kafka_client_buffered_produce_bytes` metric from Loki's Kafka producer code.
* The metric tracks the current number of bytes buffered in the client. It stays [fairly constant over time](https://admin-dev-us-central-0.grafana-dev.net/grafana/a/grafana-metricsdrilldown-app/drilldown?nativeHistogramMetric=&layout=grid&filters-rule=&filters-prefix=&filters-suffix=&from=now-1h&to=now&timezone=UTC&var-filters=&var-labelsWingman=%28none%29&search_txt=loki_kafka_&var-metrics-reducer-sort-by=default&var-ds=cortex-dev-01&var-other_metric_filters=&metric=loki_kafka_client_buffered_produce_bytes&actionView=breakdown&var-groupby=$__all)
* A metric of the same name is being produced by the Kafka client directly after the latest update.
* The new …
=> fix: Remove duplicated metric from Kafka producer

pkg/compactor/deletion/delete_requests_manager.go, pkg/compactor/deletion/delete_requests_manager_test.go, pkg/compactor/retention/retention.go
When running the compactor in singleton mode, we track processed series to skip processing them again when the delete request processing resumes after hitting a timeout. We used to store the progress in a map and store it as a JSON file on disk to persist the progress between restarts. Today, this led to an incident because it used too much memory to track the progress and then used additional memory to JSON encode the data.
In this PR, I am adding support to store series progress in a BoltDB file. Because they are memory-mapped, we should use significantly less memory, and all the updates would normally get automatically synced to the disk.
To reduce the number of series we track, I have made it track only series with chunks to process with a line …
=> chore: use boltdb for tracking series processing progress in delete requests manager

docs/sources/setup/upgrade/_index.md, docs/sources/setup/upgrade/upgrade-to-6x/index.md, production/helm/loki/CHANGELOG.md, production/helm/loki/scenarios/default-distributed-values.yaml
Added upgrade notice for: https://github.com/grafana/loki/pull/18558
**Checklist**
=> fix(docs): added instructions for how to upgrade zone-aware ingesters

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/validate.yaml
If minio is enabled, the names of the bucket names are hard-coded and `loki.storage.bucketNames` is ignored.
https://github.com/grafana/loki/blob/e0b33535d1d58c855f13ef5d35cb152acb3e16fc/production/helm/loki/templates/_helpers.tpl#L213-L216
CI is currently failing: https://github.com/grafana/loki/actions/runs/16606809856/job/46981528703?pr=18510
**Checklist**
=> fix(helm): make loki.storage.bucketNames are optional, if builtin minio is enabled.

pkg/engine/engine.go, pkg/engine/executor/executor.go, pkg/engine/executor/pipeline.go
This commit adds tracing instrumentation so that we have spans for:
* The entire query execution
* Logical planning
* Physical planning
* Pipeline construction (QueryEngine.Execute.Process)
* Pipeline consumption (one span per Read call)
Each "execution" function (the functions that construct a pipeline) have their own spans, with enough attributes to help roughly identify what they do. Ideally DataObjScan and Filter would also include a stringified version of their predicates and projections, but there's no way to easily do that right now.
This commit also fixes a bug where we were reporting the same logical planning time for both the logical planning and physical planning times on the debug log line.
=> chore(engine): add tracing instrumentation

pkg/dataobj/internal/dataset/reader_downloader.go
Previously, readerDownloader would retrieve page information for projected columns sequentially. This can result in a very high number of roundtrips to object storage: for a streams section with 160 columns, 160 roundtrips at 10ms each would add 1.6s of latency to a scan.
This updates readerDownloader to lazily download all page headers at once for all projected columns, once the first page header is requested.
=> chore(dataobj): list pages across all columns in one request

.github/workflows/helm-ci.yml, production/helm/loki/test/integration/ingress/test-plan.yaml, production/helm/loki/test/integration/single-binary/log-generator.yaml, production/helm/loki/test/integration/single-binary/test-plan.yaml
Use the [Helm Chart Toolbox](https://github.com/grafana/helm-chart-toolbox) to run Helm chart integration tests in parallel. Starting with two tests that I found in the `ci` directory.
Where I'd take this next:
1. Copy the `abc_values.yaml` files from the `ci` directory into the individual test directories. This will keep them in the text directory and "associated" with that test.
2. Create new tests at least to cover the existing tests run in `ci`
3. Stop using chart-testing (aka `ct`), which is what runs tests sequentially and takes a long time.
At this point, you should see the `helm-ci` GitHub Action take ~5 minutes, rather than 20+ minutes.
4. Long-term phase: Split the tests to focus on individual features, rather than packing lots of things into a small amount of tests. Since Helm …
=> test: Introduce the Helm Chart Toolbox integration tests

pkg/pattern/stream_test.go
The pattern tests dealing with timing of writing patterns have been [failing intermittently](https://github.com/grafana/loki/actions/runs/16723739060/job/47333980758?pr=18525), and it's hard to reproduce locally. Once hunch I have is it could be related to timing issues, so this PR switches them to use a static time in the past to try and avoid flakiness.
**Checklist**
=> test: use static time to avoid flaky test

docs/sources/shared/configuration.md, pkg/ui/config.go
Forgot to register these as command line flags.
**Checklist**
=> fix: register goldfish flags

pkg/dataobj/consumer/logsobj/builder_metrics.go, pkg/dataobj/consumer/logsobj/multi_tenant_builder.go
This pull request hacks together a histogram to track the number of sections per tenant in each data object.
**Checklist**
=> feat: add histogram to track the number of sections per tenant

pkg/dataobj/metastore/multi_tenant_updater.go, pkg/dataobj/metastore/multi_tenant_updater_test.go
This pull request fixes a bug where data would be deleted from the metastore as it would just read the first section when updating, instead of all of them.
**Checklist**
=> fix: multiple sections not working when reading metastore object

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl
Problem: 
The Helm template _helpers.tpl contained incorrect context references (.ctx.ctx.Values) for several storage types that would cause template rendering failures.
Solution: Fixed context references from .ctx.ctx.Values to .ctx.Values for:
alibabacloud storage type
swift storage type
bos storage type
cos storage type
**Checklist**
=> fix(helm): Fix incorrect context references in Helm storage templates

go.mod, go.sum, vendor/github.com/twmb/franz-go/plugin/kprom/config.go, vendor/github.com/twmb/franz-go/plugin/kprom/kprom.go, vendor/modules.txt
With https://github.com/grafana/loki/pull/18596, we upgraded kprom to a version that contains a breaking change.
The library now introduces a metric `{ns}_buffered_produce_bytes_total` which is already defined as part of both Mimir and adaptime metrics.
Rolling forward in Mimir is more complicated than rolling backwards here in Loki as I can see there are no dashboard or alerts using this metric so I propose to do that.
Without this change it's currently impossible to vendor mimir or loki into backend-enterprise.
I'll also need to tell renovate to skip this version afterward
Signed-off-by: gotjosh <josue.abreu@gmail.com>
**Checklist**
- **Note** that …
=> chore(deps): Downgrade kprom from v1.3.0 back to v1.2.1

.github/renovate.json5
Prevent Renovate from upgrading github.com/twmb/franz-go/plugin/kprom
to v1.3.0+ by adding an allowedVersions rule to keep it in the 1.2.x range.
This is to prevent the new metrics introduced in this version to conflict with Mimir's and Adaptive metrics, see for more information: https://github.com/grafana/loki/pull/18785
Signed-off-by: gotjosh <josue.abreu@gmail.com>
N/A
**Checklist** …
=> chore: Pin kprom to 1.2.x range in Renovate config

operator/internal/manifests/internal/gateway/lokistack-gateway.rego
Some weeks ago, observatorium/api merged a PR upgrading OPA to v1.5.1 from v0.69 (https://github.com/observatorium/api/commit/5bbdc9d2b4e920d392dd4b8148b818a8dfa26bc8)
Loki operator defaults to using observatorium/api:latest image, and as such it is now deploying this updated image for the Gateway. It bundles in a static rego policy file which now needs syntax changes to be compatible with OPA post v1.0.
Did not open an issue for this and found none existing.
The issue is that loki-gateway instances running recent observatorium/api crash on start-up erroring on invalid OPA policy.
The syntax update was made with OPA itself:
```
opa fmt --v0-v1 --write lokistack-gateway.rego
``` …
=> fix(operator): upgrade OPA policy syntax for v1+

pkg/dataobj/consumer/mock_test.go, pkg/dataobj/consumer/partition_processor_test.go
This pull request moves mocks into `mock.go`.
**Checklist**
=> chore: move mocks into mock.go

pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/consumer/partition_processor_test.go
This pull request updates `partition_processor.go` to use the zero value as the initial value for last modified and last flush, as no modification or flush has occurred.
**Checklist**
=> chore: use zero value for time in partition_processor.go

pkg/dataobj/section.go, pkg/dataobj/section_reader.go, pkg/dataobj/sections/indexpointers/decoder.go, pkg/dataobj/sections/logs/decoder.go, pkg/dataobj/sections/pointers/decoder.go, pkg/dataobj/sections/streams/decoder.go
Originally, sections were intended to read their entire metadata region in a single call. This had the extra requirement for metadata to be as small as possible and to only include what's always necessary.
As a result of this, sections based on dataset stored additional metadata (like lists of pages per column) in the data region, allowing the sections to retrieve that optional metadata on demand.
This decision caused some issues:
- Metadata is now fragmented across a section, making it difficult to minimize the overhead of downloading metadata from object storage
- The metadata region size histogram is not representative of the true metadata size, as some metadata is stored in the data region.
This commit changes the dataobj.SectionReader interface to permit a section to read a subset of …
=> chore(dataobj): permit reading subset of section metadata

docs/sources/operations/storage/tsdb.md
Backport https://github.com/grafana/loki/pull/18818 to 3.4 branch.
=> docs: backport link fix 3.4

docs/sources/query/log_queries/_index.md
=> docs: backport typo fix to 3.5

pkg/dataobj/sections/logs/predicate.go, pkg/dataobj/sections/logs/reader.go, pkg/dataobj/sections/logs/reader_test.go, pkg/logql/bench/generator_query.go
Logs reader composes columns dataset only using columns that are in the projection list. But there are cases where column referred by a predicate is not projected, it will only be used to filter the rows and is not part of the resulting record schema.
Metric queries with line filter currently fail for this reason as log message is not projected and does not get included in the dataset.
This pr adds non-projected predicate columns to the columns dataset. It also removes a validation step in `logs.Reader` that checks whether the columns referred by predicates are part of `ReaderOptions.Columns` (projection list) since predicate columns need not always be projected. …
=> chore(dataobj): read non-projected predicate columns

pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/consumer/partition_processor_test.go
=> fix: dataobj-consumers did not commit offsets on idle flush

pkg/logql/bench/store_chunk.go, pkg/logql/bench/store_dataobj.go
Previously, the LogQL benchmarks put chunks and dataobjs in two different directories. This prevented developers from being able to properly run Loki locally against the synthetic data, as in a real Loki setup, dataobjs are in a subdirectory of where chunks are stored.
This commit imitates that setup: put all chunk storage in in the root data/ directory, then put dataobjs in data/dataobj.
=> chore(logql/bench): align data directory with production layout

pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/consumer/partition_processor_test.go
This pull request fixes a bug in dataobj consumers where we didn't reset the last modified time on flush.
**Checklist**
=> fix: reset the last modified timestamp on flush

pkg/dataobj/consumer/partition_processor_test.go
This pull request improves some of the unit tests for flushing to better separate tests that assert multiple expectations in the same method.
**Checklist**
=> chore: improve flush unit tests with better separation

docs/sources/operations/troubleshooting.md
Removed Jaeger topic from the Troubleshooting page as Jaeger is [deprecated](https://github.com/grafana/loki/issues/6812), and Loki has been [refactored](https://github.com/grafana/loki/pull/17859) to use the OTEL tracing library.
Fixes #17282
=> docs: remove Jaeger from troubleshooting

pkg/dataobj/consumer/mock_test.go, pkg/dataobj/consumer/partition_processor.go
This pull request adds a safety check for estimated size to `needsIdleFlush`. We had a bug where the `lastModified` timestamp was not reset and it tried to flush an empty builder.
**Checklist**
=> chore: add safety check for estimated size

docs/sources/operations/storage/retention.md, docs/sources/send-data/otel/_index.md
manual backport of https://github.com/grafana/loki/pull/18900 to 3.5 branch.
=> docs: backport add note to retention topic

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl
Roll back the change made to introduce Thanos-compatible storage for the ruler. needs further work and testing to introduce without breaking current implementations
Partially reverts 18740
**Checklist**
=> fix(helm): Roll back change to Thanos ruler storage

cmd/loki/main.go, docs/sources/shared/configuration.md, integration/cluster/cluster.go, pkg/distributor/distributor.go, pkg/validation/ingestion_policies.go, pkg/validation/ingestion_policies_test.go, pkg/validation/limits.go
This PR adds support for default policy stream mappings that are automatically merged with per-tenant overrides, following the same pattern used for GlobalOTLPConfig. This allows operators to define common policy stream mappings at the distributor level that are automatically applied to all tenants, while still allowing per-tenant customizations.
With this change, operators can define default mappings once and have them automatically applied to all tenants.
**How does it work?**
1. Default mappings are configured in the distributor config under default_policy_stream_mappings
2. During startup, these defaults are applied to the global limits configuration
3. When loading tenant limits from YAML, the defaults are automatically merged with …
=> feat: Default ingestion policy mappings merged with per-tenant mappings

docs/sources/shared/configuration.md, pkg/dataobj/consumer/mock_test.go, pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/consumer/partition_processor_test.go, pkg/dataobj/metastore/config.go, pkg/dataobj/metastore/metastore.pb.go
Makes metastore events required (no more best effort)
* Adds a new parameter that picks metastore partitions by dividing the partition-processor's partition by a constant factor. I chose 10, so for every 10 logs partitions, we use a single metastore partition (e.g. for every 10 partition-ingesters, we need 1 index-builder)
* This might need to be adjusted, so when creating the topic in the first place we'll need to set it to have enough partitions.
Part of https://github.com/grafana/loki-private/issues/1769
=> chore: Make metastore event synchronous

pkg/dataobj/consumer/mock_test.go, pkg/dataobj/consumer/partition_processor.go, pkg/dataobj/index/builder.go, pkg/dataobj/index/calculate.go, pkg/dataobj/index/calculate_test.go, pkg/dataobj/index/indexobj/builder.go, pkg/dataobj/index/indexobj/builder_test.go, pkg/dataobj/metastore/metastore_test.go, pkg/dataobj/metastore/metrics.go, pkg/dataobj/metastore/multitenancy/timeranges.go, pkg/dataobj/metastore/object.go, pkg/dataobj/metastore/object_test.go, pkg/dataobj/metastore/toc_writer.go, pkg/dataobj/metastore/toc_writer_test.go, pkg/dataobj/querier/store_test.go, pkg/dataobj/sections/indexpointers/builder.go, pkg/dataobj/sections/pointers/builder.go, pkg/logql/bench/store_dataobj.go
Enables multi-tenancy for the indexobj builders & Table of Contents files.
* Also changes the TableOfContentsWriter to be multi-tenant, writing each tenant's time range to a separate section. This is slightly different to the experiment branch, which wrote the min/max timerange across all the tenants into a single entry. The functionality when multi-tenant should be exactly the same as single-tenant, now.
Fixes https://github.com/grafana/loki-private/issues/1769
* Please check multitenancy/timerange.go - I wasn't a massive fan of having a new interface in a separate package but I couldn't find an easier approch without generating import loops. I could just use …
=> chore: Support multi-tenancy in indexobj builder 

production/helm/loki/CHANGELOG.md
encourages new changelog entries to make a newline, preventing conflicts between PRs.  It's possible I'm getting ahead of myself with this since I haven't seen evidence of it, but I don't think that's the case.
**Checklist**
=> docs: encourage new entries to make newline

cmd/dataobj-inspect/stats.go
Fixes a panic in the `stats` sub-command when printing the latest version of dataobjs.
```
panic: runtime error: slice bounds out of range [12:9]
goroutine 1 [running]:
main.(*statsCommand).printStreamsSectionStats(0x103478b18?, {0x10347e6f0, 0x103a2a080}, 0x1, 0x0?)
/Users/grobinson/go/src/github.com/grafana/loki/cmd/dataobj-inspect/stats.go:76 +0x69c
main.(*statsCommand).printStats(0x140000cc090, {0x16d22f7c8?, 0x0?})
/Users/grobinson/go/src/github.com/grafana/loki/cmd/dataobj-inspect/stats.go:48 +0x38c
main.(*statsCommand).run(...)
/Users/grobinson/go/src/github.com/grafana/loki/cmd/dataobj-inspect/stats.go:25
github.com/alecthomas/kingpin/v2.(*actionMixin).applyActions(...)
```
**Special …
=> fix: panic in stats.go

cmd/dataobj-inspect/dump.go, cmd/dataobj-inspect/stats.go, pkg/dataobj/tools/stats.go
This pull request prints the tenant in the `dump` and `stats` sub-commands.
Example from `dump`:
```
Logs section:
offset: 0, tenant: -1
id: 41, timestamp: 2025-08-27 09:42:54.095359 +0100 BST, metadata:
detected_level=unknown
id: 40, timestamp: 2025-08-27 09:42:53.032302 +0100 BST, metadata:
detected_level=unknown
id: 39, timestamp: 2025-08-27 09:42:51.971561 +0100 BST, metadata:
detected_level=unknown
```
Example from `stats`:
```
Object:
size: 5.2 MB, sections: 2, tenants: 2
Logs section:
offset: 0, tenant: -1, columns: 4, compressed size: 5.2 MB, uncompressed size 5.2 MB
name: , type: stream_id, 68 populated rows, 72 B compressed (NONE), 72 B uncompressed
name: , type: timestamp, 68 populated rows, 249 B compressed (NONE), 249 B uncompressed …
```
=> feat: print the tenant in the dump and stats sub-commands

pkg/dataobj/metastore/metastore_test.go, pkg/dataobj/metastore/toc_writer.go, pkg/dataobj/metastore/toc_writer_test.go, pkg/dataobj/querier/metadata_test.go, pkg/dataobj/querier/store_test.go
This fixes an issue with the backoff in `writeEntry` where it could not be canceled by the caller, even if they wanted to. We now use the `ctx` from the argument instead.
**Checklist**
=> fix: backoff cannot be canceled via ctx

docs/sources/configure/storage.md
Fixed a very minor indentation typo at Loki's documentation for [storage examples](https://grafana.com/docs/loki/latest/configure/storage/#aws-deployment-s3-single-store)
**Describe the solution you'd like**
AS-IS
```yaml
storage_config:
tsdb_shipper:
active_index_directory: /loki/index
cache_location: /loki/index_cache
cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
aws:
s3: s3://<access_key>:<uri-encoded-secret-access-key>@<region>
bucketnames: <bucket1,bucket2>
```
TO-BE
```yaml
storage_config:
tsdb_shipper:
active_index_directory: /loki/index
cache_location: /loki/index_cache
cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk …
```
=> docs: fixed an indentation typo at storage example.

docs/sources/configure/storage.md
Manual backport of #19038 to 3.5 branch.
=> docs: backport typo to 3.5 branch

production/helm/loki/README.md, production/helm/loki/README.md.gotmpl
Fixing the link to the Helm documentation in the README.
=> docs: fixing link to Helm docs

cmd/dataobj-inspect/stats.go, pkg/dataobj/tools/stats.go
Adds p50, p95 and p99 sections per tenant to stats. For example:
```
Object:
size: 398 MB, sections: 142, tenants: 68, sections per tenant: p50: 2.00, p95: 2.00, p99: 8.00
Logs section:
offset: 0, tenant: 29, columns: 51, compressed size: 47 MB, uncompressed size 537 MB
...
```
**Checklist**
=> feat: add p50, p95 and p99 sections per tenant to stats

docs/sources/send-data/otel/_index.md, docs/sources/send-data/otel/native_otlp_vs_loki_exporter.md, docs/sources/shared/otel.md
- Preps some of the Loki OTEL content to be shared with Cloud Logs by moving the content into `docs/sources/shared/otel.md`.
- Adds note that the OTLP endpoint is the recommended way to send logs, and that Adaptive Logs users should be using the OTLP endpoint.
**Special notes for your reviewer:**
Topic with the shared content is https://deploy-preview-loki-19025-zb444pucvq-vp.a.run.app/docs/loki/latest/send-data/otel/
=> docs: prep OTEL shared content

pkg/dataobj/index/calculate.go, pkg/dataobj/index/calculate_test.go, pkg/logql/bench/store_dataobj.go
Fixes two issues with generating indexes in the benchmark suite
* The GetAndReplace objstore method requires the directory to exist
* The index Calculator didn't work with a "real" bucket due to context calcuation. The context is cancelled after calling errgroup.Wait() but it was re-used later. The in-mem bucket & readerAt implementations don't check the context during reads so this didn't trigger the existing tests.
=> chore: Fix index generation with filesystem

pkg/engine/engine.go
Fixes the initialization of the engine v2 so the prefixed metastore bucket doesn't also override the engine's bucket.
=> chore: Fix init of engine with metastore

cmd/dataobj-inspect/stats.go, pkg/dataobj/tools/stats.go
This pull request adds the p50, p95 and p99 section sizes when printing the stats for a data object.
```
Object:
size: 398 MB, sections: 142, tenants: 68
section sizes:
p50: 3.9 kB, p95: 44 MB, p99: 48 MB
sections per tenant:
p50: 2.00, p95: 2.00, p99: 8.00
Logs section:
offset: 0, tenant: -1, columns: 51, compressed size: 47 MB, uncompressed size 537 MB
name: , type: stream_id, 1467722 populated rows, 1.7 MB compressed (NONE), 1.7 MB uncompressed
name: , type: timestamp, 1467722 populated rows, 4.0 MB compressed (NONE), 4.0 MB uncompressed
```
**Checklist** …
=> feat: add p50, p95 and p99 section sizes per tenant

pkg/dataobj/consumer/consumer.go
This commit fixes a mistake in how we checked errors in the dataobj-consumer. If a fetch returned an error then we would discard records for all other fetches when instead we should have processed their records, which in turn would mean data loss.
**Checklist**
=> fix: fix possible data loss in dataobj-consumers

pkg/dataobj/consumer/logsobj/builder.go, pkg/dataobj/consumer/logsobj/builder_test.go, pkg/logql/bench/bench_test.go
Fixes a bug with logs builder which loses tenant information after resetting the builder. This happens after flushing a full section to the dataobj.
* added a test
* also added a test for generating test data to make it easier to debug these issues
=> chore: Fix tenant info in sections when resetting

tools/querytee/proxy_endpoint_test.go
- What: Deflake Test_ProxyEndpoint_SummaryMetrics in tools/querytee.
- Why: prom_testutil.ToFloat64 panics when a CounterVec has 0 children, causing sporadic failures
(“collected 0 metrics instead of exactly 1”).
- How: Replace the assertion with require.Eventually(...
prom_testutil.CollectAndCount(proxyMetrics.responsesComparedTotal) == 1 ...) so we wait for the metric
without panicking.
```
Run gotestsum -- -tags=assert -covermode=atomic -coverprofile=coverage.txt -p=4 ./${MATRIX_PACKAGE}/...
✖  tools/querytee (430ms)
✓  tools/querytee/goldfish (826ms) (coverage: 55.3% of statements)
=== Failed
=== FAIL: tools/querytee Test_ProxyEndpoint_SummaryMetrics (unknown)
panic: collected 0 metrics instead of exactly 1
goroutine 189 [running]: …
```
=> chore(querytee): Fix flaky proxy endpoint test panic

clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb, docs/sources/send-data/fluentd/_index.md
I added gzip compression function to fluentd plugin
**Checklist**
- default is off. this is compatible to past behavior.
=> feat: support 'compress gzip' setting in fluentd plugin

pkg/ingester/flush_test.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/ingester/owned_streams.go, pkg/ingester/owned_streams_test.go, pkg/ingester/stream.go, pkg/ingester/stream_test.go, pkg/ingester/streams_map_test.go, pkg/validation/limits.go, pkg/validation/limits_test.go
Adds policy-specific overrides for `max_streams_per_user` and `max_global_streams_per_user` limits.
```yaml
limits_config:
max_streams_per_user: 1000
max_global_streams_per_user: 10000
overrides:
tenant1:
max_streams_per_user: 500
max_global_streams_per_user: 5000
policy_overriden_limits:
finance:
max_streams_per_user: 200
max_global_streams_per_user: 2000
ops:
max_streams_per_user: 100
max_global_streams_per_user: 1000
```
- Policy-matching streams account for the regular owned streams count. Meaning that all streams matching a policy still account for the regular tenant stream limit, but streams not matching a policy do not account for the policy stream limit.
**Checklist**
- **Note** that Promtail is …
=> feat: per policy overridable stream limits

operator/Dockerfile, operator/Dockerfile.cross, operator/calculator.Dockerfile, operator/go.mod, operator/netlify.toml
Updates the Loki Operator to use a newer Go runtime.
**Checklist**
=> chore(operator): Update to Go 1.24.4

pkg/dataobj/index/calculate.go, pkg/dataobj/index/calculate_test.go, pkg/dataobj/index/indexobj/builder.go
Fixes a few bugs with the index-builder:
* Concurrent map access inside the builder after introducing parallelism in reading the stream sections
* Correctly reading tenant info from `section.Tenant` instead of `logsSection.Tenant()`, as the latter is empty (I will remove that method in another PR)
* Removing functionality to flush Pointers & Stream sections on hitting the max section size. Stream sections in log objects already do this, and Pointers sections need to maintain state about which sections have been seen to avoid duplicating data. This was never a problem for real data as they didn't get near the section size, but I picked it up as an edge case in tests.
* Fixes an edge case where a builder would fail to flush if a tenant's builder was …
=> chore: Fix bugs in the index-builders

pkg/dataobj/metastore/object.go, pkg/dataobj/metastore/object_test.go, pkg/dataobj/querier/metadata_test.go, pkg/dataobj/querier/store.go, pkg/dataobj/querier/store_test.go, pkg/engine/executor/executor.go
Adds ability to handles multi-tenant objects in the query engine & metastore
* This requires objects to have the `section.Tenant` value set (which the builders on main do)
* The metastore filters for the tenant ID in the context throughout ToC and Index files
* The query engine filters for the correct stream section when initialising DataobjScans, using the tenant ID in the context.
* Also adds multi-tenant support to reading dataobj using the old engine
Fixes https://github.com/grafana/loki-private/issues/1769
=> chore: Read multi-tenant objects in query-engine

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/community-openshift/manager_related_image_patch.yaml, operator/config/overlays/community/manager_related_image_patch.yaml, operator/config/overlays/development/manager_related_image_patch.yaml, operator/config/overlays/openshift/manager_related_image_patch.yaml, operator/docs/operator/compatibility.md, operator/hack/addons_dev.yaml, operator/hack/addons_ocp.yaml, operator/internal/manifests/var.go, operator/jsonnet/jsonnetfile.lock.json
Updates the Loki operand to the most recent version.
https://issues.redhat.com/browse/LOG-7660
- The Jsonnet source for the dashboards was updated as well, but the dashboards contain no change.
**Checklist**
=> feat(operator): Update Loki operand to v3.5.4

docs/sources/shared/configuration.md, pkg/dataobj/internal/dataset/reader.go, pkg/dataobj/internal/dataset/reader_downloader.go, pkg/dataobj/sections/indexpointers/iter.go, pkg/dataobj/sections/indexpointers/row_reader.go, pkg/dataobj/sections/logs/iter.go, pkg/dataobj/sections/logs/reader.go, pkg/dataobj/sections/logs/row_reader.go, pkg/dataobj/sections/logs/table_merge.go, pkg/dataobj/sections/pointers/iter.go, pkg/dataobj/sections/pointers/row_reader.go, pkg/dataobj/sections/streams/iter.go, pkg/dataobj/sections/streams/reader.go, pkg/dataobj/sections/streams/row_reader.go, pkg/engine/engine.go, pkg/engine/executor/dataobjscan.go, pkg/engine/executor/executor.go, pkg/engine/executor/streams_view.go, pkg/logql/engine.go
`dataset.readerDownloader` was originally introduced in #16429, an attempt to balance peak memory usage of reading a section with read times by downloading a configurable size of pages in advance. 
In practice, each roundtrip to object storage adds too much of a latency hit, and we've started to set the cache limit high enough to ensure that each reader only needs a single prefetch. Given what we've found, it no longer makes sense to control peak memory usage via the prefetch size. Other options, such as downloading directly to disk, may be explored in the future. 
In the meantime, this PR removes the ability to specify a cache size. All non-pruned pages will be bulk requested using the range reader (#19067) on the first read call. Pages which have left the potential read window will …
=> chore(engine): move to toggleable section prefetching

docs/sources/shared/configuration.md, pkg/dataobj/consumer/logsobj/builder.go, pkg/dataobj/index/indexobj/builder.go, pkg/dataobj/internal/dataset/column_builder.go, pkg/dataobj/internal/dataset/column_test.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/metastore/toc_writer.go, pkg/dataobj/sections/indexpointers/builder.go, pkg/dataobj/sections/indexpointers/builder_test.go, pkg/dataobj/sections/indexpointers/row_reader_test.go, pkg/dataobj/sections/logs/builder.go, pkg/dataobj/sections/logs/table.go, pkg/dataobj/sections/logs/table_build.go, pkg/dataobj/sections/logs/table_merge.go, pkg/dataobj/sections/logs/table_test.go, pkg/dataobj/sections/pointers/builder.go, pkg/dataobj/sections/pointers/builder_test.go, pkg/dataobj/sections/pointers/row_reader_test.go, pkg/dataobj/sections/streams/builder.go, pkg/dataobj/sections/streams/builder_test.go, pkg/dataobj/sections/streams/reader_test.go, pkg/dataobj/sections/streams/row_reader_test.go, pkg/engine/executor/streams_view_test.go
This PR introduces an option for the column builder to limit the number of rows in a page.
It can be set for logs object and index objects separately using `-dataobj-consumer.max-page-rows` and `-dataobj-index-builder.max-page-rows` respectively.
=> chore(dataobj): Add option to set target row limit for pages

pkg/limits/service.go
Same behavior, but done properly 😄 . Why didn't I use `IsZero()` the first time? 😖 
**Checklist**
=> chore: should use IsZero() instead of comparison to time.Time{}

pkg/logql/bench/store_dataobj_v2_engine.go
Recent pull request #19198 changed the folder structure of the benchmark dataset so it can also easily be read by a local Loki instance. However, this change broke the tests of the benchmarks itself, due to a wrong storage path, which caused the execution to not return any results.
=> chore(bench): Fix logql benchmark test setup

pkg/ingester/kafka_consumer.go, pkg/kafka/partition/reader_service.go
This commit fixes a bug where cancelling the context when there are no more records prevented the reader from cleaning up. For example, when changing from starting to running phase after processing consumer lag at startup. This is a problem for dataobj-consumers which might want to build an object and flush a metastore event.
**Checklist**
=> fix: fix context canceled stops reader from cleaning up

docs/sources/shared/configuration.md, pkg/dataobj/index/builder.go, pkg/dataobj/index/builder_test.go, pkg/dataobj/index/config.go, pkg/dataobj/index/indexer.go, pkg/dataobj/index/indexer_test.go, pkg/dataobj/index/metrics.go
This pull request is a medium sized refactoring of the dataobj index builder to support handling stale partitions in terms of buffered events per index but less than `Config.EventsPerIndex`. In particular:
- All the build index code is moved to a separate abstraction in `indexer.go` that the builder is feeding via a golang channel.
- The builder incorporates now a secondary async routine that flushes buffered event objects to the indexer according to configured flush timeout.
Fixes grafana/loki-private#1967
**Checklist** …
=> chore: Refactor dataobj index builder to handle buffered events from stale partitions

.github/workflows/promtail-windows-test.yml
This test has been very flaky lately, this is quality of life improvement to only run in on PRs that touch promtails code.
**Checklist**
=> ci: add path restrictions to promtail-windows-test.yml

operator/internal/handlers/internal/gateway/tenant_secrets.go, operator/internal/handlers/internal/gateway/tenant_secrets_test.go, operator/internal/manifests/gateway_tenants.go, operator/internal/manifests/var.go
Related with https://issues.redhat.com/browse/OSPRH-19446
**Checklist**
=> chore(operator): improve error message when users configure tenants in static and dynamic mode

pkg/engine/planner/physical/planner.go, pkg/engine/planner/physical/planner_test.go
Fixes the grouping logic for overlapping entries
Grouping of time ranges didn't work in certain cases, due to a bug in the processing order.
* If a two non-overlapping ranges are processed before a range that covers them both, only one of them will become the "main" range and form a group, the other will continue to be an isolated range.
For example, Processing the following (sorted by end time) results in:
```
range 1 -1==4------
range 2 ------6=8--
range 3 -1=======9-
produces
group 1 -1=======9- (merge 3 with 1)
group 2 ------6=8--
```
after the fix to the sorting, the groups are correctly merged by processing from the end to the beginning
```
range 3 -1=======9-
range 2 ------6=8--
range 1 -1==4------
produces
group 1 -1*******9-
```
The fix …
=> chore: Fix time range grouping logic in some cases

pkg/engine/executor/functions.go
Previously, genericFunction.Evaluate was accidentally converting the left-hand ColumnVector into an array multiple times (once per row), as the loop condition (which converted the argument into an array) was evaluated at the end of each iteration.
If the left-hand side was a CoalesceVector, this became extremely expensive. Ensuring that the left-hand side is only converting the array once makes some queries using logfmt 6x faster[^1]:
goos: darwin
goarch: arm64
cpu: Apple M2 Ultra
│ after-orig.txt │            after-logs.txt            │
│     sec/op     │    sec/op     vs base                │
{region="ap-southeast-1",_env="dev"}_[BACKWARD]                                                                            1.082 ±  4%    1.063 ±  7% …
=> perf(engine): reuse existing array in genericFunction.Evaluate

pkg/engine/planner/logical/builder_convert.go, pkg/engine/planner/logical/planner_test.go
This fixes the SSA form of logical plans to follow linearly, such that no instruction or value references a value (by ID) declared after it. This was caused by predicates on MAKETABLE not being added as instructions when they were first encountered.
Fixing this also revealed that an instruction/value with two references was generating a new ID for each time it was walked. This is also fixed by only generating an ID if one does not already exist.
Fixing these issues does not change the behaviour of the logical plan; it just makes the SSA printed form more consistent with how SSA forms are typically formatted.
=> chore(engine/logical): fix order/duplicates of SSA form

pkg/engine/planner/physical/optimizer.go, pkg/engine/planner/physical/optimizer_test.go, pkg/engine/planner/physical/planner.go
`Merge` and `SortMerge` nodes with 1 or less children are effectively no-op nodes and can safely be removed from the plan during the optimization phase.
=> chore(engine): Eliminate no-op Merge/SortMerge nodes during plan optimization

pkg/ui/frontend/package-lock.json, pkg/ui/frontend/package.json
The recent dependabot update for this pkg (https://github.com/grafana/loki/pull/19292) broke the image building of new Loki versions ([example for k274][1]).
Looks like this is a known issue of @swc/core v1.13.19 and the maintainers decided to put back v1.13.5 as the `latest` version on npm (https://github.com/swc-project/swc/issues/11120#issuecomment-3344827789).
This PR manually reverts to v1.13.5
[1]: https://github.com/grafana/loki/actions/runs/18085322757/job/51455738207
=> fix: downgrade UI's @swc/core dep back to v1.13.5

pkg/dataobj/internal/dataset/value.go, pkg/dataobj/internal/dataset/value_test.go
We can have a predicate checking for an empty string, e.g. {"foo" = ""}. If a row has no value for the column "foo", it will return a nil value for that column. Thus, when we go to compare the row with the predicate, we will be comparing an empty value to a nil value. This change adjusts the comparison check so that we correctly handle this special case.
**Checklist**
- [n/a] Documentation added
- [n/a] Changes that require user attention or …
=> fix: Add special case handling for comparing empty and nil values

pkg/dataobj/internal/dataset/column_test.go, pkg/dataobj/internal/dataset/page_builder.go, pkg/dataobj/internal/dataset/page_reader_test.go, pkg/dataobj/internal/dataset/page_test.go, pkg/dataobj/internal/dataset/reader_basic_test.go, pkg/dataobj/sections/logs/reader.go, pkg/dataobj/sections/logs/reader_test.go
Treat Message type columns as required, so always returns a value for them when reading logs.
* Currently we cannot differentiate between a NULL value and an empty value. For most columns, this isn't an issue but for the Message column, an empty log message is a valid value as needs to be returned for parity with the old engine.
* There are several ways to fix this, and ~I chose to return a value for Message types on Read, treating Message as a required column.~ I switched to making this fix on the logs writer instead.
Fixes https://github.com/grafana/loki-private/issues/1989
I'm not certain this is the best way to fix this case. I'm happy to implement any alternative fixes such …
=> chore: Handle empty message values in v2 logs reader

.github/workflows/operator-images.yaml, .github/workflows/operator-release-please.yml
With this update we now:
- Always push `latest` to `grafana/loki-operator`
- Always push `latest` to `quay.io/openshift-logging/loki-operator`
- Always push `latest` to `quay.io/openshift-logging/loki-operator-bundle`
- Always push `latest` to `quay.io/openshift-logging/storage-size-calculator`
- Always push `PR_Number` to quay.io/openshift-logging/loki-operator for testing
- We **no longer** will push `v0.0.1` or date-based tags
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted …
=> refactor(operator)!: CI publishing image strategy 

.github/jsonnetfile.json, .github/jsonnetfile.lock.json, .github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet, .github/workflows/check.yml, .github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml
Pulls in library support for the new Zizmor findings.  This support was added for the 2.9 branch [here](https://github.com/grafana/loki-release/pull/272).
**Checklist**
=> chore(build): bump 2.9 release code

Makefile
Ever since we upgraded the `golangci-lint` version in CI, I have had trouble running linting locally because I could no longer run it in container, since we never updated the `golangci-lint` version in the container. I think this is a _good_ this and am in favor of moving away from the build container for all but promtail stuff. That being said, the default tags in the `Makefile` don't work for all OSes (since I can get journald headers on Mac), so we need to make them conditional. This is and attempt to do so.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are …
=> chore: remove build container from lint
