production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/query-frontend.libsonnet
Also lowers the queue size to 1024, which seems more  reasonable.
=> simplifies jsonnet sharding

go.mod, pkg/loki/loki.go, pkg/promtail/server/server.go, vendor/modules.txt
This could be useful for understanding more off CPU time. (like io/syscall)
=> Add fgprof to Loki and Promtail.

pkg/logql/log/parser_hints_test.go
I was able to find out where was the issue with that test yesterday.
Now I realized that we can mutate (re-slice) the given log line, and so other test would fail.
This also make the parallel back.
=> Improve the parser hint tests.

pkg/logql/engine.go, pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/querier/queryrange/stats.go, pkg/querier/queryrange/stats_test.go
This can be useful to investigate how many wasted queries have been made by the frontend.
=> Add limit and line_returned in the query log.

docs/sources/logql/_index.md
to prevent people from running into https://github.com/grafana/loki/issues/3436
* The `|~` operator is a partial match. One would intuitively expect that `=~` would behave the same way, but it is in fact a exact match. It's important to point that out.
* Many log lines have newlines in them (at least in my case), so it's important to remind users that `.` does not match newlines by default.
Fixes #3436 
**Checklist**
=> docs: add note about regex

production/loki-mixin/dashboards/dashboard-loki-operational.json
Seeing as I'm used to disregarding the `container_memory_usage_bytes` metric due to it's interaction with go runtimes from ~1.13->1.15 (which don't proactively release memory), this changes to the preferred `go_memstats_heap_inuse_bytes` which I end up replacing it with.
=> Use better memory metric on operational dashboard

tools/promtail.sh
Don't auto-include pod labels as loki labels as a sane default. Folks regularly run into stream limits when they have a bunch of labels on their pods, so better to remove this to get them a nicer first onboarding experience.
**Checklist**
=> Don't auto-include pod labels as loki labels as a sane default

pkg/querier/queryrange/codec_test.go, pkg/querier/queryrange/downstreamer.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/split_by_interval.go, pkg/querier/queryrange/split_by_interval_test.go
The step needs to be taken into account:
- to be removed on each split end.
- to not split queries that have a step lower than the split interval.
The code is taken from Cortex but adjusted to keep the nanoseconds precision.
=> Fixes split interval for metrics queries.

cmd/loki/loki-local-config.yaml, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/http.go, pkg/distributor/http_test.go, pkg/ingester/checkpoint_test.go, pkg/ingester/flush_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/recovery_test.go, pkg/loki/loki.go, pkg/loki/modules.go, pkg/loki/runtime_config.go, pkg/promtail/targets/lokipush/pushtarget.go, pkg/util/runtime/config.go
A way to change values within Loki at runtime, exactly the way overrides work but we use overrides explicitly for Limits
Rather than overload the Limits struct with non limit things instead I am creating another struct for runtime Config changes.
=> Loki: Per Tenant Runtime Configs

docs/sources/upgrading/_index.md
Fixes a typo in the upgrade docs
=> docs/upgrading: Fix typo

pkg/logql/lex.go, pkg/logql/parser_test.go
Fixes Issue 28535 in oss-fuzz: loki:fuzz_parse_expr: Out-of-memory in fuzz_parse_expr
We were allowing non-utf8 and regex parsing would go crazy with this.
=> Fixes out-of-memory fuzzing issue.

pkg/logql/lex.go
This was caused by a lot of allocations when parsing range duration.
=> Fixes Issue 28593: loki:fuzz_parse_expr: Timeout in fuzz_parse_expr.

pkg/logql/parser.go
The API anyway receives the query via querystring which is normally max out by 2k based on RFC2616.
This will improve fuzzing too.
=> Set a max size for the logql parser to 5k.

docs/sources/clients/promtail/configuration.md, go.mod, go.sum, pkg/promtail/scrapeconfig/scrapeconfig.go, pkg/promtail/targets/syslog/syslogparser/syslogparser.go, pkg/promtail/targets/syslog/syslogparser/syslogparser_test.go, pkg/promtail/targets/syslog/syslogtarget.go, vendor/github.com/influxdata/go-syslog/v3/README.md, vendor/github.com/influxdata/go-syslog/v3/makefile, vendor/github.com/influxdata/go-syslog/v3/nontransparent/parser.go, vendor/github.com/influxdata/go-syslog/v3/octetcounting/parser.go, vendor/github.com/influxdata/go-syslog/v3/octetcounting/scanner.go, vendor/github.com/influxdata/go-syslog/v3/options.go, vendor/github.com/influxdata/go-syslog/v3/syslog.go, vendor/modules.txt
support max_message_length configuration for syslog parser
Fixes #3398 
**Checklist**
=> support max_message_length configuration for syslog parser

pkg/logql/log/pipeline.go, pkg/logql/log/pipeline_test.go
Fixes #3485
Should also unblock #3481
When unsafely converting string to bytes the cap of the bytes is lost but not when doing bytes to string.
It seems that this is only a problem when using go 1.16 or when using delve.
=> Set the byte slice cap correctly when unsafely converting string.

docs/sources/clients/promtail/gcplog-cloud.md
Add note on scraping multiple GCP projects
NA
NA
**Checklist**
=> doc(gcplog): Add note on scraping multiple GCP projects

docs/sources/clients/promtail/stages/_index.md, docs/sources/clients/promtail/stages/labelallow.md, docs/sources/clients/promtail/stages/labeldrop.md, pkg/logentry/stages/labelallow.go, pkg/logentry/stages/labelallow_test.go, pkg/logentry/stages/stage.go
Support `labelallow` stage in Promtail
**Checklist**
=> Support labelallow stage in Promtail

docs/sources/operations/storage/boltdb-shipper.md
=> Documentation: Update boltdb-shipper.md to fix typo

pkg/promtail/targets/file/tailer.go
This PR adds more information to
```
skipping update of position for a file which does not currently exist
```
that is, it adds which file we're talking about with this log message. I've encountered a large number of such messages, and am in process of debugging them.
=> Promtail: Added path information to deleted tailed file

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
=> Fixes a bug where unpack would mutate log line.

pkg/loki/loki.go, pkg/storage/store.go, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/shipper_index_client.go, pkg/storage/stores/shipper/table_client.go, pkg/storage/stores/shipper/table_client_test.go, pkg/storage/stores/shipper/util/util.go
BoltDB Shipper stores object with the `index/` prefix which is hardcoded which limits the usage of a single bucket to a single Loki cluster when using `boltdb-shipper` as index store.
To allow users to share a bucket with multiple Loki clusters using `boltdb-shipper`, we want to make the object key prefix configurable so that different Loki clusters store the index with different prefix hence isolate the index.
This should not be a breaking change since we are defaulting the value of the config to `index/` which was hardcoded previously.
=> make prefix for keys of objects created by boltdb-shipper configurable

pkg/querier/ingester_querier.go
We were sending a `nil` value to [TailersCount](https://github.com/grafana/loki/blob/923671a17e250542e10037f514e8f5c21fa205b9/pkg/querier/ingester_querier.go#L247) which was working fine until we upgraded grpc client which probably had a check for it. This was causing Live Tailing of logs to fail. This PR fixes the issue by passing a pointer to a  concrete value instead.
Fixes #3506
=> fix live tailing of logs from Loki

docs/sources/clients/promtail/scraping.md
=> Fixes broken link in the documentation.

pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go
Series APIs are one of the most expensive queries in Loki which is used by Grafana Explore to suggest relevant labels to the users while building logql query. It is quite easy to run those queries accidentally for longer durations when the selected time window is a week or even a month-long and a user tries to write a query.
The problem here is we split the series API queries the same as other queries and we split the queries by smaller intervals like 15 or 30 minutes to get max parallelism. Now the series API downloads a single chunk per series in each split query which means the smaller the split interval more the work for queries since they would download chunks for the same series over and over again for each split queries. This PR changes the …
=> split series api queries by day in query-frontend

pkg/loghttp/query.go, pkg/loghttp/query_test.go
When splitting correctly steps in the frontend, some queries might be of a single step, e.g start == end.
This PR add supports for those queries, which are already supported by Cortex and Prometheus, but for some reason not Loki.
PS: I've spent a lot of time digging why we were doing single step queries, turns out this is normal 🤦 .
=> Support for single step metric query.

docs/sources/configuration/_index.md
Remove memberlist_config from `ingestor_config` and `distributor_config`. Its invalid to provide `memerlist_config` on these configs.
Fixes #2754 
**Checklist**
=> Remove memberlist config from ring config.

docs/sources/clients/promtail/scraping.md
Signed-off-by: Whyeasy <Whyeasy@users.noreply.github.com>
Added some extra documentation regarding the `gcplog` job and it's internal labels. 
**Checklist**
=> Added docs for GCP internal labels.

pkg/logql/marshal/marshal.go, pkg/logql/unmarshal/unmarshal.go
This changes two places under `pkg/logql` where `"github.com/json-iterator/go"` was being imported twice. I chose to stick with the `jsoniter` import alias to leave it obvious that something other than `encoding/json` was present.
=> single import of jsoniter in logql subpackages

docs/sources/clients/lambda-promtail/_index.md
Adds a title to https://grafana.com/docs/loki/latest/clients/lambda-promtail/. Currently the page is not showing a menu or page title.
=> docs: add title to Lambda Promtail

pkg/logcli/query/query.go, pkg/logql/matrix.go, pkg/logql/matrix_test.go, pkg/logql/test_utils.go
Since we split correctly metric queries, this bug has shown itself.
Basically we were not correctly stepping through time. We should always start from start, add the step until the start is after the end.
For more read: https://www.robustperception.io/step-and-query_range
Fixes #3541
=> Fixes a bug in MatrixStepper when sharding queries.

pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/querier.go
Add the changes for LBAC support.
=> LBAC changes

docs/sources/logql/_index.md
As per PR title. Also fix typo
=> LogQL Docs: Remove key-value pair missing from logfmt output

Makefile, pkg/logql/fuzz_test.go
=> Add a target to reproduce fuzz testcase

pkg/chunkenc/memchunk_test.go, pkg/logql/ast.go, pkg/logql/functions_test.go, pkg/logql/log/parser_hints_test.go, pkg/logql/optimize.go, pkg/logql/optimize_test.go, pkg/logql/parser.go, pkg/logql/parser_test.go
1- It currently 500.
2- Happens too late, at ingester level and querier. (better at the frontend)
3- Improve API surface level, we don't need to expose this validation for anything else than ParseLogSelector.
see #3216
/cc @sandeepsukhani
=> Improve matchers validations.

pkg/promtail/client/client.go
I think this was only impacting the docker driver who would start/stop for each new followed containers.
My assumption is that this would slowly build up and eat CPU over time.
Fixes #3319
I arrived to this conclusion since strace was showing a crazy amount of futex syscall and nothing else seems to be the cause.
:pray:
big thanks to @glebsam @till 
=> Properly release the ticker in Loki client.

pkg/querier/querier_mock_test.go, pkg/storage/batch.go, pkg/storage/batch_test.go, pkg/storage/hack/main.go, pkg/storage/store.go, pkg/storage/store_test.go
=> Add a chunk filter hook in the store.

pkg/promtail/client/batch.go, pkg/promtail/client/client.go, pkg/promtail/client/multi_test.go
This was because each client would try to mutate the original set of labels.
Instead of cloning the map which can be expensive, I created a little helper that generate the string
from the labelset without a set of label name.
Fixes #3571
I also added a test to see if this was reproducible and it was indeed:
```
~/go/src/github.com/grafana/loki master*
❯ go test -timeout 30s -tags dev,gofuzz -race -run ^TestMultiClient_Handle_Race$ github.com/grafana/loki/pkg/promtail/client -v -count=1 -timeout=0s
=== RUN   TestMultiClient_Handle_Race
Read at 0x00c0000b77d0 by goroutine 22:
runtime.mapaccess2_faststr()
/usr/local/Cellar/go/1.16.2/libexec/src/runtime/map_faststr.go:107 +0x0
github.com/grafana/loki/pkg/promtail/client.(*client).getTenantID() …
```
=> Fixes a race when using specific tenant and multi-client.

production/loki-mixin/config.libsonnet, production/loki-mixin/dashboards.libsonnet, production/loki-mixin/dashboards/dashboard-utils.libsonnet, production/loki-mixin/dashboards/loki-reads-resources.libsonnet, production/loki-mixin/dashboards/loki-writes-resources.libsonnet
These dashboards are inspired by Reads and Writes resource usage Cortex dashboards.
They come in handy when we want to quickly find out bottlenecks in reads/writes or whether we have over-provisioned or under-provisioned the cluster.
Here are the screen captures showing how dashboards would look
**Reads Resources:**
**Writes Resources:**
=> add loki resource usage dashboard for read and write path

pkg/logql/stats/grpc.go
I was recently debugging a panic in our queriers and found out we acquire a lock for mutating this slice but don't acquire the lock for reading. I'm guessing this was an oversight as the lock was only used in one place prior (the `addTrailer` method).
```
goroutine 34388532 [running]:
github.com/grafana/loki/pkg/util/server.onPanic(0x2072aa0, 0x3787ff0, 0x3787ff0, 0x0)
/src/loki/pkg/util/server/recovery.go:41 +0x7b
github.com/grafana/loki/pkg/util/server.glob..func1.1.1(0x2834870, 0xc004b2e8c0)
/src/loki/pkg/util/server/recovery.go:29 +0x55
panic(0x2072aa0, 0x3787ff0)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/grafana/loki/pkg/logql/stats.decodeTrailer(0x283eea8, 0xc054461d10, 0x0, 0x0, 0x0, 0x0, 0x0, …
```
=> locks trailers during iteration

docs/sources/logql/_index.md
Corrects typo made in example of `Log Queries` section
=> documentation: typo correction

pkg/loki/loki.go, pkg/loki/modules.go
=> Loli: Make the store field public

pkg/ingester/checkpoint.go, pkg/ingester/checkpoint_test.go, pkg/ingester/flush_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go
Follow up on #3569 this is the missing piece.
/cc @MichelHollands
=> Adds chunk filter hook for ingesters.

.drone/drone.jsonnet, .drone/drone.yml
Now that the promtail builds are part of a separate pipeline they need to be included as dependencies on the manifest step
=> Build: Fix drone dependencies on manifest step

pkg/ingester/client/client.go, pkg/loki/loki.go, pkg/loki/modules.go
This makes the cfg and ingester fields public for LBAC work and adds a way to add GRPC interceptors to the IngesterClient.
=> Add interceptor override and make ingester and cfg public

pkg/validation/limits.go
Add `json` struct tags to overrides limits. (to be consistent with [Cortex](https://github.com/cortexproject/cortex/blob/master/pkg/util/validation/limits.go#L34)) 
Fixes NA
**Checklist**
=> Add json struct tags to limits.

pkg/distributor/distributor_test.go, pkg/distributor/validator_test.go, pkg/loki/modules.go, pkg/querier/querier_test.go, pkg/storage/store_test.go, pkg/validation/limits.go, pkg/validation/limits_test.go
Rationale
1. support user-friendly duration format (e.g: "1h30m45s") in JSON value.
2. In consistent with Cortex and tempo.
Fixes NA
**Checklist**
=> replace `time.Duration` -> `model.Duration` for `Limits`.

pkg/distributor/validator.go, pkg/distributor/validator_test.go, pkg/validation/validate.go
=> Rejects push requests with  streams without labels.

docs/sources/clients/promtail/configuration.md
Signed-off-by: Trevor Whitney <trevorjwhitney@gmail.com>
Adds a note about avoid re-ingesting rotated logs because of overly permissive log match patterns.
**Checklist**
=> Documentation: add note about wildcard log patterns and log rotation

go.mod, go.sum, pkg/storage/stores/shipper/util/util.go, vendor/github.com/klauspost/pgzip/.gitignore, vendor/github.com/klauspost/pgzip/.travis.yml, vendor/github.com/klauspost/pgzip/GO_LICENSE, vendor/github.com/klauspost/pgzip/LICENSE, vendor/github.com/klauspost/pgzip/README.md, vendor/github.com/klauspost/pgzip/gunzip.go, vendor/github.com/klauspost/pgzip/gzip.go, vendor/modules.txt
Since index file are expected to be large, this will help to compress/decompress in parallel.
=> Use pgzip in the compactor.

cmd/migrate/main.go, pkg/logcli/query/query.go, pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/storage/store.go, production/ksonnet/loki/config.libsonnet
From now on it will be applied at the frontend, ruler and querier level.
The querier validation was missing so I added it.
=> Deprecate max_look_back_period in the chunk storage.

pkg/storage/stores/shipper/downloads/table.go
Sometimes files get corrupted when the process gets killed in the middle of a download operation which causes boltdb client to panic. We already recover the panic but the lock on the file is not released by boltdb client which causes the reopening of the file to fail when the sync operation tries it. We want to remove the file failing to open to get rid of the lock.
=> cleanup boltdb files failing to open during loading tables which are possibly corrupt

pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/expiration_test.go, pkg/storage/stores/shipper/compactor/retention/retention.go
This allows to call model.Time only once per table which is reasonable for accuracy and this will save some cpu cycle.
=> Pass in the now value to the retention.

pkg/loki/modules.go
=> Fixes a panic with the frontend when use with downstream URL.

CHANGELOG.md, clients/pkg/promtail/targets/file/filetargetmanager.go
Remove targets that dont have any tails, in order for the target to be removed and recreated during next sync
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
This PR fixes a bug that causes Promtail to stop tailing statefulset pods after they are deleted/rescheduled
Fixes #3586
The bug seems to be some race condition where the pod is deleted and recreated before the filetarget has been removed, this fix removes any filetarget that no longer has any tails, allowing them to be recreated which solves the problem, but it does not address the actual race condition.
**Checklist**
=> Promtail: Remove non-ready filemanager targets

clients/pkg/promtail/client/logger.go, docs/sources/clients/aws/ec2/_index.md
Promtail --dry-run is missing the timezone in output. 
If you want to test test stage "timestamp" you are unable to see if it works or not without importing the data into loki.
With this PR you just have to check dry-run output.
Fixes #3679 
Signed-off-by: Kris Budde <Kris@budd.ee>
=> promtail: added timezone to logger in dry-run mode #3679"

pkg/storage/stores/shipper/compactor/retention/marker.go, pkg/storage/stores/shipper/compactor/table.go, pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/util/util.go, pkg/storage/stores/shipper/util/util_test.go
Because we mostly download, read and upload but also  because all those operations are idempotent we don't
need to try to outsmart the OS by forcefully syncing the file to disk. The OS will use cache on files and we'll most likely not suffer from high disk io.
This was a conclusion I made after some digging of why the operation of compaction+retention was a bit slow sometimes. (+5s)
I've tried the PR in dev and the whole process execute now below 40s whereas because it was 4min.
strace before:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
75.75   12.333637        2122      5812       561 futex
10.81    1.760698         242      7267           nanosleep
7.69    1.252697          88     14287 …
```
=> Removes file sync syscall for compaction.

production/loki-mixin/dashboards/dashboard-loki-operational.json
This moves away from bad practice custom diff logger promtail configs that created too many streams and should work with a reasonably default config.
=> better operational dashboard annotations via diff logger

.drone/drone.jsonnet, .drone/drone.yml, Makefile, tools/deploy.sh
We are deprecating the CircleCI job
Also, moved secrets to Vault instead of Drone
Note that this will require Flux in all environments that are updated
Issue: grafana/deployment_tools#5307
=> Deploy loki with Drone plugin instead of CircleCI job

docs/sources/installation/docker.md, production/docker-compose.yaml
* update to correspond to recent release of 2.2.1
**Checklist**
=> Update docker.md for 2.2.1

.drone/drone.yml, .lychee.toml, Makefile, docs/sources/architecture/_index.md, docs/sources/clients/promtail/configuration.md, docs/sources/overview/_index.md, loki-build-image/Dockerfile
This is not part of the CI because it can be throttle and it's not super fast ~2min.
But still usefull to check that no link are down if we make some big structure changes.
=> Add a target to find dead links in our documentation.

clients/cmd/docker-driver/loki.go, clients/cmd/docker-driver/loki_test.go
This is happening because it can still received log, but the client might be already closed.
Fixes #3705
=> Fixes docker driver that would panic when closed.

docs/sources/configuration/_index.md
Fixes #3537. Due to a change in upstream we didn't catch that breaking change in the config.
=> Fixes doc w/r/t grpc compression.

pkg/storage/batch.go
Found out that we might have no listener and trying to send the information of cancellation.
I've moved the error information down the respective log and sample iterators so that we don't need to send
it via the channel.
This seems to have cause some pretty big memory leak on our side.
/cc @slim-bean
=> Fixes a goroutine leak in the store when doing cancellation.

pkg/chunkenc/dumb_chunk.go, pkg/chunkenc/facade.go, pkg/chunkenc/interface.go, pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_request.go, pkg/storage/stores/shipper/compactor/deletion/delete_request_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_store.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_store_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_table.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_table_test.go, pkg/storage/stores/shipper/compactor/deletion/metrics.go, pkg/storage/stores/shipper/compactor/deletion/request_handler.go, pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/expiration_test.go, pkg/storage/stores/shipper/compactor/retention/retention.go, pkg/storage/stores/shipper/compactor/retention/retention_test.go, pkg/storage/stores/shipper/compactor/retention/util_test.go
This PR leverages existing code for retention to support deletion for `boltdb-shipper`.
It relies on the Mark phase of retention which now also looks at eligible delete requests by talking to `DeleteRequestsManager` to decide whether the chunk is supposed to be deleted or not. For partially deleted chunks I have added a chunk rewriter which would build chunks for the interval for which they are not deleted and writes them to the store. A successful Mark process over all the tables considers delete requests as processed and the relevant chunk should be deleted later by the Sweep process.
The delete requests are persisted in a table called `delete_requests` which is a boltdb file. The file is uploaded to the object store every 5 mins or during …
=> Logs deletion support for boltdb-shipper store

pkg/storage/stores/shipper/compactor/retention/marker.go, pkg/storage/stores/shipper/compactor/retention/marker_test.go, pkg/storage/stores/shipper/compactor/retention/pool.go, pkg/storage/stores/shipper/compactor/retention/retention.go
This PR is two fold:
1) Rotate mark files when they reached 100k marks, this is to ensure we max out marks file
and don't create file that may be too big.
2) Instead of inserting marks using the chunk id as the key, we insert using a natural sequence.
This has two benefits:
- Keys are ordered, and so insertion are faster.
- Allows us to use boltdb fill percent to 100%, this means boltdb won't over allocate for inserting key in between unordered data.
Why ?
I realize that when inserting huge amount of marks, this operation can take up to hours since boltdb has to re-allocate pages over and over.
This is mainly because chunkid arrive without  specific order.
=> Improve retention mark files.

CHANGELOG.md, pkg/logcli/client/client.go
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
It allows user to run instant queries in LogCLI with a start time in the past
Fixes #3738
**Checklist**
=> correct logcli instant query timestamp param name

docs/sources/best-practices/_index.md
Removed unnecessary numbers from headings.
=> Docs: Update _index.md

docs/sources/clients/_index.md
The current H1 heading is not rendered by Hugo, so updated to a H2 heading.
Before:
After:
I also added a reference to this section at the top of the `/clients` index page since it was very difficult to discover (perhaps that was the point, and in that case I can revert it of course).
=> [docs/clients] fix header for "Unofficial clients" and add a reference to said section.

pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_store.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_table.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_table_test.go
It comprises of 2 fixes related to deletion support for `boltdb-shipper`:
1. I had used `break` instead of `return` in a select case which caused the loop to continue and not stop the compactor.
2. We need to skip compaction or apply retention on delete requests table.
=> Boltdb shipper deletion fixes

docs/sources/logql/_index.md
Removes a backtick typo from documentation.
~Fixes #<issue number>~
No related issue, small one character change
**Checklist**
=> [docs] Remove unnecessary backtick from example

docs/sources/logql/template_functions.md, pkg/logql/log/fmt.go
@pstibrany found some nice use case for this.
=> Add fromJson to the template stage.

pkg/storage/stores/shipper/compactor/retention/marker.go, production/loki-mixin/dashboards/loki-retention.libsonnet
This makes boltdb batch for deleting entries smaller and so goroutines for deletion of chunks
are not stuck.
Also improve metrics to refresh more often.
=> Improve mark file processing.

pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go
Reuse slice for tracking non-deleted intervals of chunks in delete requests manager. The change is safe since we anyways check one chunk at a time and future changes for concurrent checks are protected by a `sync.Mutex`.
=> reduce allocs in delete requests manager by reusing slice for tracing non-deleted intervals for chunks

docs/sources/clients/_index.md
I wrote a Julia client to Loki, https://github.com/fredrikekre/LokiLogger.jl so thought it could be added with the other third party clients
=> [docs] add LokiLogger.jl to unofficial clients.

pkg/storage/stores/shipper/compactor/retention/index.go
We fail the compactor's startup when we detect a store type other boltdb-shipper and the custom retention is enabled. This PR changes it to log a warning at startup because this would otherwise make users wait till their existing logs index in other store types go out of retention.
=> just log a warning when a store type other than boltdb-shipper is detected when custom retention is enabled

docs/sources/configuration/_index.md, docs/sources/configuration/examples.md, docs/sources/maintaining/_index.md, docs/sources/storage/_index.md
Links to the sections are in the right side navigation panel.
**Checklist**
=> Docs: remove unnecessary lists of sections

pkg/loki/loki.go, pkg/loki/modules.go
This adds a new new user invisible module called QueryFrontendTripperware. This allows LBAC overrides.
=> Add a QueryFrontendTripperware module

pkg/ruler/appender.go, pkg/ruler/remote_write.go, pkg/ruler/remote_write_test.go
Exposes the `ruler.RemoteWriter` interface and `ruler.RemoteWriteClient` implementation for use in integration tests.
N/A
**Checklist**
=> Exposing remote writer for use in integration tests

docs/sources/architecture/_index.md
=> documentation:  corrected double "the the" in index.md

docs/sources/configuration/_index.md, docs/sources/operations/storage/retention.md
This adds documentation for the experimental custom retention feature through the compactor.
/cc @sandeepsukhani  see how you can hook up your deletion documentation into it.
=> Retention doc

pkg/loki/loki.go, pkg/loki/modules.go
Allows for multiple targets to be defined. A "target" is a module inside Loki (querier, ingester, etc), and currently we can only target a single one. If no `-target` argument is provided, all modules are loaded, so there should be no reason to not allow multiple targets (i.e. a subset of modules) to be defined.
Fixes #3801
Cortex already implements this; I stole the implementation wholesale.
I also tried for a good couple hours to write tests for this, but unfortunately it's made rather difficult since a lot of the fields and functions in [this package](https://github.com/cortexproject/cortex/blob/master/pkg/util/modules/) …
=> Loki: allow for multiple targets

docs/sources/clients/docker-driver/configuration.md
Add more information on `container_name` default label and when it will be added to log line.
Makes the docker-driver docs bit clear about `container_name` default label
Fixes #3811 #3811 
**Checklist**
=> Update the docker-driver doc about default labels

pkg/ruler/appender.go, pkg/ruler/appender_test.go, pkg/ruler/remote_write.go, pkg/ruler/remote_write_test.go, pkg/util/queue.go
Extracts a queue interface, which makes the `PrepareRequest` function a bit more testable.
This is mostly just a refactoring PR.
N/A
These changes are just refactorings meant to make integration testing easier.
**Checklist**
=> Extracting queue interface

docs/sources/configuration/_index.md
**What this PR does / why we need it**: This PR corrects the documentation (enable_tls: true doesn't work and this new syntax is taken from cortex documentation, works, and is tested with AWS ElastiCache Redis cluster)
**Checklist**
=> docs: Change redis configuration value for enabling TLS to correct syntax

cmd/logcli/main.go, docs/sources/getting-started/logcli.md, pkg/logcli/client/client.go
Add support for basic token authentication in cases where the loki-queriers/frontends are exposed through a reverse proxy doing token/bearer authentication.
Based on already closed PR: #2889 Thanks @gcotone
Fixes #395 (Partially - it does not implement oauth2)
**Checklist**
=> logcli: add support for bearer token authentication

docs/sources/clients/promtail/stages/template.md
Fixes an example for `regexReplaceAll` template function:
- use correct function name
- add missing $ sign when referencing a regex submatch
Updates typos in promtail configuration example
**Checklist**
=> Promtail documentation: fix template example for regexReplaceAll function

pkg/storage/stores/shipper/compactor/retention/retention_test.go
This was due because the condition was using a string array that may be not in correct order.
/cc @dannykopping
=> Fixes a flaky retention test.

pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_test.go
We fail the sync operation when we encounter an error while downloading any of the files from the tables. When a file goes missing we fail the sync and retry it next time. A file only goes missing when it gets compacted away by the compactor so we do not want to fail the sync when a file goes missing in the middle of the sync operation.
**Checklist**
=> ignore download of missing boltdb files possibly removed during compaction

docs/sources/installation/tanka.md
Fixes installation in `latest` doc. using `jb` to pull latest loki and promtail fails because by default `jb` command, assumes `master` branch, but Loki repo renamed the `master` to `main` branch.
Fixes #3808 
NA
**Checklist**
=> Add explicit `main` to pull loki and promtail to install it via Tanka

pkg/logql/ast.go, pkg/querier/querier.go
example:
```
ts=2021-06-14T08:43:30.015895283Z caller=spanlogger.go:87 org_id=4336 traceID=0b6bb74a53efd739 level=debug msg="querying ingester" params="selector={stream=\"stdout\", pod=\"loki-canary-6  64d9d8d8f-99k22\"}, direction=BACKWARD, start=2021-06-14 08:17:03.037241855 +0000 UTC, end=2021-06-14 08:17:23.037241855 +0000 UTC, limit=1000, shards="
ts=2021-06-14T08:43:30.016305592Z caller=spanlogger.go:87 org_id=4336 traceID=0b6bb74a53efd739 level=debug msg="querying store" params="selector={stream=\"stdout\", pod=\"loki-canary-664d  9d8d8f-99k22\"}, direction=BACKWARD, start=2021-06-14 08:17:03.037241855 +0000 UTC, end=2021-06-14 08:17:23.037241855 +0000 UTC, limit=1000, shards="
```
I'm seeing a lot of duplicates for short queries, this can help understand why.
Signed-off-by: Cyril …
=> Logs ingester and store queries boundaries.

docs/sources/configuration/_index.md, docs/sources/rules/_index.md
Documenting the recording rules feature
N/A
**Checklist**
=> Ruler: documentation for recording rules

docs/sources/configuration/_index.md
Add missing `-querier.max-concurrent` config in the doc
Motivation: https://community.grafana.com/t/loki-total-worker-concurrency-is-greater-than-promql-max-concurrency/49283
Fixes NA
**Checklist**
=> Add missing `-querier.max-concurrent` config in the doc

docs/sources/logql/_index.md
We are using the word `backtick` at couple of places and `back-tick` is used just once. Improves searchability. 🙂
=> Documentation: Unify spelling of backtick in documentation

docs/sources/configuration/_index.md
In https://grafana.com/docs/loki/latest/configuration/, the sub-server yaml key to configure base path for API routes should be `http_path_prefix` instead of `http_prefix`. This PR fixes the documentation.
Not sure there is related issue yet.
My first PR in open-source world. Apologize if missing some details 😟 
**Checklist**
=> docs: http_path_prefix as correct item of server_config

docs/sources/clients/promtail/stages/multiline.md
Flag (?s:.*) need be to set for regex stage to capture full traceback log to the extracted map
**Checklist**
=> multiline: Add regex stage example and note

docs/sources/clients/promtail/configuration.md
This PR adds documentation section how to configure Promtail client with oauth2 settings.
Main branch already contains Prometheus HTTPClientConfig which can be configured to use oauth2. It was just not documented
It is related to open issue #2998 
**Checklist**
=> Add oauth2 docs options for promtail client

docs/sources/configuration/_index.md
**What this PR does / why we need it**: Update the documentation for a working parameter (parameter addresses is tested with AWS ElastiCache memcached and works, this parameter is taken from cortex documentation)
**Checklist**
=> docs: Add memcached_client parameter "addresses" list

docs/sources/installation/install-from-source.md
=> Docs: improve section on building from source

cmd/logcli/main.go, pkg/logcli/client/client.go
This adds a possibility to retry unsuccessful queries when using logcli
Example output of a failed query (there is no server running on that port):
```
./logcli query "{type=\"logtest\"}" --addr="http://127.0.0.1" --retries 3
2021/06/22 15:28:02 http://127.0.0.1/loki/api/v1/query_range?direction=BACKWARD&end=1624368482937234835&limit=30&query=%7Btype%3D%22logtest%22%7D&start=1624364882937234835
2021/06/22 15:28:02 error sending request Get "http://127.0.0.1/loki/api/v1/query_range?direction=BACKWARD&end=1624368482937234835&limit=30&query=%7Btype%3D%22logtest%22%7D&start=1624364882937234835": dial tcp 127.0.0.1:80: connect: connection refused
2021/06/22 15:28:02 error sending request Get "http://127.0.0.1/loki/api/v1/query_range?direction=BACKWARD&end …
```
=> logcli: Add retries to unsuccessful log queries

production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/distributor.libsonnet, production/ksonnet/loki/ingester.libsonnet, production/ksonnet/loki/overrides.libsonnet, production/ksonnet/loki/querier.libsonnet, production/ksonnet/loki/query-frontend.libsonnet, production/ksonnet/loki/ruler.libsonnet, production/ksonnet/loki/wal.libsonnet
Instead of hardcoding the names and mount path of configmap`overrides`, make it as variables.
Note: This doesn't impact any of the existing workloads, as the default value for these variables are same the one hardcoded!
Fixes: NA
**Checklist**
=> Make `overrides` configmap names and mount path as variables.

docs/sources/maintaining/release.md
Update steps to release versioned docs. (Need to be automated)
This makes versioned docs in consistent with Grafana.
More details:
https://github.com/grafana/website/pull/4970
https://github.com/grafana/loki/issues/3317
Fixes #3317 
**Checklist**
=> Update steps to release versioned docs

production/ksonnet/loki-canary/loki-canary.libsonnet, production/ksonnet/loki/boltdb_shipper.libsonnet, production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/distributor.libsonnet, production/ksonnet/loki/gateway.libsonnet, production/ksonnet/loki/index-gateway.libsonnet, production/ksonnet/loki/ingester.libsonnet, production/ksonnet/loki/loki.libsonnet, production/ksonnet/loki/overrides.libsonnet, production/ksonnet/loki/querier.libsonnet, production/ksonnet/loki/query-frontend.libsonnet, production/ksonnet/loki/ruler.libsonnet, production/ksonnet/loki/table-manager.libsonnet, production/ksonnet/loki/wal.libsonnet, production/ksonnet/promtail/promtail.libsonnet
**What this PR does / why we need it**: Removes kausal from the root element of the jsonnet library. Instead, declare it explicitly, because it is an implementation detail that is leaking to the consumers of the libraries, polluting the root element.
**Which issue(s) this PR fixes**: N/A
**Special notes for your reviewer**: I have tested this internally (see linked PR) by re vendoring this changes in a release and it is a no-op change (results in no diff).
**Checklist**
=> refactor(production/ksonnet): Remove kausal from the root element

pkg/distributor/http.go, pkg/logql/log/jsonexpr/jsonexpr_test.go, pkg/logql/log/jsonexpr/lexer.go
Fixes a tight loop in the JSON expression lexer, which results from unexpected input.
N/A
We discovered that a query with a JSON expression like `{stream="foo"} | json key="something.["else` caused our ingesters to crash (because we were searching for recent data - it'd crashed queriers if for older data).
This bug occurred because we only break out of the scan loop if a string is terminated `"` or a closing bracket is found `]` - but we don't check for a null byte or EOF which both indicate end of input.
**Checklist**
=> Querier/Ingester: Fixing json expression parser bug

pkg/storage/stores/shipper/compactor/table.go, pkg/storage/stores/shipper/uploads/table.go, pkg/storage/stores/shipper/uploads/table_test.go
A bug caused an ingester to crash, which had just created a new index file for writes but failed to write to it, including missing creating a bucket. When the ingester came back up, it uploaded the index file without the `index` bucket. Since all the boltdb files are expected to have it, the compactor started failing to compact the files.
This PR fixes the issue by validating existing boltdb files on ingester startup to see if they have an `index` bucket. If not, they would be removed.
**Checklist**
=> remove boltdb files from ingesters on startup which do not have a index bucket

docs/sources/configuration/_index.md
The documentation didn't list the compactor as a valid value for the `target` configuration which made us forget to run it initially. By listing it as a valid value, I think we could help others not to run into the same issue.
**Checklist**
=> Doc: List 'compactor' as valid value for target option

Makefile
This allows to build promtail without journald support on linux distributions that don't have systemd.
Run as
CGO_ENABLED=0 make promtail
Fixes #3933
=> Makefile: Only set PROMTAIL_CGO if CGO_ENABLED is not 0.

pkg/storage/stores/shipper/compactor/retention/marker.go
Currently we'll keep the last recorded time, but if the marker file doesn't exist anymore we should reset it.
This would allow us to build consistent alert based on marker files that are too far behind.
=> Improve marker file current time metrics.

.drone/drone.yml, Makefile, loki-build-image/build.sh, tools/image-tag, tools/increment_version.sh, tools/promtail.sh, tools/release_prepare.sh, tools/scrape_config.sh
This patch adds a Drone CI step that runs shellcheck on all Bash script
files.
=> Lint script files.

pkg/loki/runtime_config.go, pkg/loki/runtime_config_test.go
Recently came across this issue when testing Loki, if we don't provide overrides, Loki will crash on a nil pointer.
This PR fixes this issue, having no overrides is a valid use case.
=> Allow no overrides config for tenants.

cmd/cluster-plan/template.go, pkg/sizing/sizing.go
=> update sizing calc

docs/sources/getting-started/logcli.md
In this revision:
- I recaptured the help output from LogCLI for the various commands
- I separated the help output for the various commands into different sections.  Makes it easier to read, and makes it possible to use the horizontal scroll bar.
- New section title
- Rewrote the section on batching queries
- Corrected section/subsection nesting levels and made minor spelling changes
=> Docs: revise the LogCLI subsection

docs/sources/api/_index.md, docs/sources/configuration/_index.md, docs/sources/logql/_index.md, docs/sources/operations/storage/logs-deletion.md, docs/sources/operations/storage/retention.md, docs/sources/storage/_index.md
I found more than one way that experimental features are indicated within the docs.  This PR attempts to make them more obvious to the reader by highlighting prose in yellow.  I've also attempted to make this indication consistent for all the features currently marked as experimental.
Found and removed 2 indications of experimental (boltDB-shipper) that are no longer experimental.
=> Docs: Make identification of experimental items consistent and obvious

docs/sources/overview/_index.md, docs/sources/release-notes/_index.md, docs/sources/release-notes/v2-3.md
The prose is not yet flushed out.  Let's do that when we know what will go into a 2.3.0 Loki release.
=> Docs: add structure for a release notes section

pkg/storage/stores/shipper/compactor/compactor.go
Compactor panics when retention is not enabled. This PR fixes it by moving access to `expirationChecker`, which is only initialized when retention is enabled, behind the checks.
=> fix panic in compactor when retention is not enabled

pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/expiration_test.go
1. Add some tests for compactor.
2. Fix the condition in `IntervalHasExpiredChunks` check for retention with tests.
**Checklist**
=> add some tests in compactor and fix a bug in IntervalHasExpiredChunks check in retention with tests

pkg/storage/stores/shipper/uploads/table.go
When an active index file is corrupted due to Loki/Ingester abruptly stopping, it causes Loki/Ingester to fail to start.
We automatically clean up a corrupted file in the `boltdb-cache`, which we can download again from the object store, but we can't recover a file corrupted in the active index directory.
I would not prefer to remove the corrupt file without someone intervening manually because a corrupt file means something is wrong, and that happening frequently could cause data loss. So this PR keeps the behaviour the same but lets the user know which file is corrupt to either try to fix it or remove it.
Helps fix Loki failing to start due to a corrupt file on the write path as noticed in …
=> log name of the file failed to open during startup by ingester

docs/Makefile
This target builds local docs as they should look for commits that are
placed into the main branch, showing the next up, but not yet released
Loki docs.
=> Docs: added new target (docs-next) to the docs' Makefile.

clients/pkg/logentry/stages/metrics.go, clients/pkg/logentry/stages/metrics_test.go
=> Fixes negative gauge in Promtail.

tools/dev/loki-boltdb-storage-s3/.dockerignore, tools/dev/loki-boltdb-storage-s3/.gitignore, tools/dev/loki-boltdb-storage-s3/README.md, tools/dev/loki-boltdb-storage-s3/compose-down.sh, tools/dev/loki-boltdb-storage-s3/compose-up.sh, tools/dev/loki-boltdb-storage-s3/config/datasource.yaml, tools/dev/loki-boltdb-storage-s3/config/loki.yaml, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/dev/loki-boltdb-storage-s3/docker-compose.yml
This PR adds a new dev setup that allows you to run the full distributed mode locally on docker-compose.
What's interesting about it, is that it runs the current code base by compiling it and build it with debug symbol for remote debugging.
See the [README](https://github.com/cyriltovena/loki/blob/fc12ee18e3c543fc53b103fcff8de62ef2ba9841/tools/dev/loki-boltdb-storage-s3/README.md) for the usage.
/cc @owen-d @dannykopping Feel free to add more to it like alerting and ruling.
=> Development Docker Compose Setup

go.mod, go.sum, pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/unordered.go, pkg/chunkenc/unordered_test.go, vendor/github.com/Workiva/go-datastructures/LICENSE, vendor/github.com/Workiva/go-datastructures/rangetree/entries.go, vendor/github.com/Workiva/go-datastructures/rangetree/error.go, vendor/github.com/Workiva/go-datastructures/rangetree/immutable.go, vendor/github.com/Workiva/go-datastructures/rangetree/interface.go, vendor/github.com/Workiva/go-datastructures/rangetree/node.go, vendor/github.com/Workiva/go-datastructures/rangetree/ordered.go, vendor/github.com/Workiva/go-datastructures/rangetree/orderedtree.go, vendor/github.com/Workiva/go-datastructures/slice/int64.go, vendor/modules.txt
This PR is a no-op which adds some new (currently unused) code for an unordered head block. This will lay the groundwork for removing the ordering constraint and breaks this code into it's own PR.
=> Unordered head block

clients/pkg/promtail/targets/lokipush/pushtarget.go, cmd/migrate/main.go, pkg/distributor/distributor.go, pkg/distributor/http.go, pkg/ingester/flush.go, pkg/ingester/flush_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/logql/engine.go, pkg/querier/http.go, pkg/querier/querier.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/split_by_interval.go, pkg/storage/store.go
This change replaces all uses of the weaveworks/common method
for getting tenant/org ID with the Cortex wrapper which performs
some extra validation.
Signed-off-by: Nick Pillitteri <nick.pillitteri@grafana.com>
=> Use the Cortex wrapper for getting tenant ID from a context

pkg/storage/stores/shipper/compactor/retention/util_test.go
There are 2 flaky tests in retention which I am attempting to fix.
The tests fail based on when they run so this PR changes some tests by keeping that in mind to set the expectations right.
**Checklist**
=> fix flaky retention tests

docs/sources/api/_index.md, pkg/loki/loki.go, pkg/loki/version_handler.go, pkg/loki/version_handler_test.go, pkg/querier/queryrange/roundtrip.go, pkg/util/build/build.go
This changes introduces the `/version` endpoint for all components. It returns the build info in JSON. This should ease debugging.
Fixes #3221
**Checklist**
=> Return build info under `/loki/api/v1/status/buildinfo`.

pkg/ingester/ingester.go
Setting a ChunkFilterer on the ingester currently has to be done after the ingester is created using the `SetChunkFilterer()` function. This means another target had to be added that depends on the `ingester` target just to set this.
This  PR adds a field to the config so this can be set before the `ingester` target runs. No flag is added to set the new field.
**Checklist**
=> Add a chunk filterer field to the config

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
`json` and `logfmt` parser will attempt to extract all possible keys and values as labels.
But if a values currently contains the rune error (used as  replacement when there's an invalid rune) PromQL parser will fail and the request
will be fully rejected.
This PR removes those labels values when using those two parsers.
For other parser you can just decide to not extract these values.( At least that's my choice for now).
Unfortunately this comes with a small cpu overhead prices:
```
~/go/src/github.com/grafana/loki utf8-parser*
❯ benchcmp  before.txt after.txt
benchmark                                    old ns/op     new ns/op     delta
Benchmark_Parser/json/no_labels_hints-16     3647          4210          +15.44%
Benchmark_Parser/json/labels_hints-16        2210          2247 …
```
=> Reject labels with invalid runes when using implicit extraction parser.

pkg/storage/stores/shipper/uploads/metrics.go, pkg/storage/stores/shipper/uploads/table.go, pkg/storage/stores/shipper/uploads/table_manager.go, pkg/storage/stores/shipper/uploads/table_test.go
Adds a metric to count the failures in opening active index files while loading the tables.
The file would be left untouched with its path logged as error and the code would move ahead, not causing the service to stop until the file gets fixed. The metric would help users setup an alert on it to make sure the corrupt file does not go unnoticed.
Fixes #3219
=> add a metric for counting number of failures in opening existing active index files

clients/pkg/promtail/client/logger.go
Currently Promtail only logs the entry timestamp with second precision in dry-run mode; this should be nanosecond to match what Loki can support. Without this, users who are correctly parsing their timestamps with nanosecond precision will become confused when the dry-run output only shows second precision.
Fixes #3955
**Checklist**
=> Promtial: output timestamp with nanosecond precision in dry-run mode

pkg/logql/sharding.go, pkg/logql/step_evaluator.go
While poking around some sharding code I noticed a variable was referenced incorrectly. This didn't result in a bug, but made reading this piece of code confusing/counterintuitive. This PR fixes the variable naming and gives the interface a hint.
cc @jeschkies in case you're curious
=> fixes a badly referenced variable name in StepEvaluator code

pkg/logql/log/logfmt/jsonstring.go, pkg/logql/log/parser_test.go
This allows logfmt to handle newlines so long as they are quoted as expected. It still unquotes control chars so nothing should ever break. It just throws less errors.
**Rant**
There are other issues I have ignored. The main one being that the `ScanKeyval` parser tries to be more efficient by avoiding calling `unquoteBytes` unless it sees a `\`, but it relies on `unquoteBytes` to handle utf8. So a unicode token without a `\` may not be decoded correctly. 
`unquoteBytes` also has its own logic to check for slashes so it's inefficient
`unquoteBytes` also seems to expect that the given string starts and ends with `"` but surely anything passing the string has already checked for these delimiters so, why pass them?.. another mystery. And also why does …
=> Parser: Allow literal control chars in logfmt decoder

pkg/chunkenc/facade.go, pkg/chunkenc/interface.go
I noticed we've misrepresented the `Chunk.Size` method across Loki & Cortex. [Loki](https://github.com/grafana/loki/blob/main/pkg/ingester/flush.go#L398) uses this to describe the chunk's entry count, while [Cortex](https://github.com/cortexproject/cortex/blob/master/pkg/chunk/encoding/chunk.go#L72-L73) uses this to describe the byte size. You can see this by comparing the following two metrics:
`sum(rate(loki_ingester_chunk_size_bytes_sum[1m]))`
vs
`sum(rate(cortex_chunk_store_stored_chunk_bytes_total[1m]))`
This hasn't hurt us asides from misaligning metrics, but it's good to fix.
=> fixes chunk size method in facade

pkg/logql/ast.go, pkg/logql/ast_test.go, pkg/logql/engine.go, pkg/logql/evaluator.go, pkg/logql/expr.y, pkg/logql/expr.y.go, pkg/logql/functions.go, pkg/logql/optimize.go, pkg/logql/parser.go, pkg/logql/parser_test.go, pkg/logql/sharding.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/walk.go, pkg/logql/walk_test.go
The following change set provides a simple extension that enables walking the LoqQL AST for parsed and valid LogQL expressions. This helps to build third-party tooling that can inspect and manipulate LogQL queries before hitting the target Loki query-frontend/querier (e.g. [prom-label-proxy](https://github.com/prometheus-community/prom-label-proxy/)).
Furthermore this PR changes:
- The scoping from private to public for all expressions that comprise LogQL to allow type switching when executing the walking function. 
- The `MatcherExpr` struct includes a simple `AppendMatchers` method to append new label matchers when executing the walking function.
- The LogQL optimizer's custom `walkSampleExpr` is replaced by `expr.Walk`
**Which issue(s) this PR …
=> Add LogQL AST walker

pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/compactor/table.go, pkg/storage/stores/shipper/compactor/table_test.go
A couple of improvements:
1. During compaction, we create an empty file and merge the index from all the files into it. This wastes a lot of resources in a big cluster that has large index files. This PR changes it to use compacted file built from the last compaction as seed file and then copies index from all the other files into it. If there is no compacted file then it uses whatever files appear first in the list of files to compact. This should significantly reduce compaction time in a large cluster.
2. Allows configuring compactor to compact multiple tables at a time.
**Checklist**
=> Compactor improvements

go.mod, go.sum, pkg/loghttp/entry.go, pkg/loghttp/labels.go, pkg/loghttp/query.go, pkg/loghttp/query_test.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/codec_test.go, pkg/querier/queryrange/roundtrip_test.go, pkg/util/marshal/labels.go, vendor/github.com/buger/jsonparser/.gitignore, vendor/github.com/buger/jsonparser/.travis.yml, vendor/github.com/buger/jsonparser/Dockerfile, vendor/github.com/buger/jsonparser/LICENSE, vendor/github.com/buger/jsonparser/Makefile, vendor/github.com/buger/jsonparser/README.md, vendor/github.com/buger/jsonparser/bytes.go, vendor/github.com/buger/jsonparser/bytes_safe.go, vendor/github.com/buger/jsonparser/bytes_unsafe.go, vendor/github.com/buger/jsonparser/escape.go, vendor/github.com/buger/jsonparser/fuzz.go, vendor/github.com/buger/jsonparser/go.mod, vendor/github.com/buger/jsonparser/oss-fuzz-build.sh, vendor/github.com/buger/jsonparser/parser.go, vendor/modules.txt
Improves frontend allocation by using another json parser for streams.
This also try to use a `Bytes()` function if available when reading the body to avoid a copy. (This needs to be added to cortex too)
```
❯ benchcmp  before.txt after.txt8
benchmark                        old ns/op     new ns/op     delta
Benchmark_CodecDecodeLogs-16     9692959       6406357       -33.91%
benchmark                        old allocs     new allocs     delta
Benchmark_CodecDecodeLogs-16     124103         39037          -68.54%
benchmark                        old bytes     new bytes     delta
Benchmark_CodecDecodeLogs-16     6497881       2161604       -66.73%
```
=> Improve decoding of JSON responses.

docs/sources/api/_index.md, pkg/loki/loki.go
As far as I can tell from reading the "next" documentation, the
/loki/api/v1/status/buildinfo endpoint should return the build
information. The /version endpoint is also listed further down in the
documentation but from the code prior to this change, it looks like it
should perform the same function as buildinfo endpoint so I have
removed it.
I've updated the documentation to reflect my changes.
~I'm just pulling the documentation image in order to check that the changed heading works as expected.~ LGTM
**Checklist**
=> fix: Restore /config endpoint and correct handlerFunc for buildinfo

loki-build-image/Dockerfile
In loki-build-image Dockerfile, upgrade golangci-lint and Go.
Would like to see whether Loki will work with latest golangci-lint, fails for me locally.
**Checklist**
=> loki-build-image: Upgrade golangci-lint and Go

production/loki-mixin/dashboards/loki-retention.libsonnet
This uses now a graph panel which shows us lags over time.
=> Improve the sweep lag panel in the retention dashboard.

docs/sources/logql/functions.md, docs/sources/logql/template_functions.md
Reordering is in the left side nav panel.
=> Docs: add weights to YAML metadata to order the LogQL subsections

docs/sources/logql/ip.md
Tiny commit to fix a docs typo.
=> Fix docs typo: IP Matching section "=f" becomes "="

docs/sources/configuration/_index.md, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/roundtrip_test.go, pkg/validation/limits.go
This allows to skip sharding for recent time range. For example if the value is set to 1h,
all queries for the given tenant that are between now and now-1h are not sharded.
=> Add min_sharding_lookback limits to the frontends

pkg/ruler/remote_write.go, pkg/ruler/remote_write_test.go
Applies `write_relabel_configs` if defined
N/A
I missed this somehow in the original [implementation](https://github.com/grafana/loki/pull/3766).
**Checklist**
=> Ruler: implementing write relabelling on recording rule samples

go.mod, go.sum, pkg/ruler/memstore.go, vendor/github.com/cortexproject/cortex/pkg/distributor/distributor.go, vendor/github.com/cortexproject/cortex/pkg/ingester/ingester.go, vendor/github.com/cortexproject/cortex/pkg/ingester/ingester_v2.go, vendor/github.com/cortexproject/cortex/pkg/querier/blocks_store_queryable.go, vendor/github.com/cortexproject/cortex/pkg/querier/chunk_store_queryable.go, vendor/github.com/cortexproject/cortex/pkg/querier/distributor_queryable.go, vendor/github.com/cortexproject/cortex/pkg/querier/error_translate_queryable.go, vendor/github.com/cortexproject/cortex/pkg/querier/lazyquery/lazyquery.go, vendor/github.com/cortexproject/cortex/pkg/querier/querier.go, vendor/github.com/cortexproject/cortex/pkg/querier/queryrange/queryable.go, vendor/github.com/cortexproject/cortex/pkg/querier/queryrange/test_utils.go, vendor/github.com/cortexproject/cortex/pkg/querier/tenantfederation/merge_queryable.go, vendor/github.com/prometheus/prometheus/storage/interface.go, vendor/github.com/prometheus/prometheus/storage/merge.go, vendor/github.com/prometheus/prometheus/storage/noop.go, vendor/github.com/prometheus/prometheus/storage/remote/read.go, vendor/github.com/prometheus/prometheus/storage/secondary.go, vendor/github.com/prometheus/prometheus/tsdb/block.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/github.com/prometheus/prometheus/tsdb/index/index.go, vendor/github.com/prometheus/prometheus/tsdb/querier.go, vendor/github.com/prometheus/prometheus/web/api/v1/api.go, vendor/modules.txt
This bumps prometheus up to the changes from https://github.com/prometheus/prometheus/pull/9083 and Cortex to https://github.com/cortexproject/cortex/pull/4380
Those changes made a breaking change in the `LabelQuerier`'s `LabelNames` interface adding a slice of matchers, just like `LabelValues` already did. This isn't yet needed in Loki, but it's preventing us from smoothly upgrading further.
None, AFAIK.
**Checklist**
=> Upgrade Prometheus and Cortex to `LabelNames()` with matchers versions

pkg/storage/store_test.go, pkg/storage/util_test.go
I wanted to test that overlapping chunks are correctly re-ordered
and bump into a rounding issue.
Keeping both for future will avoid the same mistake.
=> Fixes test helper `newChunk` in the storage pkg.

production/loki-mixin/dashboards/dashboard-loki-operational.json
Modifies _Loki Operational_ dashboard to group by container in Memcached row, so we can attribute used methods to components.
For example, we have an entry for `200-Memcache.Put-chunks`, but multiple components use the querier code which ultimately makes this call (`ingester` and `ruler`, for example). With this change, all entries in the panel will be prefixed with the component name.
N/A
**Checklist**
=> Group memcached queries by container

pkg/storage/chunk/schema.go, pkg/storage/chunk/storage/bytes.go, pkg/storage/chunk/storage/caching_fixtures.go, pkg/storage/chunk/storage/caching_index_client.go, pkg/storage/chunk/storage/caching_index_client_test.go, pkg/storage/chunk/storage/factory.go, pkg/storage/chunk/storage/index_client_test.go
We drop some query parameters from the queries to cache all possible rows matching the HashKey, which includes just the metric name + label name for labels index entries and the metric name + series ids for chunk ids. This PR aims at the labels index query part.
In simple terms, when a query comes in for label {foo="bar"}, the caching index client will fetch and store all the index entries for label foo irrespective of the expected value from the query. While this helps with other queries looking for other label values for `foo', it is still a lot of waste of resources if the label name is present in thousands of series, and users would not search for all of them.
I have changed the code to not drop the search parameters for labels queries and keep …
=> Optimize index queries and caching

.drone/drone.yml
It doesn't seem like https://github.com/grafana/loki/pull/4069 worked out; re-ran `drone sign` and committed the result.
=> Updating drone signature

clients/pkg/promtail/targets/journal/journaltarget.go
While following the systemd journal, if an `EBADMSG` error is thrown (or indeed anything else besides for `sdjournal.ErrExpired` or `io.EOF`), then we will enter into a tight loop and consume all available CPU.
This PR handles `EBADMSG` which can occur in a corrupt journal file, and additionally adds a 100ms sleep in the loop to prevent runaway CPU usage.
Partially addresses #4053
**Checklist**
=> Promtail: handling tight loop in journal follow logic

pkg/storage/batch_test.go, pkg/storage/chunk/chunk.go, pkg/storage/chunk/chunk_test.go
```
~/go/src/github.com/grafana/loki main* ⇣
❯ benchcmp  before.txt after.txt2
benchmark                         old ns/op     new ns/op     delta
Benchmark_ParseExternalKey-16     569           415           -27.03%
benchmark                         old allocs     new allocs     delta
Benchmark_ParseExternalKey-16     2              0              -100.00%
benchmark                         old bytes     new bytes     delta
Benchmark_ParseExternalKey-16     96            0             -100.00%
```
This is a very hot function in Loki being used for every chunk reference we get from the index.
=> Make `ParseExternalKey` from the `chunk` package allocations free.

pkg/ruler/appender.go, pkg/ruler/remote_write.go
Adds a `group_key` label to the `recording_rules_samples_queue_capacity` metric, in order to make queries simpler.
Attempting to determine what the total used capacity of a queue is difficult if we can't match the `recording_rules_samples_queued_current` and `recording_rules_samples_queue_capacity` metrics on tenant and rule group key. We need to start doing ugly things like `ignoring (group_key)` to get around this currently.
N/A
Initially this wasn't added because queue capacity (`ruler_remote_write_queue_capacity`) can only be set on a per-tenant basis. The ruler maintains a separate queue for each rule group, and each rule group inherits this capacity.
**Checklist**
=> Ruler: Adding group_key label to recording_rules_samples_queue_capacity metric

pkg/storage/chunk/aws/dynamodb_storage_client.go, pkg/storage/chunk/aws/s3_storage_client.go, pkg/storage/chunk/azure/blob_storage_client.go, pkg/storage/chunk/cassandra/storage_client.go, pkg/storage/chunk/chunk_store.go, pkg/storage/chunk/chunk_store_utils.go, pkg/storage/chunk/gcp/bigtable_object_client.go, pkg/storage/chunk/gcp/gcs_object_client.go, pkg/storage/chunk/grpc/storage_client.go, pkg/storage/chunk/inmemory_storage_client.go, pkg/storage/chunk/local/fs_object_client.go, pkg/storage/chunk/objectclient/client.go, pkg/storage/chunk/openstack/swift_object_client.go, pkg/storage/chunk/purger/purger.go, pkg/storage/chunk/storage/metrics.go, pkg/storage/chunk/storage_client.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_table.go, pkg/storage/stores/shipper/compactor/retention/retention.go, pkg/storage/stores/shipper/compactor/retention/retention_test.go, pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/util/object_client.go, pkg/storage/util_test.go
We return `chunk.ErrStorageObjectNotFound` when `GetObject` or `DeleteObject` fails due to a missing object. `GetObject` returns a reader of the object and if the file gets deleted in the middle of the download operation, it can cause the download to fail with an error set by the underlying storage client which would be different than `chunk.ErrStorageObjectNotFound`.
This PR adds a new method `IsObjectNotFoundErr` to `ObjectClient` interface and `IsChunkNotFoundErr` to `Client` interface to help consumers find if the error was due to a missing object. The former is used for raw object operations while the latter is used for treating objects as chunks in the storage.
=> add a method to check whether error is due to a missing object in storage while reading or deleting the object

pkg/ingester/index/index.go, pkg/ingester/index/index_test.go
Currently shards computation are not correctly aligned between ingester and storage causing bad metric results.
- Fixed the hash calculation which was missing the metric name `logs`.
- Revert some changes from https://github.com/grafana/loki/pull/3852/commits/5f0e2453fe0e5c922e6e152bb0d1e7b063c92065 which was not keeping the alignement of shards.
For example if the shard is 9 of 16 total, then it should also be 9 and 25 of 32. The previous commit was trying to use 10 and 11 of 32.
/cc @owen-d @sandeepsukhani 
=> Fixes unaligned shards between ingesters and storage.

pkg/querier/queryrange/codec.go, pkg/querier/queryrange/downstreamer.go, pkg/querier/queryrange/prometheus.go, pkg/querier/queryrange/prometheus_test.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/stats.go
This is a set of fixes for instant queries:
- correctly propagate statistics.
- correctly convert sampleStream to vector.
- correctly marshal to json.
- correctly encode the time for the request.
=> Fixes instant queries in the frontend.

docs/sources/installation/tanka.md
Right now these install docs assume an old version of Tanka and make you do some extra steps. With recent versions of Tanka, this is no longer necessary. 
Also made some changes to make it a bit easier for a user to follow what they have to modify in the `environments/loki/main.jsonnet` file. 
None. 
This docs page is rewritten in such a way that it assumes the user will use the boltdb-shipper. as this is the new standard going forward, this seems fine. 
In the override for the schema config, I tell the user to replace the "from" variable with the current date. I'm not sure if that is correct. (When I tested myself, I chose an arbitrary date that was equal to the first day of the …
=> Update the docs to install Loki with Tanka

docs/sources/configuration/_index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/limits.go, pkg/distributor/validator.go, pkg/validation/limits.go, pkg/validation/limits_test.go, pkg/validation/validate.go
- When log lines are longer than maxLineSize, truncate them to maxLineSize rather than dropping them
The issue calls out adding a `_truncated_` label but I didn't do that because there doesn't seem to be a way to do it without introducing unexpected behavior: 
- If added before validation, the stream might be dropped for exceeding the max number of label names.
- If added after validation, the number of streams might be doubled for reasons that might surprise an operator. 
This change also doesn't include appending `... truncated 12345 bytes` because it has the potential to introduce strange behavior around `max_line_length`
Fixes #3747
**Checklist**
=> Distributor: Truncate rather than drop log lines

pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/expiration_test.go
We optimise applying retention by skipping tables that would not have any out of retention data. The code was incorrectly skipping some tables because it was using the highest retention period as a reference instead of the smallest. All the tables older than or overlapping with the smallest retention period would possibly have some data to be deleted. This PR fixes the code.
**Checklist**
=> fix finding tables which would have out of retention data

pkg/ingester/stream.go, pkg/ingester/stream_test.go
This fixes a bug where ingester stream iterators assumed their chunks maintained increasing inter chunk order. This is not guaranteed now that unordered writes are available.
This is a followup after closing https://github.com/grafana/loki/pull/4101. Here, we take a much simpler route, adding inter-chunk ordering calculations while iterating through chunks, but importantly do not incur additional slice allocations doing so.
I spent some time attempting to build centralized logic for these calculations in order to reuse it in a few places with duplicate logic, but I was unable to find a working solution that didn't incur slice allocations which I want to avoid on this code path. I do, however, want to revisit these issues post the introduction of generics in go (or if someone sees …
=> Stream iterators account for unordered data

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/ingester/index/index.go, pkg/ingester/index/index_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/loki/config_test.go, pkg/loki/loki.go
This PR introduces `ingester.index-shards` as a configuration parameter. This is necessary now that we have support for ingester query sharding and period configurations within the schema config may choose their own shard factors. Loki requires that these are compatible. More explicitly, the `ingester.index-shards` MUST be evenly divisible by ALL schema shard factors or sharded queries to the ingester will fail.
=> ingester.index-shards config

docs/sources/configuration/examples.md
using the `168h` in the example causes the below error:
```
level=error ts=2021-08-09T09:44:51.785369434Z caller=main.go:86 msg="validating config" err="invalid schema config: boltdb-shipper works best with 24h periodic index config. Either add a new config with future date set to 24h to retain the existing index or change the existing config to use 24h period"
```
=> update boltdb-shipper index period

README.md
This PR changes the way the docs are described in links such that the README does not need to be updated as each new release is made.
=> Update Loki README with better links and descriptions

docs/sources/clients/fluentd/_index.md
Updated fluent-plugin-loki documentation links to point to new location. Original reference docs were moved in this [commit](https://github.com/grafana/loki/commit/6e67d1ea5d128c15e6b4c69895057891c1d1a8f9#diff-04dc5b2136328a0dcb189df97734c7c72e5e1227fa0c03469a6ce608f32f1b66).
Update to fluent-plugin-loki documented.
**Checklist**
=> Update fluent-plugin-loki documentation URLs

docs/sources/clients/promtail/stages/multiline.md
My addition of some newlines means that no horizontal scroll bar will exist/be needed for some of the examples. That makes the examples more readable.
=> Docs: Fix typos and grammar. Inject newlines for readability.

docs/sources/operations/ordering.md
ref https://github.com/grafana/loki/issues/1544
=> Initial out of order docs

Makefile
When the build package was refactored the Makefile was not updated, this PR fixes this.
Fixes #4115
Fixes #4133
=> Build: Fix build version info

docs/sources/clients/fluentd/_index.md
- Adds corrections from closed PR https://github.com/grafana/loki/pull/3880
=> Docs: fluentd client phrasing and formatting

production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/loki.libsonnet, production/ksonnet/loki/query-scheduler.libsonnet
This PR:
1) Uses a headless svc config with `PublishNotReadyAddresses` for the scheduler to bootstrap scheduler<>worker connections.
2) Improves some configuration handling, notably component addresses & tenant queues between configurations with/without the scheduler enabled.
3) use `frontend_worker.match_max_concurrent` rather than calculate the worker parallelism in jsonnet.
=> updates scheduler libsonnet

pkg/iter/entry_iterator.go, pkg/iter/entry_iterator_test.go, pkg/iter/sample_iterator.go, pkg/iter/sample_iterator_test.go
This PR safely closes the _current_ iterator in the `nonOverlapping` variants, which was incorrectly ignored previously.
Thanks to @alanhe's reporting in https://github.com/grafana/loki/issues/4156, I was able to repro this easily.
Closes #4156
=> safely close nonOverlapping iterators

production/ksonnet/enterprise-logs/.gitignore, production/ksonnet/enterprise-logs/Makefile, production/ksonnet/enterprise-logs/eval.jsonnet, production/ksonnet/enterprise-logs/jsonnetfile.json, production/ksonnet/enterprise-logs/jsonnetfile.lock.json, production/ksonnet/enterprise-logs/main.libsonnet, production/ksonnet/enterprise-logs/scripts/k3d-cluster, production/ksonnet/enterprise-logs/test/eval.jsonnet, production/ksonnet/enterprise-logs/test/jsonnetfile.json, production/ksonnet/enterprise-logs/test/jsonnetfile.jsonnet, production/ksonnet/enterprise-logs/test/jsonnetfile.lock.json, production/ksonnet/enterprise-logs/variables.mk
This PR adds a Grafana Enterprise Logs Jsonnet library that extends the OSS Loki library. 
- This PR includes rudimentary testing that can be performed with `$ make test`, this essentially only proves that Tanka is able to evaluate the Jsonnet.
- This has been evaluated against a working dev cluster and produces minimal (and desirable) diffs over what is currently deployed internally.
- Documentation is separate and will be released in the [GEL setup docs](https://grafana.com/docs/enterprise-logs/latest/setup/)
- There are some TODOs noted at the top of the library file. These represent task that I would ideally like to contribute to the OSS Loki chart and inherit.
**Checklist**
=> Jsonnet: Add Grafana Enterprise Logs library

cmd/loki-canary/main.go, pkg/canary/reader/reader.go
Add support for specifying tenant id for canaries which would be used for querying loki with `X-Scope-OrgID` header.
=> allow setting tenant id for querying logs from loki

production/ksonnet/loki/config.libsonnet
This propagates some configs originally from Cortex, which helps encourage connection reuse.
=> fine tune grpc configs jsonnet

pkg/loki/loki.go, pkg/loki/modules.go
I found this after debugging the scheduler<>querier connections and noticed we were failing grpc health checks. This caused deletion/recreation of the clients very often and resulted in some nasty internal errors. Here I'm globally instantiating it, similar to Cortex. This works well as we've added additional grpc connection points.
=> initiate grpc health check always

pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/iterator.go, pkg/storage/stores/shipper/compactor/retention/iterator_test.go, pkg/storage/stores/shipper/compactor/retention/retention.go, pkg/storage/stores/shipper/compactor/retention/retention_test.go, pkg/storage/stores/shipper/compactor/retention/series.go, pkg/storage/stores/shipper/compactor/retention/series_test.go, pkg/storage/stores/shipper/compactor/retention/util.go, pkg/storage/stores/shipper/compactor/retention/util_test.go
It contains the following changes to speed up the mark phase of retention:
1. We delete a chunk only when the whole chunk is out of retention. If a chunk spans multiple tables, we will retain its entry in all those tables until the whole chunk expires, even if the table is not expected to have it based on retention config. This PR changes the approach to drop the chunk index entry early by checking the interval's end time for which a table is expected to have chunks indexed.
2. We clean up the series by iterating over the index entries to find which ones should be deleted. Because of the index format, we need to go through all the label entries(including labels for unrelated series) for the user. This PR changes the code to build the index keys …
=> Retention speedup

docs/sources/storage/_index.md
=> Docs: example about using azure storage account as storage

pkg/ruler/appender.go, pkg/ruler/compat.go, pkg/ruler/compat_test.go, pkg/ruler/memstore.go
This PR adds more meaningful logs when recording rules are present, but remote-write is either disabled or misconfigured.
N/A
The previous log messages looked like this:
```
... msg="Rule evaluation result discarded" err=unimplemented sample="{__name__=\"test\"} => 2 @[1628673147231]"
```
And now look like this:
```
... msg="Rule evaluation result discarded" err="remote-write disabled" sample="{__name__=\"test\"} => 2 @[1628673202231]"
```
**Checklist**
=> Ruler: write meaningful logs when remote-write is disabled or is misconfigured

pkg/ingester/checkpoint_test.go, pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/limiter.go, pkg/ingester/stream.go, pkg/ingester/stream_test.go, pkg/validation/limits.go, pkg/validation/validate.go
Adds a limiter to the stream struct.
=> [ingester/stream]: Add a byte stream rate limit.

docs/sources/clients/docker-driver/_index.md
The Docker driver might seem stuck when Loki is not reachable. It might also drop log entries. In this change we describe how to use Promtail instead.
Relates to #2361
**Checklist**
=> Document known Docker driver issues.

cmd/logcli/main.go, docs/sources/getting-started/logcli.md
When using 'logcli query --tail', '--tail' behaves similar to the 'tail'
command, which uses '--follow' flag, if you want to continuously
follow the appended data to the file.
I believe '--follow' flag is more natural for system administrators to
use rather than '--tail' if one wants to "follow" the incoming logs, so
this commit adds one, as an alias for '--tail'.
Fixes #3570
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
**Checklist**
=> cmd/logcli: add --follow flag as an alias for --tail

docs/sources/configuration/_index.md, pkg/storage/chunk/aws/s3_storage_client.go
This option lets users set a custom CA file for connections to S3, in case they
use a local S3 instance with an internal PKI.
Also fix the documentation for `s3.http.insecure-skip-verify`.
**Checklist**
=> pkg/storage/chunk/aws: Add s3.http.ca-file option

pkg/ingester/metrics.go, pkg/ingester/stream.go, pkg/validation/validate.go
As the WAL replays segments on top of checkpoints, it's common to confront duplicate data. This PR adds metrics for how much data is discarded this way during a replay.
=> WAL replay discard metrics

docs/sources/installation/tanka.md
Refers to tank docs section for installation of `jb` instead of providing a cli command that may not work.
fixes #4023 
=> Update tanka installation docs to refer to tanka section about `jb`

docs/sources/clients/promtail/scraping.md
We have two sections on the Kubernetes service discovery in Promtail. This change links from `scraping/#kubernetes-discovery` to `configuration/#kubernetes_sd_config`.
**Checklist**
=> Link Kubernetes service discovery configuration.

pkg/ingester/client/client.go
Loki can be protected by mTLS. However, if you configure grpc_tls_config, internal grpc clients (e.g. distributor/querier to ingester) fails to connect because the client cert option is not supported.
The fix allows it.
Fixes #3252 
This has been tested with the following Loki config.
```
server:
http_listen_port: 13101
grpc_listen_port: 18931
log_level: debug
http_tls_config:
key_file: /path/to/key.pem
cert_file: /path/to/cert.pem
client_ca_file: /path/to/ca.pem
client_auth_type: VerifyClientCertIfGiven
grpc_tls_config:
key_file: /path/to/key.pem
cert_file: /path/to/cert.pem
client_ca_file: /path/to/ca.pem
client_auth_type: VerifyClientCertIfGiven
ingester_client: …
```
=> Authc/z: Enable grpc_client_config to allow mTLS

docs/sources/clients/docker-driver/configuration.md
There is a typo on loki-external-labels for [docker client labels documentation](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/), which give this error : 
```
ERROR: for xx  Cannot start service vigil: failed to initialize logging driver: error creating logger: error creating loki logger: loki: wrong log-opt: 'loki-external-lables' - 
```
N/A
**Checklist**
=> doc: fix typo on loki-external-labels for docker client labels

clients/pkg/promtail/targets/gcplog/metrics.go, clients/pkg/promtail/targets/gcplog/target.go
Also fix the Ready() method of target
- gcplog's `ready()` method always return (just like every other scrape target). Rationale is gcplog scraping shouldn't stop because of some some transient timeout errors.
- This transient failure can cause promtail readyness probe to fail which may prevent pod from starting.
- We have metrics now to track if scraping failed (`gcplog_target_last_success_scrape`).
Fixes NA
**Checklist**
=> Add metrics for gcplog scrape.

pkg/loki/loki.go, pkg/loki/modules.go, pkg/loki/runtime_config.go, pkg/loki/runtime_config_test.go, vendor/github.com/grafana/dskit/runtimeconfig/manager.go, vendor/modules.txt
Use the `runtimeconfig` package from dskit.
**Checklist**
=> Chore: Use runtimeconfig from dskit

docs/sources/configuration/_index.md
Revises wording of the configuration knob definition from https://github.com/grafana/loki/pull/4244.
=> Docs: revise max_query_lookback knob definition

clients/pkg/logentry/stages/drop.go, docs/sources/clients/promtail/stages/drop.md, docs/sources/clients/promtail/stages/match.md
When dropping a log line we are not currently incrementing the associated `dropStage.dropCount` metric.
Fixes https://github.com/grafana/loki/issues/4158
N/A
**Checklist**
- [✅] Documentation added
=>     Add missing `Inc()` to correctly increment the `dropStage.dropCount` metric on valid dropped log line; update related docs

pkg/storage/store.go
As the title suggests, this PR register a (deprecated) configuration option as CLI argument.
This will help towards auto-generating reference documentation from source.
**Checklist**
=> cli: Register configuration option `store.max-look-back-period` as CLI argument

production/ksonnet/enterprise-logs/main.libsonnet
The argument name for the license path has changed. It used to be `bootstrap.license.path` but has been updated to `license.path` (per the GEM documentation, wherein GEL likely inherits the same code). Without this change, the Jsonnet will deploy a GEL cluster that fails to find the license, causing the admin-api to fail to start and the gateway to also be unlicensed.
Fixes #4258 
**Checklist**
=> Jsonnet: Update license path argument name

pkg/ingester/flush.go, pkg/ingester/instance.go, pkg/ingester/recovery.go
Refactors stream removal into it's own function and removes empty streams after WAL replay completes in order to not interfere with tenant stream limits during rollout.
=> remove empty streams after wal replay

pkg/util/flagext/bytesize.go, pkg/util/flagext/bytesize_test.go, pkg/validation/limits_test.go
Adds custom unmarshalJSON for bytesize type.
Fixes NA. Just observation on production
**Checklist**
=> Add custom UnmarshalJSON for bytesize type

docs/sources/api/_index.md
In [documentation](https://grafana.com/docs/loki/latest/api/#series), we say that the url param for `/series` endpoint should be `match[]`, but in example we use just `match`. Although `match` works as well, we should probably use the same param.
=> Update example for /series endpoint in _index.md

production/README.md
**What this PR does / why we need it**: 
The current link to Promtail installation documentation in the file leads to 404 error. I observed that the `../docs/clients/` folder was refactored into `../docs/sources/clients` at same time in past. However, the `loki/docs/sources/clients/promtail/installation.md` file is not very convenient if we talk about UX. So, I've replaced the wrong link with the one to rendered beautiful documentation
=> docs: fix link to Promtail documentation

docs/sources/api/_index.md
The command: curl -G -s "http://localhost:3100/api/prom/query" --data-urlencode '{foo="bar"}' | jq
gives the message: parse error: Invalid numeric literal at line 1, column 6
Instead, the command: curl -G -s  "http://localhost:3100/api/prom/query" --data-urlencode 'query={foo="bar"}' | jq, works
**Checklist**
=> Correcting documentation example for `/api/prom/query`

pkg/logcli/query/query.go
Debugging local queries is life saving, but currently doesn't work for boltdb.
This fixes it. Do note that downloading index can be slow for the first time.
=> Allow to run local boltdb queries with logcli.

pkg/iter/cache.go, pkg/iter/cache_test.go, pkg/storage/lazy_chunk.go
Because chunks can overlap and that can causes multiple processing of the same chunk within batches, we decided to cache the
evaluation of it.
However there was a bug here causing incorrect query result, specially for metric queries. The bug would occur when we would only partially consume a block (overlapping block between multiple batches) and then try to replay it. 
In which case it wouldn't actually replay it but keep consuming the underlaying iterator.
I guess I assumed that blocks would only be fully consumed, but that's not correct for metric queries (forward). I added new tests that were failing with the previous code to ensure we're good now.
This took us 2 days to figure out, thank @dannykopping  for helping along.
=> Fixes a bug in the block cache code.

clients/pkg/promtail/server/ui/assets_generate.go, clients/pkg/promtail/server/ui/ui.go, clients/pkg/promtail/targets/journal/journaltarget.go, clients/pkg/promtail/targets/journal/journaltarget_test.go, clients/pkg/promtail/targets/journal/journaltargetmanager.go, clients/pkg/promtail/targets/journal/journaltargetmanager_linux.go, clients/pkg/promtail/targets/windows/bookmark.go, clients/pkg/promtail/targets/windows/format.go, clients/pkg/promtail/targets/windows/target.go, clients/pkg/promtail/targets/windows/target_test.go, clients/pkg/promtail/targets/windows/targetmanager.go, clients/pkg/promtail/targets/windows/targetmanager_windows.go, clients/pkg/promtail/targets/windows/win_eventlog/event.go, clients/pkg/promtail/targets/windows/win_eventlog/syscall_windows.go, clients/pkg/promtail/targets/windows/win_eventlog/util.go, clients/pkg/promtail/targets/windows/win_eventlog/util_test.go, clients/pkg/promtail/targets/windows/win_eventlog/win_eventlog.go, clients/pkg/promtail/targets/windows/win_eventlog/win_eventlog_notwindows.go, clients/pkg/promtail/targets/windows/win_eventlog/win_eventlog_test.go, clients/pkg/promtail/targets/windows/win_eventlog/zsyscall_windows.go, pkg/logql/fuzz.go, pkg/logql/fuzz_test.go
Format Go files with Go 1.17, which has a new build tag directive format. No biggie, but whenever I change these files `goimports` changes them to add the new build tag directive. If we reformat now, this problem goes away :)
The changes were made through `make format`.
**Checklist**
=> Chore: Reformat Go files

pkg/logql/log/pattern/ast.go, pkg/logql/log/pattern/pattern_test.go
We should never have 2 consecutive capture, since when we do we can't figure which data goes where.
The previous validation was validating two nodes at the time and moving to the next two nodes so in the end it wasn't validating properly.
I've also took the opportunity to improve the error message to make it easier to spot the problem.
:facepalm:
=> Fixes the pattern parser validation.

docs/sources/operations/storage/logs-deletion.md
What: Update the `cURL` command example to URL encode
the `match` query param
Why: The current `cURL` command throws this error:
```
$ curl -X POST \                                                                                                                                        
'http://localhost:3100/loki/api/admin/delete?match[]={foo="bar"}&start=1591616227&end=1591619692' \                                                    
-H 'x-scope-orgid: fake'
1:4: parse error: unexpected "="
```
**Checklist**
=> docs:  (logs-deletion.md) URL Encode curl command

pkg/logql/log/pattern/ast.go, pkg/logql/log/pattern/pattern_test.go
https://github.com/grafana/loki/pull/4308
=> Hotfix #4308 into k62

docs/sources/configuration/_index.md
The sets of configuration knobs/definitions are lengthy enough that when the horizontal scroll bar must be used, it is difficult to see the knob that needed the horizontal scrolling.  This PR injects newlines so that there are no horizontal scroll bars on the page.
=> Docs: inject newlines for configuration section readability

go.mod, pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/worker_service.go, pkg/querier/worker_service_test.go, vendor/modules.txt
This PR allows both the Query and QueryFrontend targets to be enabled in the same loki process, as well as adding QueryFrontend to the "all" target. It follows a similar pattern as was done in cortex, where a query worker service is enabled with an internal router to handle query endpoints. Those endpoints are either a) exposed externally if the querier is running standalone, b) used internally by the query worker if the querier is running alongside the query frontend (since the query fronted will register those same routes externally).
Fixes #4218 
**Checklist**
=> Feature: allow querier and query frontend targets to run on same process

pkg/loki/modules.go
Signed-off-by: Trevor Whitney <trevorjwhitney@gmail.com>
When running loki with target `--target=distributor,ingester` it fails with the error `FATAL: 2021/09/17 18:48:10 [core] grpc: Server.RegisterService found duplicate service registration for "logproto.Pusher"`. This is because the guard against registering the Pusher service in the `initDistributor` code is currently only guarding against the `All` target. With our work on the "single scalable deployment", we plan on having a write path where both the distributor and ingester are enabled. This PR allows both targets to be enabled.
**Checklist**
=> allow ingester and distributor to run on same instance

.golangci.yml, Makefile, clients/cmd/docker-driver/loki.go, clients/pkg/promtail/targets/file/filetarget.go, clients/pkg/promtail/targets/file/filetargetmanager.go, clients/pkg/promtail/targets/gcplog/formatter.go, clients/pkg/promtail/targets/gcplog/target.go, clients/pkg/promtail/targets/gcplog/targetmanager.go, clients/pkg/promtail/targets/journal/journaltargetmanager.go, clients/pkg/promtail/targets/stdin/stdin_target_manager.go, clients/pkg/promtail/targets/syslog/syslogtarget.go, clients/pkg/promtail/targets/syslog/syslogtargetmanager.go, clients/pkg/promtail/targets/target/target.go, pkg/querier/queryrange/split_by_interval.go, pkg/storage/chunk/aws/dynamodb_table_client.go, pkg/storage/chunk/chunk_store.go, pkg/storage/chunk/gcp/gcs_object_client.go, pkg/storage/chunk/purger/purger.go, pkg/storage/stores/shipper/compactor/retention/iterator_test.go, pkg/storage/stores/shipper/compactor/retention/marker.go
- replaced deprecated `golint` with `[revive](https://github.com/mgechev/revive#installation)` (https://github.com/golangci/golangci-lint/pull/1965)
- removed `interfacer` (https://github.com/golangci/golangci-lint/pull/1755)
- replaced deprecated `megacheck` with `staticcheck` (https://pkg.go.dev/github.com/aspenteam/go-tools/cmd/megacheck)
Partially addresses #1002
I did not include the `prealloc` linter as suggested by Marco yet as I didn't want to complicate this PR with the requisite changes it would introduce to get CI passing. This should be done in a subsequent PR.
I did implement changes to make `revive` pass, as it's a little more strict that `golint` and the …
=> CI: Fixing linter deprecations

pkg/loki/runtime_config.go
Fixes a panic which occurs when an overrides file has an entry defined for a tenant without any limits:
```yaml
overrides:
"54321":
max_query_series: 10000
"12345":
```
`12345` in the example above will be unmarshaled to a `nil` value, and cause a panic.
N/A
**Checklist**
=> Runtime config: do not validate nil limits

pkg/ruler/compat.go, pkg/ruler/registry.go, pkg/ruler/registry_test.go, pkg/ruler/util/relabel.go, pkg/validation/limits.go
This PR introduces a custom struct that eases json/yaml unmarshaling of complex relabel.Config struct.
Since we use `json` to marshal our per-tenant limits in `entitlements`, and [prometheus doesn't have a custom JSON unmarshaler](https://github.com/prometheus/prometheus/blob/main/pkg/relabel/relabel.go#L94), we need to introduce our own.
I also opted to only accept primitive types and push the responsibility of using the correct types down to the `createRelabelConfigs` function.
N/A
We do the YAML marshal/unmarshal dance because prometheus only validates the configuration in its …
=> Ruler: improve control over marshaling relabel.Config

pkg/validation/limits.go
Followup to https://github.com/grafana/loki/pull/4236
=> removes deprecated duplicate per stream rate limit fields

clients/pkg/promtail/scrapeconfig/scrapeconfig.go, clients/pkg/promtail/targets/syslog/syslogtarget.go, clients/pkg/promtail/targets/syslog/syslogtarget_test.go, docs/sources/clients/promtail/configuration.md
Add support for TLS and mTLS in promtail's syslog receiver.
Fixes #3898 
Go is not my main language (and I don’t really like it) so there might be some coding-style issue or some bad patterns.
I successfully tested this change using rsyslog and I got the following results:
* TLS disabled on both sides: **works as before**
* TLS enabled on both sides: **works as before (with TCP sessions being encrypted)**
* TLS enabled but client sends plain text messages: fails with `level=warn ts=2021-06-25T17:34:09.985034229Z caller=syslogtarget.go:207 msg="error initializing syslog stream" err="tls: first record does not look like a TLS handshake"`
* TLS enabled on both sides, with client …
=> promtail: add support for TLS/mTLS in syslog receiver

pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/worker_service.go
In #4301 we refactored the Querier but removed the recovery HTTP middleware from the Querier when not running in `standalone` mode.
Recently in production we observed an issue (fixed in #4308) where panics occurred in both the Querier and Ingester. The Queriers were able to recover but not the Ingesters.
Fixes #4325.
N/A
**Checklist**
=> Add recovery middleware to Ingester; re-add recovery middleware to Querier when not running in standalone mode

pkg/ingester/recovery.go, pkg/ingester/stream.go
"loki_ingester_memory_chunks" isn't incremented when WAL recovery is executed so I've fixed.
Fixes #4004
=> Add count to 'loki_ingester_memory_chunks' when recovery from wal

pkg/ingester/ingester.go
Signed-off-by: Trevor Whitney <trevorjwhitney@gmail.com>
Set the default value of `-ingester.chunk-target-size` to ~1MB~ 1.5MB.
Originally had this at 1MB, after talking to @slim-bean decided 1.5MB. Whatever the value is, 0 is not a good default, forcing a user to always configure this.
=> default chunk target size to ~1MB~ 1.5MB

pkg/ingester/stream.go, pkg/ingester/stream_test.go, pkg/validation/validate.go
Logs the rate limit, stream labels, and bytes for that push in the error/error message.
=> Improve error message for stream rate limit.

production/loki-mixin/dashboards/dashboard-utils.libsonnet, production/loki-mixin/dashboards/loki-chunks.libsonnet, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-retention.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet
Fix to retention dashboard (seems like query panel without a `panel(...)` line to set the name throws an error, plus add links + selector copying dropdown to other dashboards (top right of dashboard, links to other dashboards and copies over cluster selectors, etc.).
=> Minor dashboard fixes

pkg/querier/queryrange/downstreamer.go, pkg/querier/queryrange/downstreamer_test.go
We were not also checking the context to see if it was canceled while waiting for goroutines to return with query results leading to a leak of goroutines.
=> Loki: Bug: frontend waiting on results which would never come

docs/sources/installation/helm.md
**What this PR does / why we need it**: fixes link to "syslog-reciever" and "systemd-journal" config docs
**Which issue(s) this PR fixes**: -
**Special notes for your reviewer**: -
**Checklist**
=> docs: fix promtail docs links in loki installation page

docs/sources/clients/promtail/configuration.md
Language added in in https://github.com/grafana/loki/pull/4507 used the word "explode." While accurate, I think it is more appropriate to use phrasing that doesn't trigger images of death or destruction. This PR revises that word usage, and simplifies the phrasing.
=> Docs: revise incendiary language added in PR 4507

CHANGELOG.md, docs/sources/logql/template_functions.md, pkg/logql/log/fmt.go, pkg/logql/log/fmt_test.go
Introduce date time sprig template functions in logql label/line formatter, it allows us to get current time, format date time and parse date time with specified layout.
Fixes https://github.com/grafana/loki/issues/4511, we will be able to filter test jobs which create time is 1 day before as the following:
```
{job="test"} | label_format nowEpoch=`{{(unixEpoch now)}}`,createDateEpoch=`{{unixEpoch (toDate "2006-01-02" .createDate)}}` | label_format dateTimeDiff="{{sub .nowEpoch .createDateEpoch}}" | dateTimeDiff > 86400
```
N/A
**Checklist**
=> add date time sprig template functions in logql label/line formatter

pkg/logql/expr.y, pkg/logql/lex.go, pkg/logql/lex_test.go, pkg/logql/parser_test.go
Fix `ip` matcher lexer to differentiate filter from identifier
Fixes: #4571 
**Checklist**
=> Fix `ip` matcher lexer to differentiate filter from identifier

pkg/storage/stores/shipper/compactor/compactor.go
`ring.WriteNoExtend` won't keep iterating the ring until an active node is picked, so I think we should use `ring.Write` here instead. This is the same idea from https://github.com/grafana/loki/pull/4607
=> uses ring.Write instead of ring.WriteNoExtend for compactor ring checks

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/util/ring.go
This PR attempts to improve a race when adding/removing instances into the scheduler ring where messages could end up stuck in a schedulers queue with no queriers coming back to process them.
Currently when an elected scheduler is no longer "elected" everyone finds out about this through the ring, but the schedulers themselves do nothing and technically stay active, the frontend and queriers poll the ring and when they find out about the scheduler change, disconnect from the old and connect to the new.
The distributed nature of this creates the possibility that all the queriers find out about a scheduler change and disconnect from the scheduler while the frontend still stays connected. The frontend could then be stuck waiting for inflight queries to …
=> Loki: query scheduler should send shutdown to frontends when ReplicationSet changes

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/upgrading/_index.md, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go
This changes the default value for the ingester lifecycler's final sleep from 30s to 0s. With the default value, loki appears to hang when shutting down. This feature is designed to allow one last metric scrape to occur before shutdown, but as that is heavily dependent on scrape intervals in various environments, this default value is probably not sensible for everyone. Furthermore, for users who don't even know this value exists, it may be surprising to them why Loki "hangs" on shut-down.
`0s` seems like a better default, as it won't delay the Loki shutdown, and the property is still available for users to set per their environment / scrape interval.
Fixes #4605 
**Checklist**
=> default ingester final sleep to 0 unless otherwise specified

clients/pkg/promtail/targets/gcplog/formatter.go, clients/pkg/promtail/targets/gcplog/formatter_test.go, docs/sources/clients/promtail/scraping.md, go.mod
=> promtail: no need for GCP promtail_instance label now that loki supports out-of-order writes

production/ksonnet/loki/config.libsonnet
Since the WAL is now enabled by default and incompatible with chunk
transfer, the latter needs to be disabled (setting to `0`).
The default of `max_transfer_retries` is `0` and therefore the setting
can be removed.
=> Disable chunk transfers in jsonnet lib

pkg/loki/modules.go
The ring page offers the ability to "forget" instances of the ring and
this is implemented by a HTTP `form` element, which does a `POST`
request on itself.
**Checklist**
=> Allow HTTP POST requests on ring pages

CHANGELOG.md, docs/sources/upgrading/_index.md, production/ksonnet/loki/config.libsonnet
Followup to https://github.com/grafana/loki/pull/4624 now that the wal is an enabled configuration by default.
=> Default wal to enabled in jsonnet lib

docs/sources/operations/storage/boltdb-shipper.md
Attempts to rectify a confusing error message.
=> index-gw sts doc fix. closes #4583

CHANGELOG.md, docs/sources/upgrading/_index.md
Add changelog and upgrade guide for #4556
Fixes #NA
**Checklist**
=> Add changelog and upgrade guide for #4556

pkg/loki/config_wrapper.go
I can't see this being a reasonable configuration people would use, but when the scheduler is enabled `(all, read, scheduler)` targets, avoid using the scheduler ring when a downstream address is present in the frontend config, which would avoid any schedulers anyway.
=> dont try to use the scheduler ring when a downstream url is configured

clients/pkg/promtail/targets/file/filetarget.go, clients/pkg/promtail/targets/file/filetargetmanager.go
resolve issue with promtail not scraping target if only path changed in a simpler way that dont need mutex to sync threads
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
Resolves an issue in a better way, that don't require sharing variables between theads that would require a mutex to synchronize goroutines.
Fixes #4581 #4460
**Checklist**
=> [Promtail] resolve issue with promtail not scraping target if only path changed in a simpler way that dont need mutex to sync threads

CHANGELOG.md, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/expiration_test.go, pkg/storage/stores/shipper/compactor/retention/retention.go, pkg/storage/stores/shipper/compactor/retention/retention_test.go, pkg/storage/stores/shipper/compactor/table.go, pkg/storage/stores/shipper/compactor/table_test.go
It includes the following two changes:
1. We check for whether the table would have chunks requested for deletion based on the delete request interval and the interval for which the table is expected to hold data or get queries, [calculated using the table number](https://github.com/grafana/loki/blob/29b07d190de2edab4fc03333e3e224d824b5a677/pkg/storage/stores/shipper/compactor/retention/util.go#L45). The problem here though is a chunk could overlap multiple tables so if a delete request is deleting the chunk for just one of the days, the index entry would stay untouched for the days for which the chunk has not been requested for deletion. To avoid this problem I am making compactor to go through all the index tables since it is hard to know how many …
=> Logs deletion fixes

CHANGELOG.md, docs/sources/upgrading/_index.md, pkg/distributor/distributor.go, pkg/loki/loki_test.go
- Reverts [PR 4440](https://github.com/grafana/loki/pull/4440/files), which modified the distributor ring to `inmemory` (instead of consul). This is inconsistent with other rings default behavior and is also not retrocompatible with previous versions.
- That change was required at that time because, by changing the default rate limiting to `global`, a ring was necessary, and, since by default the ring KV was `consul`, the project couldn't run with the default configs. That's not the case anymore: right now we are defaulting to reusing the ingester config, which users already have properly configured otherwise they wouldn't be able to run the project anyway.
N/A
N/A
**Checklist**
=> Loki: Revert distributor defaulting to `inmemory`

pkg/loki/common/common.go, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go, pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/util/ring_config.go
This work finished what @DylanGuedes started with the common ring config and replaces #4610, which has a much better description.
**Checklist**
=> Add common ring configuration

.circleci/config.yml, .drone/drone.jsonnet, .drone/drone.yml, Makefile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, cmd/logcli/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki/Dockerfile, cmd/querytee/Dockerfile
Hopefully this helps with some flakes in our CI and issues seen locally trying to build Loki.
Instead of relying on the Make semantics of using timestamps to determine if a file should be recompiled just delete all the compiled protos every time.
Removed some dependant targets from the loki and loki canary targets, we don't need to rebuild these files to build Loki. if you are mucking around with protos or yacc files you will likely know you need to build them anyway.
**Checklist**
=> Build: simplify how protos are built

pkg/loki/loki.go
We seem to have introduced a race condition when using memberlist for the compactor ring:
```
│ level=info ts=2021-11-03T23:26:34.317080539Z caller=main.go:94 msg="Starting Loki" version="(version=k70-07ea1ed, branch=k70, revision=07ea1ed99)"          ││ level=info ts=2021-11-03T23:26:34.317342925Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"                         ││ panic: runtime error: invalid memory address or nil pointer dereference                                                                                     ││ [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xed5498]                                                                                      ││ goroutine 1 [running]: …
```
=> compactor depends on memberlist for memberlist ring option

pkg/storage/chunk/aws/s3_storage_client.go
Not sure if we're missing historical context for any reason why these requests were not instrumented, but while working on an S3 experiment @JordanRushing and I noticed that the s3 client `DeleteObject` requests are not metrics instrumented.
=> Instrument s3 client DeleteObject requests.

.drone/docker-manifest.tmpl, .drone/drone.jsonnet, .drone/drone.yml, Makefile
This isn't a perfect fix, as it will update the `latest` docker tag to any pushed tag, however this felt better than not automating this at all and having to do it manually.
Fixes #4557
**Checklist**
=> Build: Only push latest docker tag on tagged builds (not pushes to main)

pkg/chunkenc/pool_test.go
I thought zstd has a leak for the writer, but it did not.
This also fixes a request from @kavirajk when I added the finalizer on the zstd reader.
=> Add a test to verify goroutine leak in compression pools.

pkg/loki/modules.go
Fix dskit/ring metric with 'cortex_' prefix resultant from dskit/ring migration: https://github.com/grafana/loki/pull/4641
Fixes #
**Checklist**
=> Fix dskit/ring metric with 'cortex_' prefix

docs/sources/upgrading/_index.md
Documents in the upgrading guide the changes and side-effects introduced by [PR 3842](https://github.com/grafana/loki/pull/3842). The point was to especially document why Loki is warning duplicated protos occurrence.
N/A
**Checklist**
=> Docs: Document duplicated protos warning occurence

Makefile, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go, pkg/loki/loki.go, pkg/loki/modules.go, tools/increment_version.sh
This is what I believe to be the quick fix that I want to try to confirm this is the  problem, however we should take a closer look at this to see if there is a better solution.
Fixes #4680
**Checklist**
=> Loki: check new Read target when initializing boltdb-shipper store

pkg/validation/limits.go
This protects against the case where `TenantLimits` can be nil, which I thought was impossible, but upon closer a closer look at [`modules.go`](https://github.com/grafana/loki/blob/main/pkg/loki/modules.go#L145-L157), when there's no load path, it never gets instantiated. I confirmed locally using the config provided in #4684 that it failed before and succeeded after this fix.
Closes #4684
=> overrides checks for nil tenant limits on AllByUserID

clients/pkg/promtail/client/client.go
This was because promtail client was still user the old version.Version which is initialized at run-time via init.
But if we use it also at init time there's no guarantee that the version will be set.
So instead I'm using the original version variable stamped in the binary and not at runtime.
Fixes #4686
=> Fixes Promtail User-Agent.

production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/query-frontend.libsonnet, production/ksonnet/loki/query-scheduler.libsonnet
The ensure we create ports & thus SRV records in k8s with the expected `_grpclb` prefix
=> ensures components with required SRV lookups use the correct port 

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/util_test.go
No major code change except some cleanup.
```
none_524 kB: 3952.20 MB/s
none_262 kB: 3818.19 MB/s
none_262 kB: 3588.39 MB/s
none_524 kB: 3528.82 MB/s
none_66 kB: 3347.10 MB/s
none_66 kB: 3306.29 MB/s
none_524 kB: 3052.64 MB/s
none_262 kB: 2932.31 MB/s
lz4-1M_66 kB: 2567.87 MB/s
lz4_262 kB: 2467.42 MB/s
none_66 kB: 2453.80 MB/s
lz4-256k_524 kB: 2398.77 MB/s
lz4-1M_262 kB: 2295.78 MB/s
lz4-256k_524 kB: 2289.92 MB/s
lz4-256k_262 kB: 2281.90 MB/s
lz4-1M_524 kB: 2213.51 MB/s
lz4-256k_66 kB: 2187.04 MB/s
lz4_524 kB: 2183.28 MB/s
lz4_524 kB: 2177.57 MB/s
lz4-1M_66 kB: 2148.51 MB/s
lz4_66 kB: 2145.61 MB/s
lz4-1M_262 kB: 2120.39 MB/s
sample_none_66 kB: 2104.96 MB/s
lz4-64k_66 kB: 2098.88 MB/s
lz4-64k_524 kB: 2077.25 MB/s
lz4-64k_524 kB: 2073.97 MB/s
lz4-256k_66 kB: 2070.37 MB/s
lz4_262 kB: 2052.62 …
```
=> Improves memchunk benchmark to account for block size.

CHANGELOG.md, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/compactor/metrics.go
When retention is enabled, we apply it with each compaction run. This causes a lot of resources to be wasted in a big Loki cluster which also causes compaction to not be able to keep up. Since applying retention is not as critical as compacting the data for better query performance, the apply retention interval can be set to a higher value than the compaction interval.
To keep it backwards compatible, I have allowed setting the apply retention interval to 0, which is the default. A zero value here means applying retention at the same time as compaction.
When a non-zero value is set, it should be a multiple of compaction interval because we would always apply retention when running compaction which is optimum and …
=> allow applying retention at different interval than compaction with a config

CHANGELOG.md, pkg/storage/stores/shipper/compactor/retention/iterator.go, pkg/storage/stores/shipper/compactor/retention/iterator_test.go, pkg/storage/stores/shipper/compactor/retention/util.go, pkg/storage/stores/shipper/compactor/retention/util_test.go
This PR includes two fixes:
1. Add a metric name if missing in labels used for calculating index entries for the series clean up since it is used while building the series IDs. The test did not catch this because the test data included the metric name label. Without the metric name, wrong series IDs were calculated, which caused labels entries not to get cleaned up.
2. While calculating table interval from table name, we calculate the start time first and then add 24h to it. The problem with this is it would end up covering the start time of next days table. This is fixed by subtracting a millisecond from the end time of the interval after adding 24h to the start time. There was no harm caused by the overlap with the next day, I am just fixing it to …
=> index cleanup fixes while applying retention

pkg/loki/modules.go, pkg/querier/worker_service.go, pkg/querier/worker_service_test.go
Be sure to set MaxConcurrentRequests when initializing the querier.
Fixes #4760
**Checklist**
=> Loki: Set querier worker max concurrent regardless of run configuration.

pkg/ingester/ingester.go
Enrich WAL folder creation error message, by explicitly saying that it failed to create WAL folder and by saying what is the directory that is being used.
- [4704](https://github.com/grafana/loki/issues/4704)
N/A
**Checklist**
=> Enrich WAL folder creation error message

.drone/drone.jsonnet, .drone/drone.yml
Summary:
Currently, all pipelines are run by the `loki-bench` bron scheduler.
However, we only want `benchmark-cron` to run. That is why all other
pipelines need to define their own trigger which defaults to `push` and
`pull_request`.
=> Only run benchmarks on `loki-bench` cron.

production/loki-mixin/dashboards/dashboard-loki-operational.json, production/loki-mixin/dashboards/loki-operational.libsonnet
Uses logfmt in some queries that were just filtering, rearranges a few smaller panels within ingester and querier rows, and adds the missing logs datasource template selector.
=> Minor operational dashboard improvements + fix missing log template selector

CHANGELOG.md, clients/pkg/promtail/targets/kafka/formatter.go, clients/pkg/promtail/targets/kafka/target.go, clients/pkg/promtail/targets/kafka/target_syncer.go, clients/pkg/promtail/targets/kafka/target_test.go, docs/sources/clients/promtail/configuration.md, docs/sources/clients/promtail/scraping.md
Expose Kafka message key in label set and add description into the documents.
Fixes #4728 
**Checklist**
=> Expose Kafka message key in labels

pkg/iter/entry_iterator.go, pkg/iter/entry_iterator_test.go, pkg/iter/sample_iterator.go, pkg/iter/sample_iterator_test.go
Mostly improve allocations but I'm planning to do more using those benchmark.
```
name                   old time/op    new time/op    delta
HeapIterator-16          3.87ms ± 6%    3.41ms ± 1%  -11.92%  (p=0.008 n=5+5)
HeapSampleIterator-16    2.09ms ± 1%    2.09ms ± 1%     ~     (p=0.421 n=5+5)
name                   old alloc/op   new alloc/op   delta
HeapIterator-16          10.5kB ± 0%     8.2kB ± 0%  -21.88%  (p=0.008 n=5+5)
HeapSampleIterator-16    8.40kB ± 0%    6.10kB ± 0%  -27.34%  (p=0.000 n=5+4)
name                   old allocs/op  new allocs/op  delta
HeapIterator-16            12.0 ± 0%       5.0 ± 0%  -58.33%  (p=0.008 n=5+5)
HeapSampleIterator-16      12.0 ± 0%       5.0 ± 0%  -58.33%  (p=0.008 n=5+5)
```
I want to introduce a difference between the need to dedupe vs order …
=> Improve heap iterators.

docs/sources/clients/_index.md
I transferred my package to the [JuliaLogging](https://github.com/JuliaLogging) GitHub organization. The old URL redirects to the new one, but seems best to update it here too.
=> doc: Update URL for LokiLogger.jl (Julia client)

production/loki-mixin/dashboards/dashboard-utils.libsonnet, production/loki-mixin/dashboards/loki-chunks.libsonnet, production/loki-mixin/dashboards/loki-deletion.libsonnet, production/loki-mixin/dashboards/loki-logs.libsonnet, production/loki-mixin/dashboards/loki-operational.libsonnet, production/loki-mixin/dashboards/loki-reads-resources.libsonnet, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-retention.libsonnet, production/loki-mixin/dashboards/loki-writes-resources.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet
Refactors dashboard utils to include a separate function per template variables and another for tag+links so we don't always have to use `addClusterSelectorTemplate` which adds cluster/namespace/tag/links all in one.
=> Refactor dashboard utils to include a separate function per template

pkg/logql/log/filter.go, pkg/logql/log/ip.go
@jeschkies We merge your PR before my improvement on case insensitive search.
This ensure we use it everywhere.
=> Fix up a merge conflict on log filter

CHANGELOG.md, pkg/querier/worker_service.go, pkg/querier/worker_service_test.go
Because the internal query request handlers did not set the response
content type explicitly to `application/json`, and the external request
handler takes the response content type from the internal response to
set it for the resulting HTTP response, that response was also
incorrectly returning `Content-Type: text/plain`.
Setting the content type in the internal response correctly results in
the expected `Content-Type` header `application/json; charset=UTF-8`.
Fixes #4791
```console
$ curl -vGET http://localhost:3100/loki/api/v1/query_range --data-urlencode 'query={app="app"}' 
*   Trying 127.0.0.1:3100...
* Connected to localhost (127.0.0.1) port 3100 (#0)
> GET /loki/api/v1/query_range?query=%7Bapp%3D%22app%22%7D HTTP/1.1
> …
```
=> Set correct `Content-Type` header in query response

pkg/canary/reader/reader.go
When the Loki canary opens a WebSockets stream to tail logs, it sets a deadline. This deadline can expire if the ingester doesn't get a new log for the query within that deadline. The problem is that the error message logged on the canary is misleading as it states:
```
error reading websocket [...]
``` 
This is not true as there was no error reading from WebSockets but rather a timeout error. In this PR, we change the error handling to print a timeout message if the tailing times out, or the `error reading websocket [...]` message if the operation does not timeout but there is any other error.
Fixes #4821
**Checklist**
=> Enhance logging on timeout tailing logs on canary

pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/loki/modules.go, pkg/querier/queryrange/codec.go, pkg/querier/worker_service.go, pkg/util/server/middleware.go, pkg/util/server/middleware_test.go
1. Now client can send any metadata about query via `X-Query-Tags` HTTP header
2. Also record `X-Query-Tags` in `metrics.go` for instant and range queries.
Fixes: NA
Some context and rationale are discussed in https://github.com/grafana/loki/pull/4796#issuecomment-975547927
and [internal discussion](https://raintank-corp.slack.com/archives/C029V4SSS9L/p1637589440378600)
**Checklist**
=> Add support for `X-Query-Tags`

clients/pkg/promtail/targets/file/filetarget_test.go, clients/pkg/promtail/targets/file/filetargetmanager_test.go
Refactor filetarget tests.
We've aggregated inotify watcher to filetarget manager in the PR https://github.com/grafana/loki/pull/4794.
Hence filetarget_test.go should not depend on inotify watcher anymore.
In this PR, I've moved the tests to filetarget_manager_test.go and added a test to check handle file creation event via channel in filetarget.go.
Related: https://github.com/grafana/loki/pull/4794#discussion_r754897314
**Checklist**
=> Refactor tests of Promtail filetarget

cmd/loki/main.go, pkg/loki/loki.go, pkg/loki/loki_test.go
- Creates a new `RunOpts` used by Loki internally to customize running behavior. It is used in this PR to customize how to handle `/config` endpoint and can be used later to customize other behaviors.
N/A
**Checklist**
=> Loki: Implement custom /config handler

pkg/logql/log/fmt.go
This only includes required labels.
```
➜ go test -benchmem -run=^$  -bench ^Benchmark_Pipeline ./pkg/logql/log -v -count 5  > after.txt && benchstat before.txt after.txt
name                                 old time/op    new time/op    delta
_Pipeline/pipeline_bytes-16            13.8µs ± 6%    11.5µs ± 1%  -16.42%  (p=0.008 n=5+5)
_Pipeline/pipeline_string-16           13.9µs ± 2%    11.5µs ± 2%  -17.27%  (p=0.008 n=5+5)
_Pipeline/line_extractor_bytes-16      14.0µs ± 4%    11.6µs ± 0%  -17.45%  (p=0.016 n=5+4)
_Pipeline/line_extractor_string-16     13.5µs ± 0%    11.5µs ± 0%  -14.67%  (p=0.008 n=5+5)
_Pipeline/label_extractor_bytes-16     13.7µs ± 1%    11.7µs ± 1%  -14.69%  (p=0.008 n=5+5)
_Pipeline/label_extractor_string-16    14.1µs ±11%    11.6µs ± 0%  -17.89%  (p=0.008 n=5+5) …
```
=> Improve LogQL format stages requireLabel

Makefile, pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/loki/modules.go, pkg/querier/queryrange/codec.go, pkg/querier/worker_service.go, pkg/util/httpreq/tags.go, pkg/util/httpreq/tags_test.go, pkg/util/server/middleware.go, pkg/util/server/middleware_test.go
The PR #4814 introduced a cascading dependency from `pkg/logql` to `cortexpb` (from Cortex project). This is causing a conflict in a downstream project (GEM). More details here:
https://github.com/grafana/loki/pull/4814#issuecomment-979936641
In this PR I'm proposing an option to avoid the `cortexpb` cascading dependency for projects importing `logql` (I've tested this change and works from GEM perspective). Not sure if the refactoring I've done in the PR is acceptable for Loki project; if not, please share an alternative suggestion on how to solve. Thanks!
N/A
**Checklist**
=> Refactor pkg/util/server to avoid cortexpb import in downstream projects vendoring logql

production/loki-mixin/dashboards/dashboard-utils.libsonnet
Adds a stat panel function so we can more easily create grid layouts via loki dashboard utils.
=> Add a stat panel function to dashboard-utils

.github/dependabot.yml
Configure dependabot to keep go modules up to date.
=> Automation: Use dependabot to keep go modules dependancies up to date.

CHANGELOG.md, clients/pkg/promtail/server/server.go
This is bug fix for promtail.
Now, if we use http path prefix in promtail, it can't redirect to `/targets` from `/` and access to static assets correctly.
So I've fixed.
In addition I'd tested the two pattern cases, without path prefix and with it in my local workstation.
Fixes #4765
(also https://github.com/grafana/loki/issues/1709)
**Checklist**
=> Use http prefix path correctly in promtail

production/loki-mixin/jsonnetfile.json
Building the Loki mixin currently fails, because of a missing dependency. This causes a bad user experience for people that try to generate the manifests (compare docs on https://monitoring.mixins.dev). 
Fixes #4805
**Checklist**
=> loki-mixin: Add grafonnet-lib as dependency

pkg/querier/queryrange/codec.go, pkg/querier/queryrange/querysharding.go, pkg/querier/worker/scheduler_processor.go, pkg/storage/batch.go, pkg/storage/chunk/cache/memcached.go, pkg/storage/chunk/chunk_store.go, pkg/storage/chunk/chunk_store_utils.go, pkg/storage/chunk/series_store.go, pkg/storage/chunk/storage/caching_index_client.go, pkg/storage/chunk/util/parallel_chunk_fetch.go, pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_manager.go, pkg/storage/stores/shipper/shipper_index_client.go, pkg/storage/stores/shipper/uploads/table_manager.go
This PR removes spans that are not valuable but still keep all informations as log line.
This reduce considerably the amount of span generated by Loki. For example for a 6h queries I'm down to 4k spans from 135k.
=> Reduce tracing spans

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/validation/validate.go
When investigating per tenant rate limit issues it would be useful to see the user ID in error log message. This way we can know if the per tenant overrides that potentially changes the users rate limit value has been applied properly, and also differentiate between rate limit log messages for different tenants that have the same rate limit config value.
cc @owen-d @dannykopping 
=> log the user ID in the rate limit error message.

production/loki-mixin/dashboards/loki-chunks.libsonnet
Simplifies common label selectors code for all the queries + ports some panels that Cyril wanted.
cc @JordanRushing @cyriltovena 
=> Simplify chunks dashboard label selectors + port some more internal chunks related panels.

CHANGELOG.md, pkg/storage/stores/shipper/compactor/table.go, pkg/storage/stores/shipper/compactor/table_test.go
This PR changes the compactor code to re-create compacted boltdb files using [bbolt.Compact](https://github.com/etcd-io/bbolt/blob/master/compact.go) for 2 reasons:
1. When files are deleted, boltdb leaves free pages in the file. The only way to drop those free pages is to re-create the file.
See https://github.com/boltdb/bolt/issues/308 for more details.
2. boltdb by default fills only about 50% of the page in the file. See https://github.com/etcd-io/bbolt/blob/master/bucket.go#L26.
This setting is optimal for unordered writes.
bbolt.Compact fills the whole page by [setting FillPercent to 1](https://github.com/etcd-io/bbolt/blob/master/compact.go#L56-L57) which works well here since while copying the data, it receives 
the index entries in order. …
=> recreate compacted boltdb files from compactor when they are more than 12 hours old

CHANGELOG.md, clients/pkg/promtail/targets/kafka/target_syncer.go, clients/pkg/promtail/targets/kafka/target_syncer_test.go
registry.MustRegister is called every newPipeline and newPipeline is called in every newTarget in target_syncer.go.
Therefore MustRegister is called in duplicate and it causes the metrics collection error.
I've moved the newPipeline to newTargetsyncer to fix it.
Fixes #4865 
**Checklist**
=> Fix duplicate registry.MustRegister call in Promtail Kafka

CHANGELOG.md, docs/sources/configuration/_index.md, go.mod, go.sum, pkg/storage/chunk/aws/s3_storage_client.go, pkg/storage/chunk/aws/s3_storage_client_test.go, pkg/storage/chunk/azure/blob_storage_client.go, pkg/storage/chunk/azure/blob_storage_client_test.go, pkg/storage/chunk/gcp/gcs_object_client.go, pkg/storage/chunk/gcp/gcs_object_client_test.go, pkg/storage/chunk/hedging/hedging.go, pkg/storage/chunk/hedging/hedging_test.go, pkg/storage/chunk/openstack/swift_object_client.go, pkg/storage/chunk/openstack/swift_object_client_test.go, vendor/github.com/cristalhq/hedgedhttp/hedged.go, vendor/modules.txt
=> Add rate limiting and metrics to hedging

pkg/querier/queryrange/stats.go
Stats were being logged without a level preventing them from being filtered properly by changing the log level.
=> Loki: fix log level for statistics

clients/pkg/logentry/stages/replace.go, clients/pkg/logentry/stages/replace_test.go
This fixes a bug where adjacent capture groups are not replaced properly.
Fixes #4870
**Checklist**
- [X ] Tests updated
=> Promtail: Fix replace missing adjacent capture groups

CHANGELOG.md, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go
Fixes a bug with the common config where the replication factor was only getting applied if a common ring config was also provided.
**Checklist**
=> always apply replication factor common config

docs/sources/clients/promtail/stages/_index.md
This adds the multiline stage to the "Stages" overview page on the docs.
The multiline stage is added under the `Parsing stages` section
N/A
**Checklist**
=> [doc]: Add the multiline stage to stages overview

CHANGELOG.md, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go
We were using cortex middleware to apply this limit, but when the max_query_lookback was enforced it was generating
a reponse that is not known to Loki.
And since Loki frontend support many other type of reponses (Series,Labels,...) I had to fork the code in Loki.
I added a regression tests and also enforce the limit for labels API which was for some reason omitted.
**Checklist**
- [] Documentation added
=> Fixes 500 when query is outside of max_query_lookback

CHANGELOG.md, pkg/ingester/checkpoint.go
Calling `getInstances()` twice runs the risk that the set has expanded or contracted between allocating the slice and starting to iterate.
Stack trace where it went wrong:
```
panic: runtime error: index out of range [1743] with length 1743
goroutine 514 [running]:
github.com/grafana/loki/pkg/ingester.newStreamsIterator({0x27cc280, 0xc000a73600})
/src/enterprise-logs/vendor/github.com/grafana/loki/pkg/ingester/checkpoint.go:218 +0x2ba
github.com/grafana/loki/pkg/ingester.(*ingesterSeriesIter).Iter(0x17c33cf)
/src/enterprise-logs/vendor/github.com/grafana/loki/pkg/ingester/checkpoint.go:189 +0x25
github.com/grafana/loki/pkg/ingester.(*Checkpointer).PerformCheckpoint(0xc127edff78)
/src/enterprise-logs/vendor/github.com/grafana/loki/pkg/ingester/checkpoint.go:579 +0x25f …
```
=> ingester: use consistent set of instances to avoid panic

CHANGELOG.md, pkg/loki/loki.go
Small comment fix in module loading. I was trying to trace what config was required for which components (trying to set my install up so ingester doesn't have to roll on all config changes) and bumped into this.
Fixes #n/a
**Checklist**
- [n/a] Tests updated
=> Docs: Fix comment in Loki module loading for accuracy

CHANGELOG.md, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/stats.go, pkg/querier/queryrange/stats_test.go
This PR skips the stats middleware for the unsupported type `LokiLabelNamesResponse`, used by Grafana to check the data source connection
Fixes #4923
**Checklist**
=> Skip middleware for unsupported type

clients/cmd/logstash/Dockerfile, clients/cmd/logstash/README.md, clients/cmd/logstash/logstash-output-loki.gemspec
Use `logstash:7.16.1` as base image for the `grafana/logstash-output-loki` Docker image.
This logstash version uses `log4j` 2.15.0 which mitigates CVE-2021-44228.
- https://www.elastic.co/guide/en/logstash/current/logstash-7-16-1.html
- https://nvd.nist.gov/vuln/detail/CVE-2021-44228
Closes #4463
=> Update logstash dependency in logstash-output-loki plugin

docs/sources/copyright/_index.md
This PR adds a copyright notice to the docs. I've already handled the addition for previous versions of Loki in the /website repo. Change was requested by Fiona.
=> Add copyright notice

.github/workflows/operator.yaml
Provides a fix for failing lint and code-coverage action jobs executed on the operator path.
=> Fix failing operator github actions

operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml
This PR provides a set of loki configuration defaults reconciled by the operator:
- `chunk_retain_period: 5m`
- `parallelise_shardable_queries: true`
**Checklist**
=> Provide saner defaults for loki-operator reconciled config

CHANGELOG.md, pkg/ingester/ingester_test.go, pkg/querier/querier_mock_test.go, pkg/storage/chunk/chunk_store.go, pkg/storage/chunk/chunk_store_test.go, pkg/storage/chunk/composite_store.go, pkg/storage/chunk/composite_store_test.go, pkg/storage/chunk/inmemory_storage_client.go, pkg/storage/chunk/schema_caching_test.go, pkg/storage/chunk/schema_util.go, pkg/storage/chunk/series_store.go, pkg/storage/chunk/series_store_test.go, pkg/storage/chunk/strings.go, pkg/storage/util_test.go
In some cases we want to fetch label values from a limited set of series. This can be done by passing label matchers for the series to the `LabelValuesForMetricName` method. The matchers are applied first to filter out all chunk ids that matcher all of them. Then we fetch all label values and filter out those that are part of the chunks.
**Checklist**
=> Provide optional matchers to `LabelValuesForMetricName`.

operator/CHANGELOG.md, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml
This PR provides a saner default for `chunk_target_size`, effectively doubling the original value from `1048576` to `2097152` as suggested here: https://github.com/grafana/loki/pull/4881#discussion_r770301044
**Checklist**
=> Provide saner default for loki-operator managed chunk_target_size

docs/sources/fundamentals/architecture/deployment-modes.md
This docs change updates the callouts for 3 images in the Deployment modes section. The Docker image we use for builds has changed, and these particular callouts no longer work with the newer Docker image.
=> Docs: fix callouts for images in the Deployment modes section

docs/sources/clients/docker-driver/configuration.md
Add missing default labels `compose_project` and `compose_service` for the docker driver  when deployed with Docker Compose.
Relevant code:
https://github.com/grafana/loki/blob/24b4c0eed2ca35225c88d428f62766e4fffbc67a/clients/cmd/docker-driver/config.go#L260-L268
**Checklist**
=> Docs: Add default labels to Docker Driver for Docker Compose

docs/sources/installation/helm.md
This PR fixes the outdated documentation on how to enable the syslog support.  
The documentation is copied from the helm chart itself
**Checklist**
=> Doc: Update syslog receiver documentation

docs/sources/rules/_index.md
[initRulerStorage()](https://github.com/grafana/loki/blob/bd1fef08a8ea99e73a30c4739cfeb931353700e6/pkg/loki/modules.go#L582) rejects configurations with `configdb`, so `configdb` is clearly not supported. However, our docs lists it as a supported storage and it is potentially [misleading Loki users](https://github.com/grafana/loki/issues/4971).
Fixes #4971
N/A
**Checklist**
=> Docs: Fix list of Ruler supported storages

docs/sources/configuration/_index.md
Move `min_sharding_lookback` to the right place, as it is part of the `limits` section instead of `query_range`. I considered changing the CLI flag from `frontend.min_sharding_lookback` to something else but that would be a breaking change so I think it is actually a bad idea.
Fixes #4953
N/A
**Checklist**
=> Docs: Move `min_sharding_lookback` to the right place

pkg/querier/queryrange/split_by_interval.go, pkg/querier/queryrange/split_by_interval_test.go
The query split interval code is written with the assumption of `step` always being smaller than the `split` interval. This causes the following problems when `step` is larger than the `split` interval:
1. The first split is set to the same `start` and `end` time [here](https://github.com/grafana/loki/blob/38c42a26c6955ffbe43e484894a7b0bc461e9a13/pkg/querier/queryrange/split_by_interval.go#L292-L294) since we find the next `interval` and then try to align the difference by `step` which would always be of smaller value than `step` which then makes the `end` time to be set to the `start` time.
2. We end up with a gap in query interval because the start time of the second split would be set to <previous start time> + <step> …
=> fix splitting of queries when step is larger than split interval

docs/sources/clients/promtail/configuration.md
=> docs: fix yaml grammar mistakes

pkg/loki/modules.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go
* Remove `querier.query-ingesters-within` check when sharding is enabled on the frontend's tripperware
Fixes #5014
**Checklist**
=> Remove querier.query-ingesters-within check when sharding is enabled

docs/sources/fundamentals/architecture/deployment-modes.md
This PR brings the work of @zswanson from PR https://github.com/grafana/loki/pull/4877. Since 4877 was created, the file organization changed, such that the information added by 4877 has been relocated.
This PR updates Zach's wording and does not mention target=all, since the subsection is about the simple scalable deployment mode, and target=all specifies a single binary.
This PR also corrects the link to be relative.
=> Docs: SSD mode read target runs the compactor

pkg/ingester/index/index.go, pkg/ingester/index/index_test.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/logql/sharding.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/test_utils.go, pkg/querier/astmapper/astmapper.go, pkg/querier/astmapper/embedded.go, pkg/querier/astmapper/parallel.go, pkg/querier/astmapper/shard_summer.go, pkg/querier/astmapper/subtree_folder.go, pkg/querier/queryrange/querysharding.go, pkg/storage/batch.go, pkg/storage/chunk/schema.go, pkg/storage/chunk/schema_test.go, pkg/storage/chunk/series_store.go, pkg/storage/store.go, pkg/storage/store_test.go, pkg/storage/util_test.go
As a part of removing Loki dependency on cortex packages, we decided to copy the `querier/astmapper` package from cortex to Loki itself.
I decided to only fork this package and not whole querier because the other subpackages require code changes and the gigantique diff will make reviews a hard task. For this one I just had to copy stuff and replace `cortex/astmapper` with the new counterpart. 
NA
**Checklist**
=> Copy `cortex/pkg/querier/astmapper` package dependency into Loki

pkg/storage/chunk/azure/blob_storage_client.go
Eventually, I'd like to make a higher order utility for instrumented object clients, but the plumbing seemed a bit tedious. Instead, I've just added azure specific instrumentation here.
=> adds instrumentation to azure object client

CHANGELOG.md, docs/sources/api/_index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/http.go, pkg/distributor/http_test.go, pkg/distributor/ingestion_rate_strategy.go, pkg/loki/modules.go, pkg/util/http.go, pkg/validation/limits.go
- Inside the distributor implementation, rename `distributorsRing` to `distributorsLifecycler` to avoid mislead
- Add a ring instance to the distributor
- Implement a /distributor/ring page, served by the new ring instance
Fixes #4937
**Checklist**
=> Add distributor ring page

pkg/logql/engine_test.go, pkg/logql/functions.go
ref issue:https://github.com/grafana/loki/issues/1136
doc: https://grafana.com/docs/loki/latest/logql/metric_queries/ 
rate function doc:  rate(unwrapped-range): calculates per second rate of all values in the specified interval.
logql: rate({_source="vector-internal-metrics" }|json|name="component_received_event_bytes_total"|tags_component_id="service_metrics"|unwrap counter_value [1m])
qps = 20,000 /s
=> [new feature] logql: extrapolate unwrapped rate function

docs/sources/clients/promtail/installation.md
This docs-only PR removes unneeded links from the top of the Promtail installation page, corrects a link to the Helm installation docs (which changed), and revises a bit of wording to be more professional.
=> Docs: improve Promtail installation prose

pkg/loki/config_wrapper.go
Temporary fix until https://github.com/grafana/dskit/pull/101 is merged.
Fixes #4967
**Checklist**
=> temporary fix for the ruler joining the ingester ring

docs/sources/configuration/_index.md, pkg/storage/chunk/cache/cache.go, pkg/storage/chunk/cache/redis_client.go
The go-redis options requires multiple redis addresses for a cluster.
In some scenarios like AWS ElastiCache, a single configuration endpoint is used to resolve all cluster nodes.
This change adds an extra step to resolve all nodes and pass them to go-redis.
It removes the need to specify multiple cluster nodes in the configuration.
Signed-off-by: Siavash Safi <siavash.safi@gmail.com>
No tests were added for this scenario since it requires patching the Go resolver during runtime.
But let me know if you have a suggestion.
Same change for Cortex https://github.com/cortexproject/cortex/pull/4590
**Checklist**
=> Support Redis Cluster Configuration Endpoint

pkg/loki/config_wrapper.go
Backports #4968 to 2.4 release branch in preparation for 2.4.2
=> Backport #4968: temporary fix for the ruler joining the ingester ring (#4968)

docs/sources/clients/promtail/configuration.md
Based on https://github.com/grafana/loki/blob/main/clients/pkg/promtail/scrapeconfig/scrapeconfig.go#L224 the option to exclude user data of windows evens is misspelled in the documentation. This puts the correct exclude_user_data option in the documentation.
**Checklist**
=> Promtail: fix exclude_user_data description

pkg/ingester/tailer.go
I don't think the ticker was required in the first place, the behaviour is the same.
This should help in cluster where there's a lot of tailers since ticker can be expensive at scale (waking up many goroutine at the same time).
=> Remove unnecessary ticker in the tail loop

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/loki/common/common.go, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go, pkg/lokifrontend/frontend/v2/frontend.go
- Add two new common configurations:
- `instance_interface_names`, a common net interface used by components internally to look for addresses. The list order matters, as components internally iterate over the list until they find a valid address. If the common ring section specifies an `instance_interface_names`, this configuration is only applied to the frontend but not to other components.
-  `instance_addr`, a common instance address used by components to advertise their address. Again, if the common ring section specifies an `instance_addr`, this configuration is only applied to the frontend (since it is not a ring) but not to other components.
Fixes #4897 
**Checklist**
=> Loki: Implement common net interface/instance addr

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/validator.go, pkg/distributor/validator_test.go, pkg/validation/validate.go
This is part of JSON response giving out as the response to HTTP `/push` endpoint.
Old message
```
{"code":400,"status":"error","message":"entry for stream '{foo=\"bar\"}' has timestamp too old: 1970-01-01 01:00:00.5 +0100 CET"}
```
New message
```
{"code":400,"status":"error","message":"entry for stream '{foo=\"bar\"}' has timestamp too old: 2021-12-28 02:07:53.5 +0100 CET, oldest acceptable timestamp is: 2021-12-29 10:07:53.205042134 +0100 CET"}
```
main rationale being, hard to know what is the closest timestamp that Loki is expecting without going through the config.
Also config is not straight forward (its `latest stream's timestamp - ingester.max-chunk-age/2`)
**Which issue(s) this PR …
=> Improve error message if incoming logs timestamp is far too behind.

pkg/lokifrontend/frontend/v2/frontend_scheduler_worker.go
AddressAdded needs to hold the lock while doing operations on f.workers to ensure that its state doesn't mutate in the middle of its operations.
=> Fix race conditions in frontend_scheduler_worker.

clients/cmd/promtail/promtail-local-limit-config.yaml, clients/pkg/logentry/stages/pipeline.go, clients/pkg/promtail/config/config.go, clients/pkg/promtail/config/config_test.go, clients/pkg/promtail/limit/config.go, clients/pkg/promtail/promtail.go
refer issue : https://github.com/grafana/loki/issues/2664
it is important feature,。
In our production environment, the cpu can be reduced from 3.5 core to 0.8 core, and business monitoring begins to stabilize。
=> [new] promtail: add readline rate limit

docs/sources/configuration/_index.md
PR https://github.com/grafana/loki/pull/4826 was merged in without a documentation review.
This PR revises the descriptions of hedging configuration block knobs. It attempts to use the same formatting and description style as found in other blocks' descriptions within the documentation.  It also changes the block name to just be "hedging" following the style implemented in PRs https://github.com/grafana/loki/pull/5015 and https://github.com/grafana/loki/pull/4787.
=> Docs: Revise hedging configuration block descriptions

pkg/querier/queryrange/limits.go
If all workers are busy and we cancel a request, then we will have to wait a worker to finish to see the cancellation. 
We also don't need to close the work channel since it's buffered.
=> Fixes a possible cancellation issue in the frontend

pkg/lokifrontend/frontend/transport/handler_test.go, pkg/lokifrontend/frontend/v1/frontend.go, pkg/lokifrontend/frontend/v1/frontend_test.go, pkg/lokifrontend/frontend/v1/queue_test.go, pkg/lokifrontend/frontend/v2/frontend_test.go, pkg/querier/worker/frontend_processor_test.go, pkg/querier/worker/worker_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/scheduler.go, vendor/google.golang.org/grpc/test/bufconn/bufconn.go, vendor/modules.txt
There was a race condition between the broadcast triggered by the
canceled context and the condition waiting: if the broadcast happend
before the wait, wait never receives any broadcast.
I also ported back all tests missing from the code we forked.
=> Fix deadlock in disconnecting querier

pkg/querier/queryrange/roundtrip.go
https://github.com/grafana/loki/pull/5023 Removes the global split by configuration but we still have validation from upstream code configuration.
This PR removes the validation, while it is valid for a non multi tenant split-by in our case the validation is actually not working as we could override a tenant to a split-by zero and this means it would break his read path.
I understand this doesn't solve the problem (which we need to figure how to) but at least it really makes  the global split-by unused.
=> Removes split-by upstream validation

pkg/storage/chunk/cache/cache.go, pkg/storage/chunk/cache/cache_test.go, pkg/storage/chunk/chunk_store.go, pkg/storage/chunk/chunk_store_utils.go, pkg/storage/util_test.go
ref issue: https://github.com/grafana/loki/issues/5072
a queue (buffered channel) configurable in size (500 keys ~ 1GB)
`c.asyncQueue = make(chan []Chunk, c.maxAsyncBufferSize)
maxAsyncBufferSize:  1000,`
Each chunk is 1Mb, and the chan length is 1000, which is approximately equal to 1Gb
=> [enhancement] querier cache: WriteBackCache should be off query path

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/ingester/ingester.go
Ref https://github.com/grafana/loki/issues/5090
Doubles the flush queue length to 32 parallelism. This is small in the goroutine world and helps prevent OOMing issues when flushing cannot keep up with ingestion, especially on leaner-provisioned ingesters.
=> better defaults for flush queue parallelism

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/upgrading/_index.md, pkg/ingester/ingester.go, pkg/loki/loki.go, pkg/querier/querier.go, vendor/github.com/cortexproject/cortex/pkg/querier/queryrange/roundtrip.go
Default `parallelise_shardable_queries` to `true` (was `false`)
Default  `split_queries_by_interval` to `30m` (was `0s`)
~Default `align_queries_with_step` to `true` (was `fasle`)~ (kept the previous default due to the result of this change on queries with very large steps)
Default `query_ingesters_within` and `max_chunk_age` ~both to `2h`~ to `3h` and `2h` respectively (the addtional hour provides a buffer on top of `max_chunk_age`). Previously, `max_chunk_age` was set to `1h` and `query_ingesters_within` was set to `0`, meaning always query ingesters. An ingester with no data for a query will return quickly, so the performance improvement by defaulting `query_ingesters_within` to `2h` is minimal, and it does introduce complexity, since now if the …
=> improve default config values

CHANGELOG.md, Makefile, clients/cmd/fluentd/.gitignore, clients/cmd/fluentd/.rubocop.yml, clients/cmd/fluentd/Dockerfile, clients/cmd/fluentd/README.md, clients/cmd/fluentd/bin/setup, clients/cmd/fluentd/bin/test, clients/cmd/fluentd/docker/docker-compose.yml, clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec, clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb, clients/cmd/fluentd/spec/gems/fluent/plugin/data/non_utf8.log, clients/cmd/fluentd/spec/gems/fluent/plugin/loki_output_spec.rb
When a log line in hash format contains non UTF-8 characters fluentd
would drop the complete line because it failed to convert the line in
key-value format.
By forcing UTF-8 encoding and replacing non UTF-8 characters with empty
strings the log line will not be dropped but only contain the valid
UTF-8 characters.
Fixes #5099
**Checklist**
=> fluentd: Fix bug that caused lines to be dropped when containing non utf-8 characters

pkg/storage/tsdb/testutil/block_mock.go, pkg/storage/tsdb/testutil/objstore.go, pkg/storegateway/bucket_index_metadata_fetcher_test.go, pkg/storegateway/bucket_store_inmemory_server.go, pkg/storegateway/bucket_store_metrics_test.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/chunk_bytes_pool_test.go, pkg/storegateway/gateway_ring_test.go, pkg/storegateway/gateway_test.go, pkg/storegateway/metadata_fetcher_filters_test.go, pkg/storegateway/metadata_fetcher_metrics_test.go, pkg/storegateway/partitioner_test.go, pkg/storegateway/sharding_strategy_test.go
[PR 5088](https://github.com/grafana/loki/pull/5088) forked Cortex gateway, however, I missed to add the test files (overlooked because they weren't listed in the vendor folder). This PR adds those tests back and forks the necessary testutil from `tsdb` subpackage, used by these tests.
N/A
**Checklist**
=> Add missing forked gateway tests

pkg/querier/queryrange/queryrangebase/roundtrip.go
- Removes `split-queries-by-interval` validation when `query_range.cache-results` is enabled.
- This issue was introduced by #5023.
- This causes the loki components to always stay in error state. The error on the pods would be:
`level=error ts=2022-01-10T16:54:10.516711991Z caller=main.go:51 msg="validating config" err="invalid queryrange config: querier.cache-results may only be enabled in conjunction with querier.split-queries-by-interval. Please set the latter"`
**Checklist**
=> Remove split-queries-by-interval validation

pkg/lokifrontend/frontend/v2/frontend.go, pkg/lokifrontend/frontend/v2/frontend_scheduler_worker.go, pkg/lokifrontend/frontend/v2/frontend_test.go
Query Frontend failed to send cancel signal even to Query Frontend Worker during some special cases(explained below)
And that makes querier to run till completion(even after cancellation) wasting lots of resources.
This scenario is [analogous to this simple Go program](https://go.dev/play/p/YSb64s9UF6u) (run in go-playground). The gist is `default` branch in go `select` loop takes always precedence when other branch operations are blocked (sending or receiving on the channel). In our case, we **missed the sending of cancel signal**
Now to the original issue.
The main observation is for every Querier that haven't received cancel, it's corresponding Scheduler also didn't get it.
1. single query on QF has split into 128 sub queries
2. And all of them …
=> Fix cancel issue between Query Frontend and Query Schdeduler

production/ksonnet/loki/boltdb_shipper.libsonnet
Let compactor access the runtime_config (overrides.yaml) by mounting the configmap. This fixes the problem that compactor fails to start (crash) due to no access to the runtime config.
No issue filed.
**Checklist**
=> Jsonnet: Let compactor access the runtime_config

pkg/loki/modules.go, pkg/querier/worker/metrics.go, pkg/querier/worker/scheduler_processor.go, pkg/querier/worker/worker.go, pkg/querier/worker/worker_test.go, pkg/querier/worker_service.go, pkg/querier/worker_service_test.go
This adds a few new metrics. I've chosen not to thread them through the frontend processor as well as the scheduler processor because (1) these metrics previously didn't exist there and (2) we're largely moving towards scheduler usage even in the single binary.
I've also changed the prefixes from `cortex_` -> `loki_` after grepping and finding these unused.
These metrics and log lines will allow us to determine current read path saturation via
```promql
loki_querier_worker_inflight_queries
/
loki_querier_worker_concurrency
```
and will also enable tenant-partitioned log metrics via the `enqueue` and `dequeue` lines.
=> Querier worker/inflight metrics

pkg/storage/stores/shipper/compactor/retention/expiration_test.go
The `"just expired tenant"` test requires the corresponding `e.Expired` to be called within 0.01ms with previous code, and which fails on low performance devices.
https://github.com/grafana/loki/blob/ff47d7419a889ac94e43c08c534a58f9d448bf8e/pkg/storage/stores/shipper/compactor/retention/expiration_test.go#L70-L88
None
None
**Checklist**
=> Test: Fix test in compactor/retention/expiration_test.go on slow machines

production/loki-mixin/dashboards/dashboard-loki-operational.json
This fixes some metric name for object storage from `cortex_` to `loki_`
but also add a new Azure blob storage row.
=> Update the operational dashboard.

CHANGELOG.md, pkg/ruler/config.go, pkg/ruler/registry_test.go
A community member reported that a configured basic auth password was being sent via HTTP as `<secret>`. The reason for this is that value is stored in a [`Secret`](https://pkg.go.dev/github.com/prometheus/common/config#Secret) type, which - when marshaled, obfuscated the original password to `<secret>`.
Big thanks to @kingjan1999 for the report and the fix.
Fixes #5140
**Checklist**
=> Ruler: Fix remote write basic auth credentials

clients/pkg/promtail/targets/cloudflare/target.go, clients/pkg/promtail/targets/cloudflare/target_test.go, clients/pkg/promtail/targets/cloudflare/util_test.go
When pulling logs from Cloudflare we were only retrying the original HTTP request but not when reading the buffer which can also fail.
This PR allows to also retry reading log line from the HTTP stream. 
Unfortunately because Cloudflare doesn't guarantee order within log line we can't resume where we left off. So I opted for retrying from the start, which is anyway what an operator would do. 
We could restart from the last read timestamp but this can lead to data loss, so I opted for possible duplication instead.
To be able to investigate duplicates, I've added a log with the amount of already read message for a given batch. If this is too much for our users, we could alternatively buffer in memory a whole batch before pushing it, but that sounds more complex and risky (memory unbounded) …
=> Retry pulling Cloudflare logs after a stream error

CHANGELOG.md, clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec, clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb, clients/cmd/fluentd/spec/gems/fluent/plugin/loki_output_spec.rb
This change fixes a bug that is caused by incorrectly trying to encode
any values other than string.
Fixes #5099
**Checklist**
=> Fix encoding error in fluentd client

pkg/ruler/config.go
Introduced here: https://github.com/grafana/loki/pull/5144/files
Fixes NA
**Checklist**
=> Add `nil` check for Ruler BasicAuth config.

CHANGELOG.md, clients/pkg/promtail/targets/file/filetargetmanager.go, clients/pkg/promtail/targets/file/filetargetmanager_test.go, clients/pkg/promtail/targets/manager.go
This PR fixes a deadlock in Promtail which occurred when targets were removed from the target groups by the discovery manager.
The problem was that upon removal of a target it was removed from the targets list, but the correlating file event watcher channel was not removed from from the watchers list. This caused events to be sent to channels that were not read any more and therefore resulting in a deadlock.
Fixes #5162
**Checklist**
=> Fix promtail deadlock

pkg/storage/chunk/series_store.go
level=error ts=2022-01-17T11:56:24.310460077Z caller=redis_cache.go:37 msg="failed to get from redis" name=chunksredis err="context canceled"
=> Handle `context` cancellation in some of the `querier` store.index-cache-read.

cmd/loki/main.go
Move VerifyConfig after PrintConfig and LogConfig so that config can be dumped and the program can exit instead of starting loki.
None
Thanks!
**Checklist**
=> loki: Move VerifyConfig after PrintConfig and LogConfig

pkg/loki/config_wrapper.go, pkg/ruler/base/ruler.go
Ring keys have been moved out of dskit into their respective projects.
Removes a temporary fix that was waiting on https://github.com/grafana/dskit/pull/101
=> Remove temporary ruler ring key fix

pkg/storage/stores/shipper/storage/cached_client.go, pkg/storage/stores/shipper/storage/cached_client_test.go, pkg/storage/stores/shipper/storage/client.go, pkg/storage/stores/shipper/storage/prefixed_object_client.go
We, as of now, do a LIST calls per table when we need to find its objects.
If someone has a lot of tables cached locally or has query readiness set to a large number of days, it results in many list calls because each querier tries to sync tables every 5 mins by default.
This PR reduces the number of LIST calls we make when using hosted object stores(S3, GCS, Azure Blob Storage and Swift) as a shared store for boltdb-shipper.
The idea is to do a flat listing of objects supported by hosted object stores mentioned above and cache it until it goes stale.
Since caching requires a flat listing supported only by hosted object stores, I have added a `prefixedObjectClient`, making the implementation somewhat cleaner. …
=> add objects list caching for boltdb-shipper index store to reduce object storage list api calls

pkg/loki/loki.go, pkg/querier/querier.go
Add "query_memory_only" to make loki have option to rely only on memory availability like google monarch.
1: momery + store mode
2: momery mode
Fixes nil
<Monarch: Google’s Planet-Scale In-Memory
Time Series Database>
https://www.vldb.org/pvldb/vol13/p3181-adams.pdf
**Why is important**
Last week, due to the 1.5-hour unavailability of the s3 service in our area, the loki cluster operator by me was also completely unavailable for 1.5 hours, which had a very negative impact on my work。
In order to solve this problem, I checked After some information on how other companies solve this problem, I found that google's monarch has an in-memory mode that allows monitoring to be available …
=> [enhancement] querier : Add "query_memory_only" to make loki have option to rely only on memory availability like google monarch.

pkg/ingester/checkpoint.go, pkg/ingester/flush.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/recovery.go, pkg/ingester/replay_controller.go, pkg/ingester/stream.go, pkg/ingester/stream_test.go, pkg/ingester/streams_map.go, pkg/ingester/streams_map_test.go, pkg/ingester/transfer.go, pkg/ingester/transfer_test.go
Remove instance level `streams`/`streamsByFP` lock inside ingester, `Push` GRPC calls can run parallel to others with different streams.
This PR introduces a new struct `streamsMap` to replace `streamsMtx`, `streams`, `streamsByFP` inside ingester's `instance`. Instead of locking `streams`/`streamsByFP` while reading/writing, this struct provides `Load`/`LoadByFP` which is basically lock-free to read from internal `sync.Map`. Writing to `streamsMap` is locked internally to keep consistency of two `sync.Map`s.
Significantly improve concurrent capacity and process speed of ingester's `Push` GRPC API, as well as distributor's `/loki/api/v1/push` HTTP API. 
Fixes #5177
This PR was …
=> Remove instance level streams lock

pkg/querier/queryrange/split_by_interval.go, pkg/querier/queryrange/split_by_interval_test.go
In PR #5181, we made a change to step align query splits by step interval except for the start time of the first query and end time of the last query. When the step alignment is disabled, we see a small gap in graphs between the first and second query split since the start time of the query is not step aligned while the next query is.
This PR changes the code to step align all the query splits, including the start and end time of the first and last split.
I will open a follow-up PR to deprecate the step align flag, which does not add much value.
Queries with step > query split interval are splitter by step. These queries' start and end times are kept the same as the original query and are not step aligned since …
=> step align start and end time of the original query while splitting it

pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/compactor/table_test.go, pkg/storage/stores/shipper/downloads/index_set_test.go, pkg/storage/stores/shipper/downloads/table_manager_test.go, pkg/storage/stores/shipper/downloads/table_test.go, pkg/storage/stores/shipper/testutil/testutil.go, pkg/storage/stores/shipper/uploads/table_manager_test.go, pkg/storage/stores/shipper/uploads/table_test.go
`boltdb-shipper` did not initially have support for the compression of the files. When we added them, we wanted to have tests for making sure it is backwards compatible i.e it works fine with both compressed and uncompressed files. While adding tests, I added a flag in the test setup function `SetupDBsAtPath`, which would compress every other file. The mistake I did was I assumed specific files would be compressed but the test setup function iterated on a dict which is non-deterministic so the tests which relied on it are failing intermittently.
This PR fixes the test by allowing the caller to define which files to compress while setting up dbs.
**Checklist**
=> fix broken boltdb-shipper test

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/lokifrontend/frontend/v1/frontend.go
Per discussion in https://github.com/grafana/loki/issues/4613, and especially since we now default `parallelise_shardable_queries` to `true` this seems like a better default.
**Checklist**
=> Default max_outstanding_per_tenant to 2048

pkg/prom1/storage/metric/metric.go, pkg/prom1/storage/metric/metric_test.go, pkg/prom1/storage/metric/sample.go, pkg/querier/base/distributor_queryable.go, pkg/querier/base/distributor_queryable_test.go, pkg/querier/base/querier_test.go, pkg/querier/base/testutils.go, pkg/querier/series/series_set.go, pkg/querier/testutils.go, pkg/storage/chunk/chunk.go, pkg/storage/chunk/encoding/chunk.go
As a part of removing Loki dependency on cortex packages, we decided to copy the `prom1` package from cortex to Loki itself.
Note that we can't yet remove `cortex/pkg/prom1` as some vendored packages still using it.
N/A
N/A
**Checklist**
=> Copy `cortex/pkg/prom1` package dependency into Loki

pkg/querier/queryrange/limits.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/split_by_interval_test.go
Okay, I think I have this right :thinking: 
As far as I can tell, there isn't a defined limits default struct. However, we do parse the command line flags, and load those into a struct that is then passed as the defaults [here](https://github.com/grafana/loki/blob/1b5b8a31096784ac94981a0122b81e21ef6c5f78/cmd/loki/main.go#L36-L39). The default for `max_query_parallelism` is 32:
```
[max_query_parallelism: <int> | default = 32]
```
We then modify that further with internally defined default Loki tenant sizes. 
So, it seems to me that there's not a possibility of the value of `max_query_parallelism` for a given Loki tenant to be `0` without that having been explicitly set in a config file.
Tl; DR, this PR modifies the `limitedRoundTripper`, which uses `max_query_paralllelism`, to abort a …
=> [querier] Abort a query in limitedRoundTripper if parallelism is 0

production/loki-mixin/dashboards/dashboard-loki-operational.json
Signed-off-by: Jordan Rushing <jordan.rushing@grafana.com>
GCS panels as a part of the Loki Operational dashboard provide valuable per-operation insights into Loki behavior. Currently one of the panels is referencing an incorrect metric name. This PR resolves that issue.
N/A
N/A
**Checklist**
=> Update loki-mixin GCS queries in the Loki operational dashboard

pkg/ingester/instance.go
Ignore missing stream while querying in ingester. This means the stream has been removed while querying, and it's supposed to be picked up from storage by querier.
https://github.com/grafana/loki/issues/5228#issuecomment-1021484947
Fixes https://github.com/grafana/loki/issues/5228#issuecomment-1021196762
Please keep the issue open for original problem.
**Checklist**
=> Ignore missing stream while querying from ingester

docs/sources/clients/fluentd/_index.md
Adding default value for line_format so customers know which is picked up if the option is not provided.
Adds the default value for line_format option. To help customers know the default by looking at the docs and not having to try the different options
N/A
**Checklist**
- [X ] Documentation added
- [ NA] Tests updated
=> <Loki> Update fluentd-loki-output plugin doc to show default value for line_format

pkg/ingester/flush.go, pkg/ingester/instance.go, pkg/ingester/stream.go, pkg/ingester/streams_map.go, pkg/ingester/streams_map_test.go
This PR follows @owen-d 's [refactoring idea](https://github.com/grafana/loki/pull/5179#issuecomment-1017628706) in #5179 , with some minor differences.
Removing stream from `streamsMap` will lock its `consistencyMtx` first, then lock stream's `chunkMtx`. Pushing to stream will also acquire `consistencyMtx` first, then load and lock the stream with `consistencyMtx` being held. These two operations are guaranteed to be mutually exclusive if they are operating the same stream.
There are 3 differences compare to original idea:
1. `consistencyMtx` is a `RWMutex` now. Loading from `streamsMap` will `RLock` it, deleting will `Lock` it.
2. Flushing doesn't acquire `consistencyMtx` during whole process, but only when stream is comfirmed empty at the end.
3. …
=> Lock consistencyMtx outside locking chunkMtx

clients/pkg/promtail/targets/file/filetarget.go
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
Skips Glob search if the target path is an existing file and not a directory, skipping the glob search reduces the I/O operations on the storage
Fixes #5245
**Checklist**
=> Promtail: skip glob search if filetarget path is an existing file and not a directory

Makefile, loki-build-image/Dockerfile
Update the Go version to the latest 1.17.6.
Tested by running the new build image locally to build the yacc target.
N/A
**Checklist**
=> Build: update Go version in build image to latest and bump build image version

CHANGELOG.md, pkg/ingester/checkpoint_test.go, pkg/ingester/flush_test.go, pkg/querier/base/chunk_tar_test.go, pkg/querier/base/querier_test.go, pkg/ruler/base/api_test.go, pkg/ruler/base/lifecycle_test.go, pkg/ruler/base/manager_test.go, pkg/ruler/base/ruler_test.go, pkg/ruler/registry_test.go, pkg/ruler/rulestore/local/local_test.go, pkg/ruler/storage/cleaner/cleaner_test.go, pkg/ruler/storage/instance/instance_test.go, pkg/ruler/storage/wal/wal_test.go, pkg/storage/chunk/local/boltdb_index_client_test.go, pkg/storage/chunk/local/fs_object_client_test.go, pkg/storage/chunk/storage/factory_test.go, pkg/storage/store_test.go, pkg/storage/stores/shipper/compactor/compactor_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_store_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_table_test.go, pkg/storage/stores/shipper/compactor/table_test.go, pkg/storage/stores/shipper/downloads/table_manager_test.go, pkg/storage/stores/shipper/downloads/table_test.go, pkg/storage/stores/shipper/storage/client_test.go, pkg/storage/stores/shipper/table_client_test.go, pkg/storage/stores/shipper/uploads/table_manager_test.go, pkg/storage/stores/shipper/uploads/table_test.go, pkg/storage/stores/shipper/util/util_test.go, pkg/storage/tsdb/testutil/objstore.go
We can write less code by using the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
**Checklist**
=> refactor: use `T.TempDir` to create temporary test directory

pkg/loghttp/push/push.go, pkg/loghttp/push/push_test.go
HTTP server recognize `Content-Encoding: deflate` request header and unpack request body.
=> Push: add deflate compression in post requests

clients/cmd/fluent-bit/loki.go, clients/cmd/fluent-bit/loki_test.go
Attempt to unmarshal for unescaping json content. This is a best effort if it doesn't work the log content is sent with escaping.
Fixes #4771
**Checklist**
=> fluent-bit: Attempt to unmarshal nested json.

pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/expiration_test.go
When checking whether user specific index tables may have any expired chunks, we were using the smallest overall retention period instead of the smallest default retention period.
This causes us to unnecessarily download user index tables in some cases, for e.g:
We have a default config of `30d`, `user1` has a custom stream retention of `24h` and `user2` has no retention config.
Here the overall smallest retention period is `24h` and the smallest default retention is `30d`.
When checking if `user2`'s index table may have expired chunks based on table interval, we should be considering `30d` retention and not `24h`.
**Checklist**
=> use default retention period to check user index may have expired chunks when user does not have custom retention

clients/cmd/logstash/Dockerfile, clients/cmd/logstash/lib/logstash/outputs/loki.rb, clients/cmd/logstash/lib/logstash/outputs/loki/entry.rb, clients/cmd/logstash/logstash-output-loki.gemspec, clients/cmd/logstash/loki.conf, clients/cmd/logstash/spec/outputs/loki/entry_spec.rb, clients/cmd/logstash/spec/outputs/loki_spec.rb, docs/sources/clients/logstash/_index.md
The current behavior of the output plugin will map all fields in logstash to labels in Loki, given how different these systems do indexing this can easily result in some very high cardinality labels being sent to Loki.
Logstash has a way to mutate and remove fields specifically however this can be cumbersome or difficult to maintain.
This PR introduces a new config which is an optional list of field names which will be sent to Loki as labels.
When this list is configured, ONLY these labels will be sent to Loki.
**Checklist**
=> Logstash: Add config option which allows seting up an allowlist for labels to be mapped to Loki

clients/pkg/promtail/targets/docker/targetmanager.go, clients/pkg/promtail/targets/file/filetargetmanager.go
This PR fix a possible goroutine leak in promtail:
* `FileTargetManager.run()`will not exit after `FileTargetManager.stop()` is called.
`manager.SyncCh()` in `run()` is a read-only channel copy of `manager.syncCh`, and there is no `close(ch)` operation in manager's whole lifecycle. See code search below:
So it would be stuck in `range ch` operation. 
By passing the `context`related to `TargetManager.cancelfunc` , which is also passed to the `manager` above to control its lifecycle,  the problem is fixed and tested in our own project.
Fixes #5237 
**Checklist**
=> Promtail: fix TargetManager.run() not exit after stop is called

docs/sources/clients/promtail/stages/pack.md
The link to `unpack` documentation is broken
n/a
**Checklist**
=> Promtail docs: Fix link to `unpack` LogQL documentation

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/canary/reader/reader.go, pkg/loki/config_wrapper.go, pkg/loki/modules.go, pkg/querier/queryrange/roundtrip_test.go, pkg/storage/chunk/cache/cache.go, pkg/storage/chunk/cache/cache_test.go, pkg/storage/chunk/cache/fifo_cache.go, pkg/storage/chunk/cache/fifo_cache_test.go, pkg/storage/chunk/storage/caching_fixtures.go, pkg/storage/chunk/storage/caching_index_client_test.go
Addresses the problem of the FIFO cache where items become stale due to the validity setting but are never purged, as described in https://github.com/grafana/loki/issues/4921
Fixes #4921
**Checklist**
=> Auto-expire old items from FIFO cache

pkg/storage/stores/shipper/util/util.go
Was trying to debug why it was so slow to fetch tables, we already log this line at info level so I'm adding some timing info to it.
=> Loki: Add timing info to the log line for downloading and opening index tables

clients/cmd/logstash/Dockerfile
To get CI to pass we removed the `bundle update` command in #5268
Revisiting that PR it looks like we can continue to use the update command if we also update the version of the gem bundler.
This also updates the logstash version to the latest patchfix release.
=> logstash: re-add bundle update and update bundler

pkg/chunkenc/memchunk.go, pkg/chunkenc/unordered.go, pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/stream.go, pkg/iter/entry_iterator.go, pkg/iter/entry_iterator_test.go, pkg/iter/sample_iterator.go, pkg/iter/sample_iterator_test.go, pkg/logcli/client/file.go, pkg/logql/engine_test.go, pkg/logql/range_vector_test.go, pkg/logql/sharding.go, pkg/logql/test_utils.go, pkg/querier/querier.go, pkg/querier/tail.go, pkg/storage/batch.go
This PR is a first step toward fixing #4500 and will be followed up by other PRs that changes how deduplication works.
This PR refactor the `HeapIterator` into two distinct Iterators for different use:
- The `Merge` iterator __sort and deduplicate__ samples/entries
- The `Sort` iterator only sort samples and entries.
For convenience we were using the `HeapIterator` everywhere, but in most cases we only needed to sort samples and entries. I've changed the usage everywhere it was possible.
Bonus point the `Sort` iterator is **25%** faster than the `Merge` one.
```
goos: darwin
goarch: amd64
pkg: github.com/grafana/loki/pkg/iter
cpu: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
BenchmarkSortIterator …
```
=> Refactor HeapIterator into Merge and Sort Iterator.

CHANGELOG.md, clients/pkg/promtail/targets/docker/target.go, clients/pkg/promtail/targets/docker/target_group.go
The Docker target would not reconnect to a container if it restarted and
kept the same ID. This should introduces a `startIfNotRunning` method
that will be called to restart scraping the container's logs.
Fixes #5259
**Checklist**
=> Restart Docker target if stopped.

clients/pkg/promtail/targets/file/filetarget.go, clients/pkg/promtail/targets/file/filetarget_test.go, clients/pkg/promtail/targets/file/filetargetmanager.go, clients/pkg/promtail/targets/file/filetargetmanager_test.go
The constructor `NewFileTarget` is called from within a locked code
block by the FileTargetManager. However, the constructor also calls
`sync()` which starts and stops watching new directories. These methods
`startWatching` and `stopWatching` both send to the `targetEventHandler`
channel, causing the `FileTargetManager` to receive the event in a
goroutine running in the background. Handling the event calls
`sendFileCreateEvent` on the syncers, which again try to acquire the
already locked mutex.
Remove `sync()` call in FileTarget constructor and wait for first ticker after after `t.targetConfig.SyncPeriod` to call `sync()`.
**Checklist**
=> Fix Promtail watching deadlock

pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_test.go
When `getOrCreateIndexSet` method is called concurrently, the caller who is creating the index set should be the only one calling its `Init` function. I did a mistake in not returning the index set from the callers who found the index set already and continuing with initialization. This PR fixes the issue by avoiding calling `Init` function on index sets multiple times.
=> fix a panic in index-gateway caused by double closing of a channel

pkg/querier/queryrange/querysharding.go
Now that the sharding lookback is optional, it makes more sense to shard when the lookback is disabled. This also helps prevent not sharding due to small clock skew issues where the lookback=0 but the `time.Now()-lookback` is less than the `end` of the request.
=> Better logic for when to shard wrt disabled lookback

clients/pkg/logentry/stages/timestamp.go, clients/pkg/promtail/targets/kafka/target_syncer.go, pkg/util/string.go, pkg/util/string_test.go
Noticed a duplicate `StringsContain` function so this is a tiny PR to consolidate the functions.
**Checklist**
=> cleanup: consolidate util strings contain functions

pkg/storage/chunk/local/fixtures.go, pkg/storage/chunk/objectclient/client.go, pkg/storage/chunk/objectclient/client_test.go, pkg/storage/chunk/schema_config.go, pkg/storage/chunk/storage/factory.go, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/retention/retention_test.go
This PR piggybacks on the yet-unreleased v12 schema in order to make some much needed improvements to the chunk key encoding when using the `fileystem` backend. Previously, the entire key was base64 encoded, meaning all chunks regardless of tenant were stored in the same directory. This made discoverability hard (the keys were opaque) and caused performance problems at scale (one infinitely growing directory). Now, in v12+ schemas, the filesystem will use `<user>/<fingerprint>/base64Encode(<start>:<end>:<checksum>)`. 
Running locally will now look like:
```
$ tree chunks
chunks
└── fake
└── 655259a8c67c182c
└── MTdlYjY2OWY5MmI6MTdlYjY2OWY5MmY6ODFjNTZiZGI=
```
=> less opaque chunk keys on fs with v12

CHANGELOG.md, clients/pkg/logentry/stages/metrics.go, clients/pkg/logentry/stages/metrics_test.go, docs/sources/clients/promtail/stages/metrics.md
Promtail metrics support duration string formats
Fixes #5288
**Checklist**
=> Update promtail to support duration string formats

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
This implementation reuses errors instead of creating a new one for each line that is not a valid JSON in JSONParser and Unpack parser. These errors are used as boolean flags, we just check if an error exists and if so, we add an additional label to the line with another error message. 
Fixes #5310
```
benchstat old new                                                                                              
name                                             old time/op    new time/op    delta
_Parser/json/no_labels_hints-16                    3.83µs ± 1%    3.87µs ± 6%      ~     (p=0.587 n=5+5)
_Parser/json/labels_hints-16                       2.87µs ± 1%    2.87µs ± 2% …
```
=> Removed redundant memory allocations in parsers

tools/dev/k3d/Makefile, tools/dev/k3d/README.md, tools/dev/k3d/chartfile.yaml, tools/dev/k3d/charts/.gitignore, tools/dev/k3d/environments/loki-distributed/main.jsonnet, tools/dev/k3d/environments/loki-distributed/spec.json, tools/dev/k3d/environments/loki-distributed/values/default/config.libsonnet, tools/dev/k3d/environments/loki-distributed/values/default/values.libsonnet, tools/dev/k3d/jsonnetfile.json, tools/dev/k3d/jsonnetfile.lock.json, tools/dev/k3d/lib/grafana/grafana.libsonnet, tools/dev/k3d/lib/jaeger/jaeger.libsonnet, tools/dev/k3d/lib/k.libsonnet, tools/dev/k3d/lib/prometheus/prometheus.libsonnet, tools/dev/k3d/lib/promtail/promtail.libsonnet, tools/dev/k3d/scripts/create_cluster.sh, tools/dev/k3d/vendor/.gitignore
This PR creates a `tools/dev/k3d` folder, which is a tanka directory structure designed for easily spinning up loki clusters on k3d for development. There is currently one environment `loki-distributed` (based on the helm chart of the same name), but if people are open to this pattern I have more [environments](https://github.com/trevorwhitney/grafana-environments) I'd be happy to PR in. By using `k3d` and `tanka`, we can quickly build local clusters that leverage our open source [jsonnet](https://github.com/grafana/loki/tree/main/production/ksonnet) and/or [helm charts](https://github.com/grafana/helm-charts/), allowing people looking to contribute to Loki to get up and running quickly.
The README has more details, but to use, cd into this folder …
=> Add tooling for local k3d clusters under tools/dev

pkg/iter/entry_iterator.go
While investigating an issue, I found a bug where we can put the `*entryBuffer`  back into the pool twice. This PR ensures we only release it once.
This PR also improves efficiency a bit by ensuring we don't `nil` the underlying slice unnecessarily, instead letting the pool reuse it.
This can happen when:
First, we put it into the pool here:
```go
func (i *reverseEntryIterator) Next() bool {
i.load()
if len(i.buf.entries) == 0 {
entryBufferPool.Put(i.buf)
i.buf.entries = nil
return false
}
i.cur, i.buf.entries = i.buf.entries[len(i.buf.entries)-1], i.buf.entries[:len(i.buf.entries)-1]
return true
}
```
then it gets `Get()`'d by another goroutine, has it's `entries` appended, then the original goroutine puts it into the pool a second time here:
```go
func (i *reverseEntryIterator) Close() …
```
=> Release entryBufferPool once

pkg/ingester/ingester.go, pkg/ingester/instance_test.go, pkg/ingester/stream_test.go, pkg/ingester/tailer.go, pkg/ingester/tailer_test.go
For slow receiver, this dropped streams may cause ingester memory to keep increasing.
Sometimes OOMing the ingester.
Fixes #4797 
**Checklist**
=> Makes `tailer.droppedStreams` slice bounded.

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/http_test.go
This reverts commit 10b93cebe54af5b3af65308d5e0724e5aec2bb50.
We discovered that these changes can lead to log deduplication issues.
=> Revert "Simplify code for write path in distributor (#5248)"

pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/compactor_test.go
We have `MarkPhaseStarted` and `MarkPhaseEnded` calls to notify retention and deletion expiry checker about start/end of chunk mark phase before applying retention. When `MarkPhaseStarted` is called on the deletion expiry checker, it would load all the delete requests to process and `MarkPhaseEnded` would mark those delete requests as processed.
We recently added a config to run mark phase at a different interval than compaction interval so it means we do not always apply retention when running compaction, based on the config. The bug here we have is we were always calling `MarkPhaseStarted` and `MarkPhaseEnded` which was causing the delete requests to be marked as processed even without processing them.
This also fixes another bug in the …
=> Fix apply retention issue

pkg/util/conv.go, pkg/util/conv_test.go
The current implementation of RoundToMilliseconds is broken due to improper handling of floating-point operation in go.
See 
This PR fixes it by using simple division and modulo operators
**Checklist**
=> fix rounding of time to milliseconds

pkg/chunkenc/memchunk.go, pkg/storage/stores/shipper/compactor/retention/retention.go
While rebounding chunk with an interval, we get inclusive end time, while the iterator we use for fetching all the samples considers end time to be non-inclusive. Therefore, we added a `ns` to the end time to match the expectation to ensure we included all the requested log lines.
But since we have `ms` precise chunk intervals, which is what the deletion code works on, we lose the ns precision. So adding 1 `ns` makes us not include logs that have > 1 `ns` value. E.g., if the end time of the chunk is `1643958368443` and we have a log at `1643958368443000064`, adding 1 `ns` while rebounding the second half of that chunk would make us not include the log line at `1643958368443000064` since the end time we passed to iterator is `1643958368443000001`. …
=> add a ms instead of ns to end time of the rebound chunk interval

pkg/ruler/rulestore/objectclient/rule_store.go, pkg/storage/chunk/gcp/gcs_object_client.go
We copied over the ruler code as part of #5089, and it seems that at the same time we stopped depending on the object storage implementation of Cortex. Turns out, there are (slight) differences between the clients which meant that response returned by the API when we try to get a rule group that is not found had changed.
This ensures that is consistent with the error assertion that we have in the code for the ruler.
https://github.com/grafana/loki/blob/7fafe94e1abb230338e5ae0fd177216da3ad67af/pkg/ruler/rulestore/objectclient/rule_store.go#L56-L63
**Checklist**
=> Ruler: Rule group not found API message

pkg/loki/modules.go, pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go
Never fails if a config is wrong and only init the kvclient for ingester (leader)
**Checklist**
=> Improve report usage to never fail

pkg/loki/loki.go, pkg/loki/modules.go, pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go, pkg/usagestats/seed.go, pkg/usagestats/seed_test.go, pkg/usagestats/stats.go
Fixes:
- Correctly setup usage report dependency when being a leader.
- Ensure we wait for enough time to reconcile the key when using memberlist.
**Checklist**
=> Fixes memberlist usage report

pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_test.go
Always clean up the common index set after cleaning up the user index sets on the read path of boltdb-shipper.
=> cleanup common index set after cleaning up all the user index sets

pkg/storage/chunk/azure/blob_storage_client_test.go
Fixes a flaky test for hedging requests, Azure blob PUT may fired a second request but it's not guaranteed, so I try to figured it and don't account for it.
```
➜ go test  -run ^Test_Hedging$ github.com/grafana/loki/pkg/storage/chunk/azure -count=100 
ok      github.com/grafana/loki/pkg/storage/chunk/azure 25.785s
```
**Checklist**
=> Fixes a flaky hedging test.

pkg/storage/stores/shipper/compactor/index_set.go, pkg/storage/stores/shipper/compactor/retention/metrics.go, pkg/storage/stores/shipper/compactor/retention/retention.go, pkg/storage/stores/shipper/compactor/retention/retention_test.go, pkg/storage/stores/shipper/compactor/table.go, pkg/storage/stores/shipper/compactor/table_test.go, pkg/storage/stores/shipper/downloads/index_set.go, pkg/storage/stores/shipper/downloads/table.go
* Add `user-id` to logs when working on user-specific index and logging on it.
* Add comments at various places for clarity including describing the various index formats that come into play.
* Add `user_id` label on `loki_boltdb_shipper_retention_marker_table_processed_total` so that we can track actions done on user-specific index in the tables.
=> add more context to logs, improve comments for clarity in boltdb-shipper code

pkg/logql/engine.go, pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/loki/modules.go, pkg/querier/querier.go, pkg/querier/queryrange/stats.go
When running the single binary or in SSD mode, it's essentially impossible to disambiguate metrics.go output from the querier executing a subquery and the accumulated result output by the frontend.
This PR introduces a component to the logger to easily tell which component is outputting the metrics.go stats
**Checklist**
=> Loki: include the component in metrics.go log line

pkg/querier/tail.go
NOTE: When client is tailing, Querier **has** to create grpc connections to **all** the ingesters.
Sometimes when ingester is rolloing out and Querier unable to connect to ingester when
client is tailing, then error message reported by Querier is confusing.
This PR add some context to it.
Fixes #NA
**Checklist**
=> Add more context to tailer-> ingester connect error.

pkg/storage/chunk/azure/blob_storage_client.go, pkg/storage/chunk/azure/blob_storage_client_test.go
In the recent Azure SDK update, the type of the wrapped `not found` error changed to a pointer and caused `errors.As` to fail. This change updates our check to cover both pointer and non-pointer cases.
=> Fix Azure issue where 404 not recognized

pkg/ingester/encoding.go, pkg/storage/tsdb/index/builder.go, pkg/storage/tsdb/index/chunk.go, pkg/storage/tsdb/index/index.go, pkg/storage/tsdb/index/index_test.go, pkg/storage/tsdb/index/postings.go, pkg/storage/tsdb/index/postings_test.go, pkg/storage/tsdb/index/postingsstats.go, pkg/storage/tsdb/index/postingsstats_test.go, pkg/storage/tsdb/index/test_utils.go, pkg/storage/tsdb/querier.go, pkg/storage/tsdb/querier_test.go, pkg/util/encoding/encoding.go
This PR retrofits TSDB for use with Loki. This is highly experimental and unused by the rest of the project, but can be used as foundations for a slimmer, more tailored index.
All the commits are standalone and I suggest reviewers approach them one at a time.
=> Experimental TSDB index

.circleci/config.yml, CHANGELOG.md, docs/sources/configuration/_index.md, go.mod, go.sum, pkg/distributor/distributor_ring.go, pkg/ingester/ingester.go, pkg/loki/common/common.go, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go, pkg/lokifrontend/frontend/v2/frontend.go, pkg/ruler/base/ruler_ring.go, pkg/util/net.go, pkg/util/ring_config.go, vendor/github.com/grafana/dskit/grpcclient/grpcclient.go, vendor/github.com/grafana/dskit/kv/etcd/etcd.go, vendor/github.com/grafana/dskit/kv/memberlist/tcp_transport.go, vendor/github.com/grafana/dskit/netutil/netutil.go, vendor/github.com/grafana/dskit/ring/lifecycler.go, vendor/github.com/grafana/dskit/ring/ring.go, vendor/modules.txt
Update the dskit version and update the Loki code so the new extra logger parameter for the RegisterFlags function of the LifecyclerConfig is given when registering the flags of the ingester.
This latest dskit version also updates the LifecyclerConfig so that only [private interfaces are used](https://github.com/grafana/dskit/pull/126). This required changes to unit tests. Additionally the private interface call was added to other rings: frontend, ruler and distributor. These do not use the LifeCycler from dskit.
The CircleCI config was updated as well because dskit now requires Go 1.17.
N/A
**Checklist**
=> Update dskit version

.drone/drone.yml, Makefile
Updates the `.drone/.drone.yml` file after #5250 was merged.
**Checklist**
=> Run `make drone` to use the new build image

pkg/chunkenc/memchunk.go, pkg/chunkenc/unordered.go, pkg/chunkenc/unordered_test.go, pkg/ingester/recovery_test.go
When doing https://github.com/grafana/loki/pull/5289/files I actually missed to properly set the hash for headblocks.
This result in ingesters not sending the hash for really fresh data (uncut block) and so queriers will not dedupe accordingly.
**Checklist**
=> Correctly sets hash value for headblock iterator

docs/sources/clients/aws/ecs/_index.md
Reflects name change in v2.1.0.
- If an ECS user configures `"Name": "loki"` then the native output plugin will be used and the task configuration crashes in ECS.
The current example will not run in ECS.
Fixes n/a
**Checklist**
=> Docs: Use output plugin grafana-loki in ECS

pkg/logql/evaluator.go
When we introduce parallelism in binops, we use a waitGroup but once we have waited it cancel the  context and so when iterating it would actually stop right away.
This handle the cancellation in case of mutual failure manually and use the wait group without the context.
**Checklist**
=> Do not use WaitGroup context for StepEvaluator

docs/sources/configuration/_index.md, docs/sources/upgrading/_index.md, pkg/querier/worker/worker.go
We enable parallelism by default now it makes sense to me to enable `match_max_concurrent: true` by default such that to control a queriers parallelism you only need to adjust:
```
querier:
max_concurrent: 10
```
**Checklist**
=> set match_max_concurrent true by default

pkg/logql/ast_test.go, pkg/logql/lex.go, pkg/logql/lex_test.go
Add support for promql-like duration units in logql
Fixes #5199
**Checklist**
=> Parse duration expressions in accordance with promql

.drone/drone.jsonnet, .drone/drone.yml, Makefile
If I had a dollar for every time we had build failures related to file modified times and `make`.....
This PR removes any dependant targets from our binary build commands such that they run every time, I'm tired of chasing down weird modified time bugs related to git checkouts and file changes because git doesn't store timestamps and thus this functionality in make is extremely brittle and wastes more time than it ever saved.
We have separate checks in our CI to make sure generated assests are regenerated if they are changed, we don't need to do that as part of something like `make loki`
NOTE: While troubleshooting what turned out to be a drone issue, I also removed all the `mod=vendor` stuff we had in place to work through the migration of go from …
=> Build: simplify make targets to just run every time

pkg/storage/stores/shipper/downloads/metrics.go, pkg/storage/stores/shipper/downloads/table_manager.go
We do not have a metric tracking how long it takes to do a sync of all the tables. This PR adds the metric, which can be used for alerting if the sync operation is not happening fast enough.
=> add a metric for tracking the duration it took to sync the tables in queriers/index-gateways

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/ruler/base/manager.go, pkg/ruler/base/notifier.go, pkg/ruler/base/notifier_test.go, pkg/ruler/base/ruler.go
This option can be used to add a set of labels to all alerts emitted by the
ruler.
**Checklist**
=> pkg/ruler/base: Add external_labels option

pkg/logql/matrix.go, pkg/logql/matrix_test.go
I recently runs into a problem with the query-frontend where the query wasn't the right result but the querier would return the right result.
Turns out this is due to querysharding, when doing sharding we actually insert missing 0 point when stepping  on the results of each shards.
However this is wrong, zero during a min_over_time means something different, or even when dividing during a binary operations this can cause the creation of NaN.
The solution is simple we don't need to insert those points.
Fixes #5438
**Checklist**
=> Do not insert missing point when sharding

operator/Makefile, operator/docs/forwarding_logs_to_gateway.md, operator/docs/hack_loki_operator.md, operator/docs/hack_operator_make_run.md, operator/docs/storage_size_calculator.md, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/openshift/opa_openshift.go
- updates the default namespace for openshift to `openshift-operators-redhat`.
- updates the reference from `loki.openshift.io` -> `loki.grafana.com`
Fixes #5440 
**Checklist**
=> Change default installation namespace on OpenShift

pkg/storage/chunk/aws/dynamodb_storage_client.go, pkg/storage/chunk/cassandra/storage_client.go, pkg/storage/chunk/gcp/bigtable_index_client.go, pkg/storage/chunk/grpc/index_client.go, pkg/storage/chunk/inmemory_storage_client.go, pkg/storage/chunk/local/boltdb_index_client.go, pkg/storage/chunk/storage/caching_index_client.go, pkg/storage/chunk/storage/caching_index_client_test.go, pkg/storage/chunk/storage_client.go, pkg/storage/chunk/util/util.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_table.go, pkg/storage/stores/shipper/downloads/index_set.go, pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_manager.go, pkg/storage/stores/shipper/downloads/table_test.go, pkg/storage/stores/shipper/gateway_client.go, pkg/storage/stores/shipper/indexgateway/gateway_test.go, pkg/storage/stores/shipper/shipper_index_client.go, pkg/storage/stores/shipper/testutil/testutil.go, pkg/storage/stores/shipper/uploads/table.go, pkg/storage/stores/shipper/uploads/table_manager.go, pkg/storage/stores/shipper/util/queries.go, pkg/storage/stores/shipper/util/queries_test.go
We have a lot of places where we use the function signature instead of the defined `Callback` while accepting it as a parameter. This causes us to not satisfy the interfaces doing it in one way or the other.
This PR moves the type near the `QueryPages` interface, which is where it mostly belongs and changes all the places to use the defined type instead of the function signature.
=> use the defined querypages callback type at all the places implementing IndexClient.QueryPages

docs/sources/configuration/_index.md, pkg/distributor/clientpool/ingester_client_pool.go
1. Expose `remote_timeout` under `pool_config` block in yaml config file, as expected in documentation.
2. Fix mismatched flags `-ingester.client.healthcheck-timeout` and `-ingester.client.timeout` in documentation.
None
`remotetimeout` inside `pool_config` has been renamed to `remote_timeout`. This change does not affect any previous config file, since `remotetimeout` has never been actually exposed in yaml before.
loki-local-config.yaml:
```
ingester_client:
pool_config:
remotetimeout: 1s
auth_enabled: false
...
```
Running with latest version:
```
> loki -config.file=./loki-local-config.yaml
failed parsing config: ./loki-local-config.yaml: yaml: unmarshal errors:
line 3: field …
```
=> Fix two remote_timeout configs in ingester_client block

pkg/storage/stores/shipper/gateway_client.go, pkg/storage/stores/shipper/util/queries.go
We do an unbounded number of concurrent grpc calls from the index gateway clients and limit just the number of queries per grpc call to 100. If a large number of queries are made then the number of concurrent grpc calls go high as well. For 1M queries, we would do 10K grpc calls concurrently. This causes the index gateway server to be overwhelmed and possibly a lot of contention on the client as well.
This PR improves it by doing the following changes:
* Bound the number of concurrent grpc calls being made by index gateway clients to 10.
* Increase the max queries per grpc calls from index gateway client and max concurrent query processing in index gateway servers to 200.
These changes let us performance gains of about 60% as per the benchmark doing …
=> boltdb shipper index gateway client improvements

pkg/chunkenc/memchunk.go, pkg/chunkenc/unordered.go, pkg/ingester/ingester_test.go, pkg/iter/entry_iterator.go, pkg/iter/sample_iterator.go, pkg/logql/test_utils.go
While introducing #5289  to use the original stream hash to correctly dedupe mutated streams from the query, ingesters were still not correctly returning the right stream hash for their respective streams causing deduping to be all over the place.
This does few things:
- Correctly return the streamhash for merge iterator 🤦 it was returning the log hash
- Use always the hash for consistent data ordering, unless it's zero ( in case of query sharding)
- Rework the readBatch when building GRPC response to not overrides the stream hash.
- Add a master test for ingester deduping that sends a log of duplicate to many ingester and ensure we don't end up in this situation anymore since this was very slow and hard to debug. …
=> Fixes ingester sample deduping

pkg/logql/ast.go, pkg/logql/ast_test.go, pkg/logql/shardmapper_test.go
Counting distinct values cannot be sharded when mutating labels over multiple shards, since the same label can appears across multiple shard and will be counted twice.
Since avg() uses count then the same logic is applied for it too.
Fixes #5461
**Checklist**
=> Disable sharding of count/avg when labels are mutated

tools/dev/k3d/Makefile, tools/dev/k3d/scripts/create_cluster.sh
This PR fixes circular dependencies in the `loki-distributed` make target.
When running `make loki-distributed` the following error was prtiented:
```
Get "http://k3d-grafana:45629/v2/": dial tcp 127.0.0.1:45629: connect: connection refused
```
This is due to the `loki-distributed` make target depending on the `prepare` target which will try to push the loki image to the `k3d-grafana` container registry.
Problem is, that would only work if the `k3d-grafana` cluster is already created. Which is not since it’s created on the `create_cluster.sh` script which will be run after the `prepare`  target.
**Checklist**
=> Fix circular dependencies on k3d desployment

pkg/loki/modules.go, pkg/storage/chunk/local/boltdb_index_client.go, pkg/storage/stores/shipper/gateway_client_test.go, pkg/storage/stores/shipper/indexgateway/gateway.go, pkg/storage/stores/shipper/indexgateway/gateway_test.go, pkg/storage/stores/shipper/testutil/testutil.go
Previously, we sent just one row per batch in the index query response callback from the boltdb index client.
This, in turn, makes us send just one row at a time per grpc response from the index gateway server.
This PR improves it by streaming the response from the boltdb index client, which would, in turn, lets us send back a larger batch in grpc response from the index gateway server.
Here is the benchmark comparing the performance difference:
```
benchmark                                     old ns/op      new ns/op      delta
Benchmark_QueriesMatchingLargeNumOfRows-8     2027105841     1298895890     -35.92%
benchmark                                     old allocs     new allocs     delta
Benchmark_QueriesMatchingLargeNumOfRows-8     29321207 …
```
=> Stream query responses from boltdb index client

clients/pkg/promtail/targets/syslog/syslogparser/syslogparser.go, clients/pkg/promtail/targets/syslog/syslogparser/syslogparser_test.go, clients/pkg/promtail/targets/syslog/syslogtarget_test.go
This change enables best effort parsing for Syslog messages in the Syslog target within Promtail.
Right now, a malformed message will stop the syslog parser. However, the criteria for a message to be considered "valid" is [very low](https://github.com/grafana/loki/blob/b4bb8a1a46b4c1d1e234ee9f2f688435e5d455bc/vendor/github.com/influxdata/go-syslog/v3/rfc5424/syslog_message.go#L88).
By using the best effort option, a malformed or partially parsed message will not stop the parsing loop anymore, which otherwise would eventually close the TCP connection.
Parsing errors will still be logged and tracked in metrics.
Malformed messages will not be passed back to Promtail.  
Fixes #5395
Fixes #4270
Also presumably:
Fixes …
=> promtail/targets/syslog: Enable best effort parsing for Syslog messages

CHANGELOG.md, pkg/loki/modules.go, pkg/storage/chunk/storage/caching_fixtures.go, pkg/storage/chunk/storage/factory.go, pkg/storage/chunk/storage/factory_test.go, pkg/storage/store.go, pkg/storage/stores/shipper/downloads/index_set.go, pkg/storage/stores/shipper/downloads/metrics.go, pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_manager.go, pkg/storage/stores/shipper/downloads/table_manager_test.go, pkg/storage/stores/shipper/downloads/table_test.go, pkg/storage/stores/shipper/shipper_index_client.go, pkg/usagestats/reporter_test.go, pkg/usagestats/seed_test.go, pkg/validation/limits.go
The current query readiness support works only on table level. With a cluster building per user index and having query readiness configured, it would add a lot of overhead to keep the active index synced since we get a new index from ingesters every 15 mins.
This PR adds support for more fine-grained control over query readiness for per user index using limits overrides config.
I have also changed the metric to track the duration it takes to download the index at query time. It would be tracked per table. I have not added a user id to it to avoid adding too many series. I have added a log line which we can use for viewing per tenant download duration by both user id and table.
I have also dropped the older metric …
=> per user index query readiness with limits overrides

pkg/loki/loki.go
I found that I had missed adding overrides as a dependency for index gateways. I did not see that failure while testing per tenant index locally since I was running with target `all` which doesn't run the index gateways :facepalm:
=> initialize overrides when running index gateways which is required to run them

docs/sources/api/_index.md
Issue https://github.com/grafana/loki/issues/5476 points out deficits in our lists of links to the descriptions of the various endpoints. 
This PR removes the self-referential list items.  The docs reader can also use the links in the right-side navigation to find sections on the page.  So, we don't need links to the various subsections containing examples.
I also added "Deprecated" to the endpoint items in the list that are marked as deprecated, to help doc readers quickly identify the deprecated endpoints.
=> Docs: Fix links and formatting of HTTP API page

pkg/querier/worker/metrics.go, pkg/querier/worker/scheduler_processor.go
Add additional `user`  label to the existing `loki_querier_worker_inflight_queries` metrics.
This enables us observe per tenant in flight requests in the query workers.
/cc @owen-d 
**Checklist**
=> metrics: Add `user` label to `worker_inflight_queries`

.drone/drone.jsonnet, .drone/drone.yml
Moved autodeploy configuration into `common`, so the Loki team can access & modify the secret.
The `infra/ci` path is protected, and we have to reach out to another team to retrieve/update this secret every time, which is annoying to both parties involved and is unnecessary.
N/A
**Checklist**
=> CI: moving autodeploy configuration secret to new location

production/loki-mixin/dashboards/dashboard-loki-operational.json, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet
We renamed `cortex_bigtable*` metrics to `loki_bigtable*`, but neglected to update some dashboards which referred to those metrics.
**Checklist**
=> Dashboards: Fixing references to bigtable metrics

CHANGELOG.md, pkg/querier/worker/scheduler_processor.go
The call to update the inflightRequests metric incorrectly adds a "user" argument which seems to be used as a label name. This causes a run time panic as it only expects the label value:
```
10:22:22 enterprise-logs: panic: inconsistent label cardinality: expected 1 label values but got 2 in []string{"user", "test_instance"}
10:22:22 enterprise-logs: goroutine 966 [running]:
10:22:22 enterprise-logs: github.com/prometheus/client_golang/prometheus.(*GaugeVec).WithLabelValues(0x28933e0, {0xc0015fb9c0, 0xc001a24510, 0xc0001022d0})
```
**Checklist**
=> Remove extra param in call for inflightRequests metric

operator/internal/manifests/var.go
The operator generates Kubernetes services to be used for load-balancing between the different components. The services provide both A and SRV records, which are both used by the gRPC implementation. Currently the "port name" used for the Service (`grpc`) does not match the DNS service name the [lookup uses](https://github.com/grafana/loki/blob/main/vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go#L252) (`grpclb`). This leads to components emitting an error that the SRV record can not be found during runtime.
Fixes #5492 
**Checklist**
=> operator: Fix port name used for gRPC services

pkg/storage/stores/shipper/downloads/table_manager.go, pkg/storage/stores/shipper/downloads/table_manager_test.go, pkg/storage/stores/shipper/gateway_client_test.go
Index gateway benchmarks were failing due to limits not being initialized. This PR fixes it.
I have also cleaned up an unused method `QueryReadyIndexNumDays` from the limits interface.
=> fix broken index gateway benchmark due to missing limits

clients/pkg/promtail/targets/file/filetarget.go
Individual tailers are responsible for cleaning up their own metrics but in the case where no tailer is created because: 
- The file to be tailed exists [here](https://github.com/grafana/loki/blob/cdde6aa49dbb98d6bbfa0f29e0b3b3023211ca08/clients/pkg/promtail/targets/file/filetarget.go#L214) 
- but is gone by the time `startTailing` is called [here](https://github.com/grafana/loki/blob/cdde6aa49dbb98d6bbfa0f29e0b3b3023211ca08/clients/pkg/promtail/targets/file/filetarget.go#L238)
We orphan metrics for the affected paths.
This PR makes sure to cleanup any metrics for the path when there's an error creating the associated tailer.
=> Fix orphaned metrics in the file tailer

pkg/lokifrontend/frontend/v2/frontend_scheduler_worker.go
fix [5526](https://github.com/grafana/loki/issues/5526)
=> [bugfix] fix nil pointer

pkg/loki/modules.go, pkg/querier/multi_tenant_querier.go, pkg/querier/multi_tenant_querier_test.go, pkg/querier/querier_mock_test.go
This patch adds some functionality to the `MultiTenantQuerier` stub. `SelectLogs` and `SelectSamples` fan out into multiple calls, one for each tenant. The returned iterators are then merged back together and the proper tenant label is added.
Fixes grafana/loki-private#232
**Checklist**
=> Support `SelectLogs` and `SelectSamples` in multi-tenant querier.

CHANGELOG.md, production/loki-mixin/dashboards/loki-chunks.libsonnet
Signed-off-by: Jiacheng Xu <jiachengxu@users.noreply.github.com>
This PR uses `labelsSelector` for loki chunks dashboard. 
**Checklist**
=> Loki mixin: use labels selector for loki chunks dashboard

CHANGELOG.md, production/loki-mixin/dashboards/loki-chunks.libsonnet
This PR makes `labelsSelector` in loki chunks dashboards configurable so that it can be configured for different Loki installations.
**Checklist**
=> Loki mixin: make labelsSelector in loki chunks dashboards configurable

pkg/querier/worker/metrics.go, pkg/querier/worker/scheduler_processor.go
This reverts commit 45d5f28e67b156c84d412c36c2ffd2f082303dfe.
This commit inadvertantly created the possibility of a cardinality explosion in large clusters, as it creates metrics in accordance with `n_tenants * n_queriers`.
=> Revert "metrics: Add `user` label to `worker_inflight_queries` (#5485)"

pkg/usagestats/stats.go, pkg/usagestats/stats_test.go
The expvars generated in functions like `Edition()`, `Target()` and others in the usagestats package can be called twice. Previously it would panic in that case.
**Checklist**
=> Change usagestats expvars so they can be set twice

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/regexp/syntax/parse.go, vendor/modules.txt
This is a cherry-pick of https://github.com/golang/go/commit/ac071634c487eb6ac5422652de3c7c18fba7c522
with the following description:
regexp/syntax: reject very deeply nested regexps in Parse
The regexp code assumes it can recurse over the structure of
a regexp safely. Go's growable stacks make that reasonable
for all plausible regexps, but implausible ones can reach the
“infinite recursion?” stack limit.
This CL limits the depth of any parsed regexp to 1000.
That is, the depth of the parse tree is required to be ≤ 1000.
Regexps that require deeper parse trees will return ErrInternalError.
**Checklist**
=> Queries: update package to reject very deeply nested regexps which could crash Loki

pkg/logql/evaluator.go
Update the `vectorAggEvaluator` to return an error if the vector aggregator expression has a nil `Grouping` property, in order to avoid a nil pointer panic.
NA
**Checklist**
=> Update vectorAggEvaluator to fail for expressions without grouping

go.mod, go.sum, vendor/github.com/grafana/regexp/README.md, vendor/github.com/grafana/regexp/backtrack.go, vendor/github.com/grafana/regexp/exec.go, vendor/github.com/grafana/regexp/onepass.go, vendor/github.com/grafana/regexp/regexp.go, vendor/github.com/grafana/regexp/syntax/prog.go, vendor/modules.txt
This is a repeat of #5315, which was reverted in #5413.
See https://github.com/grafana/regexp/tree/speedup#readme
Includes the following changes proposed upstream:
* [regexp: allow patterns with no alternates to be one-pass](https://go-review.googlesource.com/c/go/+/353711)
* [regexp: speed up onepass prefix check](https://go-review.googlesource.com/c/go/+/354909)
* [regexp: handle prefix string with fold-case](https://go-review.googlesource.com/c/go/+/358756)
* [regexp: avoid copying each instruction executed](https://go-review.googlesource.com/c/go/+/355789)
* [regexp: allow prefix string anchored at beginning](https://go-review.googlesource.com/c/go/+/377294)
**Checklist**
- NA Documentation added - not user-visible.
- NA Tests updated - no …
=> regexp filter: use modified package with optimisations

.gitignore, cmd/querytee/Dockerfile
The Dockerfile referenced an incorrect path of the querytee binary
causing the build of the querytee image to fail.
```console
$ make loki-querytee-image
docker build -t grafana/loki-querytee:main-84c97ce -f cmd/querytee/Dockerfile .
Sending build context to Docker daemon  650.6MB
...
Step 7/8 : COPY --from=build /src/loki/cmd/querytee/loki-querytee /usr/bin/querytee
COPY failed: stat src/loki/cmd/querytee/loki-querytee: file does not exist
make: *** [Makefile:526: loki-querytee-image] Error 1
```
**Checklist**
=> Fix path to binary in Dockerfile for querytee

tools/promtail.sh
Our script currently won't work for anything v1.22+. This PR uses the new apiVersions which will. This change is also backwards compatible for any k8s versions v1.8 or newer: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122
=> updates clusterrole and clusterrolebinding apiVersions in promtail.sh

pkg/logql/ast.go, pkg/logql/downstream.go, pkg/logql/downstream_test.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/test_utils.go, pkg/querier/queryrange/querysharding.go
* Rename ShardedEngine to DownstreamEngine
* Minor code refactorings
With the introduction of split by range middleware for instant queries, the engine is reused for executing multiple downstream computations in parallel without a shard factor (optional). As a result, the engine should be renamed to DownstreamEngine.
NA
**Checklist**
=> Refactor sharding engine to downstream engine

operator/CHANGELOG.md, operator/Makefile, operator/bundle/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operator/config/overlays/openshift/prometheus_service_monitor_patch.yaml
This one provides a small fix missed in #5440 to allow OpenShift's Prometheus to access the operator metrics. Furthermore the make targets `olm-deploy` and `olm-undeploy` are restricted from deleting the managed OpenShift namespace `openshift-operators-redhat`.
Fixes #5559
**Checklist**
=> operator: Fix service monitor's server name for operator metrics

operator/CHANGELOG.md, operator/internal/manifests/compactor.go, operator/internal/manifests/distributor.go, operator/internal/manifests/indexgateway.go, operator/internal/manifests/ingester.go, operator/internal/manifests/querier.go, operator/internal/manifests/query-frontend.go, operator/internal/manifests/var.go
Changes the endpoints used by the liveness and readiness-probes generated by loki-operator to avoid unnecessary errors related to response size.
The PR also consolidates the readiness and liveness probes into a single place.
Fixes #5575 
- The readiness-probe for `query-frontend` is not using the proper readiness path because the load-balancer only contains ready pods and the readiness-check is waiting for clients to connect, causing a non-satisfiable condition.
**Checklist**
=> operator: Change endpoints for generated liveness and readiness probes

pkg/storage/stores/shipper/compactor/table.go
I noticed that while iterating through buckets for building index batch for writes, I was not clearing the batch while processing the next bucket. The batch gets recreated only when it gets full. This causes us to write duplicate index in other users index files.
This PR fixes the issue by creating a new batch while staring to process a bucket.
=> build a new batch while starting to process a bucket

pkg/storage/tsdb/index/index.go, pkg/storage/tsdb/querier.go, pkg/storage/tsdb/querier_test.go
This will store the earliest and latest sample timestamps in a new `metadata` part of the table of contents in TSDB. This should allow easy skipping over unneeded TSDBs, etc, and ensure fidelity post compaction or after serving delete requests.
=> Store tsdb bounds

pkg/storage/tsdb/bounds.go, pkg/storage/tsdb/bounds_test.go, pkg/storage/tsdb/index.go, pkg/storage/tsdb/index/chunk.go, pkg/storage/tsdb/single_file_index.go
Rather than coding bespoke overlap checks everywhere, this PR puts the logic into an interface which  is reused more easily and is less error prone.
=> bounds utility for tsdb lib

CHANGELOG.md, pkg/canary/comparator/comparator.go, pkg/canary/comparator/comparator_test.go
nil pointer dereferences in this code are causing panics in our deployment. It seems that confirmMissing wasn't intended to be run concurrently. The locking in this PR prevents accessing `missingEntries` while it is also being set to slice of nils(comparator.go:L482).
Fixes #5128
=> canary: Adds locking to prevent multiple concurrent invocations of `confirmMissing` from clobbering each other

operator/CHANGELOG.md, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/rbac/role.yaml, operator/controllers/lokistack_controller.go, operator/controllers/lokistack_controller_test.go, operator/internal/manifests/gateway_tenants.go, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/gateway_test.go, operator/internal/manifests/mutate.go, operator/internal/manifests/mutate_test.go, operator/internal/manifests/openshift/build.go, operator/internal/manifests/openshift/build_test.go, operator/internal/manifests/openshift/monitoring_rbac.go, operator/internal/manifests/openshift/options.go, operator/internal/manifests/openshift/rbac.go, operator/internal/manifests/openshift/route.go, operator/internal/manifests/openshift/service_ca.go, operator/internal/manifests/openshift/serviceaccount.go, operator/internal/manifests/openshift/serviceaccount_test.go, operator/internal/manifests/openshift/var.go
This PR adds the capability to reconcile RBAC for the OpenShift `openshift-monitoring:prometheus-k8s` serviceaccount to scrape LokiStack owned Loki components (e.g. distributor, ingester) metrics.
Fixes #5563
**Checklist**
=> operator: Add RBAC for Prometheus service discovery to Loki component metrics (OpenShift)

pkg/querier/worker/worker.go
Confusing log messages from the query worker
```
"total worker concurrency is greater than promql max concurrency. Queries may be queued in the querier which reduces QOS"
```
NOTE: `promql` instead of `logql`
Fixes NA
=> Replace `PromQL` -> `LogQL` wordings in Querier logs

pkg/querier/multi_tenant_querier.go, tools/dev/loki-boltdb-storage-s3/README.md, tools/dev/loki-boltdb-storage-s3/config/loki.yaml, tools/dev/loki-boltdb-storage-s3/docker-compose.yml
The original change injected the user id when the org id was required to fetch all data.
Fixes grafana/loki-private#230
The changes can be tested as follows
1. Change working directory to `tools/dev/loki-boltdb-storage-s3`.
2. Call `./compose-up.sh` to boot the cluster.
3. Query the logs with
```
curl -v -X GET -G "http://localhost:8007/loki/api/v1/query_range" -H "X-Scope-OrgID: 1|2"   --data-urlencode 'query={compose_service=~"log-gen.*"}' | jq '.data.result[].stream'
```
It will should two streams with `__tenant_id: 1` and `__tenant_id_: 2` as part of the labels.
**Checklist**
=> Test multi-tenant context propagation.

.drone/drone.jsonnet, .drone/drone.yml
Summary
- The benchmarks were not stable enough.
- They did not yield much value as we did not give much attention to
them.
=> Remove benchmark cron job.

operator/CHANGELOG.md, operator/docs/forwarding_logs_without_gateway.md, operator/index.md
- Adds documentation to connect to distributor component using ClusterLogForwarder.
- Links forwarding doc to `index.md` file.
**Checklist**
=> operator: Document how to connect to distributor component

pkg/scheduler/scheduler.go
This PR adds a new metric to the query-scheduler component.
The metric, `cortex_query_scheduler_inflight_requests`, reports the number of inflight requests (either queued or processing) sampled at a regular interval.
We'll use this metric as part of our querier autoscaling project.
We need to trigger scaling based on something that affects the querier's workload.
Queriers pull tasks from schedulers’ queues, thereafter, we will take both the size of the queue and the number of tasks being processed.
`cortex_query_scheduler_inflight_requests` is a summary so we can use percentiles to answer the question: For the past 5 mins, what was the size of the queue more than 75% of the time? Counterintuitively, taking just the maximum size of the queue is not a …
=> Add inflight requests metric for scheduler

pkg/querier/multi_tenant_querier.go, pkg/querier/multi_tenant_querier_test.go
```
› benchstat before.txt after.txt
name                          old time/op    new time/op    delta
TenantEntryIteratorLabels-16    13.4µs ± 1%     2.4µs ± 1%  -81.81%  (p=0.000 n=10+10)
name                          old alloc/op   new alloc/op   delta
TenantEntryIteratorLabels-16    4.15kB ± 0%    0.90kB ± 0%  -78.40%  (p=0.002 n=8+10)
name                          old allocs/op  new allocs/op  delta
TenantEntryIteratorLabels-16      44.0 ± 0%      29.0 ± 0%  -34.09%  (p=0.000 n=10+10)
```
This patch introduces a cache for re-labeling series from multi-tenant queries.
Fixes #5653
**Checklist**
=> Speed up re-labelling in multi-tenant queries.

clients/pkg/promtail/client/client.go
This PR fixes a bug from my last PR (https://github.com/grafana/loki/pull/5521) where labels might not be applied if they don't exist on the source stream, which will cause prometheus to panic due to incorrect label cardinality.
=> Fix bug with new promtail stream lag metric 

clients/cmd/fluent-bit/dque.go, clients/pkg/promtail/client/client.go, clients/pkg/promtail/client/fake/client.go, clients/pkg/promtail/client/logger.go, clients/pkg/promtail/client/multi.go, clients/pkg/promtail/client/multi_test.go
In order to fix the bug with promtail multi clients and metrics scraping I introduced the `name` field/config option to clients. This gets around duplicate metric issues by using the name as a label on client specific metrics (of which there is only one currently, the stream lag metric). Since we're doing this, we should also require that client configs are unique when creating clients.
Note that users who need to have duplicate configs can still do so by changing only the `name` config value.
=> Require unique client configs when there are multiple clients.

clients/cmd/promtail/main.go, clients/pkg/promtail/client/config.go, clients/pkg/promtail/config/config.go, clients/pkg/promtail/config/config_test.go, clients/pkg/promtail/promtail.go, docs/sources/clients/promtail/configuration.md
On the refactor PR https://github.com/grafana/loki/pull/5521 configuration `StreamLagLabels` was moved to a new wrapper config, meaning the promtail client configuration now has an additional `configs` parameter:
```
clients:                                                                                                              
configs:                                                                                                                                                                     
- external_labels:                                                                                                                                                         
cluster: dev-eu-west-0 …
```
=> Move promtail StreamLagLabels config to upper level config.Config

operator/CHANGELOG.md, operator/internal/handlers/internal/secrets/secrets.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml, operator/internal/manifests/storage/options.go
https://github.com/grafana/loki/pull/5432 added additional storage types for the installation to use. However, the PR was missing configuration changes to the `boltdb_shipper` and `schema_config` fields. This caused some components, like the ingester, to look for `S3` storage when none was specified.
**Checklist**
=> operator: Configuring multiple storage stypes for boltdb-shipper and schema

operator/CHANGELOG.md, operator/internal/manifests/config.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml, operator/internal/manifests/internal/config/options.go
This PR implements a long-standing recommendation to switch from using the `frontend_worker.parallelism` config option for `frontend_worker.match_max_concurrent: true` that sync the value from `querier.max_concurrent`. Later represents the upper bound of parallel queries to process per querier based on available CPU cores.
Fixes [Recommendation request](https://github.com/grafana/loki/pull/4881#discussion_r770303369)
**Checklist**
=> operator: Replace frontend_worker parallelism with match_max_concurrent

CHANGELOG.md, clients/cmd/promtail/promtail-local-limit-config.yaml, clients/pkg/promtail/config/config.go, clients/pkg/promtail/config/config_test.go, clients/pkg/promtail/promtail.go
Make configuration name consistent
**Which issue(s) this PR fixes**: 
Fixes #5703
**Checklist**
=> Promtail: Rename config name limit_config to limits_config

docs/sources/clients/fluentbit/_index.md
**Remove trailing commas from JSON code blocks**
Trailing commands are syntactically not allowed in JSON
**Change links to fluentbit.io website**
The documentation for the Fluent Bit Loki output plugin references the fluentbit.io website multiple times. However, the structure of this website seems to have changed. This commit updates the links to the correct URLs (if possible).
Fixes #5401
=> Update Fluent Bit docs

.drone/drone.jsonnet, .drone/drone.yml
Currently the querytee image needs to be built manually and is also not available on Dockerhub. This PR adds a pipeline step to build and publish the querytee image.
**Checklist**
=> Build querytee image as part of CI pipeline

docs/sources/clients/promtail/scraping.md
Since the GELF support in Promtail uses a library that is not necessarily meant for production usage in servers, it should be marked as experimental feature, until the library is replaced.
See https://github.com/grafana/loki/issues/5644 for more information.
**Checklist**
=> Mark GELF support in Promtail as experimental

cmd/logcli/main.go
If connecting to a TLS secured endpoint with an explicit port with logcli, certificate validation fails:
```
logcli --ca-cert=$TLS_CA --cert=$TLS_CERT --key=$TLS_KEY --addr=https://<host>:<port> labels
error sending request Get "https://<host>:<port>/loki/api/v1/labels?end=1645559631967253910&start=1645556031967253910": x509: certificate is valid for <host>, <SAN>, not <host>:<port>
Error doing request: Run out of attempts while querying the server
```
The problem can be (insecurely) avoided by adding a `--tls-skip-verify` option. 
This PR ensures that the ServerName field of the TLSConfig struct contains only the host if a port is provided to avoid
the failure. 
Per Contribution guide, didn't open an issue since …
=> logcli: Remove port from TLS server name when provided in --addr

docs/sources/release-notes/_index.md, docs/sources/release-notes/v2-5.md
Section added to make it easier to add v2.5 items to the release notes.
=> Docs: add an empty v2.5 release notes section

docs/sources/clients/aws/ecs/ecs-task.json
The configuration of the Fluent Bit plugin uses `grafana-loki` as [output name](https://github.com/grafana/loki/blob/main/clients/cmd/fluent-bit/fluent-bit.conf). In the documentation for ECS `loki` is used wrongly. This PR updates the ECS example to use `grafana-loki` as well. 
**Checklist**
=> Update fluent-bit output name

operator/CHANGELOG.md, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/openshift/opa_openshift.go
The following PR adds the missing `--opa.matcher` command line argument for the opa-openshift sidecar used when tenant mode is `openshift-logging`. This extra parameters compiles a prometheus label matcher used by Loki to limit non-admin users to have access only to logs of pods in namespace they are granted accesss to.
**Checklist**
=> operator: Add missing label matcher for openshift logging tenant mode

operator/CHANGELOG.md, operator/docs/forwarding_logs_to_gateway.md
After merge of #5624, use of UUIDs for generated tenants in tenant-mode openshift-logging has been eliminated. The tenant name is re-used as tenant id.
**Checklist**
=> operator: change uuids to tenant name in doc

clients/pkg/promtail/targets/lokipush/pushtarget.go, clients/pkg/promtail/targets/lokipush/pushtarget_test.go, clients/pkg/promtail/targets/lokipush/pushtargetmanager.go
We were passing in the active metrics registry to the util tool that sets up the logger to be used by the push server, this resulted in a duplicate metrics registration.
The metric being registered is not important so this PR just passes in an empty registry to use to init the logger.
**Checklist**
=> Promtil: Fix a panic when using the loki push api target.

docs/sources/configuration/_index.md, pkg/ingester/ingester.go, tools/dev/loki-boltdb-storage-s3/config/loki.yaml
Under normal operation the flush queue generally doesn't get too large and flush operations can completely fairly quickly. However, sometimes if the remote storage is slow, the remote storage is unavailable for a period, or when replaying a very large WAL it's possible to build a big enough flush queue that a flush operation needs more than 10s to complete.
Another more interesting question is, what should the upper bound of this operation really be? This is hard for me to answer, I think all operations should have a timeout so it seems like waiting forever here isn't ideal, but is 10m enough? 
This is related to some discoveries in #5267
=> Loki: Increase flush_op_timeout default from 10s to 10m

CHANGELOG.md, clients/pkg/promtail/limit/config.go, docs/sources/clients/promtail/configuration.md
Addresses issue https://github.com/grafana/loki/issues/5730.
Reviewers: what have I missed or gotten wrong in this addition of documentation?
=> Docs: Document Promtail global rate limiting

docs/sources/upgrading/_index.md, pkg/distributor/http.go, pkg/loki/loki.go, pkg/lokifrontend/frontend/transport/handler.go, pkg/storage/stores/shipper/compactor/deletion/request_handler.go, pkg/util/server/error.go, pkg/util/server/error_test.go
PR #4845 changed the return type of error messages from plain text to JSON. 
This PR was actually fixing a problem with the current API which returns plain text and sets a `Content-Type` header of `application/json` but then returns plain text. The problem is it's significantly changing the behavior of the API which should be considered a breaking change and we should wait to do this at the next major release.
It's entirely possible anyone who's implemented their own code against the Loki API are expecting the error messages in their current format and even though this is a "fix" it would break those users so we want to wait to do this until a future major release.
=> Loki: Revert #4845 which changed the format of errors from the API

.golangci.yml, pkg/storage/stores/shipper/downloads/table_manager_test.go
Using the pointer to the enclosing loop variable in a range loop likely
leads to unwanted behaviour. Introducing the check [`exportloopref`](https://github.com/kyoh86/exportloopref) helps
to prevent the usage of such pointers.
> The iteration variables may be declared by the "range" clause using a
> form of short variable declaration (:=). In this case their types are
> set to the types of the respective iteration values and their scope is
> the block of the "for" statement; they are re-used in each iteration.
https://go.dev/ref/spec#For_statements
=> golangci-lint: Check for pointers to enclosing loop variables

CHANGELOG.md, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
This updates all references to alpine images to the latest released 3.15.4
It was released yesterday to address busybox [CVE-2022-28391](https://security.alpinelinux.org/vuln/CVE-2022-28391)
**Checklist**
=> Update alpine images to 3.15.4

docs/sources/operations/storage/boltdb-shipper.md
// UploadInterval defines interval for when we check if there are new index files to upload.
// It's also used to snapshot the currently written index tables so the snapshots can be used for reads.
UploadInterval = 1 * time.Minute
@sandeepsukhani
=> fix boltdb-shipper doc

pkg/querier/http.go, tools/dev/loki-boltdb-storage-s3/config/datasource.yaml
The `/tail` endpoint is expected to return `HTTP 400` bad request when more than one tenant is present in the context. This change introduces this behaviour *bofore* the connection is upgraded to a web socket.
This pull request also fixes the datasource configuration for the Docker Compose development environment.
Closes #5753
**Checklist**
=> Return bad request for multi-tenant tail.

Makefile, tools/nfpm.yaml
The `packages` step in our Makefile has never worked as far as I can tell, this fixes it so the Circle CI release job will work.
The `-m` flag during the `zip` stage of `dist` will move the file into the resulting zip, meaning it is no longer in the `dist` folder. As a result, the `packages` step, which is looking for the compiled `logcli-linux-amd64` binary in the `dist` folder will always fail. 
This change unzips the `logcli` zip to a tmp folder so the `packages` step can find it.
**Checklist**
=> fix missing file during rpm and deb packaging step

pkg/storage/stores/shipper/uploads/table_manager.go
[Optimization] boltdb: reduce the code block affected by the lock tablesMtx in the TableManager.query() function.
util.DoParallelQueries(ctx, table, queries, callback) , free lock.
@sandeepsukhani  boltdb issue.
**Checklist**
=> [Optimization] boltdb readpath: reduce the code block affected by the lock tablesMtx in the TableManager.query() function

pkg/storage/stores/shipper/uploads/table.go
We currently take an exclusive lock for each index write to check whether desired index file exists which can cause contention. This PR improves the code by checking index file exists with a read lock and then takes a write lock to create if it does not exist.
=> improve mutex locking when writing index in boltdb-shipper

pkg/storage/stores/shipper/uploads/table.go
Incorporate feedback on merged PR #5830.
=> incorporate feedback on merged pr #5830

clients/pkg/promtail/promtail.go, clients/pkg/promtail/promtail_test.go
Check if the test has already failed before waiting for everything to exit.
Also call `Shutdown()` via `defer` so we clean up those resources when the test fails.
Fixes #5836
**Checklist**
- NA Add an entry in the `CHANGELOG.md` about the changes.
=> TestPromtail: avoid hanging when test fails midway

pkg/usagestats/stats_test.go
If this test is run alongside a number of other tests then the number of goroutines can change between when the report is generated and when the result is checked, which will cause the test to fail.
**Checklist**
- NA Add an entry in the `CHANGELOG.md` about the changes.
=> usagestats tests: don't check unpredictable number

Makefile
Setting GOGC=10 makes Go run garbage-collection every time the heap gets 10% bigger than it was before, which does keep the max size down but slows down memory-intensive operations.
Since this was [added for CircleCI](https://github.com/grafana/loki/pull/1022/commits/edea13fd929f27426d4b1a090923ad2b343a22fd), and we don't run those operations on CircleCI any more, remove the setting.
Comparison: tests go from 3min 10sec to 2min 14sec and lint from 3min 53sec to 1min 9sec.
Before:
```
$ GOGC=10 /bin/time go test --count=1 ./...
406.41user 76.88system 3:10.22elapsed 254%CPU (0avgtext+0avgdata 953252maxresident)k
348928inputs+7543984outputs (7044major+5071863minor)pagefaults 0swaps
$ golangci-lint cache clean
$ GOGC=10 /bin/time golangci-lint run -v …
```
=> Makefile: run lint and tests with default garbage-collection

tools/lambda-promtail/template.yaml, tools/lambda-promtail/variables.tf
This fixes a typo in the CloudFormation template file (`Descripton`)
which makes it unusable, as well as some other minor typos.
n.a.
**Checklist**
=> lambda-promtail: fix typos in CloudFormation and Terraform files.

CHANGELOG.md, clients/pkg/promtail/promtail.go
This PR adds `ActiveTargets` method propagating the activate targets of `targetManager` of
a Promtail instance. This method is useful for https://github.com/grafana/agent/pull/1582 to know
in order to fetch all active targets of a given promtail instance.
**Checklist**
=> promtail: Add ActiveTargets method

clients/pkg/promtail/targets/kafka/target_syncer_test.go
The `Test_TopicDiscovery` expections were wrong, we only need them to be true at some point since this
is reconciliation loop.
Fixes #5858
Nice catch !
**Checklist**
=> Improve kafka discovery test.

docs/sources/configuration/_index.md
Docs: Fix the command line description of the **grpc_server_max_send_msg_size** parameter
=> Docs: Fix the command line description of the grpc_server_max_send_msg_size parameter

CHANGELOG.md, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go
In the case where `instance_interface_names` is declared in the common
configuration AND the common ring configuration is also present,
`instance_interface_names` from common configuration is overwritten by
default ring configuration for all ring components.
This behavior is not the one described in documentation. 
This commit fix this issue by overwriting common ring net interface
config IF it is deeply equal to the default one.
Example:
```
common:
instance_interface_names:
- interface
ring:
kvstore:
store: inmemory
```
Then (example with Distributor configuration),
```
Distributor.DistributorRing.InstanceInterfaceNames == defaults.Common.Ring.InstanceInterfaceNames
```
but should be
```
Distributor.DistributorRing.InstanceInterfaceNames == …
```
=> loki: Fix common config net interface name overwritten by ring common config

Makefile, clients/cmd/fluent-bit/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, cmd/logcli/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, operator/Dockerfile, operator/calculator.Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
This updates golang version to v1.17.9
https://groups.google.com/g/golang-announce/c/oecdBNLOml8
```
git ls-files  '*[Dd]ockerfile*' | grep -v ^vendor/ | xargs sed -i "s/golang:[0-9\\.]*/golang:1.17.9/g" | ag 'golang:'
```
=> Upgrade golang version to v1.17.9

docs/sources/configuration/_index.md, pkg/querier/querier.go
Fix missing query_ingester_only setting in docs. Resource created with https://github.com/grafana/loki/pull/5093
=> docs: fix query_ingester_only config

.drone/drone.jsonnet, .drone/drone.yml, CHANGELOG.md, Makefile
Raise version of build image correctly
Was raising the makefile first in #5899 . Now read the docs again:
https://github.com/grafana/loki/blob/main/docs/sources/maintaining/release-loki-build-image.md
=> Upgrade golang version to v1.17.9 correctly tag build image

pkg/storage/factory.go
This adds a new condition to our conditional clause that checks if boltdb-shipper should be used for the index or not.
Without this check, there's a chance of boltdb being enabled even if no index gateway ring or index gateway address are available, which would lead to problems as no communication with the index gateway would be possible.
N/A
This was previously suggested by Sandeep on https://github.com/grafana/loki/pull/5514#discussion_r828977931, we applied it but somehow lost this during a rebase.
**Checklist**
=> Loki: Don't use boltdb-shipper if gateway communication isn't available

operator/CHANGELOG.md, operator/internal/manifests/internal/sizes.go
This PR aligns the PVC storage size requests of `1x.extra-small` with the requests of `1x.small` and `1x.medium`. This allows seamless upgrades of all stateful Loki components w/o the need to implement an particular migration handler in the operator. Since `1x.extra-small` is used only for demostration purposes, it would have been an overkill to write a handler that cleans up PVCs and statefulsets before re-creating the in the next bigger t-shirt size.
**Checklist**
=> operator: Align PVC storage size requests for all lokistack t-shirt sizes

pkg/querier/multi_tenant_querier.go, pkg/querier/multi_tenant_querier_test.go
In order to fully support tenant ID label filtering we need to return `__tenant_id__` in the label names.
Fixes #5754, #5753
**Checklist**
=> Include tenant ID label in label values.

pkg/loki/modules.go, pkg/storage/store.go, pkg/storage/stores/shipper/gateway_client.go
As spotted in #5918 the index-gw should not use the index-gw client but the local storage instead.
I'm taking another path than relying on the ring, but instead use a new config.
**Checklist**
=> Fixes the index-gateway when using the ring

pkg/ingester/flush.go
#5894 changed how we flush chunks but had a small bug which resulted in the checksum and some other values not being set properly because we passed a copy of the chunk and not a pointer to it and were mutating it.
=> Loki: Fix issue with recent change to flush code

docs/sources/community/governance.md
This PR appends the SIG operator team to the official goverance doc as discussed here:
https://docs.google.com/document/d/1dSyDwUHpFdAjdS46X4RNx9OkewY2JimRWq3Xs39LScU/edit#
=> Add SIG operator team to governance doc

docs/sources/best-practices/_index.md
changed URLs for [Fluentd](https://github.com/grafana/loki/tree/main/clients/cmd/fluentd) and [Fluent Bit](https://github.com/grafana/loki/tree/main/clients/cmd/fluent-bit) since the old URLs where leading to a 404 on GitHub.
I think there is none
This is my first ever PR in an Open Source project. I hope I have done it right :)
**Checklist**
=> Docs: Correct bad links in the best practice docs

pkg/loki/modules.go, pkg/storage/async_store.go, pkg/storage/async_store_test.go, pkg/storage/factory.go, pkg/storage/store.go
We have a [ChunkStore](https://github.com/grafana/loki/blob/8f024954539b5eb706ab3ef967c4b1696ad04fd6/pkg/storage/stores/composite_store.go#L16) type which has a `GetChunkRefs` method and [LokiStore](https://github.com/grafana/loki/blob/5ea1951c6e3e2690bdfb993e6a71dc4e8d8efe50/pkg/storage/store.go#L41) type which is actually a wrapper on top of `ChunkStore` type, providing methods like `SelectLogs`, `SelectSamples` etc.
We also have a [AsyncStore](https://github.com/grafana/loki/blob/5ea1951c6e3e2690bdfb993e6a71dc4e8d8efe50/pkg/storage/async_store.go#L34) type which is used when `boltdb-shipper` is used as an index store so that we can get chunk ids of recently flushed chunks from ingesters. However, it only implements the `GetChunkRefs` method, …
=> store: fix bug in getting chunk ids from ingesters when using boltdb-shipper

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/index_set_test.go, pkg/storage/stores/indexshipper/downloads/table.go, pkg/storage/stores/indexshipper/downloads/table_manager.go, pkg/storage/stores/indexshipper/downloads/table_manager_test.go, pkg/storage/stores/indexshipper/downloads/table_test.go, pkg/storage/stores/indexshipper/downloads/testutil.go, pkg/storage/stores/indexshipper/downloads/util.go, pkg/storage/stores/indexshipper/index/index.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/indexshipper/uploads/index_set.go, pkg/storage/stores/indexshipper/uploads/index_set_test.go, pkg/storage/stores/indexshipper/uploads/table.go, pkg/storage/stores/indexshipper/uploads/table_manager.go, pkg/storage/stores/indexshipper/uploads/table_manager_test.go, pkg/storage/stores/indexshipper/uploads/table_test.go, pkg/storage/stores/indexshipper/uploads/testutil.go, pkg/storage/stores/shipper/shipper_index_client.go
Build a generic index shipper which would be shared by `boltdb-shipper` and `tsdb-shipper` for shipping index files.
Since tsdb and boltdb based index files would have different query APIs and the way the index would be built, `index-shipper` would just manage the immutable index with following interface:
```
type Index interface {
Name() string
Path() string
Close() error
Reader() (io.ReadSeeker, error)
}
```
It has all the properties of `boltdb-shipper` like query readiness, query time downloading of index, syncs etc.
This does not have any impact yet since the code is not wired. I will slowly start wiring `boltdb-shipper` to start using `index-shipper`.
The thing that is still left to be decided is whether we will have different directories for …
=> build generic index shipper to be shared between boltdb-shipper and tsdb-shipper

pkg/util/validation/limits.go, pkg/validation/validate.go
This fixes a tiny typo in the word "limit" in 429 error for `Per stream rate limit exceeded (limit: %s/sec)` that I happened to notice while deploying Loki. Also spotted the same typo in some comments.
Fix minor typo in error response.
N/A
**Checklist**
=> Docs: Fix typo in 429 exceeded rate limit error message

pkg/storage/stores/tsdb/single_file_index_test.go
```
--- FAIL: TestSingleIdx (0.01s)
--- FAIL: TestSingleIdx/head (0.00s)
--- FAIL: TestSingleIdx/head/LabelValues (0.00s)
single_file_index_test.go:188: 
Error Trace:	single_file_index_test.go:188
Error:      	Not equal: 
expected: []string{"bar", "bard"}
actual  : []string{"bard", "bar"}
Diff:
--- Expected
+++ Actual
@@ -1,4 +1,4 @@
([]string) (len=2) {
- (string) (len=3) "bar",
- (string) (len=4) "bard"
+ (string) (len=4) "bard",
+ (string) (len=3) "bar"
}
Test:       	TestSingleIdx/head/LabelValues
FAIL
```
Fixes NA
Not sure if methods `LabelNames` and `LabelValues` should return strings sorted. So sorting it before the assert.
**Checklist**
=> chore: Fix flaky test with `TestSingleIdx`.

clients/pkg/promtail/client/client.go
Add a log message stating that client level stream lag labels deprecated and will not be used. 
Alternatively, we have talked about simply removing this field from the client config. This would break users who currently have the `stream_lag_labels` field set, but would really only be problematic for users who had multiple clients configured with different `stream_lag_labels` values. However, this configuration is technically not semantically correct, and wouldn't be accepted in future versions of promtail anyways. 
I'm opening this PR so we have a single place where we can make a decision on which of these two options to go with:
1. the change in this PR, and remove the deprecated in a future major release
2. make the breaking change now
Personally I would choose option 2 but if we want …
=> [promtail] Add a log message stating that client level stream lag labels are deprecated

pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_test.go
While cleaning up expired index, we look at the last used time to decide whether an index set has expired or not. The last used time gets set to `now` while initializing or querying the index set. The common index set should always be the last one to expire because it is the parent directory of all the user index sets and while querying we anyways need both user and common index set.
To make sure common index set never expires before user index set, we query user index set first so that its last used time is smaller than common index set. However that would not work always because if user cancels the query between index set querying, the last used time of common index set would not get updated and break our expectation.
This PR fixes the issue by …
=> boltdb-shipper: common index set should not expire before any of the user index sets

pkg/storage/stores/shipper/indexgateway/gateway.go
=> fix index gateway chunk refs response (#5957)

docs/sources/maintaining/release-loki-build-image.md, loki-build-image/Dockerfile
**Update documentation how to build and use the loki-build-image**
The existing documentation was not clear about the two-step process for
building and using the image. This PR tries to improve that.
**Trigger build for Loki build image version 0.20.3**
In commit 435391661f4e0f03eb378f77c07aaad5009cd6e9 the version was
increased from 0.20.2 to 0.20.3 in the `.drone/drone.jsonnet` file, but
not in the `.drone/drone.yml`, which caused the image not to be built.
In order to trigger the build of 0.20.3, contents of the
`loki-build-image/` folder need to change, therefore the comment in the
Dockerfile.
**Checklist**
=> Other: trigger build of loki-build-image:0.20.3

.github/pull_request_template.md
We would like to start creating a more curated changelog, and do so when PR's are added/merged.
The template update explains to only add PR's if they are for fixes to issues in previous released versions, new features, or important changes.
It's the job of the Loki Team Member that merges the PR to make sure the changelog entry is necessary and written such that it's easy to consume by someone scanning the changelog when looking to update Loki to a new release.
=> Other: Update pr template

production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/gateway.libsonnet
Signed-off-by: Ivan Rizzante <i.rizzante@gmail.com>
Currently it's not possible to configure the DNS resolver in [Gateway](https://github.com/grafana/loki/blob/7299e3bdcdae5bd7dacd08be67f706fdbaab8543/production/ksonnet/loki/gateway.libsonnet#L42), which is a problem if `kube-dns` Service does not exists.
**Checklist**
=> Loki: Make DNS resolver configurable in Gateway

pkg/loki/config_wrapper_test.go, pkg/storage/chunk/client/aws/s3_storage_client.go, pkg/storage/chunk/client/aws/s3_storage_client_test.go
This PR makes sure that we don't commit S3 credential values to logs when using `-print-config-stderr` and `-log-config-reverse-order` flags. 
**Checklist**
=> redact s3 credential values when printing config to logs

CHANGELOG.md, pkg/logql/rangemapper.go
Add missing changelog entry for split by range of instant queries.
Minor typos.
NA
**Checklist**
=> Add changelog entry for split by range of instant queries

pkg/logql/syntax/parser.go, pkg/storage/stores/shipper/indexgateway/gateway.go
This fixes a bug in the index gateway when querying values for a label.
Since the gRPC handler for LabelValuesForMetricName in the index gateway
allows empty matchers in the LabelValuesForMetricNameRequest, we need to
check if the matchers string is an empty matcher (`{}`) before we parse
the string.
This bug was introduced with the index gateway api refactoring in #5892
Fixes: #5965
**Checklist**
=> Do not parse string of empty matchers

pkg/storage/stores/series/series_index_gateway_store.go
when index gateway does not implement the new API.
This bug did not yield an error but only returned incorrect results
because both functions `c.IndexStore.LabelNamesForMetricName` and
`c.IndexStore.LabelValuesForMetricName` return `([]string, error)`.
**Checklist**
=> Call correct method on index store

pkg/storage/stores/shipper/shipper_index_client.go
Makes the log output significantly more meaningful.
Before:
```
level=info ts=2022-04-21T07:35:01.687187409Z caller=shipper_index_client.go:107 msg="starting boltdb shipper in 0 mode"
```
After:
```
level=info ts=2022-04-21T07:35:01.687187409Z caller=shipper_index_client.go:107 msg="starting boltdb shipper in read-write mode"
```
=> Add string representation of boltdb shipper mode

.drone/drone.yml, .golangci.yml, Makefile, pkg/ingester/ingester.go, pkg/storage/stores/tsdb/index/index.go
The new build image uses the latest version **v1.45.2** of golangci-lint. With this version running the `make lint` locally yields the same results as running on CI.
* Requires https://github.com/grafana/loki/pull/5924 so that `0.20.3` is built
* ~~This PR contains commits from https://github.com/grafana/loki/pull/5901~~
* The changes in file `.drone/drone.yml` were generated by `make drone`
* Code changes are fixes for the linter:
```
pkg/storage/stores/tsdb/index/index.go:1525:61: unexported-return: exported func ReadFingerprintOffsetsTable returns unexported type index.fingerprintOffsets, which can be annoying to use (revive)
func ReadFingerprintOffsetsTable(bs ByteSlice, off uint64) (fingerprintOffsets, …
```
=> Use new build image 0.20.3

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
It will ensure that our proto files follow a consistent formatting throughout. 
This PR adds `buf` to the build image and will be followed by the usage of buf in #6000
This is the first in a series two PRs (second being #6000)
**Checklist**
~- [ ] Documentation added~
~- [ ] Tests updated~
~- [ ] Add an entry in the `CHANGELOG.md` about the changes.~
=> Ensure proto definitions are formatted [1/2]

docs/sources/configuration/_index.md, pkg/storage/chunk/client/azure/blob_storage_client.go
Found a few stale references to cortex to remove.
=> Remove references to cortex

pkg/logql/log/filter.go, pkg/logql/log/filter_test.go
Regexes with concat alternate that contains empty matches are not required for filtering.
For instance `(?:)bar|foo` is exactly the same as `bar|foo`
=> Remove empty match within concat of regex

go.mod, go.sum, vendor/github.com/hpcloud/tail/tail_posix.go, vendor/modules.txt
Revendors `grafana/tail` to introduce a recent fix to how we tail symlinks. With the current implementation, promtail is only able to work with symlinks if they're in the same folder as the promtail binary; if they're inside a nested folder, tail is unable to find the files.
- Fixes https://github.com/grafana/loki/issues/3374
- The fix is based on moving to [filepath/EvalSymlinks method](https://pkg.go.dev/path/filepath#EvalSymlinks) instead of `os.Readlink`
- This was already tested [here](https://github.com/grafana/tail/issues/11)
**Checklist**
=> Revendor `grafana/tail` to fix promtail symlink behavior

pkg/storage/stores/shipper/downloads/metrics.go, pkg/storage/stores/shipper/downloads/table_manager.go
~~Adds a new `query_readiness_duration_seconds` metric, that reports query readiness duration of a tablemanager/index gateway instance. We should use it later to report performance against the ring mode.~~ 
~~Adds a new `usersToBeQueryReadyForTotal` metric, that reports number of users involved in the query readiness operation. We should use it later to correlate number of users with the query readiness duration.~~
Logs the users involved in the query readiness operation. Will be especially useful for the ring mode so that we can track down the users assigned to each instance.
Logs the duration spent in the query readiness operation.
N/A
N/A
**Checklist**
=> Add better observability to queryReadiness

production/loki-mixin/dashboards/loki-reads-resources.libsonnet
This component has been around for a while but has not been added to the
loki-mixin yet.
**Checklist**
=> Add query scheduler to "Read Resources" mixin dashboard

docs/sources/clients/aws/ecs/_index.md
This PR re-adds the reviewed and approved content added in https://github.com/grafana/loki/pull/5387. That PR became stale and was closed. This is the work of @jrykr.
=> Docs: PR 5387 redo - Warn ECS users to avoid plain text creds

pkg/storage/stores/series/index/caching_index_client.go, pkg/storage/stores/series/index/schema_util.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/series/series_store_utils.go
This PR improve performance of index queries of the series store by:
- Removing useless debug log in the hot path.
- Re-use slice of index entries to reduce allocations
- Use yolostring from index entries since those byte slice will never changed.
=> Improve series store index queries

CHANGELOG.md, cmd/loki/loki-docker-config.yaml, pkg/chunkenc/dumb_chunk.go, pkg/chunkenc/facade.go, pkg/chunkenc/interface.go, pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/loki/modules.go, pkg/storage/chunk/bigchunk.go, pkg/storage/chunk/interface.go, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/deletion/delete_request.go, pkg/storage/stores/shipper/compactor/deletion/delete_request_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager_test.go, pkg/storage/stores/shipper/compactor/deletion/validation.go, pkg/storage/stores/shipper/compactor/deletion/validation_test.go, pkg/storage/stores/shipper/compactor/retention/expiration.go, pkg/storage/stores/shipper/compactor/retention/expiration_test.go, pkg/storage/stores/shipper/compactor/retention/retention.go, pkg/storage/stores/shipper/compactor/retention/retention_test.go, pkg/util/filter/filter_function.go
Add filter functionality to the delete functionality of the compactor. This is hidden behind the "filter-and-delete" value of the deletion_mode config setting.
A filter function is added to the intervals sent to the Rebound function. This removes lines that match the given DeleteRequest.
**Checklist**
=> Add filter parameter to rebound so lines can be deleted by the compactor

tools/dev/loki-boltdb-storage-s3/docker-compose.yml
You can access the development Grafana without `admin:admin` and `skip`.
=> docker-compose: Disable auth in Grafana

production/loki-mixin/dashboards/loki-reads-resources.libsonnet
re: https://github.com/grafana/loki/pull/5946
This PR adds a new dashboard panel in the `Loki - Reads Resources` dashboard to visualize query readiness duration for IndexGateways.
N/A
N/A
**Checklist**
=> Add IndexGateway Query Readiness Duration panel to `Loki - Reads Resources` dashboard in production/loki-mixin

pkg/storage/chunk/cache/memcached.go
Since failing to put to memcached does not have an operational impact on
the write path, this log message should not be an error. Make it a
warning instead.
Do people rely on log messages being at a specific log level?
**Checklist**
=> Decrease log level for "failed to put to memcached"

pkg/storage/chunk/client/local/boltdb_index_client.go, pkg/storage/chunk/client/local/boltdb_index_client_test.go
This removes the timer and sync code, and replace it with a batch cursor that iterate when required.
Also improve the memory usage.
```
❯ benchstat before.txt after.txt 
name       old time/op    new time/op    delta
_Query-16    3.16µs ± 4%    1.01µs ± 5%  -67.96%  (p=0.008 n=5+5)
name       old alloc/op   new alloc/op   delta
_Query-16    1.08kB ± 1%    0.66kB ± 0%  -38.95%  (p=0.008 n=5+5)
name       old allocs/op  new allocs/op  delta
_Query-16      15.0 ± 0%      10.0 ± 0%  -33.33%  (p=0.008 n=5+5)
```
=> Improve batching in boltdb index

pkg/logql/downstream.go, pkg/logql/downstream_test.go, pkg/logql/mapper_metrics.go, pkg/logql/rangemapper.go, pkg/logql/rangemapper_test.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/querier/queryrange/metrics.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/split_by_range.go
* Refactor ShardingMetrics to MapperMetrics
* Add MapperMetrics to range mapper: each mapper contains the same set of metrics with a constant label that determines the mapper type, i.e., "shard" and "range" for shardMapper and rangeMapper, respectively.
Note: the metric names were not changed for backward compatibility ([see comment for more detail](https://github.com/grafana/loki/pull/6030/files#r858950266)).
For example, for the following configuration:
* `row_shards: 2`
* `split_queries_by_interval: 1m`
running the **instant query** `bytes_over_time({app="foo"}[5m])` and taking into account that the split by range middleware is executed prior to the sharding middleware (i.e., the downstream queries outputted by the range middleware are inputted …
=> Add metrics to range mapper

pkg/storage/stores/shipper/util/queries.go, pkg/storage/stores/shipper/util/queries_test.go
This PR improves deduping of entries by using different deduper depending if we are running with or without concurrency, but also make sure the concurrency is bounded even for a lot of index queries ( above 100k) maximun 10 goroutine are spawned per query.
Benchmark result:
```
❯ benchstat before.txt after.txt                                                                                                                                  
name                    old time/op    new time/op    delta
_MultiQueries/50-16        102µs ± 3%      45µs ± 2%  -55.39%  (p=0.008 n=5+5)
_MultiQueries/100-16       203µs ± 3%      90µs ± 5%  -55.57%  (p=0.008 n=5+5)
_MultiQueries/1000-16     4.16ms ± 1%    2.44ms ± 1%  -41.35%  (p=0.008 n=5+5)
_MultiQueries/10000-16    43.5ms ± 3%    24.5ms ± 1% …
```
=> Improve index entries deduping and concurrency

pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go
After noticing some unexpected module failures, I realized the usage reporter is returning context cancellation as errors. This doesn't work well with the service code which [cancels](https://github.com/grafana/loki/blob/main/vendor/github.com/grafana/dskit/services/basic_service.go#L242-L246) the context itself. I've adjusted the code to ignore cancellations for this reason.
=> ignores reporting cancellations as errors in the usage-reporter module

pkg/loki/modules.go, pkg/querier/metrics.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/tail.go, pkg/querier/tail_test.go
=> Add tailing metrics

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/table_manager.go, pkg/storage/stores/indexshipper/downloads/table_manager_test.go, pkg/storage/stores/indexshipper/downloads/table_test.go, pkg/storage/stores/shipper/compactor/index_set.go, pkg/storage/stores/shipper/compactor/table.go, pkg/storage/stores/shipper/downloads/index_set.go, pkg/storage/stores/shipper/downloads/index_set_test.go, pkg/storage/stores/shipper/downloads/table.go, pkg/storage/stores/shipper/downloads/table_manager.go, pkg/storage/stores/shipper/downloads/table_manager_test.go, pkg/storage/stores/shipper/downloads/table_test.go, pkg/storage/stores/shipper/storage/cached_client.go, pkg/storage/stores/shipper/storage/cached_client_test.go, pkg/storage/stores/shipper/storage/client.go, pkg/storage/stores/shipper/storage/client_test.go, pkg/storage/stores/shipper/storage/index_set.go, pkg/storage/stores/shipper/table_client.go
To reduce the number of list calls we make to the object store when using boltdb-shipper, we have a cache in place. The cache stays valid for 1 min and is refreshed when a list call is made and it finds that cache needs to be rebuilt. The list call could take a couple of seconds to finish in a large cluster which can add up to the query latency when downloading index at query time.
This PR adds a parameter to list calls to skip the list cache and directly load the objects list from the object store. We will skip the cache only while doing query time download of index which is not too common, we see just up to 8k query time download operations in a day in our largest Loki cluster.
The other change this PR does is to detect the staleness of the list …
=> boltdb shipper index list cache improvements

CHANGELOG.md
Add a missing changelog entry introduced by PR https://github.com/grafana/loki/pull/6034.
N/A
N/A
**Checklist**
=> Add missing changelog entry for change introduced by PR 6034.

pkg/logcli/query/tail.go
This PR changes logcli tailing to check if the quiet flag is false before logging not critical messages.
Fixes #4124
N/A\
**Checklist**
=> Logcli: Respect quiet flag in logcli tail.go

clients/cmd/promtail/Dockerfile.arm32
Fixes journald parsing for arm32 systems with newer systemd/journald. The same fix was previously accepted for the main promtail Dockerfile.
Fixes #5938
=> promtail/docker: Update libsystemd-dev from bullseye-backports for arm32 docker images

production/ksonnet/promtail/promtail.libsonnet
In Kubernetes 1.22, policyRule is promoted to v1 and out of v1beta.  Here we make the adjustment to the jsonnet call to reflect that change and allow users on 1.22 to make use of this jsonnet.  It looks like this was available at least back to 1.18.
https://jsonnet-libs.github.io/k8s-libsonnet/1.18/rbac/v1/policyRule/
**Checklist**
=> Promote policyRule to v1

CHANGELOG.md, production/ksonnet/loki/query-scheduler.libsonnet
Kubernetes sets up a DNS search path like `namespace.svc.cluster.local, svc.cluster.local, cluster.local, google.internal`; any unqualified name is first tried as a prefix to each of these. These requests, which will never succeed, add latency and increase load on the DNS service.
Adding a `.` at the end makes the name fully-qualified, so Go's DNS client will skip the search path and use the name as-is.
Note this only changes a subset of addresses in the config; others didn't seem to be causing a problem and I don't have a good way to test them.
**Checklist**
=> production config: add dot to some DNS address to reduce lookups

production/loki-mixin/dashboards/loki-reads-resources.libsonnet, production/loki-mixin/dashboards/loki-writes-resources.libsonnet
Update the Loki reads/writes resources pages to not include empty rows.
Before:
After:
**Checklist**
=> Update Loki writes resources dashboard

pkg/loki/modules.go
With `boltdb-shipper`, we have some timers configured to manage the index across various services. This PR looks at the time we allow sync operations to finish in the worst-case scenario.
With the current timers set, in the worst-case scenario, we should be finishing the index sync operation in up to 2 mins and if we fail, users might see gaps in their query response. This PR tunes some timers to allow syncs to have more time to run, specifically allowing sync to get the updates in up to 3 attempts. This change impacts the following timers with default values:
* retains index files with ingester for 20m instead of 12m after uploading.
* sets GetChunkIDs lookback to 2h41m instead of 2h28m.
The impact of this is ingesters getting more queries from …
=> allow more time for boltdb-shipper index syncs to finish

docs/sources/clients/_index.md
Added a link to the HTTP C# client [NLog-Targets-Loki](https://github.com/corentinaltepe/nlog.loki) in Loki's clients documentation in the unofficial clients sections, right next to its Serilog counterpart.
**What this PR does / why we need it**: adds a link to an existing unofficial C# NLog client to Loki for visibility.
**Which issue(s) this PR fixes**: none
**Special notes for your reviewer**: this is an HTTP client library. I'd like to implement a gRpc client library as well. I haven't yet decided if this will part of the same library or a separate one.
**Checklist**
=> docs: Add NLog-Targets-Loki as unofficial C# client to Loki

CHANGELOG.md, docs/sources/upgrading/_index.md, pkg/ingester/tailer.go
Stops live tailing from splitting a stream into more streams when using parsers while still maintaining the ability to mutate the log line using parsers and `line_format`
The current implementation will allow creating many new streams from a tailed stream when using parsers, but this multiplicative affect can make it difficult to then tail the stream because it creates a lot more overhead in the amount of data pushed down the websocket.
For the purposes of live tailing which is meant primarily for human consumption, returning the parsed and extracted labels and manipulating the streams isn't helpful for the end user visualization and instead makes the process less efficient and more likely to struggle to keep up with higher volume streams.
Update: …
=> Loki: Change live tailing to only allow mutating the log line not the number of streams.

CHANGELOG.md, clients/pkg/promtail/scrapeconfig/scrapeconfig.go, clients/pkg/promtail/targets/syslog/syslogparser/syslogparser.go, clients/pkg/promtail/targets/syslog/syslogtarget.go, clients/pkg/promtail/targets/syslog/syslogtarget_test.go, clients/pkg/promtail/targets/syslog/transport.go, docs/sources/clients/promtail/scraping.md
Until now, the syslog target in Promtail did only support TCP. This PR adds support for sending syslog messages to Promtail (via ng-syslog or rsyslog) via UDP.
UPD for syslogs can be used if you prefer speed over guaranteed delivery.
Fixes #5370 
**Checklist**
=> Add UDP transport option to Promtail's syslog target

integration/client/client.go, integration/cluster/cluster.go, integration/loki_micro_services_test.go, integration/loki_single_binary_test.go, integration/shared_test.go, pkg/loki/loki.go, pkg/storage/chunk/fetcher/fetcher.go
This PR adds simple go based integration tests, which can run Loki
in two modes:
- single-binary
- micro-services with index-gateway
After standing up it performs the most basic duties like:
- ingest logs
- run a range query
- query label names and label values
This is meant to catch more significant problem as early as possible in
the PR.
We should aim to keep this as simple as possible.
Note: _`integration/client/client.go` is copied from the closed source Granana Enterprise Logs code based_
=> Add integration tests which test happy path

pkg/querier/queryrange/codec.go, pkg/querier/queryrange/codec_test.go
When encode/decode `http.Request` into `querybase.Request` we re-create request.Path.
Before this PR, both `/labels/` and `/labels/{name}/values` endpoint was decoding into same URL path `/labels/` before
forwarding to the querier. So it always returns label names as response.
This bug became visible after enabling all the middleware for `/labels/{name}/values` endpoint as well via #6072
Fixes # NA. 
**Checklist**
=> Fix(query-frontend): LokiCodec encode/decode works correctly with label values endpoint

docs/sources/configuration/_index.md, docs/sources/configuration/query-frontend.md, docs/sources/logql/log_queries.md, docs/sources/logql/template_functions.md, docs/sources/operations/recording-rules.md, docs/sources/operations/scalability.md, docs/sources/rules/_index.md, docs/sources/tools/logcli.md, pkg/storage/chunk/client/azure/blob_storage_client.go
- References to "cortextool" remain in the docs
- https://github.com/grafana/loki/pull/6015 changed other references, but missed just one in an Azure storage msg. This PR includes that 1 code change.
=> Docs: remove Cortex references

pkg/querier/worker/scheduler_processor.go
We have enough metrics now (queue time, queue length and metrics.go statistics)
that makes these log entries obselete.
Fixes #NA
Quickly checked internal and external mixins to verify it's not used in any dashboards or alerts.
**Checklist**
=> chore(query-scheduler) Remove nosiy "inflight" requests log entries

pkg/storage/stores/series/index/table_manager.go
There is excessive logging of "creating table" and "synching tables" messages, change them
to use level.Debug() instead of level.Info() to limit the output.
Fixes #1786
=> table_manager: Change some level.Info() logging to level.Debug()

docs/sources/fundamentals/architecture/deployment-modes.md
Reverts grafana/loki#6089
i think it's break https://grafana.com/docs/loki/next/fundamentals/architecture/deployment-modes/ pic
and i see the desc at `https://github.com/grafana/loki/tree/main/docs`
> `The files in this directory are used to generate it but consequently the links don't work in Github.`
so reverts that pr
=> Revert "Docs: fix pic location in `sources/fundamentals/architecture/deployme…"

CHANGELOG.md, docs/sources/clients/lambda-promtail/_index.md, tools/lambda-promtail/README.md, tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/promtail.go, tools/lambda-promtail/main.tf, tools/lambda-promtail/template.yaml, tools/lambda-promtail/variables.tf
Add multi-tenancy support (by sending `X-Scope-OrgID` header). It's supported by main clients, makes sense to add it to lambda-promtail.
None
**Checklist**
=> lambda-promtail: Add multi-tenancy support

pkg/storage/stores/shipper/downloads/index_set.go, pkg/storage/stores/shipper/downloads/index_set_test.go, pkg/storage/stores/shipper/downloads/table.go
Do not increment index sync operation count metric from index set since we already track it on the overall sync operation in table manager [here](https://github.com/grafana/loki/blob/2758dc659acbf5682a9655422b43396a1fed5a83/pkg/storage/stores/shipper/downloads/table_manager.go#L206).
This would also fix unexpected increases in failure counts due to stale index list cache which we handle already by checking if the error is `errIndexListCacheTooStale` and retry the sync.
=> do not increment sync operation count metric on per index set

operator/docs/enhancements/enhancement_template.md, operator/docs/enhancements/ruler_support.md
The following PR adds a enhancement proposal for adding Ruler support into the Loki Operator.
Addresses #5211 and #5843
**Checklist**
=> operator: Ruler enhancement proposal

pkg/ingester/flush.go, pkg/storage/stores/tsdb/head_manager.go
Fixes a mutability bug with labels during TSDB flushes across index buckets.
=> fix mutability bug with labels during tsdb flushing

pkg/storage/stores/indexshipper/uploads/table.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go, pkg/storage/stores/tsdb/manager.go
This PR ensures that on startup, the index-shipper is loaded with any previously created tsdb indices, which may or may not have already been flushed to storage. This is important for two reasons:
1) If they were not flushed, this will re-register them to be flushed to storage
2) It will make previously built TSDBs available for querying in the `ingester` and `write` targets, which use the `uploadmanager` for reads.
=> loads previously created TSDBs into shipper on startup

pkg/distributor/distributor.go, pkg/ingester/ingester.go
We have generic `grpc_healthcheck` endpoint that get registered for all the components
during initialization stage.
https://github.com/grafana/loki/blob/main/pkg/loki/loki.go#L364
Looks like these old health checks that are part of actual component's struct itself came from legacy.
NOTE: This should be **no** op. No build or test failure as **there are no consumer for these methods**
Fixes # NA
We figured this out while investigating this ingester/querier grpc issue https://github.com/grafana/loki/issues/6023
**Checklist**
=> Remove unused grpc health check methods

docs/sources/configuration/_index.md
https://github.com/grafana/loki/pull/5109 went stale and was closed.  It was fully approved, but never got merged in. Now, with the large delay, CI can't pass without the original PR submitter rebasing.  Easier to recreate this one character docs change.
This is the work of @markspolakovs.
=> Docs: redo PR 5109

pkg/logql/downstream_test.go, pkg/logql/rangemapper.go, pkg/logql/rangemapper_test.go
This PR optimizes instant queries that use a vector aggregation around a range aggregation with log extraction stage (`json`, `logfmt`), such as `sum(count_over_time({foo="bar"} | logfmt | duration > 30s [24h]))`.
Since the vector aggregation can be pushed down to the downstream query, the downstream query does not create a massive amount of streams, even though it contains a generic label extraction stage.
This would also fix binary expression queries that use said aggregation on one of its leave nodes, such as:
```
sum(count_over_time({foo="bar"} | logfmt | duration > 2s [3s]))
/
sum(count_over_time({foo="bar"} [3s]))
```
If either the left hand side or the right hand side of a binary expression is a noop, we need to return the original expression …
=> Fix certain binary expression queries by optimizing through push down

CHANGELOG.md, pkg/ingester/tailer.go
The query pipeline will build a label cache to improve performance when processing queries, the normal use of a pipeline for queries is ephemeral so the cache is cleared when the pipeline is discarded.
When tailing, however, the pipeline was long lived and reused which lead to an unbounded growth of cached labels for certain tail queries.
This PR creates a new pipeline for every processed push into Loki vs reusing. 
There is probably future potential for a mechanism to clear the cache but not sure it's worth the additional effort vs creating and disposing of pipelines.
**Checklist**
=> Loki: When processing logs during tailing, don't reuse the query pipeline

operator/CHANGELOG.md, operator/docs/gcs_object_storage.md, operator/internal/handlers/internal/secrets/secrets.go, operator/internal/handlers/internal/secrets/secrets_test.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/handlers/lokistack_create_or_update_test.go, operator/internal/manifests/compactor.go, operator/internal/manifests/indexgateway.go, operator/internal/manifests/ingester.go, operator/internal/manifests/object_storage.go, operator/internal/manifests/object_storage_test.go, operator/internal/manifests/querier.go, operator/internal/manifests/storage/configure.go, operator/internal/manifests/var.go
There isn't an authentication mechanism in the provided Loki configuration. The Loki GCS authentication is handled via the GCS SDK which is typically done with environment variables(For example:GOOGLE_APPLICATION_CREDENTIALS).
**Checklist**
=> operator: Add method to get authenticated from GCP

pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/tsdb/identifier.go, pkg/storage/stores/tsdb/index_client.go, pkg/storage/stores/tsdb/manager.go
Doing some minor fixes for the issues that I found on my local setup:
1. Uploads manager was never queried when downloads manager was initialized in index shipper.
2. Files created from nodes having `-` in their names were failing to be opened.
3. `__name__` matcher was not removed from queries passed to tsdb head.
=> tsdb query fixes

docs/sources/logql/log_queries.md
`"response_size" => "228"` was mentioned twice in json parser list of labels and `response_latency_seconds` was missing
**Checklist**
=> log_queries.md: response_size was mentioned twice

cmd/logcli/main.go, pkg/logcli/client/client.go
Add logcli flag auth-header to be able to specify authorization header name.
What this PR does / why we need it:
Adds a flag auth-header which defaults to Authorization.
Fixes https://github.com/grafana/loki/issues/6143
Special notes for your reviewer:
Change has no side effects on existing users unless they use the new flag auth-header.
Checklist
Documentation added
Tests updated
Is this an important fix or new feature? Add an entry in the CHANGELOG.md.
Changes that require user attention or interaction to upgrade are documented in docs/sources/upgrading/_index.md
=> specify logcli authorization header by flag

docs/sources/api/_index.md, docs/sources/configuration/_index.md, docs/sources/operations/storage/logs-deletion.md
This is the updated documentation for the changes to the deletion api in PR https://github.com/grafana/loki/pull/5481 .
**Checklist**
=> Add docs for updated deletion api

cmd/logcli/main.go
Fix logcli  auth-header env variable LOKI_AUTH_HEADER.
What this PR does / why we need it:
Makes the help consistent with other help. I'm sorry to not have spotted it earlier.
Fixes https://github.com/grafana/loki/issues/6143
Special notes for your reviewer:
Sorry for the small pr... @kavirajk  
Checklist
Documentation added
Tests updated
Is this an important fix or new feature? Add an entry in the CHANGELOG.md.
Changes that require user attention or interaction to upgrade are documented in docs/sources/upgrading/_index.md
=> fix auth header env variable usage help

docs/sources/configuration/_index.md, pkg/scheduler/scheduler.go
Since now shuffle sharding is supported on the `query-path` in Loki,
it makes sense to enable this config.
Fixes #NA
Related #6173 
**Checklist**
=> query-scheduler: Now proper support for `querier_forget_delay`

pkg/querier/http.go
Without this fix, it causes panic, if series or label endpoint returns error.
Fixes NA
@sandeepsukhani found querier panics in one of our internal Loki cluster because of this bug.
**Checklist**
=> fix(querier): Record `result` length after response validation.

pkg/storage/stores/tsdb/builder.go, pkg/storage/stores/tsdb/index/index.go
This PR ensures we use the correct (without tenant label) fingerprints in TSDB creation ordering. 
This is a tricky one. I noticed crashes during TSDB WAL replays due to out of order index entries. This is because we add a `__loki_tenant__` label to TSDB for pre-compacted indices. Previously, we were sorting series by the label-hashes which included the tenant label, which exposed us to ordering issues. Now, we use the correct fingerprint without the synthetic label.
=> tsdb creation supports fingerprint overrides

operator/docs/hack_operator_make_run.md
Original command tries to apply kustomization.yaml which gives a validation error.
```
kubectl apply -f config/overlays/development/minio 
```
Replaced with the -k version, which runs kuztomize:
```
kubectl apply -k config/overlays/development/minio
```
=> Fix typo in operator/docs/hack_operator_make_run.md

integration/client/client.go, integration/loki_micro_services_delete_test.go
This adds an integration test that creates a delete request and checks the status.
Waiting until the delete request is done is not added here. This will be done in a subsequent PR.
**Checklist**
=> Add integration test for delete request

pkg/storage/stores/tsdb/multitenant.go
This PR prevents sending the internal tenant label used in `LabelNames` queries. This label is only used to pack multiple tenants into a single TSDB index until we compact to multitenant ones.
=> strips out tenant label from LabelNames queries

pkg/storage/store.go, pkg/storage/stores/composite_store.go, pkg/storage/stores/composite_store_entry.go, pkg/storage/stores/series/series_index_gateway_store.go, pkg/storage/stores/series/series_index_gateway_store_test.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/shipper/gateway_client.go, pkg/storage/stores/shipper/indexgateway/gateway.go, pkg/storage/stores/shipper/indexgateway/indexgatewaypb/gateway.pb.go, pkg/storage/stores/shipper/indexgateway/indexgatewaypb/gateway.proto, pkg/storage/stores/tsdb/store.go
1. enable new grpc calls on index gateway and add GetSeries call
2. Use index gateway client when enabled for boltdb-shipper index store.
* Please do not merge this PR until we are ready to enable new grpc calls or we add a flag to control it since we had disabled them until we can improve index gateway performance.
* We rely on boltdb-shipper config for now to initialize the index gateway client. We will have to discuss and decide how we want to proceed with tsdb config. I feel that we should share the same config to avoid complexities.
=> tsdb index gateway

pkg/storage/stores/shipper/gateway_client_test.go
Do not report an error on shutting down the test gRPC server as test failure.
**Checklist**
=> Fix flaky gRPC server shutdown in tests

pkg/loki/config_wrapper_test.go, pkg/storage/chunk/client/aws/s3_storage_client.go, pkg/storage/chunk/client/aws/s3_storage_client_test.go, pkg/storage/chunk/client/baidubce/bos_storage_client.go, pkg/storage/chunk/client/baidubce/bos_storage_client_test.go
**security: Redact BOS credentials when marshalled to YAML**
Change the type of the credentials flags for the BOS client configuration from string to flagext.Secret, which automatically redacts to `********` when marshalled to YAML.
**Use flagext.Secret for S3 object client credentials**
instead of a package private, similar implementation of a secret type flag. The redacted output of the value changes from `redacted` to `********`.
Fixes #6184
No changelog entry because the BOS storage feature is unreleased.
**Checklist**
=> security: Redact credentials when marshalled to YAML

CHANGELOG.md
- Changes a changelog entry related to the compactor address introduction, moving it to the main section since it wasn't introduced in v2.5.0
- Fix two PRs links that were pointing to a wrong PR number
N/A
N/A
**Checklist**
=> Fix compactor_address related CHANGELOG entries

docs/sources/operations/storage/logs-deletion.md
The `deletion_enabled` setting was renamed to `deletion_mode` some time ago. The documentation still mentioned the old name.
**Checklist**
=> Change deletion_enabled setting to deletion_mode

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/table.go, pkg/storage/stores/indexshipper/downloads/table_manager.go, pkg/storage/stores/indexshipper/downloads/table_test.go, pkg/storage/stores/indexshipper/uploads/table_manager.go
A couple of fixes/improvements have been made in `boltdb-shipper`, which have not made their way to `index-shipper`.
This PR adds them before I start making `boltdb-shipper` client use `index-shipper`.
=> copy all the fixes/improvements that went into boltdb-shipper that are missing from generic index-shipper

pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go
This simplifies our TSDB WAL replay to build a single TSDB rather than a TSDB per rotation period (15m) on restart. It also fixes a bug during replay where the WALs for a new rotation period didn't include the series reference (likely in a previous period).
It also builds TSDBs during replay with un-rounded timestamps to avoid clobbering in the case of multiple replays (crashlooping) in the same rotation period (15m)
=> creates a single tsdb for entire wal recovery

docs/sources/configuration/_index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/limits.go, pkg/distributor/validator.go, pkg/validation/limits.go
"Fudge" is slang, so before this configuration variable becomes part of a Loki release, we're changing the name. The configuration parameter was introduced in https://github.com/grafana/loki/pull/6042.
**Checklist**
- [X ] Documentation updated
- [X ] Tests updated
=> Rename fudge_duplicate_timestamp to be increment_duplicate_timestamp

docs/sources/storage/_index.md
Our example configs are bit misleading here. Particularly AWS deployment.
https://grafana.com/docs/loki/latest/storage/#examples
As a new user, I come here and all I can conclude is, we cannot use s3 as a single store under AWS deployment. Doc seems to recommend AWS deployment always  needs S3 + DynamoDB.
(in fact it was real confusion for new user from the community)
https://grafana.slack.com/archives/CEPJRLQNL/p1652867888720979
**Checklist**
=> doc(storage-example-configs): AWS single store configs

docs/sources/clients/promtail/stages/pack.md, docs/sources/logql/log_queries.md
=> docs: Fix broken link from unpack parser to pack stage

pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go
This fixes a bug in query planning which didn't check if the child-expressions of `avg` were shardable, which led to some `unimplemented` errors on the frontend. It's pretty unlikely to run into this (i.e. `avg(avg_over_time({job=~"myapps.*"} |= "stats" | json busy="utilization" | unwrap busy [5m]))`).
I've run this in a dev cluster as well, everything looking :+1: .
In the future, we can consider mapping `avg_over_time` -> `sum_over_time / count_over_time` :thinking: 
Closes https://github.com/grafana/loki/issues/6202
=> prevents sharding avg and avg_over_time for unshardable children

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
We do local store queries from ingester when running `boltdb-shipper` to include recently flushed data that queriers/index-gateway might not have synced yet. This PR makes it work for `tsdb` index store as well, without which we will see gaps in data due to missing out on recently flushed logs.
**Checklist**
=> run store queries in ingester when using tsdb as index store

docs/sources/api/_index.md
this pull-request describes the ordering of results when using `/query` and `/query_range` HTTP endpoints.
it is important to know whether one can rely on the results being ordered or not (for example, in the grafana loki datasource, if we cannot rely on the ordering of results, we have to sort the data)
NOTE: i do not know if what i described here is guaranteed or not. i made some tests, and it seems to work this way. it would be great if a Loki developer could also verify this info. (if it is not guaranteed, i can update the pull-request so that the docs will mention that the ordering is not guaranteed)
also, there was an error in the query-range-matrix-results format description, i fixed that.
=> docs: describe ordering in http query results

docs/sources/operations/observability.md
Add warning about potential high cardinality metrics due to the file path being included in some of the metrics. 
Depending on the setup, such config can result in a very large amount of label values, which is not recommended by Prometheus.
This can result in increased storage, slow down of queries, extra costs and so on.
Address what has been discussed in #5553.
Fixes #5553
**Checklist**
=> Docs: Hint about potential high cardinality metrics

pkg/logql/log/fmt.go, pkg/logql/log/fmt_test.go, pkg/logql/log/label_filter_test.go, pkg/logql/log/labels.go, pkg/logql/log/labels_test.go, pkg/logql/log/parser_test.go
This does two things:
- Introduce a buffer for computing labels and the buffer is only copied if we never seen that label set before.
- Add a Map function to the label builders used for `label_format` and `line_format` that avoids slice allocations and sorting.
```
❯ benchstat before.txt after.txt
name                                 old time/op    new time/op    delta
_Pipeline/pipeline_bytes-16            10.6µs ± 0%     6.9µs ± 1%  -34.85%  (p=0.008 n=5+5)
_Pipeline/pipeline_string-16           10.6µs ± 0%     6.9µs ± 0%  -35.16%  (p=0.008 n=5+5)
_Pipeline/line_extractor_bytes-16      10.6µs ± 0%     6.9µs ± 1%  -34.98%  (p=0.008 n=5+5)
_Pipeline/line_extractor_string-16     10.7µs ± 1%     6.9µs ± 0%  -35.27%  (p=0.016 n=5+4)
_Pipeline/label_extractor_bytes-16     10.7µs ± 1% …
```
=> Improve labels computation during LogQL pipeline

integration/loki_micro_services_test.go, integration/loki_single_binary_test.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/series/series_store_test.go, pkg/storage/stores/series/series_store_utils.go
`__name__` wasn't being being applied to `Label` calls when it's not meaningful for user. This PR always filters `__name__` from Label calls.
=> Remove __name__ from label calls

pkg/loki/modules.go, pkg/loki/modules_test.go, pkg/storage/config/schema_config.go
This adds the few missing pieces of multi KV runtime reloadable config to loki components that use the ring, based on Peters mimir PR [here](https://github.com/grafana/mimir/issues/996). Note that a lot of config was necessary to get the test to pass (many loki components will fail to start/be registered via the modules setup without things like storage config).
cc @JordanRushing @DylanGuedes @pstibrany
=> Runtime reloadable config; ring migration setup

Makefile, cmd/migrate/README.md, cmd/migrate/main.go, cmd/migrate/main_test.go
I dusted off the migrate tool and used it to move some old Loki data from one of my Raspberry Pi's using boltdb/filesystem to boltdb-shipper/S3 including a schema update.
This is the set of changes needed to make that work as well as some improvements to how the output and progress logging are handled.
Also updated the docs a little.
**Checklist**
=> Migrate Tool: Update to work with boltdb-shipper, improve logging output.

docs/sources/operations/troubleshooting.md
After PR 5649 submission and before approval, the directory structure of the docs changed, making a merge of https://github.com/grafana/loki/pull/5649 impossible without a rework.
This PR is the work of @gmintoco. I've put in substantial edits on the original prose from PR 5649.
=> Docs: Reimplement PR 5649 on troubleshooting timeout errors

pkg/storage/chunk/cache/fifo_cache.go, pkg/storage/chunk/cache/redis_cache.go
Currently we see following message when any of the experimental feature is used for cache (say fifocache or redis).
But the problem it doesn't say __what_kind_ of cache is it exactly.
```
caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache"
caller=experimental.go:20 msg="experimental feature in use" feature="Redis cache"
```
So this leads to confusion to track what kind of cache is the source of the experiment feature.
one such example is from the community.
https://github.com/grafana/loki/issues/6201#issuecomment-1133941794
This PR fixes it by adding more clear message.
```
caller=experimental.go:20 msg="experimental feature in use" feature="Redis cache - chunksredis"
caller=experimental.go:20 …
```
=> chore(cache): Make exprimental messages more clear for cache.

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
In https://github.com/grafana/loki/pull/6254 I'm proposing to publish a compiled version of the mixin. To make it run in CI, we need to add some jsonnet tools to build image, which is what I'm doing in this PR. I've bumped the build image minor version (from `0.20` to `0.21`) because I guess you follow semver.
N/A
Changes have been tested in https://github.com/grafana/loki/pull/6254
**Checklist**
=> Add jsonnet tools to build image

docs/sources/installation/simple-scalable-helm.md
Loki gateway service port is set to 80 by default and not 3100.
**Checklist**
=> docs: Default loki gateway service port.

production/ksonnet/loki/boltdb_shipper.libsonnet, production/ksonnet/loki/distributor.libsonnet, production/ksonnet/loki/index-gateway.libsonnet, production/ksonnet/loki/ingester.libsonnet, production/ksonnet/loki/memberlist.libsonnet, production/ksonnet/loki/query-scheduler.libsonnet, production/ksonnet/loki/ruler.libsonnet
Adds memberlist.libsonnet and modify loki services so we can set the port when using memberlist for the ring.
based on the memberlist jsonnet code written by @pstibrany for mimir, the main change is how the memberlist config values are set for services; mimir team uses cli flags while we use the config file
cc @JordanRushing @vlad-diachenko 
=> Memberlist related jsonnet

docs/sources/configuration/_index.md, docs/sources/storage/_index.md, go.mod, pkg/loki/config_wrapper_test.go, pkg/storage/bucket/azure/config.go, pkg/storage/bucket/azure/config_test.go, pkg/storage/chunk/client/azure/blob_storage_client.go
This PR adds support for authenticating to an Azure storage account via a user defined identity and is based on the Thanos implementation.
This PR also tidies up the existing code for Azure storage account and makes the documentation easier to understand.
Fixes #5710.
I haven't tested this in Azure yet as I'd like a review in principal first.
**Checklist**
=> Add support for Azure storage account user assigned identity

.drone/drone.jsonnet, .drone/drone.yml
This week we are building release `k100` but the images have not been pushed automatically since the branch name matcher is set to `k??` which means only 2 characters after prefix `k` would match. This PR updates the drone config to look for 3 letters after prefix `k`.
Since drone only supports glob for pattern matching which is not as feature right as regex we can't have a pattern matching variable lengths. See https://discourse.drone.io/t/extended-glob-patterns/7047
I think this is good enough for now and we will have ~2.5 years before we need to update this again :D
=> update drone branch match for 3 digit k release

operator/docs/howto_connect_grafana.md, operator/hack/addon_grafana_gateway_ocp.yaml, operator/hack/addon_grafana_gateway_ocp_oauth.yaml
This adds some documentation on how to set up Grafana to be able to talk to the LokiStack gateway managed by loki-operator. The document's main focus is OpenShift, because the tenancy model is defined there and the example configurations make use of functionality not available in vanilla Kubernetes, but the configuration should be adaptable to different use-cases.
**Checklist**
=> operator: Document how to connect Grafana to gateway

docs/sources/logql/log_queries.md
The last sentence was saying the opposite of what it meant.
Also fix 'start' to match singluar 'expression'.
=> Docs: Fix wording about pattern parser

docs/sources/clients/promtail/configuration.md, docs/sources/clients/promtail/stages/regex.md
When I was configuring Promtail to use a regex stage I escaped slashes in regular expressions when using double quotes in yaml files. But no where did it explain that when using the option `--config.expand-env=true` the program `envsubst` would replace double slashes with slashes. I found the issue #3635 to find out this is behavior as expected. While I accept this, I thought it would be useful to warn the next person about just this case.
Adds two paragraphs to the Promtail configuration docs:
- in `docs/sources/clients/promtail/configuration.md`: use double slashes for single slashes when using `expand-env=true`
- in `docs/sources/clients/promtail/stages/regex.md`: explained again as it's more likely to use back slashes in regex
**Which issue(s) …
=> Documentation: Explain --config.expand-env=true double slash with slash substitution

pkg/loki/modules.go, pkg/storage/factory.go, pkg/storage/store.go
We were temporarily using `boltdb-shipper` config for initializing the index gateway client. This PR fixes it by doing relevant updates.
=> use tsdb config for initializing index gateway client

docs/sources/clients/k6/log-generation.md
Support for `logfmt` log format has been merged into `main` with https://github.com/grafana/xk6-loki/commit/717a1332b4bff56e1e822527d0eca78bd76f2176
**Checklist**
=> Update docs for xk6-loki log formats

pkg/storage/stores/indexshipper/downloads/metrics.go, pkg/storage/stores/indexshipper/downloads/table.go, pkg/storage/stores/indexshipper/downloads/table_manager.go, pkg/storage/stores/indexshipper/downloads/table_manager_test.go, pkg/storage/stores/indexshipper/downloads/table_test.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/indexshipper/uploads/metrics.go, pkg/storage/stores/indexshipper/uploads/table_manager.go, pkg/storage/stores/indexshipper/uploads/table_manager_test.go, pkg/storage/stores/shipper/shipper_index_client.go, pkg/storage/stores/tsdb/store.go
In PR #6226, we refactored the code to make the `boltdb-shipper` index client use the generic `indexshipper` to manage the index on object storage. This PR takes care of follow up action to add metrics to `indexshipper`.
I have made sure we have the same metrics exposed as before by using `WrapRegistererWithPrefix`, i.e. when using `indexshipper` for `boltdb-shipper`, metrics would be prefixed with `loki_boltdb_shipper_` while for `tsdb`, the prefix would be `loki_tsdb_shipper_`
=> add metrics for tracking index shipper operations

.github/workflows/snyk.yml
What this PR does / why we need it:
This PR adds a short GH Action to generate and upload SBOM reports via Snyk.
Fixes #
Special notes for your reviewer:
FYSA @grafana/security-team
=> Snyk SBOM workflow add

pkg/ingester/flush.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/metrics.go, pkg/ingester/recovery.go, pkg/ingester/stream.go
This moves global metrics into the dedicated ingester metrics struct
=> ingester: Refactor ingester metrics from globals into the ingesterMetrics struct

pkg/storage/stores/shipper/compactor/compactor.go
There are a few use cases for running the compactor intentionally to allow it to process and cleanup existing uploaded index files, primarily I'd like it in this case to cleanup after using the [migrate tool](https://github.com/grafana/loki/tree/main/cmd/migrate)
This PR adds a new flag and some code to execute the compaction cycle exactly once, it also intentionally does not do any retention related work.
=> Loki: add a run-once flag to the compactor

CHANGELOG.md, clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb, clients/cmd/fluentd/spec/gems/fluent/plugin/loki_output_spec.rb, docs/sources/clients/fluentd/_index.md
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
This PR allows the `fluentd_thread` label included when multi-threading flushing is enabled to be configurable. The label will be included by default in order to preserve backwards compatibility.
Fixes #5336
**Checklist**
=> feat(fluentd): allow fluentd_thread label to be configurable

pkg/storage/config/schema_config.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go, pkg/storage/stores/tsdb/index_client.go, pkg/storage/stores/tsdb/index_shipper_querier.go, pkg/storage/stores/tsdb/manager.go, pkg/storage/stores/tsdb/store.go
Currently, if we have multiple schema configs with `tsdb` as index store, we will create multiple store instances.
This would cause a problem since we maintain a state on the local disk and the code is not meant to run multiple instances.
Since we do not do any schema specific operations in `tsdb` and running multiple instances would be complex and wasteful, this PR changes the code to make `tsdb` index store instance a singleton. If we do need to do schema specific handling in future, it would be a good idea to abstract away the handling of different schemas.
I have also done the following changes:
* Refactored the code a bit to avoid initializing tsdb and head manager when running `tsdb` store in read-only mode.
* Make it mandatory to configure …
=> make tsdb store instance a singleton

production/ksonnet/loki/memberlist.libsonnet
We shouldn't modify the loki config at all if the memberlist ring is not enabled.
=> [jsonnet] don't modify config if memberlist not enabled

production/loki-mixin/dashboards/loki-writes.libsonnet
Last week while on-call I realize that the latency was high in distributor but in fact it was another route (profiling) being slow. This attempts to improve the write dashboard by only including potential writes endpoint.
Not sure if the jsonnet will be correct 🤷  There's might be a clash of recording rules.
**Checklist**
=> Improve write dashboard by removing unrelated route

pkg/logql/log/fmt.go, pkg/logql/log/pipeline.go, pkg/logql/syntax/parser_test.go
This mostly remove an allocation for each `line_format` specially useful when the result is not used and copied.
This was a todo that was left for a long time.
```
❯ benchstat beforemetric.txt aftermetric.txt
name                        old time/op    new time/op    delta
_MetricPipelineCombined-16    4.94µs ± 1%    4.86µs ± 1%  -1.50%  (p=0.008 n=5+5)
name                        old alloc/op   new alloc/op   delta
_MetricPipelineCombined-16    2.49kB ± 0%    2.42kB ± 0%  -2.63%  (p=0.008 n=5+5)
name                        old allocs/op  new allocs/op  delta
_MetricPipelineCombined-16      33.0 ± 0%      31.0 ± 0%  -6.06%  (p=0.008 n=5+5)
❯ benchstat beforelog.txt afterlog.txt      
name                  old time/op    new time/op    delta
_PipelineCombined-16    4.94µs ± 2%    4.87µs ± …
```
=> Avoid line copy during LogQL line_format

pkg/distributor/validator.go, pkg/validation/validate.go
As part of the work to better understand line length limits in Loki, this adds a new histogram for them so we can better understand distributions of line lengths coming in.
Also fixes some metric instantiations that were missed in the `init` function by preferring `promauto`.
=> exposes line length hist on distributors 

pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager_test.go
Before, we considered any interval to potentially have an expired chunk if the passed userID matched a user on a DeleteRequest. This PR adds the requirement that an interval must also overlap a delete request to count as having a potential expired chunk.
=> Only consider an interval to have possible expired chunks if it overlaps a delete.

production/ksonnet/loki/memberlist.libsonnet
k100 release was changed and some changes were merged only to k100, so we need to merge it main also.
=> K100 back merge to main

production/ksonnet/loki/memberlist.libsonnet
if we enable memberlist using the logic from memberlist.libsonnet , the pods are crushed because Loki expects numeric value but it gets string value.
=> fixed type of the property in memberlist config

pkg/storage/stores/shipper/compactor/compactor.go
The cancellation time period for the delete api was hardcoded to an hour. This PR sets it to the configured `delete_request_cancel_period`.
Also refactors the delete initialization into it's own method.
=> Fix delete cancellation timeout

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/index_set_test.go, pkg/storage/stores/indexshipper/downloads/table.go, pkg/storage/stores/indexshipper/downloads/table_test.go
I somehow missed porting changes to generic `indexshipper` from `boltdb-shipper` cache changes done in PR https://github.com/grafana/loki/pull/6054. This PR takes care of it.
I have also changed the code to drop broken index set earlier instead of just doing it at query time.
**Checklist**
=> copy boltdb-shipper cache changes from PR #6054 to generic index shipper

pkg/storage/chunk/client/gcp/fixtures.go
Allows the storage tests to pass when building loki 2.5.0 for Arch Linux.
Fixes #6185
Please double check that this only affects tests and doesn't have any unintentional side effects.
**Checklist**
- [N/A] Documentation added
- [N/A] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [N/A] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> Use fake credentials in storage/chunk/storage tests

integration/client/client.go, integration/cluster/cluster.go, integration/loki_micro_services_delete_test.go, integration/parse_metrics.go, integration/parse_metrics_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_request.go, pkg/storage/stores/shipper/compactor/deletion/delete_request_test.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/deletion/metrics.go
Update the deletion integration test so it waits until the delete request has been processed. Note that at the moment no lines are removed due to flush not working. This will be fixed later on in a separate PR.
Add a metric to show how many lines are deleted.
Remove mention of Cortex in a helper function.
Change the various timeouts so the test runs in 10 seconds.
Add code to parse and check metrics.
**Checklist**
=> Update delete integration test

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/index_set_test.go, pkg/storage/stores/indexshipper/downloads/table.go
From `indexshipper`, we detect and retry failed sync due to a stale index list cache. However, it is not done in all cases like query readiness or syncing local files on startup, which causes some unexpected problems. This PR updates the code to always refresh the stale list cache and retry sync to keep it consistent.
To keep the code simple, I have made the code retry sync in all failure cases and not just the stale index list cache.
**Checklist**
=> always retry syncing index files from indexshipper when the index list cache is stale

production/ksonnet/loki/overrides.libsonnet
This PR backports required Jsonnet changes to `production/ksonnet/loki/overrides.libsonnet` in k100 to support adding a `multi_kv_config` block to our overrides ConfigMap for use when migration from Consul to Memberlist.
N/A
N/A
**Checklist**
=> Backport Memberlist migration `multi_kv_config` ConfigMap changes to k100

production/ksonnet/loki/overrides.libsonnet
This PR backports required Jsonnet changes to `production/ksonnet/loki/overrides.libsonnet` in k101 to support adding a `multi_kv_config` block to our overrides ConfigMap for use when migration from Consul to Memberlist.
N/A
N/A
**Checklist**
=> Backport Memberlist migration `multi_kv_config` ConfigMap changes to k101
