production/ksonnet/loki/overrides.libsonnet
This PR adds a correctly-nested `multi_kv_config` block to the overrides configmap when multi kv mode is enabled to support a migration between Consul and Memberlist.
- #6320
- #6321
N/A
N/A
**Checklist**
=> Add `multi_kv_config` block to overrides ConfigMap when multi-kv mode is enabled

docs/sources/clients/_index.md
I would like to add mjaron-tinyloki-java to unofficial Loki clients.
It is standalone small library without any dependencies. It may be an alternative to other libraries which use many dependencies and require more configuration to send logs.
**Checklist**
=> Update _index.md - an unofficial Loki client added

pkg/loki/modules.go
This PR backports a fix to the `MemberlistKV` module configurable `MetricsNamespace` to properly append `loki` to metric names.
Fixes #6331
N/A
N/A
**Checklist**
=> Backport `MemberlistKV.MetricsNamespace` loki change to k100

pkg/storage/chunk/cache/fifo_cache.go, pkg/storage/chunk/cache/fifo_cache_test.go
This PR adds an eviction reason for the fifocache, which will help an operator know if an entry was evicted because the TTL expired vs the cache is full.
N/A
We use a fifocache when running boltdb-shipper for storing ingesters' index caches locally. We do this because we cannot share the cache between ingesters, to prevent missing out chunks that may not exist in other ingesters.
https://github.com/grafana/loki/blob/main/pkg/loki/modules.go#L414-L425
The cache is configured with a fixed size of 200MB, and is currently not configurable; we could consider making this configurable however even in our biggest clusters we're …
=> Define a reason why the fifocache has evicted an item

CHANGELOG.md
PR https://github.com/grafana/loki/pull/6120 renamed a configuration parameter.  I forgot to include a changelog entry with that PR.  This PR adds that changelog entry.
=> Docs: Add changelog entry for configuration parameter name change

pkg/loki/loki.go, pkg/loki/modules.go
re: https://github.com/grafana/loki/pull/6322
N/A
N/A
**Checklist**
=> Backport Memberlist status page in k101

pkg/logql/rangemapper.go, pkg/logql/rangemapper_test.go, pkg/logql/syntax/ast.go
The original panic was not useful, the change to the `clone` function and it's usage will ensure that in future cases we at least get an error message along with the panic stack trace. This PR also calls the `validate` function on the modified range query to ensure it's still allowed. In the case of the panic we saw, `unwrap` is not allowed with `count_over_time`, when in the original query we had `rate` with `unwrap` which is allowed.
=> [logql] don't try to execute a modified function that is not allowed by the AST

pkg/logql/engine_test.go
This PR fixes a test. Before the PR, the `TestEngine_MaxSeries` test `return`s after the first test and prevents the other tests from running.
Fixes #: N/A
Adding `t.Run` allows using the `return`, but I went ahead and also removed the `return` and added an `else` to make it more clear. This would have prevented this and may protect against future moves/refactors.
**Checklist**
=> Fix max series test loop that returns early

pkg/logql/engine.go, pkg/querier/http.go
Support `series|labels` query_type in `logql_query_duration` histogram metric.
So that you can do quantile calculation on metadata queries.
Fixes #NA
**Checklist**
=> Support `series|labels` query_type in `logql_query_duration`

CHANGELOG.md, cmd/loki-canary/main.go, pkg/canary/reader/reader.go
Support for loki-canary in environments using mTLS, in anticipation of deny-by-default Loki server authentication coming for #6283.
Fixes #6295 
**Checklist**
=> loki-canary: Add support for client-side TLS certs for Loki connection

clients/cmd/fluentd/.rubocop.yml, clients/cmd/fluentd/docker/Gemfile, clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec, clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb, clients/cmd/fluentd/spec/gems/fluent/plugin/loki_output_spec.rb
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
Resolves all of the Rubocop linting failures for the fluentd plugin.
**Checklist**
=> chore(fluentd): resolve rubocop failures

operator/CHANGELOG.md, operator/hack/addons_ocp.yaml, operator/hack/lokistack_gateway_ocp.yaml, operator/internal/manifests/build_test.go, operator/internal/manifests/gateway.go, operator/internal/manifests/gateway_tenants.go, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/openshift/configure.go, operator/internal/manifests/openshift/opa_openshift.go, operator/internal/manifests/openshift/route.go, operator/internal/manifests/var.go
This PR configures LokiStack gateway to exclusively use the HTTPS protocol when using the openshift-logging mode. In addition, traffic to the gateway k8s service is re-encrypted using a reencrypt termination policy while using the openshift-logging mode.
**Checklist**
=> operator: Expose only an HTTPS gateway when in openshift-logging mode

operator/CHANGELOG.md, operator/api/v1beta1/lokistack_types.go, operator/bundle/manifests/loki.grafana.com_lokistacks.yaml, operator/config/crd/bases/loki.grafana.com_lokistacks.yaml, operator/internal/handlers/internal/gateway/tenant_secrets.go, operator/internal/handlers/internal/gateway/tenant_secrets_test.go, operator/internal/manifests/internal/gateway/gateway-tenants.yaml
The present `LokiStack` CR kubebuilder annotations disallow using the gateway OIDC flow by only providing a `clientID` and `issuerURL` in the secret. This makes use cases like using [token-refresher](https://github.com/observatorium/token-refresher) that forwards a valid IDToken impossible.
**Checklist**
=> operator: Allow reduced tenant OIDC authentication requirements

operator/CHANGELOG.md, operator/config/overlays/development/kustomization.yaml, operator/config/overlays/development/manager_run_flags_patch.yaml, operator/main.go
Using webhooks for `AlertingRule` and `RecordingRule` requires TLS by default and we cannot use this with kind on local development yet.
**Checklist**
=> operator: Allow optional installation of webhooks

pkg/storage/stores/indexshipper/downloads/table_manager.go
Log unique users assigned to a queryReadiness call. This will help to understand the correlation between more or fewer users and indexgateway load.
N/A
N/A
**Checklist**
=> Loki: Log # of unique users involved in query readiness operation

cmd/loki/main.go
Consider this PR as a refactor.
**Checklist**
=> cmd/loki: minor consistency patch

CHANGELOG.md, clients/cmd/promtail/promtail-journal.yaml, clients/pkg/promtail/targets/journal/journaltarget.go, clients/pkg/promtail/targets/journal/journaltarget_test.go, clients/pkg/promtail/targets/journal/journaltargetmanager.go, clients/pkg/promtail/targets/journal/journaltargetmanager_linux.go, clients/pkg/promtail/targets/journal/metrics.go, clients/pkg/promtail/targets/manager.go
There are no metrics for the journal target yet, this adds two basic ones:
- Total number of lines processed
- Total number of errors processing lines (with a reason in a label)
Because of the way the journal works, tailing one file with many possible processes writing to it, I chose note to expose counts per unit.
Fixes #5554
Doing this PR mostly to learn, not because I really need this feature. So all feedback/opinions are welcome!
I looked at the other targets and did not see any tests for the metrics produced/no pattern to copy here, but I'd be happy to figure out how to add them if requested. 
**Checklist**
=> Promtail: Add metrics for journal target

docs/sources/configuration/_index.md, pkg/storage/chunk/client/gcp/gcs_object_client.go
Add `service_account` option to configure GCS directly using service account key.
This will change the situation which have to use JSON file and `GOOGLE_APPLICATION_CREDENTIALS` env for service account (such as [#932](https://github.com/grafana/loki/issues/932#issuecomment-839846952) and #6125).
**Checklist**
=> GCS: Add service_account option

pkg/loki/modules.go
This route was missing so cache invalidation was always failing.
=> Add compactor route for the cache gen number api

CHANGELOG.md, docs/sources/configuration/_index.md, go.mod, pkg/ruler/compat.go, pkg/ruler/registry.go, pkg/ruler/registry_test.go, pkg/validation/limits.go, pkg/validation/limits_test.go
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
Fixes an issue that prevented the sigv4 authentication configuration from being set during the resolution of the per tenant overrides. This fixes the issue by allowing the global value to be properly propagated as well as enables setting the sigv4 authentication on a per tenant basis. 
Fixes #6293
N/A
**Checklist**
=> fix(loki): allow global and per tenant sigv4 config

production/loki-mixin/config.libsonnet, production/loki-mixin/dashboards/dashboard-utils.libsonnet, production/loki-mixin/dashboards/loki-chunks.libsonnet, production/loki-mixin/dashboards/loki-logs.libsonnet, production/loki-mixin/dashboards/loki-operational.libsonnet, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet, production/promtail-mixin/jsonnetfile.json
Reverts grafana/loki#6353
@hervenicol Reverting the PR, because it breaks the `main` branch. (it passed on your original branch, but suspect that CI may be bit flaky. But when tried in local `make lint-jsonnet` it fails as well)
```
Linting ./production/promtail-mixin/mixin.libsonnet
RUNTIME ERROR: Field does not exist: per_cluster_label
production/promtail-mixin/vendor/loki-mixin/dashboards/dashboard-utils.libsonnet:34:58-85	thunk from <function <anonymous>>
production/promtail-mixin/vendor/grafana-builder/grafana.libsonnet:31:57-67	thunk from <object <anonymous>>
<std>:715:15-22	thunk <val> from <function <format_codes_arr>>
<std>:722:27-30	thunk from <thunk <s> from <function <format_codes_arr>>>
<std>:592:22-25	thunk from <function <format_code>>
<std>:592:9-26	function <format_code> …
```
=> Revert "Loki Prometheus mixin: templatize cluster label"

CHANGELOG.md, pkg/logql/optimize.go, pkg/logql/optimize_test.go
This PR implements a naïve fix for the bug listed below.
Fixes #6314
The more correct way will be to unify the `JSONExpressionParser` and `LabelParserExpr`.
```golang
func (e *LabelParserExpr) Stage() (log.Stage, error) {
switch e.Op {
case OpParserTypeJSON:
return log.NewJSONParser(), nil
case OpParserTypeLogfmt:
return log.NewLogfmtParser(), nil
case OpParserTypeRegexp:
return log.NewRegexpParser(e.Param)
case OpParserTypeUnpack:
return log.NewUnpackParser(), nil
case OpParserTypePattern:
return log.NewPatternParser(e.Param)
default:
return nil, fmt.Errorf("unknown parser operator: %s", e.Op)
}
}
```
Ultimately the …
=> Naïve fix for optimize bug with `line_format` and `json` expression parser

pkg/loki/modules.go, pkg/querier/querier.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_client.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_client_test.go, pkg/storage/stores/shipper/compactor/deletion/metrics.go
To avoid showing deleted data, the querier originally failed when deletes were unavailable. If the compactor becomes unavailable this can cause loki to stop responding to queries altogether. This PR changes the querier to log an error but continue servicing the request when it fails to get deletes.
It also adds metrics to the `delete_requests_client` so we can alert when there is a chronic failure to get delete requests.
=> Don't interrupt the query path if deletes aren't available

pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager_test.go
An incorrect counter was used when deleting lines. A test to check the counter is added as well.
**Checklist**
=> Deletion: use correct counter when deleting lines

operator/Makefile, operator/config/rbac/role.yaml, operator/config/rbac/role_binding.yaml
The ClusterRole and ClusterRoleBinding are global resources.
The former names "manager-role" and "manager-rolebinding" may clash.
Renamed both to "lokistack-manager".
- incudes lokistack prefix for uniqueness.
- dropped "-role" and "-rolebinding" suffix to follow common usage.
=> Add lokistack prefix to role and rolebinding names.

production/loki-mixin-compiled/dashboards/loki-deletion.json, production/loki-mixin/dashboards/loki-deletion.libsonnet
This adds a panel for deleted lines to the Deletion dashboard. The new delete functionality has a counter for the deleted lines.
**Checklist**
=> Add deleted lines panel to deletion dashboard

pkg/storage/stores/shipper/compactor/deletion/delete_request.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager.go
Add more logging for the delete requests.
**Checklist**
=> Add more logging for delete requests

.gitignore
I noticed that after running `make test` the directory pkg/loki/wal is
created which a bunch of files and data.
I think it would be a good idea to ignore the entire directory with git.
=> Git ignore pkg/loki/wal

CHANGELOG.md, pkg/querier/querier.go
This executes label queries against ingesters and store in parallel, rather than sequentially.
**Checklist**
~- [ ] Documentation added~
=> Parallize label queries to both stores

pkg/logql/downstream.go, pkg/logql/downstream_test.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/ast_test.go, pkg/logql/test_utils.go, pkg/querier/queryrange/downstreamer.go, pkg/querier/queryrange/downstreamer_test.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/shard_resolver.go, pkg/querier/queryrange/shard_resolver_test.go, pkg/querier/queryrange/split_by_range.go, pkg/storage/stores/shipper/indexgateway/indexgatewaypb/compat.go, pkg/storage/stores/tsdb/chunkwriter.go
This adds some rudimentary request based sharding logic which will choose shard factor based on the amount of bytes in the query and the tenant's max parallelism.
=> [TSDB] Use index sampling to determine shard factor

go.mod, go.sum, vendor/github.com/hashicorp/memberlist/net.go, vendor/github.com/hashicorp/memberlist/state.go, vendor/github.com/hashicorp/memberlist/util.go, vendor/modules.txt
Use a replace directive to ensure we're using the same version of memberlist as mimir/dskit. The memberlist adjacent issues we have seen this week could be a result of using a new version of dskit but without the forked version of memberlist.
cc @JordanRushing @vlad-diachenko @owen-d @slim-bean 
=> [modules] pin version of memberlist

pkg/logql/log/util.go, pkg/logql/log/util_test.go
It was always 0 before and then appending, but in fact we wanted to have a pre-allocated size of `len(s)`.
=> Fixes bad initialization for uniqueString

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/operations/storage/logs-deletion.md, integration/loki_micro_services_delete_test.go, pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/deletion/request_handler.go, pkg/storage/stores/shipper/compactor/deletion/request_handler_test.go, pkg/util/validation/limits.go, pkg/validation/limits.go
This PR adds a per tenant compaction delete enabled flag called `compactor_deletion_enabled`. A unit test was added for the http middleware that checks access.
This was also manually tested. The following snippet was added in the Loki config file:
``` yaml
limits_config:
compactor_deletion_enabled: false
```
The runtime config contained the following:
``` yaml
overrides:
tenant1:
compactor_deletion_enabled: true
tenant2:
compactor_deletion_enabled: false
```
Running curl commands against the API gives the expected results: 
``` sh
% curl  http://localhost:3100/loki/api/v1/delete
no org id
% curl -H "X-Scope-OrgID: tenant1"  http://localhost:3100/loki/api/v1/delete
[]
% curl -H …
```
=> Compactor: add per tenant compaction delete enabled flag

CHANGELOG.md, docs/sources/upgrading/_index.md, production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/querier.libsonnet
Currently, queriers run on different nodes. We do this by using the following anti-affinity rule:
```yaml
affinity:
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchLabels:
name: querier
topologyKey: kubernetes.io/hostname
```
The original reasoning behind this is to make our systems more resilient to node failures. For example, if we have 5 queriers, all scheduled in the same node, and the node fails, we would not be able to serve queries until the pods get rescheduled and running on another node.
When new queriers are created, they need to be scheduled into different nodes. If there are not enough nodes in the cluster, new nodes need to be provisioned. This has two implications:
- Cost: Each node has an …
=> Evenly spread queriers across available nodes

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/loki/modules.go, pkg/lokifrontend/config.go
This PR adds TLS configuration parameters to query frontend. Without this, the live tailing on Openshift cluster cannot work.
Fixes #5743 
This PR is needed for this operator fix PR #6443 
**Checklist**
=> Add TLS config to query frontend

operator/quickstart.sh
The CI is currently failing due to shellcheck errors in operator/quickstart.sh. This PR adds disable directives so it doesn't error anymore.
**Checklist**
=> operator: Add shellcheck disables

pkg/loki/modules.go
This fix a bug where the IndexGateway service of a read component won't be able to attend any queries for not having the ring available; the ring wouldn't be available because the RingManager would be in client mode since the target isn't the index-gateway. 
N/A
N/A
**Checklist**
=> Set RingManager mode as Server if target=read

pkg/loki/modules.go
This PR forces Loki to not use the IndexGatewayClient when running with target=read. Without this, the read mode ends up using an IndexGatewayClient to resolve index queries; however, as IndexGatewayClient doesn't support resolving these queries, any query ends up hanging forever.
N/A
**Checklist**
=> Loki: Use Shipper as indexClient for read mode

pkg/logql/downstream_test.go, pkg/logql/rangemapper.go, pkg/logql/rangemapper_test.go
The range aggregation `rate()` supports both log ranges and unwrapped ranges, e.g.
`rate({app="foo"} [$__interval])` and `rate({app="foo"} | unwrap bar [$__interval])`
Since `rate()` was split into multiple `count_over_time()` over total duration, but `count_over_time()` does not support `unwrap`, unwrapped rate queries caused panics.
This fix changes the splitting of `rate({app="foo"} | unwrap bar [$__interval]` into multiple `sum_over_time()` over total duration.
Fixes #6344
**Checklist**
=> Fix panic in instant query splitting when using unwrapped rate

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/operations/storage/logs-deletion.md, integration/loki_micro_services_delete_test.go, pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_manager_test.go, pkg/storage/stores/shipper/compactor/deletion/mode.go, pkg/storage/stores/shipper/compactor/deletion/mode_test.go
The `whole stream deletion` mode is no longer required as the `filter-and-delete` mode can do the same and more.
**Checklist**
=> Remove whole stream deletion mode

production/promtail-mixin/alerts.libsonnet
We're going to remove the associated metric soon anyways and the alert is problematic as well.
=> [promtail/mixin] Remove promtail file lag alert

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/operations/storage/logs-deletion.md, integration/loki_micro_services_delete_test.go, pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/compactor.go, pkg/storage/stores/shipper/compactor/deletion/request_handler.go, pkg/storage/stores/shipper/compactor/deletion/request_handler_test.go, pkg/validation/limits.go
* Add per tenant compaction delete enabled flag
* Remove changes in wrong place
* Add compactor deletion enabled field
* Use limit in compactor
* Use http middleware and add test
* Fix lint issue
* Add changelog
* Revert to default setting if no override
* Add default value command line option
Signed-off-by: …
=> Compactor: add per tenant compaction delete enabled flag (#6410)

pkg/storage/stores/indexshipper/gatewayclient/gateway_client_test.go
This PR fixes a flaky test by deferring the stop of gRPC clients used. You can see an example of it failing [here](https://drone.grafana.net/grafana/loki/13014/2/5). 
N/A
N/A
**Checklist**
=> Loki: Fix flaky IndexGatewayClient test

CHANGELOG.md, docs/sources/upgrading/_index.md, pkg/loki/config_wrapper_test.go, pkg/loki/loki.go, pkg/loki/loki_test.go
I was suprised this was not already the case. I think it would be a good change to make, but I am also contious of the breaking nature of this.
=> Update loki's default port to 3100

cmd/logcli/main.go, pkg/logcli/client/client.go
Add `--proxy-url` flag to `logcli` to support connecting to Loki instances running behind either HTTP or HTTPS CONNECT-style proxies.
Examples:
http proxy:
```
logcli \
--addr="http://loki-distributed-querier.loki.svc.cluster.local.:3100/" \
--proxy-url "http://envoy.dom.tld" \
query '{app="foo"}'
```
https proxy with mTLS auth:
```
logcli \
--addr="https://loki-distributed-querier.loki.svc.cluster.local.:3100/" \
--proxy-url "https://envoy.dom.tld" \
--cert tls.crt \
--key tls.key \
--ca-cert ca.crt \
query '{app="foo"}'
```
Note that tail (`-f`) support and https proxies only work with a fork of the `gorilla/websocket` lib. There are open PRs that promise to add support for https proxies such as: https://github.com/gorilla/websocket/pull/740
Add the following to `go.mod` to use the fork …
=> logcli: add --proxy-url flag for http/https proxy support

pkg/storage/stores/indexshipper/downloads/table_manager.go
This PR modifies one of the query readiness log messages to also include how long it took to create a new table and for listing files. This will help debugging what are the slowest things of the query readiness operation.
N/A
N/A
**Checklist**
=> During query readiness, log duration of all object-store operations

pkg/loki/modules.go, pkg/loki/modules_test.go
Summary:
PR #6461 introduced a fix for the read target that was supposed to
disable the index gateway clients. However, `fallthrough` does not
behave as expected. Thus we are using a nested if statement here.
=> Disable index gateway client on read target.

MAINTAINERS.md
To be consistent with other OSS products, adding the maintainer of the technical documentation to the list of maintainers.
=> Updating maintainers.md

operator/CHANGELOG.md, operator/bundle/manifests/loki-operator-manager-config_v1_configmap.yaml, operator/config/overlays/openshift/controller_manager_config.yaml
This provides a fix introduced by #6433 as per usage report not always available on OpenShift clusters (e.g. air-gapped environments) and leaving it per default open spams the distributor logs when a custom S3 CA is used (e.g. OpenShift Data Foundation, Minio)
**Checklist**
=> operator: Disable report on overlay openshift

clients/pkg/promtail/targets/syslog/syslogtarget_test.go
We should create new certs to fix this, but in the meantime this is stopping every build so I'm just disabling the tests
=> Promtail: disable syslog tests which have expired certs

pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_client.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_client_test.go, pkg/storage/stores/shipper/compactor/deletion/metrics.go
The delete request counters do not differentiate between the clients. This PR adds a client type label.
**Checklist**
=> deletion: add client type as label

operator/CHANGELOG.md, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml
Changes the hardcoded list of (`eth0`) in the Loki Lifecycle `interface_names` config to use the upstream defaults, i.e. all private network interfaces. According to dskit:
```go
cfg.InfNames = netutil.PrivateNetworkInterfacesWithFallback([]string{"eth0", "en0"}, logger)
```
This enables out-of-the-box support for IPv6 kubernetes/OpenShift clusers.
**Checklist**
=> operator: Use default interface_names for lokistack clusters

pkg/querier/querier.go
To avoid showing deleted data, the querier originally failed when
deletes were unavailable. If the compactor becomes unavailable this can
cause Loki to stop responding to queries altogether. This PR changes the
querier to log an error but continue servicing the request when it fails
to get deletes.
E.g. when a tenant does not have deletions enabled, the compactor returns 403 (Forbidden) when listing the deletes on `GET /loki/api/v1/deletes`. https://github.com/grafana/loki/blob/k104/pkg/storage/stores/shipper/compactor/deletion/request_handler.go#L223-L233
Related PR #6368
**Checklist**
=> Do not fail queries if compactor returns unexpected status code

docs/sources/api/_index.md
This PR expands the curl examples given for the query API endpoint to include specifying a single tenant, multiple tenants, and gives the equivalent curl example, but for a GEL cluster.
Reviewers:
- Are the curl commands completely correct?
- Are there other API endpoints that should also have examples that specify tenants?
=> Docs: Add multi-tenant query curl examples

cmd/logcli/main.go, pkg/logcli/query/query.go, pkg/logcli/query/query_test.go
Add a flag to read a remote schema configs.
**Checklist**
=> logcli: add flag to read remote schema configs

pkg/querier/queryrange/shard_resolver.go
Extracting metrics for this has proven otherwise difficult because we don't have a `bytes` template and it's a bit inconvenient to add b/c the function returns an error signature.
=> log addtl info about bytes/shard in planning

tools/lambda-promtail/variables.tf
Signed-off-by: Conor Evans <coevans@tcd.ie>
Sets appropriate default values
Fixes #6451
=> fix(lambda-promtail): update default lambda_vpc_subnets / lambda_vpc_security_groups values to be appropriate empty list(string) value

cmd/loki-canary/main.go, pkg/canary/reader/reader.go
When running canary with client side certificates (introduced in #6310), a new `http.Transport` is being created for each request 🤦‍♂️. As a result, connections are left open until they timeout an hour later. This quickly causes resource exhaustion and errors like `dial tcp 1.1.1.1:1111: connect: cannot assign requested address`. 
This change will reuse the same transport for all requests just like `http.DefaultClient` is reused when not using client certs.
Tested by running loki-canary for 5 days and observing with netstat a constant number of TCP connections to the querier.
=> loki-canary: Fix resource leak when using client-side certs

.drone/drone.jsonnet, .drone/drone.yml
Currently, pipelines that should run in PRs are those that are configured to exclude the `main` or tag refs
However, pipelines are configured to run on PRs, tags and pushes. This means that, for branches in the main repo, not the fork, PRs run the same pipelines for the `pull_request` and `push` events
With this PR, the `push` run should no longer trigger on PRs
The change is:
1. Add a global pipeline trigger filter. Only trigger on the main, `k???` branches, `v*` tags or on PRs
2. When pipelines have steps that should only run on either PR or push/tag, they filter on the `event` in the step `when` condition
=> Drone: Do not run pipelines twice on PRs

pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/deletion/tenant_delete_requests_client.go, pkg/storage/stores/shipper/compactor/deletion/tenant_delete_requests_client_test.go
Originally, when deletes were disabled, the querier didn't make a request at all. This change emulates that and only makes delete requests for tenants who have deletes enabled.
=> Avoid making delete requests when deletes are disabled for a user

pkg/storage/chunk/cache/cache.go
Obsoleted by this PR: https://github.com/grafana/loki/pull/4891
=> Remove ourdated comment

.drone/drone.jsonnet, .drone/drone.yml, Makefile, operator/Dockerfile, operator/Dockerfile.cross
Follow-up PR on #6086 to use build context on root make targets and unblock `make oci-build` in `operator/` subfolder.
**Checklist**
=> operator: Use docker build context for root make targets

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml
I poorly rebased #6381 before merging and removed some commits. This PR adds them.
=> Fix release workflow

.github/workflows/publish-technical-documentation-release.yml
Will manually backport to `release-2.5.x` and `release-2.6.x`
=> Append .x to the versioned directories for the website sync

production/ksonnet/loki/boltdb_shipper.libsonnet, production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/distributor.libsonnet, production/ksonnet/loki/gateway.libsonnet, production/ksonnet/loki/index-gateway.libsonnet, production/ksonnet/loki/ingester.libsonnet, production/ksonnet/loki/memberlist.libsonnet, production/ksonnet/loki/overrides-exporter.libsonnet, production/ksonnet/loki/querier.libsonnet, production/ksonnet/loki/ruler.libsonnet, production/ksonnet/loki/table-manager.libsonnet
Adding this selector can result in outages caused by all write traffic being routed to only new distributors during initial migrations to memberlists, causing the few new distributors at the start of a rollout to be OOM killed.
cc @JordanRushing @vlad-diachenko @slim-bean 
=> Don't add the memberlist label as a selector to services.

pkg/storage/chunk/cache/groupcache.go, pkg/storage/chunk/cache/groupcache_test.go
We suspected that we were unnecessarily allocating memory for `Fetch` operations. This brings the allocs down a little but it turns out groupcache is pretty optimized as is.
```
Fetch hits
-------------------------------------------------------------------------------------------------------------------------------
Before: 
tpatterson@pop-os cache (groupcache *%) $ go test -bench BenchmarkGroupCacheFetch -run=^$  -benchmem -memprofile memprofile.out
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/storage/chunk/cache
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
BenchmarkGroupCacheFetch-8       1277026               965.6 ns/op           472 B/op         11 allocs/op
After:
tpatterson@pop-os cache (groupcache *%) $ go test -bench BenchmarkGroupCacheFetch -run=^$  -benchmem …
```
=> Groupcache performance improvements

pkg/ingester/index/bitprefix.go, pkg/querier/queryrange/shard_resolver.go, pkg/querier/queryrange/shard_resolver_test.go, pkg/querier/queryrange/split_by_interval.go, pkg/storage/stores/composite_store_entry.go, pkg/storage/stores/tsdb/index/fingerprint.go, pkg/storage/stores/tsdb/index/index.go, pkg/storage/stores/tsdb/index/postings.go, pkg/storage/stores/tsdb/index/postings_test.go, pkg/storage/stores/tsdb/index/shard.go, pkg/storage/stores/tsdb/index/shard_test.go, pkg/storage/stores/tsdb/index_client.go
This contains a few fixes I've found over the past few days of debugging TSDB operations (sorry for being all over the place), but the important bits are
1) Correctly calculates `storage.SeriesRef` offsets in the `fingerprintOffsets` table in https://github.com/grafana/loki/commit/7a34b15018d7fd8596f460018ce01cc7b78234d8. This resulted in an incredibly hard to find bug in sharding code because it wasn't:
* Using section offsets to increase the starting offsets for our series references
* Using 16 byte offsets of the _file position_ not _series number_
It caused everything but the last shard to be skipped most off the time because the actual references were waaay higher than expected
2) Simplifies the query planning algorithm to consistently prefer smaller units of work.
ref …
=> [TSDB]  fingerprint offsets is now correctly 16 byte aligned

pkg/distributor/ingestion_rate_strategy_test.go
We have a handy code coverage tool that lets us know our change's impacts on code coverage. Something strange that's been happening is the distributor package has been consistently providing non-deterministic results:
Turns out [this line](https://github.com/grafana/loki/blob/e7fb10f4567f191a8dbc2344b1e62c8072dd695e/pkg/distributor/ingestion_rate_strategy.go#L48) wasn't explicitly tested in it's unit test and was being accidentally tested as part of another test in the same package. As a result, code coverage was inconsistent. 
This PR explicitly tests this code path so the coverage results of our tests are always consistent.
=> Fix inconsistent coverage in the distributor package

go.mod, go.sum, vendor/github.com/hashicorp/memberlist/net.go, vendor/modules.txt
bumped version of grafana's memberlist fork to have the fix that allows to disable labels check that is required for the migration.
https://github.com/grafana/memberlist/pull/3
=> bumped version of grafana's memberlist fork

pkg/storage/stores/tsdb/chunkwriter.go
Because TSDB indices are accumulated on disks and eventually flushed, we rely on their replication factor, so ensure we don't skip writing index entries when the chunk exists in cache already.
=> [TSDB] dont skip writing to TSDB index when chunk exists in cache

pkg/chunkenc/facade.go, pkg/storage/chunk/bigchunk.go, pkg/storage/chunk/interface.go, pkg/storage/stores/tsdb/chunkwriter.go
Uncompressed size is more intuitive for both understanding throughput on streams via the index sampling endpoint and query planning -- this fixes an earlier oversight which used compressed size.
=> [TSDB] store uncompressed chunk size in index

operator/CHANGELOG.md, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/openshift/configure.go, operator/internal/manifests/openshift/opa_openshift.go
This change downgrades the minimum TLS version supported by the two gateway components to TLS 1.2 for OpenShift. This is, so that clusters which need to be FIPS-compliant can be supported by the loki-operator.
Currently this only modifies the configuration of the gateway deployment, one open question would be if we need to _force_ all components to use TLS 1.2 if running on a FIPS cluster for compliance.
[LOG-2546](https://issues.redhat.com/browse/LOG-2546)
**Checklist**
=> operator: Set minimum TLS version to 1.2 to support FIPS

pkg/storage/stores/tsdb/manager.go
During startup, we load all the index from the `wal` from previous session and build tsdb index out of it and upload the files with timestamp [now](https://github.com/grafana/loki/blob/f18edcf9d8199619a9b63d48a217948078ba6f24/pkg/storage/stores/tsdb/head_manager.go#L196). We also create a new `wal` with timestamp [now](https://github.com/grafana/loki/blob/f18edcf9d8199619a9b63d48a217948078ba6f24/pkg/storage/stores/tsdb/head_manager.go#L206). While rotating the `wal` we build and upload the index out of it with the same timestamp as the `wal` from which it was built [here](https://github.com/grafana/loki/blob/f18edcf9d8199619a9b63d48a217948078ba6f24/pkg/storage/stores/tsdb/head_manager.go#L288). This means the index built from `wal` created at …
=> fix the issue of overwriting tsdb files during rollouts

pkg/logql/mapper_metrics.go
We dispatch many smaller queries in planning when using TSDB as an index -- this PR updates the underlying metric buckets to use exponential growth to reflect this.
=> [TSDB] query_frontend_shard_factor uses exponential buckets

docs/sources/api/_index.md, docs/sources/operations/storage/logs-deletion.md
There were bad links named "logs deletion documentation" in the section on compactor endpoints.  This PR fixes those bad links.  Also updated the YAML file frontmatter to better conform to style guidelines since I was changing the files.
=> Docs: Fix bad links in the API section

pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/deletion/tenant_delete_requests_client.go, pkg/storage/stores/shipper/compactor/deletion/tenant_delete_requests_client_test.go
(cherry picked from commit a92e048ec31148fa709e85dfd700f4cf5f58b8b0)
This was a manual cherry pick with no errors. Originally there was an error because the delete fixes weren't making it to this branch.
=> avoid making delete requests if deletes are disabled for a user (#6583)

pkg/loki/modules.go, pkg/storage/stores/shipper/compactor/deletion/delete_requests_client.go
backport of https://github.com/grafana/loki/pull/6681
=> [release-2.6.x] Fix TIME_WAIT connection leak from queriers to compactor

pkg/storage/stores/shipper/compactor/deletion/tenant_delete_requests_client.go, pkg/storage/stores/shipper/compactor/deletion/tenant_delete_requests_client_test.go
- Don't make the request for a disabled tenant even if global deletion is allowed
=> Fix per-tenant delete client

pkg/logql/log/fmt.go, pkg/logql/log/fmt_test.go, pkg/logql/log/label_filter.go, pkg/logql/log/label_filter_test.go, pkg/logql/log/labels.go, pkg/logql/log/metrics_extraction.go, pkg/logql/log/metrics_extraction_test.go, pkg/logql/log/parser.go, pkg/logql/log/parser_test.go, pkg/logqlmodel/error.go
Currently when Loki process a line, there are a numbe of reasons the processing won't go as expected, when this happens Loki sets an `__error__` label on each line that had issues, the value of this `__error__` label is one of several values e.g. JSONParserErr or TemplateFormatErr
Keeping the value of `__error__` to a simple set of values gives users granularity over removing only certain log lines with errors from a result, e.g. `__error__ != "TemplateFormatErr"`
However currently it's often difficult to understand why there was an error, rather than modify any existing behavior this PR introduces an additiona label `__error_details__` which contains more verbose error information with each line as to why the `__error__` label was set.
For example, …
=> Loki: Return an __error_details__ label for any line which incurs a __error__ while being processed

production/ksonnet/loki/memberlist.libsonnet
We have already released [2.6.1 ](https://github.com/grafana/loki/blob/v2.6.1/production/ksonnet/loki/memberlist.libsonnet#L34-L35)with memberlist labels config being set using an intermediate field instead of setting it directly under `_config`. In PR #6707, I removed the config but it would be a breaking change so this PR adds back those intermediate config options with a suggestion to set the config directly under `_config`.
=> keep the memberlist labels jsonnet config backwards compatible with 2.6.1

production/ksonnet/loki/ingester.libsonnet
Reverts grafana/loki#6589
As discussed internally, setting `max_unavailable` to `0` would block the nodes from draining. Investigating the root cause behind what caused us to change this value, it looks like the cause was not the rollout or pod disruption; it was a panic in ingester causing multiple ingesters to go down.
=> Revert "Configure ingester PDB to have max_unavailable=0"

pkg/storage/chunk/client/gcp/instrumentation.go
During TSDB testing, I noticed metrics maxxing out at the upper bucket. This adds one more, giving us a 20s measurement upper bound for GCS latencies.
=> [Fix] Furthers gcs latency buckets

.dockerignore
This was removed in #6691, but caused errors in docker builds
```bash
$ make loki-image
docker build -t grafana/loki:main-7f343d2 -f cmd/loki/Dockerfile .
Sending build context to Docker daemon  592.7MB
Step 1/15 : FROM golang:1.17.9 as build
---> b6bd03a3a78e
Step 2/15 : COPY . /src/loki
---> 0e56c7bfde79
Step 3/15 : WORKDIR /src/loki
---> Running in ab8ba59a2684
Removing intermediate container ab8ba59a2684
---> a0928aadd596
Step 4/15 : RUN make clean && make BUILD_IN_CONTAINER=false loki
---> Running in 0aa8fb6b893a
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>
...
```
We use the `.git` dir in the `check-generated-files` Make step.
=> chore(make): reinclude .git dir in docker builds

.drone/drone.yml, CHANGELOG.md, Makefile, clients/cmd/fluent-bit/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, cmd/logcli/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, go.mod, go.sum, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, operator/calculator.Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
upgrades Go to 1.18.
1. update versions on dockerfile
```bash
fd -i Dockerfile --exclude=vendor | xargs -n1 sed -i 's/golang:1.17.9/golang:1.18.4/g' 
```
2. update `go.mod`
3. change `go get` -> `go install` (as `go get` no longer valid to install standalone tools without go.mod in go.18)
4. update `loki-build-image` tag to latest. (image already pushed with 0.22.0 tag)
5. `make drone`
Verified.
`make images` - builds all images
`make build-image` - builds new loki-build-image. and pushed.
**Checklist**
=> upgrade `go:1.17.9` to `go:1.18.4`

pkg/storage/chunk/cache/memcached.go
This removes the old memcached warning log when failing to put to memcache. This was confusing for many (looks like a problem when a certain failure rate to the chunk cache is expected). However, I'm also removing this because it happens so often that it shows up as one of the largest querier mutex blocks during profiling, so this brings a performance boost as well.
=> [Enhancement] Removes memcached failure log

go.mod, go.sum, vendor/github.com/bradfitz/gomemcache/memcache/memcache.go, vendor/modules.txt
While profiling TSDB which uses many smaller queries, I've noticed that as much as 45% of our mutex lock contention delay is caused by the memcached client, particularly as we push higher query throughputs (more accesses+cache nodes). As an experiment, I forked gomemcached and added a new commit(https://github.com/owen-d/gomemcache/commit/3b901ce25fe5001e8ebe08b519aee72df46d8176) and striped lock accesses, which improved the problem, reducing acquisition delay by ~90% if I recall correctly (I forgot to save the actual profiles to include in this PR).
This PR moves the gomemcached fork we use to my own.
=> [Memcache] use owen-d gomemcache fork for connection sharding

pkg/storage/chunk/cache/cache.go, pkg/storage/store.go
Groupcache wasn't instrumented with prometheus metrics and one of the cache was double instrumented with stats collection.
=> Fix cache instrumentation

pkg/loki/modules.go
Change error message text from indexgateway to groupcache.
=> Rephrase error message (indexgateway->groupcache)

go.mod, go.sum, vendor/github.com/hashicorp/memberlist/queue.go, vendor/modules.txt
re: 
- https://github.com/hashicorp/memberlist/pull/263
- https://github.com/grafana/mimir/pull/2418
This PR updates the version of our Memberlist fork used in Loki to include a relevant bugfix related to distributor ring state issues that Mimir encountered using the previous version.
N/A
N/A
**Checklist**
=> Update Memberlist dependency version; tidy and re-vendor

go.mod, go.sum, vendor/github.com/hashicorp/memberlist/queue.go, vendor/modules.txt
This PR backports the changes in https://github.com/grafana/loki/pull/6717 to the k108 release.
Fixes [mimir/#2401](https://github.com/grafana/mimir/issues/2401).
N/A
**Checklist**
=> Backport Memberlist dependency version bump to k108

docs/sources/logql/log_queries.md, docs/sources/logql/metric_queries.md, docs/sources/logql/query_examples.md
This docs-only revision relocates some existing examples.  It also updates prose about the examples and about evaluation precedence for logical operators in the label filtering explanation.
Future PRs will better address the organization of the examples. This PR aims only to gather examples in a single location.
=> Docs: Revise location of some LogQL examples; improve prose

pkg/loki/modules.go, pkg/storage/chunk/cache/cache.go, pkg/storage/chunk/cache/groupcache.go, pkg/storage/chunk/cache/groupcache_test.go
Support per cache group capacity. 
With this individual group in groupcache can have own memory threshold.
Fixes # https://github.com/grafana/loki/issues/6786
1. Will add per group ballast config in separate PR after testing
2. Will replace `/groupcache/` with generic name also in different PR.
**Checklist**
=> chore(groupcache): Support per cache group capacity

cmd/querytee/main.go, tools/querytee/proxy.go, tools/querytee/proxy_endpoint.go, tools/querytee/proxy_metrics.go, tools/querytee/proxy_test.go
It contains the following 2 changes for query-tee:
1. query-tee enables query response comparison between a preferred backend and a secondary backend. However, it did not allow multiple secondary backends to query and compare their responses. This PR updates the code where it would compare responses from all the secondary backends with the primary backend. I have also added a `name` label to the metric, which records the result of query response comparison.
2. Add a flag to disable just the query proxy for select secondary backends. This would allow us to temporarily disable read queries for one of the secondary backends while continuing to keep writing logs to it.
I think we should rename it to `tee` instead of `query-tee` :D
**Checklist**
=> query-tee: support for multi backend response comparison and disabling query proxy for select backends

production/promtail-mixin/dashboards.libsonnet
Fix Promtail production dashboard/panels. Error message: `bad_data: 1:40: parse error: unexpected character inside braces: '~'`.
=> Fix Promtail dashboard

pkg/storage/chunk/cache/cache.go
We stopped the panic, but it made it so a user can't configure both fifocache and groupcache together. This solves the issue differentiating if groupcache is set for a particular cache based on `cache != nil` and whether it's globally configured via `cfg.GroupCacheEnabled`
=> Allow fifocache to be configured with groupcache

production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/memberlist.libsonnet
This PR removes the configuration of consul/kvstore configs if memberlist is being used, which it is by default.
I can understand if we don't want to change this configuration/code to avoid potential configuration issues or confusion for OSS users, however for internal use we've run into some confusion as to why (for example) in newly created Loki clusters is there consul configuration if we're only actually using memberlist. 
Note that if OSS users are doing migrations from consul or another kv store to memberlist the memberlist_migration_teardown jsonnet config option will preserve the config of running components at the end of the migration until their rollout is completed.
=> [jsonnet] only set the consul kvstore configs if memberlist is not being used

production/ksonnet/loki/memberlist.libsonnet
Sets the memberlist cluster label to `cluster.namespace` by default. Our jsonnet `config.libsonnet` already requires that cluster and namespace values be set.
=> [jsonnet] populate the memberlist label by default

pkg/loki/modules.go, pkg/storage/chunk/cache/groupcache.go, pkg/storage/chunk/cache/groupcache_test.go
[Now groupcache runs it's own server.](https://github.com/grafana/loki/pull/6752) Fix the constructor of the groupcache to the same.
**Checklist**
=> chore(groupcache): Groupcache doesn't need global server handler anymore

cmd/loki/main.go, pkg/loki/config_wrapper.go
The behaviour was changed as part of #6802. This should restore the previous behaviour and allow the version to be displayed without config file.
=> Treat version flag at any position

go.mod, go.sum, vendor/go4.org/unsafe/assume-no-moving-gc/untested.go, vendor/modules.txt
Fixes https://github.com/grafana/loki/issues/6831
Thanks for reporting this @andig :+1: 
Hat-tip to @rfratto in https://github.com/grafana/agent/pull/1985
=> Support building against Go 1.19

pkg/chunkenc/interface.go, pkg/chunkenc/interface_test.go, pkg/ingester/stream.go, pkg/ingester/stream_test.go
This improves on the error if the ingested timestamp is significantly behind the highest timestamp of a stream (bigger than MaxChunkAge)
before: 
```
entry with timestamp 2022-08-02 12:32:37 +0000 UTC ignored, reason: 'entry too far behind' for stream: {foo="bar2"}
```
after:
```
entry with timestamp 2022-08-02 12:32:37 +0000 UTC ignored, reason: 'entry too far behind, oldest acceptable timestamp is: 2022-08-03T15:25:57Z' for stream: {foo="bar2"}
```
I think we can probably do even better (cc @KMiller-Grafana). But I guess that gets us a step closer.
=> Improve error message when entry is too far behind

operator/Dockerfile
Use `-mod=readonly` when buidling the loki-operator container to ignore any vendor directory and report an error when `go.mod` needs an update.
**Checklist**
=> operator: Use mod readonly when building container

pkg/storage/stores/indexshipper/compactor/compactor.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager_test.go
This is a setting to protect the compactor when there are many delete requests. Only process `delete_batch_size` per compaction.
The default of 70 was chosen based on a recent incident where we saw 16-hour delete requests run at a rate of ~28/minute. At that rate, 70 should take ~2.5 minutes. Even if the requests cover 4x the data, this should still keep the deletion phase of compaction to ~10 minutes.
=> Only process deletes in batches

pkg/querier/queryrange/shard_resolver.go
Noticed spans hierarchy wasn't populating properly in some traces and tracked it here. Now we'll properly attach the correct span parent in the shard resolver.
=> Fix context propagation for child spans in shard resolver

Makefile
Encountered after upgrade to go1.19 in local breaks this assumption. Meaning, even if your loki binary built with `-tags netgo` that file `cgo_stub.go` doesn't exist in the binary. And any `make <binary>` keep failing.
```
\nYour go standard library was built without the 'netgo' build tag.
To fix that, run
sudo go clean -i net
sudo go install -tags netgo std
make: *** [Makefile:149: cmd/loki/loki] Error 1
```
But even those commands not helping. Looks like this check was added by Tom at 2018.
tbh, checking for filename inside the binary is too much internal details that is subjected to change (which is what happened here I think).
NOTE: Had some internal discussions and confirmed that we don't need …
=> chore(makefile): Remove `NETGO` check after building loki binaries.

production/ksonnet/loki/memberlist.libsonnet
This PR changes our jsonnet code so that we don't deploy consul if we're using memberlist and not actively migrating from consul to memberlist.
=> [jsonnet] don't deploy consul if we're using memberlist

clients/pkg/promtail/promtail_test.go, clients/pkg/promtail/server/server.go, go.mod, go.sum, vendor/github.com/weaveworks/common/instrument/instrument.go, vendor/github.com/weaveworks/common/server/server.go, vendor/modules.txt
You cannot run promtail tests if there is already running promtail in your local.
e.g:
```
$ go test -run TestPromtail ./clients/pkg/promtail/
```
It gives you error
```
--- FAIL: TestPromtail (0.02s)
promtail_test.go:112: error creating promtail listen tcp 127.0.0.1:9080: bind: address already in use
FAIL
FAIL	github.com/grafana/loki/clients/pkg/promtail	0.043s
```
Cause for the error is, test uses static default port (the same we use for promtail normally) in tests.
This is not **too** annonying if seen in isolation. But mainly annoying in two cases particularly
1. Hard to run tests parallely in general with these kind of static ports
2. These are causing some real problems in some integeration …
=> test(promtail): Fix flaky test with promtail bind port.

docs/sources/configuration/_index.md, docs/sources/operations/storage/logs-deletion.md
Followup to https://github.com/grafana/loki/pull/6854 which fixes documentation references.
=> update deletion docs

docs/sources/api/_index.md, integration/loki_micro_services_delete_test.go, pkg/loki/modules.go, pkg/storage/stores/indexshipper/compactor/compactor.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager_test.go, pkg/storage/stores/indexshipper/compactor/deletion/request_handler.go, pkg/storage/stores/indexshipper/compactor/deletion/request_handler_test.go, pkg/storage/stores/indexshipper/compactor/deletion/tenant_delete_requests_client.go, pkg/storage/stores/indexshipper/compactor/deletion/tenant_delete_requests_client_test.go, pkg/storage/stores/indexshipper/compactor/deletion/tenant_request_handler.go, pkg/storage/stores/indexshipper/compactor/deletion/tenant_request_handler_test.go, pkg/storage/stores/indexshipper/compactor/deletion/util.go
To help protect against pathological delete scenarios, this PR adds the following validation to the Delete API:
- Ensure a start date is present
- Ensure the timestamp format is either 10-digit Unix seconds or RFC3339
Additionally, this PR moves the delete middleware to it's own file. This is just so validation testing could be done without setting up limits.
=> Add delete api validations

pkg/storage/stores/indexshipper/compactor/deletion/tenant_request_handler_test.go
An interface for deletion limits was added that means we don't need to use `retention.Limits` here anymore. It also means we don't have to convert between limit types in the test anymore
=> Remove unused code

docs/sources/configuration/_index.md, pkg/storage/stores/indexshipper/compactor/compactor.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/indexshipper/compactor/deletion/metrics.go, pkg/storage/stores/indexshipper/compactor/index_set.go, pkg/storage/stores/indexshipper/compactor/retention/expiration.go, pkg/storage/stores/indexshipper/compactor/retention/retention.go, pkg/storage/stores/indexshipper/compactor/retention/retention_test.go, pkg/storage/stores/indexshipper/compactor/retention/util_test.go, pkg/storage/stores/indexshipper/compactor/testutil.go, pkg/storage/stores/shipper/index/compactor/compacted_index.go, pkg/storage/stores/shipper/index/compactor/compacted_index_test.go, pkg/storage/stores/shipper/index/compactor/iterator.go, pkg/storage/stores/shipper/index/compactor/iterator_test.go, pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/compactor_test.go, tools/tsdb/tsdb-map/main.go
To help protect the system from a situation where deletes take too long and block compaction, this PR introduces timeouts to the deletion process.
As part of retention, all chunks for an affected timerange are scanned and any active deletion filters are applied. This change adds a context to that loop so that it can time out. 
The timeout may not occur exactly when the context expires. Instead, this change prioritizes changing entire chunks so that progress is made even if the timeout expires.
This change adds a `MarkPhaseTimedOut` method to `Expiration Checkers` so they can take the appropriate actions. In this case, the list of deletes to be processed are cleared which prevents `MarkPhaseFinished` from marking them as `Processed`. This ensures deletes will be retried the next time …
=> Add timeouts to deletions 

pkg/storage/store.go, pkg/storage/stores/composite_store.go, pkg/storage/stores/composite_store_test.go, pkg/storage/stores/metrics.go
We currently only have index request latency metrics on individual store types i.e boltdb-shipper, tsdb, bigtable etc. This makes it hard to instrument dashboards when we change the store type. This PR adds a metric to measure the overall index request latency irrespective of the underlying store type.
* The metric tracks the latency across all the stores, so if a query spans multiple stores, it measures the total latency from all the stores. A single query would rarely span multiple stores after splitting, so it should not be a big deal.
* The metric only measures index query latency and not the write latency. For measuring just the write latency, I need to refactor some code so left a todo for it and will do a …
=> Store request latency metrics

CHANGELOG.md, clients/pkg/promtail/scrapeconfig/scrapeconfig.go, clients/pkg/promtail/targets/journal/journaltarget.go, clients/pkg/promtail/targets/journal/journaltarget_test.go, docs/sources/clients/promtail/scraping.md
Do not process all journal logs. Add an option to add matches to the journal reader.
**Checklist**
=> [promtail] Add support for journal matches (only conjuntions)

pkg/querier/queryrange/stats.go, pkg/querier/queryrange/stats_test.go
When any type of query fails, do not collect statistics.
Rationale being when core http handler returns error, it's reponse will be nil and there won't be any statistics
to collect and log.
Fixes #6231 
**Checklist**
=> fix(stats_collector): Do not collect stats for failed requests.

pkg/logql/log/labels.go, pkg/logql/log/metrics_extraction_test.go
The error handling was missing appending the error details properly in all cases (e.g. queries with pipelines that parsed and extracted like: `sum_over_time({[...]} | logfmt | unwrap duration [5m])`)
The error message before:
> `pipeline error: 'SampleExtractionErr' for series: '{__error__="SampleExtractionErr", ... }' [...]` 
And after:
> `pipeline error: 'SampleExtractionErr' for series: '{__error__="SampleExtractionErr", __error_details__="strconv.ParseFloat: parsing \"12s\": invalid syntax", .... }' [...]` 
Fixes #6265
=> Propagate error detail properly in all cases

tools/querytee/proxy_endpoint.go, tools/querytee/proxy_metrics.go
This will allow us to isolate requests coming from the loki-canaries vs any other source in the query tee. This can be helpful when the canary represents most queries and thus biases the resulting metrics.
=> [QueryTee] Detects issuer via useragent in querytee reqs

production/ksonnet/loki/memberlist.libsonnet
PR #6888 broke some additional jsonnet we use internally to extend the `consul_deployment`, although the changes in that PR were necessary for OSS users who do want to use consul. 
What we need to do is use {} instead of null since `{} + null` is invalid and will result in an error. Then we can modify our internal extensions to the same conditional we have in this `memberlist.jsonnet` file to only add on to the consul deployment if we are not using memberlist.
=> [jsonnet] Fix conditional for deploying consul when not using memberlist

pkg/storage/stores/indexshipper/gatewayclient/gateway_client_test.go
This removes the unnecessary spinning up of a mock for `TestDoubleRegistration`. The client itself is not used at all and that
causes it to be stopped before it is actually started.
Example flake: https://drone.grafana.net/grafana/loki/14724/2/5
=> Remove unnecessary spin up of mock

pkg/storage/stores/indexshipper/compactor/compactor.go, pkg/validation/limits.go
This reintroduces a few recently deleted configurations to retain backwards compatibility for old fields, even though their behavior is now a no-op:
* `boltdb.shipper.compactor.deletion-mode` (compactor config)
*  `compactor.allow-deletes` (limits config)
=> reintroduces now deprecated+noop deletion configs for compatibility

operator/CHANGELOG.md, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/rbac/role.yaml, operator/controllers/loki/lokistack_controller.go, operator/internal/manifests/mutate.go, operator/internal/manifests/mutate_test.go
Currently the `ownerReferences` of creates resources are only set when the resource is created and not included in the check when reconciliation happens. During normal operation this is not a big issue, because the reference to `LokiStack` should not change.
We recently changed the CRD version of `LokiStack` from `v1beta1` to `v1` and stopped serving the old version. This causes references to the old `v1beta1` LokiStack to become stale. This PR fixes this issue by also looking at the `ownerReferences` field during reconciliation and updating it with the current reference.
The additional privileges are needed because the apiserver will only allow an update of the `ownerReferences` field for `ServiceAccounts` that are also able to delete the object. …
=> operator: Reconcile owner reference for existing objects

pkg/logql/rangemapper.go
Found a panic in one of our clusters and wasn't sure the query which caused it. This PR tries to log the offending query during mapping prior to the panic.
=> log query which causes panic in logql.clone

CHANGELOG.md, pkg/logql/rangemapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/ast_test.go
**How the problem was identified**
Range mapper query fails for topk/bottomk expressions with parameter 0. 
When parsing an expression the current flow is:
1) `ParseSampleExpr` from query string: https://github.com/grafana/loki/blob/main/pkg/logql/rangemapper.go#L80
```
origExpr, err := syntax.ParseSampleExpr(query)
```
this operation succeeds with no error
2) `ParseSampleExpr` from `expr.String()`: https://github.com/grafana/loki/blob/main/pkg/logql/rangemapper.go#L451
```
e, err := syntax.ParseSampleExpr(expr.String())
```
`expr.String()` does not consider the topk parameter 0 because of this condition: https://github.com/grafana/loki/blob/main/pkg/logql/syntax/ast.go#L927-L931
```
if e.Params != 0 {
params = []string{fmt.Sprintf("%d", e.Params), …
```
=> Fix topk and bottomk operations with int <= 0

pkg/logproto/extensions.go, pkg/storage/stores/index/stats/stats.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/index.go, pkg/storage/stores/tsdb/index_client.go, pkg/storage/stores/tsdb/index_shipper_querier.go, pkg/storage/stores/tsdb/lazy_index.go, pkg/storage/stores/tsdb/multi_file_index.go, pkg/storage/stores/tsdb/multitenant.go, pkg/storage/stores/tsdb/single_file_index.go, pkg/storage/stores/tsdb/store.go
Refactors the TSDB Index sampling to take an interface which uses bloom filters on the index gateways but bypasses them on the ingesters. This doesn't seem worth the cost in ingesters as it's relevant for deduplicating across index bucket boundaries (less likely with 15m shipping periods in the ingester index-shipper) and deduplicating due to replication factor (not valid in ingesters either).
=> [TSDB] disables bloom filters for tsdb index on ingesters

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/streamsharder.go, pkg/distributor/streamsharder_test.go, pkg/loki/modules.go
This PR is the first-pass implementation of the component that manages the state for sharded streams.
Todo after this:
- Expire streams so we don't grow without bound
- Cache values so not every distributor has to calculate the cost of every stream
=> Implement the stream sharder and shard iter

pkg/loki/modules.go, pkg/ruler/base/storage.go
Allows the ruler to fail to start gracefully, if no ruler storage is configured.
Also removes support for `configdb`, since this is not supported but was the default storage type in the ruler code we forked from Cortex.
Fixes #5460
If Loki SSD is run without ruler storage being configured, you get this nasty error:
```
configdb is not supported as a Loki rules backend type
error initialising module: ruler-storage
github.com/grafana/dskit/modules.(*Manager).initModule
/home/danny/Code/open-source/loki/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
/home/danny/Code/open-source/loki/vendor/github.com/grafana/dskit …
```
=> Setting sane defaults for ruler in SSD "read" mode

pkg/loki/modules.go
In the previous PR #6957 I accidentally removed about 88 metrics due to the resetting of `prometheus.Default{Gatherer,Registerer}`.
This new PR simplifies the implementation by using the default registerer but unregistering the default Go collector (which contains only a stripped-down list of metrics from the go runtime) with a collector which contains all available metrics.
N/A
The following metrics have been added:
```
go_gc_cycles_automatic_gc_cycles_total
go_gc_cycles_forced_gc_cycles_total
go_gc_cycles_total_gc_cycles_total
go_gc_heap_allocs_by_size_bytes_bucket
go_gc_heap_allocs_by_size_bytes_count
go_gc_heap_allocs_by_size_bytes_sum
go_gc_heap_allocs_bytes_total …
```
=> Register all available Go metrics

docs/sources/upgrading/_index.md, production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/distributor.libsonnet
This is equivalent to https://github.com/grafana/loki/pull/6415 but for distributors.
Why only distributors?
- Ingesters are critical and stateful, so we cannot risk losing multiple ingesters on a node failure.
- Other workloads do not typically have a high number of replicas, therefore, the risk of losing multiple replicas on a node failure outweighs the benefits.
**Checklist**
=> Evenly spread distributors across available nodes

docs/sources/configuration/_index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/streamsharder.go, pkg/distributor/streamsharder_test.go, pkg/loki/modules.go
Implement a new feature named `stream sharding`. Distributors with stream sharding enabled will reduce big streams before pushing them to the ingesters by adding a new sharding label. By having a new label, a bigger stream is hence reduced.
This shouldn't impact Loki in any form since it is disabled by default.
This initial implementation contains:
- A sharder interface to be used internally regardless of the implementation
- An initial sharder implementation that supports sharding streams
- A mechanism to recognize per-stream limits and trigger sharding based on it
- Related configurations that dictate if sharding should be enabled or not. We're not documenting these configurations yet as we don't want users to use by mistake since this is far from …
=> Loki: Implement stream sharding

docs/sources/operations/observability.md
Add deletion metrics to the documentation.
**Checklist**
=> Add deletion metrics to the documentation

pkg/querier/http.go, pkg/querier/querier.go
On PR #6835 I mistakenly removed the `querier:query_timeout` YAML configuration. This PR returns it and uses it if it is still configured, while logging a warning message to alert users of the upcoming changes.
=> Return Querier/QueryTimeout YAML configuration

docs/sources/api/_index.md
@MasslessParticle, please verify that this should be `h` instead of `"h"`.
=> Use backticks for code syntax.

pkg/storage/chunk/client/aws/s3_storage_client.go, pkg/storage/chunk/client/object_client.go
fix a s3 panic.
```go
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14fec7b]
goroutine 6271245 [running]:
github.com/grafana/loki/pkg/storage/chunk/client.(*client).getChunk(_, {_, _}, _, {{0xb130cf997b272f99, {0xc05077e6a0, 0x1b}, 0x182d1aefb2d, 0x182d1b47984, 0x9fab6388}, ...})
/loki@v1.6.2-0.20220816085209-65ed7b60fbd4/pkg/storage/chunk/client/object_client.go:171 +0x2fb
```
**Checklist**
=> [fix panic] s3: fix object nil point

CHANGELOG.md, docs/sources/clients/lambda-promtail/_index.md, tools/lambda-promtail/lambda-promtail/kinesis.go, tools/lambda-promtail/lambda-promtail/kinesis_test.go, tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/promtail.go, tools/lambda-promtail/testdata/kinesis-event.json
This PR adds support for sending Kinesis data stream events to lambda-promtail. One use case would be e.g. to send CloudFront realtime logs to Loki.
Fixes #5978 
n/a
**Checklist**
=> lambda-promtail: Add support for Kinesis data stream events

.drone/drone.yml, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
Updates the alpine image version we use to 3.16.2 and will also build/publish a new loki build image
=> update to alpine:3.6.2

CHANGELOG.md, docs/sources/logql/template_functions.md, pkg/logql/log/fmt.go, pkg/logql/log/fmt_test.go
We have the `__line__` and `__timestamp__` functions currently available in the `line_format` stage but not in the `label_format` stage. This PR fixes that.
Specifically `__timestamp__` can be valuable in a label because you can do things like
```
label_format hour_of_day=`{{__timestamp__ | date "15"}}`
```
To be able to conditionaly select log lines based on the hour of the day they were created, this can be useful for conditional alerting as an example.
Fixes #6402
**Checklist**
=> Loki: add `__line__` and `__timestamp__` to label_format

docs/sources/configuration/_index.md
I noticed when responding to #5123 the docs did not correctly explain how to disable splitting queries by time. I searched through the code and confirmed `0` is the correct value to disable this feature
**Checklist**
=> Docs: update `split_queries_by_interval` documentation to have the correct explanation for how to disable.

docs/sources/configuration/_index.md
Fix a doc stating a wrong `max_chunk_age` value.
Fixes #6919
=> Docs: Fix default max_chunk_age

docs/sources/clients/promtail/stages/_index.md, docs/sources/clients/promtail/stages/json.md, docs/sources/clients/promtail/stages/logfmt.md
I noticed earlier while writing a design doc that the `logfmt` pipeline stage is not documented. It was originally added here: https://github.com/grafana/loki/pull/4346
I've also fixed a minor typo in the json pipeline stage docs.
=> [docs] document logfmt pipeline stage

pkg/storage/factory.go, pkg/storage/stores/tsdb/store.go
This changes allows downstream projects to reset the TSDB store singleton. This must only be called in test cases where a new store instances cannot be explicitly created.
Also add a `nil` check to the reset function for the BoltDB shipper singleton instance.
=> Make TSDB store singleton resettable

pkg/storage/stores/shipper/index/compactor/table_compactor.go, pkg/storage/stores/shipper/index/compactor/table_compactor_test.go
Before this change, these files are fetched while [holding a table global lock](https://github.com/grafana/loki/blob/a1e75da9707d4fe5bacf5d3aea947225c5781d09/pkg/storage/stores/shipper/index/compactor/table_compactor.go#L195), serializing fetches.
I chose the approach of prefetching index files over attempting to change the locking pattern to allow parallel, on-demand fetches because the complexity of parallelizing on-demand fetches outweighed the benefits of avoiding extra fetches. More specifically, this patch trades off fetching idle, non-compactable index files in favor of avoiding blocking during compactions. The extra fetches are parallelized and so should incur a negligible wall clock penalty even for large numbers of tenants(e.g. 1k idle …
=> compactor: prefetch existing compacted user index files in parallel

pkg/querier/queryrange/shard_resolver.go, pkg/querier/queryrange/shard_resolver_test.go
This PR gives a little better understanding into shard query planning and targets a range of `(300MB,600MB]` per shard. Doubling this also allows us to halve query parallelism configs and still schedule the same amount of work in parallel, which should make for easier schema upgrades as the parallelism differences between TSDB and prior period configs will be less.
=> [TSDB] 600MB max per shard in query planning

pkg/ingester/flush.go
Fix panic of flushing a chunk. This fix it by first reporting its statistics and only then marking it as flushed.
```go
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x177d158]
goroutine 14455 [running]:
github.com/grafana/loki/pkg/chunkenc.(*MemChunk).Size(0xc00441c750?)
/loki@v1.6.2-0.20220816085209-65ed7b60fbd4/pkg/chunkenc/memchunk.go:611 +0x18
github.com/grafana/loki/pkg/ingester.(*Ingester).reportFlushedChunkStatistics(0xc00087a000, 0xc00f8efe80, 0xc0519d0870, {0x36b7008, 0xc01a593860}, {0x36b7008, 0xc01a5938c0}, {0x307e2f9, 0x7})
/loki@v1.6.2-0.20220816085209-65ed7b60fbd4/pkg/ingester/flush.go:395 +0x2f2
```
**Special …
=> [bugfix] fix flush.go nil pointer panic

.github/workflows/helm-ci.yml, production/helm/ct.yaml, production/helm/loki/Chart.lock, production/helm/loki/README.md, production/helm/loki/docs/examples/enterprise/overrides-enterprise-gcs.yaml, production/helm/loki/docs/examples/oss/overrides-oss-gcs.yaml, production/helm/loki/templates/monitoring/servicemonitor.yaml, production/helm/loki/templates/securitycontextconstraints.yaml, production/helm/loki/values.yaml, tools/dev/k3d/chartfile.yaml
The Helm CI would not pass the linting stage.
Summary
* updates the README
* introduces a filter that will only run the Helm CI on changes to the
Helm chart directory
* removes trailing whitespace
* corrects the Minio chart repository
=> Generate Helm chart README.

pkg/querier/queryrange/downstreamer_test.go
increase timeout, fix test fail.
```
--- FAIL: TestInstanceFor (0.01s)
downstreamer_test.go:205: 
Error Trace:	downstreamer_test.go:205
downstreamer_test.go:256
Error:      	lock couldn't be acquired
Test:       	TestInstanceFor
FAIL
```
**Checklist**
=> fix test increase timeout

pkg/logql/engine.go, pkg/logql/engine_test.go, pkg/logql/evaluator.go, pkg/logql/syntax/ast_test.go, pkg/logql/syntax/parser_test.go
logql engine support exec `vector(0)` grama.
new PR of :https://github.com/grafana/loki/pull/7007
Fixes #6946
test passed.
test1: vectorExpr only
test2: binExpr and vectorExpr
**Checklist**
=> [new feature] logql engine support exec `vector(0)` grama

pkg/storage/stores/tsdb/head.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go
Currently `Append` call to the head has to wait for block creation to complete when rotating head.
And since we rotate head every 15m (default period), this would result in latency spikes at these times.
This PR moves the TSDB build step to an async routine.
**Checklist**
=> tsdb: build rotated heads asynchronously

.github/workflows/helm-release.yaml
We don't want to run the helm release on tags matching our loki releases. We can add the helm chart to the release process later, but we're not there yet. Right now our flow is ship the updated loki binary, then circle back around and update the helm charts to use that new version is a separate PR/release.
=> Do not run helm release on tags matching our version releases

pkg/storage/stores/tsdb/head.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go, pkg/storage/stores/tsdb/manager.go
refactors tsdb manager code to expose a new method `BuildFromHead` which comes in handy for building tsdb from tenant heads after rotation.
Currently we build it by recovering head from WAL even when we have access to the in-mem tenant heads.
using `loki_tsdb_head_rotations_*` metric to track loop failures which could be caused either by rotation failures or if rotation is blocked by prev head failing to build
**Checklist**
=> tsdb: build tsdb from tenantheads

operator/website/layouts/index.html
Fix a typo in the layout: `kuberentes` instead of `kubernetes`
=> docs: fix typo in layout

pkg/util/cfg/flag.go, pkg/util/cfg/flag_test.go
see #7048 
if we don't apply cases.NoLower, it will upper first alphabet lower the others
```go
package main
import (
"fmt"
"golang.org/x/text/cases"
"golang.org/x/text/language"
"strings"
)
func main() {
source := "testAPI"
fmt.Println(cases.Title(language.Und).String(source)) // out: Testapi
fmt.Println(cases.Title(language.Und, cases.NoLower).String(source)) // out: TestAPI
fmt.Println(strings.Title(source)) // out: TestAPI
}
```
**Checklist**
=> bugfix:add cases.NoLower option

.github/workflows/helm-release.yaml
The helm release job creates a tag for each new release. The tags was previously `<chart name>-<chart version>`, which in the case of the loki chart in this repo was `loki-3.0.0`. This is confusing, so we are adding the prefix `helm-` to these  tags.
=> Add prefix for helm-release tags

CHANGELOG.md, pkg/loki/loki.go, pkg/loki/loki_test.go, pkg/loki/modules.go, pkg/server/internal_server.go
The following PR adds support for a custom internal server listener dedicated for the start to serve the ready handler on a separate port and optionally TLS configuration. The key purpose for this one is to serve the Loki HTTP API via mTLS while serving the readiness endpoints without (i.e. kubernetes readiness/liveness probes do not support authentication)
**Checklist**
=> Add support for custom internal server

pkg/loki/loki.go, pkg/loki/modules.go
Follow up on #7069. Fix server instance assignment in modules. Adds missing `buildinfo` handler to internal server listener for k8s liveness checks
**Checklist**
=> Fix internal server initialization

pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go
Print the sequence number of the delete request so the messages are not all the same.
**Checklist**
=> Add sequence num to log output for delete requests

production/helm/loki/templates/_helpers.tpl
Currently helm chart helper does not pass region or any other information if s3 storage is configured. This causes issues with connecting to S3 on AWS. This Pr fixes it, by passing all revelant configs to ruler storage config.
Fixes #7060
**Checklist**
=> Helm: Fix s3 region in ruler storage config

docs/sources/configuration/_index.md
The delete_max_interval was previously named delete_max_query_range. This rename was not done in the documentation,
**Checklist**
=> Fix setting name in documentation

operator/CHANGELOG.md, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/openshift/manager_auth_proxy_patch.yaml
This PR adds Intermediate security profile to the `kube-rbac-proxy` operator sidecar.
**Checklist**
=> Operator: Configure kube-rbac-proxy sidecar to use Intermediate TLS security profile in OCP

.github/workflows/helm-release.yaml
Only need to run the helm release action when helm paths were changed
=> Only release helm for helm paths

.github/labeler.yml
Labelling Helm related pull requests with `area/helm` will ease discovery.
=> Automatically label Helm realted pull requests.

CONTRIBUTING.md, production/README.md
- Fix the link pointing to a Loki Helm chart, found in the [Contribute to Helm](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md#contribute-to-helm) section of the [CONTRIBUTING.MD](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) file.
- Fix the link pointing to a Promtail Helm chart, found in the [Using Helm to deploy on Kubernetes](https://github.com/grafana/loki/blob/main/production/README.md#using-helm-to-deploy-on-kubernetes) section of the [production/README.md](https://github.com/grafana/loki/tree/main/production) file.
The previous links used were pointing to a [deprecated file](https://github.com/grafana/loki/tree/main/production/helm).
None.
**Checklist**
=> Docs: Fix Helm Chart links

flake.nix, nix/chart-releaser.nix, nix/default.nix
Adds the `chart-tools` and `chart-releaser` binaries to the nix shell for doing helm releases/testing.
=> Add chart-tools and chart-releaser for helm

production/helm/loki/values.yaml
Fix incorrect selectors for anti-affinity rules for loki single binary.
Fixes #7105
=> Fix pod affinity selector for single binary

production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/monitoring/dashboards/configmap-1.yaml, production/helm/loki/templates/monitoring/dashboards/configmap-2.yaml, production/helm/loki/templates/monitoring/prometheus-rules.yaml
Small helm style fix to be more consistent across templates when checking an `enabled` flag in a nested struct.
=> Make helm with style more consistent

.github/workflows/helm-release.yaml, production/helm/cr.yaml
The helm release job is failing because it's looking for the wrong release name. This is an attempt to fix it.
The addition of `on: pull_request` to the github action is a temporary hack so I can test if this fixes the issue. Please don't merge until we have a chance to remove that.
=> Fix helm release name template

docs/sources/api/_index.md, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_store.go
When sharded deletes that are partially completed are force-removed, everything is removed except the shards that are currently being deleted. The shards being deleted aren't necessarily in numerical order so there's no way to know assume which shards have and haven't been deleted.
The Delete store assumed it could look up requests in sequential order and returned empty requests where there were gaps in the stored data. This change takes the `sequence number` from the stored key of the delete requests it finds and uses that to look up details.
=> Fix errors loading deletes after force-removing partially-completed delete

operator/README.md, operator/apis/loki/v1/lokistack_types.go, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/manifests/loki.grafana.com_lokistacks.yaml, operator/config/crd/bases/loki.grafana.com_lokistacks.yaml, operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml, operator/docs/user-guides/forwarding_logs_to_gateway.md, operator/docs/user-guides/howto_connect_grafana.md, operator/internal/handlers/internal/gateway/modes.go, operator/internal/handlers/internal/gateway/tenant_secrets.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/manifests/gateway_tenants.go, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/internal/gateway/build_test.go, operator/internal/manifests/internal/gateway/gateway-tenants.yaml, operator/internal/manifests/openshift/build_test.go, operator/internal/manifests/openshift/configure.go, operator/internal/manifests/openshift/opa_openshift.go, operator/internal/manifests/openshift/options.go, operator/internal/manifests/openshift/serviceaccount_test.go
This PR adds a `network` tenant in Openshift Gateway component for [netobserv](https://github.com/netobserv) project. This will allow [network-observability-operator](https://github.com/netobserv/network-observability-operator) to configure its components to read and write `loki-operator` logs.
/
@periklis I feel recommending users to use another lokistack instance is good enough for now but feel free if you feel we should split `ModeType` or add additional guard.
**Checklist**
=> operator: Add network tenant for netobserv

CHANGELOG.md, pkg/loki/modules.go
Attaches the panic recovery handler on all HTTP handlers. 
Mitigates panics for  #6667 
**Checklist**
=> loki: Attach the panic recovery handler on all HTTP handlers

docs/sources/configuration/_index.md
Remove the duplicate deletion_mode entry in the 2.6 branch. This change is not needed for the main branch as this setting has been removed from that section there.
Fixes #7117
=> Remove duplicate deletion_mode entry

pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/ingester/stream.go, pkg/ingester/stream_test.go, pkg/loki/modules.go
Per-stream sharding will introduce automatic stream sharding on rate-limited streams. The ingester's current line-by-line behavior may result in duplicates when a partially-accepted stream is resharded and sent to other ingesters. This PR makes the ingester either rate limit the entire stream before attempting to write lines to a chunk. The PR
1. Separates validation, storage, and wal replay into their own functions
2. Implements a flag to rate limit the whole stream or not
3. Checks rate limits for the whole stream rather than line-by-line
4. Returns an error with information on the whole stream when rate limited
=> Implement all-or-nothing stream ingestion

docs/sources/logql/template_functions.md
Some examples only had a single open brace,
but require two. I added the missing braces.
Improves documentation, helps users who are reading docs about template functions.
=> Docs: Fix template function examples

pkg/storage/stores/tsdb/head.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/manager.go
Signed-off-by: Ashwanth Goli <iamashwanth@gmail.com>
clean-up unused metrics and refactor others to use a `CounterVec`
**Checklist**
=> tsdb: clean-up metrics

go.mod, pkg/ingester/ingester_test.go, pkg/ingester/instance.go, pkg/ingester/recovery.go, pkg/ingester/stream.go, pkg/ingester/stream_test.go
We've changed approaches to how we want to do per-stream rate limiting. The new approach will rely on creating an api on the ingester so the distributors can decide how streams should be sharded. As a result, the work to return rate-limited streams in the error body is no longer needed.
=> revert stream push error response

production/helm/loki/docs/examples/enterprise/overrides-enterprise-gcs.yaml
This update the example for deploying a GEL cluster using the new helm chart. The previous example was a bit out of date.
=> Update GEL helm deployment example

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/tokengen/job-tokengen.yaml, production/helm/loki/values.yaml
This PR fixes a few small things with the helm chart:
* After upgrading to the new minio chart, the subvalues for that chart were not correctly changed to the new values for `rootUser` and `rootPassword`
* The default replica count for the new minio chart is 16, which seems a little much for our needs.
* The `grafana-token` created by the tokengen job was meant to be used when configuring the GEL plugin, but it was not working, so I removed it.
=> Fix minio values, reduce replicas, and fix tokengen job

production/helm/loki/README.md, production/helm/loki/values.yaml
Exposes the compactor and limits config in the helm chart via helm values. Replaces https://github.com/grafana/loki/pull/7055 with some minor stylistic changes, and moving default limits into the new `limits_config` value.
=> Expose limits and compactor config via helm values

operator/internal/handlers/internal/tlsprofile/tlsprofile.go, operator/internal/handlers/internal/tlsprofile/tlsprofile_test.go, operator/internal/handlers/lokistack_create_or_update.go
This PR fixes the TLSProfile not working on vanilla k8s. 
Instead of erroring out when APIServer is not found, just log the error and apply the Intermediate profile instead.
**Checklist**
=> operator: Fix TLSProfile not working on vanilla k8s

production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
Signed-off-by: CAJNA Jarod <contact@jarodcajna.fr>
This will allow users of the chart to configure the s3 http_config block as documented here [https://grafana.com/docs/loki/latest/configuration/#s3_storage_config](https://grafana.com/docs/loki/latest/configuration/#s3_storage_config) through values.
Fixes grafana/helm-charts#1762
-->
**Checklist**
=> Helm: Allows loki s3 http_config block to be configured

pkg/loki/modules.go
Fixes a bug introduced in https://github.com/grafana/loki/pull/7013
This will panic when the interface's _value_ is nil because it's been assigned a concrete type already and then passed as an interface. Instead, we treat it as a nil interface with no type bound to it:
```
goroutine 40570 [running]:
github.com/grafana/loki/pkg/util/server.onPanic({0x2209320, 0x3dfae20})
/src/enterprise-logs/vendor/github.com/grafana/loki/pkg/util/server/recovery.go:41 +0x53
github.com/grafana/loki/pkg/util/server.glob..func1.1.1()
/src/enterprise-logs/vendor/github.com/grafana/loki/pkg/util/server/recovery.go:29 +0x3a
panic({0x2209320, 0x3dfae20})
/usr/local/go/src/runtime/panic.go:838 +0x207 …
```
=> fixes nil interface value with non-nil type in cache construction

CHANGELOG.md, pkg/storage/chunk/client/azure/blob_storage_client.go, pkg/storage/chunk/client/azure/blob_storage_client_test.go
This PR adds the ability to use Service Principal credentials to authenticate through Azure OAuth. It might be needed when we want to access Azure Blob storage from another tenant.  
Previously we could use only StorageAccount key that can not be used cross-tenant. 
**Checklist**
=> [loki] Azure auth using Service Principal

pkg/storage/store.go
The refactor [here](https://github.com/grafana/loki/blob/main/pkg/storage/store.go#L237) introduced in https://github.com/grafana/loki/pull/7154 will cause a panic due to duplicate registration via the same store prefix when using a backup index store (for use during tsdb migrations).
This PR adds more granularity to the label value to differentiate these and avoid the problem.
=> allow backup store metrics registration by including backend type in labels

pkg/storage/chunk/client/azure/blob_storage_client.go
Fixes duplicate key registration from https://github.com/grafana/loki/pull/7179/files#diff-665c7ce7ef736bdf9f9da76a8e389d5b6fcdc90099db913ce36b4c0da2a97ef2R121-R122
=> fixes azure client secret duplicate CLI registration

pkg/storage/stores/tsdb/manager.go
When calculating the index buckets a chunk belongs to, we shouldn't error when a bucket falls outside the current TSDB store's periodConfig range. This can happen when a chunk is written across the bounds between a previous index type (i.e. boltdb-shipper) and a new tsdb type or vice versa. Instead of erroring when this happens, we'll now correctly return only the buckets matching the TSDB store (the other buckets are handled by their respective stores).
I think we can also remove the error from this function signature, although I left it in as it's conceivably helpful in the case of a chunk range that doesn't overlap at all with the store (which shouldn't happen).
Dependent on https://github.com/grafana/loki/pull/7177
=> [Bugfix] TSDB index bucket calculation

production/helm/loki/Chart.yaml, production/helm/loki/README.md
What this PR does / why we need it:
Bumps the helm chart version to trigger a release for #7182
=> Helm: Bump helm chart patch version

pkg/storage/stores/tsdb/compactor_test.go, pkg/storage/stores/tsdb/index_shipper_querier.go, pkg/storage/stores/tsdb/manager.go
indexBuckets will return the list of overlapping TSDB buckets for a time range. Historically, this errored when there was no overlap, which is generally impossible. While mutating period configurations as a test (which should never be done in production), I realized this would preemptively error us when there were old TSDB WALs from a bucket that no longer belonged to a TSDB period (i.e. by replacing a `tsdb` index with a `boltdb-shipper` one).
This PR changes this to a log line instead as we don't need to error and stop computation; it's better to return an empty overlap instead.
=> TSDB indexBuckets helper logs instead of errors

docs/sources/upgrading/_index.md, production/ksonnet/loki/memcached.libsonnet
This PR enables the [TopologySpreadConstraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) for Memcached chunks cache introduced at https://github.com/grafana/jsonnet-libs/pull/832.
Now the chunks cache will be evenly spread across nodes but more than one cache can run on the same node.
**Checklist**
=> Evenly spread memcached across nodes

production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml
A recent PR (https://github.com/grafana/loki/pull/7137) was merged to make the server settings more configurable in the helm chart. This PR fixes a few style nits with that PR, mainly:
* Name the config block the same as the header in the actual loki config file (in this case, `server` not `serverConfig`)
* Use `with`, and wrap around the header in the config file so the entire section is omitted if empty, rather than setting an empty object under the header.
=> Bring addition of server config into existing style

clients/pkg/promtail/targets/file/filetargetmanager.go, docs/sources/clients/promtail/configuration.md
make promtail scrape logs of pod with speciifc field or label selector, so that it will watch less logs and make fewer calculations and get a better performance in some scenarios.
for example, we only want to scape the pods in a specific namespace or with specific label in other namespaces
```
- job_name: lcc-system-pods
pipeline_stages:
{{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
kubernetes_sd_configs:
- role: pod
selectors:
- role: pod
field: metadata.namespace=lcc-system
relabel_configs: ....
-  job_name: lcc-pods-not-in-lcc-system
pipeline_stages:
{{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
kubernetes_sd_configs:
- role: pod
selectors:
- role: pod
field: metadata.namespace!=lcc-system
label: …
```
=> support custom label selector in kubernetes_sd_configs

operator/CHANGELOG.md, operator/internal/manifests/config.go, operator/internal/manifests/config_test.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml, operator/internal/manifests/internal/config/loki-runtime-config.yaml, operator/internal/manifests/internal/config/options.go
Expanding on #7106 this PR adds per-tenant retention rules into the configuration generator. The per-tenant retention will also work when no global retention rules are defined, falling back to Loki's defaults (currently 31 days of retention).
[LOG-2681](https://issues.redhat.com/browse/LOG-2681)
**Checklist**
=> operator: Write configuration for per-tenant retention

production/helm/loki/templates/_helpers.tpl
Using Azure Object Storage worked before Helm chart version 3.0.
Fixes #7090
=> [helm] Storage: Read support for Azure Object Storage

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/http_test.go
Adds a test case for concurrent pushes (which would have spotted a bug in https://github.com/grafana/loki/pull/5248) and a test case for tolerance regarding replication factor.
The PR also replaces the mock ring with an actual in-memory kv store ring.
And variables and function names were changed to meet Loki/logs terminology.
**Checklist**
=> Update distributor push tests

.gitignore, CONTRIBUTING.md
For a new contributor (which I am :tada:), the `CONTRIBUTING.md` file might seem a bit vague in regard to why we need to use the `GOPATH`-scoped Loki repository to contribute. The rationale is now given (If I've missed any other reasons, please tell me).
* Fixed wrong level title,
* Added information about local workflow when dealing with locally modified dependencies,
* Added references to Go 1.18 workspaces.
I'm not a native English-speaker feel free to tell me if I've made any mistake.
=> Guidelines: Update CONTRIBUTING.md

pkg/storage/store.go, production/loki-mixin-compiled/dashboards/loki-reads.json, production/loki-mixin-compiled/dashboards/loki-writes.json, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet
In PR #7154, I refactored the code also to measure the latency on index write requests. 
This PR adds the index requests panel to the Loki Reads/Writes dashboard.
=> add index requests panel to reads/writes dashboard

pkg/logql/downstream.go, pkg/logql/rangemapper_test.go, pkg/logql/shardmapper_test.go
This is mostly a quality of life improvement. Highly sharded subqueries can be burdensome to view and they're logged on every request. This PR will only display the first four subqueries in a `Concat{Log,Sample}Expr`, which is easier on the eyes when viewing logs and is more efficient.
=> highly sharded subqueries are ellided in expr.String

pkg/querier/queryrange/split_by_interval.go, pkg/storage/stores/index/stats/stats.go, pkg/storage/stores/index/stats/stats_test.go, pkg/storage/stores/tsdb/compact_test.go, pkg/storage/stores/tsdb/compactor_test.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/index.go, pkg/storage/stores/tsdb/index_client.go, pkg/storage/stores/tsdb/index_client_test.go, pkg/storage/stores/tsdb/index_shipper_querier.go, pkg/storage/stores/tsdb/lazy_index.go, pkg/storage/stores/tsdb/multi_file_index.go, pkg/storage/stores/tsdb/multi_file_index_test.go, pkg/storage/stores/tsdb/multitenant.go, pkg/storage/stores/tsdb/single_file_index.go, pkg/storage/stores/tsdb/single_file_index_test.go, pkg/storage/stores/tsdb/util_test.go, pkg/util/time.go, pkg/util/time_test.go
Avoid using bloomfilters for chunks deduplication in tsdb `Stats` calls by avoiding fetching duplicate entries.
The idea is to split and align queries by [ObjectStorageIndexRequiredPeriod](https://github.com/grafana/loki/blob/61794710a720da135d8479b7c2f723c740e86404/pkg/storage/config/schema_config.go#L47) and make each split process chunks with a start time >= start time of the table interval.
In other terms, table interval that contains start time of the chunk, owns it.
For e.g. if the table interval is 10s, and we have chunks 5-7, 8-12, 11-13.
Query with range 6-15 would be split into 6-10, 10-15.
query1 would process chunks 5-7, 8-12 and query2 would process chunks 11-13.
This check is not applied for the first split so that we do not eliminate …
=> avoid using bloomfilters for chunks in stats calls by avoiding duplicates

production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/write/statefulset-write.yaml
just a simple modifikation to set automountServiceAccountToken on Container Level. ServiceAccount already has this setting
=> Helm: Make automountServiceAccountToken configurable

nix/build-vars.nix, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.lock, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/loki-canary/_helpers.tpl, production/helm/loki/templates/loki-canary/daemonset.yaml, production/helm/loki/templates/loki-canary/service.yaml, production/helm/loki/templates/loki-canary/serviceaccount.yaml, production/helm/loki/templates/monitoring/_helpers-monitoring.tpl, production/helm/loki/templates/monitoring/logs-instance.yaml, production/helm/loki/templates/monitoring/servicemonitor.yaml, production/helm/loki/templates/provisioner/_helpers.yaml, production/helm/loki/templates/provisioner/job-provisioner.yaml, production/helm/loki/templates/provisioner/role-provisioner.yaml, production/helm/loki/templates/provisioner/rolebinding-provisioner.yaml, production/helm/loki/templates/provisioner/serviceaccount-provisioner.yaml, production/helm/loki/templates/tokengen/job-tokengen.yaml, production/helm/loki/values.yaml, tools/dev/k3d/Makefile, tools/dev/k3d/environments/enterprise-logs/main.jsonnet, tools/dev/k3d/environments/enterprise-logs/spec.json
This PR adds the Loki canary as well as the GEL provisioner to the Loki helm chart. The Loki canary expands the self-monitoring functionality of the Helm chart, giving operators insight beyond whether Loki is just running, but also if it's functioning properly.
The GEL provisioner was necessary for the canary to work when the enterprise option (`enterprise.enabled = true`) is enabled. Since enabling enterprise in the helm chart also enables auth/multi-tenancy, the addition of the provisioner allows the helm chart to automatically create a tenant for the canary via the GEL admin API, and to create applicable access policies and tokens. Furthermore, additional tenants can also be specified, which will be provisioned, creating a read and write token …
=> [helm] Add Loki Canary to Helm Chart

production/helm/loki/README.md.gotmpl, production/helm/loki/values.yaml
The gateway in non-enterprise mode doesn't expose Prometheus endpoint for alerts/rules so Grafana fails to query and display them in alerting section.
**Note**: When comparing **nginxConfig** enterprise vs non-enterprise there are a couple of other endpoints which are missing from the gateway config.
**Which issue(s) this PR fixes**: N/A
**Checklist**
=> Helm: expose Prometheus-compatible endpoints in gateway

production/helm/loki/README.md, production/helm/loki/README.md.gotmpl, production/helm/loki/values.yaml
Enables configuring various `ruler` options like alertmanager url.
`rulerConfig` is added second in the template so users can override the `storage` config if necessary.
Have seen questions in community Slack asking how to get filesystem support and alertmanager back when migrating from the old loki helm which should now be possible.
**Which issue(s) this PR fixes**: N/A
**Checklist**
=> Helm: add support for configuring ruler

production/ksonnet/loki/overrides-exporter.libsonnet
Currently the overrides exporter uses 200 vCPUs due to a missing `m` unit indicating "milli-CPUs".
N/A
**Checklist**
=> Jsonnet: fix overrides exporter to use correct CPU limits

pkg/loki/modules.go, pkg/storage/config/schema_config.go, pkg/storage/config/schema_config_test.go
`tsdb` index store supports deletion of data, but we had missed enabling the creation of delete requests client, which is required for query time filtering of data requested for deletion. This PR takes care of it.
I have also removed some unused code and adjusted the tests accordingly.
**Checklist**
=> tsdb supports data deletion, this PR takes care of todo to enable delete request client for tsdb

docs/sources/fundamentals/_index.md, docs/sources/maintaining/_index.md, docs/sources/operations/_index.md
Three docs index pages are dead ends - they are either blank or have no links. In lieu of more detailed content, this PR populates these pages with `{{< section >}}` shortcodes that automatically generate TOC-like links to subpages.
N/A
`{{< section >}}` is used in grafana/grafana docs, but I don't see any usage in grafana/loki. If this doesn't work, replace the shortcodes with manual lists of subpages.
**Checklist**
=> Docs: Populate empty index pages

operator/CHANGELOG.md, operator/internal/manifests/ruler.go
Adds missing GRPC TLS client configuration for the ingester and boltdb-shipper clients used by the ruler. This is a follow-up fix for #6224
**Checklist**
=> operator: Fix ruler grpc tls client configuration

clients/pkg/logentry/metric/metricvec.go, clients/pkg/logentry/stages/metrics_test.go
Promtail allows ingested log entries to be modified before pushing them to Loki with the use of pipelines. One of the available pipeline "stages" is called `metrics`, and allows extracting metrics from incoming logs. These metrics are labeled with the labels available in the processed `Entry`. There's some edge cases in which if either a entry label is invalid, or it starts with the prometheus internal label prefix, `__`, calling the promtail `/metrics` fails.
One way to easily reproduce this is by having the following configuration:
```yaml
pipeline_stages:
- static_labels:
good_label: "1"
- tenant:
value: "2"
- metrics:
loki_count:
type: Counter
description: "should count all entries"
config:
match_all: true
action: inc
```
Which exposes a …
=> Fix promtail `metric` stage causing failure when getting extracted metrics

operator/apis/loki/v1/lokistack_types.go, operator/internal/handlers/internal/storage/ca_configmap.go, operator/internal/handlers/internal/storage/ca_configmap_test.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/handlers/lokistack_create_or_update_test.go, operator/internal/manifests/storage/configure.go, operator/internal/manifests/storage/configure_test.go, operator/internal/manifests/storage/options.go
Signed-off-by: Shweta Padubidri <spadubid@redhat.com>
This PR supports bringing up Loki in a cluster that runs behind a proxy
It also adds support to provide proxy certificates to support secure traffic behind a proxy in a cluster. 
**Checklist**
=> operator: Add support for certificates to allow external S3 storage connections

production/loki-mixin-compiled-ssd/dashboards/loki-deletion.json, production/loki-mixin-compiled/dashboards/loki-deletion.json, production/loki-mixin/dashboards/loki-deletion.libsonnet
Add a panel for the deletions in progress (which is received - processed). This is similar to the existing 'Number of pending requests' only panel but seems more reliable. I'll remove one later after this has been running for a while. 
Add some compactor CPU, memory and processing duration statistics so you can see how the compactor is doing.
**Checklist**
=> Update deletions dashboard

pkg/distributor/distributor_ring.go
Passes the correct `heartbeat_timeout` to the created lifecycler config in distributor ring construction. When we didn't include this, it would create a visual bug incorrectly marking many distributors as unhealthy when in fact they were in fine condition. Including 
The _lifecycler_ `heartbeat_timeout` is _only_ referenced in the status page [here](https://github.com/grafana/loki/blob/74c8cf03ba4fb2abd979a9af05bb945813a4505c/vendor/github.com/grafana/dskit/ring/lifecycler.go#L892-L894). The _ring_ `heartbeat_timeout` continues to be updated correctly.
=> correct heartbeat timeout to distributor lifecycler for ring page

pkg/ingester/instance.go, pkg/ingester/rate_calculator.go, pkg/ingester/rate_calculator_test.go, pkg/ingester/stream.go, pkg/ingester/streams_map.go, pkg/logproto/logproto.proto
Stop the rateCalculator timer when stream is about to be removed.
N/A
=> Ingester stream api stop

clients/pkg/promtail/targets/gcplog/push_target_test.go, clients/pkg/promtail/targets/gcplog/push_translation.go, clients/pkg/promtail/targets/heroku/target.go, clients/pkg/promtail/targets/heroku/target_test.go
Some Promtail targets that support pushing logs through HTTP, allow using a specific header for writing logs for multiple tenants. This log is propagated through a Promtail internal label, that is then consumed by the remote write client.
If Promtail is used in a multi-tenant manner, it'd be nice to somehow be able to track how much is each tenant's share from the logs received. This PR exposes the received tenant id value through relabeling. 
This allows for example, keeping it as a label and exposing a metric though the `metrics` pipeline stage, which can be segregated by tenant.
Related to https://github.com/grafana/cloud-onboarding/issues/2067
**Checklist**
=> Expose tenant ID through relabel in push promtail targets

clients/pkg/promtail/targets/file/decompresser.go, docs/sources/clients/promtail/_index.md
Change Promtail compression support max line size to 2MB instead of 4096 bytes (~4KB).
This however doesn't change the default buffer size.
4096 bytes means we can't ever have a buffer size bigger than ~4KB but since the default mem page size is 4096 ([source](https://unix.stackexchange.com/questions/128213/how-is-page-size-determined-in-virtual-address-space)), we end up ignoring all lines.
=> Promtail: Change max support compressed line size to be 2MB

clients/pkg/promtail/targets/gcplog/pull_target_test.go, integration/client/client.go, integration/cluster/cluster.go, integration/loki_micro_services_delete_test.go, integration/loki_micro_services_test.go, integration/loki_simple_scalable_test.go, integration/loki_single_binary_test.go
- Reduce flakiness of GCPLog tests by reusing context and stopping GCP topic
- Reduce flakiness of integration tests by:
- using port as they're assigned
- reusing context
- adding timeout to calls (hence, if something get stuck, tests fail earlier)
=> Tests: Reduce flakiness of GCPLog and integration tests

production/loki-mixin-compiled-ssd/dashboards/loki-logs.json, production/loki-mixin-compiled-ssd/dashboards/loki-operational.json, production/loki-mixin-compiled-ssd/dashboards/loki-retention.json, production/loki-mixin-compiled/dashboards/loki-logs.json, production/loki-mixin-compiled/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-retention.json, production/loki-mixin/dashboards/dashboard-loki-logs.json, production/loki-mixin/dashboards/dashboard-loki-operational.json, production/loki-mixin/dashboards/dashboard-utils.libsonnet, production/loki-mixin/dashboards/loki-operational.libsonnet
Grafana Cloud integration have the convention to name data source variables after `<type>_datasource`. That means `$logs` should become `loki_datasource`.
=> [Mixin] Rename `logs` template variable to `loki_datasource`.

docs/sources/configuration/_index.md
Hello, 🖖 
I spotted a typo in the loki documentation in the ingester section regarding the `replication_factor` option.
https://grafana.com/docs/loki/latest/configuration/#ingester
For the typo :
```
[replication_factor: <int> | default = 3]
```
should be :
```
[replication_factor: <int> | default = 3]
```
You're awesome <3
**Checklist**
- [] Reviewed the `CONTRIBUTING.md` guide
- [] Documentation added
- [] Tests updated
- [] `CHANGELOG.md` updated
- [] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> fix/docs: Fixed a typo in the ingestor section

CHANGELOG.md, pkg/logql/rangemapper.go, pkg/logql/rangemapper_test.go, pkg/logql/shardmapper_test.go
The new expression type VectorExpr introduced recently in [PR](https://github.com/grafana/loki/pull/7007), is not taken into account in the query mapping in the AST mapper rangemapper. 
The AST mapper shardmapper was updated in [PR](https://github.com/grafana/loki/pull/7045).
**Checklist**
=> Fix rangemapper with VectorExpr support

clients/pkg/promtail/targets/file/filetarget_test.go, clients/pkg/promtail/targets/gcplog/pull_target.go, clients/pkg/promtail/targets/gcplog/pull_target_test.go, clients/pkg/promtail/targets/gcplog/push_target.go, clients/pkg/promtail/targets/gcplog/push_target_test.go, clients/pkg/promtail/targets/gcplog/target_test.go
Follow-up of https://github.com/grafana/loki/pull/7273
* Tune a filetarget test to remove created files to guarantee that all tailers are interrupted/fred
* Call pubsub close for our GCP `pull target`
* Append testName to the job names used in GCP tests. This will help us to identify which tests are struggling.
=> Tests: Improve several tests behavior

operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
* Updates the max supported OCP version to 4.12
* Fixes https://issues.redhat.com/browse/LOG-3120
**Checklist**
=> operator: Prepare bundle for openshift-logging release 5.6

production/loki-mixin-compiled-ssd/dashboards/loki-deletion.json, production/loki-mixin-compiled/dashboards/loki-deletion.json, production/loki-mixin/dashboards/loki-deletion.libsonnet
Add 2 panels to the deletion dashboard that show:
- the in progress/finished delete requests during the selected period
- the delete request that have been entered, with the query
This will help with trouble-shooting deletions.
**Checklist**
=> Add list of delete requests to deletion dashboard

pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/shipper/shipper_index_client.go
As all flags defined for `TSDBShipperConfig` are already prefixed by a dot, suffixing tsdb with one makes it redundant.
```
-tsdb..shipper.active-index-directory string
-tsdb..shipper.cache-location string
-tsdb..shipper.cache-ttl duration
-tsdb..shipper.index-gateway-client.grpc.backoff-max-period duration
-tsdb..shipper.index-gateway-client.grpc.backoff-min-period duration
-tsdb..shipper.index-gateway-client.grpc.backoff-on-ratelimits
-tsdb..shipper.index-gateway-client.grpc.backoff-retries int
-tsdb..shipper.index-gateway-client.grpc.grpc-client-rate-limit float
-tsdb..shipper.index-gateway-client.grpc.grpc-client-rate-limit-burst int
-tsdb..shipper.index-gateway-client.grpc.grpc-compression string …
```
=> Fix typo in flags definitions

pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_loader.go, pkg/util/server/middleware.go
We check the cache number (incremented by deletes) after executing a query with the value returned by the queriers which executed it. If they’re different, we know we can’t safely cache. However, we’re never actually returning a number from the queriers. This means that as soon as this cache number is incremented by a delete, it’ll disable the results cache for that tenant completely.
I suspect this has been a latent bug since we forked cortex (goes back to missing some code from this [PR](https://github.com/cortexproject/cortex/pull/2279) into cortex from @sandeepsukhani  back in the day!). It just showed itself once we started using deletes.
=> Bugfix include cache generations on querier response

clients/pkg/promtail/config/config.go, clients/pkg/promtail/limit/config.go, clients/pkg/promtail/positions/positions.go, clients/pkg/promtail/scrapeconfig/scrapeconfig.go, clients/pkg/promtail/targets/file/filetarget.go
Added mapstructure tags to configs structs to promtail client. It is needed for [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib). I working on adding promtail receiver component there. Opentelemetry collector decodes configs with mapstructure
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9800
**Checklist**
=> Added mapstructure tag to promtail configs structs

pkg/querier/queryrange/metrics.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/querier/queryrange/queryrangebase/results_cache_test.go, pkg/querier/queryrange/roundtrip.go
Followup to https://github.com/grafana/loki/pull/7300 which gives more metric visibility into the underlying errors when comparing cache key versions on the queriers vs query frontends.
=> adds result cache key version comparison metrics

tools/lambda-promtail/lambda-promtail/s3.go
Regex in lambda promtail looks for specific file patterns for reading and pushing logs from it.
It currently does not read logs generated by nlb i.e having `_net` in the name. This PR updates the regex.
Cross checked it with was docs here https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html
=> update regex for matching nlb logs while using lambda promtail

pkg/ruler/rulestore/configdb/store.go
Preallocate memory instead of enforcing an incremental growth. This will result in less work for the garbage collector.
none
**Checklist**
trivial fix - no update of Documentation required
trivial fix - no update of `CHANGELOG.md` required
=> pkg/ruler/rulestore/configdb: Preallocate memory

operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/development/manager_related_image_patch.yaml, operator/config/overlays/openshift/manager_related_image_patch.yaml, operator/config/overlays/production/manager_related_image_patch.yaml, operator/internal/manifests/config.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml, operator/internal/manifests/internal/config/options.go
Upgrade the operand Loki from v2.6.1 temporarily to `main-ec0bf70` to include 2.7.0 targeted features for the operator development:
- https://github.com/grafana/loki/pull/7069
- https://github.com/grafana/loki/pull/7085
- https://github.com/grafana/loki/pull/7227
**Checklist**
=> operator: Move Loki operand from v2.6.1 to main-ec0bf70

clients/cmd/promtail/main.go, clients/pkg/logentry/stages/drop_test.go, clients/pkg/logentry/stages/labelallow_test.go, clients/pkg/logentry/stages/labeldrop_test.go, clients/pkg/logentry/stages/multiline_test.go, clients/pkg/logentry/stages/pack_test.go, clients/pkg/promtail/targets/lokipush/pushtarget.go, clients/pkg/promtail/targets/windows/target_test.go, cmd/logql-analyzer/main.go, cmd/loki/main.go, cmd/querytee/main.go, go.mod, go.sum, pkg/loki/loki.go, pkg/storage/stores/indexshipper/compactor/retention/util_test.go, pkg/storage/stores/shipper/index/compactor/util_test.go, pkg/util/log/log.go, vendor/github.com/go-kit/log/line_buffer.go, vendor/modules.txt
We initialise a global logger in `pkg/util/log/log.go` and use it extensively throughout the Loki codebase. Every time we write a log message, a `write` syscall is invoked. Syscalls are problematic because they transition the process from userspace to kernelspace, which means:
- a context-switch is incurred, which is inherently expensive ([1-2 microseconds](https://eli.thegreenplace.net/2018/measuring-context-switching-and-memory-overheads-for-linux-threads/))
- the goroutine executing the code is **blocked**
- the underlying OS thread (_M_ in the go scheduler model) is **also blocked**
- the goroutine has to be rescheduled once the syscall exits
- the go scheduler may need to spawn additional OS threads if all are blocked in syscalls - which can …
=> Use a line-buffered logger to deamplify write syscalls

CHANGELOG.md, pkg/loki/loki.go, pkg/loki/loki_test.go
The following PR adds a fix for setting up the internal server module for the query-frontend-tripperware instead for the query-frontend. Solves issue as:
```
level=info ts=2022-10-04T12:14:37.375681075Z caller=main.go:103 msg="Starting Loki" version="(version=main-ec0bf70, branch=main, revision=ec0bf7004)"
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2f8 pc=0x1d034d3]
goroutine 1 [running]:
github.com/grafana/loki/pkg/loki.(*Loki).initQueryFrontend(0xc000c10000)
/src/loki/pkg/loki/modules.go:738 +0x5b3
github.com/grafana/dskit/modules.(*Manager).initModule(0xc00000c330, {0x7ffd008d08b3, 0xe}, 0x1?, 0xc000c0e600?) …
```
=> Fix internal server bootstrap for query frontend

.drone/drone.jsonnet, .drone/drone.yml, docs/sources/maintaining/release-loki-build-image.md, loki-build-image/Dockerfile
Updated the `loki-build-image` to Go 1.19.2 as a precursor for https://github.com/grafana/loki/pull/7243.
=> Updating loki-build-image to Go 1.19

CHANGELOG.md, docs/sources/tools/logcli.md
This documents the existing command completion that kingpin provides (docs [here](https://github.com/alecthomas/kingpin#bashzsh-shell-completion) on that).
Fixes #2949
Please feel free to adjust/reword any of this! I thought I would give it a shot. I ran `make docs` too, and confirmed the formatting looked good. Hugo even indented the code blocks under the bullet points. :open_mouth: 
**Checklist**
=> docs: Document setting up command completion for logcli

operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/openshift/manager_related_image_patch.yaml
Follow-up on #7298 to use the CI-published image for OpenShift bundle.
**Checklist**
=> operator: Use quayio v2.7.0-pre image for openshift overlay

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
Currently the `loki-build-image` has a version of golangci-lint which is based on Go 1.18.
[This issue](https://drone.grafana.net/grafana/loki/16278/2/9) has arisen in our CI: https://github.com/golangci/golangci-lint/issues/3107
=> Patching loki-build-image with latest golangci-lint version

tools/lambda-promtail/README.md, tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/promtail.go, tools/lambda-promtail/main.tf, tools/lambda-promtail/template.yaml, tools/lambda-promtail/variables.tf
It adds bearer token support for lambda-promtail, as it supports only http basic auth.
**Checklist**
=> feat(lambda-promtail): add bearer token support

pkg/storage/stores/tsdb/compact_test.go, pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/identifier.go, pkg/storage/stores/tsdb/index/index.go, pkg/storage/stores/tsdb/manager.go, pkg/storage/stores/tsdb/single_file_index.go, pkg/storage/stores/tsdb/util_test.go
In PR #7321, we re-introduced mmap for reading tsdb index, but it does not cover all the paths where we open the index. This PR takes care of it.
I have also removed the code for decompressing the index file since we always get a decompressed file from the `indexshipper`.
=> mmap tsdb index file while opening it for querying

.golangci.yml, clients/cmd/fluent-bit/out_grafana_loki.go, clients/pkg/logentry/stages/metrics.go, clients/pkg/logentry/stages/pack.go, clients/pkg/promtail/client/client.go, clients/pkg/promtail/targets/lokipush/pushtarget.go, clients/pkg/promtail/targets/syslog/transport.go, pkg/canary/reader/reader.go, pkg/distributor/distributor.go, pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/logql/log/parser_hints.go, pkg/logql/rangemapper.go, pkg/logqlmodel/stats/context.go, pkg/querier/astmapper/shard_summer.go, pkg/querier/astmapper/subtree_folder.go, pkg/querier/worker_service.go, pkg/ruler/base/error_translate_queryable.go, pkg/ruler/base/ruler.go, pkg/ruler/rulestore/local/local.go, pkg/storage/chunk/client/baidubce/bos_storage_client.go, pkg/storage/stores/shipper/index/compactor/compacted_index.go, pkg/storage/stores/shipper/index/compactor/table_compactor.go, pkg/storage/stores/tsdb/manager.go, pkg/util/flagext/bytesize.go, pkg/util/log.go, pkg/util/log/log.go, pkg/util/log/wrappers.go, pkg/util/marshal/legacy/marshal.go
I removed these checks in https://github.com/grafana/loki/pull/7337 to not make https://github.com/grafana/loki/pull/7243 overly complex to review.
Refactored code to fix valid lint issues, ignored the irrelevant/dangerous ones.
I also removed `unused` and `unparam` as these produce low-quality results that are largely useless.
N/A
I'd suggest reviewing with whitespace ignored, since a lot of these stupid lints were just whitespace fixes.
=> Restoring lint checks that were previously disabled

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Adds the handling of negative/zeroed desired rate to our distributor stream sharding. Without this, invalid desired rates results in a -Inf number of shards. This also adds a log line to report that such a thing happened.
=> Loki: Add sharding support for negative/zeroed desired rate

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md
Bumped version of the chart and added changelog. 
These changes were missed in https://github.com/grafana/loki/pull/7301
=> [loki helm chart] fixed to pass CI

CHANGELOG.md, docs/sources/installation/local.md
The config file URL mentioned in the docs contain config options that doesn't match the latest version of Loki, which, as of now, is v2.6.1.
Fixes #6915 
Disclaimer: I am a Grafanista from k6.
**Checklist**
=> Clarify how and where to download the Loki config file from

.github/workflows/operator-bundle.yaml, .github/workflows/operator-scorecard.yaml, .github/workflows/operator.yaml
Update GH workflows for the operator submodule to use go 1.19. Follow up on #7243 
**Checklist**
=> Upgrade operator gh workflows to go1.19

examples/README.md, examples/promtail-heroku/Dockerfile, examples/promtail-heroku/README.md, examples/promtail-heroku/config.yml, examples/promtail-heroku/heroku.yml
Some weeks ago a blogpost was written on how to configure Promtail to receive logs from Heroku, and write them to Loki. This blogpost contains some configuration snippets like a Promtail config, a Dockerfile, etc. It's been mentioned is annoying to copy and paste the snippets from there, so this PR adds this snippets under the `examples/` folder, so that they are easily readable and iterated if necessary.
N/A
**Checklist**
=> Adding Promtail and Heroku blogpost files to `examples/`

production/loki-mixin-compiled-ssd/dashboards/loki-logs.json, production/loki-mixin-compiled-ssd/dashboards/loki-mixin-recording-rules.json, production/loki-mixin-compiled-ssd/dashboards/loki-operational.json, production/loki-mixin-compiled-ssd/dashboards/loki-writes-resources.json, production/loki-mixin-compiled/dashboards/loki-chunks.json, production/loki-mixin-compiled/dashboards/loki-logs.json, production/loki-mixin-compiled/dashboards/loki-mixin-recording-rules.json, production/loki-mixin-compiled/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-reads-resources.json, production/loki-mixin-compiled/dashboards/loki-reads.json, production/loki-mixin-compiled/dashboards/loki-writes-resources.json, production/loki-mixin-compiled/dashboards/loki-writes.json, production/loki-mixin/dashboards/dashboard-loki-logs.json, production/loki-mixin/dashboards/dashboard-loki-operational.json, production/loki-mixin/dashboards/loki-chunks.libsonnet, production/loki-mixin/dashboards/loki-logs.libsonnet, production/loki-mixin/dashboards/loki-operational.libsonnet, production/loki-mixin/dashboards/loki-reads-resources.libsonnet, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-writes-resources.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet, production/loki-mixin/dashboards/recording-rules.libsonnet, production/promtail-mixin/jsonnetfile.lock.json
Mostly related to the job selector; I deployed these against a local grafana instance along the way and I think I got everything correct but we might still need to update some of these again.
=> [dashboards] update dashboards for zone aware ingesters

pkg/storage/stores/tsdb/head.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go, pkg/storage/stores/tsdb/head_wal.go, pkg/storage/stores/tsdb/head_wal_test.go, pkg/storage/stores/tsdb/manager.go, pkg/storage/stores/tsdb/single_file_index_test.go, pkg/storage/stores/tsdb/store.go
This PR does two things:
* Includes the series fingerprint in TSDB WALs. Doing this ensures we recover fingerprint used in chunk addresses after restart even if loki is upgraded and the label hashing algorithm changes.
* Removes much of the extra hashing in the TSDB write path + manager. Occasionally, the fingerprint may be different than the hash of labels. Historically this has happened in a few places:
* When the `__name__="logs"` label was injected for non-tsdb indices (not applicable to TSDB)
* When building a multitenant tsdb index and adding a synthetic `__loki_tenant__` label
* In a previous bug(https://github.com/grafana/loki/pull/7355) when empty label values altered calculated fingerprints.
Explicitly storing/retrieving the desired fingerprint throughout helps avoid calculating …
=> TSDB explicit fingerprint

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/index_set_test.go, pkg/storage/stores/indexshipper/downloads/table_manager_test.go, pkg/storage/stores/indexshipper/downloads/table_test.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/indexshipper/uploads/index_set.go, pkg/storage/stores/indexshipper/uploads/index_set_test.go, pkg/storage/stores/indexshipper/uploads/table.go, pkg/storage/stores/indexshipper/uploads/table_manager.go, pkg/storage/stores/indexshipper/uploads/table_manager_test.go, pkg/storage/stores/indexshipper/uploads/table_test.go, pkg/storage/stores/shipper/index/querier.go, pkg/storage/stores/tsdb/index_shipper_querier.go
We noticed ingesters and index-gateways panicking when using `tsdb` as an index store with the latest build. This is caused by closing `mmap` while the index queries are still being processed. This PR takes care of it by locking the index until we are done querying the index.
**Checklist**
=> lock boltdb and tsdb index while queries are in process

docs/sources/installation/microservices-helm.md
correct indentation of `relabel_configs` to make it valid and consistent with https://grafana.com/docs/loki/latest/clients/promtail/scraping/#syslog-receiver
**Checklist**
=> documentation: correct yaml file

production/loki-mixin/dashboards.libsonnet, production/loki-mixin/dashboards/loki-canary-dashboard.libsonnet, production/loki-mixin/jsonnetfile.json, production/loki-mixin/jsonnetfile.lock.json
Summary:
This imports our canary into the Loki mixin so it can be used by the Helm chart. The dashboard is disabled by default. It can be enabled by setting
```jsonnet
{
_config+:: {
canary+: {
enabled: true,
},
},
}
```
=> Import Canary dashboard into Loki mixin.

production/helm/loki/src/alerts.yaml
The Helm Charts install the Loki canary. It should also install the alerts for the canary so the users get the full value.
Fixes #7284
**Checklist**
=> Provision alerts for Loki Canary in Helm Chart.

clients/cmd/promtail/main.go, docs/sources/clients/promtail/troubleshooting.md
Signed-off-by: Hemanth Krishna <hkpdev008@gmail.com>
Adds `-check-syntax` to promtail which will exit just by validating the
config file
- Fixes #6862 
**Checklist**
=> area(promtail): add -check-syntax functionality

CONTRIBUTING.md
Markdown fixes to the `CONTRIBUTING.md` layout.
**Checklist**
=> CONTRIBUTING: fix layout

docs/sources/clients/promtail/scraping.md
Currently the `Cloudflare` link refers to: https://grafana.com/docs/loki/latest/clients/configuration/#cloudflare
But it should be: https://grafana.com/docs/loki/latest/clients/promtail/configuration/#cloudflare
**Checklist**
=> promtail/scraping.md: Fix 404

CHANGELOG.md, clients/pkg/promtail/targets/docker/target_group.go, docs/sources/upgrading/_index.md
Discovering a new node is not an error, so having it send errors to dashboards is confusing.
**Checklist**
=> logging: Change Docker target discovery log level from Error to Info

pkg/chunkenc/memchunk_test.go
Use Go runtime facilities to report MB/s for each operation and compression ratio.
Before:
```
BenchmarkWrite/ordered-none-4               1018           1104885 ns/op         1431962 B/op         33 allocs/op
BenchmarkWrite/ordered-gzip-4                 12          87333201 ns/op         3516699 B/op        696 allocs/op
BenchmarkWrite/ordered-lz4-64k-4              51          21483048 ns/op         3095117 B/op        649 allocs/op
```
After:
```
BenchmarkWrite/ordered-none-4                841           1202007 ns/op        1054353.53 MB/s        101.9 %compressed         1569953 B/op         34 allocs/op
BenchmarkWrite/ordered-gzip-4                 13          86299699 ns/op        3357.25 MB/s             6.891 %compressed       3778896 B/op …
```
=> chunks: improve readability of compression benchmarks

CHANGELOG.md, docs/sources/operations/observability.md, docs/sources/upgrading/_index.md, pkg/util/log/log.go
Renames the metric 'loki_log_messages_total' to a more descriptive name. 
Keeps and deprecates the previously existing metric to not break functionality.
Fixes #7088 
**Checklist**
=> Loki: Renames metric 'loki_log_messages_total' to 'loki_internal_log_messages_total'

production/helm/loki/README.md, production/helm/loki/values.yaml
I want to disable usage reporting to Grafana. On clusters that don't have access to Internet it generates error logs.
And without this patch, the only way is to have the whole `loki.config` section in my custom values file.
**Checklist**
=> [helm loki] add support for custom analytics config

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ratestore.go, pkg/distributor/ratestore_metrics.go
Promtail doesn't add a stream hash to push requests. As a result, we weren't accounting for the current rate in our sharding calculation and only sharding on individual large pushes. 
This PR ensures that streams have a hash as they're ingested. It also add a couple of metrics that were useful in debugging this issue.
=> Fix stream sharding

.github/workflows/syft-sbom-ci
Adds a GitHub action to automatically build an SPDX SBOM report when a release is created. This action will automatically attach an SPDX JSON report to the release assets. 
We've implemented this in OSS Grafana, see here for an example. 
https://github.com/grafana/grafana/actions/workflows/sbom-report.yml
@dannykopping This might be of interest to you 👍 
**Checklist**
=> Create automated SBOM reports on Release

clients/pkg/promtail/targets/lokipush/pushtargetmanager.go, clients/pkg/promtail/targets/lokipush/pushtargetmanager_test.go
The current promtail scrapeConfig jobName validation only sanitizes empty spaces. If special characters are introduced it causes a panic. The implemented fix uses the label sanitzer in the strutil package.
Fixes #7275
Not sure if I described things correctly in the PR title, I'm very new to Loki in general.
**Checklist**
=> Fix promtail scrape config job name validation

CHANGELOG.md, cmd/loki-canary/main.go, docs/sources/operations/loki-canary.md
This change allows client certificates signed by a self-signed certificate authority to be used by the Loki canary.
Fixes #4366 
This has been tested on linux amd64 with self-signed certificates.
**Checklist**
=> [loki-canary] Allow insecure TLS connections

clients/pkg/promtail/promtail.go
When promtail reload config.yaml, simplify log print, only print hash.
Hash function Use the same hash function as prometheus.
/github.com/prometheus/prometheus/model/labels/labels.go
```go
import  "github.com/cespare/xxhash/v2"
func (ls Labels) HashWithoutLabels(b []byte, names ...string) (uint64, []byte) {
...
return xxhash.Sum64(b), b
}
```
`level=info ts=2022-10-12T14:40:05.323235834Z caller=promtail.go:122 msg="Reloading configuration file" newConf="server:\n  http_listen_network: tcp\n  http_listen_address: \"\"\n  http_listen_port: 9082\n  http_listen_conn_limit: 0\n  grpc_listen_network: tcp\n  grpc_listen_address: \"\"\n  grpc_listen_port: 0\n …
=> [promtail] log:   simplify log, only print hash

docs/sources/operations/observability.md
Fixing the documentation about exposed promtail metrics for promtail_request_duration_seconds
No issue related
**Checklist**
=> promtail: Fix exposed metric documentation for request_duration_seconds

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
The tool `helm-docs`is required by the Helm Chart documentation overhaul. See #7034
**Checklist**
=> Add helm-docs to build image.

pkg/loki/loki.go, pkg/loki/loki_test.go
Makes adding the internal server modules to the module map more robust. The previous implementation accidentally dropped other modules.
**Checklist**
=> Fix enable of internal server for modules

pkg/ruler/base/mapper.go, pkg/ruler/base/mapper_test.go
Do not log 'unable to read rules directory' at startup if directory hasn't been created yet
mimir pr here:
https://github.com/grafana/mimir/pull/1058/files#diff-1b3ab3225a853e6d596155b5e713954df925e60df6b0826f7f851db243bca71e
Fixes #6069
**Checklist**
=> Do not log 'unable to read rules directory' at startup if directory hasn't been created yet

clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb
Like mentioned in https://github.com/grafana/loki/issues/5010 we also want to use line_format json but noticed that newlines in the message text would be escaped. This change will un-escape double-escaped control characters (applies for \n, \r, \s, \t) e.g. newline characters "\\\n" by "\n" in the record.
This will fix e.g. newline errors when parsing the JSON message later (for example Grafana Dashboard, which shows newline errors otherwise).
Fixes https://github.com/grafana/loki/issues/5010
**Checklist**
=> fluentd: Add un-escaping of control characters in JSON

operator/CHANGELOG.md, operator/internal/manifests/build.go, operator/internal/manifests/build_test.go
This PR fixes the error when using Custom profile on Openshift
Fixes [LOG-3186](https://issues.redhat.com/browse/LOG-3186)
@Red-GV Please review this 
**Checklist**
=> operator: Fix Custom TLS profile setting for LokiStack on OpenShift

docs/sources/tools/logcli.md
Adds a missing option for logcli.
**Checklist**
=> Add remote schema option

CHANGELOG.md, clients/cmd/promtail/main.go, clients/pkg/promtail/config/config.go, docs/sources/clients/promtail/configuration.md, pkg/tracing/config.go
We've been using Promtail's HTTP/gRPC server-based targets with real workloads for some weeks now. The server that these spin out is based on [weaveworks commons](https://github.com/weaveworks/common) HTTP/gRPC servers. These include by default some middlewares that if enabled, inject tracing support.
We found this useful when tracking down request handling time, or even more, if the caller also support Jaeger tracing support, cross-correlated requests between the upstream server and Promtail's.
This PR adds support for enabling tracing the same way Loki does. At the moment, this will just generate traces for the before-mentioned targets.
In the future, the quality and completeness of tracing support can grow organically to enrich spans.
**Which …
=> Promtail: Add basic tracing support

operator/.bingo/Variables.mk, operator/.bingo/operator-sdk.mod, operator/.bingo/operator-sdk.sum, operator/.bingo/variables.env
Upgrades local tool operator-sdk to v1.24.1 (See changelog: https://github.com/operator-framework/operator-sdk/releases/tag/v1.24.1)
**Checklist**
=> operator: Upgrade operator-sdk to v1.24.1

clients/pkg/promtail/targets/cloudflare/fields.go, docs/sources/clients/promtail/configuration.md
Add RequestHeaders and ResponseHeaders fields to the Cloudflare allFields list.
We want to log custom headers which are available on those fields.
**Special notes for your reviewer**: 
**Checklist**
=> Promtail: Add fields for cloudflare

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Modify sharding to assign random shards when the number of shards is bigger than the number of entries.
This helps us to avoid hot-spotting the first shards. Ex:
- Let's say we calculate the number of shards for a given stream to be 8, but we receive a push request for that same stream with only 3 entries. Previously, we would assign the 3 entries for the first 3 shards. That means that, if we regularly receive push requests for that stream with only 3 entries, the last 5 shards wouldn't receive any load. By randomizing the entries assignment we help spreading the load between all shards.
=> Loki: Implement random entries assignment when sharding

production/helm/loki/README.md, production/helm/loki/templates/tokengen/job-tokengen.yaml, production/helm/loki/values.yaml
Add an envFrom section to the tokengen job.
Fixes https://github.com/grafana/loki/issues/7411
**Checklist**
=> Add envFrom to the tokengen job

production/helm/loki/docs/examples/oss/overrides-oss-gcs.yaml
**What this PR does**:
Replace `loki.authEnabled` in one of the example override YAMLs with `loki.authEnabled` to match the actual key name. Also adds missing newline at end of file.
**Why we need it**:
As of today the example [production/helm/loki/docs/examples/oss/overrides-oss-gcs.yaml (permalink)](https://github.com/grafana/loki/blob/85e524788e9892c4413157ce07b516f88109c935/production/helm/loki/docs/examples/oss/overrides-oss-gcs.yaml) contains the following block:
```yaml
loki:
authEnabled: false
```
This is incorrect. There is no `authEnabled` in the `values.yaml`. It has to be `auth_enabled`.
Fixes #7409
**Checklist**
=> Helm: Replace incorrect key loki.authEnabled in example override values

production/helm/loki/templates/loki-canary/_helpers.tpl, production/helm/loki/templates/loki-canary/serviceaccount.yaml
Bring the Loki Canary service account in line with the Loki service account, removing the post install hook, and sharing the top level properties for `automountServiceAccountToken` and `imagePullSecrets`. I'm open to creating canary specific values for these setting if needed, but want to start by sharing the top level values to reduce config if possible.
Also default canary to Appversion to be in sync with default Loki version
Fixes two issues raised in comments from @towolf (thanks!) on this [PR](https://github.com/grafana/loki/pull/7173#issuecomment-1256410181).
Fixes #7237
=> [helm] Mimic loki service account with canary account

docs/sources/clients/promtail/configuration.md
Document `max_streams` configuration, introduced in 2.7.
=> Docs: Add max_streams to Promtail configuration doc

production/helm/loki/README.md, production/helm/loki/templates/loki-canary/daemonset.yaml, production/helm/loki/values.yaml
Adds flags to the helm charts that are needed when doing a zero-downtime migration from a `loki-distributed` helm chart deployment. The flags allow for an additional memberlist join member to be specified. This allows the new `grafana/loki` cluster to join the old `grafana/loki-distributed` cluster, forming one big cluster. The ingesters in the `grafana/loki-distributed` cluster can then be taken down 1-by-1, allowing the whole `grafana/loki-distributed` cluster to be deleted once all the ingesters have scaled down.
Documentation coming in a follow-up PR.
Fixes #7330
**Checklist**
=> [Helm] Add flags needed for migration from distributed

pkg/distributor/ratestore.go, pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/stream.go, pkg/ingester/stream_rate_calculator.go, pkg/ingester/stream_rate_calculator_test.go
Rather than iterating streams and getting rates per stream, keep all necessary information in the rate calculator and just hand back the current rates when asked.
This change took p99 latencies from ~1.8s to ~400ms and p50 latences from ~1s to 6ms.
=> Improve rate store refresh latency

pkg/storage/stores/indexshipper/downloads/table.go
While I'm still in favor of a longer refactor to address the complexity described in https://github.com/grafana/loki/pull/7490, I'm opening this PR as a shorter, more immediate alternative that should fix the deadlocks. This also reduces the number of total lock calls in many cases as we lock to act over entire groups rather than individual items.
=> Index gw lock bugfix

pkg/logql/engine.go
There are cases where a query cannot finish (OOM of a querier/ruler) and most of our logs are emitted upon completion of a query. This can help us find queries which are OOM crashing a component.
Note: It only covers queries executed by the engine, so only instant and range queries. Another PR will be necessary to cover labels/series endpoints. However this approach seemed the best to be able to get this information from ruler executed queries.
**Checklist**
=> Loki: log when a query starts in the logql engine

pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/index/index.go
Previously when we were reading the whole tsdb index in memory, there was not much cleanup required after we were done with the index. Now that we are mmaping the tsdb index, we need to close the mmap.
I had missed calling `index.Close()` on the compacted-away multi-tenant index. This causes the compactor to retain the files on disk, leading to the compactor running away from disk space. This PR takes care of it.
While doing the changes, I noticed that some of the tests failed due to `LabelValues` tsdb implementation returning strings valid only until the underlying byte slice stays valid. Since the underlying byte slice could become invalid when we close the tsdb, we should return a copy instead of yolostring. This can also happen on the query path …
=> tsdb post compaction cleanup

production/loki-mixin-compiled-ssd/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-reads-resources.json, production/loki-mixin-compiled/dashboards/loki-writes-resources.json, production/loki-mixin/dashboards/dashboard-loki-operational.json, production/loki-mixin/dashboards/dashboard-utils.libsonnet, production/loki-mixin/dashboards/loki-operational.libsonnet, production/loki-mixin/dashboards/loki-reads-resources.libsonnet, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-writes-resources.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet
We are now accepting data through the internal gateway as well. This updates the dashboards to reflect that.
No alerts or recording rules reference `cortex-gw`. 
Does this need a CHANGELOG entry?
=> [mixin] Add cortex-gw-internal to dashboards

production/helm/loki/README.md, production/helm/loki/templates/monitoring/_helpers-monitoring.tpl, production/helm/loki/templates/monitoring/grafana-agent.yaml, production/helm/loki/templates/monitoring/metrics-instance.yaml, production/helm/loki/templates/monitoring/pod-logs.yaml, production/helm/loki/values.yaml, tools/dev/k3d/Makefile, tools/dev/k3d/environments/loki-distributed/spec.json
Previously users had to create their own `MetricsInstance` for the Grafana Agent operator to send metrics. This introduces the option for them to do so.
**Checklist**
=> Helm: Allow users to define remote write for metrics.

pkg/distributor/validator.go
Most of the time we don't need to create those strings which create an alloc per entry.
=> Improves performance of distributor validations

pkg/distributor/distributor.go
With zone awareness enabled we allow restarting multiple ingesters within a single zone at the same time, this means that for many more write requests there's potentially only 2 of the 3 replicas for a stream up at the time the write request is received. This lead to a large increase in 500s during rollouts. 
My suspicion is that the 500s on rollouts was always related to the following; the replica set ring code has something referred to as "extending the replica set". This essentially is the adding of ingesters in the ring that are not in an ACTIVE state (for example, are in LEAVING) to the set of replicas considered valid for an operation. Adding of the instance in a state other than ACTIVE can be controlled by using a different operation type, which Mimir was using but we were not. …
=> Hardcode ring.WriteNoExtend for distributor push operations

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
When using filesystem storage, there's a bug in the configmap helm template that sets `ruler.storage` to `null`. This fixes that bug.
Fixes #7267
**Checklist**
=> [Helm] Fix invalid ruler config when filesystem storage is used

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Pushing streams with unsorted labels to ingesters results in a bug where ingesters duplicate chunks for streams. This causes a memory leak and eventual OOM crash when ingesters recover from the WAL because one of the duplicate streams is orphaned.
This PR ensures that sharded streams have sorted labels to avoid this bug.
=> Ensure labels on sharded streams are sorted before they're sent anywhere

clients/pkg/promtail/promtail.go
This allows the reload metrics to be sent to a custom registerer, which is required for Grafana Agent to be able to use the Promtail code.
N/A 
Is it possible for us to cherry-pick this into k121? That's the version we're trying to update Grafana Agent to.
**Checklist**
=> promtail: register reload metrics after running options

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/index_set_test.go, pkg/storage/stores/indexshipper/downloads/table.go, pkg/storage/stores/indexshipper/downloads/table_manager.go, pkg/storage/stores/indexshipper/downloads/table_manager_test.go, pkg/storage/stores/indexshipper/downloads/table_test.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/indexshipper/uploads/index_set.go, pkg/storage/stores/indexshipper/uploads/index_set_test.go, pkg/storage/stores/indexshipper/uploads/table.go, pkg/storage/stores/indexshipper/uploads/table_manager.go, pkg/storage/stores/indexshipper/uploads/table_manager_test.go, pkg/storage/stores/indexshipper/uploads/table_test.go, pkg/storage/stores/shipper/index/querier.go, pkg/storage/stores/shipper/index/table_manager.go, pkg/storage/stores/shipper/index/table_manager_test.go, pkg/storage/stores/shipper/index/table_test.go, pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go, pkg/storage/stores/tsdb/index_client_test.go, pkg/storage/stores/tsdb/index_shipper_querier.go, pkg/storage/stores/tsdb/multi_file_index.go, pkg/storage/stores/tsdb/multi_file_index_test.go, pkg/storage/stores/tsdb/store.go
Inverts control in the `index-shipper` so consumers don't manage accesses to mutexes. This prevents deadlocks and no longer requires consumers have internal knowledge of the `index-shipper` itself.
This PR reverts a few previous attempts. Look at the last commit to see the net-additions.
TSDB previously didn't use mmap, which meant we could freely pass around TSDBs as `[]byte`. Since they were immutable, we didn't need to know when an underlying index was cleaned up/closed; this coordination was unnecessary and the garbage collector would clean up dangling memory for us. After introducing TSDB, we needed to control access to avoid use-after-free bugs. A few attempts at controlling this became increasingly complex & error prone. Instead of requiring _consumers_ to prevent deadlocks on …
=> Prevent IndexShipper from leaking mutex accesses.

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/shard_tracker.go, pkg/distributor/shard_tracker_test.go
To avoid hot spots, keep track of shard numbers across pushes. When tracking shard numbers across pushes, it's no longer necessary to randomize shards, in the case where the desired number of shards is greater than the number of entries. Instead, we just partition the entries among the shards in round robin fashion. Over time, this should give us a more even distribution of logs in shards, particularly for large streams that are made of small individual pushes.
=> Shard streams round-robin rather in batches. 

docs/sources/clients/promtail/gcplog-cloud.md
This PR is a follow up to the documentation added (https://github.com/grafana/loki/pull/7511) for configuring the infrastructure resources for shipping logs to the new-ish GCP Logs Push Promtail target. Terraform snippets are added for writing the same infrastructure in an as-code manner, which works better for infra folks.
**TODO**
**Checklist**
=> Add terraform snippets to Promtail GCP Logs documentation

pkg/canary/writer/writer.go
Fixes: #7142 (take a look for more details about the problem there)
After trying few things to avoid this race and discussin it with Ed, This small changes seems to be more accurate and seems to fix the issue.
This is unblocking rolling out new canary in our internal cells
Update: For some reason I thought the fix didn't fix the original issue when I tested it with internal loki dev cell, almost a month ago. But after testing it for more than 2hr on same cell. I realized it is working fine (will leave it for a day like this just to confirm)
Verified following:
```
{.... container="loki-canary"} |= "websocket missing"
```
and noticed it's happening no longer after the fix.
Also verified the metrics
``` …
```
=> fix(loki-canary): Send to Loki after updating `totalEntries`.

docs/sources/installation/helm/reference.md, production/helm/loki/templates/monitoring/metrics-instance.yaml, production/helm/loki/values.yaml
Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>
Chart version 3.3.0 introduced a new MetricsInstance CR. The only way to disable the MetricsInstance is `--set loki.monitoring.serviceMonitor.metricsInstance=null`, but this raises helm warning... 
```
coalesce.go:220: warning: cannot overwrite table with non table for loki.monitoring.serviceMonitor.metricsInstance (map[annotations:map[] labels:map[] remoteWrite:<nil>])
coalesce.go:220: warning: cannot overwrite table with non table for loki.monitoring.serviceMonitor.metricsInstance (map[annotations:map[] labels:map[] remoteWrite:<nil>])
coalesce.go:220: warning: cannot overwrite table with non table for loki.monitoring.serviceMonitor.metricsInstance (map[annotations:map[] labels:map[] …
```
=> [Helm] Add toggle for MetricsInstance

docs/sources/clients/promtail/gcplog-cloud.md
Some of the latest changes to the GCP Logs Promtial docs include an architecture diagram. It seems the link to this diagram is broken. This PR attempts to fix that by removing a relative routing the image tag path, since the image is deployed in [here](https://grafana.com/docs/loki/next/clients/promtail/gcp-logs-diagram.png), but was being fetched in this path: `https://grafana.com/docs/loki/next/clients/promtail/gcplog-cloud/gcp-logs-diagram.png`.
The img is deployed in the same directory as the site, so should use a `../` parent directory relative routing, as in [here](https://github.com/grafana/loki/blob/3d6210e424574ae3b5a9c111a7527f1159645436/docs/sources/clients/promtail/troubleshooting.md#L48).
Fixes #<issue …
=> Fix Promtail GCP Logs diagram route

docs/sources/installation/helm/_index.md, docs/sources/installation/helm/concepts.md
This PR fixes the hugo build used for published docs, as it was broken due to a link check inside some comments.
https://github.com/grafana/loki/actions/runs/3379539854/jobs/5611233373
n/a
**Checklist**
=> Fix Hugo build for docs

pkg/querier/queryrange/log_result_cache.go, pkg/querier/queryrange/log_result_cache_test.go, pkg/querier/queryrange/roundtrip.go
Adding transformer to results cache same as metrics cache done in PR #7542
=> add user-id transformer for logs results cache

docs/sources/installation/helm/migrate-from-distributed/index.md
Adds a migration guide to the new `loki` chart for people coming from the `loki-distributed` or `enterprise-logs` helm charts. This PR builds off @jeschkies's [Docs PR #7034](https://github.com/grafana/loki/pull/7034) and will be kept a draft until that one is merged.
Fixes #7330
The only file changed is `docs/sources/installation/helm/migrate-from-distributed/index.md`. The rest is from #7034.
**Checklist**
=> [helm] Document helm migration from `loki-distributed`

pkg/ingester/stream_rate_calculator.go
This PR reduces the number of locks in the rate calculator and allows it to hold an arbitrary number of rates by partitioning by tenant and stream hash
=> Reduce number of locks and partition by tenant and stream hash

pkg/util/marshal/marshal.go
This allows to reuse stream memory allocations between responses. Related https://github.com/grafana/loki/pull/3163 but this time this is for the encoding.
```
❯ benchstat before.txt after.txt                                                                                                              
name        old time/op    new time/op    delta
_Encode-16    29.2µs ±12%    25.2µs ± 1%  -13.85%  (p=0.016 n=5+4)
name        old alloc/op   new alloc/op   delta
_Encode-16    24.9kB ± 6%    16.4kB ± 8%  -34.20%  (p=0.008 n=5+5)
name        old allocs/op  new allocs/op  delta
_Encode-16       145 ± 0%       129 ± 0%  -11.03%  (p=0.008 n=5+5)
```
=> Improves performance of json responses

operator/CHANGELOG.md, operator/internal/handlers/internal/certificates/options.go
Small fix on fresh LokIStack installs when feature gate `BuiltInCertManagement: true`.
Follow up on #7064
**Checklist**
=> operator: Fix lookup CA Bundle options on fresh install

CHANGELOG.md, pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/querier/queryrange/queryrangebase/results_cache_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go, pkg/storage/stores/indexshipper/compactor/compactor_client.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client.go
This PR completes work started with #7426 as there are two types of http clients for using the compactor retention API, one for the deletes and one for the generation numbers. However #7426 introduced by a hindsight on the existence of generation number client the `boltdb.shipper.compactor.delete_client` which is replaced in this PR with a single `boltdb.shipper.compactor.client`. Latter enables to set the TLS settings for the underlying http client when calling the compactor retention API.
Furthermore this change set includes also a fix for enabling the generation number middlewares only if the compactor retention API is enabled. Currently this produced non-blocking but confusing 404 errors like the following on each query and rule execution:
``` …
```
=> Add single compactor http client for delete and gennumber clients

pkg/distributor/ratestore.go, pkg/distributor/ratestore_test.go
This PR accounts for intermittent streams that might get dropped on a per-second update interval
=> Keep rates in the ratestore for 10 minutes 

pkg/storage/stores/indexshipper/downloads/index_set.go
As of now, this log message isn't correctly showing the list of files (instead it logs the value as "unsupported value type").
=> Loki: Fix index_set log message

docs/sources/clients/promtail/stages/cri.md
The documentation doesn't mention the flags/tags component in a CRI log line.  I went with flags since that's the name it's given in our regex.
=> Improve CRI format documentation

pkg/storage/chunk/cache/fifo_cache.go
I configured fifo cache with `validity` option (which is [deprecated](https://github.com/grafana/loki/blob/b92f113cb0961b628b643f4f3f9fddc1c18ed921/docs/sources/configuration/_index.md?plain=1#L2004) in v2.6.0, `fifocache.duration` as an flag) and loki print that:
```
level=warn ts=2022-07-08T17:01:30.134251284Z caller=fifo_cache.go:125 msg="running with DEPRECATED flag fifocache.interval, use fifocache.ttl instead" cache=frontend.fifocache
```
However, there is no flag `fifocache.interval`.
As #5148 changed, the deprecated flag should be `fifocache.duration`, not `fifocache.interval`.
N/A
**Checklist**
=> use fifocache.duration instead of fifocache.interval in warn deprecated

CHANGELOG.md, clients/pkg/logentry/stages/decolorize.go, clients/pkg/logentry/stages/decolorize_test.go, clients/pkg/logentry/stages/stage.go, docs/sources/clients/promtail/stages/_index.md, docs/sources/clients/promtail/stages/decolorize.md, docs/sources/logql/log_queries.md, docs/sources/logql/query_examples.md, pkg/logql/log/fmt.go, pkg/logql/log/fmt_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/expr.y, pkg/logql/syntax/expr.y.go, pkg/logql/syntax/lex.go, pkg/logql/syntax/lex_test.go, pkg/logql/syntax/parser_test.go
Implement `decolorize` filter that get rids of ANSI color codes in the log message.
Fixes #7601
It's my first time writing Golang, so please let me know if I missed anything obvious 🙂 
**Checklist**
=> Loki: implement decolorize filter

production/helm/loki/Chart.yaml, production/helm/loki/README.md
changes for 3.3.2 were merged today but the chart was not released because chart version was not bumped and docs were not re-generated
fixes: https://github.com/grafana/loki/pull/7266
=> updated chart version to 3.3.2 to release merged changes

CHANGELOG.md
Add missing changelog entry for the new stream sharding feature.
This will be better detailed under the release notes doc.
=> Docs: Add missing changelog entry for stream sharding

Makefile, clients/cmd/fluent-bit/Dockerfile, clients/cmd/fluent-bit/README.md
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
* Pins digests for security enhancements
* Pass `-ldflags` using `--build-args`
* Use fluent-bit image `1.9.9`
* Use golang image `1.19.2`
* Clarify fluent-bit readme
**Checklist**
=> fluent-bit: clarify docs, use 1.9.9

pkg/logql/downstream.go, pkg/logql/engine.go, pkg/loki/loki.go, pkg/validation/limits.go
Improve the experience of migrating to our new timeouts behavior, which is the unifying of the engine:timeout and querier:query_timeout into a new configuration named limits_config:query_timeout.
This PR makes sure users won't be surprised by their timeouts being shorter, but at the same time, it makes it easier to migrate to the new configuration.
=> Loki: Implement timeouts migration

production/helm/loki/templates/monitoring/metrics-instance.yaml
If you're using prometheus operator and not Grafana Agent a metricsInstance shouldn't be auto-created.
#7529
I would also propose moving the definition at the same level with serviceMonitor and adding .enabled i.e.:
```
serviceMonitor:
enabled: true
...
metricsInstance:
enabled: true
annotations: {}
labels: {}
remoteWrite: null
```
This of course would be a breaking change.
**L.E.** Just noticed this other PR: #7525
**Checklist**
=> [Helm] Create metricsInstance only if available

docs/sources/operations/observability.md
I ran across a user setting up Loki and following this documentation, and they couldn't figure out the port where the HTTP server is listening for metrics requests. Be nice and mention the default here.
Signed-off-by: Marcelo E. Magallon <marcelo.magallon@grafana.com>
**Checklist**
=> Mention default port in docs

CHANGELOG.md, Makefile, README.md, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug, clients/pkg/promtail/targets/journal/journaltarget.go, clients/pkg/promtail/targets/journal/journaltarget_test.go, clients/pkg/promtail/targets/journal/journaltargetmanager.go, clients/pkg/promtail/targets/journal/journaltargetmanager_linux.go, docs/sources/upgrading/_index.md
This PR introduces the new go build tag `promtail_journal_enabled`. This tag is passed to go build if the environment variable `PROMTAIL_JOURNAL_ENABLED=true` is present.
It is useful for users with Linux OS and CGO enabled. Currently, if the user has Linux and CGO enabled he has to install `libsystemd-dev` library (`sudo apt install -y libsystemd-dev`) even when he doesn't need journald support.
**Checklist**
=> Promtail: Add go build tag promtail_journal_enabled

Makefile, clients/cmd/fluentd/Makefile, clients/cmd/fluentd/README.md, clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec
Version 1.2.19 contains the bugfix [#6240](https://github.com/grafana/loki/pull/6240)
At the moment releases of Loki and FluentD plugin are decoupled. In the future we probably want to maintain a separate changelog for the plugin, because it's now not easy to figure out what has been released and what not.
**Checklist**
=> Bump version `1.2.19` of `fluentd-plugin-grafana-loki`

ADOPTERS.md
Dropbox recently deployed Loki. This PR adds us to the adopters list
=> adds Dropbox to the adopters list

operator/CHANGELOG.md, operator/internal/manifests/internal/sizes.go
This PR changes the base `ingestionRate` for the 1x.small and 1x.medium t-shirt sizes to allow the average MB per second rate for their respective expected ingestion rates.
**Checklist**
=> operator: Modify ingestionRate for respective shirt size

docs/sources/clients/promtail/configuration.md
The current, 2.6.x, documentation on [configuring promtail _pipeline_stages_](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#pipeline_stages) contains a [docker stage](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#docker) which wraps the json, labels, timestamp, and output stage. The unwrapped configuration is shown as example. However, this example is outdated as can be seen by the lack of `expressions`. I have stumbled across this as I tried the example in my own config as a starter to modify to my own needs. It took me some time to realize what `failed to make file target manager: invalid json stage config: JMES expression is required` meant. This PR updates the example to match the current code at …
=> Promtail docs: Fix docker stage code example

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/single-binary/service-headless.yaml
Ignore the headless service from the Prometheus service-monitor as it was resulting in duplicate metrics. Replaces https://github.com/grafana/loki/pull/7049
=> [helm] Ignore single binary headless service from service-monitor

CHANGELOG.md, docs/sources/upgrading/_index.md
This add config differences I noticed when running the config diff tool between 2.6 and 2.7
=> Add config changes to upgrade guide

docs/sources/installation/helm/_index.md, docs/sources/installation/helm/concepts.md
Remove the non-exist references on couple of helm docs.
this fixes the docs building errors for v2.7 on grafana website.
https://github.com/grafana/loki/actions/runs/3443596525/jobs/5745297762
Fixes #NA
**Checklist**
=> docs: Fix refs on helm docs that breaks rendering new docs

CHANGELOG.md, docs/sources/configuration/_index.md
Adds `embedded-cache` config under `cache_config` section. Also adds message about deprecation of `fifocache`
Fixes #7677 
**Checklist**
=> docs(embedded-cache): Add missing docs on config page.

operator/CHANGELOG.md, operator/apis/loki/v1/lokistack_types.go, operator/bundle/manifests/loki.grafana.com_lokistacks.yaml, operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
When using the OpenShift console to create instances, the `replicationFactor` is set to a default of 1. This prevents the defaults listed in the `sizes.go` file from taking effect. This removes this from the PR, which allows an instance to be created with an empty field and thus lets the default values take effect.
**Checklist**
=> operator: Remove default value from replicationFactor field

operator/Makefile, operator/docs/operator/api.md
****What** this PR does / why we need it**:
Adds the `$(GEN_CRD_API_REFERENCE_DOCS)` deps to Make targets `docs/operator/api.md` and `docs/operator/feature-gates.md`. Re-generate api docs.
**Checklist**
=> operator: Fix api doc generation

pkg/loghttp/entry.go, pkg/util/marshal/marshal.go, pkg/util/marshal/marshal_test.go, pkg/util/marshal/query.go
Previously the query response was converted to `loghttp.ResultValue`. This requires a lot of allocations. Furthermore, the JSON response string was allocated before it was written to the response writer. This changes replaces the conversion from `parser.Value` to `loghttp.ResultValue` with a hand written JSON stream. This redueces the allocation overhead quite a bit:
```
› benchstat before.txt after.txt
name        old time/op    new time/op    delta
_Encode-16    51.5µs ± 1%    24.1µs ± 5%  -53.25%  (p=0.008 n=5+5)
name        old alloc/op   new alloc/op   delta
_Encode-16    7.68kB ± 0%    1.66kB ± 0%  -78.34%  (p=0.008 n=5+5)
name        old allocs/op  new allocs/op  delta
_Encode-16       129 ± 0%        28 ± 0%  -78.29%  (p=0.008 n=5+5)
```
The …
=> Serialize query JSON response in a stream.

CHANGELOG.md, pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_request_test.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager_test.go
It fixes the following issues:
* Whole chunks being deleted with a line filter were skipped.
* Chunks partially covered by delete requests with a line filter were not properly processed. The part that **was not covered** by the delete request was rewritten with a line filter, while the part that **was covered** by the delete request was completely deleted.
The issue went unnoticed because it seems we continue to do query time filtering of data even after the delete requests are processed.
Fixes #7590 
If multiple delete requests with a line filter touch the same chunk, then I am considering just the first request that marks it for deletion to keep this PR simple. I have left a …
=> fix bugs in processing delete requests with line filters and add proper tests

operator/controllers/loki/alertingrule_controller.go, operator/controllers/loki/certrotation_controller.go, operator/controllers/loki/lokistack_controller.go, operator/controllers/loki/recordingrule_controller.go, operator/controllers/loki/rulerconfig_controller.go
A small refactor to remove unnecessary parameters from `ctrl.Result{}` initializations to avoid confusion. It should also fix a bug where degraded conditions force a requeue, even when the `DegradedError` did not request it (for example, a missing storage secret).
**Checklist**
=> operator: Fix handling of Request requeues

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
Add the ability to add a selector for the Loki persistence volumes.
Fixes: #7737
**Checklist**
=> helm/loki: Allow to provide selector for Loki persistence volume

operator/CHANGELOG.md, operator/apis/loki/v1/lokistack_types.go, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
According to this OpenShift user bug report [LOG-3309](https://issues.redhat.com/browse/LOG-3309), putting a CAKey in to the `ObjectStorageTLSSpec` via the OpenShift Console is currently broken, because the ClusterServiceVersion renders an ConfigMap selector. The fix provided remove the accidental wrong descriptor for this field and makes it a usual text field. It still keeps the default value as `service-ca.crt`.
**Checklist**
=> operator: Fix object storage TLS spec CAKey descriptor

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl
It removes the extra `/` when `registry` or `repository` is empty
Fixes #7739 
**Checklist**
=> helm/loki: Remove extra `/` if `registry` or `repository` is empty

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/single-binary/statefulset.yaml
When running in single-binary mode, these warnings may appear:
`level=warn ts=2022-11-15T08:01:39.777179378Z caller=marker.go:214 msg="failed to process marks" path=/var/loki/compactor/retention/markers/1668476560013344947 err="open /tmp/marker-view-912253853: read-only file system"`
This was previously fixed in the old chart: grafana/helm-charts#967
Fixes grafana/helm-charts#609, again.
**Checklist**
=> [helm] Fix read-only /tmp in single-binary mode

docs/sources/logql/analyzer/script.js
It's needed to point LogQL Analyzer page to the backend with v2.7.0
=> changed the URL to LogQL Analyzer backend v2.7.0

CHANGELOG.md, examples/getting-started/docker-compose.yaml
Adds healthchecks for the loki `docker compose` example, this makes the getting started example more complete,
and can be now used with the `--wait` command.
Use the following commands to test:
```sh
cd examples/getting-started
docker compose up -d --wait
docker compose ps
```
**Checklist**
=> Examples: Add healthckecks in docker example

.drone/drone.jsonnet, .drone/drone.yml
The mixin check sometimes (e.g. [this build](https://drone.grafana.net/grafana/loki/17667/4/2)) which blocks pull requests with unrelated changes. This is a quick fix. Ideally we would investigate why Jsonnet Bundler is failing sometimes.
**Checklist**
=> Only check mixin on file changes.

production/loki-mixin-compiled-ssd/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-operational.json, production/loki-mixin/dashboards/dashboard-loki-operational.json
Avoid division by zero and therefore resulting NaN, which is displayed as 0% in the panel, showing massive drops if a specific route has a rate of 0 for some time.
Also, replace fixed range (`5m` and `1m`) with dynamic `$__rate_interval` variable for higher accuracy and better performance.
Before:
After:
With `$__rate_interval` instead of fixed `5m` range:
**Checklist**
=> [loki-mixin] Make "Success Rate" panels in operational dashboard more accurate

CHANGELOG.md, pkg/util/cfg/files.go
Before:
```
Unable to parse config: ./clients/cmd/promtail/promtail-local-config.yaml: parse "http://${LOKI_URL}localhost:3100/loki/api/v1/push":
invalid character "{" in host name
```
After:
```
Unable to parse config: ./clients/cmd/promtail/promtail-local-config.yaml: parse "http://${LOKI_URL}localhost:3100/loki/api/v1/push":
invalid character "{" in host name. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```
Fixes #NA
**Checklist**
=> config: Improve error message loading config with ENV variables.

.github/workflows/helm-release.yaml
The Helm Chart release often breaks when changes missed to update the Helm Chart version. There is also often a conflict in the version.
This solution proposes to check the `Chart.yaml` for changes.
**Checklist**
=> Only release Helm Chart when version changed.

docs/sources/maintaining/release.md
We usually tag releases from the HEAD of the release branch
=> Update release instructions

production/loki-mixin-compiled-ssd/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-operational.json, production/loki-mixin/dashboards/dashboard-loki-operational.json
Use `job=~\"$namespace/cortex-gw(-internal)?\"` throughout the dashboard. This fixes the occurrence where a regex value was used in combination with an exact label match (line 186).
@gouthamve did the initial change that added the `(-internal)?` suffix to the regex label matcher in #7481 
**Checklist**
=> Fix label selector for gateway service in operational dashboard

docs/Makefile, docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/ingress.yaml, production/helm/loki/values.yaml
The helm ingress template was copied over from the simple scalable chart and does not work when deploying the chart in single binary configuration. This fixes that by adding a set of single binary routes, and conditionally configuring the ingress resource based on deployment type.
Fixes #7080
**Checklist**
=> [helm] Fix incorrect ingress paths when using single binary deployment

CHANGELOG.md, integration/cluster/cluster.go, integration/multi_tenant_queries_test.go, pkg/logql/engine.go, pkg/querier/http.go, pkg/querier/queryrange/querysharding.go
We recently broke multitenant querying because of recent changes to how timeouts working across Loki. This PR fixes this by:
- Adapt the timeout wrapper to work with multitenant queries. It will take the shortest timeout across all given tenants
- Adapt the query engine timeout assigning to work with multitenant queries. It will take the shortest timeout between all the tenants
- Adapt query sharding to use smallest max query parallelism across given tenants
- Add a functional test to ensure multitenant is behaving as expected
Signed-off-by: DylanGuedes <djmgguedes@gmail.com>
Signed-off-by: Mehmet Burak Devecí <mhmtbrkdvc@gmail.com>
https://github.com/grafana/loki/issues/7696
The …
=> Loki: Fix multitenant querying

operator/docs/lokistack/object_storage.md
Signed-off-by: Joel Takvorian <jtakvori@redhat.com>
Fixes probably a typo in documentation for the operator, with S3 storage: secret needs to contains key `bucketnames`, not `bucketname`.
See also the hack script that doesn't contain this mistake: https://github.com/grafana/loki/blob/main/operator/hack/deploy-aws-storage-secret.sh#L16
N/A
**Checklist**
PS: I haven't updated the changelog, guessing it's not necessary for a doc typo?
=> operator: Fix docs AWS storage uses bucketnames

tools/promtail.sh
update promtail version on `tools/promtail.sh` which generates promtail config for kubernetes
Fixes #NA
This image is part of latest loki 2.7.0 release and[ it does exists ](https://hub.docker.com/layers/grafana/promtail/2.7.0/images/sha256-d54b599ea154df295486068f1545731bd5ab9790602d8518816c9285eec3df5e?context=repo)
**Checklist**
=> chore(tools): Update promtail image version

CHANGELOG.md, docs/sources/operations/blocking-queries.md, pkg/logcli/client/file.go, pkg/logql/blocker.go, pkg/logql/blocker_test.go, pkg/logql/engine.go, pkg/logql/limits.go, pkg/logqlmodel/error.go, pkg/querier/queryrange/roundtrip_test.go, pkg/util/server/error.go, pkg/util/validation/blocked_queries.go, pkg/validation/limits.go, pkg/validation/limits_test.go
Block malicious or expensive queries using a per-tenant runtime configuration.
N/A
This does not apply to `labels` or `series` queries, nor does it allow for defining other dimensions like query time range. I wanted to keep things simple to start with.
**Checklist**
=> Querier/Ruler: query blocker

CHANGELOG.md, clients/pkg/promtail/client/client.go, clients/pkg/promtail/client/client_test.go
Provides better visibility for per-tenant drops/retries in Promtail
Fixes #7570 
Does anything depend on these metrics only having 1 label that this change would break? I decided against a reason label due to cardinality concerns given how widely promtail is often deployed.
**Checklist**
=> Promtail: Add tenant label to client drop metrics and logs

cmd/loki/Dockerfile.debug, loki-build-image/Dockerfile
In order to use the `production/docker` with an interactive debugger, we need to upgrade the Delve tool to a version that works with the version of Go which Loki uses: 1.19
N/A
This is step 1 of 2 in the [release process](https://github.com/grafana/loki/blob/main/docs/sources/maintaining/release-loki-build-image.md) of the build image.
**Checklist**
=> Update delve version to be compatible with Go 1.19

.drone/drone.jsonnet, .drone/drone.yml, docs/sources/maintaining/release-loki-build-image.md, loki-build-image/version-updater.sh
In https://github.com/grafana/loki/pull/7793, I accidentally overwrote `grafana/loki-build-image:0.24.2` because the build & release steps were ambiguous. I've fixed that now, and included a script for keeping all references to this build image updated.
N/A
**Checklist**
=> Improvements to loki-build-image build & release process

.circleci/config.yml, .drone/drone.yml, Makefile, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile.cross, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/querytee/Dockerfile.cross, docs/sources/maintaining/release-loki-build-image.md, operator/Dockerfile.cross
Updates the `loki-build-image`  and corrects mistake in https://github.com/grafana/loki/pull/7793 where I overwrote the `0.24.2` image.
[Step 1](https://github.com/grafana/loki/pull/7795)
N/A
Followed my docs and found one step missing.
**Checklist**
=> Completing step 2 of updating loki-build-image

docs/sources/configuration/_index.md
In the documentation for Loki configuration use the correct field name `embedded_cache` to match the expectations in the YAML parser
N/A
**Checklist**
=> docs(embedded-cache): config uses embedded_cache

pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/stream_rate_calculator.go, pkg/ingester/stream_rate_calculator_test.go
- Use weighted moving average for rates
- Keep Streams around until they are removed
Previously, the rate calculator only kept the most recent second. This led to issues where bursty streams that didn't get pushes every second resulted in undersharding those streams
=> Update Ingester Rate Calculations

pkg/loki/modules.go
fifocache config is deprecated. use embedded-cache instead
Fixes #7798
**Checklist**
=> fifocache config is deprecated. use embedded-cache instead

CHANGELOG.md
Fixes the changelog.
- PR #7462 and #7461 were **not** included in the 2.7.x release (they were submitted right after the cutoff and did not get backported) and accidentally ended up in the 2.7.x changelog. Moved them up to Main/Unreleased.
- Moved #7602 to enhancements section of Promtail
None
PR #7668, which adds upgrade documentation for #7461, _was_ backported to 2.7.x despite the fix not being available in that release.
**Checklist**
=> Docs - Move PR's in CHANGELOG.md that weren't actually implemented in 2.7.x

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/tokengen/job-tokengen.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
Add the ability to change the Loki `target` argument. E.g. one might want to use the single-binary which has target `all` but also the `table-manager` which is not part of it. So one can override the target with `all,table-manager`.
Fixes #7788 
**Checklist**
=> helm/loki: Allow to override default loki `target`

operator/CHANGELOG.md, operator/apis/loki/v1/lokistack_types.go, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/manifests/loki.grafana.com_lokistacks.yaml, operator/config/crd/bases/loki.grafana.com_lokistacks.yaml, operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml, operator/controllers/loki/lokistack_controller.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/manifests/storage/configure.go, operator/internal/manifests/storage/configure_test.go
Followup on #7744 to check for the `ObjectStorageTLSSpec.CA` field as mandatory before looking up for ConfigMap. This is a corner case where some one opens the dialog for `ObjectStorageTLSSpec` (e.g. in the OpenShift Console UI) and introduces doing so the default value for `CAKey` but does not select any CA ConfigMap. The same can happen when a user introduced in a YAML manifest the `caKey` field but not the `ca`.
**Checklist**
=> operator: Check for mandatory CA configmap name in ObjectStorageTLS spec

clients/cmd/fluent-bit/README.md
The Loki plugin for Fluent Bit will not build with golang < 1.17 because of the use of net.IP.IsPrivate in the referenced version of github.com/grafana/dskit/netutil/netutil.go
No issue exists (this is a minor documentation issue).
**Checklist**
- [N/A] Documentation added
- [N/A] `CHANGELOG.md` updated
- [N/A] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> fluent-bit: Update the Fluent Bit plugin README with correct golang minimum version

pkg/distributor/ratestore.go, pkg/distributor/ratestore_metrics.go
Add histogram-version of two existing stream sharding metrics. The new metrics are:
- `rate_store_stream_shards`: Will show us the distribution of shards reported by ingesters. This will help us on monitoring the number of shards we're dealing with. As of now we only have access to the max number of shards seen, which is helpful but not enough.
- `rate_store_stream_rate_bytes`: Same as below: will help us understand the distribution of stream sizes instead of only showing us the max stream size seen.
=> Loki: Add new sharding metrics (histogram based)

operator/CHANGELOG.md, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml
This replaces the deprecated usage of `fifocache` in the configuration generated by Loki Operator by the updated `embedded_cache` configuration block. The same configuration values are used.
[LOG-3333](https://issues.redhat.com/browse/LOG-3333)
**Checklist**
=> operator: Replace fifocache usage by embedded_cache

operator/CHANGELOG.md, operator/internal/manifests/internal/alerts/prometheus-alerts.yaml
Currently the histogram-based alerts created by Loki Operator are using a multiplication by 100, which does not seem correct in this context (the result of `histogram_quantile` should already be in `seconds`).
**Checklist**
=> operator: Fix histogram-based alerting rules

CHANGELOG.md, pkg/loki/modules.go, pkg/querier/worker_service.go
While running all-in-one Loki instance, it's not possible to listen on anything other than IPv4 since compactor_address is then set to http://127.0.0.1. This enables listening on only IPv6.
Also if frontent_address, scheduler_ring and scheduler_address is not set, the default value is to connect to '127.0.0.1:<grpc_listen_port'. Which means that grpc_listen_address is ignored.
It's not possible to use compactor while using an all-in-one instance and listening to IPv6.
Let's not ignore grpc_listen_address to not confuse users.
As noted in the first commit, the default behavior is changed from defaulting to `127.0.0.1` to `localhost`. Not sure how major that change is though.
My …
=> [bugfix]  Remove hardwired '127.0.0.1' values in default addresses

operator/internal/manifests/internal/alerts/testdata/test.yaml
Fixes the Prometheus alert tests broken by #7809 
**Checklist**
=> operator: Fix alert unit tests

cmd/loki-canary/main.go, pkg/canary/writer/push.go, pkg/canary/writer/push_test.go
Currently `useTLS` flag is ignored on the push writer. This PR consider that flag and adjust the schema (http -> https) when that flag is enabled.
Fixes #7692 
**Checklist**
=> loki-canary: respect `useTLS` flag when `push` mode is enabled.

CHANGELOG.md, clients/pkg/promtail/targets/cloudflare/target.go, clients/pkg/promtail/targets/docker/target.go
This PR addresses issue [#6930](https://github.com/grafana/loki/issues/6930).
Promtail should not panic when the Details() method is called for a target that has no errors.
Fixes #6930
This is my first contribution, please let me know if I need to add more details regarding the small fix.
**Checklist**
=> promtail: Handle nil error on target Details() call

CHANGELOG.md, pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/querier/queryrange/queryrangebase/results_cache_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go, pkg/storage/stores/indexshipper/compactor/compactor_client.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client.go
Manual backport of #7453 into release-2.7.x.
**Checklist**
=> [release-2.7.x] Add single compactor http client for delete and gennumber clients

operator/CHANGELOG.md, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml
After merging into #7607 we need to retrofit the `compactor_client` as `delete_client` again to re-establish compatibility with upcoming v2.7.x Loki releases.
**Checklist**
=> operator: Apply delete client changes for compat with release-2.7.x

CHANGELOG.md, pkg/storage/chunk/cache/memcached.go, pkg/storage/chunk/cache/memcached_test.go
Our memcached client has race between closing `inputCh` and submitting work to it (writing to channel) by different goroutines.
This PR fix it by having `closed` channel to track if `inputCh` is closed and make it visible to other writter go-routines.
Before:
```
loki$ go test -v ./pkg/storage/chunk/cache/... -run TestMemcached_fetchKeysBatched
=== RUN   TestMemcached_fetchKeysBatched
panic: send on closed channel
goroutine 29 [running]:
github.com/grafana/loki/pkg/storage/chunk/cache.(*Memcached).fetchKeysBatched.func1()
/home/kavirajk/src/loki/pkg/storage/chunk/cache/memcached.go:167 +0x87
created by github.com/grafana/loki/pkg/storage/chunk/cache.(*Memcached).fetchKeysBatched
/home/kavirajk/src/loki/pkg/storage/chunk/cache/memcached.go:164 +0x165 …
```
=> fix(memcached): panic on `send on closed channel`.

pkg/distributor/distributor_test.go, pkg/distributor/ratestore.go, pkg/distributor/ratestore_metrics.go, pkg/distributor/ratestore_test.go
This PR changes the Rate Store to use multi-level maps rather than `tenant+stream-fingerprint` key. 
Benchmarks:
*old*
```
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/distributor
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
BenchmarkRateStore-8         117          10420080 ns/op         3201761 B/op     200025 allocs/op
PASS
ok      github.com/grafana/loki/pkg/distributor 14.646s
```
*new*
```
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/distributor
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
BenchmarkRateStore-8         320           3811906 ns/op            2660 B/op         26 allocs/op
```
*stats*
```
name         old time/op    new time/op    delta
RateStore-8    10.7ms ± 8%     4.1ms ± 8%  -61.42%  (p=0.000 n=10+10)
name         old …
```
=> Improve ratestore performance

pkg/querier/queryrange/limits.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/querier/queryrange/queryrangebase/results_cache_test.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/split_by_interval.go
We saw a spike in divide by zero panics in the code introduced in #7769. I was able to reproduce this error via a test that calculates `WeightedParallelism` with a start that's after the end. Not sure if this is possible, but we definitely saw this happening in our ops environment, so something is causing it, and the fix should guard against it in any case.
**Checklist**
=> guard against divide by 0 when splitting parallelism

pkg/storage/chunk/cache/memcached.go
Follow up to https://github.com/grafana/loki/pull/7817
This PR uses `default` branch instead of `inputCh <- work` to make sure we are writing to closed `inputCh`.
Gist is, `default` run [only when none of the branch is ready](https://go.dev/tour/concurrency/6). which makes more sense rather than to have `inputCh <- work` (writing to closed channel on the branch condition)
These can be explained by these two tiny snippets.
* [with `default`](https://go.dev/play/p/-FspbTZd20I)
* [without `default`](https://go.dev/play/p/Ag4WznOaEq0)
Fixes #NA
We already have test `TestMemcached_fetchKeysBatched` to catch this behaviour. In fact …
=> fix(memcached): use `default` branch avoid writing to closed chan

pkg/querier/queryrange/queryrangebase/retry.go, pkg/querier/queryrange/queryrangebase/retry_test.go
For better observability of query retries.
**Checklist**
- [n/a] Documentation added
- [n/a] Tests updated
- [n/a] `CHANGELOG.md` updated
- [n/a] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> Log query string on retry alongside the error

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ratestore.go, pkg/distributor/ratestore_metrics.go
This PR just adds tenant information so some of our per-stream-rate-limit metrics.
=> Make some stream shard metrics per-tenant

docs/sources/installation/helm/reference.md, flake.nix, nix/loki.nix, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml
Bumps Loki to 2.7.0 and GEL to 1.6.0 in the helm chart.
=> [helm] Bump helm Loki and GEL version

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ratestore.go, pkg/distributor/ratestore_metrics.go
Because these metrics will be coming from each distributor, this is going to have an adverse impact on cardinality. Consider doing this with logging
=> Revert "Make some stream shard metrics per-tenant (#7838)"

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
faillint needs an update for Go 1.19 where it fails unexpectedly. First observed in #7826.
See fatih/faillint#36
=> loki-build-image: update faillint

pkg/distributor/ratestore_metrics.go
Add one additional bucket (value=1) to the `rate_store_stream_shards`.
By jumping from 0 to 2 we can't distinguish between streams that were minimally sharded (shards=2) to non-sharded ones (shards=1).
=> Loki: Add one additional bucket to `rate_store_stream_shards`

production/helm/loki/src/alerts.yaml
The original added canary alert rules (https://github.com/grafana/loki/pull/7286) are malformatted and break the generated `loki-alerts` . i.e. 
```
// stripped away some labels
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
labels:
helm.sh/chart: loki-3.6.0
name: release-name-loki-alerts
spec:
groups: << nothing here
```
PTAL @dannykopping @trevorwhitney
Fixes a bug introduced in #7286
**Checklist**
=> Fix broken canary loki alerts

clients/cmd/promtail/Dockerfile.debug
The 'grafana/loki-build-image' version was not specified for the promtail-debug docker image, resulting in a ~6 month old 'latest' image as a build image. Updating this resulted in one more change: the newer version has a different location for the 'dlv' binary.
The promtail-debug image would also hang waiting for a connection when ran, this adds the same flag, `--continue`, as added to the loki debug file in #1372.
I was interested in using the `-server.profiling_enabled=true` flag, to enable pprof endpoints, and scrape with phlare. This flag is not available in the non-debug version. Therefore I do not really care for attaching a debugger right away. Open to removing that change though.
**Checklist**
=> Promtail: Fix broken promtail-debug docker image

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md
Commit 30caf142b2e9d2e0b63339b66c92a4f528ec884e introduced a regression ending up in generating no PrometheusRule alerts.
That was fixed in commit 433d883fcd7b837b927637e09893008cd2eec356 but no releases were done.
Bump version to have a release about it.
Should hopefully fix a request done by @xinbinhuang - who spotted and fixed this problem, thanks! - in #7860.
I think it is important to tag a release ASAP because stopping having alerts can be a regression in possible production environments.
I have no idea if that will force to release a 3.6.1 Helm release without doing any tag or similar, sorry! I have tried to skim documentation about that and I have skimmed …
=> [helm] Release 3.6.1 to reintroduce PrometheusRule alerts

CHANGELOG.md, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/split_by_interval.go
We disable query sharding when a query touches multiple schema configs since they might have different sharding factors and might handle sharding differently. This check was done purely on the start and end time of the query without considering `range` and `offset`, which would change the length of the actual data being queried.
Besides being incorrect, it also causes us to fail queries when migrating between tsdb and non-tsdb stores since both handle query sharding differently. For e.g., if the prev schema is `boltdb-shipper` and starting today, `tsdb` index is being used, so if we do a query `sum(rate({foo="bar"}[24h])` even with start and end within `tsdb` range, we will fail the query with error `incompatible index shard` if dynamic sharding …
=> consider range and offset in queries while looking for schema config for query sharding

pkg/validation/limits.go, production/loki-mixin/jsonnetfile.lock.json
We need to default deletion mode to `filter-only` for 2.7.1 because of the bug.
=> default compactor deletion mode to filter only

CHANGELOG.md, docs/sources/release-notes/v2-7.md
Prepares changelog and release notes for 2.7.1 release.
=> Prepare changelog and release notes for 2.7.1

CHANGELOG.md, clients/pkg/logentry/stages/limit.go, clients/pkg/logentry/stages/limit_test.go, docs/sources/clients/promtail/stages/limit.md, pkg/util/map.go, pkg/util/metrics_helper.go
Limit stage can now takes optional `by_label_name` param, which tracks distinct values of that label and ratelimit entries independently.
Log lines without expected label are not considered for ratelimiting and passed to the next pipeline stage.
To avoid stalling whole stage by just few labels it requires 'drop', to be set to true.
**Checklist**
=> promtail: ratelimiting by label

operator/CHANGELOG.md, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/development/manager_related_image_patch.yaml, operator/config/overlays/openshift/manager_related_image_patch.yaml, operator/config/overlays/production/manager_related_image_patch.yaml, operator/docs/operator/compatibility.md, operator/internal/manifests/config.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml, operator/internal/manifests/internal/config/options.go, operator/internal/manifests/var.go
Update Loki operand to v2.7.1
Because of backport #7896 the operator needs to switch from using the `delete_client` to `compactor.client`
**Checklist**
=> operator: Update Loki operand to v2.7.1

docs/sources/installation/sizing/index.md
**What this PR does / why we need it**
The current sizing tool is broken because it would not allow cross origin requests. See LogQL Analyzer (https://github.com/grafana/loki/blob/main/docs/sources/logql/analyzer/script.js#L115) for the proper way to call its API.
=> Fix sizing tool.

integration/loki_simple_scalable_test.go, pkg/loki/loki.go, pkg/loki/modules.go, pkg/loki/modules_test.go
This adds a 3rd target to SSD/Scalable mode, as well as a config flag to run the legacy `read` mode from the original 2 target configuration in order to give people time to migrate before we remove this option in Loki 3.0 (hopefully).
The 3rd target has the two major advantages:
1. Allows the read path to be run as a deployment and thus auto-scaled using our existing auto-scaling logic for queriers
2. Creates consistency with Mimir since they went with a 3 target model for their SSD deployment.
I don't want to merge this until I've had the chance to also update the helm chart, use this version, and test everything in a real environment.
**Checklist**
=> Add 3rd target (`backend`) to SSD/Scalable mode

docs/sources/api/_index.md
PR documents the default value for `delete_ring_tokens` params on `/ingester/shutdown` endpoint.
Fixes #NA
**Checklist**
=> doc(api): Default value for `delete_ring_tokens` on `/ingester/shutdown` endpoint

cmd/loki/main.go, pkg/util/log/log.go
I ran into this issue several times. No error logs were printed or no generated token for GEL. This is because crashing runs can be much faster than the flush period.
**Checklist**
=> Flush buffered logger on exit.

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/upgrading/_index.md, pkg/ruler/config.go, pkg/ruler/storage/cleaner/config.go
Deprecate CLI flag `-ruler.wal-cleaer.period` in favor of CLI flag `-ruler.wal-cleaner.period`.
Fixes https://github.com/grafana/loki/pull/7916#issuecomment-1348276269 and https://github.com/grafana/loki/pull/7916#discussion_r1047043534
**NOTE:** correctly registring the `ruler.wal-cleaner` configuration flags is not a breaking change and doesn't require an upgrade guide, because the ruler WAL cleaner initialization code already guarantees that the default values are used: https://github.com/grafana/loki/blob/c71620ae9437aa23142cdc410115f28ae8f29997/pkg/ruler/storage/cleaner/cleaner.go#L76-L101
**Checklist**
=> Deprecate CLI flag -ruler.wal-cleaer.period in favor of CLI flag -ruler.wal-cleaner.period

.drone/drone.jsonnet, .drone/drone.yml, CHANGELOG.md, Makefile, docs/sources/configuration/_index.md, pkg/lokifrontend/frontend/v2/frontend.go
Follow up from PR: https://github.com/grafana/loki/pull/7916 to add a CI step to check if the configuration flag documentation file `doc/sources/configuration/_index.md` was generated successfully.
Requirements:
* CI `check` pipeline should fail if the documentation file is updated manually
* CI `check` pipeline should fail if registration flags are changed in the code, but the documentation file is not generated.
Fixes https://github.com/grafana/loki-private/issues/83
**Checklist**
=> Add CI step to check generated documentation to check pipeline

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/provisioner/job-provisioner.yaml, production/helm/loki/templates/tokengen/job-tokengen.yaml
This adds `hook-weight` annotations to the tokengen and provisioner jobs to make sure tokengen always runs first. The fixes a race condition where provisioner attempts to go first but locks and fails the deployment because no token is available.
Fixes #7251
**Checklist**
=> [helm] control order provisioner and tokengen jobs run in

CHANGELOG.md, pkg/logql/rangemapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/ast_test.go
Running the query `topk(10,sum by(namespace)(count_over_time({application="nginx", site!="eu-west-1-dev"} |= "/artifactory/" != "api" != "binarystore" | regexp `` [1d])))` causes a panic.
This PR adds validation for regexp and pattern parsers at parse time. If they don't have a (valid) parameter an error will be returned. 
**Checklist**
=> Fix validation for pattern and rexexp parsers to they don't panic in query-frontend

pkg/logql/range_vector.go, pkg/logql/range_vector_test.go
Instant queries use the new `streamRangeVectorIterator` which has a new set of `aggregators`. Before, aggregations were based on the first point in the range to be aggregated. With  `streamRangeVectorIterator`, points are instead treated one at a time. 
The aggregations were simply checking whether the value was less than the min or greater than the max without any initialization. This PR fixes these aggregations by initializing `min` or `max` to `math.Nan` so the first point is always considered.
=> Fix min and max aggregations when using instant queries.

pkg/logql/range_vector.go, pkg/logql/range_vector_test.go
This PR cherry-picks changes from https://github.com/grafana/loki/pull/7957 into `k128`.
PR description from https://github.com/grafana/loki/pull/7957:
> Instant queries use the new `streamRangeVectorIterator` which has a new set of `aggregators`. Before, aggregations were based on the first point in the range to be aggregated. With `streamRangeVectorIterator`, points are instead treated one at a time.  
> The aggregations were simply checking whether the value was less than the min or greater than the max without any initialization. This PR fixes these aggregations by initializing `min` or `max` to `math.Nan` so the first point is always considered.
N/A
N/A
**Checklist**
=> Fix min and max aggregations when using instant queries. (#7957)

CHANGELOG.md, docs/sources/upgrading/_index.md, production/ksonnet/loki/query-frontend.libsonnet, production/ksonnet/loki/query-scheduler.libsonnet
We noticed an imbalance in the requests sent to the Query Frontend pods using `query-frontend` k8s service. This seems to be caused by `query-frontend` being a headless service that resolves to each QF pod IP and leaves it up to the client to load balance the requests as mentioned [here](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services).
This PR fixes the issue by creating two separate services for pod IP discovery and load balancing of queries:
* `query-frontend` to be used for load balancing incoming Loki queries.
* `query-frontend-headless` to be used for discovering QF pod IPs from queriers to connect as workers.
**Checklist**
=> fix query-frontend request load balancing when using k8s service

pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/ingester/stream_rate_calculator.go, pkg/ingester/stream_rate_calculator_test.go
This change was supposed to smooth out the per-second rate of streams so distributors could react more uniformly to streams with variable rates. In practice, it resulted in drastically more resource usage on distributors because `GetStreamRates` now responds with all streams on an ingester rather than only the streams seen in the last second. This change also didn't seem to affect sharding precision one way or another.
If we'd still like to implement exponential smoothing for stream rates, it should be implemented in distributors to keep communication overhead to a minimum.
=> Revert "Update Ingester Rate Calculations (#7652)"

CHANGELOG.md, clients/pkg/logentry/stages/extensions.go, clients/pkg/logentry/stages/extensions_test.go
When re-creating single lines from multiple partial lines, `\n` should be avoided to join the partial lines.
Related: https://github.com/grafana/loki/pull/6177#discussion_r976113761
Example
if Original log line is 
```
{"a": "very long json field split in two lines"}
```
And got split into partial lines via CRI
```
2022-09-20T17:51:01.214529932Z stdout P {"a": "very long json field 
2022-09-20T17:51:01.214697597Z stdout F split in two lines"}
```
The result should be without \n when joining both of those lines.
Fixes: https://github.com/grafana/loki/issues/7996
**Checklist**
=> fix(promtail): Fix cri tags extra new lines.

clients/pkg/promtail/targets/heroku/target_test.go, pkg/ingester/stream_rate_calculator.go, pkg/logql/range_vector_test.go, pkg/logql/rangemapper_test.go, pkg/logql/syntax/prettier.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/split_by_interval.go
These changes have been generated using `make lint`.
```console
$ golangci-lint --version
golangci-lint has version 1.50.0 built from 704109c6 on 2022-10-04T10:25:07Z
```
=> [chore] Fix various linter errors

CHANGELOG.md, pkg/storage/stores/series_store_write.go, pkg/storage/stores/series_store_write_test.go
Signed-off-by: Ashwanth Goli <iamashwanth@gmail.com>
When a chunk falls on the period boundary it should be written to both the stores as it gets referred to by the indexes on both sides. But we currently skip the writes for subsequent periods if the chunk is found in the cache. This PR ensures that overlapping chunks get written to both the stores
Fixes #7847 
Downside of this approach is that we end up writing the overlapping chunk multiple times, once from each instance in the replica set. But these duplicate writes would be infrequent given this occurs only on schema changes
**Checklist**
=> store: write overlapping chunks to multiple stores

docs/sources/logql/log_queries.md
Update log queries regex documentation with a clarification on the difference between the newline character in:
* label matching operator: `.*` does not match newlines
* line filter expressions: `.*` matches newlines
**Checklist**
=> Update log queries regex documentation

production/ksonnet/loki/query-frontend.libsonnet
In PR #7966, I made changes to Query Frontend service. Part of it was creating a new service.
To make the service properly load balance grpc requests, we need to use `grpclbServiceFor`, but since we do not use grpc in QF, I went with the usual method, i.e. I used `serviceFor`. Thinking more about it, I think there is no harm in keeping it grpc LB friendly, and it would save us from any possible bugs if we make QF accept queries via grpc.
=> make query-frontend service grpc lb friendly

loki-build-image/Dockerfile
Add gotestsum to the build image. Then use it to run the unit tests. The output format is easier to parse so we can get statistics about the builds.
Passing test cases look like this:
```
PASS pkg/storage/stores/shipper/index/compactor.TestTable_RecreateCompactedDB/compacted_db_old_enough (2.64s)
PASS pkg/storage/stores/shipper/index/compactor.TestTable_RecreateCompactedDB (10.26s)
PASS pkg/storage/stores/shipper/index/compactor.TestExtractIntervalFromTableName/0 (0.00s)
```
Failing test cases are shown at the end and are easier to parse:
```
=== FAIL: pkg/storage/stores/indexshipper/compactor/deletion TestGRPCGetCacheGenNumbers (unknown)
panic: Fail in goroutine after TestGRPCGetCacheGenNumbers/error_getting_from_store has completed
goroutine 293 …
```
=> Use gotestsum to run unit tests

pkg/validation/validate.go
This has come up time and time again, I have tried to write it up a bit better in code first, I would also strongly suggest that we improve the error messaging and the documentation of this.
=> Improve comments on sample timestamp validation errors

.drone/drone.yml, Makefile
Update the build image version to 0.26.
Use this in drone.yaml.
This uses the new test setup from https://github.com/grafana/loki/pull/8022
**Checklist**
=> Update build image and use in drone yaml

cmd/chunks-inspect/loki.go
Make the `chunks-inspect` command correctly report Zstandard compressed chunks as `zstd` encoding.
The `chunks-inspect` command falsely reports Zstandard compressed chunks as `lz4-256k`.
**Checklist**
=> Fix chunks-inspect reports zstd compressed chunks as lz4-256k

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/gateway/deployment-gateway.yaml, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
Add the ability to specify container lifecycle in helm chart. This is useful when pods are served by a load balancer that needs time to deregister terminating pods, as we can setup a preStop hook to wait a bit before terminating the container. Example:
```yaml
gateway:
lifecycle:
preStop:
exec:
command: ["/bin/sh", "-c", "sleep 30"]
```
None
None
**Checklist**
=> [Helm] Add the ability to specify container lifecycle

CHANGELOG.md, cmd/loki-canary/main.go, docs/sources/operations/loki-canary.md
- Replace flag with kingpin which has more capabilities to override defaults
- Override default for `addr`, `user` and `pass` from environment the variables `LOKI_ADDRESS`, `LOKI_USERNAME` and `LOKI_PASSWORD` respectively.
Fixes #8021
**Checklist**
=> [loki-canary] Support passing loki address as environment variable

CHANGELOG.md
#8024 added an enhancement to loki-canary to pickup config from env variables. However the change was wrongly added under loki instead of loki-canary in the changelog. This PR fixes the changelog.
NA
**Checklist**
=> [loki-canary] Fix changelog

operator/CHANGELOG.md, operator/internal/manifests/gateway.go, operator/internal/manifests/gateway_test.go
Fix using the replica count defined in the LokiStack size table for the lokistack-gateway deployment instead of defaulting to a one replica.
[LOG-3478](https://issues.redhat.com/browse/LOG-3478)
**Checklist**
=> operator: Use lokistack-gateway replicas from size table

.drone/drone.jsonnet, .drone/drone.yml
Fix missing manifest for Loki Operator multi-arch images published on Docker Hub.
**Checklist**
=> Add loki-operator multi-arch image manifest

production/helm/loki/templates/monitoring/pod-logs.yaml
Fix loki helm chart to properly accept podLog relabelings by changing nindent from 8 to 4. This makes the podLog relabelings usable.
Other wise helm complains with
```
Error: UPGRADE FAILED: YAML parse error on loki/templates/monitoring/pod-logs.yaml: error converting YAML to JSON: yaml: line 32: mapping values are not allowed in this context
```
Don't think documentation is required because clearly nobody was using this.
**Checklist**
=> Helm: Fix loki helm chart podLog relabelings template nindent

.drone/drone.jsonnet, .drone/drone.yml, Makefile
Copy the docker-driver pipeline from CirclCI to drone. This was tested by running with a trigger that creates an image on every branch: see the 'docker-driver' step in the https://drone.grafana.net/grafana/loki/18655 run.
See https://hub.docker.com/r/grafana/loki-docker-driver/tags for the built images: main and main-63360ab.
**Checklist**
=> Add docker-driver pipeline

docs/sources/installation/helm/reference.md, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/values.yaml
add a flag to enable/disable persistentVolumeClaimRetentionPolicy feature which is available since kubernetes 1.23 but in alpha (StatefulSetAutoDeletePVC) and disabled by default on most cloud provider
I've set the flag to true by default, to not change the actual behavior
Fixes #7249
@trevorwhitney 
**Checklist**
- [ X] Reviewed the `CONTRIBUTING.md` guide
- [ X] Documentation added
=> [helm] Add a flag to enable/disable persistentVolumeClaimRetentionPolicy feature

docs/sources/installation/helm/reference.md, production/helm/loki/templates/gateway/deployment-gateway.yaml, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
Currently, pod labels for Loki services can only
be added via the `selectorLabels` key. However, it's a
confusing name as it actually doesn't change the
selectors but only adds additional pod labels.
Additionally, it's currently not possible to add labels 
for the gateway and single binary deployments.
This change adds a new `podLabels` key for all Loki services
analog to `podAnnotations` in order to prevent adding the
confusing `selectorLabels` key to more sections and keep
everything consistent.
The `selectorLabels` keys could then be removed with
the next major version bump of this chart.
=> Add config for optional pod labels

docs/sources/installation/sizing/index.md, pkg/sizing/algorithm.go, pkg/sizing/algorithm_test.go, pkg/sizing/http.go
The cluster sizing tool should use bytes as units internally to avoid the confusion between decimal and binary prefixes such as GiB and GB.
The frontend should use GiB since not all users will have terrabytes per day for their ingestion.
**Checklist**
=> Use GiB and bytes for sizing tool.

tools/lambda-promtail/README.md, tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/promtail.go, tools/lambda-promtail/main.tf, tools/lambda-promtail/template.yaml, tools/lambda-promtail/variables.tf
This PR sets a possibility to use lambda-promtail with self signed certificates sometimes used in development systems. This setting is configurable via environment variable.
Fixes #8013
**Checklist**
=> Lambda-promtail: Add skip tls verify option

.github/workflows/publish-technical-documentation-release.yml
This ensures documentation backported to this release branch is published to the correct website directory which is "v2.5.x".
Logic in the workflow determines the major and minor versions but we need to append the ".x" part as done for main in #6611.
=> Append .x to the versioned directories for the website sync (#6611)

CHANGELOG.md, clients/pkg/promtail/client/client.go, clients/pkg/promtail/client/client_test.go, clients/pkg/promtail/client/config.go, docs/sources/clients/promtail/configuration.md
This change will allow for more deterministic behavior by multitenant Promtail instances where one or more tenants are being heavily throttled due to limits exceeded within Loki. Specifically, it will reduce the performance impact of having exponential backoff cause HOL blocking for rate limit response codes while other tenants are ready to send batches.
Fixes #7972 
**Checklist**
=> Promtail: Add configuration to drop batches when rate limited by Loki

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/provisioner/job-provisioner.yaml, production/helm/loki/templates/tokengen/job-tokengen.yaml, tools/dev/k3d/Makefile, tools/dev/k3d/environments/helm-cluster/values/enterprise-logs.yaml, tools/dev/k3d/jsonnetfile.lock.json
This PR replaces https://github.com/grafana/loki/pull/7985. It solves the same problem, which is the race condition between the minio create bucket job and the enterprise tokengen job, but without removing minio.
**Checklist**
=> [helm] fix race between minio bucket job and enterprise tokengen job

Makefile
The current delimiter is `/` which breaks when a branch name contains that character. `:` is disallowed in branch names so should serve as a suitable delimiter
This is the same as https://github.com/grafana/loki/pull/8107 but the branch name doesn't include a `/`. That shouldn't be an issue after this is merged
=> Change delimiter in  test  "sed" command to ':'

docs/sources/installation/helm/install-monolithic/index.md
Its storage type, not filesystem type. Also "before you begin" seemed a bit vague given the list below, so I added that the list below was software requirements.
=> Fixed a typo and made a small edit to the Helm monolithic setup doc. 

clients/pkg/promtail/scrapeconfig/scrapeconfig_test.go
Fix the json section of a scrape config used in a unit test. The unit test doesn't fail as the unmarshaling is very generic. The json stage is unit tested in a different place.
This was mentioned as a comment on another PR: https://github.com/grafana/loki/pull/7653.
=> Fix json stage fields in example

dependabot.yml
Dependabot tries to update https://github.com/mattn/go-ieproxy to v0.0.9. This doesn't work as it seems to redeclare a function, probably due to missing build tags. This dependabot config file excludes this version. 
**Checklist**
=> Add dependabot.yml to ignore ieproxy dependency version

docs/sources/clients/promtail/stages/cri.md
Add description that `cri` stage not only adds labels for timestamp, but that it also sets the timestamp of the log-entry before sending it.
Honestly I don't know if this is the intention or not, but this is how things are implemented today and it makes the most sense. Even if not, changing the behavior now would not be possible without breaking old implicit assumptions, so better have more explicit documentation.
Existing Implementation: https://github.com/grafana/loki/blob/main/clients/pkg/logentry/stages/extensions.go#L31 
Existing tests for described behavior: https://github.com/grafana/loki/blob/main/clients/pkg/logentry/stages/extensions_test.go#L243 
Also clarify that the cri-`flags` get extracted as a label.
=> Promtail Docs: Clarifiy labels and timestamps set by cri stage

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml
The required secrets have already been created by @slim-bean.
Internal documentation is in
https://github.com/grafana/technical-documentation/pull/545.
(cherry picked from commit 1d47c7d54b44c67f986299c9518ea57ce237108b)
=> [release-2.5.x] Update publishing workflows to use PATs with fine-grained access control (#8062)

operator/docs/lokistack/object_storage.md
Fixes a typo in the documentation for the operator docs. for a successful installation using bucketname will fail. Configuring the secret with the key bucketnames should work. 
**Checklist**
=> operator: Fix docs minio storage uses bucketnames instead of bucketname

operator/CHANGELOG.md, operator/apis/config/v1/projectconfig_types.go, operator/apis/loki/v1beta1/rulerconfig_types.go, operator/apis/loki/v1beta1/v1beta1.go, operator/bundle/manifests/loki-operator-manager-config_v1_configmap.yaml, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/crd/bases/config.grafana.com_projectconfigs.yaml, operator/config/overlays/development/controller_manager_config.yaml, operator/config/overlays/openshift/controller_manager_config.yaml, operator/config/webhook/manifests.yaml, operator/internal/validation/rulerconfig.go, operator/internal/validation/rulerconfig_test.go, operator/main.go
Following #7839, this PR adds a validation on the Alertmanager `HeaderAuth` configuration in `RulerConfig`. This validation insures that `Credentials` and `CredentialsFile` are mutually exclusive and thus not defined in the same time.
**Which issue(s) this PR fixes:**
https://issues.redhat.com/browse/LOG-3443
**Checklist**
=> operator: Add API validation to Alertmanager header auth config

integration/loki_simple_scalable_test.go
This test is causing tens of timeouts across all PRs in our system. Delete it to improve CI stability
=> Remove flaky helm test

production/helm/loki/templates/_helpers.tpl
In Azure storage case, storage ruler config is correctly prepared, but not included.
The recently added support for azure blob storage is not fully functional in simple install. Code is there but not used because of a missing check update. The fix is trivial.
Fixes #8097 
**Checklist**
=> Helm: Add missing azure check

production/README.md, production/docker-compose.yaml
* auto-provisions the dockerized Loki as a datasource
* [existing docs](https://github.com/grafana/loki/tree/main/production#run-locally-using-docker) tell user to "follow the [steps for configuring the datasource in Grafana](https://github.com/grafana/loki/blob/main/docs/sources/getting-started/grafana.md)", but that link is broken
* and this docker-compose should be focused on getting the user up and running ASAP anyway, without requiring jumping to a different reference doc
**Checklist**
=> update local docker-compose file to provision the Loki data source

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml
(cherry picked from commit 1d47c7d54b44c67f986299c9518ea57ce237108b)
=> [release-2.6.x] Update publishing workflows to use PATs with fine-grained access control (#8062)

clients/pkg/promtail/client/batch.go, clients/pkg/promtail/client/batch_test.go
The labelsMapToString function takes a relative high amount of CPU in a simple promtail pipeline. By replacing the fmt.Sprintf with a string. Builder we achieve a 50+% improvement in the function.  In my local promtail installation I get about a 10% global cpu reduction. 
```
name                 old time/op    new time/op    delta
LabelsMapToString-8    1.10µs ± 3%    0.30µs ± 4%  -72.40%  (p=0.008 n=5+5)
name                 old alloc/op   new alloc/op   delta
LabelsMapToString-8      344B ± 0%      184B ± 0%  -46.51%  (p=0.008 n=5+5)
name                 old allocs/op  new allocs/op  delta
LabelsMapToString-8      14.0 ± 0%       6.0 ± 0%  -57.14%  (p=0.008 n=5+5)
```
The code does get more complex, and this …
=> Promtail: Improve LabelsMap CPU performance

production/helm/loki/templates/read/service-read-headless.yaml, production/helm/loki/templates/write/service-write-headless.yaml
This sets the `appProtocol` of the headless services of the `loki` helm chart to `tcp`.
This is needed when deploying the helm chart in combination with Istio due to it's protocol selection breaking the routing between replicas of the satefulsets.
This is in line with [the documentation](https://grafana.com/docs/loki/latest/operations/troubleshooting/#running-loki-with-istio-sidecars) for running Loki and Istio (#6205).
Note that this only applies to Istio >= 1.10 due to https://istio.io/latest/blog/2021/statefulsets-made-easier/
None
**Checklist**
=> helm: Add `appProtocol: tcp` to headless grpc ports

pkg/logql/log/parser.go, pkg/logql/log/parser_hints.go, pkg/logql/log/parser_test.go, pkg/logql/log/util.go
Sorry I couldn't help myself and worked a bit on the JSON parser by using another library that allows way less allocations.
On top of this, the parser code is also much simpler to understand.
I realize that we could possibly also intern/cache (limited obviously) extracted JSON value per key. I would do it per key because otherwise, a high cardinality key can take over the intern/cache which will make it worthless. Happy to walk someone through the idea, I think this would be a big jump too.
Would be great to run and test this in our dev environment using some JSON queries before releasing it.
```
❯ benchstat before.txt after.txt                                                                                                              
name                             old time/op    new …
```
=> Improve the JSON parser performance.

docs/sources/lids/0001-Introduction.md, docs/sources/lids/template.md
The extra colon causes a YAML parsing failure, see https://github.com/grafana/loki/actions/runs/3905966435/jobs/6678935989
=> Correct template and LID

pkg/logql/log/pipeline_test.go, pkg/storage/stores/indexshipper/compactor/compactor.go, pkg/storage/stores/indexshipper/compactor/compactor_test.go
Before compacting tables, we look up the schema config for them. If we do not find a schema config for a table, we skip them. However, the schema lookup code was considering the start time of the schema and not the end time.
This can cause the compactor to try compacting tables with the same prefix as one of the previous schemas, but the table interval falls into one of the subsequent schemas with a different config.
This PR fixes the issue and simplifies the code by reusing existing schema lookup code.
I have also updated test cases to verify the fix works.
**Checklist**
=> skip compacting tables that do not fit in start and end date of desired schema config

production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/ingester.libsonnet
The mimir team turned a lot of jsonnet deployment code/config into functions. The functions make common config across deployments/statefulsets easier, and also creation of new similar but slightly different deployments/statefulsets of exsting components simpler as well. For example, it will make zone aware ingester creation simpler. 
The current changeset should (as in I tested it via `tk diff`) result in no diff for our own environments.
Note that this is just ingester related, there's plenty of other nice jsonnet things the mimir team is doing that we could also copy.
=> [jsonnet] port some common jsonnet for statefulset and ingester creation

tools/lambda-promtail/main.tf
This PR removes a duplicate key in the terraform configuration sample
None
This is a trivial PR
=> lambda-promtail: remove duplicate key in terraform config sample

operator/docs/lokistack/object_storage.md
Fixes a typo in the documentation for the operator docs. for a successful installation using bucketname will fail. Configuring the secret with the key bucketnames should work.
N/A
**Checklist**
=> operator: Fix docs for OpenShift Data Foundation storage uses bucketnames instead of bucketname

production/helm/loki/templates/_helpers.tpl
This PR makes sure that the value of the `app.kubernetes.io/version` label in Kubernetes is the same as the image tag for Loki when set instead of always pinning it to the hardcoded `AppVersion` of the chart.
Fixes #8077
None
**Checklist**
=> Helm: Use image tag for version labels in kubernetes resources

.github/pull_request_template.md
The previous link lead to https://github.com/grafana/loki/CONTRIBUTING.md which doesn't exist.
=> Fix link to CONTRIUTING.md in PR template

Makefile
The check-mod stage failed on me but I wasn't sure how to fix it. Emitting a message should yield faster iterations.
**Checklist**
=> Emit help message when check-mod fails

CHANGELOG.md, clients/cmd/docker-driver/loki.go, clients/cmd/fluent-bit/client.go, clients/cmd/fluent-bit/dque.go, clients/pkg/promtail/client/client.go, clients/pkg/promtail/client/client_test.go, clients/pkg/promtail/client/logger.go, clients/pkg/promtail/client/multi.go, clients/pkg/promtail/client/multi_test.go, clients/pkg/promtail/limit/config.go, clients/pkg/promtail/promtail.go, clients/pkg/promtail/targets/lokipush/pushtarget_test.go, docs/sources/installation/helm/install-scalable/index.md
promtail: Add max-line-size limit to drop on client side 
Currently the workaround is to depend only on the loki server side limits.
This PR adds support in promtail to drop "too big" log lines. It also keep track of dropped lines in `promtail_dropped_entries` metric with reason `max_line_size_limited`.
Fixes #8143 
**Checklist**
=> promtail: Add `max-line-size` limit to drop on client side 

production/loki-mixin-compiled-ssd/alerts.yaml, production/loki-mixin-compiled/alerts.yaml, production/loki-mixin/alerts.libsonnet
Excludes the route `/schedulerpb.SchedulerForQuerier/QuerierLoop` from the `LokiRequestLatency` alert query config. We have found that this route often has extremely high request latencies which will trigger the alert constantly for us. Looking through the source code it seems like it is expected to have high request latencies for this route and so in our configuration have excluded the route. We can see that this route is also being excluded in the [respective mimir config](https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/alerts.yaml#L33) so believe it might be relevant to exclude here in loki as well
N/A
**Checklist**
=> Alerts: Exclude '/schedulerpb.SchedulerForQuerier/QuerierLoop' route in LokiRequestLatency alert

cmd/loki-canary/main.go, docs/sources/operations/loki-canary.md
This PR reverts commit f9ed9cb7d98dcdaa6fe2f1b7e97ca86af2864121 which introduced breaking config changes for the Loki canary. The relevant change introduced support for configuring a new `LOKI_ADDRESS` canary environment variable by adopting a new library for flags.
This is the easiest path forward to avoid forcing breaking config changes on canary operators; such a change is likely better suited to join other configuration changes in a future major Loki release.
N/A
Related PR:
- https://github.com/grafana/loki/pull/8024
**Checklist**
=> Revert "[loki-canary] Support passing loki address as environment variable (#8024)"

operator/CHANGELOG.md, operator/bundle/manifests/loki-operator-webhook-service_v1_service.yaml, operator/bundle/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/openshift/kustomization.yaml, operator/config/overlays/openshift/manager_webhook_patch.yaml, operator/config/overlays/openshift/webhook_service_annotations_patch.yaml
When installing the Loki Operator via OLM latter is reconciling the webhook creation dynamically by creating/owning/rotating the mandatory Server Certificate for accessing validating/mutating webhooks by the Kubernetes APIServer. In contrary our present approach/believe was that we need to instruct the Service and Certificate creation for the `loki-operator-webhook-service` generated by the operator-sdk. Although this service is part of the bundle it will remain obsolete on OpenShift clusters because OLM will generate its own `loki-operator-controller-manager-service` and Secret `loki-operator-controller-manager-cert`.
[LOG-3431](https://issues.redhat.com/browse/LOG-3431)
FYI, we …
=> operator: Remove custom webhook cert mounts for OLM-based deployment

operator/CHANGELOG.md, operator/controllers/loki/lokistack_controller.go, operator/controllers/loki/lokistack_controller_test.go
Following #7839, this PR adds a watch on the Alertmanager in the user-workload-monitoring namespace that is used when the operator is running on an OpenShift cluster. 
@periklis let me know if this is what you had in mind.
**Checklist**
=> operator: Add watch on the Alertmanager in OCP's user-workload-monitoring namespace

.drone/drone.jsonnet, .drone/drone.yml
Add a `depends_on` condition to the release stage so no releases are done if the check fails.
**Checklist**
=> Do not run release stage when check stage fails

pkg/loki/config_wrapper.go
Small fix for an annoyance due special case parsing for the `version` flag. Previously we looked for `-version`, now we use the the flag library to support both `--version|-version`
=> support single & double hyphen arguments in version printing

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/provisioner/job-provisioner.yaml, tools/dev/k3d/README.md, tools/dev/k3d/environments/helm-cluster/spec.json, tools/dev/k3d/jsonnetfile.lock.json
https://github.com/grafana/loki/pull/8081 introduced a bug that caused the `provisioner` job to create an incorrect secret for the self-monitoring tenant used by the canary. This fixes that bug, as well as adding a readme on how to use the `helm-cluster` k3d env.
**Checklist**
=> [helm] Fix self-monitoring tenant secret

cmd/loki-canary/main.go, docs/sources/operations/loki-canary.md
This PR cherry-picks d8a0c6f87fd2a13b84228c47058bb8d911fb4bee onto k133. Original description below:
This PR reverts commit f9ed9cb7d98dcdaa6fe2f1b7e97ca86af2864121 which introduced breaking config changes for the Loki canary. The relevant change introduced support for configuring a new `LOKI_ADDRESS` canary environment variable by adopting a new library for flags.
This is the easiest path forward to avoid forcing breaking config changes on canary operators; such a change is likely better suited to join other configuration changes in a future major Loki release.
N/A
Related PR:
- https://github.com/grafana/loki/pull/8024
**Checklist** …
=> Revert "[loki-canary] Support passing loki address as environment variable (#8024)" (#8183)

docs/sources/installation/helm/reference.md, production/helm/loki/templates/table-manager/_helpers-table-manager.tpl, production/helm/loki/templates/table-manager/deployment-table-manager.yaml, production/helm/loki/templates/table-manager/service-table-manager.yaml, production/helm/loki/templates/table-manager/servicemonitor-table-manager.yaml, production/helm/loki/values.yaml
The Table Manager is a Loki component which takes care of creating a periodic table before its time period begins, and deleting it once its data time range exceeds the retention period.
This PR is to add Table Manager support to the loki helm chart deployment as the current chart is based on the deprecated loki-simple-scalable chart that did not support Table Manager.
Fixes #<6830>
None
**Checklist**
=> Helm: Add Table Manager support to Loki helm chart

docs/sources/installation/helm/reference.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/gateway/deployment-gateway.yaml, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
This is to allow disable `enableServiceLinks` so that the service environments are not injected into the pods where in my scenario Loki is deployed in the same namespace as the Knative services resulted the Loki pod unable to start up due to too many service environment being injected.
Reference issue for pod unable to startup due to too many services: https://github.com/kubernetes/kubernetes/issues/84539#issue-514261281
**Checklist**
=> Helm chart: Add enableServiceLinks

docs/sources/installation/helm/reference.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml
Allow configuring ingester config from helm values: https://grafana.com/docs/loki/latest/configuration/#ingester
We wanted to change the default chunk_encoding, which right now not possible in the current values template.
**Checklist**
=> Helm: Add ingester config in helm values

docs/sources/installation/helm/_index.md, docs/sources/installation/helm/reference.md, production/helm/loki/reference.md.gotmpl
The docs and reference of the Helm chart in the documentation is only applicable for the Loki Helm chart `>= 3.0` and therefore does not apply to the `grafana/loki-stack` chart, which depends on the Loki Helm chart `^2.15.2` ([requirements.yaml](https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/requirements.yaml#L5)).
Also added a headline to the "Install Loki using Helm" index page, because it looks awkward without, see screenshot.
Fixes: #8152
**Checklist**
=> [docs] Clarify for what version the Helm chart docs are applicable

production/helm/loki/templates/NOTES.txt
Add component `backend` in the list of installed components on helm notes, based on `read.legacyReadTarget` value, just like backend statefulset.
**Checklist**
=> Helm: Fix components notes

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/read/deployment-read.yaml, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/runtime-configmap.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/tokengen/job-tokengen.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
This is completely inspired by similar value available in [loki-distributed](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed) via https://github.com/grafana/helm-charts/pull/1827, which is itself  largely inspired by similar value in [mimir-distributed](https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed) helm chart.
The idea is to have a dedicated configmap to handle [runtime_config](https://grafana.com/docs/loki/latest/configuration/#runtime-configuration-file), alway present even if empty. This way, having it seperately from main config, components pods are guaranteed not to restart for any changes.
```yaml
runtimeConfig:
overrides:
tenant1:
ingestion_rate_mb: 10
max_streams_per_user: 100000
max_chunks_per_query: 100000
tenant2: …
```
=> Helm - Loki: Introduce runtimeConfig

CHANGELOG.md, clients/pkg/promtail/limit/config.go, clients/pkg/promtail/promtail.go, docs/sources/clients/promtail/configuration.md
Follow up from #8153
Changes:
* Change type of the flag from `int` to `flagext.ByteSize` (to be consistent with similar flag in `distributor`)
* Add doc to promtail config page
* Fix changelog entries
Fixes #NA
**Checklist**
=> promtail: Add doc for `max-line-size` flag.

.github/workflows/doc-validator.yml, docs/Makefile, docs/sources/_index.md, docs/sources/api/_index.md
Source code:
https://github.com/grafana/technical-documentation/tree/main/tools/doc-validator
Adds a CI step for pull requests that validates links in technical documentation and performs linting of technical documentation source files.
- Lots of issues will need to be fixed before we can merge this.
- The tool is still in early development so each error should be scrutinized for validity.
**Checklist**
- [na] Tests updated
- [na] Is this an important fix or new feature? Add an entry in the `CHANGELOG.md`.
- [na] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> Docs: Add doc-validator tool to lint technical documentation

.github/workflows/doc-validator.yml
- Fixes regression where non-Markdown files are considered for linting.
- Uses a canonical algorithm for converting headings to anchor identifiers taken from the Hugo source.
=> Use latest release of doc-validator image

docs/sources/installation/helm/reference.md, production/helm/loki/reference.md.gotmpl
With its inclusion, the page tries to redirect
https://grafana.com/docs/writers-toolkit/latest/templates/reference-template/ to https://grafana.com/docs/loki/latest/installation/helm/reference/
=> Remove template alias from Helm chart reference

docs/sources/configuration/_index.md, docs/sources/configuration/index.template
PR https://github.com/grafana/loki/pull/7916 which introduced the documentation automation tool for Loki's configuration values, incorrectly removed the last sections of the documentation. This PR introduces them accordingly.
**Checklist**
=> Docs fix: add missing sections on index.template file

.github/workflows/doc-validator.yml
- Adds support for mailto scheme in links
- Makes some errata more user friendly
https://github.com/grafana/technical-documentation/releases/tag/doc-validator%2Fv1.9.0
=> Update doc-validator to latest release

CHANGELOG.md, pkg/ingester/instance.go
This is to give visibility on `labels` size of in-memory streams on the ingesters.
It caculate the size of labels via `len(labels.String())`. Meaning if you have 
```go
lbs := labels.Labels{
{Name: "foo", Value: "bar"},
{Name: "instance", Value: "loki"},
}
```
size would be number of bytes in `{foo="bar", instance="loki"}` which is `28`. NOTE: `len(string)` gives [bytes length in Go](https://pkg.go.dev/builtin#len)
Fixes #NA
Wanted this visibility for some of the work I'm doing it with ingester in-memory streams.
**Checklist**
=> ingester: Add `ingester_memory_streams_labels_bytes` metric

pkg/distributor/distributor.go
Previously this metric was not not incremented for all the log lines in the stream. This PR fixes it.
Fixes #NA
**Checklist**
=> distributor: Fix `loki_mutated_bytes_total` metric increment

pkg/logql/evaluator_test.go, pkg/logql/log/drop_labels.go, pkg/logql/log/parser.go, pkg/logql/syntax/parser.go, pkg/storage/stores/series_store_write_test.go, pkg/storage/stores/shipper/indexgateway/gateway.go
the curren validation fails on != style matchers when they are the only matchers present, requiring at least one `=` matcher.
However for looking up label values in TSDB, by design it uses a `desired_label != ""` style query, as such it should be allowed to also include these as matchers.
Additional matchers on this Label Value queries typically only exist with LBAC headers adding additional labels.
**Checklist**
=> Loki: Remove validation of matchers when performing label values lookup.

pkg/logql/evaluator_test.go, pkg/logql/log/drop_labels.go, pkg/logql/log/parser.go, pkg/logql/syntax/parser.go, pkg/storage/stores/series_store_write_test.go, pkg/storage/stores/shipper/indexgateway/gateway.go
This PR cherry-picks https://github.com/grafana/loki/commit/c8760f31e26acfe575d2f1e71ce6044c69606ca4 onto `k133` -- original PR description below:
the current validation fails on != style matchers when they are the only matchers present, requiring at least one `=` matcher.
However for looking up label values in TSDB, by design it uses a `desired_label != ""` style query, as such it should be allowed to also include these as matchers.
Additional matchers on this Label Value queries typically only exist with LBAC headers adding additional labels.
**Checklist**
Signed-off-by: Edward Welch …
=> Loki: Remove validation of matchers when performing label values lookup. (#8224)

pkg/loki/config_wrapper.go
Using the flag parser results in a confusing message being printed
```
flag provided but not defined: -config.file
Usage of version parsing:
-version
Print this builds version information
```
Corrects a minor bug introduced by #8199
=> Match version flag using regex

clients/cmd/promtail/main.go, clients/pkg/promtail/client/config.go, clients/pkg/promtail/config/config.go, clients/pkg/promtail/config/config_test.go, docs/sources/clients/promtail/configuration.md, tools/kafka/README.md
Allows for more graceful degredation when using deprecated `stream_lag_labels` setting.
Also removed hanging references to the setting.
=> Do not exit when using `stream_lag_labels` setting

pkg/logql/engine.go, pkg/logql/engine_test.go, pkg/logql/metrics.go, pkg/logql/metrics_test.go
- Adds a new `query_hash` label pair to queries logged by `metrics.go`. As the name suggests, `query_hash` is just the hashed version of the query being logged.
- Especially useful when grouping results/behavior of different queries. Ex, you can easily find specific query patterns with `sum by(query_hash)` .
Ex:
```
level=info ts=2023-01-23T14:45:52.743780661Z caller=metrics.go:149 component=frontend org_id=fake latency=fast query="{stream=\"stdout\",pod=\"loki-canary-abcde\"}" query_hash=1360642565 query_type=limited range_type=range length=20s start_delta=58m27.642790018s end_delta=58m7.64279027s step=1s duration=4.761564089s status=200 limit=1000 returned_lines=0 throughput=78kB total_bytes=369kB total_entries=41 …
```
=> Loki: Log hashed queries emitted by `metrics.go`

pkg/logql/engine.go, pkg/logql/engine_test.go, pkg/logql/metrics.go, pkg/logql/metrics_test.go
This is a backport of PR 8244.
=> Backport PR 8244 (Log hashed queries emitted by `metrics.go`)

pkg/storage/stores/series/series_index_store.go
Instead of doing the `Get` inside a function and `Put` outside, do them both outside. This makes it clearer that it's ok to `defer` before checking for errors, which avoids dropping a pooled slice as garbage on any error.
A particular case is `CardinalityExceededError` where the dropped slice will be large, and which is treated as benign unless it happens on all matchers.
Change the pooled objects to pointer type to avoid the Go runtime creating a pointer wrapper, and we can stop silencing the warning about this from the staticcheck linter.
**Checklist**
- NA `CHANGELOG.md` updated - no user-visible difference.
- NA Changes that require user attention or interaction to upgrade are documented in …
=> stores/series: always return entries to pool

docs/sources/installation/helm/reference.md, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
Add the possibility to add initContainers to  write, backend and singleBinary's stateful set. 
This was required for us to initialize the volume with appropriate access modes. We use Amazon EFS.
Fixes #
**Checklist**
- [x ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
=> Helm: Add initContainers to write, backend, singleBinary templates

tools/dev/k3d/environments/helm-cluster/main.jsonnet, tools/dev/k3d/environments/helm-cluster/values/enterprise-logs.yaml
This patch raises the Grafana Enterprise version and enables multi tenant queries on our test environment.
**Checklist**
=> Enalbe multi tenant queries on Helm test chart.

pkg/util/log/log.go
Fixes a slight clarity regression in https://github.com/grafana/loki/pull/7924/files
The warning about the logger being unable to flush would be logged regardless of whether there was an error or not.
=> Only print logger error when required

CHANGELOG.md, pkg/storage/store_test.go, pkg/storage/stores/index/index.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/series/series_index_gateway_store.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/series_store_write.go, pkg/storage/stores/series_store_write_test.go, pkg/storage/stores/tsdb/store.go
We noticed that when a chunk overlaps multiple schemas, the index entries are being built for whole chunk range for both schemas. We should be building index entries in each stores, limited to their schema interval.
For example, `schema[0]` is `boltdb-shipper` starting at `0` and `schema[1]` is `tsdb` starting at `10`. If chunk 8-11 is flushed, it should be indexed in `schema[0]` with index entries for range 8-9, and for `schema[1]`, it should be 10-11.
However, due to my mistake in changeset [here](https://github.com/grafana/loki/commit/c8c8303a6a6767b8e6e196e9e160dbb2c6887273#diff-c2c327d47d019a916c9c1b5e668bae2e5b05a89533a90001e42cbf334ed861eaL101) I changed the behaviour, now we are indexing chunk for 9-11 in both the stores. This is causing us …
=> index-store: fix indexing of chunks overlapping multiple schemas

production/helm/loki/templates/backend/statefulset-backend.yaml
The selector value in the backend's volumeClaimTemplates has no effect. `values.yaml` already contains the appropriate key: https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L913
Fixes #
**Checklist**
- [x ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
=> Helm: Add selector to backend's volumeClaimTemplates

pkg/storage/stores/tsdb/head_manager.go
Ran into this in a set of confusing circumstances. I haven't figured out the cause yet, so I'm adding some extra logging to get further next time I see it.
=> logs more metadata when failing to recover head from WAL in TSDB

Makefile, docs/sources/configuration/examples.md, docs/sources/operations/storage/tsdb.md
Turns out the `docs-validator` doesn't do an entire check of the docs. This PR fixes some build issues and some additional linting issues.
=> fix remaining docs issues

docs/sources/installation/helm/reference.md, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
- This pr https://github.com/grafana/loki/pull/7640 introduced persistence `enableStatefulSetAutoDeletePVC` but *only*  on read pods
- This pr https://github.com/grafana/loki/pull/7920 introduced persistence `enableStatefulSetAutoDeletePVC` backend value, but did not implement it in related statefulset definition.
I propose to generalize persistence `enableStatefulSetAutoDeletePVC` on *all* statefulsets:
- read
- write
- backend
- singleBinary
To introduce this PR, i've set all default values to `true` but it could be relevant to think deeper about all specific component default value.
**Checklist**
=> Helm: Generalize enableStatefulSetAutoDeletePVC

docs/sources/installation/helm/reference.md, production/helm/loki/values.yaml
Add a default `grafana_dashboard` grafana dashboard label, so that dashboards could be detected by grafana out-of-the-box.
kube-prometheus-stack chart make the same choice here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L812
**Checklist**
=> Helm: Default grafana dashboard label

operator/CHANGELOG.md, operator/internal/manifests/config.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml
This PR changes the Loki configuration to use the gRPC service for the compactor instead of the HTTP one. In doing so, this mitigates an issue where the compactor and querier have TLS handshake errors when retention is active.
**Checklist**
=> operator: Use gRPC instead of http for compactor communications

CHANGELOG.md, docs/sources/logql/template_functions.md, pkg/logql/log/fmt.go, pkg/logql/log/fmt_test.go
Usage:
1. {{.foo | urlencode }} {{ urlencode .foo }}
2. {{.foo | urldecode }} {{ urldecode .foo }}
Example:
1. {instance="loki"} |= "routes" | logfmt | {{ .url | urldecode}}
Fixes #8220 
**NOTE** some tools or languages treats `/` as safe and will not encode it. But Go encode including character `/`. 
e.g: 
encoding '/loki' will return following in Go
```bash
go-play$ head main.go 
package main
import (
"fmt"
"net/url"
)
func main() {
fmt.Println(url.QueryEscape("/loki"))
}
go-play$ go run main.go 
%2Floki
```
But return following in Python
```bash
In [9]: import urllib.parse
In [10]: urllib.parse.quote('/loki')
Out[10]: '/loki' …
```
=> logql: Support `urlencode` and `urldecode` template functions

CHANGELOG.md, Makefile, tools/fetch-tags
* It should fetch all tags before extracting tag info to ldflag of the build.
* This issue could happen if a build tag like v2.7.1 was not fetched properly and then the build process was running. 
* The following promtail is https://github.com/grafana/loki/releases/download/v2.7.1/promtail-darwin-arm64.zip
* If there's no tag on the exact commit to publish, then <kbd>BRANCH</kbd> variable becomes HEAD, so the <kbd>VERSION</kbd> variable becomes like "HEAD-e0af1cc".
* https://github.com/grafana/loki/blob/86dcc8231bed247fc29a5f5e25c6bb184d08fa71/tools/image-tag#L7-L21
* https://github.com/grafana/loki/blob/86dcc8231bed247fc29a5f5e25c6bb184d08fa71/Makefile#L35
* Fixes #7669, #8055  …
=> Loki: Fix version info issue that shows wrong version (#7669, #8055)

.drone/drone.jsonnet, .drone/drone.yml, clients/cmd/fluent-bit/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, tools/go-version-bump.sh, tools/lambda-promtail/Dockerfile
* 1st step in updating build image
* Update golang base image in all Dockerfiles (including a new script to automate this a bit)
https://pkg.go.dev/vuln/GO-2022-1144
=> Update golang to 1.19.5

production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl
Fix this:
```console
$ helm install loki grafana/loki \
--set loki.image.tag=2.7.1@sha256:d69f377ecfdbb3f72086a180dcd7c2f02c795cf1867bbeb61606b42a8d41a557
ServiceAccount "loki" is invalid: [
metadata.labels: Invalid value: "2.7.1@sha256:d69f377ecfdbb3f72086a180dcd7c2f02c795cf1867bbeb61606b42a8d41a557": must be no more than 63 characters,
metadata.labels: Invalid value: "2.7.1@sha256:d69f377ecfdbb3f72086a180dcd7c2f02c795cf1867bbeb61606b42a8d41a557": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
],
Service "loki" is invalid: [ …
```
=> Helm: ensure valid label values when version has digest

CHANGELOG.md, integration/cluster/cluster.go, integration/multi_tenant_queries_test.go, pkg/logql/downstream.go, pkg/logql/engine.go, pkg/loki/loki.go, pkg/querier/http.go, pkg/querier/queryrange/querysharding.go, pkg/validation/limits.go
This PR backports a fix for multi-tenant queries in Loki 2.7
#7555 contains the actual fix
#7708 is required because 7555 depends on it
=> Backport PRs #7555 and #7708 to 2.7 release branch

clients/pkg/promtail/targets/gcplog/pull_target.go, clients/pkg/promtail/targets/gcplog/pull_target_test.go
Exiting from the run loop of a started target isn't meaningful. Retry forever
=> Retry getting logs from pubsub forever

.drone/drone.jsonnet, .drone/drone.yml, Makefile, clients/cmd/docker-driver/Dockerfile, clients/cmd/fluent-bit/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, operator/Dockerfile.cross, tools/go-version-bump.sh, tools/lambda-promtail/Dockerfile
This PR is a combined backport of #8278 and #8279. When done against `main`, updating the Go version and therefore also the Loki build image is a two-step process. However, when backporting this the two PRs against `main` can be combined into a single step, because the new version of the build image is already built and available.
=> Backport #8278 and #8279 (update Go version to 1.19.5)

pkg/logql/rangemapper_test.go, pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go
Sorts the imports correctly according to linter requirements.
=> [chore] Sort imports so that linter does not complain

CHANGELOG.md, docs/sources/release-notes/v2-7.md
This PR prepares the release `2.7.2`. It ...
* ... updates the CHANGELOG
* ... updates the release notes
~* ... updates the versions in the `production/` folder~
~* ... updates the versions in the installation docs~
**Notes for reviewers**
I am not sure why we cannot update the version in ksonnet https://github.com/grafana/loki/blob/main/docs/sources/maintaining/release.md?plain=1#L59-L63
The third commit of this PR however updates the versions in the ksonnet folder.
**Update:**
I removed the version updates in the production/ and docs/ folders. There is a separate PR for that, which will be merged after the new images are built.
=> Prepare release 2.7.2 - Part 1

production/helm/loki/CHANGELOG.md
Added automated update locator to helm chart changelog. it will be used to automate helm chart update on Loki/GEL release. Drone CI will put changelog entry to the next line after locator.
=> Helm Chart release automation (step 1)

pkg/logql/engine.go, pkg/logql/engine_test.go, pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/split_by_range.go
This is a continuation of #7469
I had to add a way to disable logging of the "executing query" line from the Engine in the query frontend because this is called for every split by time and shard created by our roundtrippers leading to many "executing query" lines for a single query which is not desired.
Added the "executing query" line to the roundtripper and it now covers: range, instant, series, and labels queries.
It should now also only log one line per query making it possible to correlate this to the "metrics.go" line for a finished query to help debug queries which don't finish because of OOM crash. …
=> Loki: only log "executing query" once per query in the frontend

.drone/drone.jsonnet, .drone/drone.yml
Our test-coverage report is noisy and reports for every single commit even when coverage doesn't change or the files changed are in different packages. This PR sums the coverage diff and only posts to the PR if it is non zero.
=> Only report test coverage when it changes

pkg/storage/stores/indexshipper/compactor/deletion/request_handler.go, pkg/storage/stores/indexshipper/compactor/deletion/request_handler_test.go
This PR enforces that a the duration of a delete request covers at least 1 second.
Delete requests are designed with second-precision in mind. Without this fix, users are able to submit requests where `startTime == endTime`. In addition to logically ambiguous, it causes a divide-by-zero panic.
=> Ensure a delete request interval of at least a second

production/loki-mixin-compiled/dashboards/loki-reads-resources.json, production/loki-mixin-compiled/dashboards/loki-writes-resources.json, production/loki-mixin/dashboards/dashboard-utils.libsonnet
We use a regex value for this container: https://github.com/trevorwhitney/loki/blob/751fd7984dcb585d125a63097c84d2fc56eb2c47/production/loki-mixin/dashboards/loki-writes-resources.libsonnet#L19
=> fix dashboard helper to use regex

pkg/storage/stores/index/metrics.go, pkg/storage/stores/indexshipper/gatewayclient/gateway_client.go
* Renames a metric that was poorly named and suggested it was only available for the boltdb-shipper. This is breaking, but I didn't find any references in our included mixin/etc. 
* Increases histogram bucket ranges to allow measuring beyond 10s p99s for index queries.
=> Update index metrics

pkg/sizing/algorithm.go, pkg/sizing/algorithm_test.go
The sizing tool should set the minimum replicas to three so that high availability is enabled.
Fixes #8296
**Checklist**
=> Sizing Tool: Set the minimum replias to 3.

docs/sources/installation/sizing/index.md
The input fields would hide the units which makes it harder to reason about the results. This change appends the units.
Fixes #8295
**Checklist**
=> Sizing tool: Display units.

production/helm/loki/templates/_helpers.tpl
The limits configured in the NGinx ingress should align with the timeouts and limits withing Loki.
Fixes #8203
**Checklist**
=> Helm: Align ingress timeout and size limits.

operator/CHANGELOG.md, operator/internal/handlers/internal/rules/cleanup.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/handlers/lokistack_create_or_update_test.go
This PR adds a the removal of ruler resources when it has been disabled.
[LOG-3507](https://issues.redhat.com/browse/LOG-3507)
**Checklist**
=> operator: Cleanup ruler resources when disabled

clients/cmd/promtail/main.go, clients/pkg/promtail/targets/gcplog/pull_target.go, clients/pkg/promtail/targets/gcplog/pull_target_test.go, cmd/loki-canary/main.go, pkg/logproto/alias.go
I got messages about these issues in https://drone.grafana.net/grafana/loki/19790/3/9, and since they are not relevant to that PR I've pulled them out to a separate PR.
Mostly re-ordering import lines to match `goimports` expectations. One spelling fix.
**Checklist**
- NA `CHANGELOG.md` updated
- NA Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> Cosmetic lint warning fixes

CHANGELOG.md, docs/sources/release-notes/v2-7.md
Prepares the new Loki version 2.7.3
---
This new release consists a fix for the build system, which was introduced once we moved building the binaries off CircleCI to Drone.
DroneCI checks out the commit of the tag directly and therefore did not have the tag information at hand when running `./tools/image-tag`.
=> Prepare 2.7.3 changelog and release notes

.drone/drone.jsonnet, .drone/drone.yml
Pin the Windows build Go version so we don't get the following error:
```
+ go test .\\clients\\pkg\\promtail\\targets\\windows\\... -v
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.20 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.20 set. Notably, if go1.20 adds a moving garbage collector, this program is unsafe to use.
```
**Checklist**
=> Pin windows build Go version

integration/client/client.go, integration/loki_micro_services_delete_test.go
This test failed due to the returned delete requests being in a different order. Note that these delete requests have the same start time.
**Checklist**
=> Fix comparison in a delete request integration test

.drone/drone.jsonnet, .drone/drone.yml, CHANGELOG.md, pkg/storage/store_test.go, pkg/storage/stores/index/index.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/series/series_index_gateway_store.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/series_store_write.go, pkg/storage/stores/series_store_write_test.go, pkg/storage/stores/tsdb/store.go
Backports https://github.com/grafana/loki/pull/8251 to `k134`
This also includes the change to pin the promtail windows container to golang 1.19
=> index-store: fix indexing of chunks overlapping multiple schemas (#8251)

CHANGELOG.md, production/loki-mixin-compiled-ssd/alerts.yaml, production/loki-mixin-compiled-ssd/dashboards/loki-reads.json, production/loki-mixin-compiled-ssd/dashboards/loki-writes.json, production/loki-mixin-compiled-ssd/rules.yaml, production/loki-mixin-compiled/alerts.yaml, production/loki-mixin-compiled/dashboards/loki-reads.json, production/loki-mixin-compiled/dashboards/loki-writes.json, production/loki-mixin-compiled/rules.yaml, production/loki-mixin/alerts.libsonnet, production/loki-mixin/dashboards/loki-reads.libsonnet, production/loki-mixin/dashboards/loki-writes.libsonnet, production/loki-mixin/recording_rules.libsonnet
Signed-off-by: Whyeasy <Whyeasy@users.noreply.github.com>
With the introduction of `per_cluster_label`, the selectors got updated within the dashboards. Within the `Reads` and `Writes` dashboard the latency panels are now empty.  The recording rules were missing the `per_cluster_label` as an extra selector, which was used within the latency panel. Adding the cluster label to the recording rules changed the name of the rules. 
This PR adds the `per_cluster_label` to all the recording rules. Updates the dashboards using them and there was 1 alert using it as well.
**Checklist**
=> [Mixin] Update clusterlabel usage

docs/sources/installation/helm/install-scalable/index.md
This typo is fixed in NEXT but doesn't appear to have been backported to LASTEST (2.7 branch) and was reported by a customer.
=> Fixing typo in 2.7.x branch.

CHANGELOG.md, docs/sources/tools/logcli.md, pkg/logcli/query/query.go, pkg/logcli/query/query_test.go
In order to support multiple tenants with different schemas on a single object storage bucket, LogCLI needs to support loading tenant-specific schema files. If the tenant-specific file is not found, it falls back to the global `schemaconfig.yaml`.
**Checklist**
=> [LogCLI] Load tenant-specific schema config file when using `--remote-schema`

.github/workflows/doc-validator.yml
In the future, all images will be stored in GCS and not in the repository and this linting rule will be removed.
Until then, skip insisting that all images are in page bundles.
=> Skip image validation

clients/cmd/fluentd/Dockerfile, clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec
The plugin works with Ruby 3.2 but its spec file limited it to Ruby versions < 3.0
Fixes https://github.com/grafana/loki/issues/8195
**Checklist**
=> Update fluent-plugin-grafana-loki to Ruby 3.2

docs/sources/installation/helm/install-monolithic/index.md, docs/sources/installation/helm/monitor-and-alert/index.md, docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/gateway/configmap-gateway.yaml, production/helm/loki/templates/gateway/deployment-gateway.yaml, production/helm/loki/templates/gateway/hpa.yaml, production/helm/loki/templates/gateway/ingress-gateway.yaml, production/helm/loki/templates/gateway/poddisruptionbudget-gateway.yaml, production/helm/loki/templates/gateway/secret-gateway.yaml, production/helm/loki/templates/gateway/service-gateway.yaml, production/helm/loki/templates/single-binary/_helpers-single-binary.tpl, production/helm/loki/templates/single-binary/service.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/tokengen/clusterrole-tokengen.yaml, production/helm/loki/templates/tokengen/clusterrolebinding-tokengen.yaml, production/helm/loki/templates/tokengen/job-tokengen.yaml, production/helm/loki/templates/tokengen/serviceaccount-tokengen.yaml, production/helm/loki/templates/validate.yaml, production/helm/loki/values.yaml, tools/dev/k3d/Makefile, tools/dev/k3d/environments/helm-cluster/main.jsonnet, tools/dev/k3d/environments/helm-cluster/values/enterprise-logs-ha-single-binary.yaml, tools/dev/k3d/environments/helm-cluster/values/loki-ha-single-binary.yaml
The PR allows an operator to install Loki in Single Binary mode in an HA fashion, meaning more than 1 Single Binary replica. In order for this to work, it is not possible to specify an object storage backend when running in Single Binary mode. The gateway is also now always enabled, for both Single Binary and Scalable modes.
Fixes #8269 #8185
This PR builds off #8261, will rebase after that is merged and diff will be smaller.
**Checklist**
=> [helm] Single binary object storage

operator/bundle/metadata/properties.yaml
The current main branch reflects also the next OpenShift Logging 5.7 release. This release will support up to OCP 4.15 based on RedHat's policy.
**Checklist**
=> operator: Bump bundle OCP max version property to 4.15

clients/cmd/fluentd/Makefile, clients/cmd/fluentd/fluent-plugin-grafana-loki.gemspec
Bump version so we can publish a new gem to RubyGems
=> Bump version of `fluent-plugin-grafana-loki` to 1.2.20

docs/sources/_index.md, docs/sources/getting-started/_index.md, docs/sources/installation/_index.md, examples/README.md
Removes the hard-coded note about the Grafana Cloud option, because this information is now generated automatically on the docs site (and thus is being displayed twice).
**Checklist**
=> Remove call to action from 2.7 release.

operator/CHANGELOG.md
Address missing release section in the operator changelog namely for public release `v0.1.0`.
**Checklist**
=> operator: Add missing release section into the changelog

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml
The new tokens are managed centrally and have a longer expiry. Administrators of the grafanabot account will be
notified of the pending expiry and the secret can be rotated centrally without the need for a repository administrator to update their secrets.
The existing repository secrets can safely be removed. The tokens for those secrets will be removed by the end of this week.
=> Update publishing workflows to use organization secret

integration/loki_micro_services_delete_test.go
Returned elements may not be in order. Therefore checking if elements match.
=>  Fix flaky `TestMicroServicesDeleteRequest` integration test

CHANGELOG.md, clients/pkg/logentry/stages/eventlogmessage.go, clients/pkg/logentry/stages/eventlogmessage_test.go, clients/pkg/logentry/stages/stage.go, docs/sources/clients/promtail/pipelines.md, docs/sources/clients/promtail/scraping.md, docs/sources/clients/promtail/stages/eventlogmessage.md
The Windows Event Log includes a field named `Message` that include a large amount of additional data, stored in a simple key-value format: 
* key-value pairs are separated with Windows-style `\r\n` newlines,
* the key and value are separated with `: ` (or just `:` if the key has no associated value).
The key-value data in the `Message` field is commonly utilised when investigating Windows events, e.g., in security use-cases, but the existing `windows_events` pipeline stage keeps the Message data as a string, leading to requiring significant effort at the query time to extract that data to be used in field filters.
This PR request introduces a new promtail stage that parses a specified Source (defaulting to `message` used by the `windows_events`) …
=> Promtail: Add event log message stage

production/ksonnet/loki/loki.libsonnet
compactor additions were not being applied correctly from memberlist jsonnet
=> [jsonnet] fix import ordering in loki.libsonnet

docs/sources/installation/sizing/index.md
The unit in the help text for expected daily ingest was wrong.
**Checklist**
=> Correct sizing tool unit in help text.

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/provisioner/job-provisioner.yaml
Fix rendering of namespace in provisioner job template when a `secertNamespace` is provided that's different from the release namespace.
Fixes #8403
**Checklist**
=> Fix namespace rendering in provisioner job

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/service-memberlist.yaml, production/helm/loki/values.yaml
Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>
Faster memberlist join
By reading the documentation
```
% k explain service.spec.publishNotReadyAddresses
KIND:     Service
VERSION:  v1
FIELD:    publishNotReadyAddresses <boolean>
DESCRIPTION:
publishNotReadyAddresses indicates that any agent which deals with
endpoints for this Service should disregard any indications of
ready/not-ready. The primary use case for setting this field is for a
StatefulSet's Headless Service to propagate SRV DNS records for its Pods
for the purpose of peer discovery. The Kubernetes controllers that generate
Endpoints and EndpointSlice resources for Services interpret this to …
```
=> [Helm] Allow to configure publishNotReadyAddresses on memberlist service

docs/sources/installation/helm/monitor-and-alert/index.md
Add a section to the helm monitoring docs about the need for ServiceMonitors to have the correct label to be discovered by the Prometheus Operator.
=> add section to prom operator instructions about necessary label

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/validate.yaml, production/helm/loki/values.yaml
We need to set the compactor address when running 3 target scalable mode as the querier is no longer co-located with the compactor.
**Checklist**
=> [helm] set compactor address

CHANGELOG.md, pkg/logql/syntax/ast.go, pkg/logql/syntax/parser.go, pkg/logql/syntax/parser_test.go, pkg/querier/queryrange/querysharding.go
This PR fixes two bugs where a query with the `vector()` expression failed because it could not be parsed and returned the error:
```
error : queries require at least one regexp or equality matcher that does not have an empty-compatible value. For instance, app=~".*" does not meet this requirement, but app=~".+" will
```
* The case where `vector()` was used as a `LogSelectorExpr`, e.g. in `label_format(vector(0), "foo", "bar", "", "")`
* The case where `vector()` was used in a `VectorAggregationExpr`, e.g. in `sum(vector(0))`
Fixes https://github.com/grafana/loki/issues/8266
**Checklist**
=> Fix parsing of vector expression

pkg/logql/downstream_test.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/parser_test.go
While adding some tests to compliment https://github.com/grafana/loki/pull/8448, I noticed some imprecision when determining whether a binary operation is shardable. Particularly,
* It is unshardable when using `on` grouping or when using `ignoring` with a non-zero set of labels to ignore as this can mutate labels.
* It is shardable when using `ignoring ()` is effectively the zero value which cannot mutate labels.
=> More precise sharding logic for `on|ignoring`

docs/sources/configuration/_index.md, pkg/storage/bucket/swift/config.go, pkg/storage/chunk/client/openstack/swift_object_client.go
This commit exposes the `internal` parameter of the swift client library in loki config. It allows to configure swift to use the internal endpoint of an openstack installation.
Fixes #8437
**Checklist**
=> Swift: Allow to configure swift with the internal endpoint

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/ci/default-values.yaml, production/helm/loki/ci/enterprise.yaml, production/helm/loki/ci/ingress-values.yaml, production/helm/loki/values.yaml
This PR bumps the loki version to 2.7.3, it also reverts back to 2 target mode as default for simple scalable since the third target has not yet been included in minor release.
The CI jobs are still using 3 target configurations, hence the custom loki image tag.
**Checklist**
=> [helm] Bump to Loki 2.7.3

production/helm/loki/templates/backend/statefulset-backend.yaml
Similar to https://github.com/grafana/loki/pull/7695 but for the backend template.
Read only /tmp errors in backend pods in 3 targets mode (loki helm chart simple scalable mode with legacyReadTarget: false ).
Fixes [helm-charts#2191](https://github.com/grafana/helm-charts/issues/2191)
**Checklist**
=> [helm] Fix read-only /tmp in 3 targets mode

CONTRIBUTING.md, docs/README.md
The Loki CONTRIBUTING file didn't contain any information about contributing to the docs.  Added some basic content.
**Checklist**
=> Updated CONTRIBUTING file for docs.

pkg/querier/queryrange/limits.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go
In #7510 we removed the bypass for "limited" queries.
A limited query is a logs query which has no filter expression `{app="foo"}`
Generally speaking these are very easy queries for Loki to return as it only needs to find 1000 lines.
However for a query which matches a LOT of streams and a LOT of data and runs over a long timeframe, because we bypassed the split by time and shard by time, that query was sent to execute on one querier only which would often result in overwhelming it with the amount of chunks that had to be loaded to properly sort to find the first 1000 lines.
Removing the bypass helped this by allowing the query to be executed over smaller timeframes and to shard so that each querier had to match fewer series.
This however had …
=> Loki: Process "Limited" queries sequentially and not in parallel

pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/shard_resolver.go
This is a modification to #8482, instead of fixing the number of shards we will set a maximum value.
Using a fixed shard count resulted in oversharding of queries which had very little data.
**Checklist**
=> Loki: set a maximum number of shards for "limited" queries instead of fixed number

tools/dev/k3d/Makefile
Add --debug flag to helm command on tools/dev/k3d
The --debug flag can be especially useful when (un)installing helm charts.
The installation of the enterprise-logs takes some minutes due to the required initial job execution, mainly `tokengen` and `provisioner`. Therefore, when debugging it can be extremely useful to know which step is currently in execution and if there was any failure.
```
> make helm-install-enterprise-logs // equivalent to 'make DEBUG=false helm-install-enterprise-logs
helm --debug=false install enterprise-logs-test-fixture "/Users/ssncf/Documents/grafana/git/loki/production/helm/loki" -n loki --create-namespace --values "/Users/ssncf/Documents/grafana/git/loki/tools/dev/k3d/environments/helm-cluster/values/enterprise-logs.yaml" …
```
=> Helm: add debug option to helm command for verbose output on local development

pkg/querier/queryrange/shard_resolver.go, pkg/querier/queryrange/shard_resolver_test.go
Fixes a bug introduced in https://github.com/grafana/loki/pull/8487 which had the effect of always enforcing shard factor of 1 when max-shards was intended to be disabled: https://github.com/grafana/loki/pull/8487
=> correctly calculate max shards

pkg/querier/queryrange/limits.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/shard_resolver.go, pkg/querier/queryrange/shard_resolver_test.go
Recutting k136 release to have these fixes:
- [correctly calculate max shards](https://github.com/grafana/loki/commit/495c511d777af2a0ea4a3c349d09cb643e253e05)
- https://github.com/grafana/loki/pull/8482
- https://github.com/grafana/loki/pull/8487
**Checklist**
=> Recut k136

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
With this PR we could override the generated read/write/backend URLs for the gateway.
For instance, here I show the differences in proxy_pass definitions when overriding these paths:
```
[loki]$ helm template . | grep proxy_pass
proxy_pass       http://loki-write.default.svc.cluster.local:3100$request_uri;
proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
proxy_pass       http://loki-read.default.svc.cluster.local:3100$request_uri;
proxy_pass …
```
=> helm: values to override read/write/backend paths in gateway config

tools/dev/k3d/Makefile
Add `SLEEP` argument to configure the time in seconds to wait for helm cluster commands to apply.
In some cases, a sleep interval of 5s is not enough for the cluster to be ready for helm charts installation resulting in errors such as:
```
Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://prometheus-kube-prometheus-operator.k3d-helm-cluster.svc:443/admission-prometheusrules/mutate?timeout=10s": no endpoints available for service "prometheus-kube-prometheus-operator"
helm.go:84: [debug] Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post …
```
=> Helm: add sleep argument to helm makefile on local development

docs/sources/logql/analyzer.md
Temporarily unpublish the Analyzer page due to a vulnerability.
See https://github.com/grafana/support-escalations/issues/5021
=> Temporarily unpublish Analyzer page.

Makefile, docs/sources/configuration/_index.md, docs/sources/configuration/examples.md, docs/sources/configuration/examples/10-S3-And-DynamoDB-With-KMS-Snippet.yaml, pkg/storage/chunk/client/aws/dynamodb_storage_client.go, pkg/storage/chunk/client/aws/dynamodb_table_client.go
This change adds a `kms_key_id` configuration to the `storage_config.aws.dynamodb` config.  This is used when creating DynamoDB tables to enable SSE using the specified KMS key.
Currently DynamoDB tables can only be encrypted using Amazon Owned KMS keys, and this has security and compliance drawbacks that make it not usable in some environments
Fixes #8466
**Checklist**
=> DynamoDB: Accept a KMS key for DynamoDB tables

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl
Setting `use_federated_token` in azure config crashes with current Loki version (2.7.3). Support for this parameter is in `main` but not released yet.
As `use_federated_token`'s default value will be `false`, let's not set it in config when it's `false`.
This way, the helm chart works on Azure with current Loki versions (if people don't set this parameter), and is compatible with future versions when this parameter will be supported.
Fixes #8450
N/A
**Checklist**
=> helm: azure config: don't set use_federated_token if false

operator/go.mod
assume-no-moving-gc makes the program exit if the current go version was not explicitly specified in it as safe. This version adds go 1.20 to the list of safe versions which fixes running loki when built with go 1.20.
Fixes #8399
split from #8495 as requested by @periklis
**Checklist**
=> operator: update assume-no-moving-gc to fix go 1.20

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
While https://github.com/grafana/loki/pull/8513 partially fixes the issue by conditionally removing the setting from the generated Loki config, the setting is still present in the values.yaml and therefore suggests that it may be set to `true`. However, since the setting is still unreleased, we need to completely remove it from the Helm config.
Fixes #8450
**Checklist**
=> Helm: Remove unrelease setting from Helm chart configuration file

CHANGELOG.md, cmd/logcli/main.go, pkg/logcli/query/query.go, pkg/logcli/query/query_test.go
So far logcli enforces a limit for fetching logs. However, sometimes users want to fetch all entries in a time range. This change allows to disable the limit by setting it to `0`. The entries are still fetched in batches. However, the batch loop is only stopped once no more results are returned.
**Checklist**
=> Fetch all entries with logcli if limit==0.

CHANGELOG.md, cmd/logcli/main.go, docs/sources/tools/logcli.md, pkg/logcli/output/default.go, pkg/logcli/output/jsonl.go, pkg/logcli/output/output.go, pkg/logcli/output/raw.go, pkg/logcli/query/part_file.go, pkg/logcli/query/query.go, pkg/logcli/query/query_test.go
Requesting a large range, a day, for example, takes a very long time to download. You can download in parallel by starting many processes, but this just made my job so much easier.
Continuation of  #7543
**Checklist**
=> logcli: Add parallel flags

tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/main.tf, tools/lambda-promtail/template.yaml, tools/lambda-promtail/variables.tf
If you want to add an extra label `env`, lambda-promtail would add the `__extra_` prefix, so that the resulting label is `__extra_env`. However, if you already have the `env` variable in other stream and you want to have consistent label naming, you would want to omit the prefix so the resulting label is `env`.
Fixes [#<issue number>](https://github.com/grafana/loki/issues/8471)
**Checklist**
=> lambda-promtail: Add option to omit extra labels prefix `__extra_`

pkg/logcli/query/query.go
The query jobs would block on `func (j *parallelJob) run` because the done channel was not buffered. That means the goroutine had to wait for the channel to be read.
Fixes deadlock introduced in https://github.com/grafana/loki/pull/8518.
**Checklist**
=> Fix logcli parallel download deadlock.

docs/sources/installation/helm/install-scalable/index.md, docs/sources/operations/caching.md
Memcached is our default options for caching. However, the options for Memcached are not well documented.
This change documents how Memcached should be configured and how Loki itself should be documented based on our ksonnet deployment.
**Checklist**
=> Document memcached configuration for caching.

docs/sources/installation/helm/reference.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
Uses helm values to generate htpasswd file based on tenants list.
i'm not quite sure about name conventions and such, so any help with this are welcome!
#8380
=> helm: make multi tenant easy: use tenant id from nginx $remote_user

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
- use go 1.20.1 in the build image to fix CVEs [CVE-2022-41722, CVE-2022-41723, CVE-2022-41724 and CVE-2022-41725](https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E)
- use alpine 3.16.4 in the build image
**Checklist**
=> Update build image to go 1 20 1 and alpine 3 16 4

integration/loki_micro_services_delete_test.go, pkg/logql/engine.go, pkg/logql/engine_test.go, pkg/logql/evaluator.go
fix vector() function produces wrong timestamp on instant query
Fixes #8240
**error snapshot**
error timestamp in grafana 7.x
error timestamp in grafana 9.x
**with this PR**
fix logql:
` vector(5)
`![image](https://user-images.githubusercontent.com/9583245/216041127-bbf5aa0a-6db0-4610-bf25-a6ebc96e5bf9.png)
with this PR
fix logql:
```
sum(count_over_time({namespace="traefik"}[5m]))
or
vector(5)
```
**Checklist**
=> [RFR] fix vector() function produces wrong timestamp on instant query

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
Golangci-lint [1.50.0 OOMs](https://github.com/golangci/golangci-lint/issues/3538#issuecomment-1414341372) when used with go 1.20.1. This also updates the build image.
**Checklist**
=> Use golangci-lint v1.51.2 in build image

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go
Fix our memchunk headblock filter to not skip entries that have timestamp=maxT.
=> Loki: Fix memchunk headblock filter

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go
Reverts grafana/loki#8591
This altered an internal API. We execute queries that are inclusive of start and exclusive of end: `[start,end)` and shouldn't break this. We use other ways to ensure `start==end` still works, such as by using the lookback-period to alter the range of queries: 
https://github.com/grafana/loki/blob/main/pkg/logql/evaluator.go#L179-L181
=> Revert "Loki: Fix memchunk headblock filter"

operator/CHANGELOG.md, operator/internal/handlers/internal/gateway/tenant_configsecret.go, operator/internal/handlers/internal/gateway/tenant_configsecret_test.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/manifests/gateway.go, operator/internal/manifests/gateway_test.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/var.go
This PR moves the `tenant.yml` file from the lokistack gateway configmap to a secret.
Fixes #8480
**Checklist**
=> operator: Store gateway tenant information in secret instead of configmap

production/ksonnet/loki/gateway.libsonnet
The `nginx.conf` config map server settings has a `proxy_set_header` line setting the X-Scope-OrgID using the gateway tenant ID. The Jsonnet string formatter is missing the `s` token.
Adds missing formatter token to the `nginx.conf` config map that's causing an `Unrecognized conversion type: ;` when trying to deploy.
Fixes issue from PR #[7624](https://github.com/grafana/loki/pull/7624)
**Checklist**
=> production: Add missing string formatter token to nginx.conf config map

production/helm/loki/CHANGELOG.md
Update the helm changelog CI comment to clarify that the pipeline is only used for new Loki releases.
Related to PR: https://github.com/grafana/loki/pull/8323
**Checklist**
=> Helm: update changelog CI comment

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
Co-authored-by: Christian Haudum <christian.haudum@gmail.com>
(cherry picked from commit 6dfae7c42d4a0ccb6790cddf5fe00c3d0e064385)
=> [release-2.7.x] Use golangci-lint v1.51.2 in build image (#8587)

docs/sources/operations/scalability.md
Starts to address #8631 
Removes link to outdated blog post that says "Loki is very much alpha software and should not be used in production environments."
Fixes broken link to Configuration file.
=> Fixing broken link and removing out of date blog post.

.drone/drone.jsonnet, .drone/drone.yml
[This drone step](https://drone.grafana.net/grafana/loki/20764/21/3) had to prepare a config for the `updater` to update loki helm chart with the latest image version automatically. However, it failed due to an error:
```
+ RELEASE_TAG=$(./tools/image-tag)
env: can't execute 'bash': No such file or directory
```
I forgot to install `bash` and `git` before running this script inside `alpine` container.
=> added missed binaries required to run `./tools/image-tag` script

cmd/logcli/main.go
Fixes regression reported here: https://github.com/grafana/loki/pull/8518#issuecomment-1446014229
@dannykopping can you please verify that it fixes the issue for you?
**Checklist**
=> [logcli] set default instead of error for parallel-max-workers validation

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/loki/config_wrapper_test.go, pkg/storage/bucket/s3/bucket_client.go, pkg/storage/bucket/s3/config.go, pkg/storage/chunk/client/aws/s3_storage_client.go, pkg/storage/chunk/client/aws/s3_storage_client_test.go
We want to automate the access account rotation. This is that easy at moment with service accounts in minio. Our currently life time of tokens is 3 months with minio sts works this fine.
**Checklist**
=> S3: add support for s3 session token

operator/CHANGELOG.md, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
The generated OpenShift bundle currently both references `v0.1.0` and `v0.0.1`. This PR fixes this inconsistency by removing the reference to `v0.0.1`.
**Checklist**
=> operator: Fix version inconsistency in generated OpenShift bundle

pkg/logql/log/filter.go, pkg/logql/log/filter_test.go
Interpolated variables from Grafana dashboards may result in the regex matcher `.+`. Filters with `+` are already being rewritten to be non greedy but there is a further optimization to make replace the regex altogether with a filter that just matchers `len(line) > 0`
=> Optimize .+ regex line filter

clients/pkg/promtail/wal/wal.go, pkg/ingester/wal.go, pkg/ingester/wal/encoding_test.go, pkg/ingester/wal/recordpool.go
Storing a slice in `sync.Pool` wastes 24 bytes every time it is returned to the heap; see https://staticcheck.io/docs/checks#SA6002
Storing a pointer to a slice allows the Pool to work without waste.
This came up in discussion about the benchmark in #8489 - with this change the memory usage comes down:
```
name                                                      old time/op    new time/op    delta
Writer_WriteEntries/1000_lines,_1_different_label_sets-4    7.37ms ±13%    7.45ms ± 9%     ~     (p=0.841 n=5+5)
name                                                      old alloc/op   new alloc/op   delta
Writer_WriteEntries/1000_lines,_1_different_label_sets-4     727kB ± 0%     679kB ± 0%   -6.63%  (p=0.008 n=5+5)
name …
```
=> WAL: store pointers in record pool

CHANGELOG.md, pkg/storage/chunk/fetcher/fetcher.go
We are looking at making some changes to the chunk caching strategy, and we need this data to know what size chunks we're typically requesting. For example, if the overwhelming majority of chunks are small we may decide to cache only small chunks to decrease the number of requests to the object store; we could fit more chunks in cache this way, which may have a positive performance impact.
N/A
I picked buckets that I thought would be useful, and even included a bucket that is above the recommended chunk target size since some users may be setting it that high.
**Checklist**
=> Querier/Ruler: add histogram to track fetched chunk size distribution

docs/sources/getting-started/_index.md
Previously example query was `evaluate-loki_flog_1` this was not the label used in flog. This results in query not returning any logs which beginners may be unsure of the cause of the issue. This might also be an issue if flog was running in the background and logs are not displayed.
Changed to `evaluate-loki-flog-1`.
Trivial fix to "Getting Started" documentation
**Checklist**
=> Loki Getting Started: Fix example query that was not working

docs/sources/best-practices/_index.md
We changed it from `1h` to `2h` as default long before. But look like we missed it on this best practice doc
Fixes #NA
**Checklist**
=> doc(best-practices): Update default value of `max_chunk_age`.

Makefile
This is the follow up to https://github.com/grafana/loki/pull/8111 and adds journald support for Promatil
ARM and ARM64 builds.
I've tested it locally with my Raspberry Pi and it works.
Fixes https://github.com/grafana/loki/issues/1459
=> Cross build Promtail for ARM with journald support.

pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client.go, pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_loader.go
Calls `ticker.Stop()` to avoid leaking ticker resources for `GenNumberLoader` and `deleteRequestsClient`.
=> Loki: Stop running tickers on deletes

pkg/logql/log/filter.go, pkg/logql/log/filter_test.go, pkg/logql/log/label_filter.go, pkg/logql/log/label_filter_test.go, pkg/logql/syntax/ast.go
We've done a ton of work to optimize regexes in line filters but nothing in label filters. To avoid duplicating the work or reworking all of our filter types, this PR creates a new label filter that has an optimized line filter. It uses that against the label value to determine if they match.
Note on Benchmarks: the input string for this is 1114195 bytes long. The `not` test tells us that our approach is quite a lot slower when the literal pattern isn't present in the input. The size of the input really emphasizes it. 
Benchmarks:
```
name                                        old time/op    new time/op        delta
LineLabelFilters/foo-8                        50.6ns ± 9%        14.3ns ± 1%        -71.67%  (p=0.000 n=10+8)
LineLabelFilters/not-8                        15.7ns ± 1% …
```
=> Use Line Filters in StringLabelFilter

pkg/loki/common/common.go, pkg/loki/loki.go, pkg/loki/modules.go
Follow up to #8689 that will allow to inject a different overrides implementation.
**Checklist**
=> Make Loki Overrides public.

operator/CHANGELOG.md, operator/internal/manifests/gateway.go, operator/internal/manifests/gateway_test.go
This PR fixes the problem of the `Gateway` not taking into account the `nodeSelector` and `tolerations` fields set by the `LokiStack`.
Fixes [LOG-3713](https://issues.redhat.com/browse/LOG-3713)
**Checklist**
=> operator: Fix gateway's nodeSelector and tolerations

clients/pkg/promtail/positions/positions.go, clients/pkg/promtail/positions/positions_test.go
From [NewTicker docs](https://pkg.go.dev/time#NewTicker):
`Stop the ticker to release associated resources.`
So not calling `Stop` for Promtail positions is probably leading to leakage at some level. Not sure what is the impact of this, though.
=> Promtail: Stop ticker to avoid leaking

tools/which-release.sh
I've often found myself needing to determine which release a particular PR appears in. This tool makes that easy, and it accepts the merge commit ref of the PR.
Example from https://github.com/grafana/loki/pull/7044, in which [a user is asking which version this feature appears in](https://github.com/grafana/loki/pull/7044#issuecomment-1455694087).
```bash
$ ./tools/which-release.sh 93a5a71                                 
Commit was found in the following releases:
release-2.7.x
```
=> Tools: add tool to determine which release (if any) a commit appears in

docs/sources/clients/promtail/scraping.md
Manual backport for #8688 to 2.7.x branch.
=> [Docs] Fixing broken link.

production/loki-mixin-compiled-ssd/dashboards/loki-reads-resources.json, production/loki-mixin-compiled/dashboards/loki-reads-resources.json, production/loki-mixin/dashboards/loki-reads-resources.libsonnet
Remove from loki-mixin the panel that shows the query_readiness metric. The metric was removed a while ago.
=> Loki-Mixin: Remove query-readiness panel

CHANGELOG.md, pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/compactor_test.go
When a delete request creates a new chunk from an existing chunk, we index it to the index store.
In TSDB, we [drop](https://github.com/grafana/loki/blob/944b488bd2506012d149fc363401f9b7d51af3e7/pkg/storage/stores/tsdb/head_manager.go#L235-L237) `__name__` label, which was being added to chunkrefs for historical reasons.
However, this was not done while indexing chunks from the deletion code, causing deletion to fail with the error [chunk insertion is only allowed on existing streams](https://github.com/grafana/loki/blob/619c2212f58c645661c7a004c084b839e91aec1b/pkg/storage/stores/tsdb/builder.go#L67).
This PR handles the issue by dropping the `__name__` label and adding relevant tests.
I will add an integration …
=> deletion: fix issue in processing delete requests with tsdb index

pkg/lokifrontend/frontend/v1/frontend.go, pkg/lokifrontend/frontend/v1/frontend_test.go, pkg/scheduler/queue/leafqueue.go, pkg/scheduler/queue/leafqueue_test.go, pkg/scheduler/queue/mapping.go, pkg/scheduler/queue/mapping_test.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/queue/tenant_queues.go, pkg/scheduler/queue/tenant_queues_test.go, pkg/scheduler/scheduler.go
This PR is the first step towards hierarchical queues within the query scheduler.
Hierarchical queues can be used to ensure query fairness across multiple actors within a single tenant, such as individual (human) users using the same tenant.
The change is described in the LID ["Query fairness across users within tenants"](https://grafana.com/docs/loki/next/lids/0003-queryfairnessinscheduler/).
* Extract metrics for `RequestQueue` into their own `metrics` field, so that they can extended and passed more easily in the future.
* Move mapping for tenant queues into its own data structure (ordered map) so its functionality can be reused. It also simplifies the code inside the `tenantQueues` struct.
* Add the `LeafQueue` struct that implements hierarchical queues. Sub-queues are dequeued in a …
=> Implement hierarchical queues for query scheduler

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
This PR reimplements the functionality  of `Unpack` using the `jsonparser` library rather than `jsoniter` 
Benchmarks:
```
name                                            old time/op    new time/op    delta
_Parser/unpack/no_labels_hints-8                   900ns ± 4%     309ns ± 3%  -65.62%  (p=0.000 n=10+10)
_Parser/unpack/labels_hints-8                     1.06µs ±12%    0.32µs ± 2%  -69.72%  (p=0.000 n=9+10)
_Parser/unpack-not_json_line/no_labels_hints-8    37.5ns ± 8%    10.6ns ± 3%  -71.70%  (p=0.000 n=9+9)
_Parser/unpack-not_json_line/labels_hints-8       39.6ns ±11%    10.3ns ± 2%  -74.00%  (p=0.000 n=10+9)
name                                            old alloc/op   new alloc/op   delta
_Parser/unpack/no_labels_hints-8                    536B ± 0%       80B ± 0%  -85.07% …
```
=> Reimplement Unpack in terms of jsonparser rather than jsoniter

production/loki-mixin-compiled-ssd/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-operational.json, production/loki-mixin/dashboards/dashboard-loki-operational.json
The metric `job_route` was changed to `cluster_job_route` in https://github.com/grafana/loki/pull/8247. This PR updates this metric in the operational dashboard.
**Checklist**
=> Use changed metric in operational dashboard

production/promtail-mixin/alerts.libsonnet
The PromtailFileMissing alert is not critical. This changes it to a warning.
**Checklist**
=> Change severity of PromtailFileMissing alert to warning

cmd/loki/Dockerfile.debug
On my M1 Pro, `make loki-debug-image` produces the following output:
```bash
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
This is because we run `delve` as the entrypoint for the debug image, and `delve` is being copied from `loki-build-image` which is exclusively built as `amd64` (we should make this a multi-arch image... created https://github.com/grafana/loki/issues/8759).
This change will work with whichever host OS is building the image and download `delve` using that architecture instead of relying on the `loki-build-image` version.
N/A
If you're on an `amd64` machine, please run `make loki-debug-image` and run the resultant image …
=> Modify debug loki build to work on any architecture, including ARM

clients/pkg/logentry/stages/stage.go, clients/pkg/promtail/client/manager_test.go, clients/pkg/promtail/config/config.go, clients/pkg/promtail/promtail.go, clients/pkg/promtail/utils/entries.go, clients/pkg/promtail/utils/entries_test.go, clients/pkg/promtail/wal/reader.go, clients/pkg/promtail/wal/writer_test.go, pkg/logql/log/ip.go, pkg/logql/log/label_filter.go, pkg/logql/log/parser_test.go, pkg/ruler/compat.go, pkg/ruler/grouploader.go, pkg/ruler/grouploader_test.go, pkg/ruler/memstore.go, pkg/ruler/memstore_test.go
We had a few outstanding linter issues, and running `make lint` fixes them all automatically.
=> Changes from linter

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/operations/storage/logs-deletion.md, docs/sources/upgrading/_index.md, pkg/loki/runtime_config_test.go, pkg/storage/stores/indexshipper/compactor/retention/expiration.go, pkg/storage/stores/indexshipper/compactor/retention/expiration_test.go, pkg/storage/stores/indexshipper/compactor/retention/retention_test.go, pkg/validation/limits.go
Issue #8359 exposed a very unfortunate inconsistency in a Loki config where the zero value did not disable a feature.
By convention in Loki the zero value for a config typically "disables" it.
This PR changes the retention_period to honor the zero value of `0` or `0s` to disable retention.
Fixes #8359
**Checklist**
=> Loki: Change the behavior of the 0 value for retention_period to disable retention.

pkg/logql/metrics.go
Typically `throughput` and `total_bytes` are the most common fields in the `metrics.go` log line which we look at for query performance. 
However, there are cases where query performance is better measured by `total_lines` and `lines_per_second` (e.g. when processing a lot of high volume but relatively short log lines) and having this information in metrics.go can be very helpful.
**Checklist**
=> Loki: add lines processed to metrics.go

CHANGELOG.md, docs/sources/configuration/_index.md, integration/client/client.go, integration/cluster/cluster.go, integration/cluster/ruler.go, integration/loki_rule_eval_test.go, integration/util/merger.go, pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/prometheus.go, pkg/querier/series/series_set.go, pkg/ruler/compat.go, pkg/ruler/compat_test.go, pkg/ruler/config.go, pkg/ruler/evaluator.go, pkg/ruler/evaluator_local.go, pkg/ruler/evaluator_remote.go, pkg/ruler/ruler.go, production/docker/config/loki.yaml, production/docker/docker-compose.yaml, production/docker/rules/docker/rules.yml
Adds the ability to evaluate recording & alerting rules against a given `query-frontend`, allowing these queries to be executed with all the parallelisation & optimisation that regular adhoc queries have. This is important because with `local` evaluation all queries are single-threaded, and rules that evaluate a large range/volume of data may timeout or OOM the `ruler` itself, leading to missed metrics or alerts.
When `remote` evaluation mode is enabled, the `ruler` effectively just becomes a gRPC client for the `query-frontend`, which will dramatically improve the reliability of the `ruler` and also drastically reduce its resource requirements.
This PR implements the feature discussed in …
=> Ruler: remote rule evaluation

operator/CHANGELOG.md, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
Expands the OLM skip range setting the openshift bundle to enable upgrades to the upcoming OpenShift Logging release.
**Checklist**
=> operator: Expand OLM skip range for OpenShift Logging 5.7 release

integration/cluster/cluster.go, integration/loki_micro_services_delete_test.go, integration/loki_micro_services_test.go, integration/loki_rule_eval_test.go, integration/loki_simple_scalable_test.go, integration/loki_single_binary_test.go, integration/multi_tenant_queries_test.go, integration/per_request_limits_test.go
Debugging integration tests can be difficult without Loki's logs being output.
Changing the call from `cluster.New()` to `cluster.New(level.WarnValue())` now allows the author the option to temporarily or permanently enable logging for their test, as well as configure a level filter to control the noise.
=> Integration Tests: allow loki logs to be optionally output in integration tests

pkg/logql/log/label_filter.go, pkg/logql/log/label_filter_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/parser_test.go
Label Filter optimizations omit `.*` label filters from the execution pipeline but intruduced a bug where those stages were also ommitted from calls to `String` on the expression. This results in unparsable queries and panics when queries are cloned via `query.String()` 
This PR makes `noopLabelFilter` embed matchers and inherit their `String` method just like the `StringLabelFilters` do
=> fix to-string for noop label filters

operator/CHANGELOG.md, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/openshift/opa_openshift.go
Use netobserv-specific matchers for network tenant.
This is just WIP at the moment, just opening a PR to discuss & validate the approach
cc @periklis 
Related PRs:
- https://github.com/observatorium/api/pull/440
- https://github.com/observatorium/opa-openshift/pull/15
To extend multi-tenancy in the loki-operator for openshift to new use cases, here for [NetObserv](https://github.com/netobserv/network-observability-operator). Note that it could probably be made more configurable for new/future use cases - not addressed in this PoC, but perhaps something to think about.
None
**Checklist**
=> operator: Allow multiple matchers for multi-tenancy with Network tenant

docs/sources/operations/storage/retention.md
This adds more detail around what can and cannot be used in a `selector` for retention. It was unclear whether arbitrary LogQL could be used or not; this makes it explicit.
Also added some additional matchers to the examples to show that it can be combinatorial.
=> Retention: add selector detail to docs

operator/CHANGELOG.md, operator/apis/loki/v1/v1.go, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/hack/lokirules_ocp.yaml, operator/internal/validation/openshift/alertingrule.go, operator/internal/validation/openshift/alertingrule_test.go, operator/internal/validation/openshift/common.go
Adds extended validation for the default [OpenShift Alerts Style Guide](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide), i.e.:
- Allowed severity label values: `critical`, `warning` and `info`
- Mandatory annotations: `summary` and `description`
**Checklist**
=> operator: Add alerting style guide validation

operator/CHANGELOG.md, operator/internal/manifests/internal/rules/marshal.go, operator/internal/manifests/internal/rules/marshal_test.go
The following PR adds a AlertingRule defaulting webhook is to populate the tenant ID to all rules to enable managing Alertmanager notifications per tenant.
**Checklist**
=> operator: Add alertingrule tenant id label for all rules

integration/loki_micro_services_test.go, pkg/loki/loki.go
The query frontend would not enforce the per-request query limits because the injected tripperware was wrapped *after* the frontend has been created. That is a bug. The order must be changed so that the `queryrange.LimitsMiddleware` runs *after* the `querylimits.limitsMiddleware`.
Fixes #8790
**Checklist**
=> Fix: Ensure query limits tripperware wraps frontend.

pkg/logql/evaluator.go, pkg/logql/log/parser.go, pkg/logql/log/parser_hints.go, pkg/logql/log/parser_test.go, pkg/logqlmodel/error.go
Currently metric expressions will fail if they contain the parser error label `__error__`. There are cases where you may want to count errors. For example,  `sum(count_over_time({foo="bar"} | json | __error__= "JSONParserErr" [$__interval]))` to see how many of your logs are unparsable JSON.
This pr uses `ParseHint` to determine whether the `__error__` label was requested in the query and, if it was, do math on it like any other query. Parse hints are only included in VectorAggregations so the label used to signal whether or not to keep errors is never seen by a user.
All other operations remain unaffected
=> Allow math on errors

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/role.yaml
Fixes role/PSP and role/SCC mapping in Helm chart.
Fixes #8652
**Checklist**
=> helm chart: fix role/PSP mapping

.github/workflows/helm-ci.yml, Makefile, production/helm/loki/Makefile, production/helm/loki/src/.yamllint.yaml, production/helm/loki/src/alerts.yaml
Adds a yaml linting step for the included rules in the loki helm chart. Only way I could think to enforce the comma line ending was to require qutoes around string, otherwise the linter cannot tell if the comma is just part of the string.
Fixes issue raised by @dannykopping in https://github.com/grafana/loki/pull/7860#issuecomment-1338784070.
**Note**:
First commit has an intentionally wrong `alerts.yaml`. Will fix before merging after making sure the CI works.
=> Add yaml linting step to helm ci

.github/workflows/operator-images.yaml
With #7308 the bundles directories moved into a separate location to support community and openshift bundles in parallel. However we are missing for considerable amount of time publishing the openshift bundle for dev usage.
**Checklist**
=> operator: Fix publishing operator bundle on quay.io

docs/sources/clients/promtail/configuration.md, docs/sources/clients/promtail/stages/regex.md
Fixes two word confusion in the docs:
* in multiple occasions `\` is referred to as slash instead of backslash 
* "most be convertible [...]" probably should be "must be convertible [...]"
=> Fix word confusions

tools/lambda-promtail/main.tf, tools/lambda-promtail/moves.tf, tools/lambda-promtail/variables.tf
I would like to offer this PR as a suggestion to improve the lambda-promtail terraform-module. I forked it to be able to deploy it more than once in an AWS account. I also applied terraform best-practices. I was hoping that perhaps these changes could be merged into upstream as well.
Unlike https://github.com/grafana/loki/pull/8549 , I unfortunately did not end up making a separate commit for each change. 
If you would like me to create one or more issue(s) to address the points below, I'd be happy to do that as well.
List of improvements:
1. Added `var.name` (defaults to lambda-promtail) so that this module can be deployed multiple times in the same AWS account. This allows us to define unique, non-conflicting names for:
* the Lambda function
* the …
=> refactor(lambda-promtail): apply terraform best practices

CHANGELOG.md, docs/sources/api/_index.md, pkg/ingester/ingester.go, pkg/loki/loki.go, pkg/loki/modules.go
Add a new `/ingester/prepare_shutdown` endpoint. This new endpoint configures the ingester to release resources on the next SIGTERM.
=> Loki: Add a `prepare-shutdown` endpoint

production/docker/config/loki.yaml, production/docker/docker-compose.yaml
The `backend` target is only present in v2.8.
N/A
I was using this docker setup to test https://github.com/grafana/loki/pull/8744 and I obviously left some things around from that. Sorry about that!
Thanks @wardbekker for noticing the issue
=> Removing backend target from SSD docker setup

pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/queryrange/limits.go, pkg/storage/stores/composite_store_entry.go, pkg/storage/stores/indexshipper/compactor/compactor_test.go, pkg/storage/stores/series/series_store_test.go, pkg/util/validation/validate.go
The old error messages would print only up to hours. E.g. `169h30s`. This change will print it as `7d1h30s`. See [model.Duration](https://github.com/prometheus/common/blob/66b493f42b757378fbad83e42b0ed441d425a17b/model/time.go#L259-L290) for details.
**Checklist**
=> Print duration in error messages with more readable.

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/loki/modules.go, pkg/ruler/base/ruler.go, pkg/ruler/evaluator_jitter.go, pkg/ruler/evaluator_jitter_test.go, pkg/validation/limits.go
This PR introduces a configurable random sleep before each rule evaluation to prevent contention on the query engine should multiple runs execute concurrently. It's quite likely that rules will be evaluated ~concurrently if they have the same interval.
N/A
In https://github.com/grafana/loki/pull/8744 I introduced the `ruler.Evaluator` interface, and this implementation is much simpler/elegant than what I had previously implemented in https://github.com/grafana/loki/pull/8307.
**Checklist**
=> Ruler: rule evaluation jitter

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
Fixes panic in unpack parser when processing empty lines
```
/src/enterprise-logs/vendor/github.com/grafana/loki/pkg/logql/log/parser.go:583
github.com/grafana/loki/pkg/logql/log.(*UnpackParser).unpack(...)
panic: runtime error: index out of range [0] with length 0
```
**Checklist**
=> unpack: fix panic on processing empty line

.drone/drone.jsonnet, .drone/drone.yml, Makefile, tools/fetch-tags
This invocation causes problems when make targets are executed in the build image container (`BUILD_IN_CONTAINER=true`), e.g. the `yacc` target, because git tries to fetch tags from `origin` using ssh, causing error message like these:
```
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```
This is because local ssh keys are not mounted into the build container.
In order not to break CI builds
(https://github.com/grafana/loki/pull/8232) we need to manually fetch the tags as the first step in release pipelines. This is added to the Drone configuration.
=> Remove ./tools/fetch-tags invocation from Makefile

CHANGELOG.md, production/ksonnet/loki/boltdb_shipper.libsonnet
Problem: in https://github.com/grafana/loki/pull/7804 the possibility to use gRPC for communicating with the compactor for query time filtering of data requested for deletion was added, however, the loki mixin still generates the compactor service without a gRPC port.
Solution: make the compactor service/deployment expose both an HTTP and gRPC port.
**Checklist**
=> ksonnet/loki: Add gRPC port to compactor mixin

operator/Dockerfile, operator/Dockerfile.cross
This PR updates the Dockerfile to use golang 1.20.1 images. Continuation of #8776.
**Checklist**
=> operator: Update Dockerfile to go1.20 images
