grafana/loki

- pkg/helpers/config.go
Signed-off-by: yeya24 <ben.ye@daocloud.io>
> fix a typo Eeror -> Error

- README.md
For those of us who don't know what Prometheus is
> Link to Prometheus in the README

- README.md
Bit less visually noisy, and clearer.
> Use Shields.io style badge for Circle CI

- README.md
Adds a link to Slack and a section about the search syntax (with a link to the logcli docs)
Signed-off-by: Daniel Lee <dan.limerick@gmail.com>
> readme: adds section about search

- docs/logcli.md
update logcli help info.
Signed-off-by: Xiang Dai <xiang.dai@iluvatar.ai>
> update logcli doc

- README.md
New users may think loki need a dashboard like prometheus, but no indeed.
So add a entrance statement about it.
Fix #95 
> state loki entrance

- README.md
> Add a section on the README for getting help.

- pkg/querier/store.go
> Don't forget to apply regexp filters to chunk entries.

- Makefile
> Remove go build -i

- ksonnet/README.md
Fix "Expected a comma before next field."
> fix deploy issue

- production/ksonnet/loki/jsonnetfile.json
Now consul does not has `consul` version.
> update consul version

- README.md
- docs/api.md
Helps #143 - explains more about how we do multitenancy.
> Add link to protobuf and client library to API docs.

- README.md
> Clarify what we mean by 'like Prometheus, but for logs'.

- README.md
either https://www.youtube.com/watch?v=U7C5SpRtK74&list=PLj6h78yzYM2PZf9eA7bhWnIh_mK1vyOfU&index=346 or https://www.youtube.com/watch?v=U7C5SpRtK74
> updated link to kccna18 video

- production/ksonnet/loki/config.libsonnet
- production/ksonnet/loki/distributor.libsonnet
- production/ksonnet/loki/ingester.libsonnet
- production/ksonnet/loki/querier.libsonnet
To trigger re-deployments when config changes.
> Add annotation with hash of config, 

- production/README.md
Fixes: https://github.com/grafana/loki/issues/175
> Add cloning instructions to be inside GOPATH

- README.md
After discovering how to build and test my forked loki's repo, I've come with the idea of improving documentation for people wanting to contribute with the project like me. Since I didn't find any README.md telling me this, I think it should be great to document how the external contributions work :).
Feel free to suggest anything I could add to make the docs complete (I know it's still short).
> adding #contributions header to global README.md

- README.md
> add comment for go get

- production/README.md
> Changes from #85

- production/ksonnet/README.md
- production/ksonnet/promtail/promtail.libsonnet
- tools/promtail.sh
Ensure docker data root is correct, if not, promtail can not get any meaningful data.
> tools/promtail.sh: add DATAROOT option

- pkg/promtail/position.go
- pkg/promtail/target.go
- pkg/promtail/target_test.go
Adding some channels to watch for proper closing of goroutines
Adding some unit tests around target.go
> Unit tests for Promtail

- pkg/chunkenc/interface.go
- pkg/distributor/distributor.go
- pkg/ingester/instance.go
- pkg/ingester/stream.go
- pkg/loki/loki.go
- pkg/loki/modules.go
- pkg/util/conv.go
Also, make ErrOutOfOrder a HTTP 4xx error and continue to append even when we encourter an out of order entry.
> Validate labels in the distributor.

- production/helm/templates/loki/deployment.yaml
- production/helm/templates/loki/podsecuritypolicy.yaml
- production/helm/templates/loki/pvc.yaml
- production/helm/values.yaml
Add persistent volume claim! I also changed the default location of data, open to any changes!
> Add persistent volume and move data to data

- pkg/distributor/http.go
Should now return 4xx on OOO entries.
> Correctly propagate errors in the distributor

- README.md
> Add FOSDEM video.

- pkg/ingester/flush.go
> Remove stream from index when its remove from memory.

- production/ksonnet/loki/config.libsonnet
> Put chunk_idle_period in the right place in the ksonnet.

- pkg/ingester/flush.go
I broke this when I updated the vendored Cortex, which includes https://github.com/cortexproject/cortex/commit/ac653065193fc9f9b91d0a3da38886cd20b816e5#diff-42196489d8c6339357699ab3656cb2e1R315.
Fixes #279
> Explicty encode the chunk.

- pkg/chunkenc/gzip.go
- pkg/chunkenc/gzip_test.go
- pkg/iter/iterator.go
- pkg/iter/iterator_test.go
> Support duplicate timestamps for entries

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/ingester_test.go
Caught one bug, where we weren't returning the validation error if _all_ the labels were invalid.
> Basic distributor tests.

- pkg/iter/iterator.go
- pkg/iter/iterator_test.go
> set currLabels when currEntry is set.

- docs/grafana-provisioning.md
- docs/usage.md
> Add k8s part in docs

- production/helm/templates/promtail/configmap.yaml
- production/ksonnet/promtail/promtail.libsonnet
- tools/promtail.sh
> dont add pods twice if they have app and name labels

- production/helm/values.yaml
- Loki and promtail are under heavy development, always pulling makes sure bug fixes are shipped
> Change image pull default policy to Always

- README.md
- docs/operations.md
- fluentd/fluent-plugin-loki/README.md
- fluentd/fluent-plugin-loki/docker/conf/systemd.conf
- fluentd/fluent-plugin-loki/lib/fluent/plugin/out_loki.rb
- pkg/parser/labels.go
- production/ksonnet/promtail/promtail.libsonnet
> Delete all duplicate empty blanks

- pkg/promtail/targets/filetarget.go
Signed-off-by: kun <oiooj@qq.com>
> Fix start tailing panic

- docs/troubleshooting.md
I found deleting the positions file helpful when trying loki locally.
> Clarify promtail troubleshooting around positions

- README.md
Already happened, safe to remove?
> Remove GrafanaCon from README

- pkg/promtail/api/entry_parser_test.go
just to augment the test cases that came in with the CRI format I added a few tests for the existing docker format
> adding a few more test cases for entry parsing docker format

- README.md
> Add link to logcli doc

- fluentd/fluent-plugin-loki/lib/fluent/plugin/out_loki.rb
> Fix payload_builder

- production/helm/templates/promtail/daemonset.yaml
- production/helm/values.yaml
- production/ksonnet/README.md
- production/ksonnet/promtail/promtail.libsonnet
- tools/promtail.sh
We had a use case in which we were running Docker in a location which had more storage. I'm adding the ability to modify the docker location.
> Made the docker root configurable. Default is '/var/lib/docker'

- production/helm/templates/loki/configmap.yaml
- production/helm/templates/loki/deployment.yaml
- production/helm/templates/loki/podsecuritypolicy.yaml
- production/helm/templates/loki/pvc.yaml
- production/helm/templates/loki/role.yaml
- production/helm/templates/loki/rolebinding.yaml
- production/helm/templates/loki/service.yaml
- production/helm/templates/loki/serviceaccount.yaml
- production/helm/templates/promtail/clusterrole.yaml
- production/helm/templates/promtail/clusterrolebinding.yaml
- production/helm/templates/promtail/configmap.yaml
- production/helm/templates/promtail/daemonset.yaml
- production/helm/templates/promtail/podsecuritypolicy.yaml
- production/helm/templates/promtail/role.yaml
- production/helm/templates/promtail/rolebinding.yaml
- production/helm/values.yaml
> Support only deploy loki or promtail and fix helm lint issue

- .circleci/config.yml
- Makefile
- production/docker-compose.yaml
- production/helm/grafana.yaml
- production/helm/values.yaml
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/promtail.libsonnet
- tools/promtail.sh
> Tag with lastest

- production/helm/templates/promtail/configmap.yaml
- production/helm/values.yaml
- production/ksonnet/promtail/config.libsonnet
> Add backoff_config in helm

- README.md
> Add Julien's blog post to the README.

- production/helm/values.yaml
After this, all client configs can be customized in helm.
> add miss promtail client config option

- production/helm/templates/promtail/daemonset.yaml
- production/helm/values.yaml
Check process exists or not when pod start,
> Add health check

- pkg/promtail/targets/tailer.go
- production/loki-mixin/alerts.libsonnet
@tomwilkie double check I added that new alert correctly, I added more labels to the group by clause so I could display them in the message, I think this should still work.
> Fixing a bug, tweaking and adding alerts

- production/helm/loki/templates/loki/serviceaccount.yaml
- production/helm/loki/values.yaml
> Fix serviceaccount error

- docs/operations.md
> Add dashboard example

- cmd/logcli/client.go
- cmd/logcli/main.go
Fix #456 
- move error log to stderr
- move debug log to stderr
> Log error to stderr

- docs/troubleshooting.md
> Add help info for users uses high k8s version

- docs/operations.md
> Add link to chunk format doc

- production/helm/loki-stack/Chart.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
Not sure how this got missed
cc @davkal
> Fix missing volume after refactor

- production/helm/loki/templates/service.yaml
- production/helm/loki/values.yaml
I was added to service  to allow work as  NodePort
> Added option that loki service run as nodeport

- docs/promtail-examples.md
rewrite exist example of using promtail, and add more examples with descriptions
> create and update promtail-examples.md

- production/helm/README.md
> Update helm docs

- docs/api.md
Added in Examples section, example on Python 3
> Update api documentation

- Gopkg.lock
- Gopkg.toml
- pkg/chunkenc/lazy_chunk.go
- pkg/ingester/instance.go
- pkg/iter/iterator.go
- pkg/querier/store.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/aws/aws_autoscaling.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/composite_store.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/encoding/bigchunk.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/fixtures.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/schema.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/schema_config.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/testutils/testutils.go
- vendor/github.com/cortexproject/cortex/pkg/ingester/client/client.go
- vendor/github.com/cortexproject/cortex/pkg/ingester/index/index.go
- vendor/github.com/cortexproject/cortex/pkg/ring/lifecycler.go
Wanted to test this first before I pull in all my lazy loading logic.
> Lazy load chunks

- pkg/ingester/flush.go
Add some useful stats around chunk sizes and ages.
> Add stats about chunk sizes and ages

- pkg/ingester/flush.go
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
> Fix linting

- production/helm/loki/Chart.yaml
- production/helm/loki/templates/deployment.yaml
- production/helm/loki/values.yaml
> Enable tracing loki in helm chart

- production/helm/loki-stack/Chart.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
Support costomize target config.
> Add target config

- pkg/chunkenc/gzip.go
- pkg/ingester/ingester.go
- pkg/ingester/instance.go
- pkg/ingester/stream.go
> support config chunk size

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/ksonnet/loki/config.libsonnet
> Add option

- pkg/ingester/ingester.go
> Fix #531 chunk_block_size not found

- pkg/promtail/positions/positions.go
> don't delete elements from a map while iterating over it

- pkg/promtail/positions/positions.go
#543 didn't get this quite right, this should do it, thanks @steven-sheehy
> fix positions cleanup

- pkg/ingester/flush.go
I have a suspicion that with ~1MB of data, we are taking too long to encode chunks.
> Add a histogram for chunk encoding time

- pkg/promtail/promtail_test.go
- pkg/promtail/targets/filetarget.go
> Fix flaky TestPromtail

- production/helm/README.md
Add help info about how to customize config with helm deployment.
> Add custom help info

- production/ksonnet/loki/config.libsonnet
- production/ksonnet/loki/memcached.libsonnet
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
> Fix minor issues with memcached config in ksonnet

- production/ksonnet/loki/images.libsonnet
Required for running table manager with retention
> Update table manager image in production/ksonnet

- .github/pull_request_template.md
Tweaked from Grafana's PR template. Feel free to change it further.
> Docs: Add a pull request template

- cmd/logcli/tail.go
- pkg/querier/http.go
Changed it to dict with single key called "streams" and value set to list of logproto.Stream
Sample response with new changes:
`{"streams":[{"labels":"{foo1=\"bar\", foo2=\"bar\", foo3=\"bar3\"}","entries":[{"ts":"2019-05-16T10:10:18.924258Z","line":"sample"}]}]}`
> Live-tailing: Change tail response for backward compatibilty with future changes

- pkg/ingester/instance.go
Ingesters `lookupStreams` were considering matchers with empty matches (filters) when doing a lookup, so stream without labels for that given matches where never returned.
see: https://github.com/grafana/loki/blob/master/vendor/github.com/cortexproject/cortex/pkg/util/matchers.go#L8
Will probably fixes https://github.com/grafana/loki/issues/592
> fixes ingester querier filters

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/cortexproject/cortex/pkg/chunk/aws/dynamodb_storage_client.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/fixtures.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/local/fixtures.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/schema_config.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/storage_client.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/table_manager.go
- vendor/github.com/cortexproject/cortex/pkg/ingester/client/pool.go
- vendor/github.com/cortexproject/cortex/pkg/util/validation/limits.go
Use upstream cortex now that lazy loading support is upstreamed.
> Get rid of the cortex fork

- cmd/loki/loki-local-config.yaml
- production/helm/loki/values.yaml
- production/ksonnet/loki/config.libsonnet
Psst, the date is the first commit date for loki ;)
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
> Fix local config: Use DayTime

- docs/operations.md
Small update to fix the link to the Cortex project.
> fix: Update operations.md

- production/helm/loki-stack/Chart.yaml
Should have been done in #608 but that has already been merged
> Also bumping loki-stack version

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/templates/NOTES.txt
- production/helm/promtail/Chart.yaml
- production/helm/promtail/templates/NOTES.txt
Giving the user correct testing output when not running chart in default namespace.
> Helm: Added namespace to helm install notes

- docs/operations.md
Would be helpful for users to know about it and how they can configure it.
**Checklist**
> Update operations doc about logs retention

- cmd/promtail/promtail-docker-config.yaml
- cmd/promtail/promtail-local-config.yaml
- docs/logentry/processing-log-lines.md
- docs/promtail-examples.md
- docs/promtail.md
- pkg/logentry/stages/metrics_test.go
- tools/promtail.sh
- tools/scrape_config.sh
also had to remove helm entry in scrape_config.sh because there doesn't seem to be anyway to make it work with new pipeline config
I'm submitting this as another PR because I totally jacked up the rebase in #584 and it seemed a lot easier to cherry pick commits into a new PR.  Closes #584
> updating docs for new pipeline config.

- .circleci/config.yml
- Makefile
- production/helm/loki/values.yaml
- production/helm/promtail/values.yaml
- tools/increment_version.sh
- tools/release_prepare.sh
This is really just to get things rolling, it needs some work.
Most of the work is done by a script to setup the right version number in the helm/ksonnet configs
When a tag is pushed circleci should handle pushing the properly tagged docker images
> release process

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
> release loki v0.1.0

- .circleci/config.yml
> release stage is broken, removing for now

- pkg/querier/store.go
This wasn't working before as the chunk wasn't fetched, so metric was always empty.
> Remove label __name__ from store querier

- pkg/promtail/server/ui/templates/_base.html
This page return 404.
Just disable it for now.
> Remove 404 link

- .circleci/config.yml
was previously trying to run in a container.
Also added pkg/promtail/server/ui/assets_vfsdata.go as a previous PR didn't regenerate it.
see https://github.com/grafana/loki/pull/637
> fix docker plugin ci

- Makefile
Hopefully addresses helm publish [failures](https://circleci.com/gh/grafana/loki/6327?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) 🤞 
**Checklist**
> Fix publish-helm failure

- cmd/docker-driver/loki.go
> fix missing logger in client

- production/loki-mixin/dashboards.libsonnet
@jtlisi I deployed this and appears to be correct with the new gateway
> updating the loki dashboards to use the metrics from the new gateway

- Gopkg.lock
- docs/operations.md
- vendor/github.com/cortexproject/cortex/pkg/chunk/aws/dynamodb_storage_client.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/aws/s3_storage_client.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/encoding/bigchunk.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/schema.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/storage/caching_index_client.pb.go
- vendor/github.com/cortexproject/cortex/pkg/ingester/client/cortex.pb.go
- vendor/github.com/cortexproject/cortex/pkg/ring/model.go
- vendor/github.com/cortexproject/cortex/pkg/ring/ring.go
- vendor/github.com/cortexproject/cortex/pkg/ring/ring.pb.go
Fixes https://github.com/grafana/loki/issues/699
And add doc for this new-added config.
> sync with Cortex for s3 path style url

- production/helm/loki-stack/Chart.yaml
- production/helm/loki-stack/requirements.yaml
> update grafana to fix dashboard provider

- production/helm/promtail/values.yaml
Just a simple typo.
None.
Nope.
**Checklist**
No need for tests or documentation update.
> Typo on values.yaml

- pkg/logentry/stages/util.go
- pkg/logentry/stages/util_test.go
checkin comment explains it best
> remove insignificant zeros from float to string conversion

- docs/usage.md
Documented which regex dialect the filter expression speaks.
Fixes https://github.com/grafana/loki/issues/741
**Checklist**
> Added a note about regex accepted syntax in the filter expression

- cmd/logcli/client.go
> fix path escape

- cmd/docker-driver/README.md
> adjust old instructions for troubleshooting docker daemon

- production/README.md
- document centos dep
- add `-y` option
optimize #791
> Document centos dep

- cmd/promtail/Dockerfile
- cmd/promtail/Dockerfile.debug
- docs/logentry/processing-log-lines.md
- pkg/logentry/stages/extensions.go
- pkg/logentry/stages/timestamp.go
- pkg/logentry/stages/timestamp_test.go
- pkg/logentry/stages/util.go
- pkg/logentry/stages/util_test.go
> adding ability to supply timezone to timestamp pipeline stage

- README.md
Fix broken link in README.md for Callum's talk
> Fix broken link in readme file

- fluentd/fluent-plugin-grafana-loki/docker/Gemfile
- fluentd/fluent-plugin-grafana-loki/fluent-plugin-grafana-loki.gemspec
Update gem version and fix a lint issue.
> fluentd: fix dependencies order and bump version

- cmd/docker-driver/driver.go
> fix panic in docker driver for newer docker version (18.09.7+)

- cmd/logcli/main.go
- docs/logcli.md
Updated help text for a flag used for live tailing and logcli usage in doc.
> Documentation: Update logcli usage in docs and improve help text

- docs/logentry/processing-log-lines.md
>  Missing escape character on regex in YAML

- .circleci/config.yml
- Makefile
- pkg/logproto/logproto.pb.go
- tools/image-tag
Accidentally removed, re-added
> chore: deploy

- pkg/iter/iterator.go
- pkg/iter/iterator_test.go
Fixed prefetch in `HeapIterator` when `Len()` or `Peek()` are called as first methods.
Fixes #833
- I've renamed `prenext` into `prefetch` to hopefully make it more clear to understand (any feedback is welcome)
- Please take also a look at the code comments I've added, to hopefully make it more clear to a first time (code) reader
**Checklist**
> fix(loki): prefetch HeapIterator when Len() or Peek() are called as first methods

- pkg/distributor/distributor.go
- pkg/loki/modules.go
Adds Readiness probe for Distributor
Fixes #504
> Readiness: Readiness probe for Distributor

- production/ksonnet/loki/distributor.libsonnet
@adityacs If you can also include that for your querier change PR. Otherwise I'll do it.
> Add readiness probe to distributor deployment.

- docs/governance/README.md
As discussed this is our governance documentation. This gives a path for the community to become team member.
> Add governance documentation

- pkg/distributor/distributor.go
- pkg/loki/modules.go
- pkg/querier/querier.go
- production/ksonnet/loki/querier.libsonnet
**What this PR does / why we need it ?**:
Adds readiness probe for querier. 
Fixes #504
> Readiness probe for querier

- pkg/chunkenc/gzip_test.go
The test `TestGZIPCompression` is currently skipped because of a missing fixture file. I've checked the test and the logic it tests looks already covered by other tests, so I'm proposing to remove the test to cleanup the test file and avoid misunderstandings.
Fixes #829
**Checklist**
> loki: removed unused TestGZIPCompression

- CHANGELOG.md
> Updating changelog for v0.3.0

- tools/bigtable-backup/bigtable-backup.py
`bigtable_backup_job_backups_created` was incremented at the wrong place setting incorrect value for it. Moved it to appropriate place.
> fix incrementing of bigtable_backup_job_backups_created metric

- pkg/querier/tail.go
The Tailer's `querierTailClients` was accessed in several goroutines without being protected by a Mutex in each instance; this PR changes the Mutex to a RWMutex and protects each access.
> pkg/querier: fix concurrent access to querier tail clients

- .github/stale.yml
See [probot-stale's](https://github.com/probot/stale) repository for full list of configuration options.
> Add probot-stale configuration to close stale issues.

- cmd/docker-driver/loki.go
> Add stream label to docker driver

- Makefile
Simplifies tagging by removing conditionals and always publishing as `latest`
and for images also `master` on all builds (including tags).
Also fixes the tagging of the docker-driver, latest tag is back
> chore(packaging): simplify tagging

- .drone/drone.jsonnet
- .drone/drone.yml
this is the same as what the circle job we are replacing did
> use the loki-build-image for calling circle

- README.md
Fixed two broken links
**What this PR does / why we need it**: Because broken links are bad UX
Fixes issue #1000
**Special notes for your reviewer**: Minor edit, just fixing a couple broken links
**Checklist**
> Loki: Update README.md

- cmd/docker-driver/README.md
- pkg/logcli/query/utils.go
This PR fixes a broken link for documentation and fixes a typo
There is no issue for this PR
**Checklist**
> Fix a link to correct doc and fix a typo

- production/ksonnet/loki-canary/config.libsonnet
- tools/release_prepare.sh
> updating the image version for loki-canary and adding the version increment to the release_prepare script

- pkg/querier/tail.go
This PR fixes typo in error messages
There is no issue for this PR
**Checklist**
> fix typo in error messages

- production/README.md
When I reading documentation, I noticed one of internal link has broken.
(Nothing)
(Nothing)
**Checklist**
> Loki: Fix README link

- docs/operations/authentication.md
> Fix spelling of HTTP header

- docs/README.md
> Add fluent-bit missing link in the main documentation page.

- tools/promtail.sh
Fixes the promtail.sh push path to match current prod
Signed-off-by: Joe Elliott <number101010@gmail.com>
> Updated push path to current prod

- README.md
> FixedTypo.Update README.md

- production/helm/fluent-bit/Chart.yaml
- production/helm/fluent-bit/templates/configmap.yaml
- production/helm/fluent-bit/values.yaml
- production/helm/loki-stack/Chart.yaml
> rollback fluent-bit push path until we release 0.4

- CHANGELOG.md
- docs/clients/promtail/installation.md
- docs/getting-started/logcli.md
- docs/installation/local.md
> Updating Changelog for 0.4.0

- Makefile
> reducing binary parallelism to prevent circle from OOMing

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
> update version numbers to new release

- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/client/default_retryer.go
- vendor/github.com/aws/aws-sdk-go/aws/csm/metric_chan.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/modules.txt
Update the AWS Go SDK to version v1.23.13
Fixes #1019
I run the tests and they pass, I'm not sure if any new test is needed
**Checklist**
> AWS EKS: Update the AWS Go SDK to version v1.23.13

- go.mod
- go.sum
- pkg/promtail/promtail_test.go
- vendor/github.com/weaveworks/common/aws/config.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/modules.txt
**What this PR does / why we need it**: Updates dependencies to use the current upstream version of [`weaveworks/comomon`](https://github.com/weaveworks/common).
**Which issue(s) this PR fixes**: Fixes #945.
**Special notes for your reviewer**: None.
**Checklist**
> Update dependencies to use weaveworks/common upstream

- docs/installation/helm.md
> Fixed whitespaces in example ingress yaml

- production/helm/loki-stack/Chart.yaml
- production/helm/loki-stack/requirements.yaml
`helm install` fails in k8s 1.16.
Fixes #1080
**Checklist**
> helm: loki-stack supports k8s 1.16

- docs/installation/local.md
Add documentation about packages RPMs for loki and promtail
adresses partially #52 
This PR add a minimal doc reference for RPM pkgs which we maintain at @openSUSE
For any suggestion feel free to ping me :rocket: :apple:
> DOC: add minimal information about RPMs pkgs

- docs/clients/promtail/installation.md
The download link for `promtail` is broken in its current state.
> docs: Fix promtail releases download link

- docs/logql.md
As far as I understand the example query for LogQL is missing a closing `)` which is a little confusing for new users.
If I am not mistaken then those kind of queries are only possible against the Prometheus-API-endpoint of Loki (`/loki`). Should we make this more clear in the docs as well?
If you confirm this, I can add it to the PR.
**Checklist**
> Docs: Add missing ) in LogQL example

- pkg/util/validation/validate.go
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Expose discarded bytes metric

- docs/clients/promtail/pipelines.md
add description about tenant stage
**Checklist**
> add description about tenant stage

- fluentd/fluent-plugin-grafana-loki/lib/fluent/plugin/out_loki.rb
> Wrong api endpoint in fluent-plugin-grafana-loki

- pkg/ingester/flush.go
- pkg/ingester/instance.go
- pkg/ingester/transfer.go
- pkg/util/validation/validate.go
Code linting to make things consistent.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Metrics: use Namespace everywhere when declaring metrics

- docs/configuration/README.md
The duration format stated on the docs was invalid!
Fixes #1170
Signed-off-by: Daniel González Lopes <danielgonzalezlopes@gmail.com>
> doc(configuration): Fix duration format.

- docs/clients/promtail/configuration.md
> fix broken link

- CHANGELOG.md
- docs/clients/promtail/installation.md
- docs/operations/loki-canary.md
> Update changelog for 1.1.0 release

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
> Updating version numbers for 1.1.0 release

- CHANGELOG.md
- docs/clients/promtail/installation.md
- docs/operations/loki-canary.md
> Update changelog for 1.2.0 release

- pkg/ingester/stream.go
> forgot to register the new metric for counting blocks per chunk

- docs/configuration/README.md
Adds docs to use redis for caching
**Checklist**
> Docs: Add configuration docs for redis

- docs/community/governance.md
As per our governance doc, Joe has been approved as official maintainer.
Welcome !
> Add Joe as member of the team.

- CHANGELOG.md
- cmd/docker-driver/Dockerfile
- cmd/fluent-bit/README.md
- cmd/loki-canary/Dockerfile.cross
- cmd/loki/Dockerfile.cross
- cmd/loki/Dockerfile.debug
- cmd/promtail/Dockerfile.cross
- cmd/promtail/Dockerfile.debug
- docs/architecture.md
- docs/clients/promtail/stages/cri.md
- docs/clients/promtail/stages/metrics.md
- docs/configuration/README.md
- production/ksonnet/loki/config.libsonnet
Fix all misspell.
I would like to a tool for this if possible.
> fix all misspell

- README.md
Spelling fix in main README
**Checklist**
> <Docs>: README spelling fix

- pkg/chunkenc/decompression/context.go
- pkg/chunkenc/dumb_chunk.go
- pkg/chunkenc/interface.go
- pkg/chunkenc/lazy_chunk.go
- pkg/chunkenc/memchunk.go
- pkg/chunkenc/memchunk_test.go
- pkg/ingester/chunk_test.go
- pkg/ingester/flush_test.go
- pkg/ingester/instance.go
- pkg/ingester/stream.go
- pkg/ingester/stream_test.go
- pkg/ingester/transfer_test.go
- pkg/logql/engine.go
- pkg/storage/iterator.go
This adds a collection of decompression statistics in the logql engine.
/cc @Dieterbe I think this could be the be propagated from there to the API.
> Add decompression tracing instrumentation.

- docs/operations/storage/README.md
**What this PR does**: Add missing requirement for IAM
Fixes #1443
**Checklist**
> <documentation>: Update IAM requirement

- production/README.md
Fix broken link to promtail docs
> docs: fix broken promtail link

- pkg/querier/queryrange/codec.go
- pkg/querier/queryrange/codec_test.go
Also align stream labels alphabetical order with querier.
> Fixes response json encoding and add regression tests.

- pkg/storage/iterator.go
I would like to circle back around and cleanup this code and maybe add a test, however first need to fix the panic.
> Fix a panic in chunk prefetch

- docs/installation/helm.md
Helm chart url added in helm.md and it will close #1377 
Fixes #1377 
**Checklist**
> Helm chart url added in helm.md

- docs/api.md
> Fixes bad json in Loki API documentation.

- pkg/chunkenc/memchunk.go
- pkg/logql/engine.go
- pkg/storage/store.go
This PR addresses a few critical m's that were being incorrectly treated as n's.
> Critical n => m conversions

- docs/clients/promtail/stages/output.md
Fix example.
**What this PR does / why we need it**: Fix a doc example that I think is wrong.
**Which issue(s) this PR fixes**: none raised
**Special notes for your reviewer**: 
**Checklist**
> Promtail Docs: Update output.md

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
- tools/release_prepare.sh
> update distributions with latest release artifacts

- docs/clients/promtail/configuration.md
> Updated configuration.md

- pkg/chunkenc/memchunk.go
- pkg/logql/stats/context.go
- pkg/logql/stats/context_test.go
- pkg/logql/stats/grpc.go
- pkg/logql/stats/grpc_test.go
I was a little slow responding to the initial PR, here are my suggestions for some easier to undrestand names
> Change new stats names

- codecov.yml
> Ignore markdown files in codecoverage

- .drone/drone.jsonnet
- .drone/drone.yml
:crossed_fingers: for fixing the Drone problems
> ci: pin plugins/manifest image tag

- docs/operations/loki-canary.md
In `docs/operations/loki-canary.md`, indent miss of DaemonSet manifest, fix it.
**Checklist**
> loki-canary: fix indent of DaemonSet manifest written in .md file

- docs/community/governance.md
adds usernames & links for maintainer list.
> maintainer links & usernames

- cmd/fluent-bit/loki.go
- cmd/fluent-bit/loki_test.go
Fluent-bit: Fix panic error when AutoKubernetesLabels is true
Fixes #1524 
**Checklist**
> Fluent-bit: Fix panic error when AutoKubernetesLabels is true

- production/ksonnet/loki/config.libsonnet
> Allow to configure global limits via the jsonnet deployment.

- production/ksonnet/loki/query-frontend.libsonnet
I forgot to update it to use common args.
Mistakes were made.
> Fixes frontend args in libsonnet.

- .drone/drone.jsonnet
- .drone/drone.yml
> build: fix deploy on tagged build

- Makefile
> add darwin and freebsd binaries to release output

- production/promtail-mixin/dashboards.libsonnet
> promtail-mixin: Allow choosing promtail name

- tools/deploy.sh
> build: Update the CD deploy task name

- docs/architecture.md
Fixes #1778
Signed-off-by: Brian Candler <b.candler@pobox.com>
> Docs: Recommended schema is now v11

- docs/configuration/README.md
Updates docs with new configuration parameters for redis.
**Checklist**
> Docs: Update configuration docs for redis

- docs/architecture.md
- docs/configuration/README.md
- docs/overview/README.md
> docs: clean up schema recommendations

- fluentd/fluent-plugin-grafana-loki/fluent-plugin-grafana-loki.gemspec
Bump gem version on the fluentD plugin
> bump gem version

- README.md
> docs: tweak the doc section of the readme a little

- docs/clients/docker-driver/README.md
Keep plugin install command example in one line. Easier to select all and copy.
> Docs: Keep plugin install command example in one line

- docs/clients/promtail/configuration.md
we recently changed these defaults but forgot to update the docs
> docs: update promtail docs for backoff

- CHANGELOG.md
> clear out some changelog entries to fix a merge conflict from the release branch

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
> updating helm and ksonnet for 1.4.0 release

- docs/logql.md
> Add precision about the range notation for LogQL.

- README.md
- production/helm/fluent-bit/Chart.yaml
- production/helm/fluent-bit/values.yaml
- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
updating Fluent Bit to correct image
> updating helm and ksonnet to 1.4.1

- .drone/drone.jsonnet
- .drone/drone.yml
> build: push images for `k` branches

- docs/installation/docker.md
**What this PR does / why we need it**: Fixes the commands for Windows machines. Windows doesn't recognize `$PWD` or `-config`. You need to enter the path and use `--config`.
**Special notes for your reviewer**: Please make sure the statements are true for Linux. I can verify they are true for Windows.
**Checklist**
> Docs: Update docker.md

- cmd/loki/Dockerfile
- cmd/loki/Dockerfile.debug
- cmd/loki/loki-docker-config.yaml
- cmd/loki/loki-local-config.yaml
Preparing for a demo and those are not working.
This change make sure it works locally and with a simple docker run.
> Improve the local config to work locally and inside docker.

- docs/configuration/README.md
> fix stores for chunk and index in documentation for period_config

- pkg/logql/engine_test.go
> Fix a bad rebase between #1970 and #1965.

- pkg/util/validation/validate.go
> Fix lint from my last PR

- pkg/distributor/validator.go
- pkg/distributor/validator_test.go
- pkg/ingester/instance.go
- pkg/util/validation/validate.go
> more linter fixes

- Makefile
This is ignored by other OS, see https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated.
> Adds :delegated flags to speed up build experience on MacOS.

- .circleci/config.yml
- .drone/drone.yml
- CONTRIBUTING.md
- Makefile
- cmd/chunks-inspect/go.mod
- cmd/fluent-bit/Dockerfile
- cmd/loki-canary/Dockerfile
- cmd/loki/Dockerfile
- cmd/promtail/Dockerfile
- cmd/promtail/Dockerfile.arm32
- docs/installation/local.md
- go.mod
- loki-build-image/Dockerfile
- vendor/modules.txt
Being wary of 1.14 in favor of this upstream cortex discussion: https://github.com/cortexproject/cortex/pull/2480
> Revert "Update go from 1.13 to 1.14. (#2013)"

- production/loki-mixin/dashboard-loki-operational.json
> Dashboards: fixes the cpu usage graphs

- pkg/util/flagext/labelset.go
> Fixes a panic in dry-run when using external labels.

- CHANGELOG.md
- README.md
- docs/clients/promtail/installation.md
- docs/installation/docker.md
- docs/operations/loki-canary.md
- docs/operations/upgrade.md
- production/docker-compose.yaml
> Prep 1.5.0 release

- production/helm/fluent-bit/Chart.yaml
- production/helm/fluent-bit/values.yaml
- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
> updating all the images to 1.5.0 release

- docs/community/governance.md
> Add Aditya CS as a member of Loki.

- pkg/querier/querier.go
- pkg/querier/querier_test.go
> Fix error message for max tail connections.

- .circleci/config.yml
The word was redundant with the sentence where it is used.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
**Checklist**
> Remove unhelpful/problematic term in circleci.yml

- production/helm/fluent-bit/templates/clusterrole.yaml
- production/helm/fluent-bit/templates/podsecuritypolicy.yaml
- production/helm/loki/templates/podsecuritypolicy.yaml
- production/helm/promtail/templates/clusterrole.yaml
- production/helm/promtail/templates/podsecuritypolicy.yaml
Fixes https://github.com/grafana/loki/issues/2234
@cyriltovena please review
> Kubernetes manifests: Remove namespace from cluster-wide resources

- pkg/querier/queryrange/querysharding.go
- pkg/querier/queryrange/querysharding_test.go
Fixes the https://github.com/cortexproject/cortex/issues/2765 in loki
> avoids further time splitting in querysharding mware

- go.mod
- go.sum
- vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go
- vendor/github.com/cortexproject/cortex/pkg/chunk/series_store.go
- vendor/github.com/cortexproject/cortex/pkg/distributor/distributor.go
- vendor/github.com/cortexproject/cortex/pkg/ingester/ingester_v2.go
- vendor/github.com/cortexproject/cortex/pkg/ruler/ruler.go
- vendor/github.com/cortexproject/cortex/pkg/storage/tsdb/config.go
- vendor/github.com/cortexproject/cortex/pkg/storegateway/bucket_stores.go
- vendor/github.com/cortexproject/cortex/tools/querytee/proxy.go
- vendor/github.com/cortexproject/cortex/tools/querytee/proxy_metrics.go
- vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
- vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
- vendor/modules.txt
Bring new version of cortex with store fixes https://github.com/cortexproject/cortex/pull/2796
> Update to latest cortex.

- cmd/fluent-bit/loki.go
> Fixes the lint issue merged to master.

- .drone/drone.jsonnet
- .drone/drone.yml
> Test again arm32 on internal ci.

- docs/clients/promtail/stages/metrics.md
Specially w/r/t `max_idle_duration`
see https://github.com/grafana/loki/issues/2333
> Improve documentation of the metric stage.

- pkg/promtail/targets/manager.go
Refactors Promtail target manager code.
> Refactor Promtail target manager code

- Makefile
see https://circleci.com/gh/grafana/loki/24248?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
> Fixes helm publish that needs now to add repo.

- README.md
Logo in README does not display properly due to #2378
> Update logo link in README.md

- cmd/fluentd/fluent-plugin-grafana-loki.gemspec
> bump fluentd version to release a new gem.

- docs/sources/clients/_index.md
- docs/sources/clients/logstash/_index.md
Somehow I thought I did this but could not find the PR.
> Add logstash to clients page with FrontMatter.

- production/helm/loki-stack/Chart.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/templates/service-syslog.yaml
- production/helm/promtail/values.yaml
Signed-off-by: Ryan Holt <ryan@ryanholt.net>
Adds externalIPs support to the syslog service
N/A
**Checklist**
> promtail: enable externalIPs support for syslog

- pkg/storage/stores/shipper/downloads/table.go
- pkg/storage/stores/shipper/downloads/table_manager.go
- pkg/storage/stores/shipper/downloads/table_test.go
- pkg/storage/stores/shipper/shipper_index_client.go
- pkg/storage/stores/shipper/uploads/table_manager.go
Add spans for boltdb shipper index queriers to help debug latency issues.
> add some spans for boltdb shipper index queries

- CHANGELOG.md
- README.md
- docs/sources/clients/aws/ec2/_index.md
- docs/sources/clients/aws/ecs/_index.md
- docs/sources/clients/aws/ecs/ecs-task.json
- docs/sources/clients/aws/eks/values.yaml
- docs/sources/clients/promtail/installation.md
- docs/sources/configuration/_index.md
- docs/sources/installation/docker.md
- docs/sources/operations/loki-canary.md
- docs/sources/operations/upgrade.md
Updates Changelog and Upgrade guide!
> Release 1.6.0

- docs/sources/clients/aws/eks/_index.md
- production/helm/fluent-bit/Chart.yaml
- production/helm/fluent-bit/values.yaml
- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/values.yaml
- production/helm/promtail/Chart.yaml
- production/helm/promtail/values.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
> updating images to 1.6.0

- docs/README.md
fix dead link in docs/README.md
no issue
**Checklist**
> Docs: fix dead link

- README.md
> fix incorrect upgrade link

- docs/README.md
Removed content that is not appropriate for non-Grafana members. grafana/website is a private repo.
**Checklist**
> Docs: Update README.md

- README.md
Makes it easier for new user to find the information installing and getting started
Fixes #2511
**Checklist**
> Documentation: Fixes  install and getting-started links in the readme

- docs/sources/configuration/examples.md
Fixes memberlist path in our examples
> memberlist correct yaml path. closes #2499

- docs/sources/installation/_index.md
Not sure how the markdown ever worked. It's not subfolders with `README.md`. Now, they work!
**Checklist**
> fix: broken links in Tanka documentation

- CHANGELOG.md
- pkg/promtail/server/server.go
- pkg/promtail/targets/file/filetarget.go
- pkg/promtail/targets/file/tailer.go
This is a minor release only containing 2 fixes for Promtail
> Release-1.6.1

- pkg/ruler/manager/compat.go
- pkg/ruler/manager/compat_test.go
Will allow downstream consumers to use this functionality to parse rule files (attractive for operations automation).
> exports grouploader

- docs/sources/installation/_index.md
fix links in installation docs
> Docs: fix links in installation docs

- production/loki-mixin/dashboard-loki-operational.json
> Dashboard: typo in Loki Operational dashboard

- docs/sources/getting-started/get-logs-into-loki.md
**What this PR does / why we need it**: The instructions for getting started have a bad link for the promtail-local-config.yaml
**Checklist**
> Update docs to use raw link

- production/helm/loki-stack/Chart.yaml
- production/helm/loki/Chart.yaml
- production/helm/loki/templates/statefulset.yaml
- production/helm/loki/values.yaml
Add support to select PV by labels in Loki StatefulSet volumeClaimTemplates.
> production/helm: add support for PV selector in Loki statefulset

- docs/sources/clients/aws/ecs/_index.md
- docs/sources/clients/aws/eks/_index.md
found by: https://github.com/grafana/loki/pull/2331#issuecomment-675815819
> Fixes links in aws tutorials.

- pkg/chunkenc/memchunk.go
- pkg/storage/lazy_chunk.go
Instead of reversing all blocks, we reverse one block at the time.
> Improve the way we reverse iterator for backward queries.

- pkg/querier/queryrange/split_by_interval.go
> Fix error swallowed in the frontend.

- CHANGELOG.md
Signed-off-by: Heds Simons <heds@whaleway.net>
Links to the update docs in the changelog were incorrect.
Small change, no issue raised.
**Checklist**
> CHANGELOG: Update update document links to point to the right place.

- .drone/docker-manifest.tmpl
- .drone/drone.jsonnet
- .drone/drone.yml
- Makefile
Add builds for the ppc64le(Power) architecture.
**Checklist**
> Add support for building binaries for ppc64le arch

- pkg/logql/metrics.go
- pkg/logql/metrics_test.go
With LogQL 2.0 we will be able to parse byte sizes such as `KiB`.
**Checklist**
> Logging: Log throughput and total bytes human readable.

- production/loki-mixin/dashboards/loki-operational.libsonnet
see #2729
fixes #2729
**Checklist**
> fix(loki-mixin): refer to super.annotations

- pkg/promtail/targets/file/filetarget.go
- pkg/promtail/targets/file/filetargetmanager.go
- pkg/promtail/targets/lokipush/pushtargetmanager.go
- pkg/promtail/targets/stdin/stdin_target_manager_test.go
Fix a couple of typos I found while I was reading promtail.
> Fix typos in promtail

- pkg/chunkenc/memchunk_test.go
This gives now the ratio, and the characters inserted in human readable format.
> Improve the chunksize test.

- docs/sources/clients/fluentbit/_index.md
Signed-off-by: Heds Simons <heds@whaleway.net>
The Fluent Bit client documentation on building the plugin points to a non-valid link.
N/A
**Checklist**
> Docs: Corrects Fluent Bit documentation link to build the plugin.

- .circleci/config.yml
- .drone/drone.yml
- Makefile
- cmd/docker-driver/Dockerfile
- cmd/loki-canary/Dockerfile.cross
- cmd/loki/Dockerfile.cross
- cmd/promtail/Dockerfile.cross
- loki-build-image/Dockerfile
> Move CI to helm3.

- docs/sources/overview/_index.md
> doc: Fix query-frontend typo

- production/docker/README.md
- production/docker/docker-compose-ha-memberlist.yaml
- Fix the docker image version in the compose deployment
> Fix the docker image version in compose deployment

- production/ksonnet/loki/config.libsonnet
- production/ksonnet/loki/loki.libsonnet
- production/ksonnet/loki/wal.libsonnet
> loki wal libsonnet

- pkg/promtail/targets/file/tailer.go
Should help #2979 discover the reason why it stopped.
> Add more information about why a tailer would stop.

- ADOPTERS.md
Signed-off-by: Richard Hartmann <richih@richih.org>
> docs: Create ADOPTERS.md

- docs/sources/configuration/_index.md
**What this PR does / why we need it**: Clarifies that a feature is not yet available in Loki. This was causing user confusion. See https://github.com/grafana/loki/pull/2837#issuecomment-738012228
**Checklist**
> Docs: Update _index.md

- production/loki-mixin/dashboards/dashboard-loki-operational.json
> Remove regexes in the operational dashboard.

- CHANGELOG.md
- Makefile
- cmd/fluent-bit/Dockerfile
- cmd/fluent-bit/README.md
- cmd/fluent-bit/fluent-bit.conf
- cmd/fluent-bit/out_grafana_loki.go
- docs/sources/clients/aws/ecs/_index.md
- docs/sources/clients/fluentbit/_index.md
- docs/sources/upgrading/_index.md
- pkg/chunkenc/memchunk.go
- pkg/chunkenc/memchunk_test.go
- production/helm/fluent-bit/templates/configmap.yaml
Updates the changelog and the upgrade guide for 2.1.0
> Release 2.1.0!

- docs/sources/configuration/_index.md
This adds a missing instruction to docs that is required in order for variable expansion to work in 2.1.0
Didn't create an issue bc this is such a small change
**Checklist**
- [n/a] Tests updated
> Docs: Include instruction to enable variable expansion

- docs/sources/configuration/_index.md
- docs/sources/operations/storage/wal.md
WAL is missing in the configuration doc.
Fixes #3157 
**Checklist**
> Doc: Add missing wal in configuration

- pkg/distributor/http.go
> Fixes previous commit not using the new sized body.

- pkg/distributor/http.go
A follow-up PR to #3233 which missed a change causing json logs push path to fail.
> fix broken json logs push path

- pkg/querier/ingester_querier.go
[ingester_query] change var "clients" to "reps"
> [ingester_query] change var "clients" to "reps"

- pkg/logql/engine_test.go
I was debugging some stuff and added another test covering rate'ing multiple unwrapped streams and figured I'd add it to our tests.
> Testware/ rate-unwrap-multi

- pkg/promtail/targets/windows/bookmark.go
See this discussion https://github.com/grafana/loki/pull/3246#discussion_r568674040
FYI @rfratto
> Increase the windows bookmark buffer.

- cmd/promtail/main.go
> Embed timezone data in Promtail.

- docs/sources/maintaining/release.md
Fix the broken link in public release doc
NA
**Checklist**
> Remove extra space between broken link

- pkg/logql/log/parser.go
- pkg/logql/log/util.go
- pkg/logql/log/util_test.go
> Fixes a panic with whitespace key.

- pkg/storage/stores/shipper/compactor/table.go
- pkg/storage/stores/shipper/downloads/table.go
- pkg/storage/stores/shipper/util/util.go
- pkg/storage/stores/shipper/util/util_test.go
This is basically the same change as #3173 however between some merge conflicts, some re-writes I made to reuse code and add tests, the original author not signing the CLA and my wanting to get this merged to get it in the next release I recreated this as a separate PR. 
Apologies @netdata-be not trying to take away credit for you finding and fixing an issue!
> Loki: Ignore directories in object store list results

- docs/sources/upgrading/_index.md
Adds upgrade documentation related to #3404
N/A
**Checklist**
> Adding upgrade documentation for promtail pipeline_stages change

- pkg/logql/log/parser.go
- pkg/logql/log/parser_hints_test.go
- pkg/logql/log/parser_test.go
> Only unpack entry if the key `_entry` exist.

- production/ksonnet/loki/wal.libsonnet
This was previously a bit too high for comfort. Lowering as per best practices as we discover them :)
> reduce replay flush threshold

- pkg/logql/log/fmt.go
> Fixes a race introduced by #3434.

- docs/sources/clients/promtail/stages/labelallow.md
> fix spelling in doc

- docs/sources/configuration/_index.md
- docs/sources/configuration/examples.md
Closes https://github.com/grafana/loki/issues/3498
> compactor docs

- pkg/chunkenc/memchunk_test.go
> Fixes a test from #3216.

- docs/sources/logql/_index.md
This fixes some small docs bugs.
> docs: some small docs fixes

- .circleci/config.yml
- README.md
reworking our CI a little, removing this for now.
> Remove codecov

- .circleci/config.yml
- .drone/drone.jsonnet
- .drone/drone.yml
Also renamed the docker image tags from master->main
> Build: Update CI for branch rename to main

- LICENSE
- LICENSING.md
- README.md
- clients/LICENSE_APACHE2
- pkg/loghttp/LICENSE_APACHE2
- pkg/logproto/LICENSE_APACHE2
- pkg/logqlmodel/LICENSE_APACHE2
- pkg/util/LICENSE_APACHE2
- production/LICENSE_APACHE2
- tools/LICENSE_APACHE2
For a rationale as to why this was done, please see
* https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/
* https://grafana.com/blog/2021/04/20/qa-with-our-ceo-on-relicensing/
> Re-license to AGPLv3

- docs/sources/getting-started/get-logs-into-loki.md
Fix #33190 in the `grafana` repo.
> Fix wget link.

- ADOPTERS.md
> Add Red Hat to adopters

- docs/sources/getting-started/labels.md
Complement to https://github.com/grafana/loki/pull/3641
One Snippet wasnt edited.
> Update labels.md in Loki Docs

- clients/pkg/promtail/client/client.go
- clients/pkg/promtail/client/client_test.go
> Adds the ability to provide a tripperware to Promtail client.

- docs/sources/installation/local.md
fix the Promtail default config download link
Fixes #3646
**Checklist**
> fix the promtail-default-config download link in doc

- pkg/loki/runtime_config_test.go
- pkg/storage/stores/shipper/compactor/retention/expiration.go
- pkg/storage/stores/shipper/compactor/retention/expiration_test.go
- pkg/storage/stores/shipper/compactor/retention/retention_test.go
- pkg/validation/limits.go
> Use model.Duration for easy yaml/json marshalling.

- docs/sources/clients/fluentbit/_index.md
- production/helm/fluent-bit/README.md
Fix broken link to Fluent-bit README.
NA
NA
**Checklist**
> Fluent-bit git repo link fix

- .github/workflows/publish.yml
> Fix website branch to trigger update.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Improves wording and add warnings to issue templates, to avoid users submitting issues in the incorrect way.
N/A
**Checklist**
- [N/A] Documentation added
> Issue Templates: Improve wording and add warnings

- docs/sources/configuration/_index.md
- pkg/loki/modules.go
- pkg/querier/querier.go
> Loki: Add a flag for queriers to run standalone and only query store

- docs/sources/api/_index.md
- Updates link where primary branch updated to `main`
- Fixes broken link where package looks to have moved
- N/A
- This is purely a documentation update and hopefully I've followed proper update protocol
**Checklist**
- [ X ] Documentation added
- [ N/A ] Tests updated
> API Documentation: Fix document links for /loki/api/v1/push example

- pkg/querier/queryrange/codec.go
- pkg/querier/queryrange/codec_test.go
- pkg/querier/queryrange/limits_test.go
- pkg/querier/queryrange/querysharding_test.go
- pkg/querier/queryrange/roundtrip.go
- pkg/querier/queryrange/roundtrip_test.go
- pkg/querier/queryrange/split_by_interval_test.go
Allows reuse outside of the project, notably in Grafana.
> exposes loki codec

- pkg/logql/log/parser_hints.go
- pkg/logql/log/parser_hints_test.go
This PR include those now.
Fixes #3707
> Fixes parser labels hint for grouping.

- docs/Makefile
Update the targets in the makefile to make the `make docs` target work again
> Docs: fix makefile

- pkg/storage/stores/shipper/compactor/compactor.go
We initialize components for retention and deletion even when retention is not enabled. This PR takes care of it by initializing them only when retention is enabled.
> initialize retention and deletion components only when they are enabled

- docs/sources/clients/promtail/configuration.md
- docs/sources/clients/promtail/stages/metrics.md
> [doc] mtric -> metric

- production/loki-mixin/dashboards.libsonnet
- production/loki-mixin/dashboards/loki-deletion.libsonnet
Add a dashboard for checking out the state of delete requests in Loki.
Sample dashboard:
> add a dashboard for log deletion requests in loki

- docs/sources/overview/comparisons.md
Fixes a small typo in the docs, [Loki compared to other log systems](https://grafana.com/docs/loki/latest/overview/comparisons/)
> Docs: fixed typo in "Loki compared to other log systems" (levels -> labels)

- docs/sources/design-documents/2020-02-Promtail-Push-API.md
- docs/sources/design-documents/2020-09-Write-Ahead-Log.md
- docs/sources/design-documents/2021-01-Ordering-Constraint-Removal.md
- docs/sources/design-documents/_index.md
- docs/sources/design-documents/labels.md
> Docs: add and order missing design docs

- pkg/storage/stores/shipper/compactor/compactor.go
- pkg/storage/stores/shipper/compactor/deletion/delete_requests_table.go
A couple of minor fixes:
1. Fix temp file name used for uploading delete requests table
2. Log error on failure in removing the temp file used for uploading delete requests table, only when the error is not os.IsNotExist
3. fix the CLI flag for delete requests cancellation period
> Logs deletion fixes

- .drone/drone.jsonnet
- .drone/drone.yml
I'm migrating our agents to GCP, I want to make sure it's working
> Add step to identify windows Drone runner

- production/loki-mixin/dashboards/loki-reads.libsonnet
Recently realized the latency for ingester isn't working.
> Fixes Loki reads dashboard.

- docs/sources/configuration/_index.md
- docs/sources/operations/storage/_index.md
- docs/sources/operations/storage/logs-deletion.md
Add docs explaining about logs deletion feature.
**Checklist**
> docs for logs deletion feature

- docs/sources/logql/_index.md
Add explict syntax for using `pattern` parser
Motivation is from community discussion
https://community.grafana.com/t/how-to-use-loki-pattern-parser/49195
It also makes it consistent with other parsers explanations in the doc
**Checklist**
> Add explict syntax for using `pattern` parser

- production/ksonnet/loki/boltdb_shipper.libsonnet
- production/ksonnet/loki/images.libsonnet
1. Sets index-gateway image.
2. Updates boltdb-shipper storage config instead of overwriting in boltdb-shipper lib.
> Fix jsonnet for index-gateway

- production/loki-mixin/dashboards/loki-reads-resources.libsonnet
- production/loki-mixin/dashboards/loki-reads.libsonnet
Add index gateway to reads and reads-resources dashboards.
> add index-gateway to reads and reads-resources dashboards

- production/loki-mixin/dashboards/loki-deletion.libsonnet
I had by mistake set the uid of deletion dashboard to `retention` instead of `deletion`, possibly during copying around some jsonnet. This PR fixes it.
> update uid of loki-deletion dashboard

- .github/workflows/publish.yml
Sync `main` branch docs to `next` version instead of `latest` version.
Fixes NA
**Checklist**
> Sync `main` branch docs to `next` folder

- docs/sources/community/governance.md
> Add Danny Kopping to the Loki Team.

- .drone/drone.jsonnet
- .drone/drone.yml
- Makefile
This is needed to set the repository as "Protected"
> Sign drone.yml file

- pkg/storage/stores/shipper/compactor/compactor.go
Follow up for PR #3966. Left out access unchecked at some other place causing panic. :facepalm:
> fix a panic in compactor when retention is not enabled

- .github/CODEOWNERS
This will allow the team to be notified when PRs are created as they will automatically be assigned to `@grafana/loki-team`
N/A
**Checklist**
> Adding @grafana/loki-team as default CODEOWNERS

- docs/sources/logql/template_functions.md
Closes https://github.com/grafana/loki/issues/3939
thanks @AverageMarcus for the issue!
> Fixes regexReplaceAll docs

- cmd/loki/Dockerfile
cc @hhromic - thanks for the detailed write up.
> aligns rule path in docker img with bundled config. closes #3952

- docs/sources/configuration/_index.md
- docs/sources/operations/storage/boltdb-shipper.md
Adds IndexGateway configuration and talks about it in `boltdb-shipper` documentation.
**Checklist**
> add config and documentation about index-gateway

- tools/dev/loki-boltdb-storage-s3/README.md
fix typo in `tools/dev/loki-boltdb-storage-s3/README.md`
**Checklist**
> <docs>:fix typo in remote debugging docs

- docs/sources/operations/storage/_index.md
As mentioned in #3259,  permission `s3:ListObjects` is needed,  updating the document.
**Checklist**
> Docs: Update S3 permissions list

- loki-build-image/Dockerfile
Fix the loki-build-image Dockerfile, so it builds. Changes by @slim-bean.
**Checklist**
> loki-build-image: Fix building

- docs/sources/configuration/query-frontend.md
This comes out of our jsonnet, just putting it in our docs as well.
> adds query-frontend service hints for k8s, adapted from jsonnet

- docs/sources/configuration/query-frontend.md
Docs edit of prose added by https://github.com/grafana/loki/pull/4045.
> Revise wording of query frontend service configuration

- docs/sources/configuration/_index.md
Docs edit of prose added by https://github.com/grafana/loki/pull/4047.
> Clarify prose about querier frontend min-sharding-lookback

- .drone/drone.yml
Restores the drone signature that was lost in [this merge](https://github.com/grafana/loki/commit/32e55c30434c9fccdb22a577e8c88b9d3d9a8806#diff-bdb48f4b4fc2de6480bba395b25edd195a38b948ebd998d0fa78cc15cd8acbcfL974-L977)
**Checklist**
> Restoring drone signature

- pkg/storage/chunk/storage/caching_index_client_test.go
> fix broken TestCachingStorageClientStoreQueries

- pkg/loki/modules.go
This allows the http logger to include the org-id.
> Inject the org-id if possible from the start.

- clients/cmd/fluent-bit/Dockerfile
Bump base fluent-bit image to 1.8
none
**Checklist**
> Bump fluent-bit base image to 1.8

- .github/workflows/publish.yml
The docs test is timing out, so this comments it out until we can investigate.
> Docs - remove test

- tools/lambda-promtail/README.md
> Update lambda-promtail documentation example

- README.md
> Docs: Fix broken "Upgrading" link

- docs/sources/installation/docker.md
This change will need to be propagated to the v2.3.0 docs once approved.
Addresses issue https://github.com/grafana/loki/issues/4173
> Docs: correct path to Promtail configuration file

- pkg/loki/loki.go
Remove unused code I missed in https://github.com/grafana/loki/pull/4153
> Auth followup - Remove unused

- docs/sources/logql/_index.md
- docs/sources/logql/ip.md
- docs/sources/logql/query_examples.md
- Add a subsection for examples.  The section will be populated with more examples over time.
- Fix typos and wording
> Docs: improve LogQL section

- pkg/distributor/distributor.go
fix https://github.com/grafana/loki/issues/4169
Signed-off-by: fuling <fuling.lgz@alibaba-inc.com>
new goroutine metrics
> [fix] distributor: fix goroutine leak

- pkg/distributor/distributor.go
Alternative to #4238, fixing #4169 in a simpler way.  This is how it was done in Cortex https://github.com/cortexproject/cortex/pull/1641
Instead of creating another goroutine to wait for the background `sendSamples()` to finish, give the channels it is sending on a buffer so that they can send without a listener.
> Simplify Distributor.push

- docs/sources/configuration/_index.md
re: https://github.com/grafana/loki/pull/4242
Closes https://github.com/grafana/loki/issues/4158
N/A
**Checklist**
- [✅ ] Documentation added
- [N/A ] Tests updated
> Update limits_config docs to include querier.max_query_lookback flag

- pkg/loki/modules.go
- pkg/loki/runtime_config_test.go
- pkg/storage/chunk/cache/memcached_client.go
re: https://github.com/grafana/loki/pull/4227 
Fixes https://github.com/grafana/loki/issues/4243
N/A
**Checklist**
> Change prefix for `runtimeconfig` metrics from `cortex_` to `loki_`

- .github/stale.yml
Our stalebot message is a bet terse and doesn't really explain how we use the stalebot and what we are trying to accomplish with it, hopefully this change helps.
> Build: update stalebot message to be more descriptive and friendlier

- pkg/loki/loki.go
- pkg/loki/modules.go
This field can be used downstream projects, such as GEL to configure the memberlists of services, e.g. AdminAPI service.
**Checklist**
> Export MemberlistKV field on Loki struct

- docs/sources/storage/_index.md
The snippet part for storage_config was indented into schema_config which is wrong.
> Correct the indention for azure storage configuration

- production/loki-mixin/dashboards/dashboard-loki-operational.json
ref: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/619
Upstream recording rule switched to sum_irate, this was reflected in the recording rule name.
**Checklist**
> fix(rules): upstream recording rule switched to sum_irate

- docs/sources/api/_index.md
Apologies @jacobsakran, I merged your PR before you signed the CLA.
Would you mind re-opening it and I'll make sure my trigger-finger is holstered until everything is in place? :slightly_smiling_face:
> Revert "Correcting documentation example for `/api/prom/query`"

- production/README.md
Fixing an erroneous link in the docs
> Docs: Fix a link

- go.mod
- go.sum
- pkg/distributor/distributor_test.go
- pkg/ingester/flush_test.go
- pkg/loki/modules.go
- vendor/github.com/cortexproject/cortex/pkg/cortex/modules.go
- vendor/github.com/cortexproject/cortex/pkg/querier/queryrange/split_by_interval.go
- vendor/github.com/cortexproject/cortex/tools/querytee/proxy_endpoint.go
- vendor/github.com/grafana/dskit/kv/client.go
- vendor/github.com/grafana/dskit/kv/consul/client.go
- vendor/github.com/grafana/dskit/kv/consul/metrics.go
- vendor/github.com/grafana/dskit/kv/consul/mock.go
- vendor/github.com/grafana/dskit/kv/memberlist/kv_init_service.go
- vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go
- vendor/github.com/grafana/dskit/kv/memberlist/metrics.go
- vendor/github.com/grafana/dskit/kv/memberlist/tcp_transport.go
- vendor/github.com/grafana/dskit/kv/multi.go
- vendor/modules.txt
Upgrade to latest dskit.
**Checklist**
> Chore: Upgrade dskit

- pkg/logql/log/pattern/ast.go
- pkg/logql/log/pattern/pattern_test.go
https://github.com/grafana/loki/pull/4308
> Hotfix #4308 into k61

- pkg/ingester/client/client.go
- pkg/storage/chunk/gcp/instrumentation.go
- vendor/github.com/grafana/dskit/middleware/grpc.go
- vendor/modules.txt
Use `dskit/middleware`.
**Checklist**
> Chore: Use middleware package from dskit

- docs/sources/getting-started/get-logs-into-loki.md
- section titled "Get logs into Loki"
This PR replaces (and does more needed corrections) than https://github.com/grafana/loki/pull/4314. Thanks @khaledismaeel  for the original PR.
> Docs: improve spelling, grammar, and formatting.

- docs/sources/configuration/_index.md
see: https://community.grafana.com/t/boltdb-shipper-store-configuration-dependant-on-boltdb-entries/53260
see: https://community.grafana.com/t/boltdb-shipper-store-configuration-dependant-on-boltdb-entries/53260
n.a.
**Checklist**
> Docs: Update _index.md to add value boltdb-shipper for the key store

- docs/sources/operations/storage/retention.md
Cleans up the docs or more precisely de-duplicate it. 
Was reading the docs on how compactor dedups the indexs, can't leave this change to dedup the docs :D
**Checklist**
> Deduplicating the compactor docs

- clients/pkg/logentry/stages/logfmt.go
- clients/pkg/logentry/stages/logfmt_test.go
- clients/pkg/logentry/stages/stage.go
It would be good to have a `logfmt` stage, the same as `json` stage, for extracting data from a log entry. It works the same as `json` stage where the user can specify the mapping for extracted data to define which kvs to extract and set a different key than the one in logs for the extracted data.
I would open a flow up PR for adding documentation.
**Checklist**
> add logfmt promtail stage to be able to extract data from logfmt formatted log

- .github/pull_request_template.md
To make updating changelog as part of every PR.
**Checklist**
> Update PR template to include `changelog` update in the checklist

- clients/pkg/promtail/targets/lokipush/pushtarget.go
- pkg/loki/loki.go
- pkg/loki/modules.go
- pkg/querier/worker_service.go
To prevent unexpected behavior on HTTP endpoints we should explicitly define the allowed HTTP methods
**Checklist**
> Loki: Explicitly define allowed HTTP methods on HTTP endpoints

- production/loki-mixin/dashboards/dashboard-loki-operational.json
> Fixes the operational dashboard using an old metric.

- docs/sources/configuration/_index.md
- Create a new `<ring_config>` section that documents the ring defined in the `pkg/util/ring_config.go` file
- Rewrite ruler and scheduler ring docs to make usage of the new `<ring_config>` section
- Document new common ring
N/A
N/A
**Checklist**
> Docs: Document the common ring section

- cmd/loki/loki-docker-config.yaml
- cmd/loki/loki-local-config.yaml
- pkg/ingester/ingester.go
- pkg/loki/common/common.go
- pkg/loki/config_wrapper.go
- pkg/loki/config_wrapper_test.go
- pkg/scheduler/scheduler.go
- pkg/storage/chunk/schema_config.go
- pkg/storage/stores/shipper/compactor/compactor.go
This slims down `loki-local-config.yaml` and `loki-docker-config.yaml` to take advantage of the simplified config in the simple scalable deployment.
**Checklist**
> Update local and docker config for simple scalable deployment

- docs/sources/release-notes/v2-3.md
- docs/sources/release-notes/v2-4.md
Lots of small wording changes to improve the readability of the 2.4 release notes.
> Docs: revise v2.4 release notes

- docs/sources/configuration/_index.md
Oops, looks like we missed adding this to the configuration docs.
> Adds replication_factor doc to common config

- docs/sources/clients/promtail/stages/timestamp.md
Self-explanatory.
N/A
**Checklist**
> Docs: Fix a typo

- production/loki-mixin/dashboards/dashboard-loki-operational.json
Simplifies the 4 queries for this panel into one query.
> Simplify chunk flush rate % query.

- pkg/ruler/compat.go
Summary:
- Give record and group name for failing parsing.
> Give more context to rule parser errors.

- ADOPTERS.md
Signed-off-by: Champ-Goblem <cameron_mcdermott@yahoo.co.uk>
Northflank is a developer platform to deploy microservices, cron jobs and stateful databases from development to production. Logs and metrics play an important part of any cloud platform. We use Loki to process and store logs from multiple sources, providing live tailing and querying functionality to our users.
It adds [Northflank](https://northflank.com/) to the adopters list.
None
None
**Checklist**
Not applicable
> Add Northflank to the adopters list

- docs/sources/api/_index.md
- docs/sources/clients/aws/ecs/_index.md
- docs/sources/clients/aws/eks/_index.md
- docs/sources/clients/fluentbit/_index.md
- docs/sources/clients/lambda-promtail/_index.md
- docs/sources/clients/promtail/_index.md
- docs/sources/logql/_index.md
- docs/sources/logql/log_queries.md
- docs/sources/logql/metric_queries.md
- docs/sources/operations/recording-rules.md
- docs/sources/operations/storage/retention.md
- docs/sources/operations/storage/table-manager.md
- docs/sources/rules/_index.md
Little bits of formatting and spelling and wording surrounding some of the links also needed to change.
> Docs: fix broken links

- pkg/querier/http.go
Adds some logs regarding when live tailing starts and ends with the tenant id and selectors used.
Fixes: #4782
> add logging in querier when live tailing request starts and ends

- CHANGELOG.md
- clients/pkg/promtail/targets/file/filetarget.go
- clients/pkg/promtail/targets/file/filetarget_test.go
- clients/pkg/promtail/targets/file/filetargetmanager.go
Currently, Promtail creates inotify instances for each target.
`max_user_instances` isn't often high very much so I've made it singleton to reduce usage of the instances.
Fixes #4740 
**Checklist**
> Aggregate inotify watcher to file target manager

- pkg/logql/log/filter.go
related:
https://github.com/grafana/loki/pull/4803
> [Hot Fix] Merge improving case sensitive search correctly

- docs/sources/configuration/_index.md
fix https://github.com/grafana/loki/issues/4809
> [doc] wal: fix default value

- production/ksonnet/loki/boltdb_shipper.libsonnet
- production/ksonnet/loki/index-gateway.libsonnet
We have a set of common arguments which should apply to every component; these two were missing these common arguments.
N/A
**Checklist**
> Use common args in compactor and index-gateway

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/querier/querier.go
- pkg/util/label_filter.go
> Add LabelFilterer and Store wrapper

- pkg/logql/metrics.go
- pkg/logql/metrics_test.go
- pkg/loki/modules.go
- pkg/querier/queryrange/codec.go
- pkg/querier/worker_service.go
- pkg/util/server/middleware.go
- pkg/util/server/middleware_test.go
To support Query-tags to this week release(k73)
**Checklist**
> Add support for `X-Query-Tags` (#4814) to `k73`

- production/promtail-mixin/alerts.libsonnet
Corrects the alert definition to match its message
**Checklist**
> Set alert to fire after 15m, to match message

- production/ksonnet/loki/overrides.libsonnet
We current support per-tenant runtime _configurations_ as well as per-tenant runtime _overrides_. These runtime configurations are at present undocumented; this will be completed in a separate PR.
N/A
**Checklist**
> Allow for setting of per-tenant runtime configs in jsonnet

- production/ksonnet/loki/common.libsonnet
- production/ksonnet/loki/config.libsonnet
- production/ksonnet/loki/query-frontend.libsonnet
- production/loki-mixin/dashboards/dashboard-utils.libsonnet
- production/loki-mixin/dashboards/loki-chunks.libsonnet
- production/loki-mixin/dashboards/loki-logs.libsonnet
- production/loki-mixin/dashboards/loki-operational.libsonnet
- production/loki-mixin/dashboards/loki-reads.libsonnet
- production/loki-mixin/dashboards/loki-writes.libsonnet
- production/promtail-mixin/dashboards.libsonnet
This also format some jsonnet.
> Allow to set JAEGER_REPORTER_MAX_QUEUE_SIZE globally.

- production/ksonnet/loki/common.libsonnet
> Correctly set string in env variable in jsonnet

- production/loki-mixin/dashboards/loki-operational.libsonnet
- production/promtail-mixin/dashboards.libsonnet
Fix missing log datasource selector in operational dashboard plus broken label selectors in every query in promtail dashboard.
> fixes for operational and promtail dashboard

- .github/approve_config.yml
- .github/workflows/pr-gatekeeper.yml
Adds a GitHub Action to prevent merges of PRs unless at least one of the defined maintainers has approved it.
N/A
GitHub Actions. is. the. worst. :smiling_face_with_tear: 
**Checklist**
> Adding PR gatekeeper

- CHANGELOG.md
- go.mod
- go.sum
- pkg/storage/chunk/aws/s3_storage_client.go
- pkg/storage/chunk/azure/blob_storage_client.go
- pkg/storage/chunk/gcp/gcs_object_client.go
- pkg/storage/chunk/hedging/hedging.go
- pkg/storage/chunk/hedging/hedging_test.go
- pkg/storage/chunk/openstack/swift_object_client.go
- vendor/github.com/cristalhq/hedgedhttp/README.md
- vendor/github.com/cristalhq/hedgedhttp/hedged.go
- vendor/github.com/cristalhq/hedgedhttp/stats.go
- vendor/modules.txt
In github.com/cristalhq/hedgedhttp v0.7.0 there was a breaking change: error is returned during client/rounttripper creation instead of a panic, this PR updates it. Sorry for a change, but this is better.
**Checklist**
> Update hedgedhttp to v0.7.0

- production/loki-mixin/dashboards/loki-retention.libsonnet
Very minor, but this is tripping up an internal linter.
**Checklist**
> dashboards: fix typo in row title

- pkg/ruler/compat.go
I noticed this duplicated code (see 4 lines above the removal)
> Remove duplicated code in ruler rule validation

- CHANGELOG.md
- pkg/querier/queryrange/codec.go
- pkg/querier/queryrange/roundtrip.go
- pkg/querier/queryrange/roundtrip_test.go
- pkg/querier/queryrange/stats.go
- pkg/querier/queryrange/stats_test.go
> Correctly use limits middleware in series query

- .github/workflows/operator-bundle.yaml
- .github/workflows/operator-images.yaml
- .github/workflows/operator-scorecard.yaml
- .github/workflows/operator.yaml
> Fix operator actions branch protection from master to main

- .github/workflows/operator.yaml
This PRs provides fixes for the broken operator workflow: https://github.com/grafana/loki/actions/runs/1592986645/workflow
> Fix operator action for sending code coverage

- operator/README.md
Fix path to docs assets to render Logo correctly on operator README.md
> Fix logo on operator README.md

- CHANGELOG.md
- pkg/loki/config_wrapper.go
- pkg/loki/config_wrapper_test.go
Backport fix for replication factor from common config not being applied correctly when using memberlist ring
> Backport to 2.4: always apply replication factor common config (#4875)

- docs/Makefile
Updates the docs preview commands.
**Checklist**
> update docs preview commands

- docs/sources/logql/_index.md
> Fixes LogQL doc.

- CHANGELOG.md
- docs/sources/configuration/_index.md
I was changing the `wal` directory for Loki Ruler and configured it as the docs indicated (shown below):
```
remote_write:
enabled: true
wal:
dir: "/data/wal"
client:
url: http://cortex-distributor.monitoring.svc.cluster.local:8080/api/v1/push
queue_config:
capacity: 5000
max_samples_per_send: 1000
```
On deploy, components began to fail with this error:
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
line 191: field wal not found in type ruler.RemoteWriteConfig
```
I checked the ruler code and found that the sections for `remote_write`, `wal`, and `wal_cleaner` are discrete from each other, rather than `wal` and `wal_cleaner` being children of `remote_write` as the doc had indicated.
```
type Config struct { …
```
> Docs: Fix parent of wal and wal_cleaner in loki ruler config docs

- docs/sources/clients/promtail/installation.md
I found it buried in the community site that you need to have the `HOSTNAME` env var set when using `kubernetes_sd_configs` in order for promtail to work.
**Checklist**
> update promtail daemonset docs

- CHANGELOG.md
- docs/sources/configuration/_index.md
- docs/sources/configuration/query-frontend.md
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- pkg/querier/queryrange/roundtrip.go
- production/docker/config/loki-docker-memberlist-boltdb-shipper.yaml
- production/ksonnet/loki/config.libsonnet
- tools/dev/loki-boltdb-storage-s3/config/loki.yaml
* Move `querier.split_queries_by_interval` configuration flag to per-tenant limits
* Remove configuration check on the frontend's tripperware instantiation code
Fixes #5014
**Checklist**
> Move querier.split-queries-by-interval to a per-tenant configuration

- docs/sources/configuration/_index.md
This PR is to add the documentation for a param under limit_config i.e `max_concurrent_tail_requests`.
Fixes #4829
**Checklist**
> Docs: Add doc for limit param max_concurrent_tail_requests

- pkg/logql/engine.go
- pkg/querier/querier.go
- pkg/querier/queryrange/downstreamer.go
- pkg/querier/queryrange/limits.go
- pkg/querier/queryrange/stats.go
- pkg/storage/async_store.go
- pkg/storage/chunk/aws/dynamodb_storage_client.go
- pkg/storage/chunk/chunk_store.go
- pkg/storage/chunk/chunk_store_utils.go
- pkg/storage/chunk/gcp/bigtable_index_client.go
- pkg/storage/chunk/series_store.go
- pkg/storage/chunk/storage/caching_index_client.go
- pkg/storage/chunk/util/parallel_chunk_fetch.go
- pkg/storage/stores/shipper/downloads/table.go
- pkg/storage/stores/shipper/shipper_index_client.go
- pkg/tenant/resolver.go
- pkg/util/spanlogger/spanlogger.go
- vendor/github.com/grafana/dskit/spanlogger/noop.go
- vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
- vendor/modules.txt
Move `cortex/pkg/spanlogger` into `loki`.
It uses spanlogger from `dskit/pkg/spanlogger` with small wrapper created on the
`pkg/util/spanlogger` in loki repo.
This splits the old PR #4332 into mutiple small PR (before removing the `cortex/pkg/logger` dependency)
> Chore: use `spanlogger` from `dskit`

- operator/main.go
> Fix typo 'Registring'->'Registering'

- production/loki-mixin/dashboards/loki-chunks.libsonnet
I was looking at the dashboard and a bit confused by titles, so I made them more specifics.
> Improve title of the chunk dashboard.

- clients/pkg/promtail/targets/file/filetargetmanager.go
PR #4794 improved how we handle file watchers to reduce the number needed by promtail, however since merging this PR we started seeing alerts of files not being tailed.
Pulling up some thread dumps from a running promtail which was not tailing files showed many hundreds of blocks on the `/ready` handler trying to get a lock on the mutex.
```
goroutine profile: total 1173
825 @ 0x43b856 0x44c6ec 0x44c6c6 0x468325 0x484ae5 0x22c0648 0x22c0623 0x22bd906 0x23bb7c3 0x23c0bbf 0x7b2a0f 0x939f0f 0xa6c419 0xa5c0d2 0xa6c03b 0x7b2a0f 0xa6cd3a 0x7b2a0f 0xa4a82d 0x7b2a0f 0x7b643b 0x7b1ae8 0x46c661
#	0x468324	sync.runtime_SemacquireMutex+0x24								/usr/local/go/src/runtime/sema.go:71
#	0x484ae4	sync.(*Mutex).lockSlow+0x164									/usr/local/go/src/sync/mutex.go:138
#	0x22c0647 …
```
> Promtail: Add lock of mutex when using fileEventWatchers

- docs/sources/release-notes/v2-4.md
The bugs fixed will be added in a separate PR.  This PR introduces the subsection.
> Docs: add an empty subsection for v2.4.2 bug fix items

- CHANGELOG.md
- pkg/storage/chunk/azure/blob_storage_client.go
supersedes egress metric addition portion of #5057
> Add an egress bytes total metric to the azure client.

- docs/sources/configuration/_index.md
Updates the ring's ruler's configuration section in the docs. The ruler ring was previously using the shared `ring_config`, but that does not expose `num_tokens`, which can be configured for the ruler's ring
**Checklist**
> expand ruler ring section to add num_tokens property

- cmd/loki/main.go
- pkg/loki/loki.go
- pkg/loki/loki_test.go
Backports #4785 to 2.4 release branch in preparation for 2.4.2. This is required for GEL 1.3 for bugfix: https://github.com/grafana/loki-enterprise/pull/364
**Checklist**
> Loki: Implement custom /config handler (#4785)

- pkg/storage/chunk/aws/s3_storage_client.go
- pkg/storage/chunk/azure/blob_storage_client.go
- pkg/storage/chunk/gcp/gcs_object_client.go
- pkg/storage/chunk/openstack/swift_object_client.go
I was testing hedging and realize the metric name was broken 🤦 
> Fixes metric name for hedging object store requests

- .gitattributes
Summary:
This provides a reasonable automatic merge strategy for changelog
entries. No more merge conflicts on changelog changes.
> Enable merge union strategy for CHANGELOG.md.

- CHANGELOG.md
- docs/sources/configuration/_index.md
- docs/sources/upgrading/_index.md
- pkg/ingester/ingester.go
- pkg/loki/loki.go
- pkg/querier/querier.go
Backports 5077 into 2.4 release for 2.4.2
> Backport 5077: improve default config values (#5077)

- docs/sources/configuration/_index.md
Backports #4792 into 2.4 release for 2.4.2
> Backport 4792: Docs: Fix documentation with correct default values and add missing options (#4792)

- docs/sources/release-notes/v2-4.md
> Backport 5105 to release 2.4

- docs/sources/installation/docker.md
- docs/sources/maintaining/release.md
- go.mod
- production/docker-compose.yaml
- production/docker/docker-compose-ha-memberlist.yaml
- production/ksonnet/loki-canary/config.libsonnet
- production/ksonnet/loki/images.libsonnet
- production/ksonnet/promtail/config.libsonnet
- production/simple-scalable/docker-compose.yaml
- tools/promtail.sh
> Update to 2.4.2 release

- docs/sources/api/_index.md
> Document query limit parameter default.

- docs/sources/logql/log_queries.md
Fix broken `template_function` [doc link](https://grafana.com/docs/loki/latest/logql/log_queries/template_functions/) on [LogQL queries page](https://grafana.com/docs/loki/latest/logql/log_queries/#line-format-expression).
Wrong link
```
https://grafana.com/docs/loki/latest/logql/log_queries/template_functions/
```
Correct Link
```
https://grafana.com/docs/loki/latest/logql/template_functions/
```
**Checklist**
> Doc: Fix broken `template_function` doc link

- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- The PR reverts the changes made by #5023 
- This is done because the operator still uses v2.4.1 loki image
**Checklist**
> Revert operator's loki-config changes

- pkg/loki/modules.go
Able to "forget" the unhealthy member
**Checklist**
> Support "POST" method for distributor ring

- pkg/storage/chunk/cache/instrumented.go
I am getting a redis 500 error alert.
When I tried to trace the system to find the cause of the error, I found that there was no redis error span .
I hope to add tracing error tag to speed up troubleshooting
> [instrument] cache: add tracing instrumentation when error !=nil

- docs/sources/clients/_index.md
Came across these packages for JS with help from Danny - I thought they would be useful to include in our docs for posterity.  CC  @dannykopping for info!
**Checklist**
> Update to Unofficial clients for JS

- docs/sources/getting-started/logcli.md
Instead of mentioning the `go get` (or `go install`) command to install `logcli` from source (which does not work, see #5108), include the steps for how to build `logcli` from the checked out Github source.
Closes #5108
**Checklist**
> Improve docs on how to install logcli from source

- docs/sources/clients/logstash/_index.md
1. Read our CONTRIBUTING.md guide
2. Name your PR as `<Feature Area>: Describe your change`.
a. Do not end the title with punctuation. It will be added in the changelog.
b. Start with an imperative verb. Example: Fix the latency between System A and System B.
c. Use sentence case, not title case.
d. Use a complete phrase or sentence. The PR title will appear in a changelog, so help other people understand what your change will be.
3. Rebase your PR if it gets out of sync with main
4. If changing the Helm chart, please ensure the chart version is increased per semantic versioning (https://semver.org)
-->
**Checklist**
> doc: fix typo

- Makefile
When trying to `make images` from a fresh clone of loki, the `docker-driver` step kept failing with the error
`Error response from daemon: content <rootFs sha>: already exists`. 
Rebuilding the root fs before creating a plugin from it keeps the error from happening.
> makefile: Fix docker-driver build

- clients/cmd/logstash/Dockerfile
Do not update bundle dependencies while building logstash docker plugin. It breaks some transitive dependencies.
```
NoMethodError: undefined method `set_params' for #<OpenSSL::SSL::SSLContext:0x2627335c>
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:975:in `connect'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:924:in `do_start'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:919:in `start'
```
**Checklist**
> Fix transitive dependency failure while building logstash plugin

- Makefile
- go.mod
- go.sum
- vendor/modules.txt
PR that remove `cortex` dependency from `go.mod` of Loki
**Checklist**
> Remove `cortex` references from `go.mod` and makefile

- pkg/distributor/distributor.go
Optimize for:
* payload does not contain any streams
* a stream does not contain any entries
* none of the streams contain any entries
**Checklist**
> Return early if push payload does not contain data

- cmd/loki/loki-docker-config.yaml
- cmd/loki/loki-local-config.yaml
Remove the `instance_addr` property from the local and docker configs. Hard-coding this to `127.0.0.1` breaks any attempt to scale, as all instances in the ring will report the wrong address.
Fixes #5206 
**Checklist**
> Update local configs to fix issues with incorrect addresses

- docs/sources/clients/promtail/configuration.md
Added the link of `replace` pipeline stage to doc.
Closes #3415 <issue number>
**Checklist**
> Link `replace` pipeline stage to doc

- clients/cmd/logstash/Dockerfile
- Don't update the gems that come with the logstash image
**Checklist**
> Fix transitive dependency error

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/http_test.go
> Simplify logic in push tracker logic on distributor

- docs/sources/clients/_index.md
- docs/sources/clients/k6/_index.md
- docs/sources/clients/k6/log-generation.md
- docs/sources/clients/k6/query-scenario.md
- docs/sources/clients/k6/write-scenario.md
> Documentation for load testing Loki with xk6-loki

- pkg/iter/entry_iterator.go
See https://github.com/grafana/loki/pull/5324
> Recut `k83` with bugfix

- docs/sources/copyright/_index.md
Removing copyright notice per request from Fiona.
**Checklist**
> Delete docs/sources/copyright directory

- pkg/logproto/compat_test.go
This PR adds unitary tests that check that both `logproto.Sample` and `logproto.LabelPair` are incompatible with `cortexpb.Sample` and `cortexpb.LabelPair`, while ensuring that `logproto.LegacySample` and `logproto.LegacyLabelPair` are compatible with `cortexpb.Sample` and `cortexpb.LabelPair`.
The expected values were taken from `cortexpb` so they are a reliable source. 
N/A
See [PR 5301](https://github.com/grafana/loki/pull/5301) for context.
**Checklist**
> Add tests that ensure `LegacySample` and `LegacyLabelPair` compatibility

- pkg/usagestats/reporter_test.go
When running this test multiple times it gets flaky, so i removed metrics because this how it is used.
**Checklist**
> Fixes double metrics registration in reporting

- pkg/storage/stores/shipper/indexgateway/gateway.go
- pkg/storage/stores/shipper/indexgateway/gateway_test.go
See https://github.com/grpc/grpc-go/blob/master/stream.go#L120-L123
We should not be sending grpc responses concurrently on the same stream. It was a mistake on my end when I build index gateway and missed this part. See https://github.com/grpc/grpc-go/blob/master/stream.go#L120-L123
This PR fixes it by adding a mutex on stream level to synchronize it.
**Checklist**
> do not send grpc responses concurrently from index-gateway

- pkg/storage/stores/shipper/compactor/retention/iterator.go
- pkg/storage/stores/shipper/compactor/retention/iterator_test.go
- pkg/storage/stores/shipper/compactor/retention/retention.go
- pkg/storage/stores/shipper/compactor/retention/retention_test.go
- tools/tsdb/tsdb-map/main.go
- tools/tsdb/tsdb-map/main_test.go
This should help justify which optimizations are most worth pursuing.
> Adds a tool for converting boltdb->tsdb and benchmarking queries

- production/loki-mixin/dashboards/dashboard-loki-operational.json
This dashboard had an extraneous comma that was causing import to fail.
> Fix operational dashboard

- production/loki-mixin/dashboards/dashboard-loki-operational.json
Signed-off-by: Jordan Rushing <jordan.rushing@grafana.com>
This PR updates queries used in the `Loki - Operational` dashboard to correctly show Memcache and Consul metrics for Loki.
N/A
N/A
**Checklist**
> Update loki-mixin/dashboard-loki-operational queries to correctly display Loki metrics for Memcache and Consul

- docs/sources/logql/_index.md
Updates `contains` -> `contain`.
> Docs: Fix small spelling error 

- production/loki-mixin/dashboards/loki-reads.libsonnet
The operation has changed recently and I can see it broken.
**Checklist**
> Fixes Reads dashboard boltdb panels.

- pkg/logql/rangemapper.go.go
- pkg/logql/rangemapper_test.go
POC for Split [range] on instant queries.
Epic: https://github.com/grafana/loki-private/issues/159
https://github.com/grafana/loki-private/issues/201
**Checklist**
> Add mapper for range vector

- production/ksonnet/loki/index-gateway.libsonnet
With PR https://github.com/grafana/loki/pull/5484, I added support for doing tenant index query readiness using limits config but I missed updating the jsonnet to mount overrides volume to index gateways. This PR takes care of it.
> mount overrides volume to index gateways

- docs/sources/api/_index.md
Fix link reference to a subsection of our API docs
Fixes #5476
N/A
**Checklist**
> Docs: fix link reference to "Step vs Interval" subsection

- CHANGELOG.md
Update Changelog
@cyriltovena, as discussed via Slack
**Checklist**
> Changelog: Include #5409

- docs/sources/configuration/_index.md
- pkg/loki/loki.go
- pkg/loki/modules.go
- pkg/querier/http.go
- pkg/querier/multi_tenant_querier.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- Introduce Queries interface and Querier API.
- Configure a multi-tenant querier that just passes requests through.
Closes #231
**Checklist**
> Stub multi tenant querier.

- clients/pkg/promtail/targets/lokipush/pushtarget_test.go
This test failed sometimes ([example](https://drone.grafana.net/grafana/loki/9252/2/4)) due to not using the `require.GreaterOrEqual` function correctly. This function checks that the first element is greater or equal than the second.  
Most of the time this test succeeded because there was no difference between the TS of the log and the saved one.
**Checklist**
> Fix TestPlaintextPushTarget test

- .drone/drone.jsonnet
- .drone/drone.yml
Continuation of https://github.com/grafana/loki/pull/5506
**Checklist**
> Add prefix to vault path

- tools/lambda-promtail/Makefile
- tools/lambda-promtail/lambda-promtail/promtail.go
Re-adds basic auth support for lambda-promtail tool. This feature got lost in 699fffe9e583274ca55ef4e6073fa86d5d872548 refactoring.
**Checklist**
> Lambda-promtail: add basic auth support

- Makefile
- clients/cmd/fluent-bit/Dockerfile
- clients/cmd/promtail/Dockerfile
- clients/cmd/promtail/Dockerfile.arm32
- clients/cmd/promtail/Dockerfile.cross
- cmd/logcli/Dockerfile
- cmd/loki-canary/Dockerfile
- cmd/loki-canary/Dockerfile.cross
- cmd/loki/Dockerfile
- cmd/loki/Dockerfile.cross
- cmd/migrate/Dockerfile
- cmd/querytee/Dockerfile
- cmd/querytee/Dockerfile.cross
- loki-build-image/Dockerfile
- tools/dev/loki-boltdb-storage-s3/dev.dockerfile
> update loki go version to 1.17.8

- docs/sources/logql/log_queries.md
Originally, the link points to https://grafana.com/docs/loki/latest/logql/log_queries/ip/, where it should be https://grafana.com/docs/loki/latest/logql/ip/
N/A
N/A
**Checklist**
> Docs: Fix broken link to "Matching IP addresses"

- CHANGELOG.md
- production/loki-mixin/dashboards/dashboard-utils.libsonnet
- production/loki-mixin/dashboards/loki-reads-resources.libsonnet
- production/loki-mixin/dashboards/loki-writes-resources.libsonnet
This PR adds a function `DiskSpaceUtilizationPanel` to create PVC utilization panel, and also adds the function `containerLabelMatcher` to make the labels of relative queries configurable
**Checklist**
> Loki mixin: add DiskSpaceUtilizationPanel

- pkg/loki/loki.go
Fixes frontend-worker validate error message
NA
**Checklist**
> Fix frontend-worker validate error message

- operator/CHANGELOG.md
Fixes https://issues.redhat.com/browse/LOG-2324
**Checklist**
> operator: Reorder changelog in descending order

- pkg/storage/stores/shipper/compactor/table.go
We put the reference to the common index set in a dictionary that contains a reference to all the user index sets.
We iterate this dictionary to call `indexSet.done()` which would upload the compacted db from that index set and clean up the source file from the object store. For user index sets, the index files from common index sets are also a source for compaction.
We could lose data in a case where we cleaned up the common index set first and we failed to upload newly compacted files for user index sets. This PR fixes it by always calling `done()` on the common index set at the end.
> fix possible data loss issue due to failures in uploading compacted user index

- README.md
Make's Loki adopters visible on README (also encourage people to add to the list for anyone using Loki)
Fixes NA
**Checklist**
> Make Loki adopters visible in README

- tools/tsdb/tsdb-map/diff.sh
- tools/tsdb/tsdb-map/main_test.go
> more tsdb benchmarks + updates script to work with incompatible branches

- operator/CHANGELOG.md
- operator/internal/manifests/var.go
**What this PR does / why we need it**
This PR is a follow-up PR applying recommended k8s conventions for labels
Fixes #5607 
**Checklist**
> operator: Use recommended labels for LokiStack components

- pkg/storage/chunk/storage/caching_index_client.go
We found intermittent missing log entries from the response during spot checks. As per the preliminary investigation, it looks like a bug in caching or boltdb-shipper query processing. It seems to be a rare bug so I am adding some debug logs in the caching layer to cache the number of entries cached and retrieved per query.
Since this would be logged per query and the QPS can too high, I have added them as debug logs and made sure to not add these logs to the traces.
> debug log number of index entries cached and retrieved from the cache per index query

- operator/CHANGELOG.md
- operator/Makefile
- operator/docs/alerts.md
- operator/internal/manifests/internal/alerts/build.go
- operator/internal/manifests/internal/alerts/options.go
- operator/internal/manifests/internal/alerts/prometheus-alerts.yaml
- operator/internal/manifests/internal/alerts/testdata/test.yaml
- operator/internal/manifests/prometheus_rule.go
This PR adds a playbook for instructions and further details on the Prometheus alerts provided by the operator.
**Checklist**
> operator: Adding instructions to respond to alerts

- operator/docs/forwarding_logs_to_gateway.md
- operator/docs/hack_loki_operator.md
- operator/hack/addons.yaml
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
Updated the addons file to use `2.4.1` for promtail and logcli. Also configured the addons to work with the gateway and updated the documentation on how to use the addons.
Fixes #5570
**Checklist**
> operator: Update developer addons

- docs/sources/clients/aws/ecs/_index.md
My first grafana PR, be nice.
**Checklist**
- [√] Documentation added
- [√] Tests updated
> Docs: Fix broken Fluentbit / Fluentd plugin doc links

- ADOPTERS.md
> Add Digitalist as adopter

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/var.go
Updates the operand used by the operator to the current version of Loki.
Fixes #
**Checklist**
> operator: Update Loki operand to 2.4.2

- operator/CHANGELOG.md
- operator/docs/forwarding_logs_to_gateway.md
- operator/docs/hack_loki_operator.md
- operator/index.md
- Adds documentation to forward logs to cluster logging through gateway.
- Updates the hacking on OpenShift doc to add a create ns step.
**Checklist**
> operator: Document how to connect to LokiStack gateway component

- operator/CHANGELOG.md
- operator/controllers/lokistack_controller.go
- operator/internal/handlers/internal/gateway/base_domain.go
- operator/internal/handlers/internal/gateway/tenant_secrets.go
- operator/internal/handlers/lokistack_create_or_update.go
- operator/internal/handlers/lokistack_create_or_update_test.go
- operator/internal/status/lokistack.go
- operator/internal/status/status.go
- Degraded condition was getting reset immediately when no pod actions were pending.
- updates how lokistack reconcilation is done.
**Checklist**
> operator: Fix immediate reset of degraded condition

- .drone/drone.jsonnet
- .drone/drone.yml
- Makefile
Update the docker repo for querytee to `loki-query-tee` to keep it consistent with other query tee repositories, e.g. `cortex-query-tee`: https://hub.docker.com/repository/docker/grafana/cortex-query-tee
**Checklist**
> Update docker repo to grafana/loki-query-tee

- Makefile
- pkg/logql/syntax/fuzz.go
- pkg/logql/syntax/fuzz_test.go
We refactored the logql into its own package and missed updating the ossfuzz packages
> Build: update package for fuzzer after refactoring

- clients/cmd/promtail/promtail-local-limit-config.yaml
- clients/pkg/promtail/config/config.go
- clients/pkg/promtail/config/config_test.go
- clients/pkg/promtail/promtail.go
* Rename promtail config name 'limit_config' to 'limits_config'
* Add changelog entry
* Fix formatting
(cherry picked from commit d67306b657c10c6c6d19fec6855ef7babfc48755)
> [release-2.5.x] Promtail: Rename config name limit_config to limits_config (#5707)

- docs/sources/clients/promtail/stages/metrics.md
metric_histogram does not provide an `action` configuration, so remove it.
https://github.com/grafana/loki/blob/62876c57f76797df401190b5df6c0c9940b006b1/clients/pkg/logentry/metric/histograms.go#L11-L14
**Checklist**
> Promtail docs: fix metrics stage document

- .drone/drone.jsonnet
- .drone/drone.yml
(cherry picked from commit 6cc1f315469996712e65b3e9cdaa906b2ca5e7aa)
**Checklist**
> update drone to push images on tagged builds (#5824)

- .drone/drone.jsonnet
- .drone/drone.yml
(cherry picked from commit cc3a8e44158b43728caa5779719c1f8764d26bfe)
**Checklist**
> try fixing drone again (#5826)

- docs/sources/clients/lambda-promtail/_index.md
> Fix wrong indentation in example config

- pkg/storage/chunk/client/gcp/gcs_object_client.go
- pkg/storage/chunk/client/gcp/instrumentation.go
It bugged me that `gcsInstrumentation()` was mostly doing things that had nothing to do with instrumentation.
Note I took the code from after #5834.  Suggest merging that one first.
Separate the function into one part which creates the RoundTripper and one which wraps it in instrumentation.
**Checklist**
- NA Add an entry in the `CHANGELOG.md` about the changes.
> GCS: refactor creation of http client

- docs/sources/operations/storage/schema.md
We didn't have time for a proper review the first time, fixing up with feedback from the original PR #5863
> Docs: Improve the new schema docs

- clients/pkg/promtail/targets/docker/targetmanager.go
Fixed the tag name from:
`__meta_docker_container__log_stream`
to:
`__meta_docker_container_log_stream`
Fixes #5882
**Checklist**
> Promtail: Remove excessive underscore from `dockerLabelLogStream`

- pkg/logql/rangemapper.go
Helps developers understand how the rangemapper works.
**Checklist**
> Add more function comments to the rangemapper implementation

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/internal/manifests/config.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
- operator/internal/manifests/options.go
- operator/internal/manifests/var.go
- operator/main.go
This PR updates the loki operand from v2.4.2 to v2.5.0
**Checklist**
> operator: Update Loki operand to v2.5.0

- .drone/drone.jsonnet
- loki-build-image/Dockerfile
The new version finds more errors and supports more linters.
**Checklist**
> Update golangci-lint in build image

- pkg/storage/stores/series/series_index_gateway_store.go
> Fixes a panic when response is nil in the index-gw

- pkg/storage/factory.go
- pkg/storage/store.go
- pkg/storage/stores/shipper/gateway_client.go
Modifies how we check boltdb enabling to also see the current mode for the index gateway.
**Checklist**
> Only run boltdb-shipper when appropriate.

- docs/sources/installation/simple-scalable-docker.md
- production/simple-scalable/docker-compose.yaml
Corrects endpoints for /ready and /metrics in the YAML file and in the docs.
> Fix SSD Docker installation

- .drone/drone.yml
- Makefile
- tools/check-drone-drift.sh
Instead of checking the line count of the current branch an main, run
`make drone` and check if there are changes to the target
`.drone/drone.yml` file.
**Checklist**
> Other: Improve check-drone-drift script

- pkg/ingester/ingester.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- milli -> nano conversion in the querier
- add deletes to store requests from the ingester
> Fix query filtering

- pkg/querier/http.go
- pkg/querier/querier.go
- pkg/storage/stores/shipper/compactor/deletion/request_handler.go
Add query filtering to tail requests. Tested manually using the `logcl`.
**Checklist**
> Add query filtering to the tailer

- production/ksonnet/loki/gateway.libsonnet
Signed-off-by: irizzant <i.rizzante@gmail.com>
This PR fixes a typo in #5973 
**Checklist**
> Loki: remove typo error in gateway config

- pkg/logql/syntax/parser.go
- pkg/storage/stores/series/series_index_gateway_store.go
- pkg/storage/stores/shipper/indexgateway/gateway.go
> Backport gateway fixes to k94

- pkg/storage/stores/series/series_index_gateway_store.go
- pkg/storage/stores/series/series_index_gateway_store_test.go
We see some memory issue with new Index Gateway Client introduced in #5892, This PR just disables using new API by sticking with old API calls.
**Checklist**
> Disable calling new index-gateway client's API.

- docs/sources/getting-started/_index.md
- Add the -d option to all docker-compose up commands
- Make the wording consistent about the CWD
**Checklist**
> Docs: Improve wording of getting started guide

- docs/sources/fundamentals/architecture/deployment-modes.md
The configuration link on [deployment modes][1] page should go another parent level further in order to get `configuration/`, currently, it points to `fundamentals/configuration/`.
This MR corrects the relative link.
Fixes #<issue number> (N/A)
**Checklist**
[1]: https://grafana.com/docs/loki/latest/fundamentals/architecture/deployment-modes/
> Fix broken link on deployment-modes.md

- .github/labeler.yml
- .github/workflows/labeler.yml
Adds labeler action to github workflow.
**Checklist**
> Auto add labels on new pull request

- CHANGELOG.md
- docs/sources/upgrading/_index.md
- pkg/ingester/tailer.go
After some discussion we want to make these changes as separate PR's and hold off on the API changes for a bit.  It's easier to revert the change entirely and submit a new one
> Loki: revert changes to tailing

- pkg/querier/worker_service.go
> Removed double space in Log

- docs/sources/configuration/_index.md
Documentation was missing the references to the SSL key and cert
**Checklist**
> Documentation: Update SSL config for cassandra

- operator/CHANGELOG.md
- operator/internal/manifests/object_storage_test.go
- operator/internal/manifests/storage/configure.go
This PR changes the location of the GCP secret file. As is, there can be two secret files which will mount to the same path and cause the pods to not be deployed.
**Checklist**
> operator: Changing GCP secret file path

- docs/sources/upgrading/_index.md
In https://github.com/grafana/loki/pull/6015 we changed the default value of the Azure container name from `cortex` to `loki`. If anyone was relying on this value, they will need to manually specify it when upgrading to the latest version.
> Add upgrade guide regarding azure container name change

- docs/sources/configuration/_index.md
- pkg/ruler/base/notifier.go
- pkg/ruler/base/notifier_test.go
- pkg/ruler/base/ruler.go
Adds support for alert relabelling in ruler.
Fixes #5886 
**Checklist**
> feat(ruler): support alert relabelling

- production/ksonnet/loki/boltdb_shipper.libsonnet
- production/ksonnet/loki/distributor.libsonnet
- production/ksonnet/loki/index-gateway.libsonnet
- production/ksonnet/loki/ingester.libsonnet
- production/ksonnet/loki/loki.libsonnet
- production/ksonnet/loki/memberlist.libsonnet
- production/ksonnet/loki/query-scheduler.libsonnet
- production/ksonnet/loki/ruler.libsonnet
backports memberlist jsonnet code into k100 weekly release
> K100 backport memberlist jsonnet

- production/loki-mixin-compiled/dashboards/loki-writes.json
`loki-mixin-check` has been failing due to the compiled json dashboard missing changes done in https://github.com/grafana/loki/commit/d9cc6a87c225f3378b492a82cbff5f87b4b8fcca. This PR fixes it by rebuilding json dashboards using `make loki-mixin`.
> update loki-mixin json dashboards with latest jsonnet changes

- LICENSING.md
It's a minuscle change and currently not needed, but it makes my life tracking changes across the various projects easier.
> Add licensing boiler plate in case we ever need it

- pkg/loki/loki.go
- pkg/loki/modules.go
This PR registers a new route `/memberlist` to support the Memberlist status page included in the `dskit` library that we are using on module init.
N/A
N/A
**Checklist**
> Expose Memberlist status page on MemberlistKV module init

- pkg/loki/loki.go
- pkg/loki/modules.go
re: #6322 
N/A
N/A
**Checklist**
> Backport Memberlist status page in k100

- production/loki-mixin/config.libsonnet
- production/loki-mixin/dashboards/dashboard-utils.libsonnet
- production/loki-mixin/dashboards/loki-chunks.libsonnet
- production/loki-mixin/dashboards/loki-logs.libsonnet
- production/loki-mixin/dashboards/loki-operational.libsonnet
- production/loki-mixin/dashboards/loki-reads.libsonnet
- production/loki-mixin/dashboards/loki-writes.libsonnet
> Loki Prometheus mixin: templatize cluster label

- production/promtail-mixin/jsonnetfile.json
We had to change it to some older version to revert this PR
https://github.com/grafana/loki/pull/6377
Issue, context and long-term fix are explained in this
https://github.com/grafana/loki/issues/6378
Fixes #NA
https://github.com/grafana/loki/issues/6378
> chore(jsonnet-lint): Make `promtail-mixin` depends on `loki-mixin` `main` version

- clients/cmd/promtail/promtail-local-config.yaml
- clients/pkg/logentry/stages/extensions.go
- clients/pkg/logentry/stages/extensions_test.go
- clients/pkg/logentry/stages/pipeline.go
Context matters in log lines. 
Any log lines that are scrapped by promtail that is generated by `cri-0` runtime on Kubernetes can either be partial or full long line. Partial long lines are the result of "too" big (if it exceeds 8192 bytes per line) log lines that was split by the runtime.
And these partial and full log lines can be identified by "tags" that are part of log lines. Currently promtail ignores it. This PR make promtail supports `cri-o` tags.
Fixes #5854 
**Checklist**
> Promtail: Support all `cri-o` tags (multiline tags).

- docs/sources/clients/promtail/configuration.md
- docs/sources/configuration/_index.md
- docs/sources/operations/storage/retention.md
This set of small docs edits revise spelling, grammar, capitalization, and remove the need for a horizontal scroll bar in a set of 5 PRs that did not receive a docs review before merge.  I took the liberty of also fixing a few extra items that were next to these changes within the files.
- https://github.com/grafana/loki/pull/5880
- https://github.com/grafana/loki/pull/5873
- https://github.com/grafana/loki/pull/5706
- https://github.com/grafana/loki/pull/5686
- https://github.com/grafana/loki/pull/5661
> Docs: Edits for several PRs that did not have a docs review

- go.mod
- go.sum
- production/promtail-mixin/jsonnetfile.json
- vendor/github.com/hashicorp/memberlist/net.go
- vendor/github.com/hashicorp/memberlist/state.go
- vendor/github.com/hashicorp/memberlist/util.go
- vendor/modules.txt
This PR backports aa31b46d26c0392cbb4bcbd5c0fc20870120bc79 and 666bac28d9d345351f82f7dd7e5262fad7b0471f to k102.
N/A
N/A
**Checklist**
> Backport #6413 and #6377 to k102

- operator/docs/enhancements/retention_support.md
Signed-off-by: Shweta Padubidri <spadubid@redhat.com>
**Checklist**
> operator: Enhancement Proposal to configure log retention

- operator/docs/forwarding_logs_to_gateway.md
- operator/hack/addon_grafana_gateway_ocp.yaml
- operator/hack/addon_grafana_gateway_ocp_oauth.yaml
The gateway created by loki-operator now uses TLS encryption by default when using the OpenShift configuration. This PR updates the documentation and samples related to OpenShift to this new default.
- The configuration still uses Grafana 8.5.6, because there is a bug in 9.0.0 that makes using this version with Loki managed by loki-operator impossible. The issue is already fixed and the fix should be released with 9.0.1. Depending on when this release will happen, it might make sense to hold merging this PR until it can be updated to Grafana 9.
**Checklist**
> operator: Update Grafana and forwarding documentation

- docs/sources/configuration/_index.md
- pkg/loki/modules.go
- pkg/lokifrontend/config.go
This PR backports #6444 to 2.5.x.
Related to #5743 
This PR is needed for this operator fix PR #6443 
**Checklist**
> [release-2.5.x] Add TLS config to query frontend

- CHANGELOG.md
The link to a PR is wrong in the changelog.
**Checklist**
> Changelog: Fix changelog link

- CHANGELOG.md
I have grouped all changes from `Unreleased` section and placed them under `2.6.0` release section
> updated CHANGELOG.md for the release 2.6.0

- pkg/ingester/checkpoint.go
Closes https://github.com/grafana/loki/issues/6512
> dont call getinstance twice in checkpointing

- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
Minor fix for the CSV description mentioning the target namespace
**Checklist**
> operator: Fix clusterserviceversion description

- clients/pkg/promtail/targets/syslog/syslogtarget_test.go
Update certificates used for syslog’s tests
All the certificates now have a 20 year lifetime.
This reverts commit 2fc20af9a4e55483afe0f09f8a8119ab380daea9.
Fixes #6527
I included the CA key in case someone wants to generate new cert (or regen existing ones) without regenerating everything.
The certificates were generated using [cert-manager](https://cert-manager.io/). Here are the full manifests:
```
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
name: selfsigned
spec:
selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: promtail-test-ca
spec:
secretName: promtail-test-ca-certificate
duration: 175320h # 20 years
commonName: …
```
> Promtail: update certificates used for syslog’s tests

- docs/sources/clients/promtail/configuration.md
For some reason, the `-` character was missing here in the documentation.
After struggling for some time, I finally figured out that -- quite obviously -- envsubst default behavior applies and thus the documentation was wrong.
N/A
> Documentation: Fix documentation of environment variable defaults

- .drone/drone.jsonnet
- .drone/drone.yml
- loki-build-image/Dockerfile
Needed for https://github.com/grafana/loki/pull/6456
> Add jsonnet to build image

- operator/Makefile
A minor fix as a follow-up of #6549 that unblocks local development and production deployment of our website.
**Checklist**
> operator: Fix make target deps for web-pre

- pkg/storage/stores/shipper/compactor/compactor.go
Stop the timer responsible for delaying compaction to avoid leaking resources.
I found this while investigating queries getting OOM and noticed this was leaking resources unnecessarily.
N/A
For reference: https://www.arangodb.com/2020/09/a-story-of-a-memory-leak-in-go-how-to-properly-use-time-after/
**Checklist**
> Loki: Stop compaction interval timer to avoid leak

- pkg/canary/comparator/comparator.go
When running a lot of canaries it becomes common that they have a highly overlapping window where they all run the metric test query at the same time, this PR introduces some randomness in the first execution window such that all the canaries should approximately distribute over the size of the interval for which they run the metric test query.
**Checklist**
> Canary: add random start time for the periodic metric test query

- pkg/canary/comparator/comparator.go
- pkg/storage/stores/shipper/compactor/compactor.go
Backport two PRs:
1. One that adds randomness to Canaries to avoid having multiple canaries querying at the same time
2. A change to avoid resources leaking
N/A
N/A
**Checklist**
> Backport canaries changes to k105

- pkg/loki/modules.go
- pkg/storage/stores/shipper/compactor/compactor.go
- pkg/storage/stores/shipper/compactor/compactor_test.go
- pkg/storage/stores/shipper/compactor/index_set.go
- pkg/storage/stores/shipper/compactor/retention/pool.go
- pkg/storage/stores/shipper/compactor/retention/retention.go
- pkg/storage/stores/shipper/compactor/retention/retention_test.go
- pkg/storage/stores/shipper/compactor/retention/series.go
- pkg/storage/stores/shipper/compactor/retention/util_test.go
- pkg/storage/stores/shipper/compactor/table.go
- pkg/storage/stores/shipper/compactor/table_test.go
- pkg/storage/stores/shipper/compactor/testutil.go
- pkg/storage/stores/shipper/index/compactor/compacted_index.go
- pkg/storage/stores/shipper/index/compactor/compacted_index_test.go
- pkg/storage/stores/shipper/index/compactor/index.go
- pkg/storage/stores/shipper/index/compactor/index_compactor.go
- pkg/storage/stores/shipper/index/compactor/index_test.go
- pkg/storage/stores/shipper/index/compactor/iterator.go
- pkg/storage/stores/shipper/index/compactor/iterator_test.go
- pkg/storage/stores/shipper/index/compactor/pool.go
- pkg/storage/stores/shipper/index/compactor/series.go
- pkg/storage/stores/shipper/index/compactor/table_compactor.go
- pkg/storage/stores/shipper/index/compactor/table_compactor_test.go
- pkg/storage/stores/shipper/index/compactor/util.go
- pkg/storage/stores/shipper/index/compactor/util_test.go
- pkg/storage/stores/shipper/testutil/testutil.go
- pkg/storage/stores/shipper/util/util.go
- tools/tsdb/tsdb-map/main.go
To add support for tsdb index compaction and custom retention, this PR makes the compactor generic to support various index types. I have added a method to the compactor for registering the index types that just need to implement the specific interfaces to support compaction and custom retention. I have implemented it for `boltdb-shipper` and will open a follow-up PR for `tsdb` to avoid making this PR too big.
I have added some `ToDo`s to the code to take care of in follow up PRs since this PR is already too big.
Other than addressing those ToDos, I would also move the compactor to the generic `indexshipper` package in a separate PR.
**Checklist**
> generic index compactor

- docs/sources/clients/promtail/configuration.md
- docs/sources/configuration/_index.md
- docs/sources/operations/storage/retention.md
backport of https://github.com/grafana/loki/pull/6398
> [backport] Docs: Edits for several PRs that did not have a docs review (#6398)

- CHANGELOG.md
manually backported changes from #6386
> release changelog update

- pkg/storage/stores/indexshipper/downloads/index_set.go
- pkg/storage/stores/indexshipper/downloads/index_set_test.go
- pkg/storage/stores/indexshipper/downloads/table_manager_test.go
- pkg/storage/stores/indexshipper/downloads/table_test.go
- pkg/storage/stores/indexshipper/index/index.go
- pkg/storage/stores/indexshipper/shipper.go
- pkg/storage/stores/indexshipper/uploads/index_set.go
- pkg/storage/stores/indexshipper/uploads/index_set_test.go
- pkg/storage/stores/indexshipper/uploads/table_manager_test.go
- pkg/storage/stores/indexshipper/uploads/table_test.go
- pkg/storage/stores/shipper/index/querier.go
- pkg/storage/stores/shipper/index/table_manager.go
- pkg/storage/stores/shipper/index/table_manager_test.go
- pkg/storage/stores/shipper/index/table_test.go
- pkg/storage/stores/tsdb/compact.go
- pkg/storage/stores/tsdb/identifier.go
- pkg/storage/stores/tsdb/identifier_test.go
- pkg/storage/stores/tsdb/index_shipper_querier.go
- pkg/storage/stores/tsdb/querier_test.go
- pkg/storage/stores/tsdb/single_file_index.go
- pkg/storage/stores/tsdb/util_test.go
Sets up some groundwork for querying and parsing per tenant index built by the compactor.
**Checklist**
> Tsdb tenant index querying

- .drone/drone.jsonnet
- .drone/drone.yml
Follow-up of #6086 to include refactored conditions of #6511 .
**Checklist**
> Fix drone CI builds for loki operator

- .github/workflows/publish-technical-documentation-release.yml
> Append .x to the versioned directories for the website sync (#6611)

- integration/loki_micro_services_delete_test.go
- integration/loki_micro_services_test.go
- integration/loki_simple_scalable_test.go
- integration/loki_single_binary_test.go
- integration/shared_test.go
Adds an integration test for Simple Scalable Deployment (SSD), which comprises just read and write targets.
> Add integration for SSD (read & write targets)

- pkg/loki/modules.go
- pkg/storage/stores/tsdb/builder.go
- pkg/storage/stores/tsdb/compactor.go
- pkg/storage/stores/tsdb/compactor_test.go
- pkg/storage/stores/tsdb/index/chunk.go
- pkg/storage/stores/tsdb/index/chunk_test.go
Adds support for tsdb compaction including custom retention.
The way it works is it downloads the index and adds everything(requiring compaction) to `tsdb.Builder`.
While applying custom retention it works on the `tsdb.Builder` and keeps track of what chunks to add/delete to/from the index.
Finally, when the compactor calls for conversation `ToIndexFile`, it does all the add/delete chunk operations and makes `tsdb.Builder` build the index file.
I have not focused too much on performance, we can always benchmark and improve it.
We can use a pool in some places like reading the downloaded index but don't want to complicate the code too much with the initial implementation.
**Checklist**
> build and hook tsdb compaction code to the generic index compactor

- docs/sources/upgrading/_index.md
manually backported upgrading guide from release 2.6.0
> 2.6.0 upgrading guide

- pkg/storage/config/schema_config.go
- pkg/storage/store.go
- pkg/storage/store_test.go
- pkg/storage/stores/indexshipper/downloads/table_manager_test.go
- pkg/storage/stores/shipper/compactor/compactor.go
- pkg/storage/stores/tsdb/compactor_test.go
- pkg/storage/stores/tsdb/head_manager.go
- pkg/storage/stores/tsdb/index_shipper_querier.go
- pkg/storage/stores/tsdb/manager.go
- pkg/storage/stores/tsdb/store.go
Currently, the `tsdb` index client does not add configured index prefixes to the names of the tables. This PR fixes it by building the table names with the configured index prefixes.
> use the configured index prefixes while building table names for tsdb index

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manager/kustomization.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/ingester.go
- operator/internal/manifests/querier.go
- operator/internal/manifests/var.go
Bump the operand defs to use v2.6.0
**Checklist**
> operator: Update Loki operand to v2.6.0

- cmd/loki/Dockerfile
- cmd/loki/Dockerfile.cross
This PR defines the `USER` in the Dockerfile as `10001`. When running the Loki image as `nonroot` in Kubernetes, the resulting pod(s) will have a `CreateContainerConfigError`. This is because the `USER` in the image is a non-numerical value and thus it cannot resolve if the `USER` is a non-root user by default.
The work around for this in Kubernetes is to define the user to be some non-zero user. However, since the `USER` is already intended to be `10001`, the variable should be actually defined as this numeric value.
**Checklist**
> Running Loki as non-root in Kubernetes

- operator/CHANGELOG.md
- operator/internal/manifests/config.go
- operator/internal/manifests/internal/config/build_test.go
- operator/internal/manifests/internal/config/loki-config.yaml
- operator/internal/manifests/internal/config/options.go
- operator/internal/manifests/query-frontend.go
- operator/internal/manifests/query-frontend_test.go
This PR generalizes the fix introduced by #6443 to vanilla k8s usage when TLS is enabled. It also introduces changes to take advantage of the loki-config template.
Related #5743 
**Checklist**
> operator: Add support for tail TLS encryption

- operator/config/overlays/development/manager_related_image_patch.yaml
Addresses using #6659 in local development environment.
**Checklist**
> operator: Fix kind deployment for make quickstart

- docs/sources/fundamentals/labels.md
This was missing from our docs.
Fixes #6580
> Document loki lable format

- .github/workflows/publish.yml
> Publish backported documentation to the v2.3.x release directory

- .github/workflows/publish.yml
> Publish backported documentation to the v2.2.x release directory

- docs/sources/configuration/_index.md
- pkg/loki/modules.go
- pkg/storage/chunk/cache/groupcache.go
- pkg/storage/chunk/cache/groupcache_ringmanager.go
- pkg/storage/chunk/cache/groupcache_test.go
Adds a configuration option to set the capacity of each groupcache group.
N/A
We'll need to add the ability to configure each cache individually, because the chunk cache generally needs far more capacity than the other two (result, index query), but for now this is suitable.
I've also **decreased** the default capacity to 100MB per group.
**Checklist**
> Add configurable groupcache capacity

- cmd/querytee/main.go
> Add push route to query-tee

- production/ksonnet/loki/memberlist.libsonnet
Add changes from PR https://github.com/grafana/loki/pull/6660 which lets us configure memberlist to use cluster labels.
> add jsonnet for configuring memberlist cluster label

- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
This PR is a flow up to #6514. After making the operator conform to the `restricted` policy, the addons needs to be updated to work under the same conditions. This was partially done in that PR, but it also broke the `promtail` addon. This PR fixes that addon to allow it to send logs without needing to be `privileged`. 
**Checklist**
> operator: Addons work in restricted policy

- pkg/storage/chunk/cache/groupcache.go
If the http2 transport isn't reused, we create a connection on every request that is never terminated. This change just reuses one transport for all groupcache connections
> Fix goroutine leak when using http2 with groupcache

- pkg/storage/store.go
- pkg/storage/stores/tsdb/head_manager.go
- pkg/storage/stores/tsdb/store.go
It includes two small changes:
1. We made tsdb store instance public to only allow creating a single instance of it. I have refactored the code not to make it public.
2. Build a tsdb from active wal and upload it to the object storage during ingester shutdown. This is to avoid losing the index if an ingester is being shut down forever.
> tsdb store refactoring

- pkg/storage/chunk/cache/groupcache.go
Disable hotcache. As a part of experimentation.
**Checklist**
> chore(groupcache): Disable hotcache during set

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/overlays/development/manager_related_image_patch.yaml
- operator/config/overlays/openshift/manager_related_image_patch.yaml
- operator/config/overlays/production/manager_related_image_patch.yaml
- operator/docs/operator/compatibility.md
- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
- operator/internal/manifests/var.go
Bump the operand defs to use v2.6.1
**Checklist**
> operator: Update Loki operand to v2.6.1

- go.mod
- go.sum
- vendor/github.com/hashicorp/memberlist/queue.go
- vendor/modules.txt
re:
- #6717
- #6773
N/A
#6773 accidentally targeted `main` instead of `k108`.
**Checklist**
> Backport Memberlist dependency version bump to k108

- docs/sources/logql/template_functions.md
The correctly specified signature allows avoiding misunderstanding (is it prefix or suffix?)
n/a
n/a
**Checklist**
> Docs: Fix typo in 'trimPrefix' function signature

- docs/sources/clients/promtail/installation.md
Save time fixing YAML syntax for installing Promtail ;)
N/A
N/A
**Checklist**
> Docs: Fix YAML syntax and ConfigMap reference

- docs/sources/fundamentals/architecture/components.md
Fix a typo in architecture/components.md
**Checklist**
> docs: Fix a typo in architecture/components.md

- pkg/storage/chunk/cache/cache.go
Panic on querier when enabling groupcache. Similar to one below.
```
goroutine 337 [running]:
github.com/grafana/loki/pkg/storage/chunk/cache.(*instrumentedCache).Stop(0x26fa240?)
/home/kavirajk/src/loki/pkg/storage/chunk/cache/instrumented.go:117 +0x1c
github.com/grafana/loki/pkg/storage/chunk/cache.statsCollector.Stop({{0x270cc18?, 0xc0004dad20?}})
/home/kavirajk/src/loki/pkg/storage/chunk/cache/stats.go:50 +0xe3
```
Groupcache was still registring for index-cache, because we missed the edge case on `IsGroupcacheSet()` helper.
So when we have global flag `groupcache.enabled` then even using just fifocache for index cache wont work when initializing the stats wrapper for cache.
```
cache …
```
> chore(groupcache): Fix panic with stats collector wrapper

- cmd/loki/main.go
It doesn't throw error during version check if config file isn't present.
Fixes #6770 
**Checklist**
> Run `loki -version` without needing a config defined

- docs/sources/configuration/_index.md
> Remove reference to non-existent config field

- pkg/storage/stores/tsdb/index/shard.go
This calculates shard membership in an equivalent but simpler way.
> Simplify shard membership calculations

- docs/sources/operations/storage/retention.md
Currently if you read through the entire doc, it's not super clear what happens if I don't enable retention.
Sometimes the doc even try to impose the default retention is 30 days (which is the case only if flags are set without retention period config)
This PR try to clarify the default behavior.
Fixes #NA
One of the community question sparked this PR.
https://grafana.slack.com/archives/CEPJRLQNL/p1659090314351459
**Checklist**
> doc(retention): Add clarity on default behavior.

- operator/bundle/metadata/properties.yaml
This PR adds the properties file to the bundle. The properties file is the location where dependencies and specific properties (like the maximum supported OpenShift version) can be defined.
**Checklist**
> Adding properties file

- pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager.go
- pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager_test.go
It includes a couple of improvements for handling a large number of delete requests:
* Group delete requests by users to quickly check if a user has any delete requests or not.
* Track the oldest start and latest end time of delete requests from a user to quickly check if a chunk overlaps that interval before checking it against all the delete requests.
I have also removed the overlap check for user index(i.e userID != "") in `IntervalMayHaveExpiredChunks`.
This is to ensure we update the index for chunks that overlap multiple tables and are requested for deletion while the delete requests do not cover all the table intervals.
**Checklist**
> Delete requests processing improvements

- pkg/storage/stores/tsdb/head_manager.go
We create something called tenant `head`s for holding details of flushed chunks in memory. We use an atomically incrementing number for referencing the chunks to streams. Each time we see a new stream, we increment and use that number as stream references. While logging stream info to the WAL, we also log the stream reference number and chunks then point to the streams using those reference numbers.
We create a new head while rotating the index every 15 mins, which restarts the stream references from `1`. There is supposed to be just one head per tenant every 15 mins, but due to a race, we create multiple heads, causing us to have the same reference number for different streams in the WAL. This causes the index to have chunks pointing to an …
> avoid creating multiple tenant heads in tsdb during a race

- production/ksonnet/loki/distributor.libsonnet
Existing limits were low for a large environment. In an attempt to standardize across our deployments it seemed to make most sense to change the defaults here and override when we want less, rather than having to override when we want more.
> Existing limits were low for large envs

- docs/sources/clients/lambda-promtail/_index.md
- docs/sources/operations/storage/boltdb-shipper.md
This documentation-only PR improves some spelling and grammar in sections previously updated with PRs 5796 and 6102.
> Docs: improve wording and grammar

- docs/sources/logql/analyzer.md
- docs/sources/logql/analyzer/handlebars.js
- docs/sources/logql/analyzer/script.js
- docs/sources/logql/analyzer/style.css
cherry-picked FE related commits from this PR https://github.com/grafana/loki/pull/6172 to merge them separately without backend
> Logql analyzer page cherry picks

- integration/cluster/cluster.go
Occassionaly we can see test flakes like that:
`server: listen tcp :34473: bind: address already in use`
This is because we allocate ports by checking if they are free and then biding them briefly. That leaves a chance that already allocated ports are allocated twice. This change prevents this from happening by keeping track of the ports that are about to be used.
> Fix free port allocation flake

- .drone/drone.jsonnet
- .drone/drone.yml
- clients/cmd/docker-driver/Dockerfile
- clients/cmd/fluent-bit/Dockerfile
- clients/cmd/promtail/Dockerfile
- clients/cmd/promtail/Dockerfile.arm32
- clients/cmd/promtail/Dockerfile.cross
- clients/cmd/promtail/Dockerfile.debug
- cmd/logcli/Dockerfile
- cmd/loki-canary/Dockerfile
- cmd/loki-canary/Dockerfile.cross
- cmd/loki/Dockerfile
- cmd/loki/Dockerfile.cross
- cmd/loki/Dockerfile.debug
- cmd/migrate/Dockerfile
- cmd/querytee/Dockerfile
- cmd/querytee/Dockerfile.cross
- loki-build-image/Dockerfile
- operator/Dockerfile
- operator/Dockerfile.cross
- operator/calculator.Dockerfile
- tools/dev/loki-boltdb-storage-s3/dev.dockerfile
- tools/lambda-promtail/Dockerfile
- Upgrade base images to alpine 3.15.6 everywhere
- Update golang images to 1.18.5
> Update alpine and golang base images

- .circleci/config.yml
- .drone/drone.yml
- Makefile
> Update build-image to 0.23.0

- operator/CHANGELOG.md
- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
This PR adds the `operators.openshift.io/valid-subscription` annotation to the operator metadata.
**Checklist**
> operator: Adding valid subscription annotation to metadata

- production/ksonnet/loki/memberlist.libsonnet
Signed-off-by: irizzant <i.rizzante@gmail.com>
Fixes #6887
**Checklist**
> memberlist: allow consul deployment

- docs/sources/configuration/_index.md
* Update deletion_mode to limits_config. 
* Add deprecated values mentioned in https://github.com/grafana/loki/pull/6917
Depends on: https://github.com/grafana/loki/pull/6917
**Checklist**
> Update documentation deletion_mode and allow_deleted configuration values

- pkg/querier/querier.go
A customer mentioned that this error message was not too clear. It is rewritten now.
Fixes https://github.com/grafana/loki/issues/6438.
**Checklist**
> Improve error message

- operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
- operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
This PR fixes the text that is displayed in an OCP cluster after installing Loki operator. The text should say that the operator must be deployed to `openshift-operators-redhat` not `openshift-logging`
**Checklist**
> operator: Change Loki Operator namespace to openshift-operators-redhat in the CSV

- docs/sources/configuration/_index.md
Improve documentation regarding TLS.
**Checklist**
> docs:Add documentation for TLS configuration parameters for HTTP and gRPC

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/streamsharder.go
- pkg/distributor/streamsharder_test.go
Modify sharding implementation to only use a subset of entries for each shard.
> Modify sharding to not duplicate all entries for all shards

- tools/lambda-promtail/main.tf
- tools/lambda-promtail/variables.tf
> feat: add kms ecryption

- tools/lambda-promtail/lambda-promtail/s3.go
This PR prevents LB's with numbers in the name from being truncated in the label.  Our ALB's start with `k8s-`, so the `__aws_s3_log_lb` label is `k` for all of their logs.
Fixes #6960
**Checklist**
> Lambda-Promtail: Allow numbers in LB name regex

- operator/internal/manifests/var.go
- production/nomad/loki-distributed/README.md
- production/nomad/loki-distributed/job.nomad.hcl
Fix distributor spells in production Nomad job and docs.
**Checklist**
> nomad production: Fix Loki distributor in production Nomad job and docs.

- docs/sources/operations/observability.md
Correcting two mistakes that @osg-grafana found in PR#6971. 
**Checklist**
> [Doc] Fixed comma and missing "of" in observability.md

- operator/hack/addons_dev.yaml
- operator/hack/addons_ocp.yaml
The `image` field for the logcli addons has the wrong value, which causes the pod to deploy with errors.
**Checklist**
> operator: Fixing logcli pod image value for operator addons

- docs/sources/community/getting-in-touch.md
Now we alternate between EU and US timezones.
**Checklist**
> doc(community): Update community call timings.

- production/helm/loki/README.md
- production/helm/loki/README.md.gotmpl
- production/helm/loki/templates/gateway/deployment-gateway.yaml
- production/helm/loki/templates/read/statefulset-read.yaml
Verify the upgrade path from `grafana/loki-simple-scalable` -> `grafana/loki` works.
Fixes #6874
> Helm: test migration from `grafana/loki-simple-scalable`

- operator/CHANGELOG.md
- operator/apis/config/v1/projectconfig_types.go
- operator/bundle/manifests/loki-operator-manager-config_v1_configmap.yaml
- operator/config/overlays/openshift/controller_manager_config.yaml
- operator/internal/manifests/build_test.go
- operator/internal/manifests/compactor.go
- operator/internal/manifests/distributor.go
- operator/internal/manifests/gateway.go
- operator/internal/manifests/indexgateway.go
- operator/internal/manifests/ingester.go
- operator/internal/manifests/querier.go
- operator/internal/manifests/query-frontend.go
- operator/internal/manifests/ruler.go
- operator/internal/manifests/var.go
Currently we only support running the operator on linux-based nodes, so it makes sense to extend this to the operand containers as well to avoid confusion in multi-os clusters.
One open question is whether this should be done always or only if the operator is running in OpenShift as the support situation might be different outside of OpenShift.
Fixes [LOG-2895](https://issues.redhat.com/browse/LOG-2895)
**Checklist**
> operator: Configure default node affinity for all pods

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/instance.go
- pkg/ingester/instance_test.go
- pkg/iter/entry_iterator.go
- pkg/iter/entry_iterator_test.go
- pkg/iter/sample_iterator.go
- pkg/iter/sample_iterator_test.go
- pkg/querier/querier.go
- pkg/querier/querier_mock_test.go
- pkg/querier/querier_test.go
- pkg/storage/async_store_test.go
- pkg/storage/batch.go
- pkg/storage/batch_test.go
- pkg/storage/lazy_chunk_test.go
- pkg/storage/store_test.go
- pkg/storage/util_test.go
@owen-d had a suggestion that was dramatically dimpler. Revert this whole thing and the simplified PR will be forthcoming
> Revert "Hide duplicates caused by stream sharding (#7005)"

- clients/pkg/promtail/targets/gcplog/pull_target.go
- clients/pkg/promtail/targets/gcplog/target.go
- clients/pkg/promtail/targets/gcplog/target_test.go
- go.mod
- pkg/loki/modules_test.go
- pkg/storage/chunk/cache/memcached_client.go
- pkg/storage/chunk/cache/memcached_client_selector.go
- pkg/storage/chunk/cache/memcached_client_selector_test.go
The build is currently dependent upon you building in an environment with internet connectivity and GCP credentials. This PR fixes the few parts of our code and test that rely on these external dependencies so it can be built in an environment without internet or GCP credentials (such as when building a [nix flake](https://github.com/grafana/loki/pull/7020))
Fixes #7028
**Checklist**
> Enable build in env w/o internet or GCP creds

- CHANGELOG.md
- docs/sources/logql/metric_queries.md
logql engine support exec vector(0) grama.
new PR of :https://github.com/grafana/loki/pull/7023
Fixes #6946
preview
**Checklist**
> [doc] logql: logql engine support exec vector(0) grama

- tools/lambda-promtail/main.tf
This PR will help to increase a necessary policy (kms and ec2) to resource log group and lambda.  
**Checklist**
> feat: add kms and ec2 permission

- docs/sources/operations/troubleshooting.md
Add troubleshooting instructions for running istio and loki. It takes a long time
to figure out how to make it work, hope it will help others.
**Checklist**
> Troubleshooting: instructions for loki + istio

- docs/sources/operations/shuffle-sharding.md
When shuffle sharding is disabled, meaning either `max_queriers_per_tenant=0` (default) or `max_queriers_per_tenant > number_of_available_queriers`
then failed query from crashed querier can remap to **any** available queriers (NOTE: all queriers are available in case of shuffle-sharding is disabled)
thanks @ashwanthgoli for pointing it out.
**Checklist**
> doc: Clarity on querier remapping when shuffle sharding is disabled

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/modules.txt
The `v20.10.17` release of moby (`github.com/docker/docker` in go.mod) fixed several CVEs described in their [release notes](https://github.com/moby/moby/releases/tag/v20.10.17). This PR upgrades the dependency to that version.
N/A
N/A
**Checklist**
> Bump github.com/docker/docker to v20.10.17

- production/helm/loki/templates/monitoring/servicemonitor.yaml
Affects the Loki Helm chart
The ServiceMonitor resource was missing a conditional for the `enabled` flag, as per the other monitoring resources.
Fixes #7066
**Checklist**
> Missing conditional on ServiceMonitor

- docs/sources/configuration/_index.md
when setting
```
basic_auth:
username: xxx
password: yyy
```
following error gets thrown:
```
failed parsing config: /etc/loki/loki-config.yaml: yaml: unmarshal errors:
line 123: field basic_auth not found in type base.NotifierConfig
```
**Checklist**
> docs: fix alertmanager_client config settings

- docs/sources/configuration/_index.md
- integration/client/client.go
- integration/cluster/cluster.go
- integration/loki_micro_services_delete_test.go
- pkg/logcli/query/query.go
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
- pkg/ruler/config.go
- pkg/ruler/registry.go
- pkg/ruler/registry_test.go
- pkg/ruler/ruler.go
- pkg/util/cfg/cfg.go
- pkg/util/cfg/cfg_test.go
- pkg/util/cfg/dynamic.go
- pkg/util/cfg/files.go
- pkg/util/cfg/files_test.go
- pkg/util/cfg/precedence_test.go
- pkg/validation/limits.go
This PR adds the ability for the ruler to write to more than one remote client. In order to preserve backward compatibility, a new field `Clients` is added to the `remote_write` config in addition to the previous `Client` field. The latter is only taken into account when `Clients` is empty.
Resolves #4368 
Should `Client` be deprecated for the upcoming major release?
**Checklist**
> Add ability for Ruler to remote write to multiple clients

- docs/sources/api/_index.md
- docs/sources/operations/storage/logs-deletion.md
- Fix a typo
- Fix the links in for the deletion API 
**Checklist**
> Small updates to the deletion documentation

- production/helm/loki/Chart.yaml
- production/helm/loki/README.md
Bumps the helm chart version to trigger a release to test if that action is fixed.
> Bump chart version to test release

- production/README.md
Fix the link path leading to Loki's Helm chart, in `production/README.md`.
[Current broken link](https://github.com/grafana/loki/blob/main/production/production/helm/loki/README.md).
Hey @trevorwhitney, just found out the broken link added by #6985. 
**Checklist**
> Docs: Fix Helm chart link path

- operator/internal/manifests/gateway_test.go
Provides a fix for flaky test: https://github.com/grafana/loki/runs/8268253686?check_suite_focus=true
**Checklist**
> operator: Fix flaky TLSProfile feature gate test

- pkg/storage/config/schema_config.go
- pkg/storage/config/schema_config_test.go
- pkg/storage/store.go
- pkg/storage/stores/indexshipper/downloads/table_manager.go
- pkg/storage/stores/indexshipper/downloads/table_manager_test.go
- pkg/storage/stores/indexshipper/shipper.go
- pkg/storage/stores/tsdb/chunkwriter.go
- pkg/storage/stores/tsdb/store.go
Since we are planning to start deploying `tsdb` to critical cells, we want to have a disaster recovery without any data loss.
This PR adds support to `tsdb` store itself to configure `boltdb-shipper` as a backup chunk writer.
When the flag is enabled, `tsdb` store would also index chunks in `boltdb-shipper` index store with table names set to `<configured-tsdb-table-prefix>`+`backup_`+`<table-number>`.
This is the simplest option that I can come up with without maintaining a lot of code and we can simply drop the support before marking `tsdb` as production ready.
The rollback/recovery plan would just be to change the schema config to use `boltdb-shipper` as index store with `<configured-tsdb-table-prefix>`+`backup_` as prefix like below:
**tsdb …
> tsdb: boltdb shipper backup store tsdb

- pkg/ruler/config.go
- pkg/ruler/config_test.go
- pkg/ruler/ruler.go
To be backward compatible with single client config.
```
ts=2022-09-14T08:24:04.549961234Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with:  10.132.18.167:7946"                                                                                                                     │
│ panic: assignment to entry in nil map                                                                                                                                                                                                                      │
│ goroutine 1 [running]: …
```
> fix(ruler): Initialize multi remote clients config

- production/helm/loki/values.yaml
There is a typo for the key `limits_config` in the helm values file. The helm chart does not follow the documentation.
Fixes issue in merged pull request #7055
**Checklist**
> Helm: Fix limits_config key in helm values file

- docs/sources/operations/request-validation-rate-limits.md
This PR adds documentation for the various validation & rate-limit errors that can occur when sending logs to Loki.
N/A
**Checklist**
> Document validation & rate-limit errors

- production/helm/loki/Chart.yaml
- production/helm/loki/README.md
- production/helm/loki/README.md.gotmpl
- production/helm/loki/templates/read/statefulset-read.yaml
- production/helm/loki/templates/secret-license.yaml
- production/helm/loki/templates/single-binary/statefulset.yaml
- production/helm/loki/templates/write/statefulset-write.yaml
Signed-off-by: CAJNA Jarod <contact@jarodcajna.fr>
Update references from:
```
.Values.useExternalLicense
.Values.externalLicenseName
```
to
```
.Values.enterprise.useExternalLicense
.Values.enterprise.externalLicenseName
```
Fixes #7171 
-->
**Checklist**
> Helm: Fix ExternalLicence

- docs/sources/logql/template_functions.md
Pipelines are already defined in L18-19
**Checklist**
> Docs: remove redundant section in Template functions
