docs/sources/fundamentals/labels.md

**What this PR does / why we need it**: There is currently a broken link leading to 404 in Loki documentation.
**Checklist**

Documentation: Fix broken link

---

production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/values.yaml

bumped GEL version in Loki helm chart to v1.5.2

---

pkg/logcli/query/query.go

The --remote-schema option didn't work as validation would be called before the remote schema was loaded. An error about a missing schema section is the result. This was tested by running against a remote bucket containing a schemaconfig.yaml file with a local config file that does not contain a schema config section.
**Checklist**

Logcli: load remote schema before validation

---

pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go

These debug messages are a slightly misleading and appear too frequent.
**Checklist**

Remove deletion filter debug log messages

---

operator/CHANGELOG.md
operator/internal/manifests/gateway.go
operator/internal/manifests/gateway_test.go

Adds support for the ruler API in the lokistack-gateway.
**Checklist**

operator: Expose Loki Ruler API via the lokistack-gateway

---

operator/bundle/metadata/properties.yaml

* updates maxOpenShiftVersion to 4.12
* 
Fixes [#<issue number>](https://issues.redhat.com/browse/LOG-3119)
**Checklist**

operator: Enable subscriptions on OpenShift 4.12

---

pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_manager_test.go
pkg/storage/stores/indexshipper/compactor/deletion/request_handler.go
pkg/storage/stores/indexshipper/compactor/deletion/request_handler_test.go

Log the request ID when a new delete request is created. 
**Checklist**

Log delete request ID upon creation

---

CHANGELOG.md
docs/sources/configuration/_index.md
pkg/storage/chunk/cache/redis_client.go

Add support for username to redis cache configuration
**Checklist**

Add support for username to redis cache configuration

---

production/docker/config/loki.yaml
production/docker/docker-compose.yaml

The `production/docker` docker-compose setup was broken because of a missing configuration.
N/A
I also updated Grafana to its latest release to work around https://github.com/grafana/grafana/issues/54535
**Checklist**

Add compactor_address to fix startup

---

integration/cluster/cluster.go
integration/loki_micro_services_delete_test.go
integration/loki_micro_services_test.go
integration/loki_simple_scalable_test.go
integration/loki_single_binary_test.go
pkg/loki/modules.go

Allow the OS kernel to decide what's an open port instead of trying to guess

Fix Flaky Integration Tests

---

CHANGELOG.md
clients/pkg/promtail/server/server.go
docs/sources/clients/promtail/configuration.md
docs/sources/configuration/_index.md

add changelog for https://github.com/grafana/loki/pull/7247
Fixes https://github.com/grafana/loki/pull/7247
**Checklist**

add promtail reload changelog and doc

---

pkg/distributor/distributor_test.go

Use eventually for async tests

Fix Flaky Distributor Test

---

docs/sources/logql/analyzer/script.js

pointed unreleased docs(`next`) to logql-analyzer that is built from main branch

[docs: logql-analyzer] changed url for main branch

---

docs/sources/operations/storage/_index.md

This should make it easier for users to set the proper policies for their S3 storage.
Relates to #7403
**Checklist**

Provide example policy for S3 storage.

---

.drone/drone.jsonnet
.drone/drone.yml
Makefile
cmd/logql-analyzer/Dockerfile
cmd/logql-analyzer/docker-compose.yaml
cmd/logql-analyzer/main.go
pkg/logql/log/labels.go
pkg/logql/log/pipeline.go
pkg/logqlanalyzer/analyzer.go
pkg/logqlanalyzer/analyzer_test.go
pkg/logqlanalyzer/http.go

backport of : 
* https://github.com/grafana/loki/pull/7366
* https://github.com/grafana/loki/pull/6171

[release-2.6.x] auto-deploy on Tag or Main

---

go.mod
go.sum
vendor/github.com/hpcloud/tail/tail.go
vendor/github.com/hpcloud/tail/watch/file_posix.go
vendor/github.com/hpcloud/tail/watch/file_windows.go
vendor/github.com/hpcloud/tail/watch/inotify.go
vendor/github.com/hpcloud/tail/watch/polling.go
vendor/github.com/hpcloud/tail/watch/watch.go
vendor/modules.txt

Tail PR: https://github.com/grafana/tail/pull/14

Bump tail dependency to address windows locking issues

---

clients/pkg/promtail/promtail.go

In #7405 a hash function was added, but the full config was still printing.
N/A
**Checklist**

Promtail: correctly hashes the config on reload

---

operator/bundle/manifests/loki.grafana.com_alertingrules.yaml
operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/manifests/loki.grafana.com_recordingrules.yaml
operator/bundle/manifests/loki.grafana.com_rulerconfigs.yaml
operator/config/crd/bases/loki.grafana.com_rulerconfigs.yaml

This PR updates the manifests contained in the repo. This is a follow-up of #7418 .

operator: Regenerate manifests

---

docs/sources/community/governance.md

A formal vote has taken place and `liguozhong` has been accepted! :tada:

Add Li Guozhong as a maintainer

---

pkg/logql/downstream.go
pkg/logql/engine_test.go
pkg/logqlmodel/metadata/context.go
pkg/logqlmodel/metadata/context_test.go
pkg/loki/modules.go
pkg/querier/queryrange/queryrangebase/middleware.go
pkg/querier/queryrange/queryrangebase/middleware_test.go
pkg/querier/queryrange/queryrangebase/results_cache.go
pkg/util/server/middleware.go

Move middleware to someplace more sensible and incorporate feedback missed in the review for this.

Results cache fix improvements

---

CHANGELOG.md
pkg/loki/loki.go
pkg/loki/modules.go
pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client.go

Add compactor delete client tls client config

---

docs/sources/community/governance.md

Fix broken link, and link to what is to be the consistent location of maintainers per @GrafanaWriter.

Change `master` to `main` and include `.md` ext.

---

production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md

Update the Loki helm chart version after the changes made in https://github.com/grafana/loki/pull/7479
**Checklist**

Update helm chart version

---

clients/cmd/fluentd/lib/fluent/plugin/out_loki.rb

Reverts grafana/loki#7396 according to discussing on PR

Revert "fluentd: Add un-escaping of control characters in JSON"

---

docs/sources/storage/_index.md

Add documentation for https://github.com/grafana/loki/pull/7179 which added authentication using a Service Principal for Azure.
**Checklist**

Add how to connect to Azure using Service Principal

---

CHANGELOG.md

Update the 2.7 changelog to move unreleased section into 2.7.

Make 2.7.0 section

---

CHANGELOG.md

A few small fixes to changelog. Removed one entry that was just about updating docs, and reorganized a few others to the correct section.

Few small changelog changes

---

.drone/drone.yml

Fix drone signature

---

pkg/querier/queryrange/limits.go
pkg/querier/queryrange/limits_test.go
pkg/querier/queryrange/queryrangebase/results_cache.go
pkg/querier/queryrange/queryrangebase/results_cache_test.go
pkg/querier/queryrange/roundtrip.go
pkg/querier/queryrange/roundtrip_test.go

Add a way to change the userId used in caching.
**Checklist**

Add way to override userId for caching

---

pkg/logql/syntax/parser.go

Adding some extra comments for archaeological purposes

Adds extra docs to flehs out ParseLabels implementation

---

CONTRIBUTING.md

fixing minor typos in Contributing.md . This would make documents cleaner and easy to read
**Checklist**

Fixing a typo in CONTRIBUTING.md

---

docs/sources/installation/helm/install-scalable/index.md

I believe it should be "filesystem"
**Checklist**

[Docs] Typo on Helm Install Loki in Scaleable mode

---

pkg/storage/stores/series/index/caching_index_client.go

Removes a low-value debug log line that, in one recent example, can logs tens of thousands of times in a short span of time.
N/A
**Checklist**

Querier: remove expensive & low-value debug log line

---

CHANGELOG.md

we forgot to add an empty section for the next release to place changelog entries there...

added empty changelog section for the next release

---

operator/Makefile

operator: Increase lint timeout to 5m0s

---

production/ksonnet/loki-simple-scalable/example/README.md
production/ksonnet/loki-simple-scalable/example/main.jsonnet

Loki's jsonnet libs are no longer in `github.com/grafana/jsonnet-libs` repo this MR fixes that import.
Also adds some docs for utilizing the example.
I would like to add promtail into the example, if you are open to it, I can open another MR.
**Checklist**

Add docs for jsonnet SSD example

---

docs/sources/installation/helm/reference.md
production/helm/loki/values.yaml

Fixes typos in metrics-related Helm chart parameter descriptions.
**Checklist**

[Helm] fix typos in parameter descriptions

---

clients/pkg/promtail/client/client.go

batchRetries to countersWithHost

---

.github/CODEOWNERS

(Internal) See https://github.com/grafana/technical-documentation/issues/520.

Replace person with team for documentation reviews

---

docs/sources/clients/promtail/stages/template.md

It adds a more complex example for the template stage.
**Checklist**
- [x ] Reviewed the `CONTRIBUTING.md` guide
- [ x] Documentation added

Documentation: Add a more complex template example

---

MAINTAINERS.md

Update maintainers of documentation.

---

docs/sources/installation/helm/reference.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/values.yaml

I wanted to increase the querier timeout in loki, but that is currently not possible.
**Checklist**

Loki: Add querier config to loki helm

---

docs/sources/release-notes/_index.md
docs/sources/release-notes/v2-7.md

Add 2.7 release notes

---

docs/sources/upgrading/_index.md

Add note to upgrade guide for a bug fix with log query impact
Fixes #7667
**Checklist**

docs/upgrading: Add a note about windows event log fix

---

operator/README.md

Fixes the broken links in the operator's README file.
Broken links in README
**Checklist**

operator: Fix broken links in README.md

---

docs/sources/release-notes/v2-7.md

1. Tweak entry about `fifocache`
2. Also fix upgrade guide ref on release notes.
`#260 -> #270`
**Checklist**

docs(v2.7.0): Minor tweaks on 2.7 release notes

---

operator/CHANGELOG.md
operator/apis/loki/v1/lokistack_types.go
operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/manifests/loki.grafana.com_lokistacks.yaml
operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
operator/config/manifests/bases/loki-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/controllers/loki/lokistack_controller.go
operator/go.mod
operator/go.sum
operator/internal/handlers/internal/openshift/proxy.go
operator/internal/handlers/internal/openshift/proxy_test.go
operator/internal/handlers/lokistack_create_or_update.go
operator/internal/manifests/compactor.go
operator/internal/manifests/distributor.go
operator/internal/manifests/indexgateway.go
operator/internal/manifests/ingester.go
operator/internal/manifests/proxy_env.go
operator/internal/manifests/proxy_env_test.go
operator/internal/manifests/querier.go
operator/internal/manifests/query-frontend.go
operator/internal/manifests/ruler.go
operator/internal/manifests/var.go

Follow-up of #7384 for core replacement and using `mergo.Merge`
**Checklist**

operator: Refactor proxy env variables

---

production/docker/config/promtail.yaml

Just remove some spaces

---

production/loki-mixin-compiled-ssd/dashboards/loki-operational.json
production/loki-mixin-compiled/dashboards/loki-operational.json
production/loki-mixin/dashboards/dashboard-loki-operational.json

Instead of parsing all lines and filtering on `level` label, just filter by `level=error` string.
**Checklist**

[loki-mixin] Improve error logs query in operational dashboard

---

docs/sources/logql/template_functions.md

Closes the code block for timestamp so that ToLower and ToUpper become menu items
**Checklist**

Add closing code block backticks

---

.drone/drone.jsonnet
.drone/drone.yml

backport of https://github.com/grafana/loki/pull/7715

[release-2.7.x] backport of #7715 

---

production/helm/loki/docs/examples/README.md

[Docs] Fix helm loki examples links

---

docs/sources/community/contributing.md

[Docs] Typo: Fix path build promtail

---

pkg/ruler/base/api.go

This change should make it easier to detect changes to rules via the API.
Fixes #7789
**Checklist**

Log rule changes through API.

---

docs/sources/installation/helm/reference.md
production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/templates/_helpers.tpl
production/helm/loki/templates/serviceaccount.yaml
production/helm/loki/values.yaml

Support Azure Blob Storage in helm chart. See https://grafana.com/docs/loki/latest/storage/#azure-storage-account-1
**Checklist**

[Helm] Add support for azure blob storage

---

clients/pkg/promtail/targets/cloudflare/fields.go
clients/pkg/promtail/targets/lokipush/pushtargetmanager_test.go
integration/loki_micro_services_delete_test.go
pkg/logql/syntax/lex.go
pkg/logqlmodel/logqlmodel.go
pkg/logqlmodel/metadata/context_test.go
pkg/querier/queryrange/queryrangebase/middleware_test.go
pkg/querier/queryrange/queryrangebase/results_cache_test.go
pkg/storage/stores/indexshipper/compactor/client/grpc.go
pkg/storage/stores/indexshipper/compactor/client/http.go
pkg/storage/stores/indexshipper/compactor/deletion/delete_request.go
pkg/storage/stores/indexshipper/compactor/deletion/delete_requests_client.go
pkg/storage/stores/indexshipper/compactor/deletion/grpc_request_handler_test.go
pkg/storage/stores/indexshipper/compactor/generationnumber/gennumber_loader.go
pkg/util/marshal/marshal.go

I had enabled auto-merge in PR #7804, but somehow it still merged the PR without all the checks passing.
This PR fixes the failing lint and tests.

fix lint issues from PR 7804

---

docs/sources/installation/helm/reference.md
production/helm/loki/templates/provisioner/job-provisioner.yaml
production/helm/loki/templates/tokengen/job-tokengen.yaml
production/helm/loki/values.yaml

`monitoring.alerts` are not used in the Loki Helm chart. This removes it.
Furthermore, some values are referenced in the templates, but not used in the values file. This adds the default values.
Fixes #7575
https://github.com/AndersBennedsgaard/loki/blob/main/production/helm/loki/templates/single-binary/pdb.yaml#L15 should probably also be updated since `podDisruptionBudget` is not referenced in the values file. However, I am unsure what default values should be used.
https://github.com/AndersBennedsgaard/loki/blob/main/production/helm/loki/templates/networkpolicy.yaml#L124 should probably also be updated since the `loki.rulerSelectorLabels` is not a valid helper function. …

[Helm] Remove unused value and set default values explicitly

---

.circleci/config.yml
Makefile
clients/cmd/docker-driver/Dockerfile
clients/cmd/promtail/Dockerfile.cross
cmd/loki-canary/Dockerfile.cross
cmd/loki/Dockerfile.cross
cmd/loki/Dockerfile.debug
cmd/querytee/Dockerfile.cross
operator/Dockerfile.cross

Update build image references to 0.25.0

---

.drone/drone.yml
docs/sources/maintaining/release-loki-build-image.md

Follow up on #7848, where the Drone config needed to be updated as well

rerun make drone so the newest build image is used

---

pkg/logql/syntax/parser.go
pkg/ruler/base/manager.go
pkg/ruler/base/notifier.go
pkg/ruler/base/notifier_test.go
pkg/ruler/base/ruler.go

Backport: Fix alertmanager per tenant override config behavior (#7805)

---

docs/sources/clients/promtail/configuration.md

Fixes a typo in configuration.md, improves reader clarify and confidence
**Checklist**

Fixing a typo in configuration.md

---

docs/sources/operations/shuffle-sharding.md

This change fixes a small typo in case of a missing space.

fix small typo

---

cmd/logql-analyzer/main.go
docs/sources/installation/_index.md
docs/sources/installation/helm/_index.md
docs/sources/installation/helm/generate/index.md
docs/sources/installation/sizing/index.md
pkg/sizing/algorithm.go
pkg/sizing/algorithm_test.go
pkg/sizing/helm.go
pkg/sizing/http.go
pkg/sizing/node.go

The sizing tool should help to find a good cluster sizing when starting out with Loki. It's a dynamic form withing the documentation.
This pull request will be followed by help on hover.
**Checklist**

Introduce sizing tool to documentation page.

---

docs/sources/installation/helm/install-monolithic/index.md

Add missing letter to end of word.
**Checklist**

Fix typo in helm install monolithic docs

---

docs/sources/configuration/_index.md
docs/sources/configuration/index.template
pkg/ingester/wal.go
pkg/querier/querier.go
pkg/ruler/base/ruler.go
pkg/ruler/config.go

Fix documentation typos from https://github.com/grafana/loki/pull/7916#pullrequestreview-1217192817
Fixes https://github.com/grafana/loki/pull/7916#pullrequestreview-1217192817
**Checklist**

Fix documentation typos from #7916

---

docs/sources/installation/sizing/index.md
pkg/sizing/helm.go

The labels for the sizing tool require some additional description. This change introduces help text on hover.
Fixes #7889
**Checklist**

Show help tooltip on hover in sizing tool.

---

docs/sources/installation/helm/install-monolithic/index.md

Signed-off-by: mfordjody <11638005@qq.com>
Access to the wrong path
https://grafana.com/docs/loki/latest/installation/fundamentals/architecture/deployment-modes/#monolithic-mode
After repairing the path
https://grafana.com/docs/loki/latest/fundamentals/architecture/deployment-modes/#monolithic-mode
**Checklist**

fix error helm install monolithic path

---

tools/doc-generator/README.md

Add README file to doc-generator tool

Add README file to doc-generator tool

---

docs/sources/configuration/_index.md
pkg/storage/config/schema_config.go
tools/doc-generator/parse/parser.go

Update doc generator tool to validate if slice element is a root block.
Add missing `period_config` root block to doc generator tool.
**Checklist**

Add missing period_config root block to doc generator

---

CHANGELOG.md
clients/pkg/promtail/client/config.go

These configs can be used via `batchwait` and `batchsize` keys in yaml. This PR just makes it explicit via yaml tags.
Fixes #NA
We already have test to cover those keys.
https://github.com/grafana/loki/blob/kavirajk%2Fbatch-configs-make-yaml-explicit/clients/pkg/promtail/client/config_test.go#L28-L29
Also we have config pages for those keys.
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients
**Checklist**

chore(promtail): Make `batchwait` and `batchsize` config explicit with yaml tags.

---

pkg/logql/log/filter.go
pkg/logql/log/filter_test.go

Fix caseinsensitive search in filter
Fixes #7904 #7837
**Checklist**

fix(logql): fix caseinsensitive search in filter

---

production/docker/config/nginx.conf
production/docker/config/prometheus.yaml
production/docker/docker-compose.yaml

Fix Issue 6929 - Duplicate log lines querying Loki

---

docs/sources/clients/promtail/installation.md

Fix promtail installation command using helm in the docs.
None
None
**Checklist**

Docs: Fix promtail installation doc

---

docs/sources/operations/automatic-stream-sharding.md

This PR adds documentation for the new stream sharding feature.

Add stream sharding docs

---

production/helm/loki/values.yaml

See https://grafana.com/docs/mimir/latest/operators-guide/configuring/about-dns-service-discovery/ for details
Usage is documented here: https://grafana.com/docs/loki/latest/configuration/#cache_config
**Checklist**

Helm: add support for memcached client addresses

---

docs/sources/installation/helm/reference.md
production/helm/loki/reference.md.gotmpl

There is a typo...
**Checklist**

Fixed typo in Helm values docs

---

.github/workflows/publish.yml

Publish backported documentation to the v2.0.x release directory

---

.github/workflows/helm-release.yaml
production/helm/cr.yaml

More information in: https://github.com/grafana/helm-charts/pull/2107
**Checklist**

Helm: Remove signing of helm charts

---

docs/sources/installation/helm/reference.md
production/helm/loki/CHANGELOG.md
production/helm/loki/templates/single-binary/statefulset.yaml
production/helm/loki/values.yaml

Signed-off-by: Jan-Otto Kröpke <jok@cloudeteer.de>
Dev/Test scenarios, persistence can be omitted.
**Checklist**

Add toggle for persistence disk in single-binary mode

---

.drone/drone.jsonnet
.drone/drone.yml
loki-build-image/Dockerfile

The new dependencies will enable us to follow @dh1tw's [guide](https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/) to cross build Promtail *with* journald support as request in #1459.
The changes to `Makefile` will be made in a follow up.
**Checklist**

Install build dependencies to cross build promtail.

---

docs/sources/lids/0001-Introduction.md
docs/sources/lids/_index.md
docs/sources/lids/template.md

Including spelling my own surname right! :see_no_evil:

Minor fixups to LIDs

---

pkg/logql/log/pipeline_test.go

Regression introduced by #7723 which was merged around the same time

Fixing test regression

---

docs/sources/installation/istio.md

Because there is very little information on how to install loki in the istio service mesh, and I spent a good deal of time figuring it out. 
Hope it helps
**Checklist**

Documentation: Add installation instructions for Istio

---

tools/lambda-promtail/lambda-promtail/kinesis.go

lambda-promtail-: fix parse kinesis timestamp

---

docs/sources/clients/promtail/logrotation.md

This fixes
1. Missing UI link to the side panel
2. Image paths
Fixes #NA
**Checklist**

promtail: Fix title and image path on `logrotation` doc

---

production/docker-compose.yaml

Updated loki and promtail version tags to the latest.
**Checklist**

Docker compose: Update loki and promtail version tags to 2.7.1

---

pkg/storage/store_test.go

Appending to the same slice over all sub-benchmarks means you get different overhead from the first benchmark to the last as the slice gets bigger.
The accumulated slice was only used to print a log line, which we can do more neatly using `ReportMetric()`, and without creating nearly a gigabyte of garbage.
Before:
```
Benchmark_store_SelectSample/count_over_time({foo="bar"}[5m])-4                        1        5640722394 ns/op        2531730112 B/op   213464 allocs/op
Benchmark_store_SelectSample/rate({foo="bar"}[5m])-4                                   1        5719734486 ns/op        2489809096 B/op   211765 allocs/op
Benchmark_store_SelectSample/bytes_rate({foo="bar"}[5m])-4                             1        5776751945 ns/op        2609764312 B/op   212025 allocs/op …
```

Benchmark_store_SelectSample: stop accumulating results

---

docs/sources/fundamentals/architecture/rings/_index.md
docs/sources/installation/helm/reference.md
docs/sources/installation/istio.md
production/helm/loki/values.yaml

Addresses docs feedback on #4812 
- Updates page Title 
- Changes headings to sentence case
- Adds additional context for steps
- and a couple of spelling corrections in other files.

[Docs] Adding context to Istio installation.

---

.github/CODEOWNERS

Setting Julie Stickler as codeowner for docs

---

.drone/drone.yml
Makefile
clients/cmd/docker-driver/Dockerfile
clients/cmd/promtail/Dockerfile.cross
clients/cmd/promtail/Dockerfile.debug
cmd/loki-canary/Dockerfile.cross
cmd/loki/Dockerfile.cross
cmd/loki/Dockerfile.debug
cmd/querytee/Dockerfile.cross
operator/Dockerfile.cross
tools/go-version-bump.sh

Second part of updating the Loki build image
Part 1: #8278

Use Loki build image 0.27.1 in CI

---

docs/sources/installation/docker.md
docs/sources/installation/local.md
production/docker-compose.yaml
production/docker/docker-compose.yaml
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki-simple-scalable/example/main.jsonnet
production/ksonnet/loki-simple-scalable/images.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet
production/nomad/loki-distributed/README.md
production/nomad/loki-distributed/job.nomad.hcl
production/nomad/loki-simple/README.md
production/nomad/loki-simple/job.nomad.hcl
production/nomad/loki/README.md
production/nomad/loki/job.nomad.hcl

This PR updates the docs for release `2.7.2`. It ...
* ... updates the versions in the `production/` folder
* ... updates the versions in the installation docs
**Notes for reviewers**
Part 1 is PR #8287 
_This PR needs to be rebased once #8287 is merged._ ✅

Prepare release 2.7.2 - Part 2

---

pkg/querier/worker/scheduler_processor.go

When the querier acquires a connection to the frontend from it's shared pool, but the connection is closed/no longer valid/errors, said querier logs the failure and moves on. The frontend, however, will wait for the querier's response until the entire query times out. This effectively blocks a subquery from being retried and prevents the entire query itself from succeeding. Furthermore, the query frontend will retain partial results in memory while waiting for the timeout.
I've added retry+backoff support to this operation in an attempt to minimize the likelihood of this happening.

retry+backoff querier->qf response

---

CHANGELOG.md
docs/sources/installation/docker.md
docs/sources/release-notes/v2-7.md
production/docker-compose.yaml
production/docker/docker-compose.yaml
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki-simple-scalable/example/main.jsonnet
production/ksonnet/loki-simple-scalable/images.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet
production/nomad/loki-distributed/README.md
production/nomad/loki-distributed/job.nomad.hcl
production/nomad/loki-simple/README.md
production/nomad/loki-simple/job.nomad.hcl
production/nomad/loki/README.md
production/nomad/loki/job.nomad.hcl

To reflect current version in documentation and deployment files.
* CHANGELOG and release notes for release 2.7.2
* Helm and jsonnet deployment files

Reflect release 2.7.2 on main branch

---

LICENSING.md
pkg/push/LICENSE

Loki: add apache2 license to newly refactored push module

---

go.mod
vendor/modules.txt

update pkg/push version which is available after merging the initial PR https://github.com/grafana/loki/pull/8259
**Checklist**

[chore] update pkg/push version

---

docs/sources/installation/helm/reference.md
production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/values.yaml

Updates helm stuff for the new GEL release

update helm for GEL 1.6.1

---

operator/CHANGELOG.md
operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/config/overlays/production/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/internal/manifests/var.go

Update Loki operand to v2.7.2
**Checklist**

operator: Update operand Loki to v2.7.2

---

go.mod
go.sum
vendor/github.com/grafana/dskit/multierror/multierror.go
vendor/github.com/grafana/dskit/ring/util.go
vendor/github.com/grafana/dskit/runtimeconfig/manager.go
vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
vendor/modules.txt

Includes patch for `runtimeconfig` manager fix
https://github.com/grafana/dskit/pull/262
Fixes #NA
**Checklist**

chore: Vendor `runtimeconfig` package patch

---

production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet

Updating the ksonnet libs as part of the post-release tasks.

Bump new loki/promtail versions in ksonnet libs

---

CHANGELOG.md
docs/sources/installation/docker.md
docs/sources/release-notes/v2-7.md
production/docker-compose.yaml
production/docker/docker-compose.yaml
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki-simple-scalable/example/main.jsonnet
production/ksonnet/loki-simple-scalable/images.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet
production/nomad/loki-distributed/README.md
production/nomad/loki-distributed/job.nomad.hcl
production/nomad/loki-simple/README.md
production/nomad/loki-simple/job.nomad.hcl
production/nomad/loki/README.md
production/nomad/loki/job.nomad.hcl

Update:
* CHANGELOG
* release notes
* installation docs
* version references in production/ folder

Reflect release 2.7.3 on main branch

---

tools/dev/k3d/environments/helm-cluster/main.jsonnet
tools/dev/k3d/environments/helm-cluster/spec.json
tools/dev/k3d/jsonnetfile.lock.json

Bumps version of the GEL plugin used in the k3d env to the latest.

Update GEL plugin in k3d env to latest

---

CHANGELOG.md
clients/pkg/logentry/stages/drop.go
clients/pkg/logentry/stages/drop_test.go
docs/sources/clients/promtail/stages/drop.md
docs/sources/upgrading/_index.md

With the promtail I've encountered limitations with dropping logs ie. setting complex expressions using multiple extracted data fields. Flexible approach for dropping is presented in the Prometheus section [relabel_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) where you write regular expressions against concatenated labels.
I also noticed that currently, promtail uses options `value`(exact match) and `expression` (regexp match) with configuring the drop stage it can be later limited to just `expression` without causing confused what should be used and simplifying code.
n/a
**Checklist**

feat(promtail): add more complex options of dropping logs at the drop stage

---

docs/sources/configuration/_index.md

Fixes the alertmanager_client documentation part for the ruler . 
**Checklist**

Fix the ruler alertmanager_client documentation

---

production/ksonnet/loki/loki.libsonnet
production/ksonnet/loki/memberlist.libsonnet
production/ksonnet/loki/multi-zone.libsonnet

This PR contains changes and configuration that we needed to get things to work properly + do migrations internally.

Upstream additional multi-zone ingester jsonnet 

---

operator/CHANGELOG.md
operator/bundle/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/config/overlays/production/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/internal/manifests/var.go

Update Loki operand to v2.7.3
**Checklist**

operator: Update operand Loki to v2.7.3

---

docs/sources/installation/local.md

Fixes a numbering issue in the second procedure on the page, where bullets reset the final number back to one instead of continuing the numbering.
**Checklist**

Fix numbering issue in second procedure.

---

pkg/sizing/node.go

This PR add the information to support OVHcloud as k8s provider
N/A
See: https://www.ovhcloud.com/en-ie/public-cloud/prices/ for more information
**Checklist**

Add OVHcloud to sizing tool

---

docs/sources/installation/helm/install-scalable/index.md

Fixes broken cross reference.  
**Checklist**

Fix broken cross-reference in Helm installation.

---

docs/sources/installation/helm/reference.md
production/helm/loki/Chart.yaml
production/helm/loki/templates/backend/statefulset-backend.yaml
production/helm/loki/values.yaml

This PR makes it possible configure ` podlabels` in Helm for `backend` in the same fashion as for all other components.
**Checklist**

Helm: Add podlabels to backend

---

docs/sources/installation/helm/install-scalable/index.md

Improve Helm installation instructions and add a note on how to use MinIO.
Fixes #8440

Improve installation instructions

---

pkg/usagestats/reporter.go

Remove duplicate if statement.
n.a.
**Checklist**

Usage stats reporter: fix to remove duplicate if block

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml

(cherry picked from commit ee0f46beed12f482032649966ece7fd1df7abdb5)

[release-2.6.x] Update publishing workflows to use organization secret (#8435)

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml

(cherry picked from commit ee0f46beed12f482032649966ece7fd1df7abdb5)

[release-2.7.x] Update publishing workflows to use organization secret (#8435)

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml

(cherry picked from commit ee0f46beed12f482032649966ece7fd1df7abdb5)

[release-2.5.x] Update publishing workflows to use organization secret (#8435)

---

docs/sources/installation/helm/install-scalable/index.md

Manually backporting #8430 to the 2.7.x release and fixing two typos.

Backporting fix for broken link.

---

production/nomad/loki-distributed/job.nomad.hcl

This PR fixes missing closing curly braces for service stanza in ruler and query-frontend nomad job groups.
**Checklist**

Fix missing braces for service stanza

---

operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml

Updates the LogCLI and Promtail hack addons to v2.7.3
**Checklist**

operator: Update Promtail and LogCLI addons to v2.7.3

---

tools/lambda-promtail/main.tf
tools/lambda-promtail/variables.tf
tools/lambda-promtail/versions.tf

Various fixes for the lambda-promtail terraform code
Each commit stands independently (but later ones depend on earlier ones)
**Checklist**

lambda-promtail: various terraform fixes

---

CHANGELOG.md
clients/pkg/logentry/stages/extensions.go
clients/pkg/logentry/stages/extensions_test.go
clients/pkg/logentry/stages/pipeline.go

(cherry picked from commit 43a21eac0379d7f9320cd94f2d27a3a46bd19d3f)

[release-2.7.x] fix(promtail): Make `cri` tags streams aware. (#8497)

---

production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md

Update changelog with changes from PR #8467 and bump helm chart version to 4.6.2
**Checklist**

Helm: update changelog with changes from PR #8467

---

.drone/drone.jsonnet
.drone/drone.yml

backport of https://github.com/grafana/loki/pull/8331

Helm chart auto update (#8331)

---

.drone/drone.jsonnet
.drone/drone.yml
loki-build-image/Dockerfile

Co-authored-by: Christian Haudum <christian.haudum@gmail.com>
(cherry picked from commit 272ebdec3cfab2c73628264714b1ece217af9177)

[release-2.7.x]  Update build image to go 1 20 1 and alpine 3 16 4 (#8575)

---

docs/sources/installation/docker.md
docs/sources/installation/local.md
production/docker-compose.yaml
production/docker/docker-compose.yaml
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki-simple-scalable/example/main.jsonnet
production/ksonnet/loki-simple-scalable/images.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet
production/nomad/loki-distributed/README.md
production/nomad/loki-distributed/job.nomad.hcl
production/nomad/loki-simple/README.md
production/nomad/loki-simple/job.nomad.hcl
production/nomad/loki/README.md
production/nomad/loki/job.nomad.hcl

Update references frm 2.7.{2,3} to 2.7.4

Docs: Update references from 2.7.{2,3} to 2.7.4

---

docs/sources/release-notes/v2-7.md

Docs: Add release notes for 2.7.4

---

.drone/drone.jsonnet
.drone/drone.yml

added missed binaries required to run `./tools/image-tag` script

---

pkg/ruler/base/ruler.go

Corrects a logger which was accidentally appending keys in every loop iteration, causing massive lines to be ingested 🤦 
N/A
**Checklist**

Ruler: do not keep appending logger keys

---

pkg/scheduler/queue/leafqueue.go
pkg/scheduler/queue/leafqueue_test.go
pkg/scheduler/queue/mapping.go
pkg/scheduler/queue/mapping_test.go
pkg/scheduler/queue/queue.go
pkg/scheduler/queue/tenant_queues.go

This required to make the `Mapping` work with both `TenantQueue` and `LeafQueue`. This was achieved by implementing it using generics.
**Notes to reviewer**:
Follow up PR to https://github.com/grafana/loki/pull/8691
Part of https://github.com/grafana/loki/pull/8585

Implement hierarchical LeafQueue

---

operator/CHANGELOG.md
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go

Update Loki operand to v2.7.4
**Checklist**

operator: Update Loki operand to v2.7.4

---

docs/sources/operations/scalability.md

Cherry picking c03a2912b19d07f6e34949bb3f71bd609545f9b4 from #8632 to the 2.7.x branch.

[release 2.7.x] Fixing broken link and removing out of date blog post.

---

pkg/storage/stores/series/index/table_manager.go

This makes it consistent in the repository.

chore: Fix spelling of "syncing"

---

docs/sources/clients/aws/ec2/_index.md

Fixes typos introduced in #8870

Correcting typos merged in #8870.

---

docs/sources/installation/local.md

With #6456 we started providing native packages of Loki, Promtail and logcli. They've been added to Grafana's repository in the meantime.
In order to spread the knowledge of the packages and the repo it should be documented.
Fixes #52
**Checklist**

Document how to install Loki and Promtail using APT/DNF.

---

CHANGELOG.md

Update changelog. The changes related to the 2.7.s will be backported to the release-2.7.x branch in another PR.
**Checklist**

Update changelog for 2.7.5 release

---

production/docker-compose.yaml
production/docker/docker-compose.yaml
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki-simple-scalable/example/main.jsonnet
production/ksonnet/loki-simple-scalable/images.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet
production/nomad/loki-distributed/README.md
production/nomad/loki-distributed/job.nomad.hcl
production/nomad/loki-simple/README.md
production/nomad/loki-simple/job.nomad.hcl
production/nomad/loki/job.nomad.hcl

Update version used in production scripts

---

operator/CHANGELOG.md
operator/hack/.checked-pr-template.md
operator/hack/operatorhub.sh

Minor fixes for `make operatorhub`
**Checklist**

operator: Fix makefile target operatorhub

---

docs/sources/clients/_index.md

https://github.com/alibaba/ilogtail/pull/685
ilogtail is a very popular log agent in China, with tens of millions of installations. The open source community of ilogtail has completed the integration of loki. This PR is completed as a supplement to loki doc
demo config，Type: flusher_loki
```yaml
enable: true
inputs:
- Type: file_log
LogPath: .
FilePattern: simple.log
flushers:
- Type: flusher_loki
URL: http://localhost:3100/loki/api/v1/push
ExternalLabels:
source: ilogtail
```
flusher_loki PR snapshot
**Checklist**

[doc] client : ilogtail loki integration

---

tools/diff-config.sh

I always forget this trick for diffing configs when preparing a new release so I added it to a script.

Diff configs script

---

docs/sources/clients/promtail/_index.md

The first sentence doesn't sound natural, tried to massage it to have a more natural sound. Fixed a minor typo.

typo and phrasing

---

docs/sources/community/getting-in-touch.md
docs/sources/release-notes/_index.md
docs/sources/release-notes/cadence.md

Members of our community often ask about our release cadence, so I have documented it for easy future reference.

Adding release cadence docs

---

docs/sources/alert/_index.md
docs/sources/clients/k6/write-scenario.md
docs/sources/clients/promtail/configuration.md
docs/sources/fundamentals/architecture/components/_index.md
docs/sources/installation/helm/migrate-from-distributed/index.md
docs/sources/installation/helm/reference.md
docs/sources/operations/storage/wal.md
docs/sources/storage/_index.md
docs/sources/upgrading/_index.md
production/helm/loki/values.yaml

Fixes typos and grammar. Most of them were occurrences of `it's` that should be `its`.
None
**Checklist**

Docs: Fix typos and grammar

---

docs/sources/installation/helm/reference.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/values.yaml
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet

Prepare helm and jsonnet for 2.8 release.
**Checklist**

Update helm and jsonnet for 2.8 release

---

docs/sources/maintaining/release.md

Updates the release guide to be more accurate.

I do not think we have circleci jobs anymore

---

CHANGELOG.md

Fills out the date for the 2.8 release

add 2.8 release date

---

docs/sources/release-notes/v2-8.md

These features did not actually make it into this release.

These features did not make the release

---

docs/sources/release-notes/v2-8.md

Previous was pointing to "main" which will cause confusion

Fix CHANGELOG link

---

pkg/storage/stores/tsdb/compactor_test.go

wrt https://github.com/grafana/loki/pull/9096#discussion_r1164555980

Fix comment in `buildChunkMetas ` test function

---

docs/sources/clients/promtail/_index.md

mild grammar changes
None
**Checklist**

Fixing spelling errors and incorrect units

---

docs/sources/logql/template_functions.md

- Add `eq` function
- Add example for nested if and `AND`/`OR` logic
N/A
**Checklist**

Docs: update template function

---

docs/sources/fundamentals/architecture/components/_index.md

Update a note to callout that replication factor also impacts read path behavior.
N/A
**Checklist**

Update replication factor impact to read path

---

pkg/ruler/evaluator_remote.go

We noticed that our logs contained lines like the following:
```
...msg="rule evaluation failed with non-2xx response" response_code=400 response_body="unsupported value type"
```
The `limitedBody` reader cannot be cast to a string, so the logger writes `unsupported value type` instead.
N/A
I also shortened the limited body length to 128 bytes. Let's start with this and see if it's enough; my hunch is that it will be.

Fix output of limited response body when remote rule evaluation fails

---

.drone/drone.jsonnet
.drone/drone.yml
CHANGELOG.md
docs/sources/release-notes/v2-8.md

Final pass of 2.8.1 release notes before merging to `main`.
**Checklist**

Finalize 2.8.1 changelog and release notes

---

pkg/storage/stores/tsdb/builder.go
pkg/storage/stores/tsdb/compactor.go
pkg/storage/stores/tsdb/compactor_test.go
pkg/storage/stores/tsdb/identifier.go
pkg/storage/stores/tsdb/manager.go
pkg/storage/stores/tsdb/querier_test.go
pkg/storage/stores/tsdb/single_file_index.go
pkg/storage/stores/tsdb/util_test.go
tools/tsdb/migrate-versions/main.go
tools/tsdb/migrate-versions/main_test.go

Update of https://github.com/grafana/loki/pull/9198 while @sandeepsukhani is on holiday :)

tsdb migrate versions

---

operator/CHANGELOG.md
operator/internal/manifests/ingester_test.go
operator/internal/manifests/ruler_test.go
operator/internal/manifests/var.go

Add default PodAntiAffinity to Ruler

---

operator/CHANGELOG.md
operator/Makefile
operator/bundle/community-openshift/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operator/bundle/community-openshift/manifests/loki-operator-manager-config_v1_configmap.yaml
operator/bundle/community-openshift/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
operator/bundle/community-openshift/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operator/bundle/community-openshift/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operator/bundle/community-openshift/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operator/bundle/community-openshift/manifests/loki-operator-webhook-service_v1_service.yaml
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community-openshift/manifests/loki.grafana.com_alertingrules.yaml
operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/community-openshift/manifests/loki.grafana.com_recordingrules.yaml
operator/bundle/community-openshift/manifests/loki.grafana.com_rulerconfigs.yaml
operator/bundle/community/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml
operator/bundle/community/manifests/loki-operator-manager-config_v1_configmap.yaml
operator/bundle/community/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operator/bundle/community/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml
operator/bundle/community/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
operator/bundle/community/manifests/loki-operator-webhook-service_v1_service.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki.grafana.com_alertingrules.yaml
operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/community/manifests/loki.grafana.com_recordingrules.yaml
operator/bundle/community/manifests/loki.grafana.com_rulerconfigs.yaml
operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/kustomization.yaml
operator/config/overlays/community/kustomization.yaml
operator/hack/operatorhub.sh

Prepare Community Loki Operator v0.3.0 release.
The chosen container image tag represents the last PR merged into the operator folder (See [history](https://github.com/grafana/loki/commits/main/operator)).
**Checklist**

operator: Prepare community release v0.3.0

---

.devcontainer/devcontainer.json
.drone/drone.jsonnet
.drone/drone.yml
Makefile
clients/cmd/docker-driver/Dockerfile
clients/cmd/promtail/Dockerfile
clients/cmd/promtail/Dockerfile.arm32
clients/cmd/promtail/Dockerfile.cross
clients/cmd/promtail/Dockerfile.debug
cmd/logcli/Dockerfile
cmd/logql-analyzer/Dockerfile
cmd/loki-canary/Dockerfile
cmd/loki-canary/Dockerfile.cross
cmd/loki/Dockerfile
cmd/loki/Dockerfile.cross
cmd/loki/Dockerfile.debug
cmd/migrate/Dockerfile
cmd/querytee/Dockerfile
cmd/querytee/Dockerfile.cross
docs/sources/maintaining/release-loki-build-image.md
loki-build-image/Dockerfile
operator/Dockerfile
operator/Dockerfile.cross
production/helm/loki/src/helm-test/Dockerfile
tools/dev/loki-boltdb-storage-s3/dev.dockerfile
tools/lambda-promtail/Dockerfile

https://groups.google.com/g/golang-announce/c/MEb0UyuSMsU
Also updated the build image.
---------
(cherry picked from commit f5c0fdf02873ec353a7cb4cc4f17c06431412947)
**Checklist**

Upgrade to latest security release: go1.20.4 (#9370)

---

.drone/drone.yml
CHANGELOG.md

Adds missing signature to drone
**Checklist**

Add signature missing to drone pipeline

---

CHANGELOG.md
docs/sources/installation/docker.md
examples/getting-started/docker-compose.yaml
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go
production/docker-compose.yaml
production/docker/docker-compose.yaml

Update docs and changelog with Loki 2.8.2 changes.
**Checklist**

Update docs 2.8.2

---

operator/CHANGELOG.md
operator/internal/manifests/query-frontend_test.go
operator/internal/manifests/var.go

Add default PodAntiAffinity to Query-Frontend

---

docs/sources/release-notes/v2-8.md

Add missing release notes for 2.8.2

---

docs/sources/release-notes/v2-8.md

Part of v2.8.2 release
---------
**Checklist**

Add missing release notes for 2.8.2 (#9389)

---

docs/sources/clients/promtail/_index.md

update docs to make file rotation support clearer

---

CHANGELOG.md
clients/pkg/promtail/targets/journal/journaltarget.go

(cherry picked from commit c4048a3adffc4b13957d0b3f41381277b391c56f / #9155)

Promtail: Break on iterate journal failure (#9155)

---

clients/pkg/logentry/stages/multiline.go
clients/pkg/promtail/wal/watcher.go
pkg/distributor/distributor_ring.go
pkg/iter/cache.go
pkg/iter/sample_iterator.go
pkg/loghttp/params.go

fix function name

---

operator/CHANGELOG.md
operator/internal/manifests/distributor.go
operator/internal/manifests/distributor_test.go
operator/internal/manifests/var.go

Issue: https://issues.redhat.com/browse/LOG-3850
**Checklist**

Add default TopologySpreadContraints to distributor

---

pkg/storage/chunk/cache/memcached_client_selector.go

Currently we do not have any insight when memcached clients update their server list.

Log when memcached servers are updated

---

operator/CHANGELOG.md
operator/internal/manifests/distributor_test.go
operator/internal/manifests/querier.go
operator/internal/manifests/querier_test.go

Issue: https://issues.redhat.com/browse/LOG-3851
**Checklist**

Add default TopologySpreadContraints to querier

---

docs/sources/installation/helm/monitor-and-alert/with-grafana-cloud.md

I noticed the instructions have the logs + metrics URLs swapped by mistake
Fixes N/A
**Checklist**

Fix typo in metamonitoring instructions

---

pkg/storage/stores/series_store_write.go

We have a metric which stores a count of de-duplicated chunks, this PR creates a metric to also show bytes de-duplicated
**Checklist**

Loki: also store the bytes we de-duplicate alongside the count

---

CHANGELOG.md
pkg/storage/chunk/client/openstack/swift_object_client.go

Allow the Swift Client `List()` function to return all objects that match the query.
Fixes #9360
**Checklist**

Update swift_object_client.go : Fetch all objects in List() function

---

pkg/storage/stores/indexshipper/storage/util.go

Modifies log message to report the file size.
N/A
**Checklist**

Gateway: Log file size

---

pkg/querier/queryrange/index_stats_cache.go
pkg/util/time.go
pkg/util/time_test.go

* correctly returns zero for non-overlapping data
* adds tests

Slight improvements to `GetFactorOfTime`

---

.github/pull_request_template.md

Add additional instructions for Helm charts in the pull request template.
**Checklist**

Add instructions for Helm chart updates in the pull request template

---

pkg/analytics/stats.go
pkg/analytics/stats_test.go

We discovered a bug in Phlare https://github.com/grafana/phlare/pull/706. There can be a race occuring between two different `New<Counter|Int>` calls for the same `name`.

Fix panic in `pkg/analytics`

---

docs/sources/clients/lambda-promtail/_index.md

**What this PR does / why we need it**: fix for doc typo
**Which issue(s) this PR fixes**:N/A

Fix typo on lambda-promtail docs

---

cmd/loki-canary/main.go

#8869 broke the TLS configuration for `-tls=true` in which case we'd have `-insecure=false` but no cert or ca file. The logic used to pass `nil` for the TLS config.
**Checklist**

Pass emtpy TLS config to Loki Canary client.

---

pkg/analytics/stats_test.go

I am afraid I broke main with #9502. It seem to have auto-merged with failing tests :cry:

Fix wrong error check

---

production/helm/loki/CHANGELOG.md
production/helm/loki/templates/single-binary/statefulset.yaml

This PR fix name to config checksum annotation
Fixes #9545
**Checklist**

Helm: Fix single binary checksum annotation for config.yaml

---

operator/docs/user-guides/forwarding_logs_to_gateway.md

operator: Update snippet to generate Secret for openshift-logging

---

operator/README.md

Remove production use warning from the operator main README.md
**Checklist**

operator: Remove general production use warning

---

pkg/util/time.go
pkg/util/time_test.go

Cherry pick https://github.com/grafana/loki/pull/9602

k152 frontend fix

---

CHANGELOG.md
docs/sources/query/template_functions.md
pkg/logql/log/fmt.go
pkg/logql/log/fmt_test.go

Fixes https://github.com/grafana/loki/issues/9667

add "alignLeft" and "alignRight" functions

---

docs/sources/configuration/_index.md
pkg/distributor/writefailures/cfg.go
pkg/distributor/writefailures/manager.go

backport PR #9659

---

docs/sources/configuration/_index.md
pkg/querier/queryrange/queryrangebase/results_cache.go

Follow up PR for https://github.com/grafana/loki/pull/9535#discussion_r1218167670
**Checklist**

Improve docs for empty value in cache compression config

---

docs/sources/fundamentals/architecture/components/_index.md

Update that Loki accepts out-of-order rewrites by default.

---

.github/pull_request_template.md

Includes a checklist option to the PR template about the `add-to-release-notes` label.
**Checklist**

Update PR template to include add to release notes label

---

CHANGELOG.md
integration/cluster/cluster.go
integration/loki_micro_services_delete_test.go
integration/loki_micro_services_test.go
pkg/loki/loki.go
pkg/loki/modules.go
pkg/querier/worker_service.go
pkg/scheduler/lifecycle.go
pkg/scheduler/ringmanager.go
pkg/scheduler/scheduler.go
pkg/util/cfg/dynamic.go

(cherry-picked from commit 0a5e149ea540d9b034ff7023ca6f95ce09805080 / #9471)

query-scheduler: fix query distribution in SSD mode (#9471)

---

operator/CHANGELOG.md
operator/internal/manifests/internal/sizes.go

https://issues.redhat.com/browse/LOG-4213
**Checklist**

operator: adjusts 1x.extra-small resources according to findings

---

pkg/storage/stores/indexshipper/storage/util.go

Humanize reported size of downloaded file. 
N/A
**Checklist**

Loki: Humanize downloaded file size (bytes format)

---

production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/templates/table-manager/deployment-table-manager.yaml

helm: table_manager configmap volume

---

operator/internal/manifests/internal/sizes.go

operator: fix replica count for 1x.ExtraSmall

---

cmd/migrate/main.go

This way, if an error occurs, we get as much as we can.
In some situations, not all blob data may be accessible.  For instance, in the case where we have started migration between object storage buckets, some data may be in the old bucket.  If we wanted to migrate data from the new bucket, those chunks will error with a 404, as they are in the old bucket.
This PR is so that we continue on and get all of the chunks that we can, rather than stopping with whatever error may arise.
**Checklist**

Migrate individual chunks as opposed to all chunks.  

---

pkg/util/log/log_test.go

I've noticed that the `TestLevelHandler` were flaky because the code wasn't waiting to the server to be running. Since the test is for a handler it's much simpler to call it directly with a response recorder.
**Checklist**

Replace flaky server for log level handler test.

---

pkg/distributor/distributor.go
pkg/distributor/distributor_test.go
pkg/distributor/http.go
pkg/distributor/writefailures/manager.go
pkg/ingester/stream.go
pkg/util/errors.go

Cherry-pick log-related changes to k156.

Cherry pick logs changes

---

operator/apis/loki/v1/lokistack_types.go
operator/apis/loki/v1beta1/lokistack_types.go
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
operator/docs/operator/api.md
pkg/chunkenc/memchunk.go

all: remove repetitive the

---

pkg/storage/stores/indexshipper/storage/cached_client.go
pkg/storage/stores/indexshipper/storage/cached_client_test.go

I did a mistake in returning a cached error in the code pushed in PR #9798. Fixing it in the PR with some tests.
**Checklist**

cache: fix a mistake in returning cached error in the index list cache

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml

Bundles were not regenerated in #9823 , this PR does just that.
**Checklist**

operator: Regenerate bundles after docs change

---

cmd/migrate/main.go

Migrate tool: Fetch chunks as big batch, only go one by one in case of an error

---

docs/sources/get-started/_index.md

Docs: add reference to flog CLI args

---

production/helm/loki/CHANGELOG.md

Fix the formatting for 5.8.6 in the changelog, which was bugging me too much. I have no idea why my change did anything 
N/A
**Checklist**

helm: fix formatting in CHANGELOG.md

---

.drone/drone.jsonnet
.drone/drone.yml
clients/cmd/fluent-bit/Dockerfile
clients/cmd/promtail/Dockerfile
clients/cmd/promtail/Dockerfile.arm32
clients/cmd/promtail/Dockerfile.cross
cmd/logcli/Dockerfile
cmd/logql-analyzer/Dockerfile
cmd/loki-canary/Dockerfile
cmd/loki-canary/Dockerfile.cross
cmd/loki/Dockerfile
cmd/loki/Dockerfile.cross
cmd/loki/Dockerfile.debug
cmd/migrate/Dockerfile
cmd/querytee/Dockerfile
cmd/querytee/Dockerfile.cross
loki-build-image/Dockerfile
operator/Dockerfile
operator/Dockerfile.cross
operator/calculator.Dockerfile
tools/lambda-promtail/Dockerfile

Update the go version. Another PR will follow that uses the new build image

Update go version to 1.20.6

---

.drone/drone.yml
Makefile
clients/cmd/docker-driver/Dockerfile
clients/cmd/promtail/Dockerfile.cross
clients/cmd/promtail/Dockerfile.debug
cmd/loki-canary/Dockerfile.cross
cmd/loki/Dockerfile.cross
cmd/loki/Dockerfile.debug
cmd/querytee/Dockerfile.cross
operator/Dockerfile.cross

Update go build image

---

pkg/querier/queryrange/limits.go

The `limitedRoundTripper` would spawn thousands if not millions of goroutines. However, they were mostly idle waiting for downstream calls. This would congest the Go scheduler.
A semaphore is more suitable to control concurrency as the [example](https://pkg.go.dev/golang.org/x/sync/semaphore#example-package-WorkerPool) in the documentation illustrates.
**Checklist**

Remove goroutines from limiter middleware.

---

CHANGELOG.md

Add the details of the 2.7.6 branch to the changelog
**Checklist**

Update changelog to include 2.7.6

---

docs/sources/operations/caching.md

Fixes two silly typos in caching.md
**Checklist**

docs: fixed typos in caching.md

---

.drone/drone.jsonnet
.drone/drone.yml

update drone signature

---

.github/workflows/operator-bundle.yaml

Fixing https://github.com/grafana/loki/actions/runs/5678723603
**Checklist**

Fix operator-bundle action syntax error

---

tools/image-tag

Handling `operator/v*` tags when running docker image pipelines
**Checklist**

tools: Add support for operator/v* tags

---

pkg/storage/store.go

Loki: change the prefix for the l2 chunks cache

---

clients/pkg/logentry/stages/nonindexedlabels_test.go

added additional test-case to cover match and non_indexed_labels stages together.

non_indexed_labels stage: additional test-case

---

docs/sources/operations/caching.md

Found a lost comma in the cache configuration yaml example
**Checklist**
- [ x ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ x ] Documentation added

Documentation: Remove a lost comma

---

CODEOWNERS

Add workflow files part of operators.
@periklis can you check if these are the only files related to loki-operators? To make sure CODEOWERS for operator is properly set.
**Checklist**

CODEOWNERS: Add additional files as part of loki-operators

---

CHANGELOG.md
clients/cmd/docker-driver/Dockerfile
clients/cmd/promtail/Dockerfile.debug
cmd/logcli/Dockerfile
cmd/logql-analyzer/Dockerfile
cmd/loki-canary/Dockerfile
cmd/loki-canary/Dockerfile.cross
cmd/loki/Dockerfile
cmd/loki/Dockerfile.cross
cmd/loki/Dockerfile.debug
cmd/migrate/Dockerfile
cmd/querytee/Dockerfile
cmd/querytee/Dockerfile.cross
loki-build-image/Dockerfile
production/helm/loki/src/helm-test/Dockerfile
tools/lambda-promtail/Dockerfile

Fixes #10181
Fixes Open SSL vulnerabilities
[CVE-2023-1255](https://security.alpinelinux.org/vuln/CVE-2023-1255), [CVE-2023-2650](https://security.alpinelinux.org/vuln/CVE-2023-2650), [CVE-2023-2975](https://security.alpinelinux.org/vuln/CVE-2023-2975), [CVE-2023-3446](https://security.alpinelinux.org/vuln/CVE-2023-3446), [CVE-2023-3817](https://security.alpinelinux.org/vuln/CVE-2023-3817)
Alpine Release Notes:
[3.16.7](https://www.alpinelinux.org/posts/Alpine-3.15.10-3.16.7-3.17.5-3.18.3-released.html)
[3.16.6](https://www.alpinelinux.org/posts/Alpine-3.15.9-3.16.6-3.17.4-3.18.2-released.html)
**Checklist**
`production/helm/loki/CHANGELOG.md` and …

backport security fixes to 2.7.x

---

CHANGELOG.md
docs/sources/release-notes/v2-7.md

prepare 2.7.7 release notes and changelog

Prepare changelog and release notes for 2.7.7

---

CHANGELOG.md
docs/sources/release-notes/v2-8.md

Prepares release notes and changelog for 2.8.3 which fixes a few vulnerabilities

Update changelog and release notes for 2.8.3

---

production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/templates/monitoring/pod-logs.yaml

helm: Use "loki.clusterLabel" template for PodLogs cluster label

---

production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/templates/_helpers.tpl

Use the correct name of the service inside the ingress.
The service names could be different, if release name is not loki.
**Checklist**

[helm] Use the correct name of the service inside the ingress.

---

docs/sources/send-data/promtail/_index.md

minor spelling correction
Trivial patch for grammar, updated sentence to match sentence structure used elsewhere in the docs
**Checklist**
- [ x] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)

[docs] replace use of "examplifies"

---

docs/sources/query/_index.md

Fixes https://github.com/grafana/loki/issues/10311
**Checklist**

Fixes typo: removes extra "a"

---

pkg/storage/chunk/client/congestion/congestion.go
pkg/storage/chunk/client/congestion/controller.go
pkg/storage/chunk/client/congestion/hedge.go
pkg/storage/chunk/client/congestion/interfaces.go
pkg/storage/chunk/client/congestion/retry.go

Minor logging / metric improvements to #10140

Minor fixes to congestion control mechanism

---

docs/sources/release-notes/next.md

This PR somehow overwrote the entry.
https://github.com/grafana/loki/pull/10286/files
probably some rebase issue.
**Checklist**

release-notes: Add back the entry on hedged requests improvements.

---

docs/sources/query/analyzer.md

Just fix a small typo at https://grafana.com/docs/loki/latest/logql/analyzer/  ☺️
**Checklist**

docs: fix menu title

---

cmd/loki/loki-local-config.yaml

The URL about Analytics sourcecode in the docker configuration file returns a 404.
**Which issue(s) this PR fixes**: *no issue opened, trivial fix*
**Special notes for your reviewer**: hello :wave: nice to meet you
**Checklist**

Docker: Update the analytics sourcecode URL in the docker local configuration

---

pkg/storage/chunk/client/alibaba/oss_object_client.go
pkg/storage/chunk/client/aws/s3_storage_client.go
pkg/storage/chunk/client/azure/blob_storage_client.go
pkg/storage/chunk/client/baidubce/bos_storage_client.go
pkg/storage/chunk/client/congestion/controller.go
pkg/storage/chunk/client/congestion/controller_test.go
pkg/storage/chunk/client/gcp/gcs_object_client.go
pkg/storage/chunk/client/ibmcloud/cos_object_client.go
pkg/storage/chunk/client/local/fs_object_client.go
pkg/storage/chunk/client/object_client.go
pkg/storage/chunk/client/openstack/swift_object_client.go
pkg/storage/chunk/client/testutils/inmemory_storage_client.go
pkg/storage/stores/indexshipper/storage/prefixed_object_client.go

Introduce to our `Store` interface a new function named `ObjectExists`, which can be used by external tools to validate if a given file is present on an object store without downloading the file.
N/A
**Checklist**

Storage: Introduce new "ObjectExists" API

---

docs/sources/release-notes/next.md

This PR adds important deprecations to next release notes.

Add deprecations to next release notes

---

docs/sources/clients/promtail/pipelines.md
docs/sources/clients/promtail/stages/_index.md
docs/sources/clients/promtail/stages/match.md
docs/sources/clients/promtail/stages/non_indexed_labels.md
docs/sources/get-started/architecture.md
docs/sources/get-started/labels/_index.md
docs/sources/get-started/labels/bp-labels.md
docs/sources/get-started/labels/non-indexed-labels.md
docs/sources/reference/api.md

manual backport of https://github.com/grafana/loki/pull/10073

[backport release-2.9.x] Add docs for non-indexed labels (#10073)

---

docs/sources/release-notes/next.md

Including my contributions to v2.9

Update release notes for 2.9

---

docs/sources/alert/_index.md

Adding terraform example to manager alerts and recording rules.

Add terraform example in ruler docs

---

docs/sources/alert/_index.md

Small update to change link text to be more user friendly and capitalize the company name.

[Docs] Minor update to more user friendly link text

---

CHANGELOG.md

Changelog update reflects changes going into v2.9.0
Related #10468 
**Checklist**

changelog update 2.9.0

---

docs/sources/setup/upgrade/_index.md

Upgrade guide for v2.9.0
Related: #10468 
**Checklist**

prepare upgrade guide v2.9.0

---

docs/sources/send-data/docker-driver/_index.md
docs/sources/setup/install/docker.md
examples/getting-started/docker-compose.yaml
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go
production/docker-compose.yaml
production/docker/docker-compose.yaml
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki-simple-scalable/example/main.jsonnet
production/ksonnet/loki-simple-scalable/images.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet

Images bumps and docs updates in preparation for v2.9.0
Related: #10468 
NOTE: This is on the release branch not on `main`. Will port to main post releases.
**Checklist**

Image bumps and docs upgrades for Loki v2.9.0

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go

After discussing with @periklis, decided to revert image bumps from `operator`
Related: #10468 
**Checklist**
- [ x Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)

partially revert image bumps from `operator`

---

.drone/drone.jsonnet
.drone/drone.yml

Backport 10399 to release 2.9.x

---

docs/sources/release-notes/next.md
docs/sources/release-notes/v2-9.md

#10481 backport final release notes.
**Checklist**

Backport 10481 to release 2.9.x

---

docs/sources/release-notes/next.md
docs/sources/release-notes/v2-9.md

Steven 2 9 cleanup

---

CHANGELOG.md

Adjust changelog on `main` branch post release of v2.9.0
Cleanup unreleased changes w.r.t changes went into v2.9.0
Related: #10468 
**Checklist**

post-release: Changelog adjustments on `main` branch

---

CHANGELOG.md

Follow up to #10497
Move promtail changelog to it's own section.
Fixes #NA
**Checklist**

changelog: move promtail specific entries to it's own section

---

README.md
docs/README.md

Some of the docs files have moved.  Updating links in the README now that 2.9 has been released.

update README links

---

pkg/logql/log/parser.go

https://github.com/grafana/loki/pull/10487

[k166 ] Backport `unpack` parser fix

---

pkg/logql/log/parser.go

https://github.com/grafana/loki/pull/10487

[2.9.x] Backport `unpack` parser fix

---

docs/sources/get-started/_index.md

Fix a broken alias that is generating 404 errors

Fix broken redirect

---

docs/sources/setup/upgrade/upgrade-from-2x/index.md

Hi there I was just going through some documentations to get some idea over an issue currently I am trying to resolve, it was then when I came across this typo and corrected it.

Corrected typo in index.md file

---

pkg/sizing/http.go

XSS vulnerability of fmt.Sprintf. fmt.Sprintf would reflect part of the input in the output without escaping, which causes XSS.
**Checklist**

fix xss vulnerability

---

CHANGELOG.md
docs/sources/clients/docker-driver/_index.md
docs/sources/release-notes/v2-8.md
examples/getting-started/docker-compose.yaml
production/docker-compose.yaml
production/docker/docker-compose.yaml
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet

Update our docs to reference to the newly released version v2.8.5
N/A

Add 2.8.5 references

---

docs/sources/operations/recording-rules.md
docs/sources/setup/install/helm/monitor-and-alert/with-grafana-cloud.md

Cleaning up broken links reported against the main branch.

[Docs] Fix 404s/broken links in main branch

---

CHANGELOG.md
docs/sources/release-notes/v2-8.md

We're releasing a new 2.8.5 patch. This adds references to it to our docs.
N/A

Update references to 2.8.5

---

operator/CHANGELOG.md
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go
operator/jsonnet/jsonnetfile.json
operator/jsonnet/jsonnetfile.lock.json

Update Loki operand to v2.9.1
**Checklist**

operator: Update Loki operand to v2.9.1

---

clients/pkg/promtail/targets/gcplog/pull_target_test.go

**What this PR does / why we need it**: Fix spelling error
**Which issue(s) this PR fixes**: none
**Checklist**
Not necessary:

clients/pkg/promtail/targets/gcplog: fix spelling error

---

clients/pkg/promtail/client/client.go

Fixes #10610.
**Checklist**
Not necessary:

clients/pkg/promtail/client: better error on nil metrics

---

clients/pkg/promtail/client/client.go
pkg/canary/writer/push.go

**What this PR does / why we need it**: It saves one line, and the new function
(vs. http.NewRequest) performs additional validation of the request.
**Which issue(s) this PR fixes**: None
**Special notes for your reviewer**: None
**Checklist**
Not necessary:

clients,pkg: use http.NewRequestWithContext

---

pkg/loki/modules.go
pkg/storage/chunk/client/client.go
pkg/storage/chunk/client/testutils/inmemory_storage_client.go
pkg/storage/chunk/fetcher/fetcher_test.go
pkg/storage/factory.go
pkg/storage/factory_test.go

This PR makes a clearer distinction between supported and deprecated index/chunk storage types.
There are individual commits for the different factory functions.

chore(storage): Refactor store factory

---

docs/sources/operations/recording-rules.md
docs/sources/setup/install/helm/monitor-and-alert/with-grafana-cloud.md

Cleaning up broken links reported against the latest (2.9) branch.

[Docs] Fix 404s/broken links in 2.9 branch

---

docs/sources/installation/helm/monitor-and-alert/with-grafana-cloud.md
docs/sources/operations/recording-rules.md

Cleaning up broken links reported against the 2.8 branch.

[Docs] Fix 404s/broken links in 2.8 branch

---

.drone/drone.jsonnet
.drone/drone.yml

backport #10664 to `2.8.x` branch

drone(docker-driver): Fetch tags before pushing image during release

---

docs/sources/community/maintaining/release/_index.md

Currently it looks bit wierd.
https://grafana.com/docs/loki/next/community/maintaining/
I want it to be displayed with `Releasing Grafana Loki` at top of the hierarchy. And all the steps within it. @JStickler do I need to do anything more?
Follow up to #10646 
**Checklist**

docs: Make `release` steps in `_index.md`

---

docs/sources/operations/loki-canary/_index.md
docs/sources/send-data/promtail/installation.md
docs/sources/setup/install/local.md
examples/getting-started/docker-compose.yaml
production/docker-compose.yaml
production/docker/docker-compose.yaml
production/ksonnet/loki-canary/config.libsonnet
production/ksonnet/loki-simple-scalable/example/main.jsonnet
production/ksonnet/loki-simple-scalable/images.libsonnet
production/ksonnet/loki/images.libsonnet
production/ksonnet/promtail/config.libsonnet

```
LOKI_NEW_VERSION=2.9.1 ./tools/release_update_tags.sh
```
This script was introduced as the part of release docs PR. https://github.com/grafana/loki/pull/10646
**Checklist**

chore: Missed version updates.

---

docs/sources/get-started/components.md

The page was lacking information about components and also did not contain components that were added already a long time ago.
**Checklist**

Docs: Revise components page

---

CONTRIBUTING.md
docs/README.md

Adds additional content to the README in the docs directory.
Fixes #10760

Update README file for docs

---

loki-build-image/Dockerfile
loki-build-image/README.md

Update to latest Go and Alpine version
**Checklist**

Update build image to go 1.21.2 and alpine 3.18.4

---

.drone/drone.jsonnet
.drone/drone.yml
loki-build-image/Dockerfile

I've forgot to copy the binary in https://github.com/grafana/loki/pull/10833/.
**Checklist**

Fix docker buildx install

---

pkg/logql/syntax/extractor.go
pkg/storage/stores/shipper/bloomshipper/shipper_test.go

Fix some typos, no behavioral changes.
**Checklist**

Fix some typos

---

clients/pkg/promtail/targets/gcplog/push_target_test.go
clients/pkg/promtail/targets/gcplog/target_test.go

**What this PR does / why we need it**: Previously on Mac, running these tests triggers a dialog box asking me to accept all incoming network connections. Edit the test to listen on localhost only.
Updates #10407
**Checklist**

clients/pkg/promtail/targets/gcplog: avoid listening on 0.0.0.0

---

pkg/storage/bloom/v1/TODO.md
pkg/storage/bloom/v1/archive.go
pkg/storage/bloom/v1/archive_test.go

Simple start, but helpful for building & extracting tar+gz archives over bloom block directories.

helpers for tar+gz over bloom blocks

---

integration/loki_rule_eval_test.go

These two tests are being failed randomly for very long time. And the frequency of failure increased after merging this PR
https://github.com/grafana/loki/pull/10777
After some investigation we decided to go with following approach.
1. Make this test case pass to unblocking merging PRs
2. Make sure this doesn't introduce any regression on rule evaluation
3. [Track this issue separately to make this test case more reliable.](https://github.com/grafana/loki/issues/10859)
(1) is this PR.
Changes:
1. Merge subtests (because none of those can be run separately. Rules evaluation -> needs ingestion first)
2. Increase the timeouts
**Checklist**

test(TestRuleEval): Increase timeout on this integration test

---

tools/tsdb/bloom-tester/Dockerfile
tools/tsdb/bloom-tester/Makefile
tools/tsdb/bloom-tester/lib.go
tools/tsdb/bloom-tester/lib_test.go
tools/tsdb/bloom-tester/lrucache.go
tools/tsdb/bloom-tester/main.go
tools/tsdb/bloom-tester/metrics.go
tools/tsdb/bloom-tester/readlib.go
tools/tsdb/bloom-tester/tokenizer.go
tools/tsdb/bloom-tester/tokenizer_test.go

Changes and updates to bloom-tester code

---

pkg/storage/stores/shipper/bloomshipper/shipper.go
pkg/storage/stores/shipper/bloomshipper/shipper_test.go

Initial implementation was done based on the assumption that we would use ZIP to archive the blocks. 
However, we will use `.tar.gz` archives, so, the implementation has been adjusted to use helpers from the library that allow to archive/unarchive `.tar.gz` files. 
re: https://github.com/grafana/loki/pull/10849

[BloomShipper] updated bloom shipper to extract the block using the library

---

clients/pkg/promtail/targets/syslog/syslogtarget_test.go

fixes TestSyslogTarget_TLSConfigVerifyClientCertificate which is blocking other prs from getting merged to the release branch
**Checklist**

[release-2.8.x] fix failing test 

---

production/ksonnet/loki/index-gateway.libsonnet

Otherwise the jsonnet is invalid
**Checklist**

Add local service object

---

docs/sources/release-notes/v2-9.md

[release-2.9.x] add release notes for 2.9.2

---

CHANGELOG.md

[release-2.9.x] add changelog for 2.9.2

---

CHANGELOG.md

Update the changelog on main to reflect 2.9.2 changes
**Checklist**

[Post release] release-2.9.2: update changelog

---

CHANGELOG.md

[release-2.8.x] update changelog for v2.8.6

---

docs/sources/release-notes/v2-8.md

[release-2.8.x] add release notes for 2.8.6

---

production/helm/loki/CHANGELOG.md
production/helm/loki/Chart.yaml
production/helm/loki/README.md
production/helm/loki/templates/single-binary/statefulset.yaml

helm: fix singleBinary missing anotations

---

docs/sources/get-started/deployment-modes.md
docs/sources/operations/authentication.md
docs/sources/setup/install/helm/install-scalable/_index.md
docs/sources/setup/size/_index.md

Manual backport #10958

---

docs/sources/send-data/promtail/stages/sampling.md

Fix parsing error in the doc
**Checklist**

docs: Update sampling.md

---

docs/sources/operations/authentication.md

Fix typo in Loki authentication docs

---

.github/workflows/helm-ci.yml

The previous version no longer installs.
**Checklist**

Update the helm-chart-testing action in the CI

---

docs/sources/setup/migrate/_index.md
docs/sources/setup/migrate/migrate-to-tsdb/_index.md

Adds a migration guide for moving from any of the older indexes to TSDB
**Checklist**

docs: add migration guide for tsdb

---

docs/sources/query/_index.md

Small update to conform to recent Style decision re: spelling of `time series`.
https://grafana.com/docs/writers-toolkit/write/style-guide/word-list/#t

[Style] Update timeseries to time series.

---

pkg/querier/queryrange/volume_test.go

This adds some tests around the volume middleware, which were very useful in understanding a recent issue

add tests for log volume middleware

---

docs/sources/setup/upgrade/upgrade-from-2x/index.md

There are known deficiencies in the loki helm chart upgrade guide from `2.x` to `3.x` - https://github.com/grafana/loki/issues/9427. As a first step, I would like to propose fixing few typos.
See also: https://github.com/grafana/loki/issues/9427
**Checklist**

Fix typos in helm chart upgrade guide

---

.github/workflows/doc-validator.yml

https://github.com/grafana/technical-documentation/releases/tag/doc-validator%2Fv4.0.0

Update to latest version of doc-validator

---

pkg/bloomcompactor/bloomcompactor.go
pkg/bloomcompactor/job.go
pkg/bloomcompactor/metrics.go

Addressing comments from #11154 after it was merged

Followups #11154

---

tools/lambda-promtail/main.tf

lambda-promtail: fix IAM policy for clouddwatch log stream

---

CHANGELOG.md
Makefile
pkg/logql/blocker.go
pkg/logql/blocker_test.go
pkg/logql/engine.go
pkg/logql/engine_test.go
pkg/logql/metrics.go
pkg/logql/metrics_test.go
pkg/querier/queryrange/queryrangebase/retry.go
pkg/querier/queryrange/roundtrip.go
pkg/ruler/compat.go
pkg/ruler/evaluator_jitter.go
pkg/ruler/evaluator_remote.go
pkg/util/hash_fp.go

This back-ports PR 11243 to the k177 branch
logging: Add extra metadata to inflight requests
This adds extra metadata (similar to what we have in `metrics.go`) but for queries in in-flight (both started and retrying)
Changes:
Adds following data
1. Query Hash
2. Start and End time
3. Start and End delta
4. Length of the query
5. Moved the helper util to `queryutil` package because of cyclic dependencies with `logql` package.
Find the screenshots of log entries looks like (both in `retry.go` and `roundtrip.go`)
32](https://github.com/grafana/loki/assets/3735252/177e97ed-6ee8-41dd-b088-2e4f49562ba0) ![Screenshot 2023-11-16 at 13 02 …

back-port inflight-logging: Add extra metadata to inflight requests logging 

---

pkg/compactor/compactor.go

Do not run retention loop when retention is not enabled

do not run retention loop when retention is not enabled

---

docs/sources/setup/upgrade/upgrade-from-2x/index.md

backporting #11199 to release-2.9.x branch

---

docs/sources/best-practices/_index.md

Fixes broken link to the Promtail source code.

Fix broken Promtail link

---

docs/sources/best-practices/_index.md

Fixing links that were flagged in this week's 404 and build error report.

Fixing links

---

operator/CHANGELOG.md
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go
operator/jsonnet/jsonnetfile.json
operator/jsonnet/jsonnetfile.lock.json

Update Loki operand to v2.9.3
**Checklist**

operator: Update Loki operand to v2.9.3

---

pkg/queue/queue.go

Just a minor spelling fix in a comment, no functional change.
**Checklist**

Chore: Spelling fix for linter

---

docs/sources/query/template_functions.md

Fix incorrect example
Fix incorrect example in [Template functions](https://grafana.com/docs/loki/latest/query/template_functions/)
**Checklist**

Documentation: Update template_functions.md

---

.drone/drone.jsonnet
.drone/drone.yml

This upates the loki-build-image tag for Drone so it's also published for ARM.
**Checklist**

Publish loki-build-image 0.33.0 for ARM as well.

---

CHANGELOG.md
docs/sources/release-notes/v2-8.md

Release notes for the backported fixes from the 2.8 branch
**Checklist**

Release loki v2.8.8

---

pkg/querier/queryrange/limits_test.go

I did not intend to merge this change, reverting to what it was before merging #11333

accidentally merged this from ##11333

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/var.go

Update Loki operand to v2.9.4
**Checklist**

operator: Update Loki operand to v2.9.4

---

.drone/drone.jsonnet
.drone/drone.yml

Adding the stage back after removing it in https://github.com/grafana/loki/pull/11785 to fix the test failing in main.

Add test-target-branch stage to drone again

---

.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

fix: action repo reference

---

pkg/bloomcompactor/v2_meta.go
pkg/bloomcompactor/v2controller.go
pkg/bloomcompactor/v2controller_test.go
pkg/bloomcompactor/v2spec.go
pkg/storage/bloom/v1/bounds.go
pkg/storage/bloom/v1/bounds_test.go
pkg/storage/bloom/v1/util.go
pkg/storage/stores/shipper/indexshipper/tsdb/identifier.go

This PR continues work refactoring the bloom compactor pkg and adds a bunch of utilities for keyspace manipulation/mgmt. A lot of the bloom block logic is contained here as a skeleton.
This code is not complete, but is fine to merge as we don't use this yet and should be easier to review before it gets too large.

[Bloom] Keyspace aware bloom creation, library utilities

---

docs/sources/get-started/labels/structured-metadata.md

* Rewrote description to highlight primary use case
* Added defaults for how much structured metadata can be added to log lines
* Rewrote example queries
**Checklist**

Structured metadata docs update

---

docs/sources/get-started/labels/structured-metadata.md

Manual backport for #11843

---

.github/workflows/checks.yml

The GitHub action `checks` should run on each pull request.
**Checklist**

Run GitHub action checks on pull requests against main.

---

pkg/bloomcompactor/controller.go
pkg/bloomcompactor/controller_test.go
pkg/bloomcompactor/meta.go
pkg/bloomcompactor/spec.go
pkg/bloomcompactor/spec_test.go
pkg/storage/bloom/v1/archive.go
pkg/storage/bloom/v1/archive_test.go
pkg/storage/bloom/v1/block.go
pkg/storage/bloom/v1/block_writer.go
pkg/storage/bloom/v1/bloom_tokenizer_test.go
pkg/storage/bloom/v1/bounds_test.go
pkg/storage/bloom/v1/builder_test.go
pkg/storage/bloom/v1/dedupe_test.go
pkg/storage/bloom/v1/fuse_test.go
pkg/storage/bloom/v1/index_test.go
pkg/storage/bloom/v1/iter_test.go
pkg/storage/bloom/v1/merge_test.go
pkg/storage/bloom/v1/reader.go
pkg/storage/bloom/v1/tokenizer_test.go
pkg/storage/bloom/v1/util.go
pkg/storage/bloom/v1/util_test.go
pkg/storage/stores/shipper/bloomshipper/cache.go
pkg/storage/stores/shipper/bloomshipper/client.go

Builds on top of https://github.com/grafana/loki/pull/11872, standardizing on the `bloomshipper` types `Meta` and `MetaRef`.

[Blooms] bloomshipper meta integration

---

pkg/bloomcompactor/tsdb.go
pkg/bloomcompactor/tsdb_test.go
pkg/storage/stores/shipper/indexshipper/tsdb/single_file_index.go

Builds a lazy iterator over a tsdb file for bloom construction. This is just the library utility, not the integration.

[Blooms] tsdb iterator implementation for bloom construction

---

docs/sources/setup/install/docker.md

changed first person to comply with style guide
No issue
**Checklist**

changed first person to comply with style guide

---

docs/sources/setup/install/docker.md
docs/variables.mk

Deleting old and irrelevant information
**Checklist**

Deleting old and irrelevant information

---

pkg/bloomcompactor/batch.go
pkg/bloomcompactor/spec.go
pkg/bloomcompactor/spec_test.go
pkg/storage/bloom/v1/builder.go
pkg/storage/bloom/v1/metrics.go

some better metrics, surfacing addt'l error case from underlying iterators, refactoring.

refactor(blooms): refactors `blockLoadingIter`, exposing more error cases + additional metrics

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/release-workflows.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Fixes the names of the docker images being built in the release pipeline

ci: fix docker image names

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/release-workflows.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/validate.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/workflows.jsonnet
.github/vendor/workflows
.github/workflows/check.yml
.github/workflows/conventional-commits.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml
.release-please-manifest.json
Makefile

This updates the release pipeline to `loki-release v1.11.5`, which was used to release Loki 2.8.9.

ci: update to the latest release pipeline

---

pkg/bloomgateway/bloomgateway.go
pkg/bloomgateway/bloomgateway_test.go
pkg/bloomgateway/metrics.go
pkg/bloomgateway/multiplexing.go
pkg/bloomgateway/processor.go
pkg/bloomgateway/worker.go
pkg/loki/modules.go
pkg/storage/stores/shipper/bloomshipper/cache.go
pkg/storage/stores/shipper/bloomshipper/fetcher.go
pkg/storage/stores/shipper/bloomshipper/fetcher_test.go
pkg/storage/stores/shipper/bloomshipper/metrics.go
pkg/storage/stores/shipper/bloomshipper/store.go
pkg/storage/stores/shipper/bloomshipper/store_test.go

See individual commit messages.

chore(blooms): Add more instrumentation to bloom gateway and bloom store

---

docs/sources/configure/_index.md
pkg/bloomgateway/bloomgateway.go
pkg/bloomgateway/client.go
pkg/bloomgateway/processor.go
pkg/bloomgateway/processor_test.go
pkg/loki/modules.go
pkg/storage/stores/shipper/bloomshipper/client.go
pkg/storage/stores/shipper/bloomshipper/config/config.go
pkg/storage/stores/shipper/bloomshipper/fetcher.go
pkg/storage/stores/shipper/bloomshipper/store.go
pkg/storage/stores/shipper/bloomshipper/store_test.go
pkg/validation/limits.go

See individual commit messages.

chore(blooms): Various bloom gateway fixes/improvements

---

pkg/bloomgateway/bloomgateway.go
pkg/bloomgateway/metrics.go
pkg/storage/stores/shipper/indexshipper/indexgateway/gateway.go

Some TODOs/general comments outlining things that caught my eye in the bloom-gw.

refactor(bloom-gw): todos and comments

---

pkg/bloomgateway/metrics.go
pkg/storage/stores/shipper/indexshipper/indexgateway/gateway.go

uses _seconds suffix by convention & adds more color to another todo

chore(blooms): block_query_latency_seconds rename

---

operator/calculator.Dockerfile

Follow-up for #12104, updating the builder image for `size-calculator`.
**Checklist**

fix(operator): Update Go builder for size-calculator

---

pkg/storage/stores/shipper/indexshipper/gatewayclient/gateway_client.go

We support setting custom grpc interceptors for grpc requests sent from queriers to ingesters. The interceptors are useful for setting some additional metadata in the requests. However, support for setting custom grpc interceptors is missing for grpc requests from queriers to index gateways. This PR adds support for the same.

feat: add support for setting custom grpc interceptors for requests sent to index-gateway

---

pkg/loki/modules.go

When we run queriers as a standalone service we apply some middleware for the HTTP requests supported by queriers.
We have missed applying the same middleware for series requests as what we have for other request types.
This PR fixes the issue by keeping the middlewares consistent for all the requests.

fix: fix middlewares being applied for series request when querier is running as a standalone service

---

.github/workflows/operator-reusable-hub-release.yml

chore(operator): fix typos in release workflow

---

.github/workflows/operator-reusable-hub-release.yml

chore(operator): fix typo on ocp community release

---

pkg/logql/evaluator.go
pkg/logqlmodel/stats/context.go
pkg/storage/chunk/cache/cache_gen.go
pkg/storage/chunk/client/aws/dynamodb_storage_client.go
pkg/util/metrics_helper.go

chore: fix function names in doc strings

---

pkg/ingester/instance.go
pkg/ingester/instance_test.go
pkg/logql/log/metrics_extraction.go
pkg/logql/log/pipeline.go
pkg/storage/store.go
pkg/storage/store_test.go

This conflicts with changes that will be made to a query's shard representation

chore: remove shards from wrapper signature

---

pkg/storage/bloom/v1/bloom.go
pkg/storage/bloom/v1/builder_test.go

In case the block page is not compressed, we don't need a separate decoding buffer for the compressed and the decompressed data.
Instead, the page can be loaded directly into memory without a decompression reader.
This removes memory pressure on the bloom gateways by not using buffers from the block pool.

perf(blooms): Optimize memory usage for blocks that have no compression

---

.github/workflows/operator-reusable-hub-release.yml

chore(operator): fix ocp community release

---

docs/sources/reference/api.md

The API topic was rewritten, so this is a manual backport of the two notes added in #12303.

docs: manual backport #12303

---

pkg/logql/metrics.go

Log when disable pipeline wrappers is used

fix: log state of 'disable pipeline wrappers'

---

docs/sources/release-notes/v2-9.md

We've had a couple of releases without updates to the release notes.
Fixes #12330

docs: Update release notes for recent 2.9 releases

---

pkg/bloomgateway/stats.go

Some helpers for computed fields like total duration, filter ratios in our bloom-gw logging

chore(blooms): computed fields for bloomgw stats logging

---

pkg/querier/querier.go

Just adds the pod label to the detected labels skeleton https://github.com/grafana/loki/pull/12390 as per suggestion.

feat(detected_labels): Add pod as a detected label to demo

---

Makefile

I'm not the only one who type `make docs` every time!

chore: make docs

---

.devcontainer/devcontainer.json
.drone/drone.yml
.github/workflows/check.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/three-0-release.yml
.github/workflows/three-zero-release.yml
Makefile
clients/cmd/docker-driver/Dockerfile
clients/cmd/promtail/Dockerfile.cross
clients/cmd/promtail/Dockerfile.debug
cmd/loki-canary/Dockerfile.cross
cmd/loki/Dockerfile.cross
cmd/loki/Dockerfile.debug
cmd/querytee/Dockerfile.cross
loki-build-image/Dockerfile
loki-build-image/README.md
operator/Dockerfile.cross

chore(deps): Use loki-build-image 0.33.1

---

docs/sources/_index.md

Adds a missing period from the home page. 
**Checklist**

docs: Add missing period to _index

---

.drone/drone.yml

Looks like we updated this earlier when we [bumped the build image](https://github.com/grafana/loki/pull/12464/files) but didn't sign it
**Checklist**

ci: update drone signature

---

.drone/drone.jsonnet
.drone/drone.yml
.github/workflows/promtail-windows-test.yml
.github/workflows/verify-drone.yml

still a WIP, this will move the drone job that still runs for windows promtail testing to a github action

ci: migrate windows promtail tests to github action

---

docs/sources/operations/storage/retention.md
docs/sources/release-notes/next.md
docs/sources/release-notes/v3-0.md

Manually backports the Release Notes PR (#12508) to the 3.0 branch.

docs: backporting #12508 to 30 branch

---

docs/sources/get-started/architecture.md
docs/sources/get-started/deployment-modes.md
docs/sources/get-started/quick-start.md
docs/sources/send-data/otel/_index.md

Small tweaks to page weights and menuTitle to clean up the navigation.

docs: update page weights and menutitle

---

docs/sources/alert/_index.md
docs/sources/get-started/labels/bp-labels.md
docs/sources/operations/storage/logs-deletion.md
docs/sources/operations/storage/retention.md
docs/sources/operations/storage/table-manager/_index.md
docs/sources/operations/storage/wal.md
docs/sources/reference/_index.md
docs/sources/reference/loki-http-api.md
docs/sources/release-notes/v3-0.md
docs/sources/send-data/fluentd/_index.md
docs/sources/send-data/k6/_index.md
docs/sources/send-data/k6/query-scenario.md
docs/sources/send-data/promtail/_index.md
docs/sources/send-data/promtail/configuration.md
docs/sources/setup/upgrade/_index.md
docs/sources/setup/upgrade/upgrade-to-6x/index.md

Manual backport of #12493 to the 3.0 branch.

docs: Manual backport of #12493

---

operator/CHANGELOG.md

chore(operator): cleanup changelog for release-please

---

.github/workflows/operator-check-prepare-release-commit.yml
.github/workflows/operator-release-please.yml

chore(operator): correct branch name on release-please workflows

---

operator/docs/operator/hack_operator_make_run.md

docs(operator): improved docs to run using kind

---

docs/sources/release-notes/_index.md
docs/sources/release-notes/v3-0.md

Manual backport of #12565 to 3.0 branch.

docs: manual backport #12565

---

docs/sources/operations/query-acceleration-blooms.md

Small tweak to Blooms documentation based on a conversation on Slack.

docs: delete microservices reference

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml

I discovered that the workflows are still failing....
Continues #2294
Continues https://github.com/grafana/enterprise-logs/pull/2294

docs: Update publish-technical-documentation-next.yml

---

docs/sources/setup/install/helm/install-monolithic/_index.md

Update our monolithic guide by:
- Showing a schema_config example
- Setting the deployment mode
Motivated by: https://grafana.slack.com/archives/CEPJRLQNL/p1712915014400979

docs: helm: Update monolithic guide.

---

docs/sources/visualize/grafana.md

Manual backport of #12604 to the 2.9 branch.

docs: manual backport 12604

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml

chore(operator): Update skipRange for next OpenShift release

---

pkg/storage/stores/shipper/indexshipper/tsdb/querier.go

Our `inversePostingsForMatcher` code was introduced ~2 years ago. Since then, Prometheus added some nice performance optimizations that we didn't track ([example](https://github.com/prometheus/prometheus/pull/12377)).
This PR updates our `inversePostingsForMatcher` implementation to inherit two of them, that are fast-paths and allow skipping a `LabelValues` query.
**Checklist**

perf: TSDB: Add fast-path to `inversePostingsForMatcher`

---

production/loki-mixin-compiled-ssd/dashboards/loki-logs.json
production/loki-mixin-compiled-ssd/dashboards/loki-operational.json
production/loki-mixin-compiled/dashboards/loki-logs.json
production/loki-mixin-compiled/dashboards/loki-operational.json
production/loki-mixin/dashboards/dashboard-loki-logs.json
production/loki-mixin/dashboards/dashboard-loki-operational.json

I think these got set incorrectly when I added the linting action, these are logs panels so they should be using $__auto instead of $__rate_interval

fix(mixin): dashboards $__auto fix

---

examples/getting-started/README.md

Fixes https://github.com/grafana/loki/issues/12550

fix(docs): broken link in getting started readme

---

pkg/bloomcompactor/spec.go
pkg/storage/bloom/v1/builder.go
pkg/storage/bloom/v1/metrics.go

Adds some logs + metrics to help surface properties of series while building blooms

chore(blooms): adds more instrumentation to block building

---

docs/sources/get-started/labels/structured-metadata.md

Remove a rouge "`"
**What this PR does / why we need it**: correcting a typo
none
**Checklist**

docs: Fix typo in structured-metadata.md

---

docs/sources/reference/loki-http-api.md

Adds some documentation for the new step parameter added to the patterns API.
Additional docs for #12689
**Checklist**

docs: Add info about step param for Patterns API

---

pkg/loghttp/query.go
pkg/storage/async_store.go
pkg/storage/async_store_test.go
pkg/storage/stores/shipper/indexshipper/tsdb/sharding/power.go
pkg/validation/limits.go
pkg/validation/limits_test.go

Incorporates ingester data into bounded shard planning.

feat(blooms): ingester aware bounded impl

---

pkg/bloomgateway/querier.go
pkg/logql/engine.go
pkg/querier/handler.go
pkg/querier/queryrange/downstreamer.go
pkg/querier/queryrange/limits.go
pkg/querier/queryrange/shard_resolver.go
pkg/querier/worker/scheduler_processor.go

Trying to remove some cruft from traces.

chore: reduces span footprint + double recording

---

pkg/querier/worker/scheduler_processor.go

Re-adds some bits I removed in https://github.com/grafana/loki/pull/12864 after I noticed context not propgating across scheduler<>querier boundaries

chore(instrumentation): reintroduce span propagation across scheduler boundaries

---

pkg/ruler/evaluator_remote_test.go
pkg/storage/bloom/v1/filter/partitioned.go
pkg/storage/chunk/client/grpc/grpc_server_mock_test.go

fix function names
**Checklist**

style: fix function names

---

docs/sources/setup/install/helm/install-monolithic/_index.md

Fixes issue reported via docs @ grafana email.
This update was already made in `main` as part of #12641 but needs to be published to 3.0.

docs: fix deployment mode in Helm example

---

docs/sources/get-started/labels/structured-metadata.md
docs/sources/get-started/overview.md
docs/sources/operations/loki-canary/_index.md
docs/sources/release-notes/v3-0.md
docs/sources/send-data/_index.md
docs/sources/send-data/k6/log-generation.md
docs/sources/send-data/otel/_index.md
docs/sources/send-data/promtail/_index.md
docs/sources/send-data/promtail/installation.md
docs/sources/setup/install/helm/concepts.md
docs/sources/setup/migrate/migrate-from-distributed/index.md
docs/sources/setup/migrate/migrate-to-alloy/_index.md
docs/sources/setup/migrate/migrate-to-tsdb/_index.md

Manual backport of #12502 to the 3.x branch.

docs: Update Grafana Agent to Grafana Alloy (#12602)

---

pkg/ingester/ingester.go

feat: add profile tagging to ingester

---

operator/release-please-config.json

chore(operator): update the release-please config for next release

---

pkg/ingester/owned_streams.go

added separate metrics to see the count of the streams that are not owned by the current ingester
**Checklist**

feat: improve Owned Streams feature observability 

---

docs/sources/send-data/docker-driver/configuration.md

spell and grammar corrections.
**What this PR does / why we need it**: spell and grammar corrections in the loki docker driver configuration page
**Which issue(s) this PR fixes**: None
**Special notes for your reviewer**: None
**Checklist**

docs: Update configuration.md

---

pkg/bloomgateway/client.go
pkg/bloomgateway/client_test.go
pkg/bloomgateway/multiplexing.go
pkg/bloomgateway/processor.go
pkg/bloomgateway/processor_test.go
pkg/bloomgateway/util.go
pkg/bloomgateway/util_test.go
pkg/bloomgateway/worker.go

chore(blooms): Various minor code cleanups

---

pkg/bloomgateway/util.go
pkg/bloomgateway/util_test.go

preserves logic but moves it around & adds tests

refactor(blooms): more easily testable day partitioning

---

docs/sources/release-notes/_index.md
docs/sources/release-notes/v3-1.md

Release notes for the Loki 3.1 release.

docs: Loki 3.1 release notes

---

pkg/storage/chunk/client/congestion/controller_test.go

Test is flaky, see recent failure https://github.com/grafana/loki/actions/runs/9791359516/job/27034985489?pr=13407#step:5:77
**Checklist**

test: Fix flaky congestion test

---

CHANGELOG.md

chore: Update missing entries from CHANGELOG.md

---

CHANGELOG.md

This commit prepares a 2.9.9 release using the release automation.
**Checklist**

fix: prepare 2.9.9 release

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/internal/config/build_test.go
operator/internal/manifests/internal/config/loki-config.yaml
operator/internal/manifests/var.go

Update Loki operand to `v3.1.0`
**Checklist**

feat(operator): Update Loki operand to v3.1.0

---

docs/sources/setup/upgrade/_index.md

Follow up to https://github.com/grafana/loki/pull/13421

docs: Add workaround instructions in upgrade guide for API changes

---

pkg/bloombuild/builder/builder.go
pkg/bloombuild/protos/compat.go

This adds better logging for task progress and milestones in the bloom builder.
**Checklist**

refactor(blooms): Improve task progress logging in builder

---

pkg/ingester-rf1/ring_client.go

This will allows to scale down to 1 replicas for RF1 for testing.
**Checklist**

feat: RF1 improves replication stategy to support 1 replica

---

docs/sources/get-started/labels/bp-labels.md

Fixes broken link reported in the weekly broken link report.

docs: fix broken link

---

production/helm/loki/templates/_helpers.tpl

alibabacloud oss is support in loki source [code](https://github.com/grafana/loki/blob/main/pkg/storage/chunk/client/alibaba/oss_object_client.go),but not in helm charts
**Checklist**

feat(helm): Support alibabacloud oss in helm chart

---

pkg/querier/queryrange/serialize.go

Got highly confused when looking at a trace.
**Checklist**

fix: Fixes span name of serializeRounTripper

---

pkg/storage/wal/manager_test.go

This is a no-op. It just moves some tests around and fixes inconsistent test names.
**Checklist**

chore: Clean up manager_test.go

---

pkg/querier/queryrange/roundtrip.go

We used to do this, it was removed during a change by accident.
the fixed shard factor approach here isn't the best but on really large label matchers if you do no sharding the subqueries can be too large for executing without any shards
Note: this does NOT actually limit the number of shards for the newer `bounded` shard calculations method, with this strategy the number of shards for `limited` query types will not be fixed.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be accepted unless …

chore: shard limited queries with a fixed sharding factor

---

docs/sources/send-data/alloy/examples/alloy-otel-logs.md

docs: Fixed link test

---

pkg/storage/factory.go

chore: add congestion control to AWS

---

docs/sources/send-data/fluentd/_index.md
docs/sources/setup/upgrade/upgrade-to-6x/index.md

fix some comments
fix some comments
**Checklist**

chore: fix some comments

---

docs/sources/visualize/grafana.md

The Visualize topic hasn't really been updated in two years.
* Check the existing content against the Grafana UI and make updates.
* Add links to Explore Logs now that it is in public preview and the docs are live
* Add links to Loki Mixin installation topic now that that's live

docs: Update the Visualize topic

---

.github/workflows/labeler.yml

chore(deps): Revert "chore(deps): update actions/labeler action to v5"

---

production/ksonnet/loki/common.libsonnet

Reverts grafana/loki#14123. We won't be using these.

feat: revert "feat: add functions to common.libsonnet for warpstream"

---

pkg/storage/bloom/v1/bloom_tester_test.go
pkg/storage/bloom/v1/fuse.go
pkg/storage/bloom/v1/test_util.go
pkg/storage/bloom/v1/tokenizer.go
pkg/storage/bloom/v1/tokenizer_test.go

Run `make lint format` and commit changes.

chore: Fix linter errors

---

.github/workflows/backport.yml

chore: restore backport creator workflow

---

docs/sources/release-notes/_index.md
docs/sources/release-notes/v3-1.md
docs/sources/release-notes/v3-2.md

Release Notes for Loki 3.2 release

docs: Loki 3.2 Release Notes

---

pkg/distributor/distributor.go

Testing code made it to main it seems.
cc @benclive 
**Checklist**

fix(kafka): Fixes partition selection in distributors

---

pkg/pattern/tee_service.go

Figure this metrics was prefixed by Loki twice.
**Checklist**

fix(pattern): Fixes latency metric namespace for tee to pattern

---

operator/apis/loki/v1/lokistack_types.go
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml
operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
operator/docs/operator/api.md

chore(operator): fix API documentation relative to OTEL

---

docs/sources/operations/query-acceleration-blooms.md

This is subsequent PR for https://github.com/grafana/loki/pull/14249
**Checklist**

docs: Fix link bracket for query-acceleration-blooms

---

production/ksonnet/loki/multi-zone.libsonnet

feat(jsonnet): Allow to  name prefix zoned ingesters

---

pkg/canary/reader/reader.go

Canary latency metrics report high latency every hour as a result of `tail_max_duration` configuration. As it is possible for canary to recognise this special case, and since there is no need to go through the regular behaviour of sleeping for 10 seconds (which causes the high latency reported), it makes sense to reconnect immediately.
It is related to #5086 but doesn't fix the original issue stated there. 
This PR aims to improve the metrics reported by canary.
**Checklist**
- **Note** that Promtail is considered to be feature complete, and future development for logs collection will be in [Grafana Alloy](https://github.com/grafana/alloy). As such, `feat` PRs are unlikely to be …

fix(canary): Reconnect immediately upon tail max duration

---

pkg/querier/queryrange/roundtrip.go

chore: Update for failing lint issue

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml

Based on our investigation for available downstream images on OpenShift, enabling this annotation to raise user awareness on this platform.
**Checklist**

feat(operator): Declare feature FIPS support for OpenShift only

---

CODEOWNERS

chore(operator): add JoaoBraveCoding to loki-operator owners

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml

This updates the `skipRange` annotation for the next release cycle.
[LOG-6142](https://issues.redhat.com/browse/LOG-6142)
**Checklist**

chore(operator): Update skipRange for next release

---

docs/sources/get-started/_index.md

(cherry picked from commit 5d477fb6a8ec273af64d89bbdb697bc30a341687)
manual backport of #14449 to the 3.1 branch.

docs: remove reference to Agent Flow (#14449)

---

docs/sources/setup/install/helm/install-microservices/_index.md
docs/sources/setup/install/helm/install-scalable/_index.md

This was fixed for monolithic mode, but not the other two modes.
Will close #13507 when this has merged.

docs: update Helm installation topics

---

.github/workflows/logql-analyzer.yml
.github/workflows/scripts/helm-tagged-release.sh
.github/workflows/scripts/helm-weekly-release.sh

Backport 311797442f0a402b388904ee346f4ee411e8ab03 from #14511
---
Fix the LogQL Analyzer CI
**Checklist**

ci: fix logql analyzer (backport release-3.1.x) [manual backport]

---

.github/workflows/logql-analyzer.yml
.github/workflows/scripts/helm-tagged-release.sh
.github/workflows/scripts/helm-weekly-release.sh

Backport 311797442f0a402b388904ee346f4ee411e8ab03 from #14511
---
Fix the LogQL Analyzer CI
**Checklist**

ci: fix logql analyzer (backport release-3.2.x) [manual backport]

---

docs/sources/shared/configuration.md
tools/doc-generator/parse/root_blocks.go

Formatting issue with `docs/loki/latest/configure/#named_stores_config`
**Checklist**

docs: Pre-format example for named_stores_config

---

docs/sources/release-notes/v3-1.md
docs/sources/release-notes/v3-2.md

Updates the 3.2 Release notes for 3.1.2 and 3.2.1 releases.

docs: Update release notes for 3.2.1

---

docs/sources/operations/storage/filesystem.md

This came up in a Slack conversation today.  Since this topic is now published as part of the GEL docs, decided to add a line to clarify lack of support for filesystem in production environments.

docs: support clarification for filesystem

---

docs/sources/setup/install/helm/install-microservices/_index.md
docs/sources/setup/install/helm/install-scalable/_index.md

chore: Update Helm docs regarding bloom components

---

pkg/bloombuild/builder/builder.go

This fixes a few lint errors that are currently failing CI in `main`.

fix: lint errors

---

docs/sources/setup/upgrade/_index.md

Fixes Slack URL Markdown Formatting
**Checklist**

docs: Fix Slack URL

---

docs/sources/get-started/_index.md

docs: Update _index.md #fix typos

---

operator/api/loki/v1/lokistack_types.go
operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml

fix(operator): add 1x.pico OpenShift UI dropdown menu

---

docs/sources/setup/install/helm/_index.md
docs/sources/setup/install/helm/deployment-guides/_index.md
docs/sources/setup/install/helm/deployment-guides/aws.md
docs/sources/setup/install/helm/install-microservices/_index.md
docs/sources/setup/install/helm/install-monolithic/_index.md
docs/sources/setup/install/helm/install-scalable/_index.md

Co-authored-by: Tom Glenn <289945+tomglenn@users.noreply.github.com>
Co-authored-by: Poyzan <31743851+poyzannur@users.noreply.github.com>
Co-authored-by: Jens Horstmann <jens@widgetbook.io>
(cherry picked from commit 4e4d4a962e9d1486b456693a4e951641e3ec6b3a)
manual backport of  #14517 to 3.1 branch.

docs: Deploy Loki Helm on AWS guide (#14517)

---

docs/sources/query/bp-query.md

docs: Fixing two broken links

---

.github/workflows/operator-publish-operator-hub.yml

Change was introduced in https://github.com/grafana/loki/pull/14328 but it's broken as seen by https://github.com/grafana/loki/actions/runs/11667312469/job/32484318863#step:2:7
**Checklist**

chore(operator): fix operator-publish-operator-hub.yml workflow

---

clients/pkg/logentry/stages/extensions_test.go

add missing backtick
**Checklist**

chore: add missing backtick

---

.github/workflows/helm-ci.yml

Fixes the `helm-ci` workflow, which is currently blocking all helm PRs and releases.
Fixes #14799
**Checklist**

ci: fix the helm ci

---

docs/sources/setup/install/helm/deployment-guides/aws.md

Added video + fixed config value.
**Checklist**

docs: Added video and fixed config value

---

pkg/bloombuild/planner/strategies/chunksize.go
pkg/bloombuild/planner/strategies/splitkeyspace.go
pkg/bloombuild/protos/compat_test.go

This PR
- Fixes the strategy logger
- Adds a test to convert to/from a prototask 
**Checklist**

fix(blooms): Fix strategy logger and add task test

---

.github/workflows/operator-release-please.yml
operator/docs/operator/release.md

chore(operator): CI fix image builing

---

.github/workflows/helm-ci.yml
.github/workflows/helm-release.yaml

Try the latest version of the super-linter to see if it fixes the broken helm linting. This PR is the same as https://github.com/grafana/loki/pull/15000 but from a fork, as that's when we usually see errors.
Temporary fix for #14835, but long term fix is likely making GHCR pushes work: https://github.com/grafana/helm-charts/issues/3068#issuecomment-2473690415
**Checklist**

ci: fix helm lint

---

docs/sources/get-started/labels/structured-metadata.md
docs/sources/query/query_accceleration.md

Manual backport of #15028 into 3.3 branch.

docs: update topics for Blooms (#15028)

---

docs/sources/get-started/labels/structured-metadata.md
docs/sources/operations/bloom-filters.md

Clarifying information about structured metadata after conversation with PM on Slack.

docs: Clarifying info about structured metadata, blooms

---

pkg/kafka/client/reader_client.go
pkg/kafka/partition/reader_service.go

chore: remove last mentions of ifc

---

pkg/storage/bloom/v1/filter/scalable.go
pkg/storage/stores/series/series_index_store.go
pkg/storage/stores/shipper/bloomshipper/interval.go

fix some function names in comment
fix some function names in comment
**Checklist**

chore: fix some function names in comment

---

pkg/kafka/partition/committer_test.go
pkg/kafka/partition/reader.go
pkg/kafka/partition/reader_service.go
pkg/loki/modules.go

chore: rename StdReader to KafkaReader

---

pkg/ingester/kafka_consumer.go

chore: add comments to help explain durability guarantees of the consumer

---

docs/sources/visualize/grafana.md

Updating the visualize page now that Explore Logs is GA.

docs: Update visualize page

---

docs/sources/setup/install/helm/deployment-guides/aws.md

Manual backport of #14813 to the 3.1 branch.

docs: Added video and fixed config value (#14813)

---

production/loki-mixin/dashboards/loki-writes.libsonnet

Follow up to https://github.com/grafana/loki/pull/14498#discussion_r1822134165
**Checklist**

chore(mixins): Remove redundant selector for ingesters

---

Makefile

* Organize variable at the top of the file
* Add makro `run_in_container` for running a target in the build-image container
* Replace `docker build ...` with `$(OCI_BUILD)` variable which reduces duplicating the build arguments for each command
* Format output of `help` target
**Checklist**

chore: Add structure to `Makefile`

---

docs/sources/operations/bloom-filters.md

"single scalable deployment" to "simple scalable deployment"
Corrects "single scalable deployment" to "simple scalable deployment"
Fixes # no issue opened
**Checklist**

docs: Update query-acceleration-blooms.md

---

docs/sources/get-started/components.md

Co-authored-by: Christian Haudum <christian.haudum@gmail.com>
(cherry picked from commit a412009d77de4d18ad2cb4d133338ee2b1155150)
Manual backport of #14612

docs: Update components.md #fix some typos (#14612)

---

docs/sources/operations/query-acceleration-blooms.md

Manual backport of #14544 due to file name change from #14555.

docs: Update query-acceleration-blooms.md (#14544)

---

pkg/kafka/partition/reader_service.go

refactor: kafka offset signals

---

docs/sources/setup/upgrade/_index.md

Fix for broken publication runs on my last PR (#15255).  Not sure how this got past the linter.....

docs: fixing broken admonition

---

pkg/ingester/ingester.go
pkg/kafka/partition/reader.go
pkg/kafka/partition/reader_service.go

chore: Introduce back phase for kafka delay metrics

---

docs/sources/send-data/promtail/cloud/eks/_index.md

Fixes #13877, incorrect Helm command, and a few linter errors.

docs: fixing broken command

---

.github/workflows/helm-loki-ci.yml

fix(ci): Revert "fixed `Publish Rendered Helm Chart Diff` workflow"

---

.github/workflows/helm-loki-ci.yml

fix(ci): Revert "fixed `Publish Rendered Helm Chart Diff` workflow" 

---

docs/sources/get-started/labels/_index.md
docs/sources/get-started/labels/cardinality.md

Manual backport of #15399 to 3.3 branch.

docs: Update labels, add cardinality topic (#15399)

---

pkg/limits/frontend/config.go
pkg/limits/frontend/service.go

This pull request adds the boilerplate for the new limits-frontend service.
**Checklist**

feat: add limits-frontend service

---

docs/sources/get-started/quick-start.md

Just fixing the indentation for sandbox meta tags so it parses correctly. 
**Checklist**

docs: fixed indentation for sandbox tags

---

Makefile

Updates the minor version of Go for Loki 3.2
Fixes latest CVEs.
**Checklist**

fix(deps): Update Go for Loki 3.2

---

docs/sources/shared/configuration.md
pkg/limits/frontend/client.go
pkg/limits/frontend/config.go
pkg/limits/frontend/frontend.go
pkg/loki/loki.go
pkg/loki/modules.go

This pull request registers the limits_frontend service in Loki modules.
**Checklist**

feat: create dskit service for limits_frontend

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/overlays/community-openshift/manager_related_image_patch.yaml
operator/config/overlays/community/manager_related_image_patch.yaml
operator/config/overlays/development/manager_related_image_patch.yaml
operator/config/overlays/openshift/manager_related_image_patch.yaml
operator/docs/operator/compatibility.md
operator/hack/addons_dev.yaml
operator/hack/addons_ocp.yaml
operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json
operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json
operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json
operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json
operator/internal/manifests/var.go
operator/jsonnet/jsonnetfile.json
operator/jsonnet/jsonnetfile.lock.json

Updates Loki used in operator to current latest version 3.3.2
[LOG-6554](https://issues.redhat.com/browse/LOG-6554)
**Checklist**

feat(operator): Update Loki operand to v3.3.2

---

docs/sources/setup/install/docker.md
docs/sources/setup/install/install-from-source.md
docs/sources/setup/install/local.md
docs/sources/setup/install/tanka.md

Updates install documentation with more current version info.
**Checklist**

chore(docs): Version updates for Loki install information

---

docs/sources/operations/authentication.md
docs/sources/operations/automatic-stream-sharding.md
docs/sources/operations/autoscaling_queriers.md
docs/sources/operations/blocking-queries.md
docs/sources/operations/bloom-filters.md
docs/sources/operations/caching.md
docs/sources/operations/loki-canary/_index.md
docs/sources/operations/meta-monitoring/_index.md
docs/sources/operations/meta-monitoring/mixins.md
docs/sources/operations/multi-tenancy.md
docs/sources/operations/overrides-exporter.md
docs/sources/operations/query-fairness/_index.md
docs/sources/operations/recording-rules.md
docs/sources/operations/request-validation-rate-limits.md
docs/sources/operations/scalability.md
docs/sources/operations/shuffle-sharding/_index.md
docs/sources/operations/troubleshooting.md
docs/sources/operations/upgrade.md
docs/sources/operations/zone-ingesters.md

This PR updates headings to reflect the use case for each of the features, rather than the feature itself.

docs: Update titles of pages within the "Manage" section

---

pkg/compactor/deletion/delete_requests_manager.go

We have overall delete request tracking metrics for the number of pending delete requests and the timestamp of the oldest pending delete requests. These metrics are used to alert us when we are not making any progress in processing delete requests.
Our per-tenant config lets us convert users' deletion mode to filter-only, which skips processing any of the user's delete requests.
However, we did not add this check to the metric update code, which leads to noise. This PR fixes the issue by skipping updating tracking metrics for delete requests from users whose requests are not supposed to be processed based on their tenant config.

fix: do not update delete requests tracking metrics for users whose delete requests are not supposed to be processed

---

docs/sources/operations/storage/wal.md

Fixes numbering due to incorrect indentation and resolves a couple other Linter errors while I had the file open.
Fixes #15802
Preview is here -> https://deploy-preview-loki-15874-zb444pucvq-vp.a.run.app/docs/loki/latest/operations/storage/wal/

docs: Fix WAL numbering

---

pkg/limits/frontend/frontend.go

chore: use json.NewDecoder to avoid buffering in bytes array

---

pkg/limits/frontend/frontend.go
pkg/limits/frontend/service.go
pkg/limits/frontend/service_test.go
pkg/limits/ingest_limits.go
pkg/loki/modules.go

feat(ingest-limits): Add basic metrics

---

pkg/loki/config_wrapper.go
pkg/loki/modules.go

This pull request fixes a number of missing pieces for the initialization of the Ingest Limits Frontend ring that was causing the module to fail.
**Checklist**

chore: fix missing initialization of ingest-limits-frontend-ring

---

.github/renovate.json5

chore(deps): Disable tailwind updates

---

.github/release-workflows.jsonnet
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml

Fixes https://github.com/grafana/loki/actions/runs/13121036418/job/36607684751
**Checklist**

chore(build): Only use 64bit platforms for docker driver

---

docs/sources/shared/configuration.md
pkg/dataobj/builder.go
pkg/dataobj/consumer/config.go
pkg/dataobj/consumer/partition_processor.go
pkg/dataobj/consumer/service.go
pkg/kafka/partitionring/consumer/client.go
pkg/loki/modules.go

Refactors the dataobj-consumer to utilizer tenant partitions

feat(dataobj): tenant partition consumer

---

pkg/limits/frontend/client.go
pkg/limits/frontend/client/client.go

fix(ingest-limits): Add missing GRPC interceptors

---

docs/sources/shared/configuration.md
pkg/validation/limits.go

Before merging #15982 I made a change and forgot to update the docs for it. This fixes that.
**Checklist**

docs: Fix config for stream policies mapping

---

pkg/limits/ingest_limits.go

Collect metrics for kafka requests:
- Read fetches latency
- Read Record bytes
**Checklist**

feat(ingest-limits): Add kafka request read metrics

---

go.mod
go.sum
pkg/dataobj/metastore/metastore.go
pkg/dataobj/metastore/metrics.go
vendor/github.com/thanos-io/objstore/inmem.go
vendor/github.com/thanos-io/objstore/objstore.go
vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go
vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
vendor/github.com/thanos-io/objstore/providers/s3/s3.go
vendor/modules.txt

* Handles nil previous verisions of meta store objects
* Adds success and failure metrics instead of just failures (for proportions)
* Better error disambiguation

fix(metastore): empty object corrections

---

docs/sources/setup/upgrade/_index.md

docs: add upgrade notes for 3.4.x

---

docs/sources/release-notes/v2-9.md

According to the changes from 2.9.11 to release-2.9.x:
https://github.com/grafana/loki/compare/v2.9.11...release-2.9.x
**Checklist**

docs: Release notes for 2.9.12

---

docs/sources/release-notes/v3-4.md

Updates the 3.4 Release Notes for 3.4.1.

docs: minor RN update

---

docs/sources/release-notes/v3-4.md

docs: release notes for v3.4.2

---

pkg/dataobj/querier/iter.go
pkg/dataobj/querier/metadata.go
pkg/dataobj/querier/store.go
pkg/dataobj/querier/store_test.go
pkg/loki/modules.go
pkg/querier/queryrange/querysharding.go
pkg/querier/queryrange/querysharding_test.go
pkg/querier/store_combiner.go

This PR fixes stream section index sharding which was wrong. I've also added more test to make sure we correctly shard data and added instrumentation to see dataobj querier performs.

feat(dataobj-querier): Fixes streams section sharding & instrumentation

---

pkg/dataobj/consumer/config.go
pkg/dataobj/consumer/partition_processor.go

Small fixes to be added after merged the PR https://github.com/grafana/loki/pull/16348
**Checklist**

chore: small fixes for #16348

---

operator/internal/manifests/storage/configure.go
operator/internal/manifests/storage/configure_test.go

Bring back #11708 now that #11672 is merged. Tested ✅ 
Fixes [LOG-4820](https://issues.redhat.com/browse/LOG-4820)
**Checklist**

feat(operator): Add support for Swift TLS CA configuration

---

pkg/limits/client/client.go
pkg/limits/frontend/client/client.go
tools/stream-metadata-generator/main.go

chore: rename New to NewClient

---

tools/stream-metadata-generator/main.go

This PR updates the `stream-metadata-generator` dev tool to support writing metadata records to a fixed number of partitions. The previous capability to write to dynamic set of partitions acquired from the partition-ring is kept for now until we deem it's obsolete.
**Checklist**

feat(stream-metadata-generator): Add support for static partitions

---

docs/sources/operations/loki-ui/_index.md

Updated wording around configuring Loki UI in helm vs a docker deployment.
**Checklist**

docs: fixed wording around configuration of UI 

---

pkg/querier/queryrange/downstreamer.go

The Downstreamer.For method was not properly handling context cancellation, which resulted in a flaky test: TestCancelWhileWaitingResponse.
Issue: When the parent context was canceled, the ForEachJob function would correctly detect this and stop executing, but the For method itself was blocked in a 'for range' loop waiting for all channel values to be processed and the channel to be closed. This prevented the method from returning promptly when the context was canceled.
Fix: Modified the reading loop to use a 'select' statement that checks for context cancellation and returns immediately if the context is canceled, while still processing the channel values normally if the context is not canceled. This ensures that the For method returns promptly when the parent context is canceled, even …

fix(queryrange): properly handle context cancellation in Downstreamer

---

pkg/chunkenc/memchunk_test.go

We don't use multi extractor for now and this test is flaky.
Kept the code while @trevorwhitney can investigate.

fix(memchunk): Skip a test that currently is not used in our main path

---

tools/stream-metadata-generator/main.go

feat(stream-metadata-generator): Support tenant prefix

---

pkg/limits/ingest_limits.go

chore: add comments about delete and format line length

---

docs/sources/send-data/alloy/examples/alloy-kafka-logs.md
docs/sources/send-data/alloy/examples/alloy-otel-logs.md

Fixed changes made: https://github.com/grafana/loki/pull/16289 
**Checklist**
- [] Tests updated

docs: fixed breaking tutorials

---

.github/renovate.json5

Enable auto-merge for npm dependencies
**Checklist**

chore: auto-merge npm updates

---

pkg/distributor/distributor.go

This PR adds calls to `reportDiscardedDataWithTracker()` in the Distributor when we discard logs for ingestion policy reasons which maintains consistency between `UsageTracker` and other discarded_byte metrics.
N/A
N/A
**Checklist**

fix: increment UsageTracker.DiscardedBytesAdd() for ingestion policy discards

---

Makefile

Bumps the Go version in Loki 3.3
Fixes various CVEs
**Checklist**

fix(deps): Move to Go 1.23.7

---

docs/sources/shared/configuration.md
pkg/distributor/distributor.go
pkg/distributor/distributor_test.go
pkg/loki/loki.go
pkg/loki/modules.go

This pull request enforces stream limits in distributors.
**Checklist**

feat: enforce limits in distributors

---

docs/sources/community/lids/__DRAFT__loki-mixin-configuration-improvements.md

Add a draft LIDs about improving loki mixin configurations to support multiple metric collections setup.
N/A
N/A
**Checklist**

docs(LIDs): Add Loki mixin configuration improvements draft

---

pkg/distributor/distributor.go
pkg/distributor/distributor_test.go

chore: add tests for checking limits in distributor

---

pkg/limits/frontend/service.go

chore: remove unused code

---

pkg/limits/frontend/frontend.go
pkg/limits/frontend/http.go

chore: move http.Handler to http.go

---

pkg/limits/frontend/http.go

chore: small code clean up, and removed some obvious comments

---

pkg/limits/client/client.go

We agreed a while ago to not use backend, and to just have service and service-frontend as naming conventions. This commit updates the metrics to follow that naming convention.
**Checklist**

chore: remove backend from limits metrics

---

pkg/limits/frontend/frontend.go

For more information, see https://github.com/prometheus/client_golang/issues/240#issuecomment-539743118.
**Checklist**

chore: namespace is not longer recommended, is semi-deprecated

---

pkg/limits/frontend/frontend.go
pkg/limits/frontend/frontend_test.go

Small rename of a field to make it more intuitive.
**Checklist**

chore: small rename

---

pkg/limits/frontend/frontend.go

chore: small clean up of frontend.New

---

pkg/limits/frontend/ring.go

chore: chose a better name for this method

---

pkg/limits/config.go
pkg/limits/ingest_limits.go

Just as we did for `limits/frontend`, move config into `config.go`.
**Checklist**

chore: move config to separate file config.go

---

pkg/kafka/partition/reader.go

This commit changes `loki_kafka_reader_receive_delay_seconds` from a histogram to a gauge. It doesn't make sense to plot this as a histogram, it is a single dimension stat that we want to track as it increases and decreases.
**Checklist**

feat: change loki_kafka_reader_receive_delay_seconds to gauge

---

pkg/kafka/partition/reader.go

fix: fix help message in metric

---

pkg/dataobj/querier/store.go
pkg/engine/engine.go
pkg/logql/downstream.go
pkg/logql/engine.go
pkg/logql/evaluator.go
pkg/logql/optimize.go
pkg/logql/rangemapper.go
pkg/logql/syntax/ast.go
pkg/logql/syntax/test_utils.go
pkg/logql/syntax/walk.go
pkg/logql/syntax/walk_test.go
pkg/querier/multi_tenant_querier.go
pkg/querier/queryrange/downstreamer.go
pkg/querier/queryrange/split_by_interval.go

The boolean return value indicates whether walking/traversing should be continued with child nodes.
Required for https://github.com/grafana/loki/pull/16916
This PR does not change any existing traversal behaviour.

chore(ast): Update WalkFn signature to return bool

---

docs/sources/query/metric_queries.md

Added experimental tag to aggregated_topk section
Clarifies that the approximated topk feature is experimental
N/A
**Checklist**

docs: Clarify approx_topk is an experimental feature

---

pkg/limits/frontend/frontend.go

This commit contains some metric changes to the ingest-limits-frontend. We will remove `requests_exceeds_limits_total` as it doesn't make sense here, and if we keep it, it should be tracked in the distributor.
The second small change is removing tenant from the variable names, we don't need to include the labels in the variable name.
**Checklist**

chore: some metrics changes to ingest-limits-frontend

---

pkg/storage/stores/shipper/indexshipper/tsdb/head_read.go
pkg/storage/stores/shipper/indexshipper/tsdb/index/index.go
pkg/storage/stores/shipper/indexshipper/tsdb/index/index_test.go
pkg/storage/stores/shipper/indexshipper/tsdb/querier.go
pkg/storage/stores/shipper/indexshipper/tsdb/single_file_index.go

revert: avoid copying label values from tsdb unless required (backport k249)

---

pkg/logql/bench/cmd/bench/views/run.go

The branch k250 has linter issues and is failing to create the new weekly release.
We have several SA1019, using deprecated code.
The linter output can be checked here: https://github.com/grafana/loki/actions/runs/14437465311/job/40481166303
**Checklist**

fix(lint): fix k250 linter issues

---

go.mod
go.sum
pkg/distributor/distributor.go
pkg/distributor/distributor_test.go
pkg/loghttp/push/otlp.go
pkg/logql/log/pipeline.go
pkg/push/go.mod
vendor/github.com/prometheus/otlptranslator/.gitignore
vendor/github.com/prometheus/otlptranslator/.golangci.yml
vendor/github.com/prometheus/otlptranslator/CODE_OF_CONDUCT.md
vendor/github.com/prometheus/otlptranslator/LICENSE
vendor/github.com/prometheus/otlptranslator/MAINTAINERS.md
vendor/github.com/prometheus/otlptranslator/README.md
vendor/github.com/prometheus/otlptranslator/SECURITY.md
vendor/github.com/prometheus/otlptranslator/metric_name_builder.go
vendor/github.com/prometheus/otlptranslator/normalize_label.go
vendor/github.com/prometheus/otlptranslator/strconv.go
vendor/modules.txt

Prometheus moved the otlptranslator package to prometheus/otlptranslate
https://github.com/prometheus/prometheus/pull/16240

chore(deps): Use updated prometheus/otlptranslate

---

docs/sources/release-notes/v2-9.md

Update Release Notes for 2.9.14 release.

docs: Update Release Notes for 2.9.14 release

---

docs/sources/release-notes/v3-4.md

Update Release Notes for 3.4.3 release.

docs: Update RN for 3.4.3 release

---

docs/sources/setup/size/_index.md

**What this PR does / why we need it**: 
fix a typo

docs: typo cluster size

---

pkg/engine/executor/pipeline_test.go
vendor/github.com/apache/arrow-go/v18/arrow/csv/common.go
vendor/github.com/apache/arrow-go/v18/arrow/csv/reader.go
vendor/github.com/apache/arrow-go/v18/arrow/csv/transformer.go
vendor/github.com/apache/arrow-go/v18/arrow/csv/writer.go
vendor/modules.txt

This PR introduces two new testing utilities that simplify working with Arrow records during testing:
1. `CSVToArrow`: A function that converts CSV strings into Arrow Records based on a provided schema
2. `BufferedPipeline`: A Pipeline implementation that iterates through preloaded arrow records. Works well with (1)
These utilities will make it easier to test components that consume Arrow records or Pipeline implementations.
Testing code that works with Arrow records can be verbose and complex. These utilities provide a simpler way to create test data from easily readable CSV strings.
- Converts CSV strings to Arrow Records
- Supports multiple data types (int64, float64, bool, int32, float32)
- Handles nulls via `null` placeholder in CSV
- Validates schema compatibility at parse time
- …

chore(dataobj,executor): CSV arrow batches & pipeline helpers

---

pkg/limits/frontend/cache.go
pkg/limits/frontend/cache_test.go

This commit changes the limits cache to evict items once half the TTL has elapsed since the last eviction. It is a minor performance improvement to avoid iterating the cache when there is nothing to evict.
**Checklist**

fix: evict the limits cache once half the TTL has elapsed

---

pkg/limits/frontend/ring.go
pkg/limits/frontend/ring_test.go

chore: improve the test coverage for ring.go

---

pkg/limits/frontend/ring_test.go

chore: small test fixes

---

pkg/querier/http.go

Objects in object storage usually lag behind 20-30 minutes, but to ensure that they are available, we enable the v2 engine only if the end time is earlier than 1 hour ago.

chore(engine): Only use new engine if dataobjs are available in storage

---

docs/sources/query/logcli/getting-started.md

Updates the outdated shell output in logcli docs
-
The better PR is to automate `./logcli help` and replace the md content. I think I can try on sh but I'm not sure how to integrate with git actions and stuff.
Also this updated help output was formatted with `fold` since `fmt` borked some lines.
**Checklist**

docs(logcli): update command reference

---

pkg/compactor/deletion/delete_requests_manager.go

Recut K251 with fix from PR #17469

fix: concurrent map access for processedSeries in delete requests manager (#17469)

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/release-workflows.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/install_workflow_dependencies.sh
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/validate.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/workflows.jsonnet
.github/workflows/backport.yml
.github/workflows/dependabot_reviewer.yml
.github/workflows/helm-ci.yml
.github/workflows/helm-diff-ci.yml
.github/workflows/helm-tagged-release-pr.yaml
.github/workflows/helm-weekly-release-pr.yaml
.github/workflows/images.yml
.github/workflows/lint-jsonnet.yml
.github/workflows/logql-analyzer.yml
.github/workflows/metrics-collector.yml
.github/workflows/minor-release-pr.yml
.github/workflows/nix-ci.yaml
.github/workflows/patch-release-pr.yml
.github/workflows/promtail-windows-test.yml
.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml
.github/workflows/release.yml
.github/workflows/secret-scanning.yml
.github/workflows/syft-sbom-ci.yml
.github/workflows/verify-release-workflow.yaml

chore(ci): Set checkout actions to not persist credentials

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/validate.libsonnet
.github/workflows/images.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Bump loki release to get latest security/zizmo fixes

ci: bump loki-release

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/release-workflows.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/workflows/check.yml
.github/workflows/images.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

chore(ci): Bump loki-release hash, update release-workflows

---

.github/workflows/promtail-windows-test.yml

chore(ci): Fix cache poisoning report

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/validate.libsonnet
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml
Makefile

Update loki-releae to fix id-token permissions, add Make task for bumping to latest loki release

ci: bump loki-release again

---

.github/release-workflows.jsonnet
.github/workflows/check.yml
.github/workflows/images.yml

remove id-token read from check and images

ci: remove id-token read

---

.github/workflows/backport.yml
.github/workflows/labeler.yml

Fix the gh app used in the labeler

ci: use loki-gh-app for the labeler

---

.github/release-workflows.jsonnet
.github/workflows/labeler.yml

chore(ci): update labeler permissions

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/release-workflows.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/workflows/images.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Failing [run](https://github.com/grafana/loki/actions/runs/14740205642)
**Checklist**

chore(ci): add appropriate oidc perms to publish workflow

---

.github/workflows/operator-release-please.yml

Previous [PR](https://github.com/grafana/loki/pull/17480) to fix up permissions was a bit heavy handed and rushed.  This PR fixes the permissions up correctly. (`id-token` may only be `write`).
**Checklist**

chore(ci): Fix up file changed earlier this week

---

docs/sources/operations/meta-monitoring/_index.md
docs/sources/operations/meta-monitoring/deploy.md
docs/sources/operations/meta-monitoring/mixins.md

Fixing some typos, then I can hopefully backport these changes from https://github.com/grafana/loki/pull/16835 and https://github.com/grafana/loki/pull/17496 to the 3.5 branch so that they're published.

docs: fix typos

---

pkg/limits/frontend/frontend.go

This just moves some of the methods around in the file.
**Checklist**

chore: a bit of clean up in frontend.go

---

pkg/loki/loki.go

chore: use fmt.Sprintf in readyHandler

---

pkg/loki/modules.go

chore: fix lint issues on main

---

production/helm/loki/Chart.yaml
production/helm/loki/README.md

**Checklist**
- [] Documentation added

chore: update loki 3.4.2 -> 3.5.0

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

chore(ci): Update release workflow for shell escaping

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/workflows/check.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Pulls in a fix for a variable name.
Failing run: https://github.com/grafana/loki/actions/runs/14802271174
**Checklist**

chore(ci): Pull in loki release for correct var name

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Pulls in the latest code from loki-release.
**Checklist**

chore(ci): Pull in latest loki-release code for Loki 3.5

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/workflows/check.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Pulls in the latest 2.9-specific code from `loki-release`.
**Checklist**

chore(ci): bump release code 2 9

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/main.jsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Bumps release workflows to latest, includes permissions fixes identified during GEL 3.5 release.
**Checklist**

ci: update release lib

---

pkg/limits/frontend/frontend.go

chore: update a couple comments that were out of date

---

pkg/engine/engine.go
pkg/engine/executor/executor.go
pkg/loki/modules.go
pkg/querier/http.go

chore(engine): Use configured storage bucket in execution context

---

pkg/kafka/encoding.go
pkg/limits/ingest_limits.go
tools/stream-generator/generator/kafka.go

chore: move MetadataTopic function to limits package

---

pkg/limits/stream_metadata.go

Adds helpers for working with stripe locks.
**Checklist**

chore: add helpers for acquiring stripe locks

---

pkg/dataobj/internal/dataset/reader_basic.go

Fixes a potential memory corruption bug in `reuseRowsBuffer`. Scenario that could cause this:
```
// Assume the column is sparsely polulated with non-null values
// 1. A non-null value from src[500] could be copied to dst[5] for reuse.
// 2. When the reader writes back dst[5] to src[5], we now have the same value at both src[5] and src[500]
//    This also assumes fewer than requested values are read.
// 3. This creates memory aliasing - changes to one position would affect the other
```
When reusing memory for column values, ensures the value being reused is in the same position 
in both source and destination buffers by swapping non-null values to the front. 
This prevents memory aliasing when writing back fewer values than requested.
**Which …

chore(dataobj): fixes a memory aliasing bug in dataobj reader

---

pkg/engine/engine.go
pkg/engine/executor/dataobjscan.go
pkg/engine/executor/dataobjscan_test.go
pkg/engine/executor/limit.go
pkg/engine/executor/sortmerge.go
pkg/engine/executor/sortmerge_test.go
pkg/engine/executor/util_test.go
pkg/logql/bench/bench_test.go
pkg/logql/bench/store_dataobj_v2_engine.go

non fork variant of https://github.com/grafana/loki/pull/17617

feat(engine, dataobj): logql bench wiring for new engine [non-fork]

---

pkg/limits/ingest_limits.go

This pull request deletes some unused code.
**Checklist**

chore: delete unused code

---

docs/sources/shared/configuration.md
pkg/ingester/ingester.go
pkg/ingester/kafka_consumer.go
pkg/ingester/kafka_consumer_test.go
pkg/kafka/config.go
pkg/kafka/encoding.go

chore: parallel kafka processing (#17262)

---

pkg/limits/service.go

This pull request re-instantiated the evictions counter metric.
**Checklist**

fix(limits): Fix ingest-limits eviction metric

---

pkg/limits/service.go

We should count the active streams and the total streams. The number of streams outside the window can be calculated as total - active.
**Checklist**

chore: fix metric counting active streams and total streams

---

pkg/limits/partition_lifecycler.go

Should use `quartz` for the clock like in other structs.
**Checklist**

chore: should use quartz in partition lifecycler

---

pkg/compactor/retention/retention.go

Fix main branch failing to build due to lint error.
**Checklist**

fix: fix lint failure in retention.go

---

pkg/limits/service.go
pkg/limits/store.go
pkg/limits/store_test.go

Move limits into update cond to prepare for optimizing counting active streams.
**Checklist**

chore: move limits into update cond to prepare for optimizing counting active streams

---

tools/deprecated-config-checker/checker/checker.go

Rename the function `appenPath` to `appendPath` to fix the spelling error.
Fixes #
**Checklist**

fix: Correct typo in appenPath function name

---

pkg/limits/store_bench_test.go

chore: fix lint again

---

pkg/engine/executor/sortmerge.go

If `p.inputs[i].Read()` returns a batch with 0 rows, getting the timestamp for the record would panic, because it would try to access the value of the timestamp column at position 0, which does not exist.

fix(engine): Fix out-of-bounds panic in SortMerge implementation

---

docs/sources/operations/storage/schema/_index.md

backports #17060 to the 3.4 branch

docs: backport 17060 to 3.4 branch

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/workflows/images.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml
Makefile

Updates to the latest release code, which is already in main. Also updates to the latest version of Go.
**Checklist**

fix(ci): Update release code 3.4

---

docs/sources/send-data/promtail/stages/logfmt.md

Backport #18007 to 3.5 branch.

docs: manual backport 17007

---

.github/jsonnetfile.json
.github/jsonnetfile.lock.json
.github/vendor/github.com/grafana/loki-release/workflows/build.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/common.libsonnet
.github/vendor/github.com/grafana/loki-release/workflows/release.libsonnet
.github/workflows/check.yml
.github/workflows/minor-release-pr.yml
.github/workflows/patch-release-pr.yml
.github/workflows/release.yml

Updates to the latest 2.9-specific release code.  This is a separate branch due to the differences between Loki 2.x and 3.x and the related release code, so it requires a slightly different set of code.
**Checklist**

fix(ci): Pull in latest 2.9-specific release code

---

docs/sources/release-notes/v3-4.md

Updates Release Notes for 3.4.4 patch release.

docs: Update Release Notes 3.4.4

---

pkg/loghttp/push/push.go

Cherry pick of https://github.com/grafana/loki/commit/6495be0180ec08f5dcfca1c0fd42daa6b3fb877d
**Checklist**

feat: add latency metric to k258

---

docs/sources/setup/install/helm/_index.md

Manual backport to add #18160 to 3.5 branch

docs: Add GCP to links, 3.5 branch

---

pkg/querier/http.go

Allow usage of v2 query engine for instant queries
**Checklist**

chore(engine): allow v2 engine usage by instant queries endpoint

---

production/helm/loki/ci/non-default-values.yaml

increases the test coverage in CI for the helm charts. 
**Checklist**

feat(helm): Add non-default-values.yaml to increase test coverage

---

pkg/dataobj/explorer/inspect.go

Adds info about the new pointers section to the dataobj UI
* This is pretty much identical to the other sections. I'll aim to tidy this up soon.

chore: Add pointers to dataobj-inspect UI

---

docs/sources/operations/multi-tenancy.md

Inspired by the tenant ID docs for [Mimir][mimir] and [Pyroscope][pyroscope], this change adds a section that clarifies what characters are valid tenant IDs in Loki.
[mimir]: https://github.com/grafana/mimir/blob/70d7ed181d4298685b56360fa1bec9e2c3d4f526/docs/sources/mimir/configure/about-tenant-ids.md
[pyroscope]: https://github.com/grafana/pyroscope/blob/0a97784549cd2bac8242fa5511b06ee79f658151/docs/sources/configure-server/about-tenant-ids.md
None that I know of.
- While I think we could find a better title than "Restrictions", I
think it's useful to keep it the same as in the other tools'
documentation pages.
- In the original texts, it said "150 bytes or characters". Since …

docs: Add section about restrictions on Tenant IDs

---

docs/sources/query/metric_queries.md

I added a link to this month's Loki Community Call where we talk about metric queries.

docs: Add Loki Community Call in further resources

---

tools/lambda-promtail/Dockerfile
tools/lambda-promtail/go.mod
tools/lambda-promtail/go.sum

The CI workflow was failing since a while, e.g. https://github.com/grafana/loki/actions/runs/16257626478/job/45906161654

fix(ci): Fix lambda-promtail image build

---

clients/pkg/promtail/targets/azureeventhubs/parser.go
clients/pkg/promtail/targets/docker/target.go
clients/pkg/promtail/targets/gcplog/formatter.go
clients/pkg/promtail/targets/gelf/gelftarget.go
clients/pkg/promtail/targets/heroku/target.go
clients/pkg/promtail/targets/lokipush/pushtarget.go
clients/pkg/promtail/targets/syslog/syslogtarget.go
pkg/storage/stores/series/index/schema.go
pkg/storage/stores/series/index/schema_util.go
pkg/storage/stores/series/series_store_utils.go
pkg/storage/stores/shipper/indexshipper/boltdb/compactor/iterator_test.go

chore: clarify comments in labels.Labels.Range loop

---

pkg/compactor/deletion/delete_request_batch.go
pkg/compactor/deletion/job_builder.go

chore: fix failing lint on main

---

pkg/engine/compat.go
pkg/engine/compat_test.go
pkg/engine/engine.go

The "warning" is displayed in Grafana.

chore(engine): Add warning to response when query was executed with new engine

---

production/loki-mixin/dashboards.libsonnet
production/loki-mixin/dashboards/dashboard-utils.libsonnet
production/loki-mixin/dashboards/loki-deletion-horizontally-scalable.libsonnet

Add a dashboard for monitoring deletion with a horizontally scalable compactor. I have added a config(defaulting to false) to enable the dashboard's creation.

feat(compactor HS): add a dashboard for monitoring deletion with horizontally scalable compactor

---

docs/sources/send-data/k8s-monitoring-helm/_index.md

docs(fix): Updated port expose for Alloy

---

pkg/kafka/partitionring/consumer/client_test.go

TestPartitionMonitorRebalancing was suceptible to "soft" deadlocks where both committing offsets and processing revoked partitions were waiting for the other to finish (via the WaitGroup used in the test).
In this case, "soft" deadlock refers to how some goroutines would be blocked forever, but franz-go library managed to work its way around it (by spawning other goroutines, aborting a wait on a callback, etc.)
In at least one case on CI, this deadlock appeared to be harder, where the test timed out instead.
This commit attempts to fix the problem by instead doubling down on commiting uncomitted offsets at the time partitions are revoked.
I've been running this fix in a loop for the past hour, and it no longer produces a situation where the test takes longer than 30 seconds to finish (on …

test(kafka/partitionring/consumer): fix test flakiness

---

docs/sources/shared/configuration.md
go.mod
go.sum
vendor/github.com/grafana/dskit/middleware/logging.go
vendor/modules.txt

The current main branch is failing after the update with dskit, using the latest version and building the app locally is working properly
**Checklist**

fix(deps): update dskit dependency

---

go.mod
go.sum
vendor/github.com/grafana/dskit/ring/multi_partition_instance_ring.go
vendor/modules.txt

Incorporating this fix https://github.com/grafana/dskit/pull/730
**Checklist**

fix: Update dskit to fix linux/arm build

---

docs/sources/shared/configuration.md
go.mod
go.sum
vendor/github.com/grafana/dskit/middleware/logging.go
vendor/github.com/grafana/dskit/ring/multi_partition_instance_ring.go
vendor/modules.txt

(cherry picked from commit f39fc1e6e623bc88bf4d5d8e2e0c2ca039f5967f)
**Checklist**

fix: Update dskit to fix linux/arm build (#18715)

---

pkg/distributor/http.go

With  `log_push_request` we can log all the streams a customer is pushing. This is useful to debug which streams are discarded later on. To debug logs dropped due to blocked policies on the operator end, we are resolving a printing the policy when `log_push_request` is enabled.
**Checklist**

feat: log ingestion policy when log_push_request is set

---

docs/sources/operations/storage/tsdb.md

Backport #18818 to 3.5 branch.

docs: backport link fix 3.5

---

docs/sources/reference/loki-http-api.md
docs/sources/send-data/otel/_index.md
docs/sources/send-data/otel/otel-collector-getting-started.md

Fixes #https://github.com/grafana/support-escalations/issues/15419

docs: Remove port number from OTEL endpoint

---

go.mod
go.sum
vendor/github.com/grafana/ckit/internal/gossiphttp/message.go
vendor/modules.txt

Fixing ARM 32bits build with https://github.com/grafana/ckit/pull/97
**Checklist**

fix: update ckit

---

pkg/dataobj/index/builder.go

Correctly sets metastore prefixes so they don't end up double-prefixed.

chore: fix metastore indexes being written with double prefixes

---

pkg/engine/executor/sortmerge.go

This is a follow up to https://github.com/grafana/loki/pull/18915
In the `SortMerge` batches (`arrow.Record`) where incorrectly freed (`Release()`) leading to panics (out of bounds errors), like these:
```
panic: runtime error: index out of range [36] with length 0
goroutine 131 [running]:
github.com/apache/arrow-go/v18/arrow/array.(*simpleRecord).Column(0x35c3380?, 0xc04b5295c0?)
/home/christian/sandbox/grafana/loki/vendor/github.com/apache/arrow-go/v18/arrow/array/record.go:236 +0x30
```

chore(engine): Correctly free record allocations

---

operator/internal/handlers/lokistack_enable_zone_awareness.go
operator/internal/handlers/lokistack_enable_zone_awareness_test.go
operator/internal/manifests/gateway_tenants.go
operator/internal/manifests/internal/config/options.go
operator/internal/manifests/mutate.go
operator/internal/manifests/openshift/alertingrule.go
operator/internal/manifests/openshift/recordingrule.go
operator/internal/manifests/options.go
operator/internal/manifests/rules_config_test.go

Use https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize to "modernize" the entire codebase.
Inspired by https://github.com/prometheus/prometheus/pull/17092.
**Checklist**

chore(operator): Apply modernize analyzer to the codebase

---

pkg/dataobj/index/builder.go

When the client is closed, the err returned should be a [kgo.ErrClientClosed]. However, the code will instead attempt to return ctx.Err(), which can be nil.
**Checklist**

fix: nil error returned when client closed

---

pkg/util/rangeio/rangeio.go

Introduce tracing instrumentation into rangeio.ReadRanges.
This also fixes a minor issue where range splitting would not occur when setting `MaxParallelism` to 0 or lower (which indicates to use the number of CPUs as the parallelism limit).

chore(rangeio): add tracing to rangeio.ReadRanges

---

pkg/dataobj/index/builder.go

If one fetch returns an error, all other fetches will be discarded, even if records were returned for those fetches. This leads to data loss as the records for the successful fetches will not be fetched a second time.
**Checklist**

fix: records discarded if one fetch returns error

---

pkg/limits/client/client.go

fix inconsistent function name in comment
**Checklist**

chore: fix inconsistent function name in comment

---

.github/workflows/images.yml
Makefile
go.mod

fix: Upgrade go version 1.24.6 in release-3.5.x

---

docs/sources/release-notes/v3-5.md

Updates the Release Notes for 3.5.4 patch release.

docs: Release notes for 3.5.4

---

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml
operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml
operator/config/samples/loki_v1_alertingrule.yaml

https://issues.redhat.com/browse/LOG-6782
**Checklist**

fix(operator): updated AlertingRule sample to make it comply with the validation we apply

---

docs/sources/setup/upgrade/upgrade-to-6x/index.md

Manual backport of #19152 to 3.5 branch to fix typo/

docs: Backport 19151

---

.github/workflows/operator-scorecard.yaml

chore(operator): ci change from engineerd/setup-kind to helm/kind-action

---

pkg/engine/internal/types/aggregations.go
pkg/engine/internal/types/column.go
pkg/engine/internal/types/operators.go

Attempt to fix [failing lint check on main](https://github.com/grafana/loki/actions/runs/17812437219/job/50639071727). This PR excludes that package from the linting rules.
**Checklist**

chore: exclude types package from linting rules.
