grafana/loki

docs/sources/configuration/_index.md, pkg/storage/config/store.go, pkg/storage/factory.go
With the addition of the [config generation tool](https://github.com/grafana/loki/pull/7916), a comment prefix was added for all cache types:
`Cache config for index entry writing.`
https://grafana.com/docs/loki/next/configuration/#cache_config
This appears in the description of each cache config option, and is misleading.
The likely explanation is that we have 4 different cache types who all register the same flags, and the last one got precedence
I noticed this while reviewing https://github.com/grafana/loki/pull/8852.
=> (chore): remove incorrect cache config preample

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/storage/chunk/cache/redis_client.go
Current Redis client only reads from master node, which makes master node under heavy pressure.
Usually, one or more read replicas are expected on production environments.
This PR helps to increase the utilization of read replicas.
Fixes #8811 
* The `route_randomly` option defaults to `false`, which matches the same behavior in previous versions, hence no breaking change.
* User needs to explicitly set `route_randomly` to `true` in order to use it.
* The purpose of this PR is to evenly distribute the read requests, so only [`RouteRandomly`][1] is used and not the following:
* `ReadOnly` (which only reads from read replicas)
*  `RouteByLatency` (requests probably won't be even …
=> Loki: Add route_randomly to Redis options

operator/netlify.toml
Pin go version to the operator version to get `gen-crd-api-reference-docs` work always with the linked k8s/go version deps. FWIW for the last 2 weeks we didn't have docs deploys because the default netlify image was using go1.17 and a k8s deps could not be parsed properly:
```
9:14:06 PM: (re)installing /opt/buildhome/.gimme_cache/gopath/bin/gen-crd-api-reference-docs-v0.0.3
9:14:07 PM: /opt/buildhome/.gimme_cache/gopath/bin/gen-crd-api-reference-docs-v0.0.3 -api-dir "github.com/grafana/loki/operator/apis/loki/" -config "/opt/build/repo/operator/config/docs/config.json" -template-dir "/opt/build/repo/operator/config/docs/templates" -out-file "/opt/build/repo/operator/docs/operator/api.md"
9:14:07 PM: I0321 20:14:07.293426    2144 main.go:155] …
```
=> operator: Pin go version used in netlify env

docs/sources/clients/aws/ec2/_index.md
Adding more information on what to do if `__meta_ec2_private_dns_name` doesn't match the hostname.
=> update on Running Promtail on AWS EC2 tutorial

docs/sources/logql/log_queries/_index.md, docs/sources/upgrading/_index.md, pkg/logql/log/labels.go, pkg/logql/log/metrics_extraction.go, pkg/logql/log/parser.go, pkg/logql/log/parser_hints.go, pkg/logql/log/parser_hints_test.go, pkg/logql/log/parser_test.go
In many cases we only need a few labels from a line. Because most of our parsers parse lines incrementally, we can stop parsing a line after we have all the labels we want from it.
This pr uses `ParserHints` to keep track of the number of extracted labels. It also provides a way for parsers to know when they should stop parsing.  
Notes:
- parsers had inconsistent ordering between the `ShouldExtract` call and adding the `_extracted` label to duplicates. This PR makes appending `_extracted` always happen before `ShouldExtract` to keep counts of what is extracted compared to expected labels consistent.
Next Steps:
- When the user specifies a query with a grouping containing the `_extracted` label but there is no duplicate between the passed line and labels, short circuiting will not work. …
=> Short circuit parsers

CHANGELOG.md, production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/query-frontend.libsonnet, production/ksonnet/loki/query-scheduler.libsonnet
Mixins in general are rather complex pieces of code to consume. When trying to use the loki mixins it wasn't apparent at first that I could use a headless service for DNS SRV discovery for both query_frontend and query_scheduler, especially because for frontend the service is named `query_frontend_headless_service`  and for the scheduler, it's named `query_scheduler_service_discovery`. Furthermore, the query_frontend mixin provides a non-headless version of the service while query_scheduler doesn't. This PR aims at normalizing this for end users, both headless services are now named `query_frontend_headless_service` and `query_scheduler_headless_service` and both also provide a non-headless version of the service. …
=> mixins: Normalize headless service name for query-frontend/scheduler

pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/compactor_test.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_read.go, pkg/storage/stores/tsdb/index/index.go, pkg/storage/stores/tsdb/index/index_test.go, pkg/storage/stores/tsdb/index_client.go, pkg/storage/stores/tsdb/index_client_test.go, pkg/storage/stores/tsdb/querier.go, pkg/storage/stores/tsdb/querier_test.go, pkg/storage/stores/tsdb/single_file_index.go, pkg/storage/stores/tsdb/single_file_index_test.go
Previously we used to read the info of all the chunks from the index and then filter it out in a layer above within the tsdb code. This wastes a lot of resources when there are too many chunks in the index, but we just need a few of them based on the query range.
Before jumping into how and why I went with chunk sampling, here are some points to consider:
* Chunks in the index are sorted by the start time of the chunk. Since this does not tell us much about the end time of the chunks, we can only skip chunks that start after the end time of the query, which still would make us process lots of chunks when the query touches chunks that are near the end of the table boundary.
* Data is written to tsdb with variable length encoding. This means we can't …
=> tsdb: sample chunk info from tsdb index to limit the amount of chunkrefs we read from index

pkg/distributor/distributor.go, pkg/ingester/stream.go
Add new spans to our write path to better determine which operations are holding our write performance.
=> Loki: Add more spans to write path

cmd/loki-canary/main.go, pkg/canary/reader/reader.go
The canary logs can be shipped to Loki in various formats. This allows users of the canary to parse out the canaries logs from any format e.g. nested json.
The alternative is to do something different for the canary logs to prevent the logs being wrapped / manipulated (e.g. write to Loki directly, or use a different log pipeline) which limits the benefits of the canary.
I've confirmed this works locally.
Fixes #7775
**Checklist**
=> Canary: support filtering / parsing logs with LogQL

pkg/ingester/wal/recordpool.go
Nothing is ever fetched from the pool - `GetEntries()` is never called. And the loop to call `PutEntries()` follows a call where the slice it ranges over is reset to empty, so that loop never added anything to the pool.
**Checklist**
- NA `CHANGELOG.md` updated
- NA Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> WAL: remove ePool that is unused

pkg/lokifrontend/frontend/v1/frontend.go, pkg/lokifrontend/frontend/v1/frontend_test.go, pkg/scheduler/queue/dequeue_qos_test.go, pkg/scheduler/queue/metrics.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/scheduler.go
This allows for easier passing of the metrics to the scheduler instantiation.
**Checklist**
- [n/a] Documentation added
- [n/a] `CHANGELOG.md` updated
- [n/a] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> Extract scheduler queue metrics into separate field

pkg/lokifrontend/frontend/v1/frontend.go, pkg/scheduler/queue/metrics.go, pkg/scheduler/queue/queue.go, pkg/scheduler/scheduler.go
Better o11y of the scheduler.
This change yields new metrics with potentially high cardinality on the scheduler.
A different approach for the `enqueueCount` would be to add the `level` label to the `queueLength` metrics, however, then we would need to know the level when we dequeue an item. 
**TODO**
**Checklist**
=> Extend scheduler queue metrics with enqueue/dequeue counters

README.md, docs/sources/upgrading/_index.md
The build flags have to be provided before the package paths.
Otherwise the `build` command fails with this error:
> malformed import path "--tags=promtail_journal_enabled": leading dash
See `go help build`:
> usage: go build [-o output] [build flags] [packages]
=> Promtail: Fix examples how to build it

pkg/logql/log/metrics_extraction.go, pkg/logql/log/parser.go, pkg/logql/log/parser_hints.go, pkg/logql/log/parser_hints_test.go, pkg/logql/log/parser_test.go, pkg/logql/log/pipeline.go
This PR makes parsers aware of any downstream label-matcher stages at parse time. As labels are parsed, if one has a matcher, the matcher is checked at parse time. If the label does not match it's matcher, parsing is halted on that log line.
**ex 1:**
consider the log:
`foo=1 bar=2 baz=3`
And the query
`{} | logfmt | bar=3`
When `bar` is parsed it is immediately checked against it's matcher. The match fails so we the parser never spends time parsing the rest of the line.
**ex 2:**
consider the log:
`foo=1 baz=3 bletch=4`
And the query
`{} | logfmt | bar=3`
`bar` is never seen in the log so the whole line is parsed.
**Benchmarks:**
```
│ parsers__old_2.txt │          parsers__new_3.txt          │
│       sec/op       │    sec/op     vs base                │
_Parser/json/inline_stages-8 …
```
=> Short circuit parsing when label matchers are present

operator/CHANGELOG.md, operator/controllers/loki/internal/lokistack/ruler_config_discovery.go, operator/controllers/loki/internal/lokistack/update.go, operator/controllers/loki/rulerconfig_controller.go
When `RulerConfig` is deleted, update the `LokiStack` annotations in order to update the Loki configurations.
**Checklist**
=> operator: Update LokiStack annotation on RulerConfig delete

docs/sources/release-notes/v2-7.md
This adds the release notes for v2.7.5 and v2.7.4. This last release was apparently not added last time. 
This will be backported to the release branch as well in a separate PR.
**Checklist**
=> Add release notes for v2.7.5 release

operator/calculator.Dockerfile
This is a follow-up of #8863 to fix image building on `main`. Currently it fails with:
```
#12 [builder 5/8] RUN go mod download
#12 1.822 go: github.com/grafana/loki/operator/apis/loki@v0.0.0-00010101000000-000000000000 (replaced by ./apis/loki): reading apis/loki/go.mod: open /workspace/apis/loki/go.mod: no such file or directory
#12 ERROR: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
------
> [builder 5/8] RUN go mod download:
#12 1.822 go: github.com/grafana/loki/operator/apis/loki@v0.0.0-00010101000000-000000000000 (replaced by ./apis/loki): reading apis/loki/go.mod: open /workspace/apis/loki/go.mod: no such file or directory
------
calculator.Dockerfile:10
--------------------
8 |     # cache deps before …
```
=> operator: Fix calculator dockerfile

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/roundtrip_test.go, pkg/util/querylimits/limiter.go, pkg/util/querylimits/limiter_test.go, pkg/util/querylimits/middleware_test.go, pkg/util/querylimits/propagation.go, pkg/validation/limits.go
As pointed out in https://github.com/grafana/loki/pull/8851, some queries can impose a great workload on a cluster by selecting too many streams.
Similarly to the `RequiredLabels` limit introduced at https://github.com/grafana/loki/pull/8851, here we add a new limit `RequiredNumberLabels` to require queries to specify at least N label. For example, if the limit is set to 2, then the query should contain at least 2 label matchers.
This limit can be configured per tenant and at query time.
Fixes https://github.com/grafana/loki-private/issues/699
**Checklist**
=> Implement `RequiredNumberLabels` query limit

operator/CHANGELOG.md, operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml, operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml
This is a follow-up of #8651 and adds the missing `replaces` directives for easy upgrading of the Community Loki Operator from `v0.1.0` to `v0.2.0`
To verify the replaces directives pointing to the previous CSV version:
- [k8s-operatorhub: Previous Version](https://github.com/k8s-operatorhub/community-operators/blob/bec6f9af3742764814c162c0ff384c000c7a2a69/operators/loki-operator/0.1.0/manifests/loki-operator.clusterserviceversion.yaml#L163)
- [redhat-openshift-ecocystem: Previous Version](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/6b56ca97b26059e9c9f12bc9ad62fc707b523db9/operators/loki-operator/0.1.0/manifests/loki-operator.c …
=> operator: Add missing replaces directives for release v0.2.0

pkg/logql/syntax/ast.go, pkg/logql/syntax/ast_test.go
This PR moves Line Filters to be as early in a log pipeline as possible. 
For example:
`{app="foo"} | logfmt |="some stuff"` becomes `{app="foo"} |="some stuff" | logfmt`
Any LineFilter after a `LineFormat` stage will be moved to directly after the nearest `LineFormat` stage
benchmarks:
```
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/logql/syntax
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
│ reorder_old.txt │           reorder_new.txt           │
│     sec/op      │   sec/op     vs base                │
ReorderedPipeline-8      2104.5n ± 3%   173.9n ± 2%  -91.74% (p=0.000 n=10)
│ reorder_old.txt │          reorder_new.txt          │
│      B/op       │   B/op    vs base                 │
ReorderedPipeline-8        336.0 ± 0%   0.0 ± 0%  -100.00% (p=0.000 n=10)
│ …
```
=> Automatically Reorder Pipeline Filters

pkg/util/querylimits/limiter.go
At https://github.com/grafana/loki/pull/8727 we introduced various limits that can now be configured at query time. We always compare the value of the limit configured at query time with the value set on the overrides for the tenant or the default if not configured (aka original); applying the most restrictive one.
If the most restrictive is the original value or the limit is not configured at query-time, we print the following debug message:
https://github.com/grafana/loki/blob/9e1846c47a1f3685fc540b7d03d285c7530da223/pkg/util/querylimits/limiter.go#L43
It will be printed many times: every time the query is not configured at query-time, as well as every time the original value is more restrictive. Moreover, this log message lacks some useful …
=> Log when returning query-time limit

pkg/scheduler/queue/metrics.go, pkg/scheduler/queue/queue.go
The metrics was useful for initial testing of the new scheduler queue implementation but yields high cardinality metrics, which is not desired. Also, the metric does not add additional value beyond the initial testing phase.
The metric was introduced with commit cba31024d4d0cc5c45612dd051c032f248817729
**Checklist**
=> Revert high cardinality metric in scheduler

pkg/scheduler/queue/queue.go, pkg/scheduler/queue/queue_test.go, pkg/scheduler/queue/tenant_queues.go
Prior to the changes in https://github.com/grafana/loki/pull/8752 the max queue size per tenant was enforced by the size of the buffered channel to which a request was enqueued.
However, since we have hierarchical queues, every subqueue has the same channel capacity as the root (tenant) queue. Therefore the total queue size per tenant needs to be tracked separately, so requests can be rejected when the max queue size is reached.
**Checklist**
- [n/a] Documentation added
- [n/a] `CHANGELOG.md` updated
- [n/a] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> Enforce per tenant queue size

docs/sources/configuration/_index.md, pkg/util/querylimits/propagation.go, pkg/validation/limits.go
Followup PR for https://github.com/grafana/loki/pull/8918 renaming config. See https://github.com/grafana/loki/pull/8918/files#r1151820792.
Fixes https://github.com/grafana/loki-private/issues/699
**Checklist**
=> Rename config for enforcing a minimum number of label matchers

docs/sources/operations/caching.md, production/ksonnet/loki/boltdb_shipper.libsonnet, production/ksonnet/loki/config.libsonnet, production/ksonnet/loki/memcached.libsonnet
Since we are not using the write dedupe cache ourselves we should not advise other users to do so.
**Checklist**
=> Remove dedupe cache from operations documentation.

CHANGELOG.md, pkg/storage/chunk/fetcher/fetcher.go
The `Size()` function on `chunk.Chunk` calls out to `func (ChunkRef) Size() int` in the proto, which doesn't actually include the size of the chunk data! We need to call `chunk.Data.Size()` for that.
N/A
This will fix the `Cache.Chunk.BytesSent` stat which indicates how many chunk bytes we sent to the chunk cache. This should probably be renamed for clarity at some point; it's a little confusing.
The same fix is applies to the `loki_chunk_fetcher_fetched_size_bytes{source="store"}` histogram metric.
**Checklist**
=> Fix fetched chunk from store size in metric

docs/sources/configuration/_index.md, pkg/distributor/distributor.go, pkg/distributor/ratestore.go, pkg/ingester/stream.go, pkg/logql/engine.go, pkg/querier/http.go, pkg/querier/queryrange/downstreamer.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/log_result_cache.go, pkg/querier/queryrange/queryrangebase/query_range.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/querier/queryrange/shard_resolver.go, pkg/storage/chunk/client/util/parallel_chunk_fetch.go, pkg/storage/chunk/fetcher/fetcher.go, pkg/storage/stores/composite_store_entry.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/series_store_write.go, pkg/storage/stores/tsdb/index_client.go
- At different places, inherit the span/spanlogger from the given context instead of instantiating a new one from scratch, which fix spans being orphaned on a read/write operation.
- At different places, turn spans into events. Events are lighter than spans and by having fewer spans in the trace, trace visualization will be cleaner without losing any details.
- Adds new spans/events to places that might be a bottleneck for our writes/reads.
=> Loki: Improve spans usage

pkg/storage/store_test.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/shipper/shipper_index_client.go, pkg/storage/stores/tsdb/identifier.go, pkg/storage/stores/tsdb/store.go
While building file names from `boltdb-shipper` and `tsdb`, we add the name of the uploader to it.
To avoid collisions in filenames when running multiple ingesters with the same name, we also add a nanosecond precise timestamp to the ingester name, which is persistent as the uploader name in the active index directory.
This is not being done for the tsdb index built from ingesters which can cause collisions in filenames when running multiple ingesters with the same name. I have moved the code to manage the uploader name to the index shipper config and used the same to share it with tsdb.
=> tsdb: use unique uploader name while building tsdb index filename, same as boltdb-shipper

CHANGELOG.md, pkg/querier/queryrange/downstreamer.go
In several places within Loki we need to determine if a query is a `range query` or `instant query`, this is done by checking to see if the start and end time are equal **and** the `step=0`
The downstream handler was not checking for `step=0` and thus it incorrectly mapped a range query to an instant query when a query has a start time equal to and end time.
There are a few other things at play here, mainly that we should really error anytime someone tries to run an instant query for logs which would have exposed this error much more easily. But that's something I'd like to handle in a different PR as it will be considered a breaking change depending on how we do it.
This PR uses an existing function we have for testing the query type and addresses …
=> Loki: Fixes incorrect query result when querying with start time == end time

operator/apis/loki/v1/lokistack_types.go, operator/internal/manifests/internal/sizes.go
Remove resource requirements so lokistack can run on laptop-sized SNO or CRC clusters.
Originally I thought to add an even smaller size, but I see that
1x.extra-small is already documented as not-for-production, so it seems appropriate.
Doc comment:
// SizeOneXExtraSmall defines the size of a single Loki deployment
// with NO resource requirements and without HA support.
//
// This is ONLY for development, testing, or demos
// on limited single-node clusters.
// There are NO performance guarantees.
// LokiStack will use whatever resources are available,
// and WILL NOT FUNCTION CORRECTLY if there is not enough memory or CPU.
//
// DO NOT USE THIS IN PRODUCTION!
=> Redefine 1x.extra-small to have 0 requirements.

docs/sources/logql/template_functions.md
WHAT:
- Update examples for `contains` and `hasSuffix`
- Correct order should be `functionName arg1 arg2 argN`, eg. `contains s src`
WHY:
- Current example for `contains` and `hasPrefix` / `hasSuffix` has a wrong order that will cause `TemplateFormatErr`.
- Examples I'm referring to `{{ if .err hasSuffix "Timeout" }} timeout {{end}}`
**Checklist**
=> Update contains and hasPrefix/hasSuffix with the correct examples

cmd/loki-canary/main.go, pkg/canary/reader/reader.go
This supports cases where the cert cannot be trusted but we are not using mTLS, i.e. `loki-canary -tls=true -insecure=true`
**Checklist**
=> Loki Canary: Enable insecure-skip-verify for all requests

docs/sources/api/_index.md
Describes how exactly the `start` and `end` timestamps operate on the time range boundaries. 
**Checklist**
=> Docs: Improve time range documentation

tools/helm.yaml
rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Signed-off-by: Anton Patsev <patsev.anton@gmail.com>
Which of these should I fill out in this PR ?
**Checklist**
=> Update rbac.authorization.k8s.io/v1beta1 to rbac.authorization.k8s.io/v1

docs/sources/configuration/_index.md, pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go, pkg/usagestats/stats.go
Reports used to be sent to a fixed URL usageStatsURL.
Now this url can be configurable while using the old url as a default.
Updated tests to use config for custom URLs instead of changing package variable.
Fixes #6502
**Checklist**
=> Loki: Add UsageStatsURL to usagestats Config

docs/sources/clients/promtail/scraping.md
This PR fixes the link to the configuration in the Azure Event Hubs scraping doc.
Link to the discussion https://github.com/grafana/loki/pull/8787#discussion_r1145298591
Not available
**Checklist**
=> Fix the link in the Azure Event Hubs doc

CHANGELOG.md, clients/pkg/promtail/targets/journal/journaltarget.go
Since PR #4066 two messages are logged for the errors `ErrExpired` and `EOF`, whereas nothing has been logged beforehand.
As `ErrExpired` is returned by the `JournalReader` after sending a message to the `until` channel to signal a normal stop, this should not be logged as an error.
N/A
/CC @dannykopping
**Checklist**
=> Promtail: Prevent logging errors on normal shutdown

pkg/querier/queryrange/roundtrip.go
Found this double-copied line which a mistake. This PR removes one of them which won't change behavior (besides removing duplicate spans/etc).
=> remove redundant splitby middleware

docs/sources/installation/docker.md, docs/sources/upgrading/_index.md, examples/getting-started/docker-compose.yaml, production/docker-compose.yaml, production/docker/docker-compose.yaml, tools/diff-metrics.sh
Changes version references in Loki docs for the upcoming release
Also adds a script for diffing metrics when doing a release.
**Checklist**
=> Change loki version in docs for 2.8 release

docs/sources/installation/docker.md, docs/sources/upgrading/_index.md, examples/getting-started/docker-compose.yaml, production/docker-compose.yaml, production/docker/docker-compose.yaml, tools/diff-metrics.sh
Automatic backport failed: https://github.com/grafana/loki/pull/8985#issuecomment-1494977977
=> [release-2.8.x] Change loki version in docs for 2.8 release (#8985)

operator/apis/loki/v1/lokistack_types.go, operator/internal/manifests/internal/sizes.go
Removed by accident in:
75ec3f338 * Redefine 1x.extra-small to have 0 requirements. (#8977)
=> operator: Restore minimum PVC sizes for 1x.extra-small

.drone/drone.jsonnet, .drone/drone.yml
Right now, backporting to a kXXX branch causes a trigger of the `deploy` pipeline, which overrides already deployed newer releases.
**Checklist**
=> Trigger `deploy` CI step only on push to main or tag of new release

CHANGELOG.md, clients/pkg/promtail/targets/journal/journaltarget.go, production/ksonnet/loki/boltdb_shipper.libsonnet
This key is missing when not using boltdb_shipper, but this lib is included by default
=> Mixins: check that `memcached_index_writes` exists before using it in `boltdb_shipper`

CHANGELOG.md, clients/pkg/promtail/scrapeconfig/scrapeconfig.go, clients/pkg/promtail/targets/file/decompresser.go, clients/pkg/promtail/targets/file/decompresser_test.go, clients/pkg/promtail/targets/file/filetarget.go, clients/pkg/promtail/targets/file/filetarget_test.go, clients/pkg/promtail/targets/file/filetargetmanager.go, docs/sources/clients/promtail/_index.md, docs/sources/clients/promtail/configuration.md
Adds a new `compression` configuration to Promtail to customize decompression behavior.
As of now, two options are supported:
`enabled`: false by default but if truthy, Promtail will infer a compression algorithm to use based on the file extension
`initialDelay`: 0 by default but if higher, Decompressor will sleep for the given duration before trying to decompress. This is to avoid scenarios where the Decompressor starts to work on a file that is still being compressed/generated.
Fixes https://github.com/grafana/loki/issues/8784
**Checklist**
=> Promtail: Add `decompression` configuration

operator/CHANGELOG.md, operator/Makefile, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manager/kustomization.yaml
Reverts partially the `-placeholder` suffix introduced by #8651 to enable OpenShift builds.
**Checklist**
=> operator: Remove static placeholder suffix for openshift bundle

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
`goimports` is required by https://github.com/grafana/loki/pull/9012.
**Checklist**
=> Add goimports to Loki build image.

CHANGELOG.md, docs/sources/api/_index.md, pkg/loki/format_query_handler.go, pkg/loki/format_query_handler_test.go
Change is to be in consistent with other endpoints and also to the prometheus `format_query` format. https://prometheus.io/docs/prometheus/latest/querying/api/#formatting-query-expressions
Fixes #NA
requested by @gwdawson.
Related: https://github.com/grafana/grafana/pull/64337
**Checklist**
=> chore(format_query): Change response type to `application/json`

docs/sources/maintaining/release-loki-build-image.md
> Repeat step 1.3, which will use the new image
is the same as calling `make drone`. So it is not required.
**Checklist**
=> Remove unnecessary build image step.

integration/loki_micro_services_test.go, integration/per_request_limits_test.go, pkg/util/querylimits/propagation.go, pkg/util/querylimits/propagation_test.go
`maxQueryTime` is more in line with the other per-request limits we have.
**Checklist**
=> Rename per-request query limits.

operator/CHANGELOG.md, operator/controllers/loki/lokistack_controller.go, operator/controllers/loki/lokistack_controller_test.go
This PR adds the ability for the Loki Operator to watch the S3 storage `Secret` and reconcile accordingly. 
[LOG-3818](https://issues.redhat.com/browse/LOG-3818)
**Checklist**
=> operator: Add watch for the object storage secret

pkg/querier/queryrange/limits.go
When the query size limiter can't limit the query, fail through to the next middleware instead of erroring. This can happen, for example, when a query spans schemas, which is still a valid query case, so we want to make sure to fall back to existing behavior.
=> Fail through to next middleware when querySizeLimit cannot be applied

CHANGELOG.md
A few items were incorrectly listed under 2.8 on `main` that are not in 2.8. This PR brings the `CHANGELOG` on `main` in line with the one already on `release-2.8.x` and therefore doesn't need to be backported.
=> Fix CHANGELOG to accurately reflect what's in 2.8

docs/sources/release-notes/v2-8.md
https://github.com/grafana/loki/pull/9048 only updated the link in the `/next` version of the docs which reflects `main`. This will update the `/latest` link which reflects the latest version (2.8).
=> Fix CHANGELOG link

pkg/storage/stores/tsdb/index/shard.go
Saw validation tests failing due to this on `main`; not sure how this hasn't borked our builds but this ensures we don't error on shard-factors of zero (equivalent to not sharding). This doesn't actually hit our code paths because we explicitly shortcut factor=0 in the shardmapper.
=> makes test pass for 0 sharding factor (equivalent to no sharding)

pkg/logql/metrics_test.go, pkg/util/log/wrappers.go
Currently when we log "with context" we will only add the traceID if the particular trace is being sampled. This is nice because it makes it obvious that if you go search for a trace you'll find it.
However, traceID is also useful for selecting all the log lines from a single query within Loki itself and if the trace wasn't sampled we remove this useful piece of context for querying the log lines.
In this PR, instead of dropping the traceID from the logs, we instead prefix it with `NS-`
Where NS is short for Not Sampled
Example:
```
level=debug ts=2023-04-05T15:06:24.377067817Z caller=fetcher.go:292 org_id=145265 traceID=NS-13ed6c30228e221d chunks=1 decodeRequests=1 missing=0
```
Questions: 
* should we bikeshed a little on this prefix? (I wanted …
=> Loki: log all trace ID's but include `sampled=true` when the trace is logged

pkg/distributor/ratestore.go
Fix an event logging on rate store that is missing the `event` key. `LogKV` expects a key-value pair always.
=> Loki: Fix span event logging on rate store

CHANGELOG.md, pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/compactor_test.go
At `compactedIndex.ToIndexFile` we were not computing the size of the chunk correctly. We were looking at the size of the chunk ref. Since the size of the chunk ref is always a bunk of bytes, the chunk meta KB field would always be 0.
https://github.com/grafana/loki/blob/4e893a0a88b2c8c3ea9d1d8b1037f54d8fb7f1af/pkg/storage/stores/tsdb/compactor.go#L367
Instead, we should get the approx KBs by looking at the chunks data uncompressed size. As we do at `store.IndexChunk`:
https://github.com/grafana/loki/blob/d405162516be78beb3d0712cfd57256c7873fe78/pkg/storage/stores/tsdb/store.go#L189
This PR fixes this.
**Checklist**
=> Estimate chunk size on compaction looking at data uncompressed size

clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, go.mod, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
Bumps our go dependency from 1.20.1 to 1.20.3 to address [security fixes](https://groups.google.com/g/golang-announce/c/Xdv6JL9ENs8)
**Checklist**
=> Bump go from 1.20.1 -> 1.20.3

CHANGELOG.md, clients/pkg/promtail/config/config.go, clients/pkg/promtail/promtail.go, clients/pkg/promtail/targets/file/filetarget.go, clients/pkg/promtail/targets/file/filetarget_test.go, clients/pkg/promtail/targets/file/filetargetmanager.go, clients/pkg/promtail/targets/file/filetargetmanager_test.go, clients/pkg/promtail/targets/file/tailer.go, clients/pkg/promtail/targets/manager.go, docs/sources/clients/promtail/configuration.md, go.mod, go.sum, vendor/github.com/grafana/tail/tail.go, vendor/github.com/grafana/tail/watch/polling.go, vendor/modules.txt
Currently, Promtail always polls files every 250ms. This PR allows the polling period to be customized, starting at a minimum polling period and exponentially increasing the polling frequency to a bounded maximum if the file has no changes.
When file changes are detected, the polling frequency resets to the minimum.
The default behavior is the existing behavior; both the minimum and maximum polling intervals are set to 250ms.
I'm opening this in draft to get early feedback. There's a few open questions:
* Where can I add validations to ensure that the min/max polling intervals are configured properly? 
* Is this the right approach for implementation? Do I need to make any changes?
* Does this need tests? 
I'll update the CHANGELOG and Documentation after we're agreed on an approach.
=> promtail: support configurable polling interval

clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, go.mod, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
Manual backport of https://github.com/grafana/loki/pull/9106 as the automated one failed.
=> [release-2.8.x] Bump go from 1.20.1 -> 1.20.3 (#9106)

clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, go.mod, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
Manual backport of https://github.com/grafana/loki/pull/9106 as the automated one failed.
=> [release-2.7.x] Backport 9106 to release 2.7.x

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
This PR makes the `unpack` parser sanitize label keys like all the other parsers. When invalid label names are included, it causes the user to get `could not write JSON response` errors when the response is serialized to send back to the user.
=> Sanitize label keys in the unpack parser

operator/CHANGELOG.md, operator/apis/loki/v1/lokistack_types.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/manifests/build_test.go, operator/internal/manifests/config.go, operator/internal/manifests/internal/sizes.go
Revert "Redefine 1x.extra-small to have 0 requirements. (#8977)"
This reverts commit 75ec3f33864ce98df1b89b0973cc67479d7486bc.
Introduce a new size 1x.tiny-test
=> operator: Revert 1x.extra-small changes, add 1x.tiny-test

CHANGELOG.md, pkg/loki/modules.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/querysharding.go, pkg/querier/queryrange/querysharding_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/shard_resolver.go, pkg/querier/queryrange/split_by_range.go, pkg/querier/queryrange/split_by_range_test.go
The following middlewares in the query frontend uses a downstream engine:
- `NewQuerySizeLimiterMiddleware` and `NewQuerierSizeLimiterMiddleware`
- `NewQueryShardMiddleware`
- `NewSplitByRangeMiddleware`
These were all creating the downstream engine as follows:
```go
logql.NewDownstreamEngine(logql.EngineOpts{LogExecutingQuery: false}, DownstreamHandler{next: next, limits: limits}, limits, logger),
```
As can be seen, the [engine options configured in Loki][1] were not being used at all. In the case of `NewQuerySizeLimiterMiddleware`, `NewQuerierSizeLimiterMiddleware` and `NewQueryShardMiddleware`, the downstream engine was created to get the `MaxLookBackPeriod`. When creating a new Downstream Engine as above, the `MaxLookBackPeriod` [would always …
=> Pass engine opts down to middlewares

CHANGELOG.md
Some changelog entries were misplaced into _Promtail Enhancements_ instead of _Loki Enhancements_. This PR fixes this by moving the items to the correct section.
Fixes https://github.com/grafana/loki/pull/9042
**Checklist**
=> Move misplaced recent changes in changelog to Loki Enhancements

docs/sources/installation/helm/monitor-and-alert/with-grafana-cloud.md
Changed "integrations and connections" to "connections" and removed the lightning bolt icon reference.
=> Removed deprecated navigation names

.gitignore, docs/Makefile, docs/docs.mk, docs/variables.mk
- Adds ability to build multiple projects simultaneously using, for example, `make docs PROJECTS='grafana grafana-cloud'`.
- Adds `make doc-validator` which runs [`doc-validator`](https://github.com/grafana/technical-documentation/tree/main/tools/cmd/doc-validator) on all documentation.
Using a centralized script will help ensure consistency in workflow across all projects.
=> Use centralized make-docs script from Writers' Toolkit

docs/sources/operations/scalability.md
The example config path on Loki's query scheduler is using `-config.file=/mimir/config/mimir.yaml`, which looks a little bit confusing on Loki's document, even though there are multiple references to Mimir.
https://github.com/grafana/loki/blob/7bec727c6dff8e6268f9a8f9b64fee725d4195f8/docs/sources/operations/scalability.md?plain=1#L23
This PR replaces the Mimir config path with the one found in query-frontend's document.
https://github.com/grafana/loki/blob/7bec727c6dff8e6268f9a8f9b64fee725d4195f8/docs/sources/configuration/query-frontend.md?plain=1#L115
N/A
I noticed this when checking configuration of 2.6, but this is still the case in the [latest …
=> Docs: Replace mimir example config path with a loki one

Makefile
Support debug build for `logcli` binary. This writes debug binary under `logcli-debug` name in the same `cmd/logcli` directory.
Already faced situation multiple times this is useful to debug some issues with LogQL locally.
Fixes NA
**Checklist**
=> Makefile: Support debug build for `logcli`.

docs/sources/clients/promtail/configuration.md
Promtail can set the tenant id from a label with PR 6290 (commit a1e0298a5).
However, while docs/sources/clients/promtail/stages/tenant.md was appropriately updated, docs/sources/clients/promtail/configuration.md was left untouched.
**Checklist**
=> Docs: add missing configuration option

CHANGELOG.md, pkg/storage/stores/indexshipper/compactor/retention/expiration.go, pkg/storage/stores/indexshipper/compactor/retention/expiration_test.go
`DropFromIndex` should be return false when `retention_period` is set to a zero value.
If we take chunks that overlap period boundary and are indexed in two tables, we drop these from the table on the left side of the period boundary even if they have not expired - https://github.com/grafana/loki/blob/ashwanth/drop-from-index-zero-value/pkg/storage/stores/indexshipper/compactor/retention/retention.go#L218
**Checklist**
=> expiration: do not drop index if period is a zero value

.drone/drone.jsonnet, .drone/drone.yml
These pipelines cannot run because secrets are not being exposed on fork builds
=> Skip pipelines that require secrets in forks

docs/sources/installation/helm/reference.md, production/helm/loki/values.yaml
Fix comment in the `values.yaml` and re-generate the reference docs.
**Checklist**
=> Fix comment in helm values.yaml

flake.lock, flake.nix, nix/overlays/golangci-lint.nix, nix/overlays/helm-docs.nix, pkg/util/ring_test.go
Updates `flake.lock` to grab the latest `nixpkgs-unstable` in order to upgrade go version to `1.20`.
=> upgrade go to 1.20 in nix flake

.github/workflows/append-release-notes.yml, docs/sources/release-notes/next.md
This PR aims to remove the manual process required to create release notes during a release. It will allow contributors to add the label `add-to-release-notes` to any PR. When that PR is merged, this action will create another PR appending the original PR's # and title to the release notes for the next release. This second PR will give the author an opportunity to add a description to their addition, as well as give maintainers an opportunity to discuss it's relevance in the release notes.
If we move forward with this approach, I will follow up with an addition to the PR template to ask contributors if they think their PR is worthy of mention in the next releases' release notes, and if so to add the label.
Depends on new [github …
=> Add release notes appender action

docs/sources/installation/helm/reference.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml, tools/dev/k3d/environments/helm-cluster/spec.json, tools/dev/k3d/environments/helm-cluster/values/enterprise-logs.yaml, tools/dev/k3d/jsonnetfile.lock.json
This PR bumps the GEL version to match the Loki version that was added in version 5 of the helm chart. With these new versions we can now default to 3 targets in scalable mode `read`, `write`, and `backend`.
This PR also fixes 2 bugs when running in scalable mode:
* the gateway should forward requests to the admin api to the `backend` target when running 3 targets
* the index gateway should default to using `ring` mode, which will allow the queriers in the new `read` target to find the index gateway address for their index gateway clients via the ring.jj
**Checklist**
=> [helm] Bump GEL version, default to 3 scalable targets

.drone/drone.jsonnet, .drone/drone.yml
Fixes issue introduced by https://github.com/grafana/loki/pull/9161
There's a bug, the modified pipelines do not run in forks anymore because they don't run anywhere 
This PR fixes this, I was missing a `$` 🤦 
To test, I pushed this branch to the main repo and to my fork:
- This PR: https://drone.grafana.net/grafana/loki/22604/22/3, the step runs
- PR from my fork (do not merge): https://github.com/grafana/loki/pull/9166, pipeline is skipped: https://drone.grafana.net/grafana/loki/22605/22/3
=> Fix pipeline skipping in forks

operator/CHANGELOG.md, operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/rbac/role.yaml, operator/controllers/loki/lokistack_controller.go, operator/internal/manifests/gateway.go, operator/internal/manifests/gateway_test.go, operator/internal/manifests/mutate.go, operator/internal/manifests/mutate_test.go
This PR adds a `PodDisruptionBudget` to the Loki Operator Gateway, with a `MinAvailable` of 1.
**Checklist**
=> operator: Add a PodDisruptionBudget to lokistack-gateway

docs/sources/installation/helm/reference.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml, production/ksonnet/loki-canary/config.libsonnet, production/ksonnet/loki/images.libsonnet, production/ksonnet/promtail/config.libsonnet
backport #9003 to release 2.8
Prepare helm and jsonnet for 2.8 release.
(cherry picked from commit 5113906c6723234c1441838c0d5896f28d15d3e3)
=> [release-2.8.x] Update helm and jsonnet for 2.8 release (#9003)

pkg/distributor/ratestore.go, pkg/ingester/ingester.go
- Add a new span event to our ingesters `GetStreamRates` function.
- Add how many streams were updated on a `updateRates` call. This way, if we see a slow updateRates we'll be able to see if there's a correlation between the update beign slow and the amount of streams being high.
N/A
**Checklist**
=> Loki: Add debug event to ingester `GetStreamRates`

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
- Reuse rates mapping returned by the calculator to reduce the number of allocations
=> Ingester: Reuse allocations on `GetStreamRates`

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/querier/queryrange/queryrangebase/roundtrip.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go
At https://github.com/grafana/loki/pull/8972 we started caching all index stats requests.
If the results cache gets overloaded, it can quickly take down the rest of the loki cell due to all the increased work.
This PR adds a new flag so we can easily disable caching index stats requests.
This PR is a follow up for https://github.com/grafana/loki/pull/8972
**Checklist**
=> Flag to disable index stats cache

CHANGELOG.md, pkg/storage/chunk/cache/redis_client.go, pkg/storage/chunk/cache/redis_client_test.go
See referenced issue below for details
Fixes https://github.com/grafana/loki/issues/9149
This is the challenge of using magic in our code; it produces unexpected results sometimes which are hard to debug. In general we should prefer being explicit, but we cannot revert this functionality now because it may be in use. I think this (automatically deriving multiple endpoints from a single one) is a good candidate for a deprecation, and ultimately removal in v3. Thoughts?
**Checklist**
=> Prevent redis client from incorrectly choosing cluster mode with local address

pkg/logcli/query/query.go, pkg/storage/chunk/client/object_client.go
This PR improves the error messaging for Logcli when an object cannot be downloaded from the store by printing the name of the object along with the error.
Internal support escalation
There are other places where GetObject is called:
- `indexStorageClient.GetFile`
- `indexStorageClient.GetUserFile`
Looks like both of them are used only by the compactor and the table manager. IIUC, these functions are not used by LogCLI.
**Checklist**
=> Logcli - Better logging when object cannot get loaded from object store

CHANGELOG.md, docs/sources/api/_index.md, docs/sources/configuration/_index.md, docs/sources/upgrading/_index.md, pkg/ingester/flush.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/metrics.go, pkg/loki/modules.go, pkg/loki/modules_test.go
This updates the PrepareShutdown method so it supports GET and DELETE methods as well. This makes it similar to Mimir: https://github.com/grafana/mimir/pull/4718. 
The status is now stored in a local file. A new config setting had to be added for this file as there is no obvious place to store it.
**Checklist**
=> Update prepare shutdown

operator/CHANGELOG.md, operator/internal/manifests/build_test.go, operator/internal/manifests/indexgateway.go, operator/internal/manifests/indexgateway_test.go, operator/internal/manifests/querier.go, operator/internal/manifests/querier_test.go, operator/internal/manifests/query-frontend.go, operator/internal/manifests/query-frontend_test.go
This PR adds 3 `PodDisruptionBudget`s for the following components:
* `query-frontend` with a `MinAvailable` of 1.
* `querier` with a `MinAvailable` of 2 for `1x.medium` and 1 for `1x.small`.
* `index-gateway` with a `MinAvailable` of 1.
**Checklist**
=> operator: Add PodDisruptionBudgets to the query path

CHANGELOG.md, production/ksonnet/loki/multi-zone.libsonnet
This PR makes Ingester pods available in multi zone mode which, based on the previous defaults, were not created.
Fixes #9139 
**Checklist**
- [X Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
=> Loki microservices tanka: add some ingester replicas

pkg/ingester/stream.go, pkg/ingester/stream_test.go
Obs: PSRL stands for `per-stream rate limit`
- Fixes the scenario where all entries errors are accounted as PSRL if sharding is enabled
- Fixes invalid/rejected entries being accounted as candidates to be inserted
Scenario to illustrate:
- Let's say a push request has two entries for the same stream, one entry being invalid/super old, and another one being a valid one. Two issues will occur: 1) the two will be accounted to check if they're hitting the psrl or not; 2) the two will be rejected with PSRL error
=> Loki: Fix wrong association of PSRL when sharding is enabled

pkg/storage/stores/tsdb/compactor_test.go
just a little cleanup to make tests run faster -- the 20 user test doesn't seem to test any additional surface area and takes a long time.
=> removes 20 user test from compaction; seems redundant and hits timeouts

docs/sources/installation/helm/reference.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
This re-adds the configuration that was removed in https://github.com/grafana/loki/pull/8515
**Checklist**
=> Re-add helm configuration for Azure OIDC federation

docs/sources/api/_index.md
POST /loki/api/v1/push is on the write path on the distributor and should not be the query frontend (read path)
**Checklist**
=> POST /loki/api/v1/push should not be on query path

.gitignore, Makefile, docs/Makefile, docs/docs.mk, docs/make-docs, docs/variables.mk
This reverts the revert in https://github.com/grafana/loki/pull/9146 with a slightly less "nuclear" solution.
I think the problem was that CI was pulling `docs.mk` from `main`, and it was creating a diff between the version we had checked in. I changed `docs.mk` to point to a specific sha, which should prevent this in the future.
I also opened a [PR](https://github.com/grafana/writers-toolkit/pull/228) against the writers-toolkit.
=> Bring back centralized docs toolkit (undo revert in #9146)

pkg/distributor/distributor_ring.go, pkg/loki/config_wrapper_test.go
https://github.com/grafana/loki/pull/9184 changed the signature of `ring.GetInstanceAddr`. That function is now used since  https://github.com/grafana/loki/pull/8067 which was not updated to use the changed signature.
This PR fixes this by passing a new config flag `EnableIPv6` to the new `enableInet6` argument of `ring.GetInstanceAddr`. Similar to how it's done for the ruler:
https://github.com/grafana/loki/blob/3abd26097587779b461a8befef1af06700d0ae13/pkg/ruler/base/ruler_ring.go#L80
Fixes `main`
**Checklist**
[1]: https://grafana.com/docs/loki/latest/configuration/
=> Do not use IPv6 when getting addr from ring

CHANGELOG.md, docs/sources/release-notes/v2-8.md
Prepares the release notes and changelog for 2.8.1
=> Update CHANGELOG and release notes

CHANGELOG.md, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, production/helm/loki/src/helm-test/Dockerfile, tools/lambda-promtail/Dockerfile
Upgrade alpine version to address [openssl CVEs](https://www.alpinelinux.org/posts/Alpine-3.17.3-released.html)
**Checklist**
=> Upgrade alpine 3.16.4 -> 3.16.5

CHANGELOG.md, docs/sources/release-notes/v2-8.md
Brings over the correct 2.8.1 changelog and release notes from `release-2.8.x`.
**Checklist**
=> Finalize 2.8.1 changelog and release notes

operator/config/overlays/development/minio/deployment.yaml
This PR replaces the deprecated MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables in the operator template with their new names MINIO_ROOT_USER and MINIO_ROOT_PASSWORD.
Fixes #8702 
This splits the previous PR #9150 in order to have separate PRs for Loki and Operator.
**Checklist**
=> operator: Replace deprecated MinIO environment variables

docs/sources/lids/template.md
Marks the LID template as "draft" so that the template is not published to the docs site.
Fixes #9283
=> Mark template as draft to unpublish.

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
Updates the `skipRange` in the ClusterServiceVersion manifest, so that it matches the next release version. This PR also changes the lower bound of the skip-range, so that direct updates can not skip too many versions.
Refer to [LOG-3837](https://issues.redhat.com/browse/LOG-3837) for the reasoning behind updating the lower bound.
**Checklist**
=> operator: Update skipRange for 5.8 release

pkg/storage/stores/tsdb/index/index.go
Reverts grafana/loki#9276
Update main to prevent writing v3 by default while I find a bug in it.
=> Revert "start writing tsdb v3"

pkg/util/http.go, pkg/util/http_loki_test.go
- Modifies `decompressFromBuffer` to call `buffer.Bytes()` a single time.
- Adds a new Benchmark under `http_loki_test.go` file. I had to create this in a separated file to differentiate from the original `http_test.go` forked from Cortex and because `http_test.go` uses package `http_test` which doesn't allow us to test private functions.
Before:
```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -tags integration,requires_docker -bench ^BenchmarkDecompressFromBuffer$ github.com/grafana/loki/pkg/util
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/util
cpu: AMD Ryzen 9 7900X 12-Core Processor            
BenchmarkBla-24    	384391501	         3.185 ns/op	       0 B/op	       0 allocs/op
PASS
ok …
```
=> HTTP: Reuse `buffer.Bytes()` when decompressing

docs/sources/installation/helm/reference.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/reference.md.gotmpl, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
This exposed the a `signatureVersion` property in the helm chart's storage config options that can be used to set the `signature_version` for a Loki S3 storage config.
=> Expose signature version property for s3 storage configs

pkg/distributor/distributor.go
Modify the `createShard` method to create the entries slice with the number of entries divided by the total number of shards instead of always creating it with len=1024.
=> Distributor: Modify `createShard` to create slice with more precise size

tools/dev/k3d/environments/helm-cluster/main.jsonnet
Not sure if this is a change to Grafana, but while the old sytnax used to work, it no longer does, and needs this `;grafana-enterprise-logs-app` suffix, which appears to fix things.
**Checklist**
=> Fix GF_INSTALL_PLUGINS syntax for k3d env GEL plugin

operator/CHANGELOG.md, operator/internal/manifests/distributor.go, operator/internal/manifests/distributor_test.go, operator/internal/manifests/ingester.go, operator/internal/manifests/ingester_test.go, operator/internal/manifests/internal/sizes.go
This PR adds a `PodDisruptionBudget` to the Loki Operator Ingester and Distributor.
- Ingester with a MinAvailable of 1 or 2 if `1x.medium` is used.
- Distributor with a MinAvailable of 1.
**Checklist**
=> operator: Add PodDisruptionBudget to lokistack-ingestion path

CHANGELOG.md, docs/sources/configuration/_index.md, docs/sources/upgrading/_index.md, pkg/analytics/reporter.go, pkg/analytics/reporter_test.go, pkg/analytics/seed.go, pkg/analytics/seed_test.go, pkg/analytics/stats.go, pkg/analytics/stats_test.go, pkg/distributor/distributor.go, pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/ingester/metrics.go, pkg/loghttp/push/push.go, pkg/logql/metrics.go, pkg/loki/loki.go, pkg/loki/modules.go, pkg/storage/store.go, pkg/storage/stores/indexshipper/compactor/compactor.go, tools/doc-generator/parse/root_blocks.go
Rename usagestats to analytics. The config section in the yaml is already called analytics, this makes things more consistent.
**Checklist**
=> Rename usagestats to analytics

integration/loki_micro_services_delete_test.go
`loki_compactor_deleted_lines` increments each time we find a line to delete from a chunk. If the chunk is indexed in multiple tables, we increment it for each of these tables as they get compacted.
Currently the chunk (that holds the line to be deleted) starts @`now - 46h`, so depending on when the test runs it gets indexed in 2 or 3 tables. It has been failing between hours `22:00 - 23:59` as the chunk only overlaps and gets indexed in 2 tables while the test expects it to be indexed in 3
https://drone.grafana.net/grafana/loki/23063/2/1
https://drone.grafana.net/grafana/loki/23067/2/1
Updating the chunk start time to now-48h so that it always gets indexes in 3 tables …
=> fix flaky integration TestMicroServicesDeleteRequest test

operator/CHANGELOG.md, operator/internal/manifests/build_test.go, operator/internal/manifests/compactor.go, operator/internal/manifests/distributor.go, operator/internal/manifests/gateway.go, operator/internal/manifests/indexgateway.go, operator/internal/manifests/ingester.go, operator/internal/manifests/ingester_test.go, operator/internal/manifests/querier.go, operator/internal/manifests/query-frontend.go, operator/internal/manifests/query-frontend_test.go, operator/internal/manifests/ruler.go, operator/internal/manifests/ruler_test.go, operator/internal/manifests/var.go
This PR adds PodAntiAffinity to Ingester to make the k8s scheduler prefer to schedule the pods of these components in different nodes if running with more than 1 replica. This improves the overall resiliency of the stack.
https://issues.redhat.com/browse/LOG-3848
**Checklist**
=> operator: Add default PodAntiAffinity to Ingester

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml, production/ksonnet/loki-canary/config.libsonnet, production/ksonnet/loki/images.libsonnet, production/ksonnet/promtail/config.libsonnet
Bumps helm and jsonnet to use the latest Loki and GEL versions
**Checklist**
=> Bump helm and jsonnet to latest version

.drone/drone.jsonnet, .drone/drone.yml
Pin manifests plugin to unblock CI.
Example failed step: https://drone.grafana.net/grafana/loki/23046/26/3 . The tempo team had the same issue some time ago: https://github.com/grafana/tempo/pull/2371/files.
=> Pin manifests plugin version

production/ksonnet/loki/memberlist.libsonnet
There is a duplicated ConfigMap volume definition in Ingester StatefulSet when:
` multi_zone_ingester_enabled: false,`
See generated json:
```
"ingester_statefulset": {
...
"terminationGracePeriodSeconds": 4800,
"volumes": [
{
"configMap": {
"name": "loki"
},
"name": "loki"
},
{
"configMap": {
"name": "overrides"
},
"name": "overrides"
},
{
"configMap": {
"name": "loki"
},
"name": "loki"
},
{
"configMap": {
"name": "overrides"
},
"name": "overrides"
}
]
}
},
```
Fixes #9344
**Checklist**
=> Loki microservices Tanka: remove unintended override

pkg/storage/stores/tsdb/index/chunk_test.go, pkg/storage/stores/tsdb/index/index.go
Tricky one to find, but this does the following
* correctly subtracts remaining chunk count when skipping a page (this was previously using a zero-valued marker)
* correctly set previous maxt on pages that are skipped. This is important because chunks themselves are delta-encoded against the previous chunk.
* removes the markers pool from the chunk decoding which isn't needed.
* adds a test
* adds a bit more logging on which series resulted in a decoding error during chunk iteration
=> fixes bug during chunk iteration using markers

pkg/storage/stores/tsdb/index/index.go
Reverts grafana/loki#9301
Should be good to start writing v3 again after https://github.com/grafana/loki/pull/9328 is merged and when we're ready to start using tsdbv3 as the default
=> Revert "Revert "start writing tsdb v3""

production/helm/loki/templates/_helpers.tpl
This PR adds a routing rule for `/loki/api/v1/delete` endpoint to `gateway` component.
Fixes #9325
**Checklist**
=> /loki/api/v1/delete is routed to backend url

docs/sources/operations/storage/retention.md
Made chances to reflect uniform reference to the name Compactor, changed all lowercase instance outside of code to uppercase.
To make the docs uniform when speaking about the Compactor
**Checklist**
=> Change upper and lower case Compactor name

docs/docs.mk, docs/make-docs
Supports Ubuntu Snap based Docker installations by using TMPDIR instead of an explicit tempfile. 
Because Ubuntu Snap packages have access to only the user's home directory, users must specify something like `TMPDIR="$(mktemp -d -q ~/.make-docs.XXXXX)"` in order to be able to run `make docs`.
=> Update centralized make-docs procedure

production/helm/loki/templates/_helpers.tpl
1. Rewrite the regular expressions for exact or prefix matches because they are matching in places where they shouldn't be (due to a missing anchor (`^`)), which is also causing inefficiency. Exact and prefix matches are also easy to understand because they are the longest matches regardless of the order in which they are listed.
2. Change the destination of the following Ruler API from `$readUrl` to `$backendUrl` because setting `LegacyReadTarget=false` cause it to stop functioning. (Fix #9214)
- `/api/prom/rules`
- `/api/prom/rules/*`
- `/loki/api/v1/rules`
- `/loki/api/v1/rules/*`
3. Add the following APIs settings.  
- Ingester  
- `/flush`
- MeberListKV  
- `/memberlist`
- Compactor  
- `/loki/api/v1/delete`
- …
=> Helm: Fix gateway proxy_pass settings

docs/sources/api/_index.md
Remove /ready and /metrics from API list of the querier and the query frontend because they are exposed by all components.
Remove /loki/api/v1/push from API list of the querier and the query frontend because it is exposed by distributor.
Move /api/prom/push from API list of the querier and the query frontend to API list of the distributor because it is exposed by distributor.
Add /api/prom/series to API list of the querier and the query frontend.
Change reference to /loki/api/v1/label to /loki/api/labels because former is not documented.
**Checklist**
=> Docs: Fix API document

tools/dev/k3d/environments/helm-cluster/main.jsonnet
Bumps the version of Grafana/Grafana-Enterprise being used to what is currently current. 
This gets rid of a warning displayed about "The current Grafana version is not supported" in relation to the GEL plugin.
**Checklist**
=> Bump grafana and grafana-enterprise versions used for GEL Helm env

.devcontainer/devcontainer.json, .drone/drone.jsonnet, .drone/drone.yml, Makefile, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, docs/sources/maintaining/release-loki-build-image.md, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
https://groups.google.com/g/golang-announce/c/MEb0UyuSMsU
=> k146: Upgrade to latest Go security release 1.20.4

.devcontainer/devcontainer.json, .drone/drone.jsonnet, .drone/drone.yml, Makefile, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, docs/sources/maintaining/release-loki-build-image.md, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
https://groups.google.com/g/golang-announce/c/MEb0UyuSMsU
=> k147: Upgrade toGo security release 1.20.4

.devcontainer/devcontainer.json, .drone/drone.jsonnet, .drone/drone.yml, Makefile, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, docs/sources/maintaining/release-loki-build-image.md, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
https://groups.google.com/g/golang-announce/c/MEb0UyuSMsU
=> k148: Upgrade toGo security release 1.20.4

.drone/drone.jsonnet, .drone/drone.yml
CI was failing https://drone.grafana.net/grafana/loki/23216/19/2, we need to apply the changes from https://github.com/grafana/loki/pull/9342 to 2.8.x.
**Checklist**
=> Pin manifest plugin version

pkg/loki/loki.go
Change the default value of `DisableRequestSuccessLog` to true. This way Loki won't log every successful gRPC call by default. The log line isn't useful either since it is redundant with existing gRPC metrics.
N/A
=> Avoid excessive gRPC logging

operator/CHANGELOG.md, operator/internal/manifests/distributor.go, operator/internal/manifests/distributor_test.go, operator/internal/manifests/indexgateway.go, operator/internal/manifests/indexgateway_test.go, operator/internal/manifests/ingester.go, operator/internal/manifests/ingester_test.go, operator/internal/manifests/querier.go, operator/internal/manifests/querier_test.go, operator/internal/manifests/query-frontend.go, operator/internal/manifests/query-frontend_test.go, operator/internal/manifests/var.go
This PR adds the `labelSelector` to the `TopologySpreadConstraints` spec defined in #9315 when using zone awareness.
@periklis 
**Checklist**
=> operator: Add label selector to zone awareness TopologySpreadConstraints

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
When the value parsed by the `JsonExpressionParser` is an escaped json string, the result still contains escape character and may not be valid json. This causes subsequent json parsing steps to fail. For example:
`{app="foo"} | json message | line_format "{{.message}}" | json` fails when `message` remains escaped.
This PR unescapes the results of extracted `JsonExpressions` so they can be parsed by subsequent json parsers
=> fix json expression parser

pkg/logql/log/parser.go, pkg/logql/log/parser_test.go
https://github.com/grafana/loki/pull/9410
=> Backports the fix for unescaped json strings to k148

operator/CHANGELOG.md, operator/apis/config/v1/projectconfig_types.go, operator/bundle/community-openshift/manifests/loki-operator-manager-config_v1_configmap.yaml, operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator-manager-config_v1_configmap.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml, operator/config/overlays/community-openshift/controller_manager_config.yaml, operator/config/overlays/openshift/controller_manager_config.yaml, operator/controllers/loki/lokistack_controller.go, operator/controllers/loki/lokistack_controller_test.go, operator/docs/operator/feature-gates.md, operator/internal/manifests/gateway_tenants.go, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/gateway_test.go, operator/internal/manifests/openshift/build.go, operator/internal/manifests/openshift/build_test.go, operator/internal/manifests/openshift/options.go, operator/main.go
With the availability of the `community-openshift` (See #8881) bundle we control all available hubs for OpenShift clusters. Thus we can assume that a user using either the `redhat-openshift-ecosystem/community-operators-prod` hub or the RedHat internal catalogs installs this Operator on an OpenShift clusters. Therefore we can always assume that the following facilities are available:
- OpenShift Route
- OpenShift Service Certificates Controller
This PR decouples reconciling a Route and a CABundle ConfigMap from the user selection of tenant mode. Formerly the user had to select either tenant mode `openshift-logging` or `openshift-network` to inform the operator that the hosting cluster is OpenShift. In the proposed change the cluster flavor is …
=> operator: Enable Route by default on OpenShift clusters

tools/release, tools/release-note.md
Releases in GitHub are published automatically from Drone. Drone calls the `tools/release` script which uses the `tools/release-note.md` template to generate the release body.
Before this PR, the template used the `$DRONE_TAG` env variable which had a `v` preffix (e. `v2.8.0`). Since we publish the docker images without the `v` preffix, the docker images referenced by the release did not exist. This affected the `v2.8.0`, `v2.8.1` and `v2.8.2` releases.
I manually fixed the `v2.8.0`, `v2.8.1` and `v2.8.2` release pages, but this PR should fix the template so we no longer run into this situation.
Fixes https://github.com/grafana/loki/issues/9384
Not sure where to find the …
=> Fix docker image tag in release template

pkg/ingester/stream.go, pkg/ingester/stream_test.go
Modify how our ingesters build the final error message to not append the streamName for every single entry. All entries are already part of the same stream, so repeating it is unnecessary.
N/A
N/A
**Checklist**
=> Ingester: Avoid repeating `streamName` on error message

CHANGELOG.md, pkg/storage/chunk/cache/memcached.go
Users using extstore (with NVMe drives) may experience latencies higher than the ~250ms max as previously defined.
=> Adding more buckets to loki_memcache_request_duration_seconds histogram

operator/internal/manifests/compactor_test.go, operator/internal/manifests/config_test.go, operator/internal/manifests/distributor_test.go, operator/internal/manifests/indexgateway_test.go, operator/internal/manifests/ingester_test.go, operator/internal/manifests/mutate_test.go, operator/internal/manifests/querier_test.go, operator/internal/manifests/ruler_test.go, operator/internal/manifests/rules_config_test.go
Moves all the unit tests under `operator/manifests` to the `manifests` package making all test files now uniform.
**Checklist**
=> Moves all unit tests under operator/manifests to the manifests package

docs/sources/configuration/_index.md, pkg/loki/loki.go, tools/doc-generator/parse/root_blocks.go
`memberlist_config` section is not present in 2.8.x release, must have gotten removed by mistake when we moved to the doc generation tool. This pr adds it back.
Fixes #9423
**Checklist**
=> docs: add memberlist section to the configuration page

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
Adds the ability to reference images by digest instead of tag.  Useful for images that are bundled in an OCI artifact, where the digest must be used.
Fixes #9440 
**Checklist**
=> Add image reference by digest to Loki Helm chart

docs/sources/installation/helm/monitor-and-alert/with-grafana-cloud.md
The remote write URL placeholders for metrics and logs are in the incorrect positions in the config example.
=> Correct Loki Helm monitoring config placeholders

pkg/logql/log/filter.go, pkg/logql/log/label_filter_test.go
When comparing a case insensitive regular expression to a label value, Loki was only matching values that were in upper case. This was caused by compiling a case insensitive regular expression (such as `(?i)hello`), which produced an upper case `prefix` that was then used in `containsLower` as the `substr` value - but that function was written in such a way that only allowed matches of exact case or where the `line` value was upper case and the `substr` value was lower case.
This PR added a some additional test cases to demonstrate/understand the issue, and adds two additional checks to the `containsLower` function to enable it to work correctly when either input is in either case.
Fixes #9294
**Special notes for …
=> Fix case insensitive label filter

pkg/storage/stores/indexshipper/gatewayclient/gateway_client.go
When running the IndexGateway in ring mode, `ring.MakeBuffersForGet()` in the index gateway client allocated fixed size `[]string`/`[]InstanceDesc` slices with a capacity of 5 for each and every request.
By using a `sync.Pool` the client can reduce the amount of allocations. Additionally, since we run the index gateway ring with a high replication factor to be able to scale them better horizontally, an initial capacity of 5 is most of the time too low, leading to extra allocations when growing the capacity of the slice. 
**Checklist**
=> Reuse string/InstanceDesc buffers in index gateway clients

pkg/ingester/instance.go, pkg/validation/validate.go
Add `org_id` to push error when the error is "max active streams limit exceeded". Apparently all other push errors correctly report the `org_id`, but not this one.
N/A
**Checklist**
=> Distributor: Add org_id to log error

pkg/ingester/instance.go, pkg/storage/stores/tsdb/index/chunk.go
* Reduces double counting streams when possible
* proportionally add stats based on chunk overlap range
* code reuse
=> Better combines stats in ingesters

pkg/ingester/instance.go, pkg/ingester/instance_test.go
The instance wasn't counting unflushed chunks in the stats. This change checks that the chunk's `flushed time` is 0 which means it hasn't been flushed yet.
=> Count unflushed chunks in instance stats

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/templates/backend/query-scheduler-discovery.yaml, production/helm/loki/values.yaml
Currently, we have a bug in our code when running Loki in SSD mode and using the ring for query-scheduler discovery. It causes queries to not be distributed to all the available read pods. I have explained the issue in detail in [the PR which fixes the code](https://github.com/grafana/loki/pull/9471). 
Since this bug causes a major query performance impact and code release might take time, in this PR we are doing a new helm release which fixes the issue by using the k8s service for discovering `query-scheduler` replicas.
Fixes #9195
=> helm: release a new helm charts to use k8s service for discover query-scheduler replicas

CHANGELOG.md, clients/pkg/promtail/targets/file/filetarget_test.go, clients/pkg/promtail/targets/file/tailer.go
There's a goroutine leak in promtail file tailer, which has been encountered in https://github.com/grafana/agent/issues/3885. 
The issue is the following:
- There are two goroutines that tailer manages: one for reading lines, the other for updating positions: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/file/tailer.go#L103
- The tailer can be cleanly stopped & drained via `.Stop()` https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/file/tailer.go#L221
- But if the goroutine reading lines encounters an error from the underlying `tail`, the tailer is stopped without draining using the defer statement here: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/file/tailer.go#L151 
- The …
=> Promtail: Fix goroutine leak in file tailer

cmd/chunks-inspect/loki.go, cmd/chunks-inspect/main.go
Get the version byte of the current inspecting Loki chunk printed.
Fixes -
**Checklist**
=> chunks-inspect: print chunk version (format)

pkg/ingester/instance.go, pkg/ingester/instance_test.go
revert this commit: https://github.com/grafana/loki/commit/aeba51ab0fe785ab251eaf8d7005f203ece0986f
We seem to be dramatically overcounting bytes now which is causing oversharding
This is the same query before and after:
Before: ~20 GB
After: ~8 EB
=> revert count unflused chunks

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
This PR adds `extraVolumeClaimTemplates` value for write loki component, it allows to have more than one volume claims for persistent statefulset configuration. For example, when it's needed to have ingester's and shipper's WAL files on different persistent volumes. 
**Checklist**
=> Helm: Support of extraVolumeClaimTemplates for writer statefulset

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/monitoring/_helpers-monitoring.tpl
**What this PR does / why we need it**: Quotes the value of `tenantId` for the cases where tenantId is made up of only numerical values (i.e. if tenantId is `0`)
the motivation for this is that we have long used the tenant id `0` in our loki instance for some stuff. We probably should fix that, but it's going to be easier (at least for us) to patch this than to rename this tenant or migrate to a new tenant.
N/A - If you'd like me to file an issue to track this there as well, let me know and i'll write one up. i figured this fix was simple enough
**Checklist**
=> Helm: Quote tenantId value in logsInstance

CHANGELOG.md, pkg/logql/rangemapper.go, pkg/logql/rangemapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/ast_test.go, pkg/logql/syntax/parser_test.go
The changes rangemapper made to LogQL expressions created invalid LogQL. It added a `without` clause instead of `without ()`. This PR changes the String function of the Grouping struct. This is then used in the rangemapper.
This caused the following panic:
```
panic: error cloning query: count without (rate({namespace="apps"}[15s])): parse error at line 1, col 16: syntax error: unexpected RATE, expecting IDENTIFIER or )
```
**Checklist**
=> Fix Grouping String function and usage so it prints "without ()"

CHANGELOG.md, docs/sources/installation/helm/reference.md, docs/sources/operations/storage/wal.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/backend/hpa.yaml, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/read/hpa.yaml, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/write/hpa.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
It adds missing HPA (HorizontalPodAutoscaler) templates to write, read, and backend components 
Fixes #7864
**Checklist**
=> Helm: add hpa for read, write and backend

docs/sources/clients/promtail/configuration.md
There were various formats for the "Available Labels" headings. This PR makes them all the same heading level and spelling.
=> Uniformize "Available Labels" headers in Promtail config reference doc

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
It fixes the breaking change I introduced by changing sts podManagementPolicy from Parallel to OrderedReady
Fixes #9524
**Checklist**
=> helm: fix breaking sts change

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/gateway/deployment-gateway.yaml, production/helm/loki/templates/read/deployment-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/table-manager/deployment-table-manager.yaml, production/helm/loki/templates/write/statefulset-write.yaml, production/helm/loki/values.yaml
Allows annotating loki components with custom annotations. For instance:
```yaml
loki:
annotations:
secret.reloader.stakater.com/reload: loki-aws-credentials
```
No issue
**Checklist**
- Helm chart section is empty.
=> helm: support of annotations to deployments and statefulsets

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl
Currently the gateway only listens on IPv4. On IPv6-only clusters, this causes the readiness probe to fail, rendering the gateway unusable.
No issue created
**Checklist**
=> helm: gateway: also listen on IPv6

pkg/iter/entry_iterator.go, pkg/iter/entry_iterator_test.go
We saw a performance decrease when running the merge iterator with a very small pool of ingesters. The reason was that we would allocate a new buffer with each next call.
`main` is missing `merge_sort_dedupe-16` so I ran it once with a small patch to generate the data.
```goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/iter
cpu: AMD Ryzen 7 3700X 8-Core Processor             
│ mergeiter-old.txt │         mergeiter-new.txt          │
│      sec/op       │   sec/op     vs base               │
SortIterator/merge_sort-16                1.350m ± 4%   1.368m ± 4%       ~ (p=0.579 n=10)
SortIterator/merge_sort_dedupe-16         2.566m ± 4%   2.462m ± 5%       ~ (p=0.105 n=10)
SortIterator/sort-16 …
```
=> Reuse allocated buffer space in merge iterator.

pkg/iter/entry_iterator.go, pkg/iter/entry_iterator_test.go
This PR cherry-picks 2830ec379129f3e7cdf05646885bb6cafc0aac34 onto `k151`.
We saw a performance decrease when running the merge iterator with a very small pool of ingesters. The reason was that we would allocate a new buffer with each next call.
`main` is missing `merge_sort_dedupe-16` so I ran it once with a small patch to generate the data.
```goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/iter
cpu: AMD Ryzen 7 3700X 8-Core Processor             
│ mergeiter-old.txt │         mergeiter-new.txt          │
│      sec/op       │   sec/op     vs base               │
SortIterator/merge_sort-16                1.350m ± 4%   1.368m ± 4%       ~ (p=0.579 n=10)
SortIterator/merge_sort_dedupe-16         2.566m …
```
=> Reuse allocated buffer space in merge iterator. (#9538)

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md
There were 2 commits for the helm chart with the same version number. In this case the build scripts only releases 1 new helm chart, containing the first commit. This PR adds a new version so a helm chart will be created that contains the later PR. 
**Checklist**
=> Fix version number of helm chart

pkg/util/flagext/bytesize.go
When marshalling to yaml or json, expect the value not a pointer.
=> Fix marshalling ByteSize

pkg/logql/log/filter.go, pkg/logql/log/filter_test.go, pkg/logql/matchers_test.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/parser_test.go, pkg/loki/runtime_config_test.go, pkg/storage/store_test.go
To optimize regex line and label filters, Loki rewrites them to be non-greedy. This can cause extra characters to appear in the regex when `String()` is called. In addition to confusing logging, this can also cause internal panics when a previously-parsable query becomes too long.
This PR stores the original regex in the label/line filter and uses that in calls to `String`.
This PR also removes regex optimizations from label selectors. Making the optimization at parse time caused the original regex to be lost.
=> Regex line/label filters return original regex when `String` is called

tools/lambda-promtail/lambda-promtail/cloudtrail_test.go, tools/lambda-promtail/lambda-promtail/cw.go, tools/lambda-promtail/lambda-promtail/json_stream.go, tools/lambda-promtail/lambda-promtail/kinesis.go, tools/lambda-promtail/lambda-promtail/kinesis_test.go, tools/lambda-promtail/lambda-promtail/main_test.go, tools/lambda-promtail/lambda-promtail/promtail.go, tools/lambda-promtail/lambda-promtail/s3.go, tools/lambda-promtail/lambda-promtail/s3_test.go
Loki runs into performance issues when too many log entries have the same timestamp. Ironically our own lambda-promtail can be a cause for such data.
In this change we modify the logic a little in case lambda-promtail does not find a timestamp in the source data. Instead of adding the same for all entries it sets a new one.
**Checklist**
=> Set unique timestamp in lambda-promtail.

pkg/runtime/config.go
Backport https://github.com/grafana/loki/pull/9568 into k152.
=> Backport PR 9568 to k152

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/single-binary/hpa.yaml, production/helm/loki/values.yaml
Add HPA for single binary deployment. Off by default.
Fixes #7097
**Checklist**
- [N/A] Documentation added
- [N/A] Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> Fix: HPA for single binary deployment

pkg/loki/modules.go
When deletes are enabled, we track the cache generation number to know when to invalidate the cache. The queriers add this cache generation number to the response, and in the frontend, we check if we should cache the response or not based on such generation number.
Before this PR, the queriers didn't add the cache generation number to the index stats responses, therefore, when deletes were enabled, we could see the following error message in the frontend when checking if we should store a new response in the cache:
```
we found results cache gen number %s set in store but none in headers
```
This PR fixes this by adding the middleware to add the generation number to the index stats handler in the querier.
As seen in the following screenshot, once we …
=> Fix cacheGen for index stats reqs

CHANGELOG.md, docs/sources/configuration/_index.md, pkg/storage/chunk/cache/background.go, pkg/storage/chunk/cache/background_test.go
The background writeback process is used to write chunks that have been fetched from the store to cache. Chunks have a target size, but not all chunks will necessarily be this size, so it is tricky to find the correct value for `writeback_buffer` which specifies how many chunks will be held in the queue at any given time.
For example: setting `writeback_buffer=10000` (the default) with all chunks being the default target size (`chunk_target_size=1.5MiB`), in the worst case could result in 15GiB of memory being used for this buffer. Practically speaking, the queue never grows so deep, but if the cache Loki is writing to becomes overwhelmed this could happen.
Setting a value too low would result in many chunks not being written back to cache, which …
=> Querier: configurable writeback queue bytes size

pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/storage/stores/tsdb/index_client.go
This PR adds events to the traces to have some extra observability for how we compute the index stats. We also add some trace events to the results cache.
**Checklist**
=> Add span events for index stats and result cache

docs/sources/query/log_queries/_index.md
Removed duplicated documentation and corrected typos in the Drop Labels expression section.
**What this PR does / why we need it**: fix typo for log queries documentation
**Which issue(s) this PR fixes**: N/A
=> Fix typo in log_queries docs

pkg/ingester/instance.go, pkg/ingester/instance_test.go
Now that the bug where huge values is fixed and known not to be this. Let's readd it.
Original: https://github.com/grafana/loki/pull/9479
=> Revert "revert count unflused chunks (#9504)"

production/helm/loki/templates/_helpers.tpl
The gateway config (nginx config file) incorrectly states 10 minutes (as in 600 seconds) as 6 minutes.
This small PR corrects that.
N/A
Although this indeed modifies the chart, I don't think it's worth a version bump. Please let me know if you have other ideas.
**Checklist**
=> Fix comment and indentation in gateway config of SSD helm chart

CHANGELOG.md, pkg/ingester/instance.go, pkg/ingester/instance_test.go
Using the label values matchers exposed by #8824 introduces duplicate label values when the lookup goes through the ingester. This PR deduplicates label values when matching active streams and in turn aligns the behavior with the `series_index_stores.go`. Latter is used actively by the querier to lookup label values with matchers.
**Checklist**
=> Fix duplicate label values from ingester streams

pkg/logql/log/filter.go, pkg/logql/log/filter_test.go, pkg/logql/matchers_test.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/parser_test.go, pkg/loki/runtime_config_test.go, pkg/storage/store_test.go
This is a backport of #9584 to k152
**Checklist**
=> k152: Regex line/label filters return original regex when `String` is called (#9584)

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/table-manager/deployment-table-manager.yaml
This PR fixes the path to the configmap template in table-manager deployment file
Fixes #9578 
This is probably the same issue as in #9546.
**Checklist**
=> Fix configmap checksum in table manager deployment template

CHANGELOG.md, pkg/logcli/query/query.go
set TSDB shipper mode to ReadOnly and disabled indexGatewayClient during local query run. Also, I increase index downloading timeout to 1m because the users run the query from local machines that not always have more than 100Mbps
Fixes #9555 
Unfortunately, we do not have similar tests and test architecture to cover it with unit tests properly.
**Checklist**
=> [logcli] fixed query command that is run against user's bucket with TSDB index enabled

operator/CHANGELOG.md, operator/apis/loki/v1/lokistack_types.go, operator/apis/loki/v1beta1/lokistack_types_test.go, operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml, operator/config/crd/bases/loki.grafana.com_lokistacks.yaml, operator/config/manifests/community-openshift/bases/loki-operator.clusterserviceversion.yaml, operator/config/manifests/community/bases/loki-operator.clusterserviceversion.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml, operator/docs/lokistack/sop.md, operator/docs/operator/api.md, operator/internal/manifests/config_test.go, operator/internal/manifests/internal/config/build_test.go, operator/internal/manifests/internal/config/loki-config.yaml, operator/internal/manifests/internal/config/loki-runtime-config.yaml, operator/internal/manifests/internal/sizes.go
These changes allow users to configure `PerStreamRateLimit` and `PerStreamRateLimitBurst` in `IngestionLimitSpec`.
This is needed for [Netobserv](https://github.com/netobserv) to increase the default values in some large clusters scenarios.
None 
I have forced using `MB` unit for consistency with `ingestion_rate_mb`. 
Please let me know if you prefer to keep it flexible to any human readable forms (1MB, 256KB, etc).
**Checklist**
=> operator: Expose per_stream_rate_limit & burst

docs/sources/configuration/_index.md, pkg/distributor/writefailures/cfg.go, pkg/distributor/writefailures/manager.go
Make appending `insight=true` key-value pair to log failures configurable.
N/A
**Checklist**
=> Distributor: Make  key configurable when logging failures

docs/sources/clients/k6/write-scenario.md
k6 is now available as a managed service on Grafana Cloud. 
This is a small doc changes to remove the mention of `k6 Cloud`.
=> Docs: replace `k6 Cloud` mention

clients/pkg/promtail/targets/cloudflare/fields.go, docs/sources/clients/promtail/configuration.md
Hey folks 👋 
Little contribution here to add a useful log field for cloudflare users.
Indeed I add the [ClientRequestSource field](https://developers.cloudflare.com/logs/reference/clientrequestsource/ ) which is pretty useful when debugging some specific traffic handled by cloudflare
Extra: Since I was on the documentation I fixed an indentation issue that I spotted
Don't hesitate to reach me if you have any questions
Cheers 😉 
Loki rocks 🚀 
**Checklist**
=> feat(promtail): add CF ClientRequestSource field

docs/sources/configuration/_index.md, pkg/querier/queryrange/index_stats_cache.go, pkg/querier/queryrange/index_stats_cache_test.go, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/log_result_cache.go, pkg/querier/queryrange/queryrangebase/results_cache.go, pkg/querier/queryrange/queryrangebase/results_cache_test.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/roundtrip_test.go, pkg/storage/async_store.go, pkg/validation/limits.go
When we query the stats for recent data, we query both the ingesters and the index gateways for the stats.
https://github.com/grafana/loki/blob/ebdb2b18007e024d56105afc5230383165ca1650/pkg/storage/async_store.go#L112-L114
https://github.com/grafana/loki/blob/ebdb2b18007e024d56105afc5230383165ca1650/pkg/storage/async_store.go#L126-L127
Then we merge all the responses, which means summing up all the stats
https://github.com/grafana/loki/blob/ebdb2b18007e024d56105afc5230383165ca1650/pkg/storage/async_store.go#L157-L158
https://github.com/grafana/loki/blob/ebdb2b18007e024d56105afc5230383165ca1650/pkg/storage/stores/index/stats/stats.go#L23-L26
Because we have a replication factor of 3, this means that we will get the stats from the ingesters repeated up …
=> Add config to avoid caching stats for recent data

operator/apis/loki/v1beta1/lokistack_types_test.go, pkg/storage/stores/tsdb/head_manager.go, pkg/storage/stores/tsdb/head_manager_test.go, pkg/storage/stores/tsdb/index_client.go, pkg/storage/stores/tsdb/multi_file_index.go, pkg/storage/stores/tsdb/multi_file_index_test.go, pkg/storage/stores/tsdb/single_file_index.go, pkg/storage/stores/tsdb/single_file_index_test.go
Revert #9217 (potential bug in query result)
Cherry pick #9685 to `k153`
=> Revert 9217 chaudum/tsdb chunkrefs pool (#9685)

CHANGELOG.md, production/promtail-mixin/dashboards.libsonnet
In promtail-mixin, the dropdown template for clusters would only include clusters that run loki. So if a cluster only run promtail and not loki, it doesn't appear.
Tested on dashboard:
**Checklist**
=> Fix promtail cluster template not finding all clusters.

operator/CHANGELOG.md, operator/apis/loki/v1/lokistack_types.go, operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community-openshift/manifests/loki.grafana.com_lokistacks.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki.grafana.com_lokistacks.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml, operator/config/crd/bases/loki.grafana.com_lokistacks.yaml
`1x.demo` was added as a new `LokiStack` size for a while back. This PR fixes the validation in the Kubernetes API, so that the value can be used.
**Checklist**
=> operator: Fix availability of demo LokiStack size

docs/sources/installation/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/loki-canary/daemonset.yaml, production/helm/loki/values.yaml
Add support for setting additional labels on the loki-canary pods
=> Helm: add support for additional labels on loki-canary pods

CHANGELOG.md, clients/pkg/logentry/stages/extensions.go, clients/pkg/logentry/stages/extensions_test.go, clients/pkg/logentry/stages/stage.go, docs/sources/clients/promtail/stages/cri.md
I started to see OOM after upgrading to a promtail version with #8497. So played around to make partial line behavior more stable. You can now truncate partial lines and configure max partial lines buffer.
**Checklist**
=> Promtail: improve behavior of partial lines

pkg/logql/log/fmt_test.go
The unit tests for unixToTime do not take the current timezone into account. 
**Checklist**
=> Add handling of timezones in unixToTime tests

tools/packaging/promtail-postinstall.sh
Previously the systemd version extract pulled in debian string breaking the detection on debian variants
Fixes  postinst error on Debian variants
Fixes #9701 #9302
Tests on various OS variants:
Debian/12
```
$ systemctl --version 
systemd 252 (252.6-1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
$  systemctl --version | head -1 | sed 's/systemd \([0-9]\+\).*/\1/'
252
```
CentOS/7
```
$ systemctl --version 
systemd 219
+PAM +AUDIT …
```
=> packaging: fix postinst on debian oses

pkg/loki/loki.go, pkg/loki/modules.go, pkg/storage/async_store.go, pkg/storage/factory.go, pkg/storage/store.go
This seems to cause some issue with `querier`, not getting chunks from ingesters correctly via `async_store`.
I narrowed down to this PR. But hard `revert` seems not possible anymore. So created this manually.
https://github.com/grafana/loki/pull/9476
=> revert(9476): Bringback async store like before for the queriers

production/ksonnet/loki/memberlist.libsonnet
We use a headless service called `gossip-ring` which contains all the memberlist members, previously we passed this headless service into our memberlist code as 
```
join_members:
- gossip-ring.loki-ops.svc.cluster.local:7946
```
What this resulted in was the dskit wrapper around the memberlist library thinking there was only 1 join_node, so it passed this directly to the join method in memberlist. The memberlist lib would then do a DNS resolution on this and it would find **all** the members behind this service.
This is generally not noticeable until you get to very large clusters with thousands of memberlist members and it results in new joiners attempting to join to ALL the existing members instead of just a few.
This PR prefixes the url with …
=> Jsonnet: add dns+ to join_members in memberlist config

production/helm/loki/templates/monitoring/servicemonitor.yaml
As of #9218 `clusterLabelOverride` can be used to set the `cluster` label, however the ServiceMonitor still uses `loki.fullname`. This fixes that so it will use `loki.clusterLabel` to be consistent with other components.
**Checklist**
=> helm: make ServiceMonitor cluster label respect clusterLabelOverride

production/helm/loki/templates/config.yaml
this PR make all resources have some behavior when running `helm template loki grafana/loki --name istio-system`
istio use it here: https://github.com/istio/istio/blob/master/manifests/addons/gen.sh#L89
**Checklist**
=> helm: fix resource not respect namespace

docs/sources/clients/aws/ecs/_index.md
Configuration options show  "Name": "grafana-loki", however, fluentbit specifies this should just be "loki"
A few users have reported receiving an error when using the documented "Name" option, but it works as expected when using the Name specified in the fluentbit docs:
Reference: https://docs.fluentbit.io/manual/pipeline/outputs/loki#fluent-bit-+-grafana-cloud
=> Loki ECS Client: Update Name in Options config

pkg/loki/modules.go
During reverting this [PR](https://github.com/grafana/loki/pull/9715). I missed one important flag switch. Which this PR fixes it.
Fixes NA
We found a bug on querier due to async_store and we tracked down to[ this PR](https://github.com/grafana/loki/pull/9476). So I reverted the PR in [this PR ](https://github.com/grafana/loki/pull/9715)(manually. Auto revert was not possible as things changed a lot meanwhile)
But during my revert PR I missed switching this async store config.
**Checklist**
=> fix(async_store): Fix the `storageconfig.EnableAsyncStore` config

pkg/storage/stores/tsdb/index_client.go
Modify our calls to `index_client.GetChunkRef` to report invocations through a span event instead of through span logging. This way we won't log a new log line for every GetChunkRef call.
N/A
**Checklist**
=> Loki: Report event for `GetChunkRef` instead of SpanLogging

pkg/storage/stores/tsdb/builder.go, pkg/storage/stores/tsdb/builder_test.go, pkg/storage/stores/tsdb/compactor.go, pkg/storage/stores/tsdb/compactor_test.go, pkg/storage/stores/tsdb/manager.go, pkg/storage/stores/tsdb/querier_test.go, pkg/storage/stores/tsdb/single_file_index.go, pkg/storage/stores/tsdb/util_test.go, tools/tsdb/migrate-versions/main_test.go, tools/tsdb/tsdb-map/main.go
This PR adds version as a property to the TSDB Index Builder, forcing users of the builder to specify a version for each builder instance. This is the first of many PRs that will add the TSDB index version to the schema version config.
Re #9565
The full functionality of supporting TSDB index versions in the schema/period config is enabled via 3 PRs. Each PR can be reviewed and merged independently.
[1/3] https://github.com/grafana/loki/pull/9566
[2/3] https://github.com/grafana/loki/pull/9590
[3/3] https://github.com/grafana/loki/pull/9633
**Checklist**
=> Add version to TSDB index builder struct

CHANGELOG.md
noticed that a couple of unreleased changes are incorrectly showing under 2.8.0 release, moving them to the right place.
also adds the missing changelog entry for #7447
**Checklist**
=> changelog: moving unreleased changes to the main section

CHANGELOG.md, pkg/logql/downstream_test.go, pkg/logql/rangemapper.go, pkg/logql/rangemapper_test.go
Fix the logic of the `offset` operator for downstream queries on instant query splitting of (range) vector aggregation expressions already containing an offset.
**Checklist**
=> Bugfix: Fix logic of offset operator in instant query splitting

.drone/drone.jsonnet, .drone/drone.yml, integration/loki_micro_services_test.go
The integration test is writing logs across two index periods but there's a chance that the log `lineB` is written after the beginning of the second period after it's added. This means we never get `lineB` in the results.
This change pushes back the write time of the first logs so they're always stay in the first index period.
=> fix integration test for multiple periods

pkg/util/loser/tree.go, pkg/util/loser/tree_test.go
The tree stores the loser in each node, or maxVal if the sequence has ended. If sequences can contain maxVal, we need to take care not to let an ended sequence overtake an active one.
Some test cases from Charles who pointed out the issue in #9053.
Note this situation cannot happen for real in Loki, since we don't expect log lines with a timestamp that far into the future,
but this is supposed to be a re-usable library.
**Checklist**
- NA `CHANGELOG.md` updated
- NA Changes that require user attention or interaction to upgrade are documented in `docs/sources/upgrading/_index.md`
=> loser tree: allow sequences to contain maxVal

docs/sources/installation/helm/reference.md, production/helm/loki/src/alerts.yaml.tpl, production/helm/loki/templates/monitoring/loki-alerts.yaml, production/helm/loki/values.yaml
Adds the ability to specify other labels on the Prometheus alerts.
Specifying:
```yaml
monitoring:
rules:
additionalRuleLabels:
custom_label: custom_value
```
will add it to all alerts:
```yaml
- alert: LokiRequestErrors
annotations: ...
expr: ...
for: 15m
labels:
severity: critical
custom_label: custom_value
```
This approach is inspired by: [kube-prometheus-stack/rules](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml)
Though in their case they run [sync_prometheus_rules.py](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py) to create the `tpl`.
I can understand if this is not the …
=> Helm: add additionalRuleLabels to PrometheusRule alerts

CHANGELOG.md, clients/pkg/promtail/targets/journal/journaltarget.go
This reduces the amount of open file descriptors per followed journal file from 3 to 2. It also releases file descriptors for removed files (journal vacuuming).
The `defaultJournalEntryFunc` is only called once upon startup. It creates a `Journal` instance to only read a single entry to determine the age of the entry referenced in the positions file. Right after, this instance is not required anymore.
The actually used `Journal` instance used to follow the journal is created inside `journalTargetWithReader`.
=> Promtail: Fix file descriptor leak

production/helm/loki/CHANGELOG.md, production/helm/loki/templates/_helpers.tpl
If you currently deploy the Loki chart under a release name other than "loki" errors occur which is why loki is not accessible via Ingress.
The problem looks like this:
> $ k describe ingress xyz-loki-app
> Name:             xyz-loki-app
> Labels:           app.kubernetes.io/instance=xyz-loki-app
>                   app.kubernetes.io/managed-by=Helm
>                   app.kubernetes.io/name=loki
> [...]
> Rules:
>   Host                                      Path  Backends
>   ----                                      ----  --------
>   loki.example.com
>                                             /api/prom/tail              xyz-loki-app-read:3100 (<error: endpoints "xyz-loki-app-read" not found>)
> …
=> loki chart: fix service/ingress mapping

production/helm/loki/templates/runtime-configmap.yaml
The `runtime` ConfigMap in the Loki Helm chart (introduced in https://github.com/grafana/loki/commit/7aa596752d33e8a0445aec59c23642b83baf4328) starts with an empty line because it improperly removes the current line.
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: loki-runtime
data:
runtime-config.yaml: |
{}
```
While this generates technically valid YAML, it looks weird and interacts badly with some tools. E.g.:
- Python ruamel.yaml library: https://stackoverflow.com/questions/75584262/ruamel-yaml-adds-incorrect-indentation-indicator
- VS Code which is set to trim whitespace on save (yellow highlighting is for objects, not strings):
This PR removes this empty start line:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: …
```
=> Helm - Loki: Fix empty starting line in runtimeConfig

CHANGELOG.md, pkg/loki/loki.go, pkg/loki/modules.go, pkg/storage/stores/shipper/indexgateway/grpc.go
This commit add a counter metric with labels `operation`, `tenant`, `status` for gRPC requests that are served by the index gateway.
**What for?**
The per-tenant RPS on the index gateway is used to derive the per-tenant shard factor.
**Why tracking on the server?**
Unlike tracking index gateway RPS on the client side, tracking on the server side does not yield that many series, even in multi-tenant installations with a lot of tenants, because the amout of index gateway instances is relatively small compared to the amount of queriers and frontends.
The previous approach of tracking requests on the client https://github.com/grafana/loki/pull/9781 has been abandoned.
**Checklist**
=> Add per-tenant request counter metric to index gateway server

CHANGELOG.md, pkg/loki/loki.go, pkg/loki/modules.go, pkg/storage/stores/shipper/indexgateway/grpc.go
**This is a backport of #9797 to k156**
---
This commit add a counter metric `loki_index_gateway_requests_total` with labels `operation`, `tenant`, `status` for gRPC requests that are served by the index gateway.
**What for?**
The per-tenant RPS on the index gateway is used to derive the per-tenant shard factor.
**Why tracking on the server?**
Unlike tracking index gateway RPS on the client side, tracking on the server side does not yield that many series, even in multi-tenant installations with a lot of tenants, because the amount of index gateway instances is relatively small compared to the amount of queriers and frontends.
The previous approach of tracking requests on the client https://github.com/grafana/loki/pull/9781 has been abandoned.
=> Add per-tenant request counter metric to index gateway server (#9797)

cmd/migrate/main.go
Without this fix, the migration tool tries to initialize the ingexGateway client, which is unreachable. 
This leads to the error:
`Failed to create source store: error creating index client: index gateway grpc dial: failed to build resolver: passthrough: received empty target in Build()`
=> disabled indexGateway client for boltdbShipper in migration tool.

docs/sources/configuration/_index.md, pkg/querier/queryrange/limits.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/shard_resolver.go, pkg/querier/queryrange/shard_resolver_test.go, pkg/validation/limits.go
Adds the per tenant limit `tsdb-max-bytes-per-shard` which is used in configuring the shard size for tsdb subqueries. This effectively gives control over how big subqueries should be (assuming they're shardable). The default is no different (`600MB`) than the previously hardcoded initial value.
This should help us iterate to find optimal shard sizes to improve operations in the long term.
=> adds tsdb-max-bytes-per-shard limit

pkg/distributor/http.go, pkg/distributor/writefailures/manager.go, pkg/distributor/writefailures/manager_test.go, pkg/ingester/stream.go
Modify our write path to not log generic messages with the `writefailures.Manager`. With generic messages I mean: contextCancel errors and contextDeadlineExceeded errors.
N/A
**Checklist**
=> Failures logging: avoid logging generic errors

pkg/distributor/distributor.go, pkg/distributor/writefailures/manager.go
Modify the `writefailures.Manager` to
- Log the tenant id. Otherwise, it is hard to identify which tenant is responsible for a problematic push
- Log stream parsing failures
N/A
=> LogPushFailures: Log the tenant id

pkg/storage/stores/indexshipper/compactor/compactor.go, pkg/storage/stores/indexshipper/compactor/table.go, pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/indexshipper/downloads/index_set_test.go, pkg/storage/stores/indexshipper/downloads/table_manager.go, pkg/storage/stores/indexshipper/downloads/table_manager_test.go, pkg/storage/stores/indexshipper/downloads/table_test.go, pkg/storage/stores/indexshipper/storage/cached_client.go, pkg/storage/stores/indexshipper/storage/cached_client_test.go, pkg/storage/stores/indexshipper/storage/client.go, pkg/storage/stores/indexshipper/storage/client_test.go, pkg/storage/stores/indexshipper/storage/index_set.go, pkg/storage/stores/indexshipper/table_client.go
We have a cache for index files available in the object storage, which helps reduce the number of list calls we make to the object storage. Currently, we only support refreshing the whole index cache, which includes all the files for all tables and users. However, in a large cell with many tables and tenants, it is less likely that all the tables are being referenced. Also, most iterative operations would only need a fresh listing of just a few tables at a time so it is wasteful to always refresh the whole index cache.
This PR adds support for refreshing the index cache for only specific tables. I am doing it as part of some compactor improvements to run compaction and retention in separate goroutines to avoid blocking compaction when some expensive …
=> index: allow refreshing index file names cache for specific tables

tools/packaging/promtail-postinstall.sh
When the `promtail-postinstall` script creates a `promtail` user, I do not believe that user requires a home directory to function correctly, and there are cases where the directory cannot be created causing the installation to fail.
n/a - trivial fix
**Checklist**
=> Loki Promtail: Don't Create home directory for `promtail` user in promtail-postinstall.sh

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
When `-validation.increment-duplicate-timestamps` is enabled out of order log entries within the same push request can have their timestamps  incorrectly mutated.
The code is currently just looking for 2 consecutive entries where the timestamp is not increasing.
It should only affect entries where the timestamp is a *duplicate*
Test push request payload:
```json
{
"streams": [
{
"stream": {
"increment_duplicate_timestamp": "fixed|true|false"
},
"values": [
[
"1683665111628000000",
"1a: 1683665111628000000"
],
[
"1683665111628000000",
"1b: 1683665111628000000"
],
[
"1683665111628000003",
"3: 1683665111628000003"
],
[
"1683665111628000002",
"2: 1683665111628000002"
]
]
}
]
}
````
As only the first 2 of these timestamps are the same I would expect all but `1b` to have the timestamps recorded …
=> Only modify identical timestamps when increment-duplicate-timestamps enabled

docs/sources/configuration/_index.md, pkg/storage/stores/indexshipper/storage/cached_client.go
PR #9798 got merged by mistake without me addressing the feedback. There is some critical feedback which needs to be addressed, particularly https://github.com/grafana/loki/pull/9798#discussion_r1243526743.
=> address feedback on pr 9798

production/ksonnet/loki/shipper.libsonnet
https://github.com/grafana/loki/pull/9790 introduced a new config `tsdb_shipper_shared_store`, but it's being referred to even if tsdb index is not enabled. This fixes it by accessing the value only if using_tsdb_shipper is set to true
**Checklist**
=> ksonnet: refer to tsdb_shipper_shared_store only if using_tsdb_shipper is true

CHANGELOG.md, clients/pkg/promtail/client/config.go, clients/pkg/promtail/client/config_test.go
Apply defaults to HTTPClientConfig and validate it. similar to how it's done [here](https://github.com/grafana/loki/blob/e9644d8186174654832e7b6f37a4b4ad34637b0d/vendor/github.com/prometheus/prometheus/config/config.go#L524) in prometheus.
promtail [configuration page](https://grafana.com/docs/loki/latest/clients/promtail/configuration/) incorrectly claims that `follow_redirects` is true, but it is being set to false given that the defaults are not being applied currently
**Checklist**
=> promtail: apply defaults to HTTP client config

CHANGELOG.md, pkg/storage/chunk/client/aws/s3_storage_client.go, pkg/storage/chunk/client/azure/blob_storage_client.go, pkg/util/instrument/instrument.go, pkg/util/instrument/instrument_test.go
Stop emitting spans for every call to our object storages (like S3 or Azure); we don't emit them for GCP already. It causes every chunk fetching to emit a span, which can end with a huge amount of unnecessary spans. It will still report request metrics just fine.
N/A
**Checklist**
=> Queriers: Stop emitting spans for every objectstorage call

pkg/querier/http_test.go, pkg/querier/queryrange/marshal.go, pkg/util/marshal/marshal.go, pkg/util/marshal/marshal_test.go
Commit b35bbd80d65f09eb6f1e6ba1bfe05bf4af712a97 introduced a regression in the deserialization code. It would switch on `logproto.SeriesResponse` instead of the pointer type `*logproto.SeriesResponse`.
**Checklist**
=> Switch on pointer `*logproto.SeriesResponse` in JSON serialization.

pkg/querier/queryrange/codec.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/stats_test.go
The `series_volume` endpoint returns stats about the call. This PR wires things up such that basic stats are returned:
- Execution time
- Number of responses
=> Get basic statistics from series volume requests

docs/sources/alert/_index.md, docs/sources/get-started/_index.md, docs/sources/get-started/architecture.md, docs/sources/get-started/components.md, docs/sources/get-started/deployment-modes.md, docs/sources/get-started/hash-rings.md, docs/sources/get-started/labels.md, docs/sources/get-started/overview.md, docs/sources/query/_index.md, docs/sources/query/analyzer.md, docs/sources/query/ip.md, docs/sources/query/log_queries/_index.md, docs/sources/query/logcli.md, docs/sources/query/metric_queries.md, docs/sources/query/query_examples.md, docs/sources/query/template_functions.md, docs/sources/visualize/grafana.md
@jdbaldry commented on #9717 that the alias format had changed, but we [agreed](https://github.com/grafana/loki/pull/9717#issuecomment-1594960563) that I could update it in a follow up PR. This is that follow up.  Also updating previously merged file moves that used the old alias format.
Breaking the alias updates into two PRs to make for smaller reviews.
=> Update redirects to use new alias format. (part 1 of 2)

docs/sources/clients/docker-driver/_index.md
This pulls @Pandry's [workaround](https://github.com/grafana/loki/issues/2361#issuecomment-718024318) for the seemingly deadlocked Docker daemon into the documentation.
**Checklist**
=> Document deadlocked Docker daemon workaround.

docs/sources/query/ip.md
This updates the Docs with an example of how to use an OR conditional filter when filtering by IP addresses.
Example of this working on [Grafana Play can be found here](https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22grafana%5C%22%7D%20%7C%20logfmt%20%7C%20remote_addr%3Dip%28%6010.10.0.0%2F24%60%29%20or%20remote_addr%3Dip%28%6010.4.1.0%2F24%60%29%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221688342400000%22,%22to%22:%221688428799000%22%7D%7D)
**Special …
=> [Docs] - Add example of Conditional OR to IP Filter

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
Debian Bookworm has a later version of the protobuf compiler which somehow causes the generated protobuf code to substitute `empty.Empty` with `emptypb.Empty` among others. Below is an example of the changes:
```
-	WriteIndex(ctx context.Context, in *WriteIndexRequest, opts ...grpc.CallOption) (*empty.Empty, error)
+	WriteIndex(ctx context.Context, in *WriteIndexRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
```
These [changes](https://protobuf.dev/reference/go/faq/#modules) will happen at some time due to new google.golang.org/protobuf library. To avoid this for now we can use Debian Bullseye instead. Note that Debian Buster is no longer available for Go 1.20.6.
=> Use Debian Bullseye

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
helm-docs and gotestsum use a different libc version when built on the normal golang image so they have to be built on the bullseye image as well. Otherwise errors like these occur:
```
gotestsum: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by gotestsum)
gotestsum: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by gotestsum)
helm-docs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by helm-docs)
helm-docs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by helm-docs)
```
Tested by running them manually in the new build image.
=> Build gotestum, helm-docs and others on bullseye

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/tail/tail.go, vendor/github.com/grafana/tail/watch/polling.go, vendor/modules.txt
This bumps the grafana/tail version used, mostly to address an issue with the retry logic (https://github.com/grafana/tail/pull/16)
Fixes #9864 #9877 #9869, maybe others
I did NOT add a note about this dependency bump in the changelog. Let me know if you want me to add that ... or kindly add that line yourself.
**Checklist**
=> Bump tail dependency to address issue in retry logic

docs/sources/alert/_index.md, docs/sources/get-started/_index.md, docs/sources/get-started/architecture.md, docs/sources/get-started/components.md, docs/sources/get-started/deployment-modes.md, docs/sources/get-started/hash-rings.md, docs/sources/get-started/labels.md, docs/sources/get-started/overview.md, docs/sources/query/_index.md, docs/sources/query/analyzer.md, docs/sources/query/ip.md, docs/sources/query/log_queries/_index.md, docs/sources/query/logcli.md, docs/sources/query/metric_queries.md, docs/sources/query/query_examples.md, docs/sources/query/template_functions.md, docs/sources/visualize/grafana.md
Re: [this comment ](https://github.com/grafana/loki/pull/9890#pullrequestreview-1521562982)from @jdbaldry  on #9890 that "Relative aliases that refer to the current page location won't be effective and should be removed because they can cause confusion and might result in mistaken redirects in the future if pages are moved again."
Removing aliases that refer to the current location of the pages.
=> Remove aliases to current location.

clients/pkg/logentry/stages/match_test.go, docs/sources/clients/promtail/stages/match.md
Some users of Promtail seem to be confused that certain types of filter expressions are not supported in Promtail's `match` stage.
This change clarifies what kind of filter expressions are supported.
Fixes #5209
**Checklist**
=> Clarify that label filter expressions are not supported in promtail.

pkg/storage/store.go, pkg/storage/stores/series/series_index_gateway_store.go, pkg/storage/stores/series/series_index_gateway_store_test.go
The fallback was once used by boltdb-shipper, but since boltdb-shipper changed to not use the index gateway, the fallback was also never used.
**Checklist**
=> Remove unused fallback in index gateway client store

pkg/distributor/distributor.go, pkg/distributor/writefailures/manager.go, pkg/distributor/writefailures/manager_test.go, pkg/distributor/writefailures/metrics.go, pkg/ingester/ingester.go, pkg/loki/modules_test.go
Add metrics for our write failures manager. This way we can easily monitor how much logging we're doing and how much we're discarding.
N/A
**Checklist**
=> WriteFailures: Add metrics to increase monitoring

Makefile, tools/fetch-tags
**This is a backport of #8854**
---
This invocation causes problems when make targets are executed in the build image container (`BUILD_IN_CONTAINER=true`), e.g. the `yacc` target, because git tries to fetch tags from `origin` using ssh, causing error message like these:
```
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```
This is because local ssh keys are not mounted into the build container.
In order not to break CI builds (https://github.com/grafana/loki/pull/8232) we need to manually fetch the tags as the first step in release pipelines. This is added to the Drone configuration.
**What this PR does / why we …
=> Remove ./tools/fetch-tags invocation from Makefile (#8854)

pkg/storage/stores/series/series_index_store.go
This PR changes the invocation of `FetchChunks` in the series index store to happen in parallel. It seems like this was the original intention due to the `// bound concurrency` comment when allocating the `groups` slice. This came out of an investigation of some slow queries, and the traces showed many serial calls to `FetchChunks`.
=> Call FetchChunks in parallel from series index store

CHANGELOG.md, pkg/ingester/tailer.go, pkg/logql/log/labels.go, pkg/logql/log/pipeline.go, pkg/logql/log/pipeline_test.go
Recent query optimizations made pipeline creation more expensive with the assumption that it occurred relatively infrequently. To avoid growing pipline caches without bound, integers recreate pipelines on every push. The combination of these things means that tailing high-volume streams can cause ingester failure.
This fix adds the ability to clear pipeline caches so we don't need to create a new one each time.
=> reset pipeline caches when tailing rather than making a new pipeline

operator/internal/manifests/node_placement.go
Follow up to the PR : https://github.com/grafana/loki/pull/9503
**Checklist**
=> operator: Gateway pods do not need to have INSTANCE_AVAILABILITY_ZONE env set in their containers

operator/CHANGELOG.md, operator/internal/handlers/lokistack_enable_zone_awareness_test.go, operator/internal/manifests/node_placement.go, operator/internal/manifests/node_placement_test.go, operator/internal/manifests/var.go
Issue: https://issues.redhat.com/browse/LOG-3835
Problem: when a user configures zones in spec.replication we want to
make sure that when loki pods are started that they have access to the
zone that they are scheduled in. The zone_labeling_controller is
responsible for annotating the pods of zone-aware components, once these
are scheduled an annotation containing the zone where the pod was
scheduled is added. Furthermore, the controller will also configure the container
env vars to have this annotation available as an ENV variable.
Loki for loki to operate properly this ENV var must be set when the
the container starts, otherwise, loki will not be configured properly.
Solution: in this PR we have added an initContainer …
=> operator: add initContainer to pods of zone aware components

operator/CHANGELOG.md, operator/controllers/loki/lokistack_controller.go, operator/internal/handlers/internal/openshift/alertmanager.go, operator/internal/manifests/config_test.go, operator/internal/manifests/gateway_tenants.go, operator/internal/manifests/openshift/configure.go, operator/internal/manifests/openshift/var.go
When in `openshift-logging` tenant mode, setting any overrides on the `application` tenant currently overrides the automatic alert-manager configuration. This PR changes the behaviour, so that the automatic alert-manager configuration is only skipped when the `application` tenant is already configured with a custom alert-manager.
https://issues.redhat.com/browse/LOG-4325
**Checklist**
=> operator: Fix application tenant alertmanager configuration

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go
In https://github.com/grafana/loki/pull/9700, we added support for writing non-indexed labels from entries into chunks. This PR introduced two bugs:
- When the buffered iterator is closed, the buffer to read metadata labels is put back into the pool but not set to nil. Subsequent uses of the iterator may write on top of the buffer that was put back on the pool. This may lead to inconsistent/incorrect results.
- Inside the buffered iterator, we were not correctly handling EOFs while reading the number of labels and each label length. This was due to the `lastAttemp` variable not being reset.
This PR adds a new test for these two bugs and also fixes them.
Fixes https://github.com/grafana/loki/pull/9700
**Special notes …
=> Fix buffered iterator

CHANGELOG.md, docs/sources/upgrading/_index.md, production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/ingester.libsonnet, production/ksonnet/loki/multi-zone.libsonnet
in k8s version 1.25 some k8s APIs are deprecated, such as policy.v1beta1 which is moved to policy.v1
**Checklist**
=> [jsonnet] removed deprecated policy.v1beta1

pkg/ingester/recovery_test.go, pkg/ingester/wal/encoding.go, pkg/ingester/wal/encoding_test.go
In https://github.com/grafana/loki/pull/9700, we support encoding and decoding non-indexed labels for each entry into the chunks. This PR adds support for writing/reading the non-indexed labels to/from the WAL.
**Checklist**
=> Support non-indexed labels in WAL

.drone/drone.jsonnet, .drone/drone.yml, Makefile, clients/cmd/docker-driver/Dockerfile, clients/cmd/fluent-bit/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, operator/Dockerfile, operator/Dockerfile.cross, operator/calculator.Dockerfile, tools/lambda-promtail/Dockerfile
Update the 2.8 branch so it uses Go version 1.20.6. A 2.8.x release will be built from this later on.
**Checklist**
=> Backport go 1.20.6 to 2.8

pkg/distributor/writefailures/manager.go
Change our writefailures module to use "org_id" instead of "tenant" to be more consistent with the rest of our system.
N/A
**Checklist**
=> Change "tenant" to "org_id"

docs/Makefile
This fixes the `make -C docs ...` command on macOS.
Idk, but it originates from https://github.com/grafana/loki/pull/9945#issuecomment-1645272136
I have tested it. Also, shouldn't break the rest of the systems (Linux).
**Checklist**
=> Drop :z from the podman mount command to make it work on macOS

pkg/querier/queryrange/series_volume.go, pkg/querier/queryrange/series_volume_test.go
To save some frontend work, this PR sorts all the log volumes by volume rather than name. For range queries, only the first value is used.
=> sort sort log volumes by size

clients/pkg/promtail/promtail.go
Fixes #9960
Deletes incomplete comment in code that was introduced from Prometheus as part of https://github.com/grafana/loki/commit/fb26baa5b1bd58b33a34e9c946c81b253d7610bc
=> Delete incomplete comment.

CHANGELOG.md, clients/pkg/promtail/targets/cloudflare/fields.go, docs/sources/clients/promtail/configuration.md
Hey folks 👋
Little contribution here to add a useful log field for cloudflare users.
Indeed I add the [BotTags field](https://developers.cloudflare.com/bots/concepts/cloudflare-bot-tags/) which is pretty useful when debugging some specific traffic handled by cloudflare
Don't hesitate to reach me if you have any questions
Cheers 😉
**Checklist**
=> feat(promtail): retrieve BotTags field from cloudflare

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl
This PR fixes an issue I ran into while installing enterprise Loki in non-single binary mode via Helm. We override the port value for the gateway here `gateway.service.port` and when the provisioner launches and tries to connect to the gateway it was not aware of the overriden port and instead would try to connect over port 80 which would fail, causing the whole helm install to fail as well.
I didn't do a comprehensive search but a quick search did not reveal an existing issue.
I think single binary mode is fine to assume the port as `3100` because it does not appear that can be overriden. It has been some time since I've used single binary mode though so maybe I'm missing …
=> Helm: Fix loki helm chart helper function for loki.host to explicitly include gateway port

.drone/docker-manifest-operator.tmpl, .drone/drone.jsonnet, .drone/drone.yml
Adds support to handle upcoming `operator/v*` tags for Loki Operator releases to start using tags instead of git refs. Starting with: 
- grafana/loki/pull/10050
**Checklist**
=> Add drone support for loki operator/v* tags

pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/util/httpreq/tags.go, pkg/util/httpreq/tags_test.go
Adjust the regex for X-Query-Tags to allow @ and . so that email addresses can be displayed properly. 
Also changed the ToLower to only apply to the key not the value
**Checklist**
=> Loki: Tweak how we handle X-Query-Tags header

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/ingress.yaml, production/helm/loki/values.yaml
Custom labels for ingresses are usually addressed from values files, so we need this feature.
**Checklist**
=> helm: add custom labels for loki ingress

pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/storage/stores/index/index.go
- Stop using `instrument.CollectedRequest` on all Index calls since it emits spans that are redundant with existing ones and aren't improving Loki's monitoring while making it more expensive to run
- Add events to `QuerySample` to improve its monitoring so we can better track what is holding down its performance
- Remove redundant Ingester.GetChunkRef span
N/A
**Checklist**
=> Remove redundant spans

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/pool.go, pkg/chunkenc/symbols.go, pkg/chunkenc/symbols_test.go, pkg/chunkenc/unordered.go, pkg/chunkenc/unordered_test.go
In PR #9700, we added support for storing non-indexed labels in chunks. This PR optimizes resource usage for storing and processing non-indexed labels by doing string interning. We will store deduped label names and values as a list in chunks 
in the newly added non-indexed labels section. The labels would then be referenced in blocks by their index(called symbols).
Additionally, I have started the convention of writing lengths of sections with their offsets within chunks, making it easier to introduce new sections. The section offsets and lengths would be stored at the end of the chunk, similar to [TOC](https://ganeshvernekar.com/blog/prometheus-tsdb-persistent-block-and-its-index/#a-toc) in TSDB.
**Checklist**
=> implementing string interning to optimize resource usage for storing and processing non-indexed labels

cmd/logcli/main.go, pkg/logcli/client/client.go, pkg/logcli/client/file.go, pkg/logcli/index/volume.go, pkg/logcli/query/query_test.go, pkg/logcli/volume/volume.go
This PR fixes `logcli` to use the new endpoints for volume, which are now `volume` and `volume_range` instead of `series_volume` and `series_volume_range`. This PR also adds support for the additional parameters `targetLabels` and `aggregateBy`.
=> logcli: fix volume routes, add targetLabels and aggregateByLabels

docs/sources/installation/_index.md
Change the recommended installation path from Tanka to Helm in the current docs (this update has already been made in main/next).
=> Remove recommendation for Tanak installation.

pkg/ingester/instance.go, pkg/storage/stores/tsdb/single_file_index.go
This improves the logic when calculating volumes by only aggregating series or labels based on which was requested. Previously we aggregated both, and then picked the correct set for the response, causing unnecessary additional memory consumption.
=> Only aggregate labels or series based on requested

.drone/drone.jsonnet, .drone/drone.yml
Provides a small fix for the drone CI pipeline `manifest-loki-operator` to wait until the corresponding docker images pipelines are built. Effectively adds the `refs/tags/operator/v*` trigger to the Loki Operator image pipelines.
**Checklist**
=> drone: Fix manifest-operator pipeline waiting for deps

pkg/logql/log/labels.go, pkg/logql/log/metrics_extraction_test.go, pkg/logql/log/pipeline_test.go
In https://github.com/grafana/loki/pull/9702 we added support for returning non-indexed labels in the labels results. The problem is that non-indexed labels may overwrite stream labels if both are named the same way. This PR fixes this by adding an `_extracted` suffix if the non-indexed label is already present in the stream labels.
**Checklist**
=> Add `_extracted` to non-indexed labels with same name as stream labels

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/unordered.go, pkg/chunkenc/unordered_test.go
Since the non-indexed labels are part of the returned labels results, we don't need to send them also along with each returned entry. This PR will:
-  Reduce the size of the response payload
- Solve a problem in Grafana only showing the last log line
**Checklist**
=> Do not send back non-indexed labels for each entry in query response

pkg/storage/chunk/cache/cache_test.go, pkg/storage/chunk/cache/mock.go, pkg/storage/chunk/fetcher/fetcher.go, pkg/storage/chunk/fetcher/fetcher_test.go, pkg/storage/config/store.go, pkg/storage/store.go, pkg/storage/stores/series_store_write_test.go, pkg/storage/util_test.go
As we play around with our caching strategies, there has surfaced a potential benefit to having 2 layers of chunks cache with a `duration from now` handoff.  i.e. chunks older than _x_ days get sent to an L2 chunks cache.
**Checklist**
=> Loki: add an expirmental l2 chunks cache

pkg/logql/metrics.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/series_volume.go, pkg/querier/queryrange/stats.go
I noticed we were logging volume requests as metric requests in `metrics.go`. This PR logs volume requests on their own with relevant data.
=> Logging improvements for volume requests

pkg/ruler/registry.go
Resubmit of PR https://github.com/grafana/loki/pull/10098 (https://github.com/grafana/loki/pull/10098#issuecomment-1657051336)
/cc @dannykopping 
> provided the PR comes with a test to ensure no regression
The existing tests in `pkg/ruler/registry_test.go` already cover this change. However, if they are insufficient, I am more than willing to add additional tests.
https://github.com/grafana/loki/blob/77b04b796350616c7c22994a1b6950774b5621c3/pkg/ruler/registry_test.go#L171-L179
https://github.com/grafana/loki/blob/77b04b796350616c7c22994a1b6950774b5621c3/pkg/ruler/registry_test.go#L599-L652
Original PR description:
> Comparing two strings to the same case with `strings.ToLower` is more computational expensive than `strings.EqualFold`.
> 
> Sample …
=> Ruler: compare header with `strings.EqualFold`

operator/internal/manifests/internal/sizes.go
This PR fixes the replication factor for the 1x-extra-small T-shirt size.
It should be 2 not 1.
Fixes #
**Checklist**
=> operator: Fix replication factor for 1x-extra-small size

production/ksonnet/loki/common.libsonnet, production/ksonnet/loki/ingester.libsonnet
removed redundant pdb name override because the constructor of `podDisruptionBudget` requires the name to be defined during object creation.
Re: https://github.com/grafana/loki/pull/9978/files
=> [GEL jsonnet] fixed PDB creation

.github/workflows/dependabot_reviewer.yml
Update the "dependabot_reviewer" Github Action workflow.
This should fix the issues we having when trying to enable "auto-merge" for example
https://github.com/grafana/loki/actions/runs/5680113173/job/15393583446?pr=10080
I have tested this using another repository
example.
https://github.com/kavirajk/dependabot-play/pull/7
With workflow change.
https://github.com/kavirajk/dependabot-play/blob/main/.github/workflows/dependabot_reviewer.yml#L27-L35
Fixes #NA
**Checklist**
=> fix(dependabot): Combine approve and enable auto-merge into one step

pkg/ingester/stream.go
Modify the "errTooFarBehind" error to include the stream name if it will be emitted by the write failures manager. This will make the behavior for the write failures more consistent without breaking the existing behavior.
N/A
**Checklist**
=> Include stream name on error message

CODEOWNERS
Add dependabot as codeowner for dependencies related files (`go.mod`, `go.sum` and `/vendor`)
This is needed because, we have branch protection rule (for `main` branch) with "Required review of code owners" as one of the checks
Fixes #NA
Follow up to #10126 
NOTE: Github linter may show "@dependabot is unknown and may not have write permission for the repo" But that's fine. I tested it on my personal repository.
example: Before having it as CODEOWNERS.
https://github.com/kavirajk/dependabot-play/pull/10 (GH action waited for another user from CODOWNER to review before merging)
example: After adding it to CODEOWNERS
https://github.com/kavirajk/dependabot-play/pull/13 (GH action …
=> chore(CODEOWNERS): Add dependabot as codeowners for dependencies

operator/Makefile
Based on #9457 we need to set the minimum required OCP version to 4.12 for the community OpenShift bundle releases.
**Checklist**
=> operator: Drop OCP 4.10 & 4.11 support in community-openshift bundle

.github/workflows/dependabot_reviewer.yml
We are still facing permission error in enabling auto-merge for dependabot PRs example: https://github.com/grafana/loki/actions/runs/5737803871/job/15550129786?pr=10138
After discussing it with internal security team, they asked to try changing the event type from `pull_request_target` -> `pull_request`.
Personally, I suspect this would make any difference, given It worked with `pull_request_target` when testing it with my personal repo.
https://github.com/kavirajk/dependabot-play/blob/main/.github/workflows/dependabot_reviewer.yml#L5
Auto-merged PR.
https://github.com/kavirajk/dependabot-play/pull/15
But still wanted to test this.
**Checklist**
=> chore(dependabot): Change event type to `pull_request`.

pkg/chunkenc/dumb_chunk.go, pkg/chunkenc/interface.go, pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/symbols.go, pkg/chunkenc/symbols_test.go, pkg/chunkenc/unordered.go, pkg/iter/entry_iterator.go, pkg/storage/lazy_chunk_test.go, pkg/storage/stores/indexshipper/compactor/retention/retention_test.go
This PR fixes some bugs discovered while setting the default chunk format yo _V4_ and the default head format to _unordered with non-indexed labels_.
Note that this PR doesn't change the defaults, but fixes some bugs that would prevent us from changing them in the future.
The bugs it fixes are:
- Index out-of-range panic when symbols' labels are empty and we do a Lookup. **Test added**.
- When applying retention, new chunks wouldn't contain non-indexed labels (caused by https://github.com/grafana/loki/pull/10090). **Test added**.
- New chunks would fail to serialize non-indexed labels when applying retention because the head format would be the [dummy one (ordered)][1] [(used here via `c.headFmt`)][2]. **Cannot test unless we change the default …
=> Fix bugs in non-indexed-labels

pkg/chunkenc/dumb_chunk.go, pkg/chunkenc/interface.go, pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/symbols.go, pkg/chunkenc/symbols_test.go, pkg/chunkenc/unordered.go, pkg/iter/entry_iterator.go, pkg/storage/lazy_chunk_test.go, pkg/storage/stores/indexshipper/compactor/retention/retention_test.go
Manually backporting #10142 since the CI is failing to do it automatically.
https://github.com/grafana/loki/actions/runs/5739598473/job/15555724625#step:4:28
=> Backporting: Fix bugs in non-indexed-labels (#10142)

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator-controller-manager-metrics-service_v1_service.yaml, operator/bundle/openshift/manifests/loki-operator-manager-config_v1_configmap.yaml, operator/bundle/openshift/manifests/loki-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, operator/bundle/openshift/manifests/loki-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operator/bundle/openshift/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_role.yaml, operator/bundle/openshift/manifests/loki-operator-prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml, operator/bundle/openshift/manifests/loki-operator-webhook-service_v1_service.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki.grafana.com_alertingrules.yaml, operator/bundle/openshift/manifests/loki.grafana.com_lokistacks.yaml, operator/bundle/openshift/manifests/loki.grafana.com_recordingrules.yaml, operator/bundle/openshift/manifests/loki.grafana.com_rulerconfigs.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml, operator/config/overlays/openshift/kustomization.yaml
Removes the obsolete `v` prefix from any version references (e.g. labels, annotations) to simplify downstream build scripts.
**Checklist**
=> operator: Remove `v` prefix from openshift bundle version refs

tools/lambda-promtail/moves.tf, tools/lambda-promtail/sqs.tf, tools/lambda-promtail/variables.tf
Currently, the Terraform module for lambda-promtail is not working due to a misnamed reference:
```
╷
│ Error: Reference to undeclared resource
│ 
│   on .terraform/modules/lambda_promtail/tools/lambda-promtail/sqs.tf line 66, in resource "aws_iam_role_policy_attachment" "lambda_sqs_execution":
│   66:   role       = aws_iam_role.iam_for_lambda.name
│ 
│ A managed resource "aws_iam_role" "iam_for_lambda" has not been declared in
│ module.lambda_promtail.
╵
```
It looks like this was the result of a conflict with #8231 and #8750.
While I was in there I also refactored the SQS work to be more consistent with #8750.
I also made the queue name prefix configurable with the `sqs_queue_name_prefix` variable, as it was hardcoded before which could cause …
=> lambda-promtail: fix/refactor SQS integration in Terraform module

tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/s3.go, tools/lambda-promtail/lambda-promtail/s3_test.go
The S3 object key for Organization CloudTrail events includes the org's ID at the beginning. Currently, trying to ingest Organization CloudTrail events with lambda-promtail fails due to the object key not matching the regex. This PR adds support for both matching and parsing out that org ID.
- instead of adding a new regex I just amended the existing regex just to avoid too heavy of a refactor
- I also threw in error logging on the handler because that was _invaluable_ debugging why lambda-promtail wasn't working in our environment. I figure others might get some benefit from it.
**Checklist**
=> lambda-promtail: Support AWS Organization CloudTrail

CODEOWNERS
This is not needed as
(1) Adding it on codeowners have no impact for dependabot 
(2) CODEOWNER linter errors complanining about dependabot not existing and don't have write access to the repo
**Checklist**
=> chore(CODEOWNERS): Remove dependabot

docs/sources/clients/docker-driver/_index.md
Fixes #10112 by backporting PR [#9870](https://github.com/grafana/loki/pull/9870) to the current release branch.  (Fix is in "next" docs but not in "latest" docs.)
=> Backporting #9870 to latest

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/ingester/encoding_test.go
When the head block is empty, we do not serialize it while checkpointing. This causes a mismatch in chunk and head block format which ideally should be on the same version. The problem happens when we rollback from v4 chunk and block format to v3 and the head is empty in checkpoint which then [gets set to the default version](https://github.com/grafana/loki/blob/ce91076dd4cb6016f1f39b7a5126c2fd88a8b18e/pkg/ingester/checkpoint.go#L106) i.e v3 while the checkpointed chunk would be v4.
**Checklist**
=> serialize empty head block as well while checkpointing to retain the head block format

cmd/migrate/main.go, pkg/storage/batch.go, pkg/storage/chunk/cache/cache_test.go, pkg/storage/chunk/cache/mock.go, pkg/storage/chunk/fetcher/fetcher.go, pkg/storage/chunk/fetcher/fetcher_test.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/series/series_store_test.go, pkg/storage/stores/series/series_store_utils.go, pkg/storage/stores/shipper/index/compactor/util_test.go
This started as a simple PR to optimize the new L2 chunks cache code such that we don't look up chunks in L1 that we know won't be there, however, the complexity of the FetchChunks method taking both a slice of requested Chunks as well as a slice of requested Keys made this really challenging.
Looking at how we use this method, I saw no reason for there to be a requirement to pass both a list of chunks and keys, we only ever want the Chunks and everywhere we used this we were generating the list of keys external to this function from the list of chunks being passed in.
The second change was to the implementation of how we process the cache results to look for found vs missing keys.  The current implementation required the chunks to be sorted by …
=> Loki: simplify the FetchChunks method and optimize the experimental l2 cache a little more

CHANGELOG.md, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, production/helm/loki/src/helm-test/Dockerfile, tools/lambda-promtail/Dockerfile
Fixes #10181
Fixes Open SSL vulnerabilities [CVE-2023-1255](https://security.alpinelinux.org/vuln/CVE-2023-1255), [CVE-2023-2650](https://security.alpinelinux.org/vuln/CVE-2023-2650), [CVE-2023-2975](https://security.alpinelinux.org/vuln/CVE-2023-2975), [CVE-2023-3446](https://security.alpinelinux.org/vuln/CVE-2023-3446), [CVE-2023-3817](https://security.alpinelinux.org/vuln/CVE-2023-3817)
Alpine Release Notes:
[3.16.7](https://www.alpinelinux.org/posts/Alpine-3.15.10-3.16.7-3.17.5-3.18.3-released.html)
[3.16.6](https://www.alpinelinux.org/posts/Alpine-3.15.9-3.16.6-3.17.4-3.18.2-released.html)
**Checklist**
=> Upgrade alpine 3.16.5 -> 3.16.7

production/loki-mixin-compiled-ssd/dashboards/loki-reads.json, production/loki-mixin-compiled/dashboards/loki-reads.json, production/loki-mixin/dashboards/loki-reads.libsonnet
This PR adds a Per Pods P99 Latency plot to each row of the Loki/Reads dashboard.
=> Add per pod latency plot to reads dashboard

pkg/querier/queryrange/codec.go, pkg/querier/queryrange/codec_test.go, pkg/querier/queryrange/views_test.go
A type switch error was not emitting the actual type which makes debugging hard. This change adds the information.
Furthermore the merge logic wasn't merging already merged views. This happens when split and sharding layers are nested.
**Checklist**
=> Include response type in merging error message and merge already merged views.

CODEOWNERS
Explicit code-owners for loki operator
**Checklist**
=> CODEOWNERS: Add codeowners for loki operator

CHANGELOG.md, docs/sources/release-notes/v2-8.md
2.8.3 was released without release notes, causing confusion in #10234, which should actually be preparing 2.8.4.
=> Update changelog and release notes for 2.8.4

pkg/loki/runtime_config.go, pkg/loki/runtime_config_test.go
Adds a new section to our runtime configuration that will allow customization of default runtime values.
For instance, our default `log_push_request` is `false`. Previously, there was no way of setting it to `true`, so you'd have to set it for every existing tenant.
For a full example, please check the added test.
N/A
**Checklist**
=> Configuration: Allow customization of default runtime values

pkg/chunkenc/memchunk.go, pkg/chunkenc/memchunk_test.go, pkg/chunkenc/unordered_test.go, pkg/ingester/chunk_test.go, pkg/ingester/encoding_test.go, pkg/ingester/flush_test.go, pkg/ingester/stream_test.go, pkg/ingester/wal/encoding.go, pkg/logql/metrics.go, pkg/storage/hack/main.go, pkg/storage/stores/indexshipper/compactor/retention/retention_test.go, pkg/storage/stores/series_store_write_test.go, pkg/storage/stores/shipper/index/compactor/util.go, pkg/storage/util_test.go
This PR updates the default chunk and heads format to v4 to support writing and reading non-indexed labels.
=> Update chunk and head fmt to v4 (non-indexed labels)

.github/workflows/dependabot_reviewer.yml
I reverted back auto merge, because of permission issues with "who" can push to the repo.
After some internal discussion, we decided to use `grafanabot` for enabling auto-merge. This PR does that.
**Checklist**
=> dependabot: Re-enable `auto-merge`.

pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/storage/stores/tsdb/single_file_index.go, pkg/storage/stores/tsdb/single_file_index_test.go
This PR changes the behavior the `index/volume` endpoint to return intersecting labels when requesting volume aggregating by label. Previously it only returned labels that matched selectors in the query. The old behavior is still possible using the `targetLabels` argument.
=> Return intersecting labels when aggregating volume by label

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/gateway/ingress-gateway.yaml, production/helm/loki/templates/ingress.yaml, production/helm/loki/values.yaml
**What this PR does / why we need it**: Use tpl for ingress hosts. Needed for values passed from globals in umbrella charts. We´re already using this in [Grafana Helm Chart](https://github.com/grafana/helm-charts/blob/d8a64071970b5928cf990dce480925ff6b8edb56/charts/grafana/templates/ingress.yaml#L37). 
**Checklist**
=> helm: use tpl for ingress hosts

pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/ast_test.go, pkg/querier/queryrange/querysharding_test.go
A few bugfixes and more sharding optimizations
* fix bug on `<aggr> by|without ()` groupings which removed the grouping while downstreaming
* shardable implementations for `max+min`, operation specific merge strategies which enable many more types of sharded requests, even when label-reduction is performed at edge.
=> Sharding optimizations

CHANGELOG.md, pkg/storage/chunk/client/hedging/hedging.go
We currently have request hedging implemented in many object store clients. Right now we track how many hedged requests we make, and how many are rate-limited, but nothing actually tells us _how effective_ the hedged requests are. In other words, we don't know how many hedged requests were issued and _won_ (completed before the original).
N/A
I thought adding these details to the underlying hedging library's stats would work, but as I point out in https://github.com/cristalhq/hedgedhttp/pull/46#issuecomment-1682152313 we have too many hedged clients in play, when we have only one set of metrics published that all instances share.
**Checklist**
=> Track effectiveness of hedged requests

cmd/loki-canary-boringcrypto/Dockerfile
Add compatibility libs to BoringCrypto Loki Canary image.  As it is dynamically linked, the runtime libs need to be added so the executable can run
**Checklist**
=> Add compat libs to Loki Canary BoringCrypto Docker image

README.md, docs/sources/api/_index.md, docs/sources/best-practices/_index.md, docs/sources/clients/aws/ec2/_index.md, docs/sources/clients/aws/ecs/_index.md, docs/sources/clients/aws/eks/_index.md, docs/sources/clients/docker-driver/configuration.md, docs/sources/clients/fluentbit/_index.md, docs/sources/clients/lambda-promtail/_index.md, docs/sources/clients/promtail/configuration.md, docs/sources/installation/helm/concepts.md, docs/sources/installation/helm/reference.md, docs/sources/maintaining/release-loki-build-image.md, docs/sources/operations/observability.md, docs/sources/operations/scalability.md, docs/sources/operations/storage/table-manager/_index.md, docs/sources/release-notes/v2-3.md, docs/sources/storage/_index.md, docs/sources/upgrading/_index.md, operator/docs/operator/hack_operator_make_run.md, operator/docs/operator/storage_size_calculator.md
Manual backport of https://github.com/grafana/loki/pull/9080 to "latest" after a customer reported a 404 to the docs@grafana email today.
=> Update GitHub URLs from master to main

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml
table_manager is deprecated. It would be nice the add the possibility to remove the key from the config.
**Checklist**
=> [helm] Make table_manager configuration toggle.

production/loki-mixin-compiled/dashboards/loki-writes.json, production/loki-mixin/dashboards/loki-writes.libsonnet
Modify the Index panel on `Loki/Writes` to account for any ingesters, to avoid ignoring zone-aware ingesters.
N/A
**Checklist**
=> Add zone-aware ingesters to Index panel.

pkg/storage/chunk/client/azure/blob_storage_client.go
Azure Blob Storage is being used in production by many organisations, including Grafana Labs. It should no longer be marked experimental.
Fixes #10298
=> Azure Blob Storage is no longer experimental

pkg/scheduler/queue/metrics.go, pkg/scheduler/queue/queue.go, pkg/scheduler/queue/tenant_queues.go
We want to investigate whether work stealing among queriers would be useful. So we are recording the wait time of queriers for new requests in their queue.
**Checklist**
=> Record waiting time for queriers to receive requests.

docs/sources/clients/docker-driver/configuration.md, docs/sources/clients/promtail/configuration.md, docs/sources/clients/promtail/installation.md, docs/sources/fundamentals/labels.md, docs/sources/installation/_index.md
Addresses duplicate headings that are affecting search engine optimization (SEO).
These issues have been fixed in `next`, this PR only updates the current release branch.
Addresses the logs issues listed on [this issue.](https://github.com/grafana/website/issues/14851)
=> Rewrite duplicate headings for SEO.

pkg/logql/log/label_filter.go, pkg/logql/syntax/parser_test.go
Reverts grafana/loki#10277
This currently breaks and cause panics for query with regex label matcher. Reverting it till we find the fix.
=> Revert "Stopped String() from doubly escaping regex characters"

pkg/logql/log/label_filter.go, pkg/logql/syntax/parser_test.go, pkg/storage/chunk/client/congestion/congestion.go, pkg/storage/chunk/client/congestion/controller.go, pkg/storage/chunk/client/congestion/hedge.go, pkg/storage/chunk/client/congestion/interfaces.go, pkg/storage/chunk/client/congestion/retry.go
Reverts #10277 as it caused panics on regex label filters
Adds #10319 to include minor fixes for congestion control
=> Recut k164

CHANGELOG.md, pkg/storage/stores/series/series_index_store.go
~Lock around data that is modified from multiple goroutines concurrently.~
Replaced with the implementation from #9984 since @akhilanarayanan did it more efficiently.
Relates to #8586
**Checklist**
- NA If the change is worth mentioning in the release notes, add `add-to-release-notes` label
- NA Changes that require user attention or interaction to upgrade are documented in `docs/sources/setup/upgrade/_index.md`
- NA For Helm chart changes bump the Helm chart version in `production/helm/loki/Chart.yaml` and update `production/helm/loki/CHANGELOG.md` and `production/helm/loki/README.md`. [Example PR](https://github.com/grafana/loki/commit/d10549e3ece02120974929894ee333d07755 …
=> Series Index Store: fix race in GetSeries

CODEOWNERS
To keep LogQL grammar in sync with https://github.com/grafana/lezer-logql, we would like to add @grafana/observability-logs as a co-codeowner for grammar file `/pkg/logql/syntax/expr.y` to get notification when this file change.
=> Update CODEOWNERS to include logs team for grammar file

production/ksonnet/loki/overrides.libsonnet
Add a `default` section to our runtime jsonnet file.
The `default` section was introduced by https://github.com/grafana/loki/pull/10193.
N/A
**Checklist**
=> Jsonnet: Add `default` section to runtime jsonnet file

pkg/scheduler/queue/metrics.go
We should set buckets for the `querier_wait_seconds` histogram.
**Checklist**
=> Set buckets for querier_wait_seconds histogram.

pkg/storage/config/schema_config.go, pkg/storage/config/schema_config_test.go
Fix periodConfigs `Validate()` for new schema `v13`.
Found when testing archiver with latest loki
**Checklist**
=> chore(schema-v13): Fix `periodConfig.Validate` for `v13` schema

pkg/logql/log/label_filter.go, pkg/logql/syntax/parser_test.go
[This PR](https://github.com/grafana/loki/pull/10277) fixed an issue where regexes were being escaped multiple times and causing otherwise valid queries to fail our length check. It put the resulting regexes in double quotes which meant that any regexes that _needed_ escaping were now invalid. 
This PR make is so the unescaped regex is put in a raw string literal so any extra escaping in unnecessary.
=> Put unescaped regexes in a raw string literal

.drone/drone.yml, Makefile, loki-build-image/Dockerfile
`trivy` is a command line utility that can scan our images for vulnerabilities. For example, this is how I checked #10217 addressed the CVEs we were hoping it would
```
❯ trivy i grafana/loki:release-2.8.x-d784431
2023-08-11T12:34:15.272-0600    INFO    Vulnerability scanning is enabled
2023-08-11T12:34:15.272-0600    INFO    Secret scanning is enabled
2023-08-11T12:34:15.272-0600    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-08-11T12:34:15.272-0600    INFO    Please see also https://aquasecurity.github.io/trivy/dev/docs/scanner/secret/#recommendation for faster secret detection
2023-08-11T12:34:15.283-0600    INFO    Detected OS: alpine
2023-08-11T12:34:15.283-0600    INFO    Detecting Alpine vulnerabilities... …
```
=> add `trivy` to Makefile and build image

pkg/storage/stores/series/index/schema_config.go, pkg/storage/stores/series/series_store_test.go
The creation of a series store schema failed when using v13 schema version.
When adding the `v13` to the series store test cases (`pkg/storage/stores/series/series_store_test.go`) they fail. Example error:
```
=== RUN   TestSeriesStore_LabelValuesForMetricName/foo_/_toms_/_v13_/_store
series_store_test.go:700: ========= Running labelValues with metricName foo with labelName toms with schema v13
series_store_test.go:93: 
Error Trace:	/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:93
/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:77
/home/christian/sandbox/grafana/loki/pkg/storage/stores/series/series_store_test.go:702
Error:      	Received …
```
=> chore(schema-v13): Fix series store schema creation for v13

docs/sources/configure/_index.md, pkg/storage/config/schema_config.go
`v12` is stable schema with more efficient/stable chunks and index formats. Start recommending it instead of old `v11`.
**Checklist**
=> doc(schema): Start recommending `v12` schema instead of `v11`

CHANGELOG.md, docs/sources/configure/_index.md, pkg/storage/stores/indexshipper/compactor/compactor.go, tools/doc-generator/parse/root_blocks.go
Compactor config use `-boltdb.shipper.compactor.` as prefix which is misleading as the config options apply to tsdb index as well.
This pr introduces `-compactor.` prefix which can now be used to configure compactor configuration options and deprecates `-boltdb.shipper.compactor.`
**Checklist**
=> compactor: deprecate -boltdb.shipper.compactor. prefix in favor of -compactor.

tools/querytee/proxy_endpoint.go, tools/querytee/proxy_endpoint_test.go
`Test_ProxyEndpoint_SummaryMetrics` does not wait for `compareResponses` call to finish which causes the test to fail as the expected metric response does not match
this pr updates the test to wait for `responses_compared_total` to be set to 1 before asserting `missingMetrics`
**Checklist**
=> chore: fix flaky querytee proxy test

CHANGELOG.md, pkg/logql/downstream_test.go, pkg/logql/range_vector.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/test_utils.go, tools/dev/loki-boltdb-storage-s3/config/loki.yaml, tools/dev/loki-boltdb-storage-s3/docker-compose.yml
The range aggregation `avg_over_time` is simply shardable if there's no label reduction.
If there is one it can be express as
```
sum by (method) (
sum_over_time(
{container="app"} | json | unwrap bytes [$__interval])
) 
/
sum by (method) (
count_over_time(
{container="app"} | json [$__interval]
)
) 
```
Note that `sum by`, `sum_over_time` and `count_over_time` are shardable once more.
**Checklist**
=> Enable sharding for avg_over_time.

CHANGELOG.md
We recently implemented a new feature to support attaching and querying non-indexed labels attached to each log line.
This PR updates the changelog with entries referencing the main PRs of this feature.
=> Add changelog for non-indexed labels

CHANGELOG.md, docs/sources/configure/_index.md, docs/sources/configure/examples.md, docs/sources/configure/examples/10-S3-And-DynamoDB-With-KMS-Snippet.yaml, docs/sources/configure/examples/9-Expanded-S3-Snippet.yaml, docs/sources/setup/upgrade/_index.md, pkg/loki/config_wrapper_test.go, pkg/storage/chunk/client/aws/s3_storage_client.go
AWS now defaults to SSE S3 for every bucket. All objects are automatically encrypted at no additional cost. Thus, this change will deprecate the enable toggle from Loki.
**Checklist**
=> Remove deprecated s3 sse toggle

CHANGELOG.md, docs/sources/setup/upgrade/_index.md, pkg/ruler/base/ruler.go, pkg/ruler/config.go
=> Remove experimental enable ruler api toggle

pkg/ingester/ingester.go
There is a bug when passing a query parameter to the `/label/:label/values`. Currently the ingester is not respecting this query string, and so is always returning all label values. This PR fixes that bug.
=> fix: respect query matcher in ingester when getting label values

pkg/sizing/node.go
The sizing tool was listing an AWS EC2 instance that does not exsit.
Fixes #10315
**Checklist**
=> Remove `t2.4xlarger` from sizing tool.

tools/promtail.sh
This PR fixes a bug in [promtail.sh](https://github.com/grafana/loki/blob/94a5f94cf408e2da3e4293e8163e18c47c74e4d6/tools/promtail.sh). 
promtail.sh is a script to deploy promtail in kubernetes clusters as a daemonset. The defaults should make sense in that environment. 
Currently, The default log parser in pipeline stages is, `- docker: `. Kubernetes uses CRI format so it makes more sense to default to CRI parser and this PR does exactly that.
This PR does not affect any existing users of loki and it'll improve it for people who decide to use this script with the default arguments in the future because kubernetes uses cri format and grafana can't parse JSON logs properly if they were fed to loki with docker parser instead of the more appropriate cri …
=> bugfix/promtail.sh: Updated script to work better by default in k8s environment

docs/sources/configure/_index.md, pkg/storage/chunk/client/congestion/config.go
Adds `congestion-control` prefixes to new flags.
Currently to enable congestion control via a flag, one must use `-store.enabled` which is obviously misleading.
=> Fix CLI flags for congestion control

.drone/drone.jsonnet, .drone/drone.yml
It appears that this commit (https://github.com/grafana/loki/commit/d484d31856926b9694d6d2d162ade10de3de247c) is causing a failure when on the manifest.manifest-fluent-bit step (2023/08/28 09:53:47 pushing by spec
time="2023-08-28T09:53:47Z" level=fatal msg="Inspect of image \"grafana/fluent-bit:main-586b904-amd64\" failed with error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
exit status 1).
Subsequent investigation has shown that the grafana/fluent-bit docker repo does not exist.  
This PR is to change the manifest step to reference 'fluent-bit-plugin-loki' instead of 'fluent-bit'.  The former is referenced for other steps in the Make process.
I have also moved the boringcrypto canary …
=> Fix fluentbit plugin for manifest step

CHANGELOG.md, docs/sources/configure/_index.md, docs/sources/setup/upgrade/_index.md, pkg/querier/queryrange/queryrangebase/roundtrip.go
…range config
Removed split_queries_by_interval and forward_headers_list from query_range config
The fields were deprecated and hence going to be removed in the next major version
**Checklist**
=> Remove split_queries_by_interval and forward_headers_list

docs/sources/storage/_index.md
Legacy storage backends (that are not single store aka "shipper") have been deprecated with https://github.com/grafana/loki/pull/10341
The docs should reflect this change.
The structure of the page changed _slightly_:
* Made object storage a separate section under "Chunk storage"
* Refer to this section in the "Single Store" section for supported backends
* Moved Azure example underneath the rest of the single store examples
While it is not yet perfect, I tried to change as little as possible and keep the big change for when the legacy storage backends are removed.
=> Add deprecation notes to Storage documentation

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml
The writer scaleUp configuration is missing `stabilizationWindowSeconds`, without it I cannot enable the autoscaler.
The autoscaling minReplicas is 1, but the default `replication_factor` is 3. If a user enables the autoscaler but does not update the minReplicas the pod will crash, should I increase the minReplicas to 2?
**Checklist**
=> Helm: Increase HPA minReplicas and maxReplicas

production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/gateway/deployment-gateway.yaml, production/helm/loki/templates/loki-canary/daemonset.yaml, production/helm/loki/templates/loki-canary/serviceaccount.yaml, production/helm/loki/templates/read/deployment-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml, production/helm/loki/templates/write/statefulset-write.yaml
This is a small, nit-picky stylistic change to the helm chart. When there are no annotations for a template, this omits the `annotations` key, rather than having an empty `annotations` section in the rendered template.
=> helm: omit annotation section when empty

clients/pkg/promtail/client/batch.go, clients/pkg/promtail/client/batch_test.go, clients/pkg/promtail/client/client_test.go
When we added non-indexed-labels support to the promtail, we forgot to adjust the batch size calculation which leads to the case when promtail thinks that batch size is `X` but when it sends it to Loki, Loki rejects it because the actual size of the payload is `X`+`N`(size of non-indexed labels).
This feature is not released yet, so, changelog update is not needed.
**Checklist**
=> [promtail] include the size of non-indexed labels into batch size

docs/sources/configure/_index.md, go.mod, go.sum, pkg/util/spanlogger/spanlogger.go, vendor/github.com/grafana/dskit/server/server.go, vendor/github.com/grafana/dskit/spanlogger/spanlogger.go, vendor/modules.txt
In particular, dskit has changed the SpanLogger struct such that all fields are unexported. This updates Loki to work with the new version while preserving the existing Loki behavior.
N/A
Required for Mimir vendor update job in `backend-enterprise` because Reasons.
**Checklist**
=> Update to latest dskit version for SpanLogger changes

clients/cmd/docker-driver/main.go, clients/cmd/fluent-bit/loki.go, clients/cmd/promtail/main.go, clients/pkg/promtail/targets/lokipush/pushtarget.go, cmd/loki/main.go, pkg/util/log.go, pkg/util/log/log.go, tools/tsdb/index-analyzer/main.go, tools/tsdb/migrate-versions/main.go
This PR removes unnecessary code used to convert the dereleased `dslog.Interface` (see https://github.com/grafana/dskit/pull/359) into `go-kit.Logger`.
Additionally, it modifies the signature and implementation of `pkg/util/log/log.go`'s `InitLogger` as follows:
- previous signature 
```
InitLogger(*server.Config, prometheus.Registerer, bool, bool)
```
has been replaced with 
```
InitLogger(*server.Config, prometheus.Registerer, bool, bool) log.Logger
```
Namely, the new `InitLogger` initialises the global logger and returns it.
- the new implementation initializes the global logger, but it does not override the default logger for the server. This is now done by the callers of `InitLogger`. Previously, it was done inside `InitLogger` for …
=> Remove unnecessary code  after dskit log.Interface has been dereleased

pkg/loki/loki.go, pkg/querier/querier.go, pkg/querier/querier_mock_test.go, pkg/querier/querier_test.go, pkg/storage/batch_test.go, pkg/storage/store.go, pkg/storage/store_test.go, pkg/storage/stores/composite_store.go, pkg/storage/stores/composite_store_test.go
In an attempt to simplify the store abstractions/interfaces, this PR does the following cleanups:
* Remove duplicate store field in `pkg/storage.*store`
* Remove duplicate index.Filterable interface inheritance
* Remove nesting from CompositeStore
* Rename/move ChunkReader to ./pkg/storage.SelectStore
**Checklist**
=> Chore(storage): Simplify store interfaces and abstractions (pt 1)

pkg/loki/loki.go
Applications that extends the `Loki` struct must be able to also override the `Store`. In order to allow this, the field must be an interface type, so any `storage.Store` implementation can be assigned.
This reverts the change from interface type to struct type made in PR #10435.
=> Make the Store field of the Loki struct an interface type

docs/sources/get-started/labels/structured-metadata.md
Updates the warning at the top of the structured metadata topic to explicitly state that the feature is not yet available for Cloud Logs users.
=> [Docs] Update warning on structured metadata topic

docs/sources/release-notes/next.md, docs/sources/release-notes/v2-9.md
`next.md` -> `2.9.0` and create new `next.md`
relate: #10468 
**Checklist**
=> Freeze v2.9.0 release notes on `main`

tools/lambda-promtail/template.yaml
I ran into the below error during the CloudFormation stack creation when trying to use the [example CloudFormation config](https://github.com/grafana/loki/blob/main/tools/lambda-promtail/template.yaml):
`"Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function"`
The issue is that the config does not give the `logs:PutSubscriptionFilter` permission to the Lambda Promtail Role. This adds that permission to fix the error
**Checklist**
=> Lambda Promtail: Add logs:PutSubscriptionFilter to Lambda Promtail role

docs/sources/release-notes/_index.md
Adds 2.9.x release to release notes page
**Checklist**
=> chore: add 2.9.x entry to  release-notes index page

.drone/drone.jsonnet, .drone/drone.yml
This change has already made it into main and subsequently into the 2.8 and 2.9 release branches, but was never update in the 2.7 release branch.
This caused CI to fail to push the multi-arch Docker image manifest to Docker hub when releasing 2.7.6 and 2.7.7
Ref: https://drone.grafana.net/grafana/loki/27053/19/2
Ref: https://github.com/grafana/loki/issues/10122
Ref: https://github.com/grafana/loki/pull/9342
=> Pin version of plugins/manifest image in Drone pipeline

docs/sources/configure/_index.md, docs/sources/configure/index.template
Tested locally with `make docs`
=> Fix alias to redirect `/docs/loki/<LOKI_VERSION>/configuration/` to `/docs/loki/<LOKI_VERSION>/configure/`

pkg/logql/log/parser.go
We've had [some reports](https://github.com/grafana/loki/issues/8936) that `unpack` is mangling label names. We're using `unsafeGetString` to generate these so, when the underlying byte slice changes, the label name is also changed. This change incurs an alloc to make sure the generated string wont change when the underlying bytes do.
fixes #8936
=> Don't use unsafe string for label names in the UnpackParser

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/backend/clusterrole.yaml, production/helm/loki/templates/backend/clusterrolebinding.yaml, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/role.yaml, production/helm/loki/values.yaml
**Disclaimer: this work has been done by @Jeinhaus in the [legacy repo](https://github.com/grafana/helm-charts/pull/1625), I have simply migrated here and tested it in our own infrastructure**
--- 
This PR adds a sidecar to the loki chart that queries the Kubernetes API to find Configmaps and/or Secrets that contain loki rules, similar to the way the grafana chart does it for dashboards, plugins or sources.
**Checklist**
*`CHANGELOG.md` updated*: I have not update the CHANGELOG as I can see that it hasn't been updated since the start of version 5. As this been automated now? Or should I had the change logs somewhere else? Or perhaps simply format my commit in a certain way so it gets generated? Apologies if this …
=> Loki Helm: add sidecar to find loki rules in configmaps and secrets

docs/sources/get-started/labels/bp-labels.md
Tested locally with `make docs`
=> Fix alias to redirect `/docs/loki/<LOKI_VERSION>/best-practices/` to `/docs/loki/latest/get-started/labels/bp-labels/`

docs/sources/configure/_index.md, docs/sources/configure/index.template
Backport 5408ec1c9c41f893aa4b3ba61705bc86c4df4929 from #10503
---
Tested locally with `make docs`
=> [release-2.9.x] Fix alias to redirect `/docs/loki/<LOKI_VERSION>/configuration/` to `/docs/loki/<LOKI_VERSION>/configure/`

tools/lambda-promtail/lambda-promtail/eventbridge.go, tools/lambda-promtail/lambda-promtail/eventbridge_test.go, tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/s3.go, tools/lambda-promtail/testdata/eventbridge-s3-event.json
Lambda promtail supports s3 events, which are used for scraping several log sources such as ALB access logs. This works by configuring at the S3 bucket level "s3 event notification", that are configured to target the lambda deployment of lambda-promtail.
However, if one is configuring this through CloudFormation, there's a known issue with AWS that doesn't allow to configure both the lambda, the bucket, and the notifications in the same stack. See [this issue](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/79) for details.
For that, AWS introduced EventBridge notifications, which can be used to ship s3 events to a lambda deployment as well. This flow looks like:
s3 -> eventbridge bus -> eventbridge rule -> lambda …
=> Add support for EventBridge s3 events in lambda-promtail

docs/sources/setup/upgrade/_index.md
Cleanup upgrade notes from 2.9 release on main branch.
=> Reflect 2.9 upgrade notes on main

operator/CHANGELOG.md, operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/overlays/community-openshift/manager_related_image_patch.yaml, operator/config/overlays/community/manager_related_image_patch.yaml, operator/config/overlays/development/manager_related_image_patch.yaml, operator/config/overlays/openshift/manager_related_image_patch.yaml, operator/docs/operator/compatibility.md, operator/hack/addons_dev.yaml, operator/hack/addons_ocp.yaml, operator/internal/manifests/var.go
Update Loki operand to v2.9.0
**Checklist**
=> operator: Update Loki operand to v2.9.0

pkg/loghttp/query.go, pkg/util/unmarshal/unmarshal_test.go
Even though the[ Loki HTTP API docs for the push endpoint][1] state that the stream label values should be strings, we previously didn't enforce this requirement. With https://github.com/grafana/loki/pull/9694, we started enforcing this requirement, and that broke some users.
In this PR we are reverting this type of assertion and adding a bunch of tests to avoid the regression in the future.
[1]: https://grafana.com/docs/loki/latest/reference/api/#push-log-entries-to-loki
=> Fix regression when parsing numbers in Push request

CHANGELOG.md, docs/sources/configure/_index.md, docs/sources/setup/upgrade/_index.md, pkg/storage/store.go, pkg/storage/stores/indexshipper/shipper.go, pkg/storage/stores/tsdb/head_manager_test.go, pkg/storage/stores/tsdb/store.go
The setting `use_boltdb_shipper_as_backup` (`-tsdb.shipper.use-boltdb-shipper-as-backup`) was a remnant from the development of the TSDB storage.
It was used to allow writing to both TSDB and BoltDB when TSDB was still highly experimental.
Since TSDB is now stable and the recommended index type, the setting has become irrelevant and therefore was removed.
The previous default value `false` is applied.
Also closes https://github.com/grafana/loki/issues/9603, but a fix needs to be backported to 2.9 and 2.8
**Checklist**
=> Remove backup index writer from TSDB configuration

clients/pkg/promtail/client/client_test.go, cmd/migrate/main.go, integration/loki_micro_services_delete_test.go, pkg/ingester/flush_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/querier/querier.go, pkg/querier/querier_mock_test.go, pkg/storage/async_store.go, pkg/storage/async_store_test.go, pkg/storage/chunk/client/congestion/congestion.go, pkg/storage/chunk/client/congestion/controller_test.go, pkg/storage/store.go, pkg/storage/store_test.go, pkg/storage/stores/composite_store.go, pkg/storage/stores/composite_store_entry.go, pkg/storage/stores/composite_store_test.go, pkg/storage/stores/index/index.go, pkg/storage/stores/series/series_index_gateway_store.go, pkg/storage/stores/series/series_index_store.go, pkg/storage/stores/series/series_store_test.go, pkg/storage/stores/shipper/index/compactor/util_test.go, pkg/storage/stores/shipper/indexgateway/gateway.go, pkg/storage/util_test.go
* Remove preemptive interface from `indexReaderWriter` and make it an exported struct
* Compose `IngesterStore` and `QuerierStore` from existing interfaces
The ingester and querier do not require a store that implements the full interface, but can accept stores that are a subset of the interfaces. Therefore we can make specific interfaces that are accepted by the ingester and querier constructors.
* Split `ChunkFetcherProvider` interface out of `ChunkFetcher`
**Checklist**
=>  chore(storage): Simplify store interfaces and abstractions (pt 2)

docs/sources/configure/_index.md, pkg/distributor/limits.go, pkg/distributor/validator.go, pkg/distributor/validator_test.go, pkg/validation/limits.go, pkg/validation/validate.go
This PR introduces two new limits for structured metadata:
- `max_structured_metadata_size`: Defaults to 64 KB. Limits the maximum size of the structured metadata attached to a log line.
- `max_structured_metadata_entries_count`: Default to 128. Limits the maximum number of structured metadata entries attached to a log line.
We discussed adding other limits like `max_structured_metadata_label_name_length` and `max_structured_metadata_label_value_length` but discarded this idea for now.
=> Add limits

docs/sources/setup/install/docker.md, examples/getting-started/docker-compose.yaml, production/docker-compose.yaml, production/docker/docker-compose.yaml
This PR updates the version of Loki used by our sample Dockerfiles to the most recent version of 2.9.0.
**Checklist**
=> Update version of loki referenced in docker files to 2.9.0

docs/sources/operations/_index.md
The new information architecture moved the Upgrade docs under "Setup."  
Based on feedback received via Slack, adding a link to the Upgrade docs to the Manage/Operations landing page to help users find the Upgrade docs.  
**Special notes for your reviewer:**
Note that because how the page is structured (the list is a Hugo "section") this is a bit of a workaround.  The link to the Upgrade docs is at the bottom, not in alphabetical order.
=> [Docs] Add upgrade link to Manage page.

clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile
Update alpine versions used by our images to `3.18.3`
N/A
**Checklist**
=> Update alpine versions

pkg/logql/downstream.go, pkg/logql/engine.go, pkg/logql/evaluator.go, pkg/logql/matrix.go, pkg/logql/matrix_test.go, pkg/logql/range_vector.go, pkg/logql/range_vector_test.go, pkg/logql/step_evaluator.go, pkg/logql/vector.go
This change makes the `StepEvaluator` more flexible for changes like #10417 that introduce a different step result. With the interface `StepResult` we can support other vector types in the future.
**Checklist**
=> Return `StepResult` from `StepEvaluator.Next()`.

CHANGELOG.md, pkg/storage/stores/indexshipper/storage/cached_client.go, pkg/storage/stores/indexshipper/storage/cached_client_test.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/modules.txt
There were many race conditions reported if you run `go test -race` on this package.
Google's 'singleflight' package is much neater and makes all the race warnings go away.
Relates to #8586
This is a backport of https://github.com/grafana/loki/pull/10314 to the 2.9.x release branch.
=> indexshipper/storage: fix race conditions (#10314)

CHANGELOG.md, docs/sources/release-notes/v2-9.md, docs/sources/send-data/docker-driver/_index.md, docs/sources/setup/install/docker.md
This PR prepares the release of Loki 2.9.1
=> Prepare release 2.9.1

operator/CHANGELOG.md, operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json, operator/jsonnet/config.libsonnet, operator/jsonnet/jsonnetfile.json, operator/jsonnet/jsonnetfile.lock.json
Bumps the jsonnet tag for dashboars from `v2.8.2` to `v2.9.0`. Introduces a couple of minor fixes for supporting OCP's Grafana 6 based dashboard feature.
**Checklist**
=> operator: Upgrade dashboards for for Loki v2.9.0

operator/CHANGELOG.md, operator/internal/manifests/gateway_tenants_test.go, operator/internal/manifests/openshift/configure.go
This PR enables the new "query selector extraction" feature of observatorium/api when `openshift-logging` tenant mode is enabled.
Depends on observatorium/api#555
Refs [LOG-4296](https://issues.redhat.com/browse/LOG-4296)
**Checklist**
=> operator: Update gateway arguments to enable namespace extraction

CHANGELOG.md, pkg/storage/stores/indexshipper/storage/cached_client.go, pkg/storage/stores/indexshipper/storage/cached_client_test.go
The bug could manifest in missing results when querying logs older than what is kept on ingesters.
This commit changes the behaviour of the caching in the storage client client used by the indexshipper to download indexes from object store.
The object store client maintains an internal, in-memory cache of tables (= per-day index directories) available on object storage to reduce the amount of expensive List operations. This cache gets updated in a regular interval (1m) by the table manager that uses the client. However, when the per-tenant setting `query_ready_index_num_days` is set the 0, which is the default (to disable index pre-fetching), the sync is only performed once on startup, but not subsequently. This leads to a stale list of table names in the cache and any new index directory …
=> Fix bug in cache of the index object client

CHANGELOG.md
Changelog entry contained the wrong Alpine version.
=> Fix wrong Alpine version in CHANGELOG

docs/sources/send-data/promtail/stages/structured_metadata.md
According to the code the pipeline name uses `_` not `-` for the name
https://github.com/grafana/loki/blob/main/clients/pkg/logentry/stages/stage.go#L46C38-L46C38
**Checklist**
=> chore(docs): Fix structured_metadata usage

CHANGELOG.md, docs/sources/release-notes/v2-9.md, docs/sources/send-data/docker-driver/_index.md, docs/sources/setup/install/docker.md
Reflect Loki 2.9.1 release on main branch to be up-to-date with latest released version.
=> Reflect release 2.9.1 on main branch

operator/apis/loki/v1beta1/lokistack_types.go, operator/docs/enhancements/retention_support.md, operator/docs/operator/api.md, operator/hack/lokistack_dev.yaml, operator/hack/lokistack_gateway_dev.yaml, operator/hack/lokistack_gateway_ocp.yaml, operator/internal/external/k8s/client.go, operator/internal/manifests/rules_config.go, operator/internal/validation/lokistack.go
- Changes the size of the example LokiStack configurations to `1.demo`
- Updates the `storageClassName` to `gp3-csi` where `gp2` was used before
- Fix a few typos
- Correct the receiver of a method in validation code (receiver is unused in that method though)
I think we can skip the changelog for this one.
**Checklist**
=> operator: Update example configurations to use demo size

pkg/storage/factory.go
This commit fixes a regression in the object store client creation introduced with #10518
=> Fix object store type for table manager

docs/sources/send-data/lambda-promtail/_index.md, tools/lambda-promtail/README.md, tools/lambda-promtail/template-eventbridge.yaml
https://github.com/grafana/loki/pull/10449 added support so that lambda-promtail can handle s3 events through AWS EventBridge. This PR is a follow up adding a CloudFormation template to deploy lambda-promtail, with the corresponding EventBridge rule to deliver s3 events to the lambda.
related to https://github.com/grafana/loki/issues/10209
**Checklist**
=> Add CloudFormation template for lambda + EventBridge setup

pkg/storage/stores/indexshipper/downloads/index_set.go, pkg/storage/stores/tsdb/multi_file_index.go
Index Gateways can stall when certain queries try to download tons of indices because. `ErrGroup` needs an explicit limit set on it. This PR sets the limit provisionally until a more configurable solution can be introduced.
=> Don't allow unbounded parallelism when downloading indices

CHANGELOG.md, clients/pkg/promtail/targets/file/filetarget_test.go, clients/pkg/promtail/targets/file/tailer.go
Users are getting `PromtailFileMissing` alerts, which are defined as:
```
promtail_file_bytes_total{namespace!=""} unless promtail_read_bytes_total{namespace!=""}
```
This appears to be due to a race condition where a file can be deleted while the file target is being stopped.
**Checklist**
=> Fix race condition when stopping to tail files

CHANGELOG.md, docs/sources/reference/api.md, docs/sources/setup/upgrade/_index.md, pkg/ingester/ingester.go, pkg/loki/modules.go
The handler was deprecated for a while and is removed in favour or `/ingester/shutdown?flush=true`.
**Checklist**
=> Remove legacy ingester shutdown handler

cmd/loki/main.go, pkg/loki/loki.go
This helps to get insights about slow startup of Loki, e.g. for the index gateway, which may pre-fetch a lot of data before it becomes ready.
**Checklist**
=> Log process startup and running time

.drone/drone.jsonnet, .drone/drone.yml
backport #10664 to `2.9.x` branch
=> drone(docker-driver): Fetch tags before pushing image during release

docs/sources/operations/storage/wal.md
The reference to a headline on the API page broke, because the headline was removed in https://github.com/grafana/loki/pull/10655
**Checklist**
=> Docs: Fix broken link on WAL page

CHANGELOG.md, docs/sources/configure/_index.md, docs/sources/setup/install/helm/reference.md, docs/sources/storage/_index.md, go.mod, go.sum, pkg/storage/bucket/azure/bucket_client.go, pkg/storage/bucket/azure/config.go, pkg/storage/bucket/azure/config_test.go, pkg/storage/chunk/client/azure/blob_storage_client.go, pkg/storage/chunk/client/azure/blob_storage_client_test.go, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml, vendor/github.com/thanos-io/objstore/CHANGELOG.md, vendor/github.com/thanos-io/objstore/README.md, vendor/github.com/thanos-io/objstore/objstore.go, vendor/github.com/thanos-io/objstore/providers/azure/azure.go, vendor/github.com/thanos-io/objstore/providers/azure/helpers.go, vendor/modules.txt
Adds a connection-string option to the azure blob storage config. So the [Azurite](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite) emulator can be used in local test environments (my use case). But also to support the use of a SAS token. See the (future) addition of this option to the Thanos object storage client: https://github.com/thanos-io/objstore/pull/51
n/a
https://github.com/thanos-io/objstore/pull/51 isn't merged yet. But I'm already creating this PR to see what others think.
**Checklist**
=> azure: add connection-string

.github/workflows/dependabot_reviewer.yml
Noticed, the dependencies auto-merge is breaking with error.
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
https://github.com/grafana/loki/actions/runs/6222148810/job/16885518452?pr=10623
After some investigation. The suspect is secerets are not properly imported into the GH actions (NOTE from above GH run, the env `GITHUB_TOKEN` is set empty).
Also from the docs, this token can be set either by `GITHUB_TOKEN` or `GH_TOKEN`. `GITHUB_TOKEN` will get higher priority.
https://cli.github.com/manual/gh_help_environment
**Checklist**
=> dependabot: Fix accessing secerets via environmental variables.

docs/sources/get-started/architecture.md, docs/sources/operations/storage/legacy-storage.md
Also split out legacy storage into separate page.
**Checklist**
=> Revise documentation about Loki architecture

docs/sources/send-data/promtail/scraping.md
GELF support in Promtail is not experimental (any more).
Nothing really worth mentioning in the changelog or release notes.
=> Docs: Remove experimental flag from GELF support in Promtail

CHANGELOG.md, clients/cmd/promtail/main.go, clients/pkg/promtail/client/client.go, clients/pkg/promtail/client/config.go, clients/pkg/promtail/config/config.go, docs/sources/send-data/promtail/configuration.md
The setting was deprecated and already caused an error on startup when used.
This behaviour was noticed when looking at the reference configuration docs of Promtail.
**Checklist**
=> Promtail: Remove deprecated stream_lag_labels setting

docs/sources/get-started/labels/structured-metadata.md, docs/sources/reference/api.md, docs/sources/send-data/k6/_index.md, docs/sources/send-data/promtail/_index.md, docs/sources/send-data/promtail/configuration.md
Cleaning up the API reference documentation:
* Removed unsupported APIs
* Change order so it matches the list on top 
* Write better headings
* Make cURL examples consistent with command-response-blocks
=> Restructure API reference documentation

docs/sources/reference/api.md
When I rebased https://github.com/grafana/loki/pull/10654 before merging I did not resolve the merge conflict correctly. I forgot to remove the link to the section that was removed on main already with a previous commit.
Resolves https://github.com/grafana/loki/pull/10654#discussion_r1334601729
=> Fix internal reference in API docs

pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, pkg/logql/syntax/ast.go, pkg/logql/syntax/extractor.go
Previously, we didn't always consider that some label reductions from downstream vector|range-vector aggregations come from groupings. This is particularly useful in the min/max/count sharding mapper.
edit: also fixes an issue with the range extractor mishandling `without ()` as `by ()`
=> [sharding] [bugfix] Correctly account for child groupings in count/min/max sharding

CHANGELOG.md, pkg/ingester/ingester.go
- Change our sleep log line from `level=debug` to `level=info` to allow visibility of it without having to change the log line level of distributors as a whole
- Make the flush jitter to be 20% of flush check period instead of 1%. This means that, for the default 30s flush check period, the jitter will be at most 6s.
**Checklist**
=> Ingester: Change log line level and make jitter potentially longer.

docs/sources/get-started/labels/structured-metadata.md
OSS users tried to use the structured metadata feature and faced an issue because they used previous schema versions (V11, V12) and they were not aware that it was necessary to use V13 because the docs did not cover it.  
re: https://github.com/grafana/loki/issues/10683
=> Update structured-metadata docs

pkg/logql/evaluator.go
Check that the next evaluator isn't nil when iterating with a LiteralStepEvaluator.
This will especially happen for binary operations with a comparison at the end. 
N/A
**Checklist**
=> Check that evaluator isn't nil

docs/sources/visualize/grafana.md
10692 - Added urls for Mac and Windows when connecting a Grafana running on Docker to a locally built Loki instance
I've added 2 URLs (mac and windows) that needs to be used if the user is running a Grafana with docker and trying to connect to a locally built Loki running on localhost (not Docker). When trying to figure out how to run the buids, it was very confusing as to why it's not working, I had to research to try to make the connection work. zDocumentation in setting up a local development environemtn can actually use some improvement as well as I had to moved from one section to another.
Fixes #10692
**Checklist**
=> Add urls to connect Grafana (on Docker) to Loki (local buid instance)

pkg/logql/engine.go, pkg/logql/evaluator.go, pkg/logql/evaluator_test.go
This is a follow up to #10701 and checks in all evaluators if the nested evaluator returned a result or not.
**Checklist**
=> Check for nil StepResult.

docs/sources/get-started/overview.md
On https://grafana.com/docs/loki/latest/get-started/overview/ you can see that two links do not render well. I fixed them in this PR.
**Checklist**
=> Doc: Fix link typos in documentation

pkg/storage/factory.go, pkg/storage/stores/shipper/shipper_index_client.go
The constructor function name is misleading as it suggests that the returned object is a [shipper](https://github.com/grafana/loki/blob/main/pkg/storage/stores/shipper/index/table_manager.go#L48), rather than an index client.
Also, change the return type to be a struct pointer, rather than an interface.
**Checklist**
=> Rename NewShipper to NewIndexClient

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/monitoring/grafana-agent.yaml, production/helm/loki/templates/monitoring/logs-instance.yaml, production/helm/loki/templates/monitoring/pod-logs.yaml, production/helm/loki/templates/monitoring/servicemonitor.yaml, production/helm/loki/templates/write/hpa.yaml, production/helm/loki/templates/write/poddisruptionbudget-write.yaml, production/helm/loki/templates/write/service-write-headless.yaml, production/helm/loki/templates/write/service-write.yaml, production/helm/loki/templates/write/statefulset-write.yaml
It adds the right `namespace` values for some components in the helm chart. 
Fixes #10048 
**Checklist**
I hope I did things right w.r.t. the changelog/README changes for the helm chart. Please let me know if I did something wrong :)
=> helm: add namespace settings where missing

docs/sources/alert/_index.md
Based on what we have written here:
https://grafana.com/docs/loki/latest/operations/recording-rules/#write-ahead-log-wal
A WAL for the Loki Ruler already has been implemented, so lets no longer leave it as a "future improvement"
=> Remove that the Ruler WAL is a coming soon feature

CHANGELOG.md, docs/sources/setup/upgrade/_index.md, integration/loki_micro_services_test.go, pkg/storage/chunk/cache/embeddedcache.go, pkg/storage/chunk/cache/embeddedcache_test.go
Removes the following embedded cache metrics since `loki_cache_request_duration_seconds` (which instruments requests made to all the caches) [already covers them](https://github.com/grafana/loki/blob/6a07988491124c91d4acb1cbbf2ee2a4d7dc8900/pkg/storage/chunk/cache/cache.go#L110):
- `querier_cache_added_total`
- `querier_cache_gets_total`
- `querier_cache_misses_total`
Updates the namespace and subsystem for the following metrics
- `querier_cache_added_new_total` is renamed to `loki_embeddedcache_added_new_total`
- `querier_cache_evicted_total` is renamed to `loki_embeddedcache_evicted_total`
- `querier_cache_entries` is renamed to `loki_embeddedcache_entries`
- `querier_cache_memory_bytes` is renamed to `loki_embeddedcache_memory_bytes`
Removes …
=> embedded cache: update metric namespace and remove duplicate metrics

operator/CHANGELOG.md, operator/internal/manifests/internal/sizes.go
The default of replication factor of 3 does not make sense for the size 1xMedium, in a stack where the number of ingester replicas is 3, if one of the ingester pods is restarted this brings the stack down. A much better default is replication factor of 2. This PR is an alternative to https://github.com/grafana/loki/pull/10719, from my POV prefer this PR.
https://issues.redhat.com/browse/LOG-4507
Alternative PR: https://github.com/grafana/loki/pull/10719
**Checklist**
=> operator: Change default replication factor of 1x.medium to 2

docs/sources/get-started/deployment-modes.md
I realized when I was looking at this topic, that the headings were not parallel.
Fixed the headings, and also updated the first paragraphs to include the words "deployment mode" since I took it out of the headings.
=> Update headings in deployment modes topic

CHANGELOG.md, docs/sources/configure/_index.md, docs/sources/setup/upgrade/_index.md, pkg/storage/config/store.go, pkg/storage/store.go
Adds a deprecation node for write dedupe cache. This cannot be fully removed yet as legacy indexes rely on this.
**Checklist**
=> Add deprecation node for write dedupe cache

docs/sources/get-started/deployment-modes.md
Linked to the same graphic twice by accident.  Fixing the link to point to the correct graphic file.
=> Fix graphic link in Deployment Modes topic

pkg/storage/stores/shipper/indexshipper/downloads/index_set.go, pkg/storage/stores/shipper/indexshipper/downloads/table.go, pkg/storage/stores/shipper/indexshipper/shipper.go, pkg/storage/stores/shipper/indexshipper/tsdb/index/index.go, pkg/storage/stores/shipper/indexshipper/tsdb/index_shipper_querier.go, pkg/storage/stores/shipper/indexshipper/tsdb/multi_file_index.go
This addresses an issue we've seen with index gateways when handling queries that touch a large number of series, although these are improvements not necessarily solutions.
We've seen a tremendous amount of goroutines being spawned while processing GetChunkRefs requests, specifically when the gateways have recently found a lot of uncompacted recent ingester tables.
This PR puts some limits on the parallelism of processing tables, the implementation is a bit arbitrary, we limit the concurrent iterations to GOMAXPROCS/2
In practice this is potentially still too much as an index gateway will be serving many requests in parallel witch each able to do parallel table iteration, however it's a more reasonable line in the sand than having no limits and …
=> Index Gateway: Set some concurrency limits around concurrent index table processing

loki-build-image/Dockerfile
Once more with a change to the dockerfile to force a new build of the build image.
**Checklist**
=> Force new build of build image

.drone/drone.yml, Makefile, clients/cmd/fluent-bit/Dockerfile, clients/cmd/promtail/Dockerfile, clients/cmd/promtail/Dockerfile.arm32, clients/cmd/promtail/Dockerfile.cross, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, tools/lambda-promtail/Dockerfile
Update the go version in the Dockerfiles to 1.21.2
**Checklist**
=> Update Go version to 1.21.2 in Dockerfiles

.drone/drone.jsonnet, .drone/drone.yml
Currently we use `grafana/base-docs:latest` which broke our build. We should pin the version to make CI builds reproducible and test version updates.
**Checklist**
=> Pin grafana/docs-base image version.

CHANGELOG.md, docs/sources/configure/_index.md, docs/sources/setup/upgrade/_index.md, pkg/loki/modules.go, pkg/lokifrontend/frontend/v1/frontend_test.go, pkg/querier/querier.go, pkg/querier/worker/worker.go, pkg/querier/worker/worker_test.go, pkg/querier/worker_service.go
To simply loki configuration, this pr removes `querier.worker-parallelism` as it does not offer additional value to already existing `querier.max-concurrent`
Also updates the default value of `querier.max-concurrent` to 4. This is a better default for users that are just starting out. Users can consider increasing it as they scale up their loki installation.
**Checklist**
=> config: better defaults for querier max concurrency

production/ksonnet/loki/ingester.libsonnet, production/ksonnet/loki/wal.libsonnet
In https://github.com/grafana/loki/pull/10709, we removed `-ingester.max-transfer-retries` in favor of the WAL. Then, in https://github.com/grafana/loki/pull/10844 we removed it from the config file but we did not remove it from the ingester args. This PR solves this by removing it.
=> Remove -ingester.max-transfer-retries

production/ksonnet/loki/index-gateway.libsonnet
In a recent PR we added support for the simple mode in the index gateway client to support a connection pool, a headless service is needed for resolving all the current gateways to be used in the pool
**Checklist**
=> jsonnet: add index-gateway headless service

CHANGELOG.md, production/ksonnet/loki/index-gateway.libsonnet, production/ksonnet/loki/shipper.libsonnet
fixes a bug in applying the storage_config for tsdb (the else{} prevented the configs from applying, don't know why.
Updates the index gateway client to use the new headless service.
**Checklist**
=> Jsonnet: update index gateway client to use headless service, fix a bug in index gateway storage config application

CHANGELOG.md, pkg/ruler/storage/instance/instance.go, pkg/ruler/storage/instance/instance_test.go, pkg/ruler/storage/wal/wal.go
prometheus ruler added a feature of notifying the reader when a sample is appended, instead of waiting in a loop burning the CPU cycles. https://github.com/prometheus/prometheus/pull/11949
This changes a default behaviour a bit. Now if `notify` is not enabled, next read is done only when next readTicker is triggered.
Also should fix https://github.com/grafana/loki/issues/10859
Adding few more details for the sake of completeness.
We found this via more frequent failures of rule-evaluation integration tests linked on the issue above. After some investigation, we tracked down to prometheus changes.
Prometheus introduced new type `wlog.WriteNotified` interface with `Notify()` method …
=> ruler: Support `writeNotify` on Loki ruler

production/ksonnet/loki/config.libsonnet
remove the usage of already deleted config match_max_concurrent from loki ksonnet
**Checklist**
=> ksonnet: remove usage of already deleted config match_max_concurrent

docs/sources/community/maintaining/release/_index.md, docs/sources/get-started/deployment-modes.md, docs/sources/operations/loki-canary/_index.md, docs/sources/send-data/docker-driver/_index.md, docs/sources/send-data/promtail/installation.md, docs/sources/setup/install/docker.md, docs/sources/setup/install/local.md, examples/getting-started/docker-compose.yaml, production/docker-compose.yaml, production/docker/docker-compose.yaml, production/ksonnet/loki-canary/config.libsonnet, production/ksonnet/loki-simple-scalable/example/main.jsonnet, production/ksonnet/loki-simple-scalable/images.libsonnet, production/ksonnet/loki/images.libsonnet, production/ksonnet/promtail/config.libsonnet
- run ./tools/release_update_tags.sh to use v2.9.2
- also updates the release security patch docs to include version upgrade step
**Checklist**
=> chore: update examples, docs to use the latest loki version

.drone/drone.yml, Makefile, clients/pkg/promtail/targets/syslog/syslogtarget_test.go, loki-build-image/Dockerfile
`loki-build-image:0.29.3-go1.20.10` that uses go1.20.10 is published.
pr updates drone to use the updated build image on the release branch
**Checklist**
=> [release-2.8.x] update build image to use go1.20.10

docs/sources/community/design-documents/2020-02-Promtail-Push-API.md, docs/sources/operations/zone-ingesters.md, docs/sources/send-data/fluentd/_index.md, docs/sources/send-data/promtail/cloud/gcp/_index.md, docs/sources/setup/upgrade/_index.md
Developers tend to abbreviate "Kubernetes" to just K8, but as a best practice it should be spelled out in the documentation.
=> Spell out Kubernetes in docs

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/values.yaml
Add support for configuring distributor with Helm. Needed to be able to enable IPv6 on that component.
**Checklist**
=> helm: add support for configuring distributor

CHANGELOG.md, pkg/querier/queryrange/queryrangebase/retry.go
Currently any subquery which fails with a 5xx status code is retried by the query frontend immediately, and by default will make a total of 5 attempts to execute the subquery, ultimately failing the query if you exhaust those attempts.
We notice there are times when subqueries can fail extremely quickly, mostly around queriers handling various GRPC related issues between components like ingesters or index gateways.
In these cases a query will exhaust all the retries in less than a second and fail back to the user.
Also in cases where a query is causing a lot of memory pressure on a pool of queriers leading to OOM crashes of queriers, the lack of a backoff on retries can make this behavior quite aggressive and potentially cause disruption if you …
=> Loki: introduce an exponential backoff on failed query retries.

docs/sources/send-data/fluentd/_index.md
Fluentd client configuration has changed recently. The default config already [reflects](https://github.com/grafana/loki/blob/main/clients/cmd/fluentd/docker/conf/loki.conf#L5-L8) the new syntax. However, the examples on the page haven't been updated yet.
=> Fix docs for fluentd client

clients/cmd/fluentd/Dockerfile
1.14.0 is over 2 years old and the latest 1.16 continues to work just fine with loki
=> clients: update fluentd base container

docs/sources/query/metric_queries.md
Bring back offset modifier doc section from https://github.com/grafana/loki/pull/3455 and lost in  https://github.com/grafana/loki/pull/4012
Fixes regression from https://github.com/grafana/loki/issues/2785
**Checklist**
=> Docs: LogQL `offset` modifier

pkg/bloomgateway/bloomgateway.go
Change `Len()` method to use `RUnlock()` instead, since it was locked using `RLock()`.
N/A
**Checklist**
=> Bloomgateway: Use RUnlock to unlock RLock instead

pkg/loki/modules.go, pkg/util/server/recovery.go, pkg/util/server/recovery_test.go
Commit 56437fa0c44efae3727f05972ab1d7e54ef59f64 introduced a querier handler that would work without an HTTP layer. This removed the HTTP recovery middleware that would catch panics and return them as HTTP 500 errors. This change introduces a new middlware for the querier handler that has the same behviour.
**Checklist**
=> Recover querier handler from panic.

clients/pkg/promtail/client/config.go
Because the block of code immediately below `*Config` indicates that all arguments are deprecated, I incorrectly assumed that the `*Config` itself was deprecated and went hunting for a replacement. But the `*Config` struct is still how a client is expected to be configured.
**Which issue(s) this PR fixes**: Updates #10702.
**Checklist**
=> promtail/client: note client config is not deprecated

pkg/bloomgateway/bloomgateway_test.go
The order of active users is non-deterministic, so we need to check for matching elements, rather than for equal slice.
Failed test run: https://drone.grafana.net/grafana/loki/29579/3/6
Passed test run: https://drone.grafana.net/grafana/loki/29577/3/6
**Checklist**
=> Fix flaky bloomgateway test case

pkg/loki/modules.go
The errors below were introduced during adding initial service structure for BloomGateway https://github.com/grafana/loki/pull/10782 and BloomCompactor https://github.com/grafana/loki/pull/10748 components. 
```
docker-loki-read-3      | panic: runtime error: invalid memory address or nil pointer dereference
docker-loki-read-3      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9e6d90]
docker-loki-read-3      |
docker-loki-read-3      | goroutine 1 [running]:
docker-loki-read-3      | github.com/grafana/dskit/kv.createClient({_, _}, {_, _}, {{{0x22f6128, 0xe}, {{0x0, 0x0}}, 0x4a817c800, 0x0, ...}, ...}, ...)
docker-loki-read-3      |       /src/loki/vendor/github.com/grafana/dskit/kv/client.go:158 +0x360
docker-loki-read-3      | …
```
=> Fix ring start up errors

pkg/logproto/compat.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/limits_test.go
We need to return empty responses for logproto request types from NewEmptyResponse based on types that can be returned from DecodeRequest.
=> WIP: return empty responses for logproto request types from

pkg/logproto/compat.go, pkg/querier/handler.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/limits_test.go
Replaces https://github.com/grafana/loki/pull/11048/. We would return `logproto.VolumeResponse` but not match it in the codec. 
**Checklist**
=> Remove `GetHeaders` from `logproto.VolumeResponse`.

pkg/loki/loki.go, pkg/loki/modules.go
For enterprise we must be able to override the Codec that's injected into the query frontend and the queriers.
**Checklist**
=> Initialize the request codec in the module chain.

pkg/logproto/compat.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/limits_test.go
We need to return empty responses for logproto request types from NewEmptyResponse based on types that can be returned from DecodeRequest.
---------
(cherry picked from commit 0d7b6b2622f9bcf5d9d151dc3d25a8c97c3f2039)
**Checklist**
=> Return empty responses for logproto request types from (#11029)

pkg/logql/metrics.go, pkg/logql/metrics_test.go, pkg/querier/http.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/roundtrip.go, pkg/querier/queryrange/stats.go
Requests to the following APIs previously had limited or incorrect logging, which made understanding their behaviour at runtime difficult.
[GET /loki/api/v1/labels](https://grafana.com/docs/loki/latest/reference/api/#list-labels-within-a-range-of-time)
[GET /loki/api/v1/label/<name>/values](https://grafana.com/docs/loki/latest/reference/api/#list-label-values-within-a-range-of-time)
[GET /loki/api/v1/series](https://grafana.com/docs/loki/latest/reference/api/#list-series)
[GET /loki/api/v1/index/stats](https://grafana.com/docs/loki/latest/reference/api/#index-stats)
[GET /loki/api/v1/index/volume](https://grafana.com/docs/loki/latest/reference/api/#volume)
[GET /loki/api/v1/index/volume_range](https://grafana.com/docs/loki/latest/reference/api/#volum …
=> Improve observability of index queries

production/ksonnet/enterprise-logs/jsonnetfile.lock.json
This PR updates the GEL config to use the latest Loki config so some removed settings are no longer present. This is causing a problem in a test environment.
**Checklist**
=> Update GEL ksonnet to latest Loki version

.gitignore, Makefile
Adds a make file target for running both trivy and snyk to scan our images for vulnerabilities during/before releases.
=> add scan-vulnerabilities make target

pkg/loki/modules.go, pkg/querier/queryrange/instrument.go, pkg/querier/queryrange/metrics.go, tools/dev/loki-boltdb-storage-s3/config/loki.yaml
#10858 removed the HTTP and gRPC server from the querier workers. That means inflight requests are not instrumented anymore. This change adds a middleware that does that.
This will add metrics such as 
```
cortex_inflight_requests{method="gRPC",route="*logproto.IndexStatsRequest"} 0
cortex_inflight_requests{method="gRPC",route="*queryrange.LabelRequest"} 0
cortex_inflight_requests{method="gRPC",route="*queryrange.LokiRequest"} 0
cortex_inflight_requests{method="gRPC",route="*queryrange.LokiSeriesRequest"} 0
```
**Checklist**
=> Instrument querier inflight requests.

pkg/ingester/tailer.go, pkg/ingester/tailer_test.go, pkg/iter/categorized_labels_iterator.go, pkg/iter/categorized_labels_iterator_test.go, pkg/logql/engine.go, pkg/querier/http.go, pkg/querier/querier.go, pkg/querier/querier_mock_test.go, pkg/querier/querier_test.go, pkg/querier/tail.go, pkg/querier/tail_test.go, pkg/util/httpreq/encoding_flags.go, pkg/util/marshal/marshal.go, pkg/util/marshal/marshal_test.go, pkg/util/marshal/query.go, pkg/util/marshal/tail.go, pkg/util/unmarshal/unmarshal_test.go
This is a follow-up PR for https://github.com/grafana/loki/pull/10419 adding support for tailing.
I tested it on a dev cell and works fine.
**Note**: With these changes, the JSON marshal unmarshal functions for the tail are no longer used ([example][1]) so I think we can remove them. Also, the new Tail response is no longer used, so we can also make it an alias to the _legacy_ one. Let's do it on a follow-up PR to avoid making this one bigger.
[1]: https://github.com/grafana/loki/blob/52a3f16039dd5ff655fc3681257d99794f620ec4/pkg/loghttp/entry.go#L210-L238
=> Support categorized labels in Tailing

pkg/loki/modules.go, pkg/querier/queryrange/instrument.go, pkg/util/server/recovery.go, pkg/util/server/recovery_test.go, tools/dev/loki-boltdb-storage-s3/config/loki.yaml
* Instrument querier inflight requests. (#11085)
* Recover querier handler from panic. (#10983)
**Checklist**
=> Backport instrumentation and recovery.

.github/workflows/helm-ci.yml, production/helm/ct.yaml
The `helm-extra-args` causes an error with the new version of ct lint. This change removes the timeout parameter specified in there and adds a timeout in the CI step configuration.
**Checklist**
=> Remove timeout parameter

pkg/loki/loki.go, pkg/loki/modules.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/instrument.go
A previous change removed the RED metrics for the querier. This adds them back as part of a middleware.
**Checklist**
=> Bring back RED metrics for querier when processing scheduler requests.

CHANGELOG.md, clients/pkg/promtail/targets/windows/target.go, cmd/querytee/main.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ingester/checkpoint_test.go, pkg/ingester/flush.go, pkg/ingester/flush_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/recovery.go, pkg/ingester/recovery_test.go, pkg/loki/modules.go, pkg/lokifrontend/frontend/config.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/tail.go, pkg/querier/tail_test.go, pkg/storage/chunk/client/aws/metrics_autoscaling_test.go, pkg/storage/chunk/client/testutils/testutils.go, pkg/storage/factory.go, pkg/storage/store.go, pkg/storage/stores/series/index/table_manager.go, pkg/storage/stores/series/index/table_manager_test.go, pkg/storage/stores/series/series_store_test.go, pkg/util/net.go, tools/querytee/instrumentation.go, tools/querytee/proxy_endpoint.go
Refactors Loki to inject logger from the constructors instead of using global logger variable. It is generally considered a good practice. 
[Fixes #<issue number>](https://github.com/grafana/loki-private/issues/810)
**Checklist**
=> Stop using global logger in modules

.drone/drone.jsonnet, .drone/drone.yml, loki-build-image/Dockerfile
This updates golangci-lint in our build image so that we can use `gochecksumtype`.
**Checklist**
=> Update golangci-lint to 1.55.1.

docs/sources/send-data/_index.md, docs/sources/send-data/otel/_index.md
In PR #10727, we added support for ingesting logs to loki in OTLP format. This PR adds the documentation on how to configure otel collector and how the data is mapped from OTLP format to Loki format.
**Checklist**
=> add documentation on how to use otel collector for ingesting logs to loki

docs/sources/configure/examples/query-frontend.md, docs/sources/get-started/_index.md, docs/sources/operations/query-fairness/_index.md, docs/sources/operations/troubleshooting.md, docs/sources/send-data/k6/query-scenario.md, docs/sources/visualize/grafana.md
Updating "datasource" to be "data source" per recent decision by Style Council.
=> [Style] Data source as two words.

CHANGELOG.md, cmd/migrate/main.go, docs/sources/configure/_index.md, docs/sources/setup/upgrade/_index.md, integration/loki_micro_services_test.go, pkg/loki/loki.go
Change the default for a subset of metrics. After this all Loki metrics should start with "loki_". This changes the following metrics:
cortex_distributor_ingester_clients
cortex_dns_failures_total
cortex_dns_lookups_total
cortex_dns_provider_results
cortex_frontend_query_range_duration_seconds_bucket
cortex_frontend_query_range_duration_seconds_count
cortex_frontend_query_range_duration_seconds_sum
cortex_ingester_flush_queue_length
cortex_kv_request_duration_seconds_bucket
cortex_kv_request_duration_seconds_count
cortex_kv_request_duration_seconds_sum
cortex_member_consul_heartbeats_total
cortex_prometheus_last_evaluation_samples
cortex_prometheus_notifications_alertmanagers_discovered
cortex_prometheus_notifications_dropped_total …
=> Change default of metrics.namespace

docs/sources/operations/autoscaling_queriers.md, docs/sources/operations/observability.md, docs/sources/operations/scalability.md, docs/sources/operations/shuffle-sharding/_index.md
After the default metrics namespace is changed to "loki" these metrics mentioned in the docs have to change as well. Should be merged at the same time as https://github.com/grafana/loki/pull/11110
**Checklist**
=> Update changed metrics in docs

production/loki-mixin-compiled-ssd/dashboards/loki-reads.json, production/loki-mixin-compiled/dashboards/loki-reads.json, production/loki-mixin/dashboards/loki-reads.libsonnet
The per-pod latency panel should use "ms" as the unit, instead of the default (which is "short").
I'm also wrapping everything around "defaults", because that's how it is used everywhere. 
N/A
**Checklist**
=> Jsonnet: Fix unit used by per-pod latency panel

CHANGELOG.md, pkg/ingester/ingester.go
This PR is a backport of https://github.com/grafana/loki/pull/10375 to release-2.9.x
Relates to https://github.com/grafana/loki/issues/10759
**Checklist**
=> [release-2.9.x] fix: respect query matcher in ingester when getting label values (#10375)

CHANGELOG.md, tools/lambda-promtail/lambda-promtail/main.go, tools/lambda-promtail/lambda-promtail/main_test.go
=> fix(tools/lambda-promtail): not evaluate empty string for drop_labels

docs/sources/send-data/promtail/cloud/ecs/_index.md
Currently the docs suggest using the `loki` output plugin, however the options provided align with the `grafana-loki` plugin
**Checklist**
=> Use correct plugin name for fluentbit ecs task

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/manifests/openshift/bases/loki-operator.clusterserviceversion.yaml
This updates the `skipRange` used in the bundle for the OpenShift version of the operator to support the next development version.
[LOG-4713](https://issues.redhat.com/browse/LOG-4713)
**Checklist**
=> operator: Update skipRange for next OpenShift release

pkg/querier/queryrange/codec.go, pkg/util/httpreq/tags.go
https://github.com/grafana/loki/pull/10858 removed the code that would inject query tags into the context of the querier. This change adds an extraction in the decode method.
**Checklist**
=> Extract query tags from HTTP requests.

pkg/logql/engine.go, pkg/logqlmodel/error.go, pkg/querier/worker/util.go
Fallout of a recent change to reduce complexity in our tripperware/middleware in #10688 lead to non-retryable errors being retried by the retry middleware in the frontend.
This PR is a solution to that problem, I'm not sure it's the best solution, but it's a solution....
**Checklist**
=> Loki: fix mapping of non-retryable error codes

pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/volume.go, pkg/querier/queryrange/volume_test.go
We had originally assumed that it would be weird for a user to get back a timeseries response from `volume_range` that didn't include a datapoint with a timestamp at the start of their requested range. This was a bad assumption. The `volume_range` endpoint is inherently doing aggregations. For each step, a datapoint is calculated representing the percent of chunk volumes that the selector appeared in. It therefore stands to reason that the steps volume was not that value until the end of the step time range, as we are to assume volume is monotonically increasing. The fact that we were using the start of the range made it difficult to turn this data into a per-second rate, which this PR aims to fix.
Fixes #11134
=> always align volume range timestamp to end of step

Makefile, loki-build-image/Dockerfile
The changes in https://github.com/grafana/loki/pull/11130 broke `make build-image` and `make build-image-push`. This defaults the target arch added in #11130 so those make targets still work.
=> Default build-image target arch to amd64

pkg/loki/modules.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/codec_test.go, pkg/querier/queryrange/limits_test.go, pkg/querier/queryrange/queryrangebase/definitions/interface.go, pkg/querier/queryrange/queryrangebase/middleware.go, pkg/querier/queryrange/queryrangebase/query_range.go, pkg/querier/queryrange/views.go
https://github.com/grafana/loki/pull/10858 removed the extraction of the query time header on the querier side and the generation of the cache number. This change adds them back and uses the headers of the response format.
**Checklist**
=> Propagate query metrics and cache num information.

docs/sources/setup/install/helm/install-monolithic/_index.md
S3 Helm example uses the wrong keys. See: https://github.com/grafana/loki/blob/cc6f0eca9849409a10cd1f5e0c87f03e46cf6dd2/production/helm/loki/values.yaml#L280-L281
**Checklist**
=> Fix S3 Helm example

clients/cmd/logstash/lib/logstash/outputs/loki.rb, clients/cmd/logstash/lib/logstash/outputs/loki/batch.rb, clients/cmd/logstash/lib/logstash/outputs/loki/entry.rb, clients/cmd/logstash/logstash-output-loki.gemspec, clients/cmd/logstash/loki-metadata.conf, clients/cmd/logstash/loki.conf, clients/cmd/logstash/spec/outputs/loki/entry_spec.rb, clients/cmd/logstash/spec/outputs/loki_spec.rb, docs/sources/get-started/labels/structured-metadata.md, docs/sources/send-data/logstash/_index.md
This PR adds support for Loki Structured Metadata to the logstash output plugin.
Given that Structure Metadata is enabled as an experimental feature plugin changes were done in a way that is backward compatible for users not wanted structured metadata.
**Checklist**
=> feat(logstash): clients logstash output structured metadata support

production/ksonnet/loki/images.libsonnet
Rationale being
1. Unify with extstore based cache we use on cloud
2. Looks like some extra useful metrics are exported on `0.11.3`
**Checklist**
=> chore(jsonnet): Upgrade memcached-exporter to `0.11.3`

.github/workflows/vulnerability-scan.yml, pkg/querier/queryrange/codec.go
Fixes a panic when the underlying response struct is accessed but not populated after an out-of-bounds request is short-circuited via `NewEmptyResponse` [here](https://github.com/grafana/loki/blob/main/pkg/querier/queryrange/limits.go#L155-L164). This PR ensures the embedded types are not nil in accordance with the other variants in this function.
=> populate empty resonse for IndexStatsResponse and VolumeResponse

pkg/querier/queryrange/codec.go
Backport 265018b7293329241ffe9b7c56f38afb07b6b08f from #11209
---
Fixes a panic when the underlying response struct is accessed but not populated after an out-of-bounds request is short-circuited via `NewEmptyResponse` [here](https://github.com/grafana/loki/blob/main/pkg/querier/queryrange/limits.go#L155-L164). This PR ensures the embedded types are not nil in accordance with the other variants in this function.
=> [k174] populate empty resonse for IndexStatsResponse and VolumeResponse

pkg/logql/syntax/serialize.go, pkg/logql/syntax/serialize_test.go
This is a follow up to https://github.com/grafana/loki/pull/11123 and fixes a few bugs discovered by increasing the test coverage.
**Checklist**
=> Increase test coverage for AST serialization to >94%.

docs/sources/configure/_index.md, pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/config.go, pkg/bloomcompactor/sharding_test.go, pkg/validation/limits.go
We want to control bloom compaction per tenant basis. Adding configs to enable/disable bloom compactor. 
**Checklist**
=> [bloom-compactor] Add configs to enable compactor per tenant

pkg/storage/bloom/v1/tokenizer.go, pkg/storage/bloom/v1/tokenizer_test.go
Rebuilds tokenizers based on an iterable approach. This ends up being significantly faster -- benchmarks below.
This PR doesn't remove the old tokenizers, just adds the new ones. Revamping tokenizer consumers & removing the old variants can be done in a separate PR.
Roughly, raw tokenizers complete in 66% of the time and chunkID prefixed tokenizers in ~55-60% of the time.
```
pkg: github.com/grafana/loki/pkg/storage/bloom/v1
BenchmarkTokens/three/v1-10      	  134811	      8648 ns/op	       0 B/op	       0 allocs/op
BenchmarkTokens/three/v2-10      	  179797	      5728 ns/op	       0 B/op	       0 allocs/op
BenchmarkTokens/threeSkip1/v1-10 	  215822	      5260 ns/op	       0 B/op	       0 allocs/op
BenchmarkTokens/threeSkip1/v2-10 	  343784	      3514 ns/op	       0 B/op	       0 …
```
=> iterable tokenizer w/ comparison benching

pkg/storage/bloom/v1/fuse.go, pkg/storage/bloom/v1/fuse_test.go
returns the list of chunks in the bloom which failed the test so we can merge these results across blocks
=> inverts the logic when testing a block against a list of chunks

pkg/storage/bloom/v1/fuse.go, pkg/storage/bloom/v1/fuse_test.go, pkg/storage/bloom/v1/util.go
Adds a few utilities for comparing fingerprints to blocks that cover a specific fingerprint range. Will likely need to be refactored with more comprehensive types, but the logic still applies.
=> boundscheck & partitioning fingerprints between blocks

integration/loki_micro_services_delete_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/metrics.go, production/loki-mixin-compiled-ssd/dashboards/loki-retention.json, production/loki-mixin-compiled/dashboards/loki-retention.json, production/loki-mixin/dashboards/loki-retention.libsonnet
In PR #9884, we separated the retention loop from compaction to avoid blocking compaction for too long due to some intensive delete requests. Currently, we track retention and compaction using the same metrics. This PR adds separate metrics for monitoring retention operation. I have also updated the Retention dashboard to use the new metrics.
=> compaction: Separate metrics for tracking retention and compaction

pkg/loki/modules.go, pkg/querier/queryrange/codec.go, pkg/querier/queryrange/codec_test.go, pkg/querier/queryrange/instrument.go
The changes in https://github.com/grafana/loki/pull/10688 did not propage the trace ID from the context. `Frontend.RoundTripGRPC` would inject the trace ID into the request. That's not done in `Frontend.Do`. This changes extends the `codec.EncodeRequest` to inject the trace ID there. This is more inline with other metadata.
(cherry picked from commit 8d34f857bcb41120fca71948f9b7dc3504047228)
=> [k174] Propagate trace ID with HTTP gRPC request. (#11251)

pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/storage/bloom/v1/tokenizer.go, pkg/storage/bloom/v1/tokenizer_test.go, tools/tsdb/bloom-tester/lib.go, tools/tsdb/bloom-tester/lib_test.go, tools/tsdb/bloom-tester/metrics.go, tools/tsdb/bloom-tester/readlib.go, tools/tsdb/bloom-tester/readlib_test.go
Removes all usage of v1 tokenizers, renames v2 to v1 since we never released this in a production way.
**Checklist**
=> tokenizer v1 cleanup

pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/storage/bloom/v1/tokenizer.go, pkg/storage/bloom/v1/tokenizer_test.go
Previously, the `calculatePrefix` function was used to generate the token buffer used, but this wouldn't necessarily have enough space to append the ngram afterwards without reallocating+copying the token buffer. This PR ensures we allocate enough space for both prefix and ngram in the token buffer.
=> utilities for reducing ngram allocations in token iterator construction

pkg/querier/queryrange/split_by_interval.go, pkg/querier/queryrange/split_by_interval_test.go
The recent change https://github.com/grafana/loki/pull/11246 requires that `LokiRequest.Plan` is always set.
**Checklist**
=> Set query plan when copying LokiRequest

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/bloomcompactor_test.go, pkg/bloomcompactor/sharding.go, pkg/util/ring/sharding.go
This PR fixes the check in the bloom compactor startup to ignore all other index types than TSDB.
When updating an existing Loki installation that uses BoltDB Shipper in the schema config, you get the following error:
```
invalid tsdb path:
/data/boltdb-shipper-cache/XXXXXXXXX_index_19682/write-0-1639160260677624223-1700595900
││ create index shipper
││ github.com/grafana/loki/pkg/bloomcompactor.New
││     /src/loki/pkg/bloomcompactor/bloomcompactor.go:159
││ github.com/grafana/loki/pkg/loki.(*Loki).initBloomCompactor
││     /src/loki/pkg/loki/modules.go:1406
││ github.com/grafana/dskit/modules.(*Manager).initModule
││     /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136
││ github.com/grafana/dskit/modules.(*Manager).InitModuleServices
││ …
```
=> Fix bloom compactor startup when using unsupported index type

pkg/bloomcompactor/bloomcompactor.go, production/docker/config/loki.yaml
Follow up from https://github.com/grafana/loki/pull/11285/, where Loki doesn't start up due to duplicate metric registration. 
```
2023-11-22 22:43:32     /src/loki/vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go:276 +0x178
2023-11-22 22:43:32 github.com/grafana/loki/pkg/storage/stores/shipper/indexshipper/downloads.newMetrics({0x2a62040, 0x4001baa660})
2023-11-22 22:43:32     /src/loki/pkg/storage/stores/shipper/indexshipper/downloads/metrics.go:21 +0xa4
2023-11-22 22:43:32 github.com/grafana/loki/pkg/storage/stores/shipper/indexshipper/downloads.NewTableManager({{0x4000cdae58, 0x18}, 0x45d964b800, 0x4e94914f0000, 0x0, {0xffff4f32e908, 0x40009c6750}}, 0x24192e0, {0x2a89f50?, 0x40004e7320}, ...)
2023-11-22 22:43:32 …
```
=> Fix bloom compactor startup duplicate metric registration

pkg/bloomcompactor/bloomcompactor.go, pkg/storage/bloom/v1/archive.go, pkg/storage/bloom/v1/block_writer.go, pkg/storage/bloom/v1/reader.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/client_test.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go
This reverts commit af177034 (https://github.com/grafana/loki/pull/11267)
because the compression/uncompression must be done outside of the client
context: https://raintank-corp.slack.com/archives/C056KUQFBFT/p1700494151990649
=> Revert "Compression of bloom blocks (#11267)"

clients/pkg/logentry/logql/parser.go, pkg/logql/syntax/parser.go, pkg/logqlmodel/error.go, pkg/util/server/error.go
Making a request to the `/volume{,_range}` endpoints results in a 500 is a LogQL expression is given instead of the expected label matchers. The reason for this is that the error is not wrapped in such a way as to be interpreted by `ClientHTTPStatusAndError` correctly.
5xx responses from the querier are automatically retried, so any invalid request currently results in 5 retries which are unnecessary.
=> bug(volume): return 400 error for invalid volume request

docs/sources/configure/_index.md, pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/config.go, pkg/bloomgateway/sharding.go
This PR adds three new settings to the Bloom-Gateway config:
- `worker_concurrency`: replaces the `numWorkers` constant. Named after the scheduler's `scheduler_worker_concurrency` config.
- `max_outstanding_per_tenant`: replaces the `maxTasksPerTenant` constant. Named after the frontend's  `max_outstanding_per_tenant` config.
- `pending_tasks_initial_capacity`: replaces the pendingTasksInitialCap constant.
**Note to the reviewers:**
- I think in the future `max_outstanding_per_tenant` should be configurable per-tenant. This would require refactoring the queue pkg and the frontend/scheduler, so I think it doesn't make sense it in this PR.
- I moved the `Limits` struct definition to `config.go` so have all the adjustable settings in the same place.
=> Make Blooms-Gateway queue settings configurable

integration/loki_micro_services_test.go, pkg/querier/queryrange/codec_test.go, pkg/util/marshal/marshal_test.go, pkg/util/marshal/query.go
This is a followup PR for https://github.com/grafana/loki/pull/10419 wrt this comment https://github.com/grafana/loki/pull/10419#discussion_r1406285386.
If there is no parsed nor structured-metadata labels in a given entry, and the categorize-labels header is set, add an empty object to the entry array. For example, we currently return:
```json
{
"data": {
"encodingFlags": [
"categorize-labels"
],
"result": [
{
"stream": {
"agent": "promtail",
"filename": "/var/log/nginx/json_access.log",
"host": "appfelstrudel",
"job": "nginx_access_log"
},
"values": [
[
"1701096036028751750",
"example line"
]
]
}
]
}
}
```
But we want:
```json
{
"data": {
"encodingFlags": [
"categorize-labels"
],
"result": [
{
"stream": {
"agent": "promtail",
"filename": "/var/log/nginx/json_access.log",
"host": …
```
=> Categorized Labels: Return empty JSON object if no parsed nor structured metadata labels

pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, tools/tsdb/bloom-tester/lib.go
Removes the stubbed out metrics from the Bloom Tokenizer, and puts in metrics that were being captured and deemed useful during initial POC testing.
**Checklist**
=> Initial pass at metrics for bloom tokenizer

docs/sources/setup/install/helm/reference.md, production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl, production/helm/loki/values.yaml
Add swift to common config via helm.
No issue
**Checklist**
=> Helm: Add swift credentials and container name to common config

pkg/logql/syntax/ast.go, pkg/logql/syntax/ast_test.go
This PR adds a missing `String()` call for the `or` statement in line filters. It also fixes a bug where `or` statements were not applied in conjunction with an IPLineFilter expression.
**Checklist**
=> Fix `or` filter not being stringified correctly

pkg/storage/config/schema_config.go, pkg/storage/config/schema_config_test.go
Unmarshalling for `IndexPeriodicTableConfig` is not working as expected since it contains an inline field that implements `yaml.Unmarshaler` interface. Configuring `path_prefix` is resulting in a error because it tries to Unmarshal to the parent inline field directly.
Fix this by implementing `yaml.Unmarshaler` interface for `IndexPeriodicTableConfig`
related to: https://github.com/go-yaml/yaml/issues/125
```
field path_prefix not found in type struct { Prefix string "yaml:\"prefix\""; Period model.Duration "yaml:\"period\""; Tags config.Tags "yaml:\"tags\"" }
```
**Checklist**
=> config: fix index periodic config unmarshal

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/client.go, pkg/bloomgateway/querier.go
This PR addresses some TODOs in the Bloom-Gateway component to reduce allocations by pooling.
**Note for reviewers:**
- I'm not really sure about the max size for the preallocated pools. Used 16K for all of them but that's probably too much for pools such as the `responsesPool`, `addressesPool`... Feel free to leave a comment in the PR with an estimate on the size you think it would make sense to set as the max.
=> Bloom-Gateway: Use pools to reduce allocations

pkg/storage/stores/shipper/bloomshipper/block_downloader.go, pkg/storage/stores/shipper/bloomshipper/block_downloader_test.go
The `blockDownloader` does not wait until all of its worker goroutines are finished. This leads to a flaky test, see #11347 
To properly fix the behaviour, the `stop()` function should wait until all workers are done.
Closes #11347
=> Wait for all workers to stop when stopping blockdownloader

clients/cmd/fluent-bit/out_grafana_loki.go
This redacts the basic auth credentials from the configured URL that is displayed when fluent-bit is started, if these are included. Go's built-in redaction only hides the password, turning a url like `http://user:pass@example.com` into `http://user:xxxxx@example.com`.
Fixes #10514 
**Checklist**
=> fluent-bit: Redact basic auth credentials from fluent-bit logging

pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/storage/bloom/v1/tokenizer.go
The main work of this PR is to improve the performance of the reassemble() function.  By changing the assignment of the 'cur' variable to not do addition, and incrementing the 'pos' variable separately, the benchmarks improved as follows:
BenchmarkTokens/threeSkip1Chunk/v2-10  	   88864	     13487 ns/op
BenchmarkTokens/threeSkip1ChunkAt2/v2At2-10         	   98607	     12256 ns/op
(This was validated with multiple runs, on multiple size inputs)
The remaining changes in the PR are just to add some benchmarking for PopulateSeriesWithBloom, in case we need to do other comparisons for future improvements.
=> Bloom tokenization performance tweaks

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/worker.go, pkg/storage/stores/shipper/bloomshipper/store.go
At current point in time, the worker calls `w.store.GetBlockQueriersForBlockRefs()` to obtain a list of block queriers sorted by fingerprint in ascending order.
However, the shipper used by the store to fetch blocks by its refs, calls a callback function when a requested block is available. Instead of waiting for all callbacks to be called and then returning a single list of block queriers, the store now exposes a new function `ForEach()` that also accepts a callback that is passed to the underlying shipper.
This allows to process blocks in the worker as soon as they become available. Some block may be served from cache, some may need to be downloaded. That way, we reduce waiting time.
=> Bloom Gateway: process blocks immediately when they are available

pkg/bloomgateway/util.go, pkg/bloomgateway/util_test.go
Since chunks don't necessarily have the same duration, we cannot assume that the last item of a slice sorted by `From` time also has the greatest `Through` time.
=> Fix `getFromThrough()` function for ShortRefs

docs/sources/configure/_index.md, pkg/bloomgateway/cache.go, pkg/bloomgateway/cache_test.go, pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/bloomgateway/config.go, pkg/bloomgateway/querier.go, pkg/logproto/compat.go, pkg/logproto/compat_test.go, pkg/logqlmodel/stats/context.go, pkg/loki/modules.go, pkg/storage/chunk/cache/resultscache/cache.go, pkg/storage/chunk/cache/resultscache/config.go, pkg/validation/limits.go
This PR adds caching to the bloom-gateway client. It uses the result cache from https://github.com/grafana/loki/pull/11343.
Here's how we:
- Merge responses: group all chunks by FP and remove duplicated chunk checksums.
- Extract responses based on time span: For all chunks in each FP, add to the extracted response only the chunks that overlaps with the desired start and end time.
=> Bloom-Gateway cache

tools/lambda-promtail/lambda-promtail/cw.go, tools/lambda-promtail/lambda-promtail/cw_test.go
Adds the `__aws_log_type` label to AWS CloudWatch logs in `lambda-promtail`.
N/A
AWS S3 & Kinesis log types already have this label. The `lambda-promtail` documentation [here](https://github.com/grafana/loki/blob/main/docs/sources/send-data/lambda-promtail/_index.md?plain=1#L154) suggests that CloudWatch logs has this label added as well, but in practice it does not AFAICT.
**Checklist**
=> lambda-promtail: cloudwatch: add '__aws_log_type' label

pkg/querier/queryrange/marshal.go, pkg/querier/queryrange/marshal_test.go
This fixes a regression in `frontend.encoding=protobuf`:
```
body rpc error: code = Internal desc = invalid response format, got (*queryrange.VolumeResponse)
```
**Checklist**
=> Wrap VolumeResponse.

pkg/compactor/metrics.go
I added a new metric but prefixed it by mistake with `loki_boltdb_shipper` instead of `loki_compactor`. This PR fixes it.
=> compactor: fix metric name for a compactor

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/bloomgateway/multiplexing.go, pkg/bloomgateway/util.go, pkg/bloomgateway/util_test.go, pkg/bloomutils/iter.go, pkg/bloomutils/ring.go, pkg/bloomutils/ring_test.go, pkg/storage/bloom/v1/iter.go, pkg/storage/bloom/v1/iter_test.go
Calling `c.sharding.OwnsFingerprint(tenant, uint64(fingerprint))` for each Series of a TSDB index is very expensive, because it not only creates the tenant's sub-ring but also needs to check the fingerprint against it.
Instead, we can pre-calculate the current instance's token ranges and check if the (uint32 converted) fingerprint is contained within these ranges.
The main change of this PR is https://github.com/grafana/loki/commit/5b58326c19eba7058823a5317ff0af2aa0ce8d2c
=> Bloom Compactor: Optimize check for fingerprint ownership

pkg/storage/stores/shipper/indexshipper/downloads/index_set.go, pkg/storage/stores/shipper/indexshipper/tsdb/multi_file_index.go
In the case where we have zero elements, we can exit early; with 1 element there's no need for concurrency.
This will provide a small optimisation and also make our profiles/execution traces easier to read.
We have a fairly significant amount of requests which don't require concurrency:
=> Shortcut callback execution if there are 1 or fewer elements

pkg/bloomcompactor/chunkcompactor.go, pkg/bloomcompactor/chunkcompactor_test.go, pkg/storage/stores/shipper/bloomshipper/block_downloader.go, pkg/storage/stores/shipper/bloomshipper/block_downloader_test.go, pkg/storage/stores/shipper/bloomshipper/client.go
Bloom blocks in the wild likely exceed the memory resources of a compactor. Therefore we need to make sure that we don't copy block data into memory, but rather write to and read from disk.
=> Avoid reading block files into memory

docs/sources/send-data/promtail/scraping.md
Replaces @Alex3k PR #9058 which has gone quite stale (file has moved, new content has been added).
Adds a mini table of contents at the beginning of the page with links to headings.
Rearranges the headings so that they are in alphabetical order.
Content below line 27 is unchanged and previously published, it has only been moved in the file.
=> alphabetize headings and add mini-TOC

operator/CHANGELOG.md, operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-chunks.json, operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json, operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-retention.json, operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json, operator/jsonnet/config.libsonnet, operator/jsonnet/jsonnetfile.json, operator/jsonnet/jsonnetfile.lock.json
- New write dashboards for structured metadata done in https://github.com/grafana/loki/pull/11087
Issue: https://issues.redhat.com/browse/LOG-4700
**Checklist**
=> operator: Adds structured metadata dashboards

CHANGELOG.md, pkg/storage/chunk/cache/memcached.go, pkg/storage/chunk/cache/memcached_client_test.go, pkg/storage/chunk/cache/memcached_test.go
Reverts grafana/loki#11363
This PR was causing some issue. Spend some time testing on some internal cell. Still couldn't track down the issue yet. Reverting to make `main` stable for now.
=> Revert "bugfix(memcached): Make `memcached` batch fetch truely context aware"

.github/workflows/snyk-pr-comment.yml, .github/workflows/trivy-pr-comment.yml, Makefile
Adds trivy filesystem scanning to our Makefile and PR pipelines. This will scan the `go.mod` file for vulnerabilities in dependencies, which are sometimes missed by just scanning the image.
PS @dannykopping this also adds the changes to the vulnerabilities output we talked about that should make it easier to identify a) where the vulnerability is (ie. docker image / os dep vs go.mod dep), and b) what version the dependency needs to be updated to in order to fix it.
=> Add trivy filesystem scanning

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
This allows us to duplicate (i.e. "tee") some of the log streams from the `Distributor` by introducing an optional interface in a follow-up PR.
None
See inline comments
**Checklist**
=> Refactor Distributor.Push() to be able to Tee log streams.

production/ksonnet/loki/bloom-compactor.libsonnet, production/ksonnet/loki/bloom-gateway.libsonnet, production/ksonnet/loki/bloomfilters.libsonnet, production/ksonnet/loki/images.libsonnet, production/ksonnet/loki/loki.libsonnet
This PR adds the deployment of the bloom-compactor and the bloom-gateway to the Loki jsonnet lib.
Both components are deployed as StatefulSets, using disks backed by PersistentVolumeClaims. Additionally, the bloom-gateways can also be configured with local SSDs when available.
_:warning: :construction: :warning: Bloom-compactor and bloom-gateway are still in development and not fully functioning. Do not enable the flag `$._config.use_bloom_filters` unless you know what you're doing and/or actively developing the feature._
=> Add jsonnet lib for deploying Bloom Compactor and Bloom Gateway

pkg/logql/syntax/serialize.go, pkg/logql/syntax/serialize_test.go
Originally we would not set the matcher of a label filter if the name or value was empty. However , `post != ""` is a valid filter expression with an empty value.
**Checklist**
=> Always set matcher in label filter deserialization.

pkg/ingester/checkpoint_test.go, pkg/ingester/ingester.go, pkg/ingester/instance.go, pkg/ingester/instance_test.go, pkg/logql/log/metrics_extraction.go, pkg/logql/log/pipeline.go, pkg/querier/querier_mock_test.go, pkg/storage/store.go, pkg/storage/store_test.go
This PR implements interfaces to inject new pipelines/extractors into the query path of queriers and ingesters.
=> Implement hooks to instrument query pipelines

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/tee.go, pkg/loki/loki.go, pkg/loki/modules.go
This allows us to inject a `Tee` in the `Distributor` that can duplicate all of the incoming log stream, before they are replicated.
No issue
**Checklist**
=> Add log duplication (tee-ing) in the Distributor

pkg/logql/log/label_filter.go, pkg/logql/syntax/clone.go, pkg/logql/syntax/clone_test.go
The `LineFilterLabelFilter.Filterer` wasn't cloned which resulted in nil pointer panics.
**Checklist**
=> Clone filterer of label filter

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/config.go, pkg/bloomgateway/multiplexing.go, pkg/bloomgateway/multiplexing_test.go, pkg/bloomgateway/util.go, pkg/bloomgateway/worker.go, pkg/storage/bloom/v1/block.go, pkg/storage/bloom/v1/index.go, pkg/storage/bloom/v1/test_util.go
So far, the line filters from the user query have been tokenized to n-grams based on the per-tenant setting.
However, since the setting can change over time, block may be written with different n-gram sizes.
This PR adds the ability to read the n-gram length from the block schema at query time and tokenizes the line filters from the input just ahead of searching the block.
**Checklist**
=> Tokenize line filters on a per-block basis

production/helm/loki/src/dashboards/loki-logs.json, production/loki-mixin-compiled-ssd/dashboards/loki-logs.json, production/loki-mixin-compiled-ssd/dashboards/loki-operational.json, production/loki-mixin-compiled-ssd/dashboards/loki-reads.json, production/loki-mixin-compiled/dashboards/loki-logs.json, production/loki-mixin-compiled/dashboards/loki-operational.json, production/loki-mixin-compiled/dashboards/loki-reads.json, production/loki-mixin/dashboards/dashboard-loki-logs.json, production/loki-mixin/dashboards/dashboard-loki-operational.json, production/loki-mixin/dashboards/loki-reads.libsonnet
* Update our legacy panels (Loki/Logs and Loki/Operation) do use `"type": "timeseries"` instead of `"type": "graph"`. The graph type is deprecated on recent Grafana versions. I tested the changes with Grizzly and it worked fine.
* Fix our p99 panel unit. I previously made it to be `s` instead of `short` but when replicating the change on our source code I put the change at the wrong identation level. This time I made sure to test the change with Grizzly.
=> Jsonnet: Fix and update loki-mixin panels

operator/internal/manifests/storage/configure.go
Refactor the function `ensureObjectStoreCredentials` in manifests/storage package to make it more easy to understand
**Checklist**
=> operator: Refactor ensureObjectStoreCredentials in manifests/storage package

pkg/bloomcompactor/bloomcompactor.go, pkg/loki/modules.go
If there are multiple period configs with TSDB, then each shipper
instance needs to register their metrics with a unique static label set,
otherwise, the bloom compactor would panic at startup due to duplicate
metric registration attempt.
We don't want/need to upload any index files in the bloom compactor, but
we only download files.
=> Bloom Compactor: Fix panic at startup if multiple TSDB period configs are defined

pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/bloomgateway/querier.go, pkg/bloomgateway/querier_test.go, pkg/loki/modules.go
The bloom gateway client panicked, because the ring, from which it gets the subring for the tenant was never passed as argument in the constructor, even though it was part of the client struct.
=> Fix panic in bloom gateway client

CHANGELOG.md, pkg/querier/queryrange/codec.go
=> Do not reflect label names in request metrics' "route" label

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/gomemcache/memcache/memcache.go, vendor/modules.txt
See https://github.com/grafana/gomemcache/pull/16
I think this should largely be innocuous so I'm not documenting it in the release notes or upgrade guide yet, but if we see some significant changes in behaviour I will (or roll this back). I'm not expecting fireworks from this change, though.
**Checklist**
=> Revendor gomemcache to import deadline fix

docs/sources/send-data/promtail/cloud/ecs/_index.md, docs/sources/send-data/promtail/cloud/ecs/ecs-task.json
Also updated the Docker image to match the latest version
**Checklist**
=> Docs: Fix link to `ecs-task.json` file in ECS instructions

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/tee.go
It is useful for implementations of Tee to also know the tenant who sent the logs. This PR adds tenant to the tee interface.
=> Add tenant to tee

pkg/logql/log/fmt.go, pkg/logql/log/labels.go
reverts pooling that causes a panic for concurrent map writes
=> revert map pooling from #11484

docs/sources/reference/api.md
Adds example for querying against Grafana Cloud log tenant to API docs. 
Addresses internal doc request that came about via a Support ticket
**Checklist**
=> Docs: Adding example in API docs for querying against Grafana Cloud log tenant

docs/sources/reference/api.md
=> Update API docs

docs/sources/reference/api.md
=> Manual backport #11581

CHANGELOG.md, pkg/ruler/registry.go, pkg/ruler/registry_test.go
A ruler handling many hundreds of rules can provoke a situation where the WAL appender reads & modifies tenant configs concurrently in an unsafe way; this PR protects that with a mutex.
Fixes #11569
This doesn't need to be locked in a fine-grained way because this isn't on the hot path.
**Checklist**
=> Ruler: protect overrides map with mutex when accessing tenant configs

pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/metrics.go
Earlier we had a counter for the number of times tables were skipped by compaction due to them being locked by retention. Counter makes it hard to reliably write an alert without making it noisy. I am changing the counter to gauge which would count the number of times tables were consecutively skipped by compaction. This would make it easier to write alerts.
**Checklist**
=> compactor" track number of times table compactions were skipped consecutively

pkg/compactor/retention/retention.go, pkg/compactor/retention/retention_test.go
When a delete request has a line filter and/or is deleting a chunk partially, we create a new chunk from the source chunk and mark the original chunk for deletion. However, when a chunk overlaps multiple tables, we apply heuristics to retain the chunk until all the tables that have it indexed get processed since we need the original chunk to build a new one.
Earlier, we used to process tables from oldest to newest, so the logic to detect if all the tables indexing a chunk are processed was done by seeing if `chunk-end-time` <= `table-end-time`. To put it in simple terms, if the chunk ends in the current table we are processing, it means this is the last table that we are processing, which has the chunk indexed.
However, this does not work anymore …
=> deletion: delete chunk overlapping multiple tables when processing oldest table that has it indexed

CHANGELOG.md, clients/pkg/promtail/promtail.go, clients/pkg/promtail/server/server.go
This PR improves the clarity of log message when the Promtail server is disabled (if `server.disable` is true in config file, or flag `-server.disable` is used).
Previously, the reason "promtailServer cast fail" in log message (as below) was ambiguous, leading to confusion about potential error in config file.
```
level=warn ts=2023-12-09T15:40:24.064376445Z caller=promtail.go:260 msg="disable watchConfig" reason="promtailServer cast fail"
```
The updated message is more understandable, indicating directly that the Promtail server is disabled.
```
level=warn ts=2023-12-09T15:50:58.723168763Z caller=promtail.go:260 msg="disable watchConfig" reason="Promtail server is disabled"
```
N/A. …
=> Promtail: show a clearer reason in "disable watchConfig" log message when server is disabled

CHANGELOG.md, pkg/querier/http_test.go, pkg/querier/queryrange/serialize_test.go, pkg/util/server/error.go, pkg/util/server/error_test.go
#11487 introduced a regression which added trailing newlines to HTTP error response bodies, which may affect client integrations.
This regression hasn't made it into the 2.9.x or 2.8.x releases yet so no backporting is necessary.
**Checklist**
=> Restore previous behaviour of no trailing newlines in HTTP error response bodies

pkg/ruler/registry.go
Expands on #11601
Turns out the previous tests didn't expose all possible causes for data races (another one occurs at https://github.com/grafana/loki/blob/5a55158cc751465846383bc758aa0c169363b292/pkg/ruler/registry.go#L204).
Moving the mutex to the calling function adds more safety.
Fixes #11569
=> Ruler: catering for another data race in tenant config

docs/sources/send-data/promtail/cloud/ec2/_index.md, docs/sources/send-data/promtail/cloud/ecs/_index.md, docs/sources/send-data/promtail/cloud/eks/_index.md
Updates links to path for a couple of example files that were missed in the information architecture moves.
Fixes #11617 
(This is in addition to the updates in https://github.com/grafana/loki/pull/11568)
=> Update paths in cloud config topics

clients/cmd/docker-driver/README.md
Fix the link to the docker-driver documentation.
=> docs: Fix the link to the docker-driver documention

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/_helpers.tpl
The  code in https://github.com/grafana/loki/blob/main/production/helm/loki/templates/_helpers.tpl file doesn't include "swift" type object storage.
when user using swift by configure `loki.storage.swift.*`, then `loki.storage.type` shall = `swift` , but the "loki.isUsingObjectStorage" cannot get the proper value in this case.
As of now "swift" type object storage has been added to resolve Loki HELM Chart error.
**Which issue(s) this PR fixes**:.
Fixes #11611 
**Checklist**
=> [area/loki]: Added "swift" type object storage to resolve Loki HELM Chart error

.devcontainer/devcontainer.json, .drone/drone.yml, .github/workflows/checks.yml, Makefile, clients/cmd/docker-driver/Dockerfile, clients/cmd/promtail/Dockerfile.cross, clients/cmd/promtail/Dockerfile.debug, cmd/logcli/Dockerfile, cmd/logql-analyzer/Dockerfile, cmd/loki-canary-boringcrypto/Dockerfile, cmd/loki-canary/Dockerfile, cmd/loki-canary/Dockerfile.cross, cmd/loki/Dockerfile, cmd/loki/Dockerfile.cross, cmd/loki/Dockerfile.debug, cmd/migrate/Dockerfile, cmd/querytee/Dockerfile, cmd/querytee/Dockerfile.cross, loki-build-image/Dockerfile, loki-build-image/README.md, operator/Dockerfile.cross, production/helm/loki/src/helm-test/Dockerfile, tools/dev/loki-boltdb-storage-s3/dev.dockerfile, tools/lambda-promtail/Dockerfile, tools/tsdb/bloom-tester/Dockerfile
Bumps alpine in the loki build image and ass the build image to the `scan-vulnerabilities` target to make it easier to scan in the future
=> Bump build image

pkg/logql/downstream.go, pkg/logql/downstream_test.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go, tools/dev/loki-boltdb-storage-s3/config/loki.yaml
Sharding of a binary operation with one unshardable side has been broken for quite some time.
**Checklist**
=> Support sharding of binary operation for non shardable side.

operator/bundle/community-openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/community/manifests/loki-operator.clusterserviceversion.yaml, operator/bundle/openshift/manifests/loki-operator.clusterserviceversion.yaml, operator/config/rbac/role.yaml, operator/controllers/loki/lokistack_controller.go, operator/internal/manifests/openshift/rbac.go
Updated RBAC now match the new updated requirements by UWM Alertmanager introduced on https://github.com/openshift/cluster-monitoring-operator/pull/2099
Issue https://issues.redhat.com/browse/LOG-4938
**Checklist**
=> operator: Fixes Ruler RBAC to allow it to send alerts to UWM AM

pkg/logql/optimize.go, pkg/logql/shardmapper.go, pkg/logql/shardmapper_test.go
This fixes a four year old bug. The `optimizeSampleExpr` was switching on the wrong `DownstreamSampleExpr` type.
**Checklist**
=> Skip optimization for DownstreamSampleExpr

.drone/drone.jsonnet, .drone/drone.yml, Makefile
The configuration in `tools/dev/loki-boltdb-storage-s3` was broken in the past because it's easy to miss. This change covers the validation in the CI to raise awareness.
**Checklist**
=> Validate dev cluster config in CI

CHANGELOG.md, pkg/storage/chunk/cache/background.go
The size check was not being performed atomically, which led to flakiness in the `TestBackgroundSizeLimit` test.
=> Cache: correctly check background cache size

operator/CHANGELOG.md, operator/controllers/loki/lokistack_controller.go, operator/controllers/loki/lokistack_controller_test.go, operator/internal/handlers/internal/storage/ca_configmap.go, operator/internal/handlers/internal/storage/ca_configmap_test.go, operator/internal/handlers/lokistack_create_or_update.go, operator/internal/handlers/lokistack_create_or_update_test.go
The operator allows to set a custom CA used for accessing S3-based object storage using the `spec.storage.tls.caName` key. While the operator already produces an error when the ConfigMap referenced by that key does not exist or does not contain data, it does not automatically react to changes to the ConfigMap. This PR fixes that by watching for changes to ConfigMap resources.
[LOG-4897](https://issues.redhat.com/browse/LOG-4897)
-  [This commit](https://github.com/grafana/loki/commit/92611216e8edb7721e83119f73c4606436d04661) of the PR contains a change to the predicate used for checking if a ConfigMap resource has changed. The old implementation used `metadata.generation` which …
=> operator: React to changes in ConfigMap used for storage CA

CHANGELOG.md, pkg/querier/queryrange/log_result_cache.go, pkg/querier/queryrange/log_result_cache_test.go
Log results cache when handling a hit composes an empty response based on the cached request.
But the limit or direction fields in the cached request need not match with the current request being served.
This causes the log results cache to return a response with incorrect limit. This incorrect limit could then get applied when merging responses upstream (split by interval mw for ex.)
This pr fixes this by composing the response based on the request being served.
I also thought about updating the cache key to include both limit and direction to have a clear separation, but I left it as is for the following reason: if a time range contains no log lines, that result would not change irrespective of a different limit or direction
**Which issue(s) this …
=> fix(log results cache): compose empty response based on the request

docs/sources/send-data/fluentbit/_index.md
It improves the docs by addressing #11575 allowing users to use the official fluent-bit helm chart over the deprecated grafana one
Fixes #11575 
@JStickler wanted to take a look at this.
**Checklist**
- [ x ] Reviewed the [`CONTRIBUTING.md`](https://github.com/grafana/loki/blob/main/CONTRIBUTING.md) guide (**required**)
- [ x ] Documentation added
=> docs: Update _index.md addressing #11575

production/docker/config/loki.yaml, production/docker/config/prometheus.yaml, production/docker/docker-compose.yaml
At https://github.com/grafana/loki/pull/9899 added the new `backend` SSD target to the docker compose we ship at `production/docker`. Later on, https://github.com/grafana/loki/pull/8836 removed it since the current stable version of Loki was 2.7.3 and `backend` was introduced with 2.8 (RC at the time of this PR).
The backend target is now GA, this PR enables it back in our provided docker compose.
Additionally, the following improvements/updates are made:
- Move storage config from `common.storage.s3` to `storage.aws`
- Remove schema period using boltdb-shipper
- Update tsdb schema to latest (v13)
- Expose minio web console
=> Fix backend target in docker compose

integration/client/client.go, integration/cluster/cluster.go, integration/loki_micro_services_test.go, pkg/bloomcompactor/bloomcompactor.go, pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/worker.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go, pkg/storage/stores/shipper/bloomshipper/store.go, pkg/storage/stores/shipper/indexshipper/indexgateway/gateway.go
**What?**
This PR adds an end-to-end integration test for creating bloom filters and using them in the gateway to filter chunks.
**Why?**
This test helped to identify bugs in the bloom shipper code that would have taken a very long time to discover in other ways, such as deploying to a dev environment or running a long-running docker compose setup.
**Notes**
The following commits of this PR are actual changes to the compactor/gateway code to make e2e test work:
* https://github.com/grafana/loki/pull/11645/commits/2dcc761ba069a377ece1a3a48fa6c6c59039043c
* https://github.com/grafana/loki/pull/11645/commits/84052ddb34c012e12d3e98b86317a6b18bc3d76e
* https://github.com/grafana/loki/pull/11645/commits/3ba44f83c81bb305d3fb08d0141b6f080bde03ea
The bloom gateway code path for processing blocks …
=> Add e2e tests for bloom filtering

CHANGELOG.md, cmd/loki/main.go, pkg/tracing/config.go, vendor/github.com/grafana/dskit/spanprofiler/README.md, vendor/github.com/grafana/dskit/spanprofiler/spanprofiler.go, vendor/github.com/grafana/dskit/spanprofiler/tracer.go, vendor/modules.txt
Same as https://github.com/grafana/tempo/pull/3276 this adds profiling integration to tracing instrumentation allowing to get profile for a single request removing the noise of everything else.
Thanks me later.
**Checklist**
cc @poyzannur we talked about this for compaction to get profiling per run, all you need is a root span per run !
=> feat: Add tracing integration to profiling.

CHANGELOG.md, production/loki-mixin-compiled-ssd/dashboards/loki-writes.json, production/loki-mixin-compiled/dashboards/loki-writes.json, production/loki-mixin/dashboards/loki-writes.libsonnet
The Distributor latency dashboards are the only ones that were not setting a label for the route, this resulted in the final PromQL expression to not belong to the `_route` namespace.
**Checklist**
=> mixins: add route to write Distributor Latency dashboard

operator/CHANGELOG.md, operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-reads.json, operator/internal/manifests/openshift/internal/dashboards/static/grafana-dashboard-lokistack-writes.json, operator/jsonnet/config.libsonnet, operator/jsonnet/jsonnetfile.json, operator/jsonnet/jsonnetfile.lock.json
Issue: https://issues.redhat.com/browse/LOG-4940
**Checklist**
=> operator: updates mixins to fix structured metadata dashboards

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/backend/query-scheduler-discovery.yaml
This PR adds the namespace attribute to the query-scheduler-service descriptor because it is needed when deploying loki in non-default namespace
Fixes #10048 
**Checklist**
I hope I did everything right with the changelog, chat and readme updates since this my first PR, please tell me if something needs fixing.
=> helm: added missing namespace to query-scheduler-discovery service

docs/sources/configure/_index.md, pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/chunkcompactor.go, pkg/bloomcompactor/chunkcompactor_test.go, pkg/bloomcompactor/chunksbatchesiterator.go, pkg/bloomcompactor/chunksbatchesiterator_test.go, pkg/bloomcompactor/config.go, pkg/bloomcompactor/mergecompactor.go, pkg/bloomcompactor/sharding_test.go, pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/validation/limits.go, pkg/validation/limits_test.go
Added chunks batches iterator to download chunks in batches instead of downloading all of them at once. Otherwise, when the stream contains a lot of chunks, it can lead to OOM.
**Checklist**
=> [bloom-compactor] downloading chunks in batches

CHANGELOG.md, docs/sources/configure/_index.md, pkg/querier/queryrange/labels_cache.go, pkg/querier/queryrange/labels_cache_test.go, pkg/querier/queryrange/limits/definitions.go, pkg/querier/queryrange/roundtrip_test.go, pkg/querier/queryrange/series_cache.go, pkg/querier/queryrange/series_cache_test.go, pkg/validation/limits.go
Adds `max_metadata_cache_freshness` to limit the metadata requests that get cached. When configured, only metadata requests with end time before `now - max_metadata_cache_freshness` are cacheable.
_reason for setting the default to 24h?_
metric results cache can [extract samples for the desired time range from an extent](https://github.com/grafana/loki/blob/b6e64e1ef1fb2a2155661c815d0198e147579c8e/pkg/querier/queryrange/queryrangebase/results_cache.go#L78) since the samples are associated with a timestamp. But the same is not true for metadata caching, it is not possible to extract a subset of labels/series from a cached extent. As a result, we could return inaccurate results, more that what was requested. for ex: returning results from an entire 1h …
=> feat(metadata cache): adds max_metadata_cache_freshness

pkg/logql/log/labels.go, pkg/logql/log/parser_hints.go, pkg/logql/log/parser_test.go
A data race introduced in https://github.com/grafana/loki/pull/11587 was caught  in the [backport to k184](https://github.com/grafana/loki/pull/11668). This removes the shared state of a single global `noParserHints` in favor of creating an empty `Hint` object for each label builder, since the `Hints` is keeping state of `extracted` and `requiredLabels`.
=> fix: remove shared state noParserHints to avoid data race

integration/loki_micro_services_test.go, integration/parse_metrics.go, pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/worker.go
For better observability of the bloom gateway, this PR adds two additional metrics that expose the amount of chunk refs pre and post filtering. This can be used to calculate the filter ratio of the gateways.
Also, the `ForEach` operation on the bloom store is measured so that the latency of fetching/extracting the blocks can be observed.
=> Bloom gateway: Add metrics for store operations and chunk ref counts

pkg/logql/syntax/parser.go
We originally added this limit from fuzz testing and realizing there should be some maximum limit to an allowed query size. The original limit was 5120 based on some internet searching and a best estimate of what a reasonable limit would be. We have seen use cases with queries containing a lot of filter expressions or long expanded variable names where this limit was too small. Apparently the spec does not specify a limit, and more internet searching suggests almost all browsers will handle 100k+ length urls without issue
Some limit here still seems prudent however, so the new limit is now 128k.
**Checklist**
=> Loki: increase the limit for query length from 5k to 128k

.drone/drone.jsonnet, .drone/drone.yml
`validate-example-configs` step is flaky and fails with the following error: `[Text file busy](bash: line 1: ./cmd/loki/loki: Text file busy)`
looks like the recently added `validate-dev-cluster-config` runs in parallel. since both steps run loki target first, they often end up updating the binary when the other step is executing it.
this pr fixes this by running these steps sequentially
**Checklist**
=> chore(build): fix flaky validate examples step

clients/cmd/fluent-bit/config.go
Modify our fluentbit go client to not throw away error messages for invalid configuration values. Instead, wrap them with our existing descriptive messages.
=> Fluentbit: Wrap errors without throwing away the original error message

pkg/storage/stores/shipper/indexshipper/tsdb/head_manager.go, pkg/storage/stores/shipper/indexshipper/tsdb/head_manager_test.go
This PR ensures we retain previous TSDB heads on ingesters for one cycle (15m) in order to serve index queries while waiting for index-gws or queriers to sync it from storage. This bug hadn't surfaced yet (for us) because we've historically used ~6m `chunk-retain` periods which masked this problem (chunks were kept around so we didn't see read gaps). Fixing this bug should allow us to avoid retaining chunks post-flush in ingester memory in TSDB since it doesn't utilize the index-cache (which was the other reason for retaining chunks in memory).
This is very attractive because it allows us to reduce memory pressure in ingesters as well as reduces the data they query since now ingesters will only return the chunk references. This allows queriers to download chunks directly rather than …
=> [TSDB][bug] retain previously rotated tsdb heads for one cycle to serve queries

pkg/storage/bloom/v1/builder_test.go, pkg/storage/bloom/v1/index.go, pkg/storage/bloom/v1/index_querier.go
While debugging some unrelated code, I found that `Seek` was improperly implemented. It should return the first value greater or equal than the target. Previously it would cause iterators to return different values when reset.
=> fixes seek in bloom blocks to correctly return the first fp >= target_fp

pkg/storage/stores/shipper/bloomshipper/block_downloader_test.go
The flaky test is caused by a race condition caused by concurrent writes of a counter that is used to track how often a method was called.
Fixed by converting into an atomic integer.
=> Fix flaky block downloader test

integration/multi_tenant_queries_test.go
Fixes the flaky `TestMultiTenantQuery` integration test.
---
Same PR as https://github.com/grafana/loki/pull/11728 but against `main`.
=> Fix flaky `TestMultiTenantQuery` integration test

production/ksonnet/loki/gateway.libsonnet
We have a linter in place in our internal deployment tooling to catch the usage of Unicode quotes because it has caused some issues due to shells/tooling not recognizing them. The linter has caught one such instance in the jsonnet in the Loki repo, which is fixed in this PR.
=> jsonnet: fix unicode quotes in jsonnet to avoid tools failing to parse it properly

pkg/bloomgateway/multiplexing.go
The wrapper `FilterRequest` wraps `v1.Request` but the additional field with the error channel is never used.
=> Remove unnecessary wrapper around v1.Request

production/ksonnet/loki/bloom-gateway.libsonnet
The value is supposed to be a time.Duration value, rather than an int value for seconds.
This changes fixes the rather small cache TTL.
=> Fix jsonnet config for bloom gateway blocks cache

CHANGELOG.md, docs/sources/release-notes/v2-9.md
Updates changelog and release notes for 2.9.4 patch release
**Checklist**
=> Release 2.9.4

docs/sources/clients/docker-driver/_index.md, docs/sources/installation/docker.md, examples/getting-started/docker-compose.yaml, production/docker-compose.yaml, production/docker/docker-compose.yaml, production/ksonnet/loki-canary/config.libsonnet, production/ksonnet/loki/images.libsonnet, production/ksonnet/promtail/config.libsonnet, tools/release_update_tags.sh
This fixes the docs and some config examples to use the latest patch version. This hadn't been done for a while, so I also added the script to do it from https://github.com/grafana/loki/pull/10646
**Checklist**
=> Update patch versions in docs and YAML files to v2.8.8

docs/sources/get-started/deployment-modes.md, docs/sources/operations/loki-canary/_index.md, docs/sources/send-data/docker-driver/_index.md, docs/sources/send-data/promtail/installation.md, docs/sources/setup/install/docker.md, docs/sources/setup/install/local.md, examples/getting-started/docker-compose.yaml, production/docker-compose.yaml, production/docker/docker-compose.yaml, production/ksonnet/loki-canary/config.libsonnet, production/ksonnet/loki-simple-scalable/example/main.jsonnet, production/ksonnet/loki-simple-scalable/images.libsonnet, production/ksonnet/loki/images.libsonnet, production/ksonnet/promtail/config.libsonnet, tools/release_update_tags.sh
Ran recently introduced tag updater `tools/release_update_tags.sh` (https://github.com/grafana/loki/pull/10646) to update version tags in docs and yaml files
=> Update patch version in docs and yaml files for v2.9.4

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/v2spec.go, pkg/bloomcompactor/v2spec_test.go, pkg/storage/bloom/v1/archive_test.go, pkg/storage/bloom/v1/block.go, pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/storage/bloom/v1/builder.go, pkg/storage/bloom/v1/builder_test.go, pkg/storage/bloom/v1/dedupe_test.go, pkg/storage/bloom/v1/fuse_test.go, pkg/storage/bloom/v1/index.go, pkg/storage/bloom/v1/merge_test.go, pkg/storage/bloom/v1/test_util.go
This is my attempt at making more testable implementations of the work done by the `bloomcompactor` pkg. It's largely inspired by what already exists there, but without depending on things like object storage, chunk clients, etc, it's much easier to locally prove behavior. I'm planning to build on top of this, continuing to integrate work already done in this pkg.
=> [Blooms] Specs out BloomGenerator

pkg/logql/log/labels.go, pkg/logql/log/labels_test.go
This PR fixes an issue where the `label_format` stage sometimes doesn't populate labels when it should.
The label `baz` exists on all log lines but is only populated on the first line.
The issue is this call to [IntoMap](https://github.com/grafana/loki/blob/06bb20914b027c96ac3af27ae36e91f35529524d/pkg/logql/log/fmt.go#L403). It tries to avoid copying the map multiple times [here](https://github.com/grafana/loki/blob/06bb20914b027c96ac3af27ae36e91f35529524d/pkg/logql/log/labels.go#L482) but the `baseMap` variable isn't reset when the labels builder is reset. As a result, calls to to `IntoMap` after the builder has been reset mean that `!b.hasDel() && !b.hasAdd() && !b.HasErr()` evaluates to `true` but `b.baseMap == nil` also evaluates to `true` so no items are copied.
This PR makes it so …
=> reset the basemap when the labelsbuilder is reset

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/bloomgateway_test.go
While removing not matching chunks from a fingerprint, the for loop over the chunks removes items, and therefore the index of the current iteration needs to be adjusted to accommodate for the removal, otherwise it may panic with `out of bounds`.
**Notes for reviewer**:
Extracted from https://github.com/grafana/loki/pull/11717
=> Bloom Gateway: Fix panic in chunk removal after receiving query results

pkg/bloomgateway/util.go, pkg/bloomgateway/util_test.go
The test cases now also cover partially out of bounds blocks as well as inconsecutive block ranges.
=> Extend `TestPartitionFingerprintRange` test case

CHANGELOG.md, pkg/storage/chunk/cache/background.go, pkg/storage/chunk/cache/background_extra_test.go, pkg/storage/chunk/cache/background_test.go
While looking at the metrics from one of our cells, we noticed that the queue size is set to a very high value even when the length is pretty much 0.
Background cache is incrementing the queue size twice for each enqueued key. This pr removes the additional increment call.
`TestBackgroundSizeLimit` might be flaky because of the [writeBackLoop](https://github.com/grafana/loki/blob/8eb09c78c842b61f6619fb3755a43b180536b761/pkg/storage/chunk/cache/background.go#L193) which dequeues from the channel and reduces the queue size concurrently. To make the test predictable, I have set the `WriteBackGoroutines` to 0.
**Checklist**
=> fix(background cache): increment queue size exactly once

pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/worker.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go
The check `isOutsideRange()` returned incorrect results, because the end timestamp of the search interval is not inclusive.
=> Bloom Shipper: Fix bug in block boundary check

pkg/storage/bloom/v1/index_querier.go, pkg/storage/bloom/v1/index_test.go
Move variable declaration to only access the desired page when it's valid. Also removes an unused (duplicate) test fn.
=> [Blooms] Fix panic when accessing page outside of page bounds

docs/sources/get-started/deployment-modes.md
**What this PR does / why we need it**: Docs do not match the code in the helm chart - where the read deployment is made as a statefulset with ReadWriteOnce disks (https://github.com/grafana/loki/blob/main/production/helm/loki/templates/read/statefulset-read.yaml). I suspect the docs are correct that it's possible - but given it's the official helm chart - the deviation should be noted.
N/A
**Checklist**
=> Note the helm chart and docs do not agree

.drone/drone.jsonnet, .drone/drone.yml, integration/loki_micro_services_test.go, pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/metrics.go
This PR modifies the metrics of the bloom compactor to:
- Add new histogram metrics to track the time spent to process compaction cycles, tenants and jobs.
- Replace `_succeeded` and `_failed` metrics with a new `_completed` metric with a status label. 
**Checklist**
=> Add timing metrics for compaction

clients/pkg/promtail/targets/docker/target_test.go
We ported this fix a few days ago to the Agent via this [PR](https://github.com/grafana/agent/pull/6201) but the added test is often failing in our drone pipeline.
I believe that there are two reasons why this test is flaky:
- the test expects that the 5 last lines of logs are the expected ones but it seems that other lines might be logged as well (https://drone.grafana.net/grafana/agent/16045/4/2)
- we saw that the simulated container did not always have enough time to stop before calling the tgt.startIfNotRunning() to restart it. (https://drone.grafana.net/grafana/agent/16077/4/2)
Fix:
- the test now uses "assert.EventuallyWithT" and checks that within 5 seconds the expected log lines will be amongst the logs without duplicate.
- the test now …
=> <Promtail>: Fix flaky docker test

integration/loki_micro_services_test.go, pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/mergecompactor.go, pkg/bloomcompactor/v2spec.go, pkg/bloomcompactor/v2spec_test.go, pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/storage/bloom/v1/metrics.go, pkg/storage/bloom/v1/tokenizer_test.go, pkg/storage/bloom/v1/util.go, pkg/storage/stores/shipper/indexshipper/tsdb/index.go
This PR refactors a bunch of code to separate state+I/O related complexity from logic so we can test and extend it more easily. It also adds more logic for the bloom generator to use.
=> [Blooms] Refactoring bloom compactor to isolate state from logic

.github/workflows/minor-release-pr.yml, .github/workflows/patch-release-pr.yml, .github/workflows/release.yml, .release-please-manifest.json, Makefile
The new release process is being developed in another repo for now as it enables much faster feedback loops. We are at the stage where we are pulling the Loki repo and building images, so it's time to move the `release-please` config into Loki, and configure it for the various packages we will be releasing.
This PR adds the two basic configs that `release-please` requires. This PR does not change anything about the release process, it just enables us to keep iterating out of band until we're ready to move over.
This was already added to `main`, but adding here so I can test it on the release branch
Re #11332
=> feat: add release please config (#11333)

pkg/bloomgateway/multiplexing.go, pkg/bloomgateway/multiplexing_test.go, pkg/bloomgateway/worker.go
The `requestIterator` (`v1.Iterator[v1.Request]`) can be built directly from the task and does not require any unnecessary merging of tasks, since this is done by the `v1.FusedQuerier` already.
=> (chore) Bloom Gateway: Avoid unnecessary merging of tasks prior to passing them to the FusedQuerier

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/multiplexing.go, pkg/bloomgateway/multiplexing_test.go, pkg/bloomgateway/worker.go
This PR refactors the bloom gateway workers so that tasks that have been enqueued by requests do not end up locking the results channel and therefore the worker, in case the request was cancelled (`context cancelled`) or timed out (`context deadline exceeded`).
It also handles errors from the shipper in a way that they are returned to the waiting request asap so it can return and does not need to wait for all tasks to finish.
This PR also fixes the worker shutdown in a way that it now gracefully stops and continues to work off the remaining tasks from the queue.
=> Bloom Gateway: Make tasks cancelable

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/processor.go, pkg/bloomgateway/processor_test.go, pkg/bloomgateway/util_test.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/client_test.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go
The processor executes a set of tasks.
It cleanly separates I/O from logic and therefore is more testable than the current worker implementation.
https://github.com/grafana/loki/blob/9602214abf5f0b016f1cad90e921d1e4d969856c/pkg/bloomgateway/processor.go#L33-L36
**Note**:
~~Only commit https://github.com/grafana/loki/pull/11812/commits/cd28931055a38827f3a8a739fe2a64c165b3fc89 is relevant. The rest of the commits are part of different PRs (#11792 and #11809), which need to be merged first.~~
The processor is not used yet in the worker.
**Certain parts must be refactored when #11810 is merged.**
=> Bloom Gateway: Extract processing logic from bloom worker into separate struct

operator/CHANGELOG.md, operator/internal/handlers/internal/storage/secrets.go, operator/internal/handlers/internal/storage/secrets_test.go, operator/internal/handlers/internal/storage/storage_test.go
The `kverrors` library we currently use to emit errors found in the storage secret is not well suited for this task, because the `Error()` output does not contain the structured metadata which makes many error messages ambiguous. As we use these error messages in the status of the LokiStack this is not helpful for the user.
This has been extracted from #11802. That PR needs to be updated again when this is merged.
**Checklist**
=> operator: Improve messages for errors in storage secret

production/loki-mixin-compiled-ssd/dashboards/loki-writes.json, production/loki-mixin-compiled/dashboards/loki-writes.json, production/loki-mixin/dashboards/loki-writes.libsonnet
Currently, the distributor latency panel uses a "=" in the code as opposed to a "=~", causing the panel to render as empty. This is to fix that issue.
**Checklist**
=> Change distributor latency to have a regular expression equals 

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/processor.go, pkg/bloomgateway/processor_test.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/client_test.go, pkg/storage/stores/shipper/bloomshipper/fetcher.go, pkg/storage/stores/shipper/bloomshipper/fetcher_test.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/store.go
This PR changes the structure of how the bloom client
* The `BloomStore` is the top component interface which implements the `Store` and the `Client` interfaces. The store holds a store entry for each schema period.
* The `bloomStoreEntry` implements the `Store` and `Client` interfaces. It holds a bloom client for a single schema period. Additionally, the store entry also exposes a fetcher for metas (and in the future for blocks), which is responsible for getting data from cache or storage (if not available in cache).
* The `BloomClient` implement the `Client` interface. The bloom client uses an object client for the schema period of the bloom client.
* The `Fetcher` can fetch and cache metas.
This structure is very similar to what we use for the …
=> Bloom shipper: Restructure bloom store

pkg/loghttp/push/otlp.go, pkg/loghttp/push/otlp_test.go
When no resource attributes are defined, check for `service.name` resource attributes fail with `nil pointer dereference`. This PR fixes the issue by checking the bool returned by the `Get` method on resource attributes.
**Checklist**
=> otlp: fix otlp service.name check when no resource attributes are defined

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomgateway/processor.go, pkg/bloomgateway/processor_test.go, pkg/bloomgateway/util_test.go, pkg/bloomgateway/worker.go, pkg/storage/bloom/v1/bounds.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/client_test.go, pkg/storage/stores/shipper/bloomshipper/fetcher_test.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go
The latter struct has more utility functions to compare and operate on bounds.
=> (chore) Bloom shipper: Replace `Keyspace` struct with `v1.FingerprintBounds`

pkg/bloomgateway/processor.go, pkg/bloomgateway/worker.go, pkg/storage/bloom/v1/bounds.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/client_test.go, pkg/storage/stores/shipper/bloomshipper/interval.go, pkg/storage/stores/shipper/bloomshipper/interval_test.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go, pkg/storage/stores/shipper/bloomshipper/store.go
~~Even though it is mainly used by the bloom shipper and bloom gateway, it should reside next to the FingerprintBounds, which has similar characteristics and utility functions.~~
Update:
I reverted moving the struct, but kept the utility functions.
=> (chore) Bloom shipper: Extend `Interval` struct with utility functions

production/helm/loki/templates/compactor/deployment-compactor.yaml, production/helm/loki/templates/compactor/service-compactor.yaml, production/helm/loki/templates/compactor/statefulset-compactor.yaml, production/helm/loki/templates/distributor/deployment-distributor.yaml, production/helm/loki/templates/distributor/service-distributor.yaml, production/helm/loki/templates/gateway/deployment-gateway.yaml, production/helm/loki/templates/gateway/service-gateway.yaml, production/helm/loki/templates/index-gateway/service-index-gateway-headless.yaml, production/helm/loki/templates/index-gateway/service-index-gateway.yaml, production/helm/loki/templates/index-gateway/statefulset-index-gateway.yaml, production/helm/loki/templates/ingester/deployment-ingester.yaml, production/helm/loki/templates/ingester/service-ingester-headless.yaml, production/helm/loki/templates/ingester/service-ingester.yaml, production/helm/loki/templates/ingester/statefulset-ingester.yaml, production/helm/loki/templates/querier/deployment-querier.yaml, production/helm/loki/templates/querier/service-querier-headless.yaml, production/helm/loki/templates/querier/service-querier.yaml, production/helm/loki/templates/querier/statefulset-querier.yaml, production/helm/loki/templates/query-frontend/deployment-query-frontend.yaml, production/helm/loki/templates/query-frontend/service-query-frontend-headless.yaml, production/helm/loki/templates/query-frontend/service-query-frontend.yaml, production/helm/loki/templates/query-scheduler/deployment-query-scheduler.yaml, production/helm/loki/templates/query-scheduler/service-query-scheduler.yaml, production/helm/loki/templates/ruler/deployment-ruler.yaml, production/helm/loki/templates/ruler/service-ruler.yaml, production/helm/loki/templates/ruler/statefulset-ruler.yaml
Components were expecting the port name to be `http` instead of `http-metrics`.
N/A
=> Helm: Fix http port name

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/backend/statefulset-backend.yaml, production/helm/loki/templates/read/statefulset-read.yaml, production/helm/loki/templates/single-binary/statefulset.yaml
Remove trailing tab character in helm templates
Fixes #11385
**Checklist**
=> Remove trailing tab character in helm templates

docs/sources/configure/_index.md, docs/sources/send-data/otel/_index.md, pkg/loghttp/push/otlp_config.go, pkg/loghttp/push/otlp_config_test.go, tools/doc-generator/parse/parser.go, tools/doc-generator/parse/root_blocks.go
In PR #11143 we added support for per tenant otlp config. This PR adds the relevant documentation to explain how the config looks and works.
**Checklist**
=> otlp: add docs for per tenant otlp config

pkg/storage/bloom/v1/block.go, pkg/storage/bloom/v1/bloom_tokenizer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/storage/bloom/v1/fuse.go, pkg/storage/bloom/v1/fuse_test.go, pkg/storage/bloom/v1/test_util.go, pkg/storage/bloom/v1/tokenizer_test.go
This PR fixes the block querier to correctly test blooms for chunks. Before this PR, for each chunk we were checking the same set of search terms against the bloom. Therefore, we were not filtering chunks, but only series. This PR uses the chunk ref as a prefix for the search term. 
**Checklist**
=> Correctly check chunks in bloom block querier.

pkg/logql/quantile_over_time_sketch.go, pkg/logql/quantile_over_time_sketch_test.go, pkg/logql/sketch/quantile.go
This should reduce our memory usage for our quantile sketches by about half, at least in our current situation we'll OOM after ~160-170 minutes instead of ~90 :cry:
=> quantile sharding: switch to ddsketch sparse constructor and remove quantile vector pooling in Join function

pkg/storage/bloom/v1/archive.go, pkg/storage/bloom/v1/archive_test.go, pkg/storage/bloom/v1/block_writer.go, pkg/storage/bloom/v1/bloom_tokenizer_test.go, pkg/storage/bloom/v1/bounds_test.go, pkg/storage/bloom/v1/builder_test.go, pkg/storage/bloom/v1/dedupe_test.go, pkg/storage/bloom/v1/fuse_test.go, pkg/storage/bloom/v1/index_test.go, pkg/storage/bloom/v1/iter_test.go, pkg/storage/bloom/v1/merge_test.go, pkg/storage/bloom/v1/reader.go, pkg/storage/bloom/v1/tokenizer_test.go, pkg/storage/bloom/v1/util_test.go
Moves the archival code to an interface based approach, removing the explicit fs dependency. We can now implement with in-memory solutions. Also refactors to use a tar-file iterator and marks tests as parallelizable.
=> [Blooms] Stateless archiving

docs/sources/operations/query-fairness/_index.md
The rest of the doc mentions the correct header name.
=> Use correct header name in docs for query fairness in scheduler

pkg/bloomgateway/processor_test.go, pkg/storage/stores/shipper/bloomshipper/store.go
For certain operations, we want direct access to the `BloomClient`. Since every schema period has its own client, the `Client()` function accepts a `model.Timestamp` for which the client should be returned.
The function may return an error, if no client for the given time could be found.
=> Extend BloomStore with `Client(model.Time)` function

pkg/bloomcompactor/controller.go, pkg/bloomcompactor/spec.go, pkg/bloomcompactor/spec_test.go, pkg/bloomgateway/processor.go, pkg/bloomgateway/processor_test.go, pkg/bloomgateway/util_test.go, pkg/storage/stores/shipper/bloomshipper/cache.go, pkg/storage/stores/shipper/bloomshipper/cache_test.go, pkg/storage/stores/shipper/bloomshipper/fetcher.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/store.go, pkg/storage/stores/shipper/bloomshipper/store_test.go
In order to encapsulate the reference counting on the `BlockDirectory`, the `BloomStore` now returns a slice of `*CloseableBlockQuerier` instead of the directory itself.
The caller is responsible for closing the returned querier in order to release the reader resource and decrement the ref counter.
The PR also renames `ClosableBlockQuerier` to `CloseableBlockQuerier`.
=> BloomStore: Change signature of `FetchBlocks()` to return `[]*CloseableBlockQuerier`

docs/sources/get-started/labels/structured-metadata.md, docs/sources/release-notes/v2-9.md, docs/sources/send-data/otel/_index.md
Updating the docs in advance of OTEL release to remove "experimental" notes.
Also restructured release notes so that most recent content is first.
=> Update docs to support OTEL GA

docs/sources/get-started/labels/structured-metadata.md, docs/sources/release-notes/v2-9.md
Manual backport for two of three files updated in #11858.
Note that the third file updated by #11858 has not been published to the 2.9 release, and thus is not part of this backport.
=> Manual backport for the relevant parts of #11858

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/processor.go, pkg/bloomgateway/processor_test.go, pkg/bloomgateway/util_test.go, pkg/bloomgateway/worker.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go
This PR replaces the iteration of the bloomgateway worker with the code encapsulated in the previously established processor.
Since the processor only relies on the BloomStore, rather than on the BloomShipper, the PR also removes unused code from the shipper.
Up  next is integrating metrics into the processor.
=> Bloom gateway: Integrate processor into worker

docs/sources/configure/_index.md, pkg/bloomgateway/bloomgateway.go, pkg/logqlmodel/stats/context.go, pkg/storage/chunk/cache/embeddedcache.go, pkg/storage/stores/shipper/bloomshipper/cache.go, pkg/storage/stores/shipper/bloomshipper/config/config.go, pkg/storage/stores/shipper/bloomshipper/fetcher.go, pkg/storage/stores/shipper/bloomshipper/store.go, pkg/storage/stores/shipper/bloomshipper/store_test.go
Until now, the cache configuration in the bloom gateway did not intialize the cache.
This PR wires the config with the actual implementation and passes them to the bloom store.
=> Bloom gateway: Wire up cache config with implementation

.drone/drone.jsonnet, .drone/drone.yml, pkg/storage/stores/shipper/bloomshipper/shipper_test.go
Recent changes causing compilation failures -- this fixes type signatures after refactoring.
Also removes test coverage comparisons because they prevent us from fixing `main`
=> fix type errors after introduction of typedcache into bloomshipper

pkg/bloomgateway/processor.go, pkg/bloomgateway/processor_test.go, pkg/bloomgateway/worker.go
Update metrics for bloomgatway worker to improve observability of the query path.
```
dequeueDuration   : Summary
processDuration   : Summary
metasFetched      : Summary
blocksFetched     : Summary
tasksDequeued     : Counter
tasksProcessed    : Counter
blockQueryLatency : Histogram
```
=> Update metrics of bloomgateway worker

pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/util_test.go, pkg/storage/bloom/v1/archive_test.go, pkg/storage/bloom/v1/builder_test.go, pkg/storage/bloom/v1/fuse_test.go, pkg/storage/bloom/v1/test_util.go
The utility correctly populated the blooms, but returned incorrect values for `keys`, which are the indexed keys of a bloom.
The values need to be copied when appending to the result slice.
https://github.com/grafana/loki/pull/11909/files#diff-8aa1bba39beb779ea35f85fa9309b10d08637a2f6527f9fd4b26f59db79802e8L80
Additionally, the source for the tokenizer changed to be avoid duplicate keys that are present in all blooms.
=> Fix test utility function `MkBasicSeriesWithBlooms`

pkg/bloomgateway/worker.go
Even though the main information from these metrics are the `sum` and the `count`, histograms offer the ability to aggregate them.
Follow up to https://github.com/grafana/loki/pull/11907
Ref: https://prometheus.io/docs/practices/histograms/#quantiles
=> Bloom gateway: Change Summary metrics to Histogram metrics

pkg/querier/worker/processor_manager.go
A data race existed with the workerID variable, as it could be modified by multiple goroutines.
Relates to: https://github.com/grafana/loki/issues/8586
--
Before fix:
```
go test -count=1 -race ./pkg/querier/worker
Read at 0x00c000494108 by goroutine 229:
github.com/grafana/loki/pkg/querier/worker.(*processorManager).concurrency.func1()
/Users/progers/dev/src/github.com/grafana/loki/pkg/querier/worker/processor_manager.go:81 +0x118
Previous write at 0x00c000494108 by goroutine 222:
github.com/grafana/loki/pkg/querier/worker.(*processorManager).concurrency()
/Users/progers/dev/src/github.com/grafana/loki/pkg/querier/worker/processor_manager.go:70 +0x108
github.com/grafana/loki/pkg/querier/worker.(*querierWorker).r …
```
=> Cleanup data race associated with workerID var

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/spec.go, pkg/bloomcompactor/spec_test.go
While reviewing https://github.com/grafana/loki/pull/11919, I figured it'd be nice to make `batchedLoader` generic so we can reuse it's logic. This let me test it easier and remove a lot of now-unnecessary adapter code (interfaces, types)
=> makes batchedLoader generic + removes unnecessary interfaces & adapters

pkg/querier/http.go, pkg/querier/tail.go, pkg/querier/tail_test.go
This addresses the data race present on the `t.stopped` variable in `tail.go`.
```
Write at 0x00c00098b198 by goroutine 568:
github.com/grafana/loki/pkg/querier.(*Tailer).close()
/Users/progers/dev/src/github.com/grafana/loki/pkg/querier/tail.go:272 +0x104
github.com/grafana/loki/pkg/querier.TestTailer.func7.2()
/Users/progers/dev/src/github.com/grafana/loki/pkg/querier/tail_test.go:169 +0x34
runtime.deferreturn()
/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/panic.go:477 +0x34
testing.tRunner()
/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1595 +0x1b0
testing.(*T).Run.func1()
/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1648 +0x40
Previous read at 0x00c00098b198 by …
```
=> Add mutex for t.stopped to prevent data races

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/controller.go, pkg/bloomcompactor/controller_test.go, pkg/bloomgateway/util_test.go, pkg/storage/bloom/v1/bounds.go, pkg/storage/bloom/v1/bounds_test.go, pkg/storage/bloom/v1/fuse_test.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/client_test.go, pkg/storage/stores/shipper/bloomshipper/fetcher_test.go, pkg/storage/stores/shipper/bloomshipper/shipper.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go, pkg/storage/stores/shipper/bloomshipper/store_test.go
Building of `meta.jsons` and removal of old `meta.jsons` + bloom blocks in the `bloomcompactor`
=> meta & removal support for bloom compaction

pkg/bloomutils/ring.go
No need to sort tokens which are already sorted in the `dskit/ring` pkg.
=> [blooms] Remove unnecessary token sorting

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/bloomutils/ring.go, pkg/bloomutils/ring_test.go
This PR replaces min/max token fields with a `TokenRange` field that uses the `Range[uint32]` type.
The `Range[uint32]` uses similar semantics as the `FingerprintBounds` we use for fingerprint ranges.
=> Replace min/max token with `TokenRange` in bloom ring utilities

docs/sources/release-notes/cadence.md
Replaces #11923.  For some reason I can't push updates to that PR, so opening a new one.
Fixes broken links in https://grafana.com/docs/loki/latest/release-notes/cadence/
=> Fixing broken links

production/helm/loki/CHANGELOG.md, production/helm/loki/Chart.yaml, production/helm/loki/README.md, production/helm/loki/templates/ciliumnetworkpolicy.yaml
This PR fixes the `ciliumnetworkpolicy` template file in the chart because in its current state, the ciliumNetworkPolicies are wrong. The `toPorts` field was not written properly and this was leading to network issues when deployed.
**Checklist**
=> Helm: fix ciliumNetworkPolicy template in the chart

pkg/distributor/distributor.go
This PR reduces the `ringAutoForgetUnhealthyPeriods` for Distributors from 10->2. The current default heartbeat timeout is 1 minute. This change means that we will forget unhealthy distributors from the ring 5x faster, matching the current setting for Rulers.
N/A
N/A
**Checklist**
=> Reduce Distributor auto-forget unhealthy cycles from 10->2

pkg/distributor/distributor.go
This PR cherry-picks cad4b8e onto `k189` to reduce the # of cycles needed to auto-forget unhealthy distributors.
N/A
N/A
**Checklist**
=> Reduce Distributor auto-forget unhealthy cycles from 10->2 (#11935)

pkg/storage/stores/shipper/indexshipper/tsdb/identifier.go, pkg/storage/stores/shipper/indexshipper/tsdb/identifier_test.go
TSDB parsing code previously used `ParseInt` which accounts for signed integers, but we use unsigned integers in checksums. This PR fixes this mismatch and will allow us to correctly parse the entire keyspace.
=> tsdb parsing handles uint

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/controller.go, pkg/bloomcompactor/metrics.go, pkg/storage/bloom/v1/util.go, pkg/storage/bloom/v1/util_test.go
This PR adds new metrics to the bloom-compactor:
- `loki_bloomcompactor_compactions_started`: Total number of compactions started
- `loki_bloomcompactor_compactions_completed`: Total number of compactions completed. With `status` (`success`, `failure`).
- `loki_bloomcompactor_compactions_time_seconds`: Time spent during a compaction cycle. With `status` (`success`, `failure`).
- `loki_bloomcompactor_tenants_discovered`: Number of tenants discovered during the current compaction run.
- `loki_bloomcompactor_tenants_skipped`: Number of tenants owned by this instance.
- `loki_bloomcompactor_tenants_skipped`: Number of tenants skipped since they are not owned by this instance.
- `loki_bloomcompactor_tenants_started`: Number of tenants started to process …
=> (Blooms) Add metrics to compactor

pkg/bloomcompactor/batch.go
previously would panic when the previous block list was nil (first iteration)
=> correctly set block iter when no overlapping blocks are found

pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/bloomutils/ring.go
This PR re-implements the fingerprint partitioning on the bloom gateway client using `slices.BinarySearchFunc`.
Benchmark results from `sort.Search` (old) vs. `slices.BinarySearchFunc` (new):
```
$ benchstat old.txt new.txt
goos: linux
goarch: amd64
pkg: github.com/grafana/loki/pkg/bloomgateway
│   old.txt    │              new.txt               │
│    sec/op    │   sec/op     vs base               │
PartitionFingerprintsByAddresses-8   18.75µ ± 70%   16.94µ ± 2%  -9.68% (p=0.000 n=10)
│   old.txt    │             new.txt              │
│     B/op     │     B/op      vs base            │
PartitionFingerprintsByAddresses-8   18.69Ki ± 0%   18.69Ki ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
│ …
```
=> (chore) Bloom gateway: Improve fingerprint partitioning in client

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/controller.go, pkg/bloomcompactor/tsdb.go, pkg/bloomgateway/util_test.go, pkg/storage/config/schema_config.go
Before this PR, bloom blocks and metas were written to `bloom/<day>/<tenant>...`, but the gateway expects it to be at `bloom/<index prefix>_<day>/<tenant>`. This PR adds the index prefix to the path. 
**Checklist**
=> Use TSDB index prefix on blooms directory

pkg/bloomgateway/processor.go, pkg/bloomgateway/util.go, pkg/bloomgateway/util_test.go
`tasksForBlocks` and `boundedTasks` are identical structs. The former was introduced when rewriting query logic in the `processor.go` file.
This PR removes the duplicates and renames it to `blockWithTasks`.
`partition` and `partitionFingerprintRange` are identical functions, for the same reason as the structs mentioned above.
This PR removes the duplicates and renames it to `partitionTasks`. The test case uses the remaining function.
=> (chore) Cleanup duplicate functions/strucs in bloomgateway package

pkg/bloomgateway/bloomgateway.go, pkg/bloomgateway/bloomgateway_test.go, pkg/bloomgateway/querier.go, pkg/bloomgateway/worker.go
See individual commit messages for details.
=> Various bloom gateway instrumentation changes

pkg/bloomgateway/processor.go
Increasing the correct metric with amount of fetched blocks.
=> Bloom gateway: Fix metric for fetched blocks

pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/bloomutils/ring.go
In order to compare the keyspace from the bloom gateway's ring with the fingerprints, they need to use the same keyspace.
The ring, however, uses tokens within a `uint32` keyspace, whereas the fingerprints use a `uint64` keyspace.
Therefore the ranges from the ring tokens need to be mapped into the `uint64` keyspace. This is done bit-shifting the Min value 32 bits to the left and the Max value 32 bits to the left plus adding `(1<<32)-1` to "fill" the remaining values up to the next Min value.
The structs used to combined ring instance information and token/fingerprint ranges are yet to be simplified. However, this is not goal of this PR.
=> Map ring token keyspace (uint32) into fingerprint keyspace (uint64)

pkg/logql/metrics.go
=> Remove unnecessary ingester fields from metrics.go which only work in single binary

pkg/bloomcompactor/batch.go, pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/bloomcompactor_test.go, pkg/bloomutils/ring.go, pkg/bloomutils/ring_test.go, pkg/loki/modules.go
Moves bloom ring ownership back to a traditional consistent hashing mode via tokens. Copies/adapts some dskit ring code where necessary because `<ReadRing>.GetTokenRangesForInstance()` does not currently support non zone-aware topologies.
This should also break up the bloom compactor's unit of work by making metas for smaller ranges which are now roughly `(keyspace_range / num_replicas / tokens_per_replica)`. With the currently hardcoded `10` tokens per replica, we'll build about 10 times more metas than prior.
Also includes a small change to minimize metric construction during chunk iteration where it's not needed, although this may need some more extensive refactoring for more performance benefits later.
=> [Blooms] Consistent hashing via tokens for bloomcompactor

pkg/logql/downstream_test.go, pkg/logql/engine.go, pkg/logql/quantile_over_time_sketch.go, pkg/logql/quantile_over_time_sketch_test.go, pkg/logql/sketch/quantile.go
**EDIT: I also found the bug that was causing us to OOM when executing instant queries, see the 2nd commit**
This should reduce the memory allocated by the vector iteration by at least 25% but as much as ~80%. The quantile vector iteration accounts for at least 15% of all in use space last time I tested (and during that time queriers we're OOM'ing as a result of quantile sharding). 
However, with the usage of this alternate store type we give up some amount of relative accuracy guarantees for _lower_ quantiles. From their readme:
```
We also provide implementations, returned by LogCollapsingLowestDenseDDSketch(relativeAccuracy, maxNumBins) and LogCollapsingHighestDenseDDSketch(relativeAccuracy, maxNumBins), where the q-quantile will be accurate up to the specified relative error for q …
```
=> quantile sharding; fix bug related to # of steps (instant query mem usage) and use CollapsingLowestDense store for ddsketch

pkg/logql/downstream_test.go, pkg/logql/engine.go, pkg/logql/quantile_over_time_sketch.go, pkg/logql/quantile_over_time_sketch_test.go, pkg/logql/sketch/quantile.go
instant queries for sharded probabilistic quantiles were incorrectly executing over all data, forever, because we didn't include an exit clause for instant queries
this backports the fix for this issue into k190
=> backport #11905 to k190

pkg/storage/stores/shipper/bloomshipper/store_test.go
The support for table prefixes was introduced with https://github.com/grafana/loki/pull/11977
=> test: Use table prefix in bloomstore tests

pkg/storage/stores/shipper/bloomshipper/cache_test.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/compress_utils.go, pkg/storage/stores/shipper/bloomshipper/compress_utils_test.go
Instead of writing the data to a temporary file, the reader from the object client can be used directly to feed to the `v1.UnTarGz()` function that extracts the zipped contents into a target directory.
=> fix: Extract block directory directly from gzipped tar reader

pkg/chunkenc/pool.go, pkg/storage/bloom/v1/bloom.go, pkg/storage/bloom/v1/bloom_querier.go
releases data to correct pools in correct locations + improves SnappyPool to release reader refs prior to putting to Pool
Signed-off-by: Owen Diehl <ow.diehl@gmail.com>
=> fix(blooms): race condition in `BloomPageDecoder`

pkg/distributor/distributor_test.go
Before this PR:
```
Read at 0x00c000b44348 by goroutine 330:
github.com/grafana/loki/pkg/distributor.Test_IncrementTimestamp.func1()
/Users/progers/dev/src/github.com/grafana/loki/pkg/distributor/distributor_test.go:399 +0x170
testing.tRunner()
/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1595 +0x1b0
testing.(*T).Run.func1()
/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1648 +0x40
Previous write at 0x00c000b44348 by goroutine 372:
github.com/grafana/loki/pkg/distributor.(*mockIngester).Push()
/Users/progers/dev/src/github.com/grafana/loki/pkg/distributor/distributor_test.go:1230 +0x184
github.com/grafana/loki/pkg/distributor.(*Distributor).sendStreamsErr() …
```
=> test: Finish sync work for mockIngester.pushed var

pkg/bloomcompactor/bloomcompactor.go, pkg/bloomcompactor/bloomcompactor_test.go, pkg/bloomgateway/client.go, pkg/bloomgateway/client_test.go, pkg/bloomutils/ring.go, pkg/bloomutils/ring_test.go
Use the recently introduced `tokenRangesForInstance()` function to determine the the ranges for each replication set.
For this purpose, the function moves into the `bloomutils` packages.
This PR eliminates the structs `addrsWithBounds` and `instanceWithFingerprints` (which had somewhat similar usage) and unifies them into `rsWithRanges` that holds both the fingerprint ranges and the assigned GroupedChunkRefs.
=> refactor: Simplify fingerprint partitioning in bloom gateway client

pkg/storage/stores/shipper/bloomshipper/cache_test.go, pkg/storage/stores/shipper/bloomshipper/client.go, pkg/storage/stores/shipper/bloomshipper/compress_utils.go, pkg/storage/stores/shipper/bloomshipper/compress_utils_test.go, pkg/storage/stores/shipper/bloomshipper/fetcher.go, pkg/storage/stores/shipper/bloomshipper/fetcher_test.go
This PR contains two changes:
1) Extracting the block without an intermediate temp file.
The commit is cherry-picked from https://github.com/grafana/loki/pull/12021, but that PR got merged into the wrong branch :see_no_evil: 
2) Strip `.tar.gz` suffix from block file when extracting it into a directory.
=> chore(blooms): Improve how block directory is extracted

pkg/bloomgateway/bloomgateway_test.go, pkg/loki/config_wrapper.go, pkg/loki/config_wrapper_test.go, pkg/loki/modules_test.go, pkg/storage/chunk/client/util/util.go, pkg/storage/stores/shipper/bloomshipper/shipper_test.go, pkg/storage/stores/shipper/bloomshipper/store.go, pkg/storage/stores/shipper/bloomshipper/store_test.go
Fail startup if directory does not exist or there are not enough permissions. This prevents the bloomstore to fail later in the process once it tries to download and extract blocks.
=> fix: Ensure working dir for bloomstore exists
